### PR TITLE
NIFI-13108 Update a variety of dependencies

### PR DESCRIPTION
**Pull request by joewitt**
# Summary

[NIFI-13108](https://issues.apache.org/jira/browse/NIFI-13108)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### UI Contributions

- [ ] NiFi is modernizing its UI. Any contributions that update the [current UI](https://github.com/apache/nifi/tree/main/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui) also need to be implemented in the [new UI](https://github.com/apache/nifi/tree/main/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi).  

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — COMMENTED** [review]
Thanks for the incremental upgrades @joewitt.

None of the updates appear introduce notable changes, however, two attempts to run the integration tests resulted in failures. Unfortunately, there appears to be a logging configuration problem resulting in an extremely large number of debug log messages for the `PeerChannel` class. This may need to be addressed separately, but for now, it appears to be obscuring the failure. The integration tests pass on the current main branch, so unless we can confirm that the failures are intermittent on GitHub, it appears that one of these updates could have introduced an unexpected change.

**Comment by joewitt** [comment]
@exceptionfactory Yeah that is an ultra bummer because i run the same integration tests locally and they work fine. I'll run them again though and see if the same log info comes out.  I noticed what you're talking about as well.  Will try to run it down

**Comment by joewitt** [comment]
have noticed a good bit of failures on the windows build as well with something related to the otel stuff.

**Comment by joewitt** [comment]
the wild log output is found in at least nifi-framework-core integration tests.  And it is due to

SLF4J(W): Class path contains multiple SLF4J providers.
SLF4J(W): Found provider [ch.qos.logback.classic.spi.LogbackServiceProvider@7c24b813]
SLF4J(W): Found provider [org.slf4j.simple.SimpleServiceProvider@2c35e847]
SLF4J(W): See https://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J(I): Actual provider is of type [ch.qos.logback.classic.spi.LogbackServiceProvider@7c24b813]

This stems from the fact that we have in our lib (and now in the nifi-bom) logback-classic/logback-core AND there is a test dependency in the root pom on slf4j-simple.   I dont know why we need/want the slf4j-simple so am looking into that.

**Comment by joewitt** [comment]
Adjusted nifi-bom to remove logback-classic and logback-core from the dependency list even as provided as it means test runs have both slf4j-simple and logback-classic/core.  The nifi-bom now is listing things which we are ok with components having a dependency on wheras things like logback-classic/core are really meant as runtime dependencies anyway.

Might add these things back into the nifi-bom but mark them as 'runtime' instead of provided to better articulate this intent.

**Comment by joewitt** [comment]
@exceptionfactory This changeset should do it.  Hilariously reducing the number of log impls changes the behavior of aws-processors test.  I had to change that in NIFI-12998 but now that it is back to one the assertions are different.  I didn't look into why but that is...funny.

The root of the adjustment here is we took logback-classic and logback-core out out of the dependency set (still in dep mgmt) of nifi-bom.  This makes sense given we dont want things actually having compile time deps on them anyway.  I did mark them as 'runtime' scope instead of provided.  Meanwhile the nifi-py4j-bridge DOES have a direct code based requirement for logback-classic (and thus core).  This seems undesirable but I didn't look into the full story there and instead just explained this and marked it as provided scope for that one module.

Log output is dramatically reduced now thanks to the default behavior of test scoped slf4j-simple.

Anyway this should be in much better shape.  The integration tests seem fairly flakey in multiple local runs but they are able to pass most of the time.  And now we should see why it fails instead of being buried in noisy logs.

**Comment by joewitt** [comment]
grrr.  Need to clean these up...

❯ find . -type f | grep \\.jar | grep logback
./nar/framework/nifi-framework-nar-2.0.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/logback-core-1.5.6.jar
./nar/extensions/nifi-server-nar-2.0.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/logback-core-1.5.6.jar
./nar/extensions/nifi-framework-kubernetes-nar-2.0.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/logback-core-1.5.6.jar

**Comment by pvillard31** [comment]
@joewitt - it feels like some of the dep upgrades included in that PR could also apply to NiFi 1.26 - are you planning for a PR that would apply to 1.x and should I wait for this before kicking off the NiFi 1.26 RC?

**Comment by joewitt** [comment]
The change-set for the main branch is ready to go and looks good.

In general I do not plan to make hygiene updates on the 1.x line at this point.  The dependency management there is substantially less certain than it is now on the 2/x main line post NIFI-12998 and various related JIRAs which reduced build size/etc...  But some of these should be safe-ish and I'll flag those and put up a different JIRA and PR for it.

**Comment by joewitt** [comment]
@pvillard31 For the 1.x line i put together https://issues.apache.org/jira/browse/NIFI-13131.  This *should be* safe.  Full clean build and a basic runs suggests so.

**Review by exceptionfactory — APPROVED** [review]
Thanks for resolving the logging issues @joewitt, the latest set of updates looks good. +1 merging

**Pull request closed without merging**
