### PR TITLE
NIFI-9773 Refactor nifi-system-tests using JUnit 5

### PR DESCRIPTION
**Pull request by exceptionfactory**
#### Description of PR

NIFI-9773 Refactors the `nifi-system-tests` module to use JUnit 5. The upgrade involved refactoring of the JUnit 4 `TestWatcher` in `NiFiSystemIT` to a new `TroubleshootingTestWatcher` implementation applied using the JUnit 5 `ExtendsWith` annotation.

Additional changes include enabling the GitHub `system-tests` workflow for push and pull request operations that include changes to the `nifi-system-tests` path.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [X] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [X] Have you written or updated unit tests to verify your changes?
- [X] Have you verified that the full build is successful on JDK 8?
- [X] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by MikeThomsen** [comment]
```
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 319.671 s <<< FAILURE! - in org.apache.nifi.tests.system.pg.BatchFlowBetweenGroupsIT
Error:  org.apache.nifi.tests.system.pg.BatchFlowBetweenGroupsIT.testSingleConcurrencyAndBatchOutputToBatchInputOutput  Time elapsed: 317.629 s  <<< ERROR!
java.util.concurrent.TimeoutException: testSingleConcurrencyAndBatchOutputToBatchInputOutput() timed out after 5 minutes
```

Looks like you need to up the timeout.

**Comment by exceptionfactory** [comment]
> ```
> Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 319.671 s <<< FAILURE! - in org.apache.nifi.tests.system.pg.BatchFlowBetweenGroupsIT
> Error:  org.apache.nifi.tests.system.pg.BatchFlowBetweenGroupsIT.testSingleConcurrencyAndBatchOutputToBatchInputOutput  Time elapsed: 317.629 s  <<< ERROR!
> java.util.concurrent.TimeoutException: testSingleConcurrencyAndBatchOutputToBatchInputOutput() timed out after 5 minutes
> ```
> 
> Looks like you need to up the timeout.

Thanks for the feedback. The default timeout is five minutes for all tests, and this is generally sufficient. I have still observed sporadic time outs due to some conditions not being handled properly. I restarted the Ubuntu Java 11 system-tests job for now, but separate work may be necessary to track down the source of that particular problem.

**Comment by MikeThomsen** [comment]
Fair enough. I see green. That's good enough for me.

**Comment by MikeThomsen** [comment]
Will review tonight or tomorrow morning, as time permits.

**Review by MikeThomsen — APPROVED** [review]

**Pull request closed without merging**
