### PR TITLE
Updating ReportingTasks to use ComponentLogger instead of creating Controller level bulletins

### PR DESCRIPTION
**Pull request by mcgilman**
NIFI-2595:
- Updating ReportingTasks to use ComponentLogger instead of creating Controller level bulletins.
- Making the bulletin responses consistent in that all bulletins will be included but in redacted form as appropriate.

### CODE REVIEW

**Comment by mcgilman** [comment]
Appears to contain a failing test... Will address

**Comment by mcgilman** [comment]
Updated PR to address failing unit test

**Comment by bbende** [comment]
Reviewing...

**Comment by bbende** [comment]
Looks good, verified that I can see the controller level bulletins when I have access to the reporting task, and can't when I remove access, will merge to master

**Pull request closed without merging**
