### PR TITLE
NIFI-6368: Avro logical decimal type with precision and scale

### PR DESCRIPTION
**Pull request by matthew-formosa-gig**
**Description of PR**

Controller services such as the JsonRecordSetWriter do no take into account the precision and scale in the case of Avro logical decimal types. While this may not be classified as a bug since the output is Json and not Avro, this improvement should help eliminate any misunderstandings between the different serialisations.

This should also improve functionality of other processors making use of such utils.

In order to streamline the review of the contribution we ask you to ensure the following steps have been taken:

### For all changes:

- [X]  Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [X]  Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X]  Has your PR been rebased against the latest commit within the target branch (typically master)?

- [X]  Is your initial contribution a single, squashed commit? Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not squash or use --force when pushing to allow for clean monitoring of changes.

### For code changes:

- [X]  Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?

- [X]  Have you written or updated unit tests to verify your changes?

### CODE REVIEW

**Comment by bbende** [comment]
Hi @matthew-formosa-gig , thanks for the contribution!

I noticed there is another effort related to decimal support here:
https://github.com/apache/nifi/pull/3343

Was wondering if these are essentially trying to achieve the same thing, or if there are differences. I haven't really looked into either of them very closely, but just wanted to bring it to your attention.

**Comment by matthew-formosa-gig** [comment]
Hi @bbende, thanks for bringing that PR to my attention. 

Indeed we are trying to achieve the same thing. I will close off this PR and leave my comments on #3343.

**Comment by bbende** [comment]
Sounds good.  If your work is closer to ready then by all means feel free to leave your PR open, I just wanted to make sure you were aware of it.

**Comment by matthew-formosa-gig** [comment]
I believe the other PR is more comprehensive and still close to ready despite the feedback I just gave. I can still work with my custom NAR files until the PR is merged so I am not in a particular hurry.

**Pull request closed without merging**
