### PR TITLE
NIFI-4731

### PR DESCRIPTION
**Pull request by nologic**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by nologic** [comment]
@MikeThomsen seems like a lot of violations, what's the best way to clear these up?

**Comment by MikeThomsen** [comment]
It's whack-a-mole. To see many/all of them at once do this from the source root:

`mvn clean install -Pcontrib-check :nifi-gcp-processors`

(I didn't look closely. I'm assuming `nifi-gcp-processors` was the maven module that was failing. It needs to be the failing maven module's maven name + `:` at the start to tell Maven to only build that one module w/ the full contrib-check profile)

Then you just keep changing until you make stylecheck happy.

**Comment by joewitt** [comment]
It is 164 violations but all very easy things to fix.  It is possible there was some newline issues in generating the PR or just some IDE formatting thing can be run.  But it should be super easy to fixup

**Comment by nologic** [comment]
cool, all checks have passed. Is there anything else you need need before this thing gets scheduled for a merge?

**Comment by joewitt** [comment]
please address the author tags.

**Comment by lsh-0** [comment]
hi guys - I've just introduced NiFi at work, [found and built this](https://github.com/sand0id/nifi-bigquery-bundle), discovered it's many limitations and was about to rewrite it when I found this ticket!

May I ask what is currently blocking it?

**Comment by MikeThomsen** [comment]
> May I ask what is currently blocking it?

@nologic appears to have not addressed all of the review feedback.

@joewitt I can rebase and address the author tags. If the tests run, I can merge myself. You want to do that?

**Comment by danieljimenez** [comment]
There are two other PRs that supersede this one.

**Comment by lsh-0** [comment]
I've just taken a look at the other two tickets and it looks like #3019 is the most recent one but is lacking the conversation/ticket history. As an outsider I can see that's three open tickets for one feature with a chain like #2420 -> #2682 -> #3019 .

I think at the very least this ticket (#2420) can be closed as it's quite definitely superceded.

**Pull request closed without merging**
