### PR TITLE
NIFI-9354 Remove material-design-icons from Registry

### PR DESCRIPTION
**Pull request by exceptionfactory**
#### Description of PR

NIFI-9354 Removes the `material-design-icons` dependency from `package.json` in `nifi-registry-web-ui`.

The `nifi-registry-bootstrap.js` imports the Material Design font from the `covalent/core` module, which supports application usage of icons using the Angular `mat-icon` component. The `material-design-icons` dependency is 31 MB compressed and almost 400 MB uncompressed, consisting of over 89,000 files.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [X] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Review by gresockj — APPROVED** [review]
This shaves over a minute off of my 4.5-minute nifi-registry build, and does not affect the appearance of any of the icons in nifi-registry.  Nice find!

+1 from me, however I am going to wait for input from the 1.15.0 release manager, @joewitt, before merging.

**Review by greyp9 — APPROVED** [review]
Works well for me.  This sequence of commands suggests that the omission of this component saves a significant amount of time (~60%) inflating the content and cleaning the content from the previous build.

`mvn -pl :nifi-registry-web-ui clean`
`mvn -pl :nifi-registry-web-ui clean install`

I also used `du` to measure a (~30%) reduction in the footprint of `nifi/nifi-registry/nifi-registry-core/nifi-registry-web-ui/target/` after the build.

Nice work @exceptionfactory !

**Comment by gresockj** [comment]
@scottyaslan how does this change look to you?

**Comment by scottyaslan** [comment]
Nice optimization @exceptionfactory! +1

**Pull request closed without merging**
