### PR TITLE
NIFI-13125: Add view for comparing different versions of registered flows

### PR DESCRIPTION
**Pull request by sardell**
# Summary

[NIFI-13125](https://issues.apache.org/jira/browse/NIFI-13125)

### Testing
1. Start NiFi Registry and create a bucket. Import a flow to that bucket. 
2. Open the controller settings modal in the NiFi UI and add a registry client. Point the url to the NiFi Registry url. 
3. Add a Process Group and import the flow you just created in registry. 
4. Make some changes to the flow (can be as simple as renaming a processor). Right click on the process group and select Version > Commit local changes. Save your changes.
5. Repeat step 4 so you have another set of committed changes (so 3 versions total, though you could do more if you’d like).
6. Right click on the process group and select Version > Change version
7. You’ll see a new icon to the left of the Version column in the versions table (see 1st image below). Click on an icon that isn’t the current version. You should see a modal launch listing the differences between the two versions (see 2nd image below). 
8. Try adjusting the version selection dropdowns. If you compare the same version, you should see a message informing you that there are no differences (see 3rd image below).
9. The filter should apply whatever input it has across the 3 columns (component name, change type, and difference).

Screenshot 2024-07-24 at 4 49 06 PM

Screenshot 2024-07-24 at 4 49 19 PM

Screenshot 2024-07-24 at 4 49 24 PM

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by elcsiga** [comment]
Comparing different versions looks great, version selection and filters are working well 👍 

image

### Comments about version selection, maybe related to this PR:

- for the 1st glance meaning of the 2 numbers in the 2 dropdowns wasn't super clear for me. Maybe a label for the dropdowns would be helpful.
- version selection in the 'Change Version' dialog is a bit more user-friendly, having comments and dates. I'm not sure is there anything to do here without redesigning the header, since there is no place to display additional information in the dropdowns. And user can also use 'Change Version' dialog to select. 
image

### A strange issue:

Workflow 1:

1. Select version 1 in the 'Change Version' dialog
2. Click the 'compare' icon of version 3. Compare dialog will show comparison between 3 and 3. 
image

Workflow 2:

1. Select version 3 in the 'Change Version' dialog
2. Click the 'compare' icon of version 2. Compare dialog will correctly show comparison between 3 and 3
3. Select version 3 in the 'Change Version' dialog  
4. Click the 'compare' icon of version 3. Compare dialog will show comparison between 3 and 3, but with wrong content:
image

**Comment by joewitt** [comment]
I dont see the related pr for this on the 2.x line.  It is important we're not adding features to the 1.x line that are not present on the 2.x line.

**Comment by sardell** [comment]
@joewitt I've created [a Jira](https://issues.apache.org/jira/browse/NIFI-13662) but the work is not quite ready for review yet.   Do you want me to close this PR and reopen once the 2.x PR is ready, or is having the Jira good enough for tracking purposes? I'm fine with either approach. I should have the 2.x PR open very soon.

**Comment by joewitt** [comment]
The key is new feature work should be going to 2x then as desired and review cycles available backported to 1.x. UI cases admittedly tougher.

We should not be introducing capability to 1.x then maybe eventually 2.x though.

**Comment by sardell** [comment]
@joewitt Alright, I'll close this and pursue opening the same feature for 2.x for now.

**Pull request closed without merging**
