### PR TITLE
NIFI-8643: Correcting nifi.cluster.load.balance.address in properties

### PR DESCRIPTION
**Pull request by gresockj**
#### Description of PR

Since the code looks for nifi.cluster.load.balance.address but nifi.cluster.load.balance.host is specified in the documentation and nifi.properties file, the load balancer is always bound to localhost.  This corrects the properties and documentation.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [X] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [X] Have you verified that the full build is successful on JDK 8?
- [X] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [X] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by gresockj** [comment]
Though, looking at the rest of the nifi.properties, *.host appears to be the standard for everything except nifi.cluster.load.balance.address and nifi.cluster.node.address.  Perhaps these two should be renamed to nifi.cluster.load.balance.host and nifi.cluster.node.host.  Thoughts, @markap14, @exceptionfactory?

**Comment by markap14** [comment]
Ha I think `nifi.cluster.node.address` was the property I looked at to ensure the correct naming convention when I created the `nifi.cluster.load.balance.address` :(
Unfortunately, though, I don't think it's a good idea to rename. It could cause a lot of problems and confusion for people upgrading from one version to another. I think it makes more sense to just use 'address' in some places and 'host' in other places.

**Review by exceptionfactory — APPROVED** [review]

**Comment by markap14** [comment]
Honestly, though, @gresockj thinking about this a bit more - this PR updates the docs to match what the code does. I think perhaps we should go the other way. The documentation is all correct about what the property name should be. In the code, we just had a bug that caused it to look at the wrong property name. If we don't update the docs and instead just fix the bug in NiFiProperties, then we remain consistent with using `.host`, which I like. It means anyone who did go ahead and add in the extra property would need to ensure that in 1.14.0 that they do have the correct value for .host, but I think that's fair since the docs are already calling it out.

**Comment by gresockj** [comment]
> Honestly, though, @gresockj thinking about this a bit more - this PR updates the docs to match what the code does. I think perhaps we should go the other way. The documentation is all correct about what the property name should be. In the code, we just had a bug that caused it to look at the wrong property name. If we don't update the docs and instead just fix the bug in NiFiProperties, then we remain consistent with using `.host`, which I like. It means anyone who did go ahead and add in the extra property would need to ensure that in 1.14.0 that they do have the correct value for .host, but I think that's fair since the docs are already calling it out.

I see your point.  I think it makes more sense the way you called out.  Updating the PR.

**Comment by markap14** [comment]
Thanks @gresockj merged to main

**Comment by JensMKofoed** [comment]
Hi
When I typed in a fqdn as the nifi.cluster.load.balance.address is still bind to localhost. I had to type in the IP address or 0.0.0.0.
So the property name address seems to correspond to an actual ip address. If the property name was host I will assume it would be a fqdn.
If I have multiple network interfaces on my nodes, I would select one interface (ip address) to be the network for load balance and another for the remote access UI and S2S.
Using fqdn as host property will not provide you the possibility to select a different network for internal load balance between nodes. Therefore I will go for the address property and specified that it has to be an ip address
Kind Regards
Jens M. Kofoed

**Pull request merged**
