### PR TITLE
NIFI-5612: Support JDBC drivers that return Long for unsigned ints

### PR DESCRIPTION
**Pull request by colindean**
Refactors tests in order to share code repeated in tests and to enable some parameterized testing.

MySQL Connector/J 5.1.x in conjunction with MySQL 5.0.x will return a Long for ResultSet#getObject when the SQL type is an unsigned integer. This change prevents that error from occurring while implementing a more informational exception describing what the failing object's POJO type is in addition to its string value.

---

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root nifi folder?
- [X] Have you written or updated unit tests to verify your changes?
- [ ] ~~If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?~~
- [ ] ~~If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?~~
- [ ] ~~If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?~~
- [ ] ~~If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?~~

### For documentation related changes:
- [ ] ~~Have you ensured that format looks appropriate for the output in which it is rendered?~~

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by colindean** [comment]
The test failure seems to be a timeout from a test unrelated to what I changed but still within the nifi-standard-processors maven component:

```
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.089 s <<< FAILURE! - in org.apache.nifi.processors.standard.TestHandleHttpRequest
[ERROR] testRequestAddedToService(org.apache.nifi.processors.standard.TestHandleHttpRequest)  Time elapsed: 10.01 s  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 10000 milliseconds
	at org.apache.nifi.processors.standard.TestHandleHttpRequest.testRequestAddedToService(TestHandleHttpRequest.java:138)
```

All other tests passed. Is this an intermittent failure?

**Comment by pvillard31** [comment]
Hey @colindean, I'll let @bbende & @mattyb149 have a look on the code but as long as 1 of the 3 Travis builds is green, you're good to go. We have to fix the intermittent issues on the builds but that's not related to your PR.

**Comment by mattyb149** [comment]
Reviewing...

**Comment by colindean** [comment]
@mattyb149 Thoughts?

**Comment by colindean** [comment]
I'll note that I built this NAR and used it for a job running against the production server in which I originally observed the problem. That job did not display the behavior and seems to have retrieved all of the expected data, so I can conclude that this fix does fully resolve the original problem for me.

**Comment by mattyb149** [comment]
+1 LGTM, ran full build with tests, reproduced the issue before applying the PR and verified on MySQL that the issue no longer occurs. Also tried similar data types on Oracle and PostgreSQL. Thanks for the fix (and adding unit tests)! Merging to master

**Comment by colindean** [comment]
Awesome! @mattyb149, where you able to reproduce the bug on other database software/driver combinations? 

Was this behavior unique to MySQL 5.0.x and driver 5.1.x? 

I wasn't able to reproduce it with MSSQL 2012 and JTDS 1.3.1.

**Comment by mattyb149** [comment]
No I couldn't reproduce, Oracle and Postgres don't have native unsigned types (they use contraints/checks). Wanted to try a few DBs/types just in case, seems even with standards (SQL, JDBC) everybody does something different, and a fix for one might break another :P

**Comment by colindean** [comment]
That's fair. I feel like a release is coming up. Looking at the calendar, it seems like it happens in the first two weeks of each quarter. There's a been a lot of commits since 1.7.1! We're OK dropping in a 1.8.0-SNAPSHOT to this one environment but we'd love to include 1.8.0 in our builds as soon as possible. Do you have a feel for when 1.8.0 might be released?

**Comment by alopresto** [comment]
@colindean the releases aren't on a set schedule and are decided by discussion on the dev@nifi.apache.org mailing list, but I think you're right in your feeling that a release is probably coming up soon. This is great work and exciting to get in. Thanks for researching and developing it.

**Pull request closed without merging**
