### PR TITLE
NIFI-4846: AvroTypeUtil to support more input types for logical decimal conversion

### PR DESCRIPTION
**Pull request by ijokarumawak**
## NOTE

This PR is based on #2450 commit to add more capability on top of that. Please review #2450 first. Thank you.

---

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by mattyb149** [comment]
There's a merge conflict now that #2450 is merged, I'm guessing it's because you built this PR with your other commit from 2450 as well. Can you rebase / replace your NIFI-4844 commit with the one from master? Please and thanks :) In the meantime I will cherry-pick the NIFI-4846 commit into master for testing

**Comment by mattyb149** [comment]
+1 LGTM, ran a build with contrib-check and unit tests, also tried with a live NiFi with various schema conversions. Once the rebase has been performed, I will merge this to master. Thanks for the improvement!

**Comment by ijokarumawak** [comment]
@mattyb149 Rebased with the latest master. Thanks!

**Comment by mattyb149** [comment]
Thank you sir, merging to master

**Pull request closed without merging**
