### PR TITLE
NIFI-2919 improved GetFile to fail if target directory is inaccessible

### PR DESCRIPTION
**Pull request by olegz**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by alopresto** [comment]
Reviewing...

**Comment by olegz** [comment]
@alopresto unless you find any major issues that would require me to follow up with more work, would you be able (before merging) to change in _testWithUnwritableDir_ the actual directory to be ```File unreadableDir = new File("target/unwritable");```? Copy/Paste error, otherwise i'll do it.

**Comment by alopresto** [comment]
@olegz No problem.

**Comment by alopresto** [comment]
I made a couple small changes, but otherwise +1. Verified by creating a directory structure as below and verified the positive case succeeded with no error output; the two negative cases caused the expected bulletins and log messages to be generated. 

```
hw12203:/Users/alopresto/Workspace/scratch/pr1147 (master) alopresto
🔓 73s @ 16:03:49 $ ll
total 0
drwxr-xr-x   5 alopresto  staff   170B Oct 19 16:03 ./
drwxr-xr-x  56 alopresto  staff   1.9K Oct 19 16:01 ../
drwxr-xr-x   2 alopresto  staff    68B Oct 19 16:03 regular/
d-wx-wx-wx   2 alopresto  staff    68B Oct 19 16:01 unreadable/
dr-xr-xr-x   2 alopresto  staff    68B Oct 19 16:01 unwritable/
hw12203:/Users/alopresto/Workspace/scratch/pr1147 (master) alopresto
🔓 2s @ 16:03:52 $
```

* Fixed typos in error message ("redable" -> "readable")
* Changed multiline comment to block comment
* Removed unusued imports in test
* Fixed variable names & directory in test as per @olegz 's request above

**Pull request closed without merging**
