### PR TITLE
NIFI-4811 Added two missing entries to the nifi-redis-service-api-nar…

### PR DESCRIPTION
**Pull request by MikeThomsen**
… NOTICE file.

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by joewitt** [comment]
We need to ensure both nars produced have their LICENSE/NOTICE files representing all source/binary artifacts that will be included.  The best way is to look at the content of the nar itself.  I used the maven dependency/compile scope in some cases as well but due to how we use Nars those weren't always reliable.

**Comment by ottobackwards** [comment]
I wonder if we could have the nar maven plugin produce a report....

**Comment by MikeThomsen** [comment]
@ottobackwards I've thought something similar. We could build a big JSON file or folder of JSON files that have the standard verbiage per dependency and then cause a build error if it finds something new.

**Comment by MikeThomsen** [comment]
@joewitt we should be good to go now.

**Pull request closed without merging**
