### PR TITLE
NIFI-6362 - Upgraded com.puppycrawl.tools:checkstyle to 8.18. Made sm…

### PR DESCRIPTION
**Pull request by thenatog**
…all checkstyle changes to nifi-kafka.

Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Enables X functionality; fixes bug NIFI-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by ijokarumawak** [comment]
@thenatog I found more recent check-style version 8.21 has been released while this PR uses 8.18. I personally think that is not a problem as check-style releases pretty often (looks monthly). Just wanted to check before merging it. Thanks!
https://checkstyle.org/releasenotes.html

**Comment by thenatog** [comment]
@ijokarumawak I'm getting an error when I upgrade to 8.21:
"Failed during checkstyle configuration: cannot initialize module TreeWalker - Property 'cacheFile' does not exist, please check the documentation."
I've tried adding this property in a few different places and am still getting the error. I don't know enough about the checkstyle stuff to see what the problem is here.

**Comment by thenatog** [comment]
Figured out that problem. Hitting a few new checkstyle errors so I'll update those soon and push a commit which moves to 8.21.

**Comment by thenatog** [comment]
Submitted another commit which upgrades the maven-checkstyle-plugin and the puppycrawl tool. When this runs it will add a .checkstyleCache file at the root directory which caches the state of checked files.

**Comment by ijokarumawak** [comment]
Confirmed build passes locally, LGMT +1. Merging. Thanks @thenatog !

**Pull request closed without merging**
