### PR TITLE
NIFI-5018

### PR DESCRIPTION
**Pull request by R-Bower**
[NIFI-5018](https://issues.apache.org/jira/browse/NIFI-5018)

I've made some modifications to the Canvas UI that results in a "snap-to-grid" during the canvas element's drag state.  The processor alignment is based on rounding the component's X and Y coordinates during the drag event.  The X and Y values of the canvas elements now shift 8px at a time.  

The size of the following canvas elements were altered, minimally, to ensure even rounding and consistent alignment following drag events:
- process-group
- remote-process-group
- processor
- port

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [x] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [x] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by alopresto** [comment]
Hi. I'm excited to try out this feature. I am concerned however, that changing the component sizes will have serious impacts on user experience, flow versioning & fingerprinting. I think there needs to be substantial testing on these integration points and either change how fingerprinting works, or provide a smooth transition/migration experience. 

In addition, making this an immediate change without a boolean flag to turn it on/off will disrupt many users. I would suggest making both the snap pixel size and the feature itself configurable from nifi.properties. 

Ideally, this would be a per-user setting on a NiFi instance, but that is a large requirement for this feature.

**Comment by R-Bower** [comment]
> Hi. I'm excited to try out this feature. I am concerned however, that changing the component sizes will have serious impacts on user experience, flow versioning & fingerprinting. I think there needs to be substantial testing on these integration points and either change how fingerprinting works, or provide a smooth transition/migration experience.
> 
> In addition, making this an immediate change without a boolean flag to turn it on/off will disrupt many users. I would suggest making both the snap pixel size and the feature itself configurable from nifi.properties.
> 
> Ideally, this would be a per-user setting on a NiFi instance, but that is a large requirement for this feature.

Regarding the altered components:
- Only four are modified.  These are listed above.
- I've ensured that all of the size changes don't restrict or prevent content from displaying.  Canvas layouts update consistently from pre-existing configurations, but I don't have any testing in place to bolster the idea that no/minimal errors will occur from updating.  I've merely updated the JS width/height properties on these four components.  What are your predictions, re: potential conflicts that'd arise from altering those dimensions?

I'll look into configuring the nifi.properties.  I don't imagine it'll be too difficult for this feature.

**Comment by alopresto** [comment]
The four components altered are the ones most frequently displayed on the canvas, and therefore likely to cause changes in versioned flows based on position changes. Can I ask what reasoning led to not applying this snap feature to labels, funnels, or queue description panels/bend points? It seems like this would lead to an inconsistent experience for a user adding/modifying components on the canvas. 

My concern is that having the canvas change those dimensions/positioning will report back to the server that the component position has changed via the API, which will mark each component state as modified when flow versioning is enabled. This means that the version control features provided through the integration with NiFi Registry will be invoked and the flow will be marked as modified locally. It may also cause problems with nodes re-joining a cluster where two nodes may report the state changes in a non-deterministic manner and cause a conflict in the flow fingerprinting.

**Comment by R-Bower** [comment]
Good question.  I simply added the snap functionality to the most used components.  You're right about consistency.  I'll likely go back and change everything else.

Interesting, re: flow versioning.  I had assumed that only the data flows were relevant in flow versioning.  Adding/removing processors, endpoints, etc...  

In testing and implementing this feature, I noticed that the canvas elements didn't move until I had moved them (thereby evoking the draggable event).  While their sizes certainly changed, their origin coordinates didn't shift on the canvas.  What's tracked in the flow versioning process?  I'd imagine that the only required position data would be a single x/y coordinate for each component.  You'd only really need the size information for things like labels, unless there's a way to resize components that I'm not aware of.

**Comment by alopresto** [comment]
Yes, the origin point is what is tracked, although that's because component size (other than labels) was static and unchanged since 1.0.0. With this change, component size may need to be tracked as well, or there could be inconsistencies introduced when a flow from one version is imported into an instance running a different version. 

It's interesting that the "snap" doesn't occur until a drag event is registered on the component. Does this happen for all components in a selection/snippet if you select multiple and move them that way? I can see pros and cons to this -- an existing flow will not change the origin points until manually changed, but at the same time, if you have 1000's of components on a canvas, having to "snap" them individually/in groups. If a process group is moved, do the components contained inside that process group have their location modified as well?

I'm in the middle of a coding on a feature branch, so I can't check out this PR right now to explore on my own. Usually some level of this detail is covered in the PR description or at least documented via unit tests.

**Comment by mcgilman** [comment]
Will review...

**Comment by mcgilman** [comment]
@R-Bower Thanks for the PR! It is a very concise solution to the problem at hand. I share some of the share concerns that have been mentioned thus far and I have a few suggestions for addressing them.

**Turning this feature on/off**
Rather than always using snap-to-grid or adding a property which would set it for the entire instance what are your thoughts about conditionally snapping based on whether the drag event contains some modifier key (like Drag-Shift or something)? We could even discuss further with others in the community if the modifier key activated the snap functionality or if snap was the default and the modifier activated the more granular placement. If we took an approach like this we could even apply the same logic when resizing a label to ensure it's dimensions are a factor of `snapAlignmentPixels`. For consistency, I would also probably apply the same logic to connection bend point movement.

**Component dimensions**
My hesitations with the component dimensions are slightly different. The design/layout of each canvas node have been thoroughly considered/implemented to ensure they are pixel perfect. If we modify the dimensions of them it would probably warrant reconsidering each. Also, there would be another concern that could affect flow layout. As the dimensions change, the spacing between the nodes in existing flows also change and may require manually adjusting the layout. In extreme cases (either large changes to the dimensions or tightly laid-out flows), nodes could even overlap. This is admittedly not super concerning in this PR because the dimension changes here are so minimal. But it's still something we are super conscious of and generally avoid. However, I can appreciate the solution here by having the dimensions be a factor of `snapAlignmentPixels` we can align against all four sides of the node. Clever :)

@moranr Can you pull down this PR and evaluate each of the affected components to see if the change in dimensions would necessitate adjusting any of their contents?

**Comment by R-Bower** [comment]
Hey guys, thanks for all of the constructive feedback.  

> It's interesting that the "snap" doesn't occur until a drag event is registered on the component. Does this happen for all components in a selection/snippet if you select multiple and move them that way? I can see pros and cons to this -- an existing flow will not change the origin points until manually changed, but at the same time, if you have 1000's of components on a canvas, having to "snap" them individually/in groups. 

Having just tested this, I can confirm that each component does snap and align individually when multiple are selected and moved together.  Let me know if you want to see the recording that I took. 

> If a process group is moved, do the components contained inside that process group have their location modified as well?

Since the draggable event only impacts the selected canvas element(s), the inner processors for a process group shouldn't be moved.  I believe that draggable states are only invoked on components selected in the current canvas "level", and not on nested components, but I haven't verified this.

> **Turning this feature on/off**
> Rather than always using snap-to-grid or adding a property which would set it for the entire instance what are your thoughts about conditionally snapping based on whether the drag event contains some modifier key (like Drag-Shift or something)? 

This seems like the best compromise.  Current users would still be able to move components around as they do now, but snap alignment would also be an option.  I'm unfamiliar with how nifi handles modifier keys.  Since all of the controlling logic for draggable events is in nf-draggable, how would I go about accessing the activated keys?  I've merely scratched the service of nifi's frontend and would appreciate some additional direction/tips!

**Comment by moranr** [comment]
@mcgilman I'm looking over the discussion had so far and will pull this down to take a look soon.

**Comment by moranr** [comment]
> @moranr Thoughts on the drag with modifier key behavior?

+1 on using key modifier over a setting in properties. Shift key seems a good choice.

**Comment by moranr** [comment]
Upon first look, I definitely don't see anything out of place that is going to create any situation where something is not legeble. I will try to dig a bit more, but thinking anything that might need minor adjustment can be handled outside this PR. @mcgilman was there anything specific you wanted to check on?

**Comment by mcgilman** [comment]
@moranr With the changed dimensions, I was wondering if the contents would need to be offset to ensure the spacing remained consistent. For instance, with additional vertical space, the contents might be sitting too high since the additional space goes entirely to the bottom. And similarly would need to consider less vertical space and more/less horizontal space.

We're only talking a few pixels here so it's not much. But I know that we've spent a lot of time getting them nodes looking exactly right. Just wanted to ensure that you thought things were still looking good.

WRT the key modifier - Do you have thoughts on which behavior should be the default and which should be activated with Shift?

**Comment by moranr** [comment]
@mcgilman thinking about that some more, snap-to-grid might be nice as the default behavior. It would provide the simplest way for a user to easily align components (if they're particular about it). Holding Shift can can then deactivate that behavior, providing the user with greater precision.

Re: the changed dimensions -- understand your point. I'd say there are likely some adjustments that could be made. I'd need more time to go through every component and make recommendations.

**Comment by R-Bower** [comment]
Here are the size changes that I've made for this feature:
```
     var portDimensions = {
         width: 240,
-        height: 50
+        height: 48
     };
     var remotePortDimensions = {
         width: 240,
-        height: 75
+        height: 80
     };
// process-group
     var dimensions = {
-        width: 380,
-        height: 172
+        width: 384,
+        height: 176
     };

// remote process group
     var dimensions = {
-        width: 380,
-        height: 158
+        width: 384,
+        height: 176
     };
```

**Comment by R-Bower** [comment]
I'm going to update this PR with snap alignment for the remaining canvas elements.

**Comment by aperepel** [comment]
I would prefer bot changing component dimensions. E.g. there is logic in nifi-cli around import which ensures the new PG is never overlapping existing ones and has some whitespace around it upon placement.

Regarding auto-snap. IMO it's ok to have it ON as the default. A very simple (and expected) UX is to have a snap to grid toggle for when something else is desired. Existing components should not be forcefully snapped, let the user wiggle them if she wants to snap to a grid. I can hardly imagine a need to disable snap, especially if the grid size is reasonable.

Now, we are not trying to create a pro layout editor, just sensible basics. Definitely not a fan of adding any new property to the nifi.properties.

**Comment by andrewmlim** [comment]
@R-Bower I like what you've done here.  The snap-to-grid behavior is subtle, so making it the default behavior sounds good to me. Offering a modifier key to deactivate the behavior (like the Hold + Shift suggested by @moranr) is a good idea if for some reason the user needs more precision in placing their component.

**Comment by R-Bower** [comment]
> I would prefer not changing component dimensions. E.g. there is logic in nifi-cli around import which ensures the new PG is never overlapping existing ones and has some whitespace around it upon placement.

Unfortunately there's no other way to make the snap alignment consistent between components of varying sizes.  I tested numerous values and settled on 8 pixel increments.  Values less than 8 weren't noticeable enough, and larger values would've required drastic changes to component width/height.   My goal was to implement this feature without overhauling the entire canvas, and I think that this was the best compromise.  

The entire point of the snap-to-grid functionality is to be able to align components quickly without disrupting the developer's workflow.  I'm aware of the 1.2.0 alignment functionality, but the UX is cumbersome.  Click+Drag to select all components -> right click -> choose alignment (horizontal/vertical).  Having to repeat this step every time you add a new component is often more cumbersome than it's worth.

**Comment by R-Bower** [comment]
Just pushed.  
## updates
- The shift key now disables snap alignment when held during a drag event.  
- Adjusted the `nf-remote-process-group` `text.remote-process-group-last-refresh` to account for the increased height of the component.
- `nf-label` now resizes based on the snap alignment value.  
- Reduced initial width/height of `nf-label` from 150 to 148.
- Increased MIN_HEIGHT of `nf-label` from 20 to 24
- Added snap alignment to the drag event for `nf-connection`.  
- Increased width of `nf-connection` from 216 to 224.  Shifted alignment of connection status icon 8 pixels to the right.

## Notes
-  nf-connection has a dynamic height that adjusts based on whether its a `to` or `from` connection.  Its max height is ultimately dynamic, based on the number of rows + their contents and borders.  The top and bottom edges don't perfectly line up on the y axis.  This is minor, but the user can always disable the snap alignment for a pixel-perfect adjustment.  It's a minor issue, imo.

**Comment by moranr** [comment]
I spent a little time looking over changes and everything I have observed so far looks good. I see the RPG last refresh text I took note of previously has been addressed.

I think this being default behavior will add the greatest value. You can easily align components as you drag/drop or move them on the canvas, creating straight connection lines w/o having to go through the context menu. It also lets you align along a single horizontal or vertical edge (e.g., align left, align top) which currently is not possible. Disabling the behavior — in my opinion — would rarely be used going forward when building new flows. However, using the Shift key to do so is very easy.

@mcgilman / @andrewmlim hopefully you all have some time to try it out to see how you like it, plus more eyes to identify any issues due to size changes would be great.

@R-Bower thanks for all your work on this!

**Comment by mcgilman** [comment]
Sorry for the delay getting back here. 

@moranr It looks like the dimensions of the Remote Process Group changed to match the height of the Process Group. This change was a little more pronounced than others. See the screenshot below.

Screen Shot 2019-03-08 at 2 40 53 PM

@R-Bower The second and third (revert commit) has some merge conflicts with current master. I can sort of work through those but the resulting commit shows a lot of files changed where their contents are identical. I was wondering if you might be able to rebase and force push this PR without these two present. I might be able to drop these while I'm doing an interactive rebase assuming there are no additional changes needed here.

**Comment by moranr** [comment]
@mcgilman yes the largest change was the RPG, but the last refresh line was moved down accordingly. The additional whitespace doesn't bother me. There are still many visual differences between a PG and RPG, if that's a concern.

**Comment by mcgilman** [comment]
@R-Bower Ok, sounds like we're good with the component dimensions. However, I did notice one small issue. In `nf-connection.js` we've adjusted the run status and expiration icons. I think we need to also update the load balancing icons [1]. Since the others were bumped by 8 pixels (200 -> 208) I think we'd need to adjust these by the same increment. This icon is only available when in clustered mode. Let me know if you have any questions.

Thanks!

[1] https://github.com/apache/nifi/blob/master/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-connection.js#L1384

**Comment by R-Bower** [comment]
@mcgilman 

> The second and third (revert commit) has some merge conflicts with current master. I can sort of work through those but the resulting commit shows a lot of files changed where their contents are identical. I was wondering if you might be able to rebase and force push this PR without these two present. I might be able to drop these while I'm doing an interactive rebase assuming there are no additional changes needed here.

I'm not sure what happened there, hence the revert.  Those commits can be ignored.  

I've updated the nf-connections.js.  Let me know if you still want me to do a rebase.

**Comment by R-Bower** [comment]
@mcgilman Looks like the most recent commit failed with some checkstyle issues.  However, I haven't touched any of the files that it's complaining about.  Any ideas?
image

**Comment by mcgilman** [comment]
@R-Bower I'll take a look at the checkstyle when I pull everything down again. When I rebase this time I will drop the second and third commit and see where we're at. Thanks

**Comment by mcgilman** [comment]
@R-Bower I am not seeing any checkstyle issues on my branch where I've dropped those two commits.

**Comment by mcgilman** [comment]
Thanks @R-Bower! This has been merged to master.

**Pull request closed without merging**
