### PR TITLE
NIFI-4011 Updating Docker Hub image version information

### PR DESCRIPTION
**Pull request by apiri**
NIFI-4011 Updating Docker Hub image version information to accommodate release.

### CODE REVIEW

**Comment by joewitt** [comment]
+1

**Comment by evaldasou** [comment]
You have updated this, but now it fails at this step:

Step 12 : RUN curl -fSL $NIFI_BINARY_URL -o $NIFI_BASE_DIR/nifi-$NIFI_VERSION-bin.tar.gz        && echo "$(curl $NIFI_BINARY_URL.sha256) *$NIFI_BASE_DIR/nifi-$NIFI_VERSIO
N-bin.tar.gz" | sha256sum -c -  && tar -xvzf $NIFI_BASE_DIR/nifi-$NIFI_VERSION-bin.tar.gz -C $NIFI_BASE_DIR     && rm $NIFI_BASE_DIR/nifi-$NIFI_VERSION-bin.tar.gz
 ---> Running in 7f0673888650
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found

**Comment by evaldasou** [comment]
Looks You guys updated dockerfile to use 1.3.0 release... but it's not available yet at :
https://archive.apache.org/dist/nifi/

**Comment by apiri** [comment]
Hey @evaldasou,

That is anticipated.  Given the mechanics of the release process, the image will not be available until the release fully completes.  If you would like to build something now, locally, you can make use of the Docker Maven path to build an image available in the source tree at https://github.com/apache/nifi/tree/master/nifi-docker/dockermaven

**Comment by evaldasou** [comment]
got it! thanks!

**Comment by apiri** [comment]
No problem!  Let us know if you hit any obstacles with the other path.  Looks like the current release vote will be wrapping up today with the associated image build getting kicked off in the 24 hours after that.

**Pull request closed without merging**
