### PR TITLE
NIFI-11877 add a Comments field for Rules in UpdateAttribute processor

### PR DESCRIPTION
**Pull request by markobean**
# Summary
Added a feature for adding Comments to individual Rules in the Advanced UI of the UpdateAttribute processor. This provides a better location to provide comments as they apply to a particular rule. The only alternative is to document Rules in the Comments tab of the processor. This is too far removed from the Rule to be easy to associate the comment with the Rule - and is highly susceptible to the comment becoming stale relative to rule changes.

[NIFI-11877](https://issues.apache.org/jira/browse/NIFI-11877)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X] Pull Request based on current revision of the `main` branch
- [X] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

This PR is largely a UI feature. Add Rules in the Advanced UI of UpdateAttribute. Comments are able to be added and persist. Also, when creating a new Rule based on an existing Rule, the Comments field carries forward.

### Build

- [X] Build completed using `mvn clean install -P contrib-check`
  - [X] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — COMMENTED** [review]
@markobean Can you rebase this pull request on the latest main branch? Recent changes addressed issues with failing QuestDB tests, so it would be helpful to incorporate those changes and confirm clean automated builds.

**Comment by markobean** [comment]
> @markobean Can you rebase this pull request on the latest main branch? Recent changes addressed issues with failing QuestDB tests, so it would be helpful to incorporate those changes and confirm clean automated builds.

Rebased, ran build with `-Pcontrib-check`, pushed.

**Comment by exceptionfactory** [comment]
> @exceptionfactory Any additional comments on this one? Or can we stick a fork in it and merge?

Thanks for the follow up @markobean, I will review the latest updates soon.

**Review by exceptionfactory — APPROVED** [review]
Thanks for your work on this improvement @markobean, the new Rule Comments field looks good and provides a helpful way to describe functional details for specific Update Attribute Rules. +1 merging

**Pull request closed without merging**
