### PR TITLE
NIFI-10516: PutORC with Java 17 fails when using SNAPPY Compression

### PR DESCRIPTION
**Pull request by mark-bathori**
# Summary

[NIFI-10516](https://issues.apache.org/jira/browse/NIFI-10516)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [x] Build completed using `mvn clean install -P contrib-check`
  - [x] JDK 8
  - [ ] JDK 11
  - [x] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for putting forward this change @mark-bathori.

I'm not sure this is the best solution to introduce at this level. This changes the behavior of the JVM across the board for all components referencing those modules, not just PutORC. This highlights a compatibility issue that really should be resolved in the particular library.

We could consider introducing a commented option to `bootstrap.conf` for users who want to enable certain features on Java 17. However, I don't think we should introduce this as an automatic setting.

**Comment by mark-bathori** [comment]
Thanks @exceptionfactory for the review.
First I wanted to upgrade the snappy version but it already use the latest version. After that I also checked the `bootstrap.conf` solution just didn’t know if it can be expected from the user to know that enabling this jvm parameter is required to use certain processor, that’s why I thought that the NiFi runner should do this automatically based on the jdk version.
I was looking the oracle’s documentation for the jdk8+ migration: https://docs.oracle.com/en/java/javase/16/migrate/migrating-jdk-8-later-jdk-releases.html

However as you mentioned, modifying the JVM’s behaviour for one processor doesn't seems to be the best solution.

My question is, should I add any specific comment in the bootstrap.conf that reflects to the PutOrc processor?

**Comment by exceptionfactory** [comment]
Thanks for the reply @mark-bathori.

Although it will take more effort for a user to adjust a bootstrap.conf setting, it seems like the best solution in this case due to the nature of the workaround.

There is an open issue for the Snappy Java project to change the behavior, so I recommend referencing this issue URL in the comment, and note that it applies to any component that makes use of snappy-java.

https://github.com/xerial/snappy-java/issues/348

**Comment by exceptionfactory** [comment]
@mark-bathori Given that the changes to make this work would require a more generalized change to bootstrap.conf, I think it is best to close this pull request and create a new one that describes the more generalized nature of the change. Alternatively, it seems better to leave the Jira issue open for now and monitor progress on the snappy-java issue. I'm closing this pull request for now, but if you want to propose a configurable bootstrap.conf approach, feel free to open to a new PR.

**Pull request closed without merging**
