### PR TITLE
NIFI-3213: ListFile - Do not skip obviously old files.

### PR DESCRIPTION
**Pull request by ijokarumawak**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

Before this fix, files with the latest timestamp within a listing
iteration are always be held back one cycle no matter how old it is.

### CODE REVIEW

**Comment by ijokarumawak** [comment]
I believe the old behavior that always postpone to emit files with the latest timestamp is counter intuitive and can be problematic with some use cases if user would like to schedule it with longer run schedule. Please correct me if I'm missing any important purpose for this behavior.

I had to fix many unit test cases because those are written with an assumption that the latest file should be skipped. Again I believe those test cases became more natural and understandable by this PR, but I may be missing something.

Thanks for reviewing in advance!

**Comment by trixpan** [comment]
@ijokarumawak reviewing it

**Comment by trixpan** [comment]
LGTM merging

**Comment by trixpan** [comment]
@ijokarumawak my bad. I was just running a extra set of compilations and I noticed that under certain conditions there seems to be a race condition affecting 

```
Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.66 sec <<< FAILURE! - in org.apache.nifi.processors.standard.TestListFile
testFilterAge(org.apache.nifi.processors.standard.TestListFile)  Time elapsed: 1.212 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<age[2].txt> but was:<age[1].txt>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.apache.nifi.processors.standard.TestListFile.testFilterAge(TestListFile.java:223)

```

Do you want to have a look at it?

**Comment by ijokarumawak** [comment]
@trixpan Thanks for reviewing and catching the unit test failure. Yes, I'd like to look at it closer. I will update the PR accordingly.

**Comment by ijokarumawak** [comment]
@trixpan Since the failing test has more Thread.sleep calls than before, the meaning of variables such as `age1` or `age2` became fragile at the later part of the test. I added another commit to fix the test case. Also, rebased it with the latest master just in case.

Thanks again for caching this test issue. Please review the test again, and let me know if you want me to squash commits.

**Comment by trixpan** [comment]
@ijokarumawak merged. However I forgot to add reference to the PR in the commit message. Would you mind closing it manually ?

I thank you in advance

**Comment by ijokarumawak** [comment]
@trixpan Thank you for merging! closed.

**Pull request closed without merging**
