### PR TITLE
NIFI-12030 Property pop-up window is horizontally resizable

### PR DESCRIPTION
**Pull request by annanys23**
# Summary

[NIFI-12030](https://issues.apache.org/jira/browse/NIFI-12030)

When a property of a controller service or processor is a list of values, the combo box is now horizontally resizable when open.

# Tracking

### Issue Tracking

- [x ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [x] Build completed using `mvn clean install -P contrib-check`
  - [x] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [x] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by Lehel44 — APPROVED** [review]
Thanks @annanys23 for the contribution. I tested the feature in Chrome and Safari and it works fine.
Screenshot 2023-10-26 at 17 33 12

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for the contribution @annanys23, and thanks for testing this @Lehel44.

Although resizing the combo option box may have some usefulness, the user experience around resizing the combo option does not seem like the best approach. Others with additional user interface experience may have thoughts.

**Comment by koccs** [comment]
Probably it is less comfortable because it requires hover over the options, but if any text is truncated with an ellipsis then a tooltip (with the full text) is the most commonly used solution in the industry.
Although it is not the best in the perspective of accessibility, but neither the resize handle.

**Comment by scottyaslan** [comment]
This case is already addressed in the UI. For long values, the text is truncated with the ellipsis:

Screenshot 2023-10-31 at 1 53 40 PM

The user can hover over the value to see the title tooltip:

Screenshot 2023-10-31 at 1 53 11 PM

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
I agree with you @scottyaslan, this is already handled, so from that perspective, I don't think there are any better approaches.

Do you have any additional thoughts @annanys23? Otherwise it would be best to close the pull request, and perhaps continue the discussion on the associated Jira issue.

**Comment by annanys23** [comment]
I don't have any other thoughts on this.  Thank you all for your input.

**Pull request closed without merging**
