### PR TITLE
NIFI-6382: On flow import and version change, create parameter context where necessary and add parameters where necessary

### PR DESCRIPTION
**Pull request by markap14**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Enables X functionality; fixes bug NIFI-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?

- [ ] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by bbende** [comment]
Will review...

**Comment by bbende** [comment]
Still testing, but noticed two things so far...

1) Sensitive properties still have their values cleared out when being saved to registry. I think we want to detect if the value is a parameter reference and retain the value in that case, otherwise those values would have to manually be set again after import.

2) In the case where you import a flow from registry that has a context named "foo" and there is already a context named "foo" in the NiFi instance, it doesn't appear to be adding new parameters. I had existing "foo" with "param1", and the incoming "foo" from the flow snapshot also had "param2" and "param3" but those weren't added to the existing "foo".

**Comment by bbende** [comment]
To clarify on #2, the issue appears to be only on initial import when a context already exists. Changing version does appear to add new parameters correctly.

**Comment by markap14** [comment]
Thanks @bbende - both great catches! Will address.

**Comment by bbende** [comment]
Verified the latest changes, everything looks good, going to merge, thanks!

**Pull request closed without merging**
