### PR TITLE
[NIFI-636] Processor Logger using same level as message for Throwables

### PR DESCRIPTION
**Pull request by brianghig**
Processor Loggers will now use the same Logger level for Throwables as is used for messages. Previously, enabling DEBUG was the only way to see stacktraces from logged throwables when running in INFO, WARN, or ERROR levels.

### CODE REVIEW

**Comment by joewitt** [comment]
Brian,

The issue with this proposal is that it takes away the administrators ability to control whether stack traces are provided or not.  The reason we used 'isDebugEnabled' was because that was the use case in which the stack trace was necessary (because they were debugging).   Given that you can edit logback config on the fly this seems like a reasonable approach.  But taking away their ability to control this as the effect of this proposal means they're getting the stack traces whether they want them or not.  This can cause very excessive and noisy output in the logs.

Do you have an alternative proposal for how we can retain the flexibility of letting the administrator toggle the stack traces?

Thanks
Joe

**Comment by brianghig** [comment]
Hi Joe,

We could use filters within the Logback configuration to turn on/off Throwables or any granularity of Exceptions.  Since exceptions can be used for more than debugging, doing so would honor the caller's logging level of the throwable and allow admins to maintain full control over the logs.

For example, using some built-in mechanisms from http://logback.qos.ch/manual/filters.html#evalutatorFilter, we could add something like this to the appender(s):
```
<filter class="ch.qos.logback.core.filter.EvaluatorFilter">
    <evaluator>
        <expression>java.lang.Exception.class.isInstance(throwable)</expression>
    </evaluator>
    <onMatch>DENY</onMatch>
</filter>
```

Thanks,
Brian

**Comment by joewitt** [comment]
...slick.  Will need to read more on that but this could be an option.  Curious what others think?  Can you please make a JIRA for it and like that to this?

**Comment by joewitt** [comment]
Brian - can you mention what you think are the other use cases for exception stack traces beyond debugging?

**Comment by danbress** [comment]
A couple comments

1) Does this pull request have a JIRA ticket associated with it?

2) As a developer I also share Adam's developer viewpoint.  I would prefer the 'operations' style log messages turned down, and the exceptions turned up.

**Comment by brianghig** [comment]
@danbress - I created NIFI-636 to cover this PR, and updated the PR's title to link it.

@joewitt - the use case I'm considering for stack traces is operational with feedback to engineering teams. When something is going wrong on some far away network, we've had folks and/or tools tailing logs and reporting details about the errors to dev teams via tickets that include stack traces.  Additionally, stack traces can be useful tools for low-level auditing purposes to follow the flow of a user or piece of data through layers of the system, but as you've said, provenance does a much better job of handling that.

**Comment by joewitt** [comment]
@brianghig would you be opposed to closing this and re-opening once we get develop branch removed?  I think we can get it merged quickly thereafter.  Is that cool?

**Comment by brianghig** [comment]
@joewitt sounds good to me.  Would be nice to also get some of those custom formatters in there to make it easier for end users to have examples to work with when they do want to suppress stack traces in the logs.

**Pull request closed without merging**
