### PR TITLE
NIFI-8171 Upgraded Bouncy Castle libraries to 1.68 and centralized de…

### PR DESCRIPTION
**Pull request by exceptionfactory**
#### Description of PR

NIFI-8171 Upgrades Bouncy Castle Security Provider and related libraries from 1.66 to 1.68.  This PR also centralizes the managed dependency version in the root Maven configuration to avoid different versions in extension bundles.  The Bouncy Castle Security Provider is configured using Security.addProvider(), which impacts the entire system, so different dependency versions should not be allowed.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [X] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [X] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by joewitt** [comment]
looked through each of the dep updates.  Since they are generally updating only dependency management it is probably fair game to elevate the specific declaration to the top level pom's dependency mgmt section.  The others which are updated for dependency (not dependency management are fine since they simply remove the version declaration (thus it comes from parent poms).  So I believe this will be easier to maintain without changing the actual behavior.  

That said hopefully this tackles the github actions issue which has emerged.  Will watch this build.

**Comment by exceptionfactory** [comment]
> looked through each of the dep updates. Since they are generally updating only dependency management it is probably fair game to elevate the specific declaration to the top level pom's dependency mgmt section. The others which are updated for dependency (not dependency management are fine since they simply remove the version declaration (thus it comes from parent poms). So I believe this will be easier to maintain without changing the actual behavior.
> 
> That said hopefully this tackles the github actions issue which has emerged. Will watch this build.

@joewitt Thanks for reviewing the changes.  As mentioned in the PR description, uses of Bouncy Castle in classes within `nifi-security-utils` impact the entire system, so it seems to be best to elevate version management to the root Maven configuration.

The initial GitHub CI run failed with a couple assertion errors, as opposed to the SSL handshake exceptions previously observed, so I pushed an update to increase the timeouts in the two failing HTTP tests.

**Comment by joewitt** [comment]
Yeah true they do have a pretty broad impact.  However, we have to be extremely careful about which dependencies end up in our 'all things classloader' since every subordinate classloader will be impacted.  Specifically when the binary of nifi is build we need to ensure ONLY those jars we want to make/force be present on every classloader is in the lib folder.  We have to be careful to ensure we dont grow that as each time we do we reduce the classloader isolation nars can offer.

**Comment by exceptionfactory** [comment]
> Yeah true they do have a pretty broad impact. However, we have to be extremely careful about which dependencies end up in our 'all things classloader' since every subordinate classloader will be impacted. Specifically when the binary of nifi is build we need to ensure ONLY those jars we want to make/force be present on every classloader is in the lib folder. We have to be careful to ensure we dont grow that as each time we do we reduce the classloader isolation nars can offer.

@joewitt That makes sense.  For clarification, are suggesting any changes to the dependency management changes in this PR?

The dependency management restructuring does not alter the class path and library directory contents, it just moves the version number management to the root Maven configuration.  Both before and after these proposed changes, any extensions that leverage Bouncy Castle and also depend on `nifi-security-utils` directly or indirectly should be using the same version to avoid unexpected runtime behavior.

**Comment by joewitt** [comment]
no. just verbalizing what i was focusing on .  i think your changes don't change it since you just operated on 'dependency management' rather than 'dependency' sections except as noted.  All good.  Fingers crossed

**Comment by exceptionfactory** [comment]
This PR ended up introducing a lot of additional unit test changes in order to optimize the build process.

Upgrading Bouncy Castle to 1.68 resolved the previous issues related to the following exception:

`java.security.InvalidKeyException: cannot identify XDH private key`

Azul Zulu JDK 11.0.10 included [changes](https://bugs.openjdk.java.net/browse/JDK-8171279) to support X25519 and X448 Elliptic Curves for TLS.  This change and other changes to Key Agreement selection appear to have forced the selection of the Bouncy Castle Security Provider in some circumstances.  Bouncy Castle 1.67 and 1.68 enhanced support for these Elliptic Curves and TLS 1.3.

After introducing the Bouncy Castle version upgrade, several unit tests started failing in different methods due to apparent timeout issues.  The test classes for `InvokeHTTP` and `ListenHTTP` as well as `PutTCP` relied on the `SSLContextService` implementation class, which resulted in instantiating a new `SSLContext` for each test method.  Refactoring these test classes to initialize `SSLContext` once per test class and mocking `SSLContextService` optimized test performance and appears to have addressed the timeout issues.

**Comment by joewitt** [comment]
Reviewing this in more detail and trying on my fork.  I did get the build to pass in one case but it was unreliable in a couple others.  I'm trying with diff ubuntu versions, with urandom being set as a system property.  I see failures like

Warning:  Tests run: 8, Failures: 0, Errors: 0, Skipped: 5, Time elapsed: 0.16 s - in org.apache.nifi.processors.standard.TestGetHTTPGroovy
2786
Error:  Failures:
2787
Error:    TestGetHTTP.testSecure_oneWaySsl:391 org.apache.nifi.processor.exception.ProcessException: javax.net.ssl.SSLException: arraycopy: last source index 32 out of bounds for byte[31]
2788
Error:  Tests run: 1661, Failures: 1, Errors: 0, Skipped: 23
2789
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project nifi-standard-processors: There are test failures.
2790
Error:
2791
Error:  Please refer to /home/runner/work/nifi/nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/target/surefire-reports for the individual test results.
2792
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
2793
Error:  -> [Help 1]

Error:  Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.995 s <<< FAILURE! - in org.apache.nifi.processors.standard.TestListenRELP
2776
Error:  testTLS(org.apache.nifi.processors.standard.TestListenRELP)  Time elapsed: 0.124 s  <<< ERROR!
2777
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
2778
	at org.apache.nifi.processors.standard.TestListenRELP.sendFrames(TestListenRELP.java:277)
2779
	at org.apache.nifi.processors.standard.TestListenRELP.run(TestListenRELP.java:236)
2780
	at org.apache.nifi.processors.standard.TestListenRELP.testTLS(TestListenRELP.java:178)
2781
Caused by: java.io.EOFException: SSL peer shut down incorrectly
2782
	at org.apache.nifi.processors.standard.TestListenRELP.sendFrames(TestListenRELP.java:277)
2783
	at org.apache.nifi.processors.standard.TestListenRELP.run(TestListenRELP.java:236)
2784
	at org.apache.nifi.processors.standard.TestListenRELP.testTLS(TestListenRELP.java:178)
2785

Error:  Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.93 s <<< FAILURE! - in org.apache.nifi.security.util.crypto.PasswordBasedEncryptorGroovyTest
2790
Error:  testBcryptDecryptShouldSupportLegacyKeyDerivationProcess(org.apache.nifi.security.util.crypto.PasswordBasedEncryptorGroovyTest)  Time elapsed: 1.038 s  <<< FAILURE!
2791
org.codehaus.groovy.runtime.powerassert.PowerAssertionError:
2792
assert recovered == PLAINTEXT
2793
       |         |  |
2794
       |         |  'This is a plaintext message. '
2795
       |         false
2796
       'n\f�ˬ�L��e~E�\r鞜>`�D�KR��=��N'
2797
	at org.apache.nifi.security.util.crypto.PasswordBasedEncryptorGroovyTest.testBcryptDecryptShouldSupportLegacyKeyDerivationProcess(PasswordBasedEncryptorGroovyTest.groovy:445)
2798
2799
Error:  Failures:
2800
Error:    PasswordBasedEncryptorGroovyTest.testBcryptDecryptShouldSupportLegacyKeyDerivationProcess:445 assert recovered == PLAINTEXT
2801
       |         |  |
2802
       |         |  'This is a plaintext message. '
2803
       |         false
2804
       'n\f�ˬ�L��e~E�\r鞜>`�D�KR��=��N'
2805
Error:  Errors:
2806
Error:    TestListenRELP.testTLS:178->run:236->sendFrames:277 » SSLHandshake Remote host...
2807
Error:  Tests run: 1661, Failures: 1, Errors: 1, Skipped: 23
2808
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project nifi-standard-processors: There are test failures.
2809
Error:
2810
Error:  Please refer to /home/runner/work/nifi/nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/target/surefire-reports for the individual test results.
2811
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
2812
Error:  -> [Help 1]
2813
Error:
2814
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
2815
Error:  Re-run Maven using the -X switch to enable full debug logging.
2816
Error:
2817
Error:  For more information about the errors and possible solutions, please read the following articles:
2818
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
2819
Error:
2820
Error:  After correcting the problems, you can resume the build with the command
2821
Error:    mvn <args> -rf :nifi-standard-processors
2822
Error: Process completed with exit code 1.

**Comment by joewitt** [comment]
very impressive work on this David.  +1 merged to main.  Hopefully the build works here again.  Squashed the 14 commits.  Did also verify its behavior on my fork with various diff java 11 related configs.  none of them seemed necessary - just the code changes you've made.  Hopefully this sorts the sudden java 11 instability found since this latest Azul release.  Either way the changes seem beneficial. Thanks

**Pull request closed without merging**
