### PR TITLE
NIFI-2087: Do not update the lucene index to delete expired events...

### PR DESCRIPTION
**Pull request by markap14**
Instead, just wait for the entire index to expire and remove the files for that index. This is much more efficient.

### CODE REVIEW

**Comment by JPercivall** [comment]
Reviewing

**Comment by JPercivall** [comment]
I see this change only taking effect when the repo is initialized. Is there really no other place that should be updated?

**Comment by markap14** [comment]
@JPercivall no, that should be it. We have one other place where we use the DeleteFileAction but it still needs to stay there. This should take care of it.

**Comment by JPercivall** [comment]
+1

Did a contrib check build, visually verified and ran a lot of data with a small index size and saw it work as expected. Will merge in.

**Pull request closed without merging**
