### PR TITLE
NIFI-11956 Update frontend.mvn.plugin.version to 1.13.4

### PR DESCRIPTION
**Pull request by mr1716**
# Summary

[NIFI-11956](https://issues.apache.org/jira/browse/NIFI-11956)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI-11956) issue created

### Pull Request Tracking

- [X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X] Pull Request based on current revision of the `main` branch
- [X] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for the upgrade @mr1716. There are two other version references for the frontend-maven-plugin, one in `nifi-jolt-transform-json-ui` and one in `nifi-registry-web-ui`. Both of these specific version numbers should be replaced with the property reference `${frontend.mvn.plugin.version}`. If you can make those changes and the builds look good, this should be ready to go.

**Comment by mr1716** [comment]
@exceptionfactory thanks. transform-json-ui has been updated accordingly. I see nifi-registry-web-ui pom.xml referencing the proper variable mentioned here.

**Comment by exceptionfactory** [comment]
> @exceptionfactory thanks. transform-json-ui has been updated accordingly. I see nifi-registry-web-ui pom.xml referencing the proper variable mentioned here.

Thanks for updating the Jolt UI configuration. The Registry pom.xml has multiple references to the plugin, some of which are correct, but one still has a hard-coded version.

**Comment by mr1716** [comment]
@exceptionfactory thanks for the clarification. Apologies for the delay, didnt see that part, so I just made the fix.

**Review by exceptionfactory — APPROVED** [review]
Thanks for making the additional updates @mr1716, the latest version looks good. +1 merging

**Pull request closed without merging**
