### PR TITLE
NIFI-3352 - Address issue where ListenLumberjack was sending long num…

### PR DESCRIPTION
**Pull request by trixpan**
…bers back to clients - instead of int

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [x] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [x] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by joewitt** [comment]
@trixpan is there anything we can reference for this change showing it should be an int instead of a long?  It is clearly a pretty simple change just want to have some clear basis for it.  thanks

**Comment by trixpan** [comment]
@joewitt 

sure thing:

https://github.com/elastic/logstash-forwarder/blob/master/PROTOCOL.md#ack-frame-type

**Comment by alopresto** [comment]
Reviewing...

**Comment by alopresto** [comment]
Reviewed, reviewed reference documentation provided by @trixpan , and ran all tests and contrib-check. Merged.

**Pull request closed without merging**
