### PR TITLE
NIFI-7605 Removed user-agent default value so no header will be sent …

### PR DESCRIPTION
**Pull request by MikeThomsen**
…by default.

Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Enables X functionality; fixes bug NIFI-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [ ] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by alopresto** [comment]
If the *User Agent* property is left blank in `InvokeHTTP`, the user agent header is now provided as `okhttp/3.8.1`. Is this the intended behavior?

```
{"args":{},"headers":{"x-forwarded-proto":"https","x-forwarded-port":"443","host":"postman-echo.com","x-amzn-trace-id":"Root=1-5f28620a-fb32576cde15e89c20a30306","date":"Mon, 03 Aug 2020 19:14:18 GMT","accept-encoding":"gzip","user-agent":"okhttp/3.8.1"},"url":"https://postman-echo.com/get"}
```

**Comment by alopresto** [comment]
I fixed the issue as per the mailing list discussion via this commit: https://github.com/alopresto/nifi/commit/24de890bf2410ec396357c9e13ada9410d8b679c.

**Comment by joewitt** [comment]
+1 pls merge both commits andy.  ty

**Comment by johighley** [comment]
After this change, User-Agent header is still being sent when no property value is set, but the header has no value.  If no property value is set in processor config, then the header should not be sent.

**Comment by exceptionfactory** [comment]
Thanks for the note @johighley. As this pull-request is already closed, please create a new issue in the [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) project so that is can be addressed.

**Comment by johighley** [comment]
Created https://issues.apache.org/jira/browse/NIFI-10397

**Pull request closed without merging**
