### PR TITLE
NIFI-3173: When a template is created with multiple components in dif…

### PR DESCRIPTION
**Pull request by markap14**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

…ferent groups all referencing the same controller service, ensure that controller service is added to the template at a high enough level that all components needing hte service can access it.

### CODE REVIEW

**Comment by JPercivall** [comment]
Reviewing

**Comment by JPercivall** [comment]
@markap14 I hit a case where a CS wasn't preserved. I'll outline it in the same way you listed your example in the comments:

G1 -- C1
|
|
G2 -- C2
|    \
|      P1
G3   
| \   \
|    \   P2
G4  G5
|        |
|        |
P3    P4

P3 and P4 are HandleHttpRequest and HandleHttpResponse which reference C1 (HttpContextMap) and P2 is ReplaceText. They form an Http Service which takes any request and returns "test".

P1 is an InvokeHttp which references an SSLController Service C2 which is in the same group.

When making the template (by being in G1, selecting G2 and clicking create template), the Http Service explained first is created as expected but C2 is not added to the template at all.

**Comment by markap14** [comment]
@JPercivall good catch! I was so caught up verifying top-level controller services that i missed that. I have pushed a second commit to address this. Thanks!

**Comment by JPercivall** [comment]
+1

Visually verified code and did a contrib-check build. In standalone and clustered, tried creating templates ranging in complexity from a processor template to a template containing multiple different PGs, CSs and processors at every level. All worked as expected. Thanks @markap14 I will squash and merge.

**Pull request closed without merging**
