### PR TITLE
NIFI-9830: Use temp directory with post-rename during nar-unpacking

### PR DESCRIPTION
**Pull request by gresockj**
#### Description of PR

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [ ] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by exceptionfactory** [comment]
Thanks for the contribution @gresockj. Can you provide some additional details on how the change improves performance? It seems like there is more work involved in unpacking to a temporary directory and moving, as opposed to just unpacking directly to the working directory. This impacts more than Stateless, so it would be helpful to understand the implications for all deployment form-factors.

**Comment by gresockj** [comment]
> Can you provide some additional details on how the change improves performance?

Sure -- in some use cases if the unpacking is interrupted, the working directory may be incomplete.  Previously, the only way around this was to delete the working directory prior to running stateless, regardless of whether the working directory was incomplete, in which case the NAR must be unpacked each time stateless starts.  This change allows us to be confident that the working directory is complete, and thus remove the unnecessary working directory cleanup before each stateless startup.

While we could add some additional conditional code that only activates this mode in stateless, I don't think it has enough of a performance impact to warrant that complexity.

**Comment by exceptionfactory** [comment]
Thanks for the additional background @gresockj, that is helpful to know.  Would it make more sense to check the contents of the working directory and unpack as needed? It seems like this change could have a larger impact in some cases.

**Comment by exceptionfactory** [comment]
@gresockj In discussing this change with @markap14, it seems like a better approach would be the check for the presence of the digest file as an indicator of whether the unpacking process completed. That should avoid the need to unpack to a temporary directory on every invocation.

**Comment by gresockj** [comment]
> @gresockj In discussing this change with @markap14, it seems like a better approach would be the check for the presence of the digest file as an indicator of whether the unpacking process completed. That should avoid the need to unpack to a temporary directory on every invocation.

Agreed -- I meant to close this earlier.  Thanks for following up!

**Pull request closed without merging**
