### PR TITLE
NIFI-3299 Adding example of sensitive property key migration to the a…

### PR DESCRIPTION
**Pull request by bbende**
…dmin guide

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by andrewmlim** [comment]
This is a good addition to the doc for this tool.

Now that we have two separate use cases, I suggest adding two new sub-sections within the "Encrypt-Config Tool" section.  Something like this:

**Key Migration**

In order to change the key used to encrypt the sensitive values, indicate migration mode using the -m or --migrate flag...
.
.
.
old password → new key
old password → new password

**Existing Flow Migration**

This tool can also be used to change the value of nifi.sensitive.props.key for an existing flow...

**Comment by alopresto** [comment]
@bbende This looks good, thanks for the submission. I added a couple formatting elements and a little further description of the `-x` flag (see my separate additions [here](https://github.com/alopresto/nifi/commit/61987ded4b54032967376b900ce39333987a209c)). 

Merging.

**Comment by alopresto** [comment]
@andrewmlim just saw your comment and I agree. I will add those sub-section headers before merging (and update my NIFI-3299 branch for posterity).

**Comment by alopresto** [comment]
Added [sub-section headers](https://github.com/alopresto/nifi/commit/e3f08a512ec8143d319ed55097b81ed08cde0bc8) as per @andrewmlim .

Merging...

**Pull request closed without merging**
