### PR TITLE
Message on history page when clustered

### PR DESCRIPTION
**Pull request by mcgilman**
NIFI-2302:
- Showing a message on the history page when in a cluster to indicate that only the actions from the current node are displayed.

### CODE REVIEW

**Comment by JPercivall** [comment]
I was a bit confused by the message at first, I took it to mean "this history only shows changes that were made on this node" and was confused when I saw changes from every node on the history of each node. I'm not sure the most succinct/correct way to phrase it but maybe something more like "this history shows all changes made to the cluster while this node was connected"?

**Comment by mcgilman** [comment]
Your first impression of that message is accurate. We are only showing actions from the node the browser is pointing to. Meaning, if that node has other history before it was clustered it would be available. Each node is only showing the history it knows about. If every node was only part of its current cluster then all nodes would report the same history.

**Comment by JPercivall** [comment]
Sorry more specifically, I have a 3 node cluster and made one change on each (while all were connected), I didn't expect to see all three of the changes in the history of each node.

**Comment by mcgilman** [comment]
Each node processed each action regardless if your browser was pointed to it. That's how the flows are kept in sync. The potential confusion here is with actions that happened to a node when it was not part of the cluster.

**Comment by JPercivall** [comment]
Yup, that was my confusion and I think the target user of this message (people not really familiar with the in's/out's of clustering) will get hung up on that as well.

**Comment by mcgilman** [comment]
Do you have another suggestion for the message? What if we create another JIRA for further explanation in the user guide? Tough to explain the scenario in a short sentence or two.

**Comment by JPercivall** [comment]
Hmmm, not sure if it's too long but maybe something like (first sentence is probably optional):

Viewing the history of the current node only. This history includes changes that were made as a standalone instance and any changes replicated to this instance(?) as a node of a cluster.

**Comment by mcgilman** [comment]
The message is only shown when the node is part of a cluster. I think we shouldn't overcomplicate things. Inform the user that they are viewing the history of the current node and suggest they can browse to another node to view it's history. I believe this is a clear, simple, and accurate description of what is being display and what other options the user has.

**Comment by JPercivall** [comment]
After sleeping on it, I agree with you.

+1

Visually verified code, and did a contrib check build. In 3 node secure cluster and standalone verified that the message appeared when expected and history displayed what was expected. Thanks @mcgilman, I will merge it in.

**Pull request closed without merging**
