### PR TITLE
NIFI-3856 PutCloudWatchMetric support for StatisticSets and Dimensions

### PR DESCRIPTION
**Pull request by tequalsme**
- Add support for StatisticSets as well as regular (double) values
- Add support for Dimensions via dynamic properties

### CODE REVIEW

**Comment by jvwing** [comment]
Reviewing...

**Comment by jvwing** [comment]
@tequalsme thanks again for contributing this cool upgrade to PutCloudWatchMetric.  First, a couple of nickpicks:
* PropertyDescriptor `name` should be a data key, typically lowercase, like "minimum".  The `displayName` property should have a human-readable name "Minimum".  Although the names and displayNames might be very similar now, this helps provide flexibility for later changes.  I realize we didn't follow that convention creating PutCloudWatchMetric, and your changes are following the pattern established in the file.  In this case, we should be different.
* I found a Checkstyle warning for "Unused import - java.util.Comparator" (for TestPutCloudWatchMetric) running `mvn clean install -Pcontrib-check`.

The processor performed well under proper use.  So I moved on to improper use.  For the statistic set scenario, if I provided some but not all of Minimum, Maximum, Sum, and SampleCount, the processor did not raise a validation issue and later ran into a NullPointerException parsing a double from Minimum (in this case).  How about a validation clause to make sure you specified something for all four?

Other validations worked well.  Help/docs look good.  Code coverage from unit tests is great.  Code quality looks very high.

**Comment by tequalsme** [comment]
@jvwing Thanks for reviewing so promptly, and good call on checking for incomplete statistic sets. That was an oversight in customValidate(). I fixed and added a test case, and also addressed your other comments.

**Comment by jvwing** [comment]
The additional validation logic looks good.  The full build passes. 

Thank you for changing the name/displayName arrangement on the new PropertyDescriptors.  I'm going to leave out the changes to the PropertyDescriptor `name` property for the pre-existing PropertyDescriptors Namespace, MetricName Value, Timestamp, and Unit.  We don't want to change the pre-existing ones in a minor release, because they will break existing settings when processors are upgraded and the names don't match values stored in flow.xml.gz.  Sorry for adding confusion about those.

I will merge this shortly.  Thanks, @tequalsme!

**Pull request closed without merging**
