### PR TITLE
NIFI-10580 Upgrade SLF4J from 1.7.36 to 2.0.6

### PR DESCRIPTION
**Pull request by exceptionfactory**
# Summary

[NIFI-10580](https://issues.apache.org/jira/browse/NIFI-10580) Upgrades SLF4J from 1.7.36 to 2.0.6 and upgrades Logback from 1.2.11 to 1.3.5.

SLF4J 2.0 does not introduce any breaking API changes to standard interfaces, but changes the initialization process, which requires a minimum Logback version of 1.3.0. Logback 1.4.0 requires Java 11, so Logback 1.3.5 is the current compatible version.

Spring Boot 2.7 provides a logging system implementation based on Logback 1.2, but the initialization process is not compatible with Logback 1.3. NiFi Registry does not depend on the Spring Boot logging initialization, so disabling the initialization using a System property resolves startup issues.

ZooKeeper has a dependency on Logback, which creates issues when running some tests, but excluding Logback resolves those issues.

The ZooKeeperMigratorTest.groovy creates a test ZooKeeper server using an Apache Curator class that relies on Logback 1.2. This test is written in Groovy and uses Spock, so this pull request removes the test class.

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X] Pull Request based on current revision of the `main` branch
- [X] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [X] Build completed using `mvn clean install -P contrib-check`
  - [X] JDK 8
  - [ ] JDK 11
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by joewitt** [comment]
very cool. So " so disabling the initialization using a System property resolves startup issues" - with this our logging and such for the registry still works we just bypass springs initialization problem?

**Comment by exceptionfactory** [comment]
> very cool. So " so disabling the initialization using a System property resolves startup issues" - with this our logging and such for the registry still works we just bypass springs initialization problem?

That's correct, Spring Boot has its own logging system that provides conveniences like mapping application properties to logging levels. However, since NiFi Registry includes a standard logback.xml and does not use Spring Boot application properties, standard Logback initialization works.

**Comment by joewitt** [comment]
Great work here.  But I think there is a bit more to do.  Running a full build with this command

mvn clean install -T 1C -Pinclude-grpc,contrib-check,include-ranger,include-atlas,include-hive3,include-rules,include-sql-reporting,include-hadoop-aws,include-hadoop-azure,include-hadoop-cloud-storage,include-hadoop-gcp,include-graph,include-accumulo,include-hadoop-ozone,include-asn1,include-aws,include-snowflake,include-media

I then search for any jar with log in the name and find

./work/nar/framework/nifi-framework-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/nifi-deprecation-log-1.20.0-SNAPSHOT.jar
./work/nar/framework/nifi-framework-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/logback-core-1.2.10.jar
./work/nar/framework/nifi-framework-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/nifi-write-ahead-log-1.20.0-SNAPSHOT.jar
./work/nar/framework/nifi-framework-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/nifi-logging-utils-1.20.0-SNAPSHOT.jar
./work/nar/extensions/nifi-email-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/log4j-api-2.18.0.jar
./work/nar/extensions/nifi-hive3-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/flogger-system-backend-0.5.1.jar
./work/nar/extensions/nifi-hive3-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/logback-core-1.2.10.jar
./work/nar/extensions/nifi-hive3-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/hive-hcatalog-core-3.1.3.jar
./work/nar/extensions/nifi-hive3-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/log4j-api-2.18.0.jar
./work/nar/extensions/nifi-hive3-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/flogger-0.5.1.jar
./work/nar/extensions/nifi-hive3-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/flogger-slf4j-backend-0.5.1.jar
./work/nar/extensions/nifi-standard-services-api-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/nifi-deprecation-log-1.20.0-SNAPSHOT.jar
./work/nar/extensions/nifi-media-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/log4j-api-2.18.0.jar
./work/nar/extensions/nifi-distributed-cache-services-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/nifi-write-ahead-log-1.20.0-SNAPSHOT.jar
./work/nar/extensions/nifi-gcp-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/flogger-system-backend-0.7.4.jar
./work/nar/extensions/nifi-gcp-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/flogger-0.7.4.jar
./work/nar/extensions/nifi-hadoop-libraries-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/flogger-system-backend-0.5.1.jar
./work/nar/extensions/nifi-hadoop-libraries-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/log4j-api-2.18.0.jar
./work/nar/extensions/nifi-hadoop-libraries-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/flogger-0.5.1.jar
./work/nar/extensions/nifi-hadoop-libraries-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/flogger-slf4j-backend-0.5.1.jar
./work/nar/extensions/nifi-accumulo-services-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/logback-core-1.2.10.jar
./work/nar/extensions/nifi-windows-event-log-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/nifi-utils-1.20.0-SNAPSHOT.jar
./work/nar/extensions/nifi-windows-event-log-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/commons-io-2.11.0.jar
./work/nar/extensions/nifi-windows-event-log-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/jna-5.12.1.jar
./work/nar/extensions/nifi-windows-event-log-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/nifi-windows-event-log-processors-1.20.0-SNAPSHOT.jar
./work/nar/extensions/nifi-windows-event-log-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/jna-platform-5.12.1.jar
./work/nar/extensions/nifi-provenance-repository-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/nifi-deprecation-log-1.20.0-SNAPSHOT.jar
./work/nar/extensions/nifi-jolt-record-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/nifi-deprecation-log-1.20.0-SNAPSHOT.jar
./work/nar/extensions/nifi-hadoop-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/nifi-deprecation-log-1.20.0-SNAPSHOT.jar
./work/nar/extensions/nifi-cdc-mysql-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/mysql-binlog-connector-java-0.27.5.jar
./work/nar/extensions/nifi-standard-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/nifi-syslog-utils-1.20.0-SNAPSHOT.jar
./work/nar/extensions/nifi-standard-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/nifi-deprecation-log-1.20.0-SNAPSHOT.jar
./work/nar/extensions/nifi-standard-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/simple-syslog-5424-0.0.16.jar
./work/nar/extensions/nifi-standard-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/nifi-logging-utils-1.20.0-SNAPSHOT.jar
./work/nar/extensions/nifi-mqtt-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/nifi-deprecation-log-1.20.0-SNAPSHOT.jar
./work/nar/extensions/nifi-record-serialization-services-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/nifi-syslog-utils-1.20.0-SNAPSHOT.jar
./work/nar/extensions/nifi-record-serialization-services-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/simple-syslog-5424-0.0.16.jar
./work/nar/extensions/nifi-azure-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/logging-interceptor-4.10.0.jar
./work/nar/extensions/nifi-flow-registry-client-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/nifi-deprecation-log-1.20.0-SNAPSHOT.jar
./work/nar/extensions/nifi-hbase_1_1_2-client-service-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/logback-core-1.2.10.jar
./work/nar/extensions/nifi-ranger-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/flogger-system-backend-0.5.1.jar
./work/nar/extensions/nifi-ranger-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/logback-core-1.2.10.jar
./work/nar/extensions/nifi-ranger-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/log4j-api-2.18.0.jar
./work/nar/extensions/nifi-ranger-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/flogger-0.5.1.jar
./work/nar/extensions/nifi-ranger-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/flogger-slf4j-backend-0.5.1.jar
./work/nar/extensions/nifi-hbase_2-client-service-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/logback-core-1.2.10.jar
./work/nar/extensions/nifi-site-to-site-reporting-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/nifi-deprecation-log-1.20.0-SNAPSHOT.jar
./work/nar/extensions/nifi-ssl-context-service-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/nifi-deprecation-log-1.20.0-SNAPSHOT.jar
./work/nar/extensions/nifi-atlas-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/scala-logging_2.12-3.9.2.jar
./work/nar/extensions/nifi-social-media-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/logging-interceptor-4.10.0.jar
./work/nar/extensions/nifi-poi-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/log4j-api-2.18.0.jar
./work/nar/extensions/nifi-ldap-iaa-providers-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/nifi-deprecation-log-1.20.0-SNAPSHOT.jar
./work/nar/extensions/nifi-accumulo-services-api-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/logback-core-1.2.10.jar
./work/nar/extensions/nifi-accumulo-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/logback-core-1.2.10.jar
./work/nar/extensions/nifi-stateless-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/nifi-deprecation-log-1.20.0-SNAPSHOT.jar
./work/nar/extensions/nifi-other-graph-services-nar-1.20.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/jcabi-log-0.14.jar
./lib/logback-classic-1.3.5.jar
./lib/bootstrap/nifi-deprecation-log-1.20.0-SNAPSHOT.jar
./lib/bootstrap/logback-classic-1.3.5.jar
./lib/bootstrap/logback-core-1.3.5.jar
./lib/logback-core-1.3.5.jar
./lib/log4j-over-slf4j-2.0.6.jar

Looks like some older references to logback still work their way in there.

Thanks

**Comment by joewitt** [comment]
building/reviewing

**Comment by exceptionfactory** [comment]
Thanks for the feedback @joewitt! It looks like some NAR files included the older `logback-core`, which should also have been marked as `provided`. Adding the dependency version and default scope for `logback-core` in the root Maven configuration removed those references, and I also updated the assembly configurations to make include `logback-core` along with `logback-classic` as needed.

**Comment by joewitt** [comment]
much cleaner.  I dont see the older versions now.  Just the new stuff.  If build checks out on GH CI will merge.

**Comment by joewitt** [comment]
i did an ultra full clean build and contrib check and manual review.  all checks out.  merging. thanks

**Pull request closed without merging**
