### PR TITLE
NIFI-11793: Added documentation to indicate how to debug Python side …

### PR DESCRIPTION
**Pull request by markap14**
…of nifi framework, as well as debugging python processors themselves using VSCode's Remote debugger.

This also provides the ability to launch the Controller process in such a way that it will listen to incoming remote debug connections.

# Summary

[NIFI-00000](https://issues.apache.org/jira/browse/NIFI-00000)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — COMMENTED** [review]
Thanks for the improvement and documentation @markap14. The new properties and documentation look good in general, I just noted a couple minor property naming recommendations.

**Review by exceptionfactory — COMMENTED** [review]
Thanks for the improvement and documentation @markap14. The new properties and documentation look good in general, I just noted a couple minor property naming recommendations.

**Comment by markap14** [comment]
Thanks @exceptionfactory , agreed on the naming. Have updated and pushed new commit.

**Review by exceptionfactory — APPROVED** [review]
Thanks for making the adjustments @markap14, the latest version looks good! +1 merging

**Pull request closed without merging**
