### PR TITLE
NIFI-4092: Removing direct dependency on jaxb

### PR DESCRIPTION
**Pull request by mcgilman**
NIFI-4092:
- Removing direct dependency on jaxb.

### CODE REVIEW

**Comment by joewitt** [comment]
@mcgilman the test failures in Travis-CI appear to be informative and important.  Can you take a look?

**Comment by mcgilman** [comment]
@joewitt Looks like the previous implementation using a `com.sun` class used two space indentation. Primarily investigation suggests a few options...

- Accept a new default of 4 spaces.
- Set a property which configures an internal indentation strategy

`marshaller.setProperty("com.sun.xml.internal.bind.indentString", "  ");`

- Add a dependency on the BSD licensed stax-utils

```
<dependency>
    <groupId>net.java.dev.stax-utils</groupId>
    <artifactId>stax-utils</artifactId>
    <version>20070216</version>
</dependency>
```

which offers a similar (same?) `com.sun` class that we were previously referencing.

**Comment by joewitt** [comment]
@mcgilman in my opinion we should set the indentString property to maintain consistency with the older format

**Comment by mcgilman** [comment]
@joewitt I agree that we should remain consistent with the older format. I don't think I fully explained option 3. The stax-utils artifact appears to package the same `com.sun` class we were previously referencing but in a `javanet.staxutils` package. This may be the safer of the two options as we wouldn't be relying on an internal/undocumented `Marshaller` property.

**Comment by joewitt** [comment]
@mcgilman you explained it fine.  You just didn't indicate you had a preference :)

Let me read up on that thing.  I agree depending on internal/undoc items is uncool.

**Comment by joewitt** [comment]
Option1: Change from the old impl/dep which had 4 spaces to JDK built-in classes which is now 2.
  Pro: Removes a problematic dependency.  Con: Impacts users doing pure diffs of templates.

Option2: Set the com.sun.indent property on the marshaller.  This is not doc'd or guaranteed and could change.  If it does change it could break the app since it would throw an exception if it gets a property it doesn't understand.

Option3: Use the 2007/java.net binary you found.  Given that is from a now defunct location it is hard to really trust it from an L&N pov and it appears to have a transitive dep based on looking at its pom.  In general i dont love this option.

So my preference is in order 1, 3, 2.

What do you think @mcgilman

**Comment by mcgilman** [comment]
@joewitt I agree regarding the questionable L&N on option 3. I also agree with your take on option two. Let me update the PR.

**Comment by ravipapisetti** [comment]
Hi, We are hitting the same issue with NiFi 1.3. Any workaround how this could be solved. Interesting to know this happens only in one of the node in the cluster, even though all nodes are identical. Appreciate any help.

**Comment by joewitt** [comment]
@ravipapisetti it has been resolved and is in the nifi 1.5.0 release.  You'll need to upgrade to that version.

**Pull request closed without merging**
