### PR TITLE
NIFI-6792

### PR DESCRIPTION
**Pull request by manoj1222**
added a function in Expression Language to
Evaluate Variable value containing expression Language

Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR
enables to evaluate a variable value having an expression

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ **Yes**] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?
- [ **Yes**] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [**Yes** ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [ **Yes. OK**] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [**Yes** ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder? 
- [**Yes** ] Have you written or updated unit tests to verify your changes? 
- [ **Yes**] Have you verified that the full build is successful on both JDK 8 and JDK 11? 
- [ **Did not add new dependencies** ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [**Not applicable** ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [**Not applicable** ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [**Not applicable** ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ **Yes, I have ensured**] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by manoj1222** [comment]
If you are sure with the name `evaluateELString`, I can make the changes and you can review it again.
Let me know if you are ok with this.

**Comment by MikeThomsen** [comment]
I think that will work. `stringEL` is just not particularly intuitive.

**Comment by manoj1222** [comment]
I have made the suggested changes by you.

**Comment by MikeThomsen** [comment]
Merged. Thanks!

**Pull request closed without merging**
