### PR TITLE
NIFI-12651: Add case-insensitive field retrieval option for Record and Schema

### PR DESCRIPTION
**Pull request by mark-bathori**
# Summary

The idea is to create a separate map in the Schema with lowercase names and a separate method where the ‘fieldName’ parameter is also lowercased to make the retrieval case-insensitive.
The new value map is created with **lazy evaluation** strategy so it’s only generated when there is a method call for it. With this approach we are not storing the same mapping twice.

[NIFI-12651](https://issues.apache.org/jira/browse/NIFI-12651)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [x] Build completed using `mvn clean install -P contrib-check`
  - [x] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for proposing this new feature @mark-bathori.

The concept seems useful, but the initial implementation raises some questions. Although the lowercase field map is created lazily, it effectively duplicates the existing field map, which could have notable impacts on memory usage when processing files with hundreds of thousands of records.

Introducing a new `caseInsensitiveGetField` method makes this more accessible, but it does raise a question about whether this should be a first-class API method.

As an alternative approach, one option could be supporting an additional constructor argument to handle fields while ignoring the case sensitivity.

Either way, this seems worth further consideration before going forward.

**Comment by mark-bathori** [comment]
Thanks a lot @exceptionfactory for commenting on this. I'm happy to discuss possible solutions for this task since I was thinking a lot about how should this be implemented properly.

I was also considering the constructor parameter solution, my main concern was that usually when we are creating a `Record` ( e.g. through a `RecordReader`) we don't know how other components would like to use it so we can't determine if it should be created in case-sensitive or insensitive way. Possible solution could be if it is modifiable on the `Record` and maybe track the state with a boolean. 

Possible solution with the current approach could be if we set the original case-sensitive `Map` to be also **lazy-initialized**. This would solve the duplicated storing issue. There could be further restriction added so only one type of map can be initialized at once but both could be supported if needed.

I can also see further improvements in the current `SimpleRecordSchema` implementation in terms of memory usage. Currently it stores the schema fields in a `List` (**fields**) and also in a `Map` (**fieldMap**) where the key is the name of the record field and the value is the `RecordField` object. Since the `RecordField` object is stored twice it could be changed to store the index of the `RecordField` in the field list as the map's value instead of the RecordField itself.

I agree on moving this only to the `SimplRecordeSchema` implementation if we don't want to add this on interface level.

What is your opinion about these?

**Review by exceptionfactory — COMMENTED** [review]
Thanks for the thoughtful reply @mark-bathori.

Revisiting this discussion, making case-insensitive retrieval a first-class concept raises a number of questions.

In the current form, Records provide a format-agnostic model that maintains a level of fidelity to the original structure. There are some other Map implementation approaches that support case-insensitive lookup, which could be part of a solution.

Perhaps it would be helpful to describe some use cases. I know the Jira references some particular workarounds, but describing those might be a good way to highlight whether or not this is a good candidate for a generalized solution.

**Comment by mark-bathori** [comment]
Thanks for the reply @exceptionfactory. 

For example Kudu([NIFI-6680](https://issues.apache.org/jira/browse/NIFI-6680)) and Iceberg([NIFI-11263](https://issues.apache.org/jira/browse/NIFI-11263)) processor contains some kind of workaround for this. Both of them requires this when the NiFi side record schema and the database schema needs to be matched.

I've checked other Map implementations like Apache’s CaseInsensitiveMap but the problem I found with them is their performance is usually worse than HashMap's and it would lead to unneccesary performance degredation.

I think we can close this PR since we have a working solution currently for every module which needs a case-insensitive field retrieval. This can be reopened if we will have a new feature requiring this kind of functionality in the future.

**Pull request closed without merging**
