### PR TITLE
NIFI-924:Nifi-Camel Integration

### PR DESCRIPTION
**Pull request by PuspenduBanerjee**
working version of nifi-camel integration.
It Supports to load camel context from File, Classpath as well as to define and modify Routes on the fly.
Overall it's an implementation of feature request NIFI-924 [https://issues.apache.org/jira/browse/NIFI-924#]

Sample NiFi Template: 
[CamelProcessorTestingTemplate.xml.zip](https://github.com/apache/nifi/files/111181/CamelProcessorTestingTemplate.xml.zip)

Over and above all, this component will mitigate the need of creating  many Processors as camel integrate excellently with a lot of other products, protocols and standards available in the market, e.g. activemq, rabitmq, aws, rules engine, rest services etc. A larger list of available components/protocols is available at : 

- [http://camel.apache.org/component-list-grouped.html](http://camel.apache.org/component-list-grouped.html)

- [http://camel.apache.org/components.html](http://camel.apache.org/components.html)

### CODE REVIEW

**Comment by PuspenduBanerjee** [comment]
@olegz Please review once you get a chance.
@joewitt please find NiFi Template attached  with PR at [CamelProcessorTestingTemplate.xml.zip](https://github.com/apache/nifi/files/111181/CamelProcessorTestingTemplate.xml.zip)

**Comment by PuspenduBanerjee** [comment]
Hi Team ,
OOM Again for [NiFi openjdk-7](https://travis-ci.org/apache/nifi/jobs/105995868) build .
Can we have any permanent solution.
Details:
Tests run: 17, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 4.436 sec <<< FAILURE! - in org.apache.nifi.processors.standard.TestExecuteStreamCommand
testExecuteIngestAndUpdate(org.apache.nifi.processors.standard.TestExecuteStreamCommand)  Time elapsed: 1.592 sec  <<< ERROR!
java.lang.OutOfMemoryError: Java heap space

Marking @apiri

**Comment by joewitt** [comment]
we'd love a perm solution for the OOM issue seen in Travis-CI environment.  But so far the cause of the issue isn't known.

**Comment by PuspenduBanerjee** [comment]
Hi @joewitt 
For now the issue is happening for org.apache.nifi.processors.standard.TestExecuteStreamCommand.testExecuteIngestAndUpdate().
Where we are running a Pattern on 100MB data. So, I have modified the testcase with a sliding window matching mechanism. I hope it will work.:

    /**
     * Generates a String representation by taking a slice of backing byte[] from MockFile.
     * It's a low memory foot-print alternative to {@code new String(mockFile.toByteArray)}
     * @param mockFlowFile 
     * @param patternToMatch
     * @return
     * @throws NoSuchFieldException
     * @throws SecurityException
     * @throws IllegalArgumentException
     * @throws IllegalAccessException
     */
    private boolean matchPattern(MockFlowFile mockFlowFile, final String  patternToMatch) throws NoSuchFieldException, SecurityException, 
                                                            IllegalArgumentException, IllegalAccessException {
        final Pattern pattern= Pattern.compile(patternToMatch);
        Field dataField=MockFlowFile.class.getDeclaredField("data");
        dataField.setAccessible(true);
        byte[] byteArray = (byte[])dataField.get(mockFlowFile);
        final int sliceLength=patternToMatch.length()>(10240)?patternToMatch.length():(10240);
        final int windowLength=sliceLength-patternToMatch.length();
        int offset=0;
        StringBuilder stringBuilder=new StringBuilder();
        while(offset<=byteArray.length){
            if(pattern.matcher(stringBuilder.append(new String(Arrays.copyOfRange(byteArray, offset, (offset+sliceLength))))).find()){
                return true;
            }
            stringBuilder.delete(0, windowLength);
            offset+=sliceLength;
        };
        return false;
    }

**Comment by joewitt** [comment]
Wow great find.  Created NIFI-1456 to address.

**Comment by PuspenduBanerjee** [comment]
@joewitt  Thank You.
So, this PR fixes NIFI-1456 as well.
https://travis-ci.org/apache/nifi/builds/106119240

**Comment by joewitt** [comment]
Puspendu - thanks.  I provided an alternative patch which simply reduces the size of the test data and which resolves some IO handling issues which could also lead to test stability.  There is no reason for such large input tests anyway particularly given the intermediary byte and string copies being made.  I like your sliding expression matcher concept though.  I'd be interested to understand its function on non-uniform byte length character sets.  If it does or can work on such character sets we should see about using that instead of our current methods which require users to specify maximum buffer length.

**Comment by PuspenduBanerjee** [comment]
@joewitt For Non-Uniform charset attached piece should work.

```java
/**
     * @param rawBytes
     * @param patternToMatch
     * @return
     */
    private static boolean matchPattern(byte[] rawBytes , final String patternToMatch){
        out.println("Pattern= "+patternToMatch);
        final Pattern pattern = Pattern.compile(patternToMatch);
        final int patternByteLength=patternToMatch.getBytes().length;
        out.println("PatternByteLength= "+patternByteLength); 
        final int minSliceByteLength=2;
        final int sliceByteLength = patternByteLength > minSliceByteLength ? patternByteLength : minSliceByteLength;
        int offset = 0;
        while (offset <= rawBytes.length) {
            String s=new String(Arrays.copyOfRange(rawBytes, offset>patternByteLength? offset-(patternByteLength+1):0,
                                                   (offset + sliceByteLength)));
            out.println("Retrieved byte[]= "+s);
            if (pattern.matcher(s).find()) {
                return true;
            }
            offset += sliceByteLength;
        };
        return false;
    }
```

I tried with \:
```java
matchPattern("I♥NY♥Y♥NABCDdkk;lskiepdmclod;die;'cnjywkl;sfdsXRSHSY♥♥Y".getBytes(), "♥♥Y");
```

**Comment by olegz** [comment]
@PuspenduBanerjee We are currently in the process of releasing 0.5 which is imminent. We'll be happy to help you through this (review, polish etc) once 0.5 is out. Hope you understand.

**Comment by PuspenduBanerjee** [comment]
Will reopen for after 0.5 release.

**Comment by mahmoudimus** [comment]
Ping. Is this still worked on?

**Comment by magick93** [comment]
What happened to this PR? Is Camel not going to be integrated into Nifi?

**Comment by PuspenduBanerjee** [comment]
I think the majority here 

> What happened to this PR? Is Camel not going to be integrated into Nifi?
I think, due to Spring Integration support , none find a separate need for Camel Integration here.

**Pull request closed without merging**
