### PR TITLE
NIFI-7431 kafka exitcompression type

### PR DESCRIPTION
**Pull request by gadLinux**
#### Description of PR
Enables de client 2.1 of kafka that supports new compression types and features.

The original issue is here.
https://issues.apache.org/jira/browse/NIFI-7431

Adds new components supporting this kafka 2.1 client. Tested in lab.

### CODE REVIEW

**Comment by pvillard31** [comment]
Thanks for the contribution @gadLinux!

IIRC we introduced separate bundles to make sure we don't face any compatibility issue against Kafka between different versions. However, if there is no backward incompatibility with the Kafka clients (meaning that any 2.x client can talk to any 2.x broker - we would need to double check), I'd recommend to just keep using the existing ``nifi-kafka-2-0-nar`` and update the client version and add any property that would make sense. We could even bump the version to 2.5.0 if there is no backward compatibility issue.

@markap14 - what are your thoughts on this?

**Comment by gadLinux** [comment]
Hi, 
But client 2.0 doesn't have proper support. And it doesn't work with current installation. So I had to bump the client. I can bump the client over 2.0 if you want. This solution will be easy but I don't know if it can break anything because transitive deps.

We can try.

**Comment by pvillard31** [comment]
Yeah I totally understand. I believe that any client 2.x would work with lower versions on the broker side as long as the user does not use properties that are new and not interpreted by the broker. I don't know what is best between bumping the version and having a dedicated bundle. If we go with the bundle, I think it'd be best to use the latest version available at this time. I defer to @markap14 on this one as he worked a lot on the Kafka processors.

**Comment by markap14** [comment]
I do think it's probably better to have a separate bundle. Just because it clearly conveys the intent. It's also the case that while a newer server may be compatible with an older client, it doesn't mean that it works *well*. We've seen this in the past with Kafka where using a 1.0 client with a 1.1 server (it's entirely possible that these are not the correct versions, just using this as an example) worked but the performance was about an order of magnitude slower than using 1.0 client with 1.0 server or 1.1 client with 1.1 server. It had to do with upgrading/downgrading the protocol and was super expensive. So best to stick with matching versions. Also of note, there is a PR up already (https://github.com/apache/nifi/pull/4383) for Kafka 2.5 processors.

**Comment by gadLinux** [comment]
I rebased this branch, maybe we should decide what to do...

**Pull request closed without merging**
