### PR TITLE
NIFI-1833 - Adding Azure Storage processors

### PR DESCRIPTION
**Pull request by simonellistonball**
A little progress on a quick patch to add storage processors. Still requires some unit and integration testing. May need a little more on the documentation as well. Better supporting for Azure batching commands would be a good next step, but probably lives as a further enhancement. Comments gratefully received.

### CODE REVIEW

**Comment by simonellistonball** [comment]
This needs a little bit more work. The goal here is to use a common pattern from standard processors, however, while tests work fine, loading into NiFi causes a duplicate of the standard processor nar and therefore unpredicatable ordering. One solution to this would be to factor the base AbstractListProcessor classes out of standard processors into processor-utils. However, they have a legacy dependency on the distributed cache service which would cause a circular dependency for this refactoring. 

Short term solution would be to reimplement the trigger and state logic direct in the Azure processors, which violates DRY. 

Longer term it would be great to have clean Abstracts for some of these common custom patterns in processor-utils, but that's for another issue and another PR.

In the meantime I'll re-implement and update the PR, so please don't worry about reviews right now.

**Comment by atilcock** [comment]
Hi Simon  - are you still working on this?    Not sure if it's related to the duplicate nar issue you mentioned but I've found an issue after a restart of NIFI where the processor stops working.  i.e. implement a workflow with a putAzureBlob call.  Stop and restart NIFI and the processor no longer responds to data in the queue.

**Comment by simonellistonball** [comment]
I'm still working on this, yes. Apologies, I've not had the time I'd like to finish it off, but will be doing so very soon. The issue is very much the duplicate nar dependencies, which requires some refactoring to avoid the dependency this PR has on standard-processors.

**Comment by simonellistonball** [comment]
Latest commit should remove some of the duplicate nar circular dependency issues. It's not the cleanest way to implement this, but that really wants a common cloud util library around the way cases like listing are handles. That feels like the scope for a much greater refactoring.

**Comment by slachterman** [comment]
Quick question: is there overlap with [NIFI-1922](https://issues.apache.org/jira/browse/NIFI-1922)?

**Comment by trixpan** [comment]
@slachterman I would say so

**Comment by joewitt** [comment]
@simonellistonball can you consider closing this in favor of the approach outlined in NIFI-1922 which takes advantage of a new runtime classpath manipulation option which has been proven to work.

**Comment by slachterman** [comment]
Example for Azure Data Lake Storage using additional classpath functionality: https://community.hortonworks.com/articles/58793/hdf-20-use-ambari-to-enable-kerberos-for-hdf-clust.html

**Comment by trixpan** [comment]
@slachterman - thank you for the handy link

**Comment by trixpan** [comment]
@simonellistonball - Seems like your PR has been adopted by @jtstorck and @aperepel so closing this PR as we currently have 3 PRs for the same JIRA.

**Comment by joaocc** [comment]
@simonellistonball Hi. Was the work on Azure Storage Table dropped? I tried to find it in the current (1.8) version but only Storage Blob seems to be there. Thx

**Pull request closed without merging**
