### PR TITLE
NIFI-6253 - Fix: UI - Process Group ID display in Operate palette can…

### PR DESCRIPTION
**Pull request by rfellows**
… get out of sync when process groups are removed from different sessions.

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by mcgilman** [comment]
Will review...

**Comment by mcgilman** [comment]
@rfellows Thanks for the PR. When I run this I receive the following stacktrace:

```
Uncaught TypeError: nfCanvasUtils.loadProcessGroup is not a function
    at Object.enterGroup (nf-process-group.js?1.10.0-SNAPSHOT:1653)
    at Object.showDeepLink (nf-canvas-utils.js?1.10.0-SNAPSHOT:433)
    at Object.init (nf-graph.js?1.10.0-SNAPSHOT:213)
    at Array.<anonymous> (nf-canvas-bootstrap.js?1.10.0-SNAPSHOT:388)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Object.<anonymous> (jquery.min.js:2)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at A (jquery.min.js:4)
```

**Comment by rfellows** [comment]
I'll have a look and update the PR as needed.

**Comment by rfellows** [comment]
@mcgilman I'm not sure how i missed that in my original commit but i've fixed it with my latest commit.

**Comment by mcgilman** [comment]
@rfellows Thanks for the PR. This has been merged to master.

**Pull request closed without merging**
