### PR TITLE
NIFI-4303 Add routingKey to ConsumeAMQP processor

### PR DESCRIPTION
**Pull request by doodzio**
#### Description of PR

_Adds routing key in ConsumeAMQP processor NIFI-4303_

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [x] Have you written or updated unit tests to verify your changes?
- [x] Have you verified that the full build is successful on JDK 8?
- [x] Have you verified that the full build is successful on JDK 11?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Comment by turcsanyip** [comment]
@doodzio Thank you for your first contribution.
As far as I see, you are not assigned the Contributor role yet. Could you please request for "Jira contributor access" on the mailing list dev@nifi.apache.org?
Then please assign the Jira ticket to yourself and also set it to Patch Available status.

I tested your change and it works as expected. The code and tests look also fine.

What do you think about also adding `exchange` (from the envelope) and `queue` (from the processor property) to the outgoing FlowFile's attributes too?

**Comment by doodzio** [comment]
@turcsanyip Thx. I tootaly overlooked those steeps, I did it today.

Adding `exchange` seems ok, I am not sure that we should append something that already is definied by user.

**Comment by turcsanyip** [comment]
`ConsumeKafka` and `ConsumeJMS` add the destination as an attribute (`kafka.topic` / `jms_destination`).
It is true though, that the destination property can come from variable registry in case of those processors so it is more dynamic.
In general, it is easier to use this info in the downstream flow if it is available on the FlowFile.

**Review by turcsanyip — APPROVED** [review]
+1 LGTM

Merging to main.

**Pull request closed without merging**
