### PR TITLE
NIFI-6038 Remove scope parameter from OIDC TokenRequest

### PR DESCRIPTION
**Pull request by mosermw**
I tested this PR against Google OAuth2 API and it still works.

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by mcgilman** [comment]
@mosermw Thanks for the PR. According to the OpenId Connect specification, the scope parameter with a value of `openid` is required [1]. Additional scopes can be used and should be ignored if unrecognized.

I think the docs for ForgeRock [2] also discuss requiring the `openid` scope.

[1] https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest
[2] https://backstage.forgerock.com/docs/am/6/oidc1-guide/#register-openid-connect-clients

**Comment by mosermw** [comment]
Hey @mcgilman thanks for looking at this!

It's not the Authorization Request that's failing, and you're correct that one must have a scope.  In this case it's the Token Request [1] that's failing.

[1] - https://openid.net/specs/openid-connect-core-1_0.html#TokenRequest

**Comment by mcgilman** [comment]
@mosermw Bah. Sorry was so focused on the scope removal I didn't process the context of the change. Glancing at the docs, I'm also not seeing why we're using the `scope` parameter in the token request. I'll take another look and see if I can't remember why that ended up there in the first place.

**Comment by mcgilman** [comment]
Thanks @mosermw! This has been merged to master.

**Pull request closed without merging**
