### PR TITLE
NIFI-9525 modify lib packaging to use files from build directory

### PR DESCRIPTION
**Pull request by gforeman02**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

The current Nifi RPM build process includes a series of include/exclude package statements for organizing the resulting lib directory.  Over time, these statements become misaligned with what is actually happening in the Nifi lib directory and cause RPM deployments to fail.  This PR replaces the package statements with a single statement to include in the RPM the contents of the lib directory that have already been produced by the build.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [x] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by joewitt** [comment]
am testing this now but wow if this change is all we needed to do before that is amazing.  i wasted a lot of time using the other method :).

**Comment by joewitt** [comment]
When I do a full clean build with the rpm profile activated this happens


[ERROR] Failed to execute goal org.codehaus.mojo:rpm-maven-plugin:2.1.5:attached-rpm (build-bin-rpm) on project nifi-registry-assembly: Unable to build the RPM: Error while executing process. Cannot run program "rpmbuild" (in directory "/development/code/nifi.git/nifi-registry/nifi-registry-assembly/target/rpm/nifi-registry-bin/SPECS"): error=2, No such file or directory -> [Help 1]

mvn -T C1 clean package -Pcontrib-check,include-grpc,rpm

I'm guessing there is an RPM profile for the registry as well and it doesnt work either.  Looking into it

**Comment by exceptionfactory** [comment]
@joewitt The `rpm-maven-plugin` relies on the `rpmbuild` command being installed on the system.  Do you have it installed?

**Comment by joewitt** [comment]
hmm good piont.  this is a new system on which i havent yet done this ...

**Pull request closed without merging**
