### PR TITLE
NIFI-1146  Allow GetKafka to be configured with auto.offset.reset to "largest" or "smallest"

### PR DESCRIPTION
**Pull request by naveenmadhire**

### CODE REVIEW

**Comment by naveenmadhire** [comment]
Screenshot 1

image


Screenshot 2 - Users can select either "largest" or "smallest"

image

**Comment by naveenmadhire** [comment]
Screenshot 1 - To show the new option
image


Screenshot 2 - Users can select either "largest" or "smallest"
image

**Comment by markap14** [comment]
Naveen, thanks for contributing this back! Certainly a nice addition to the GetKafka processor. The patch looks good, but I did have just a couple of small points of feedback.

For the PropertyDescriptor added, it may helpful to explain in a little more detail in the "description" what exactly the property controls & when it takes effect, for those who may be less familiar with Kafka.

I was also a bit confused by the addition of the @WritesAttribute annotation - it indicates that the outgoing FlowFile will have an attribute named "auto.offset.reset" but that attribute is not added to the FlowFile. This may be a misunderstanding of what the @WritesAttribute annotation is used for perhaps?

Otherwise, the patch looks great. Thanks again for taking the time to submit the pull request!

**Comment by naveenmadhire** [comment]
Closing the pull request. As I've messed up with the commits. I will open a new one soon. Sorry for the trouble.

**Comment by markap14** [comment]
@naveenmadhire no trouble at all :) Looking forward to the new pull request.

**Pull request closed without merging**
