### PR TITLE
NIFI-11857 - CLI - recursively change version of processors

### PR DESCRIPTION
**Pull request by pvillard31**
# Summary

[NIFI-11857](https://issues.apache.org/jira/browse/NIFI-11857) - CLI - recursively change version of components

With and without scoping the process group where this should be applied.

````
% ./cli.sh nifi change-version-processor -u http://127.0.0.1:8080/nifi-api --group org.apache.nifi --artifact nifi-poi-nar --version 2.0.0-SNAPSHOT --extension-name org.apache.nifi.processors.poi.ConvertExcelToCSVProcessor -pgid 8e04f78a-0189-1000-0e6f-007ca6b51dbc

#   Name                         ID                                     Type                         Run Status   Version          
-   --------------------------   ------------------------------------   --------------------------   ----------   --------------   
1   ConvertExcelToCSVProcessor   8e050129-0189-1000-62ba-09fe4588412c   ConvertExcelToCSVProcessor   RUNNING      2.0.0-SNAPSHOT   

% ./cli.sh nifi change-version-processor -u http://127.0.0.1:8080/nifi-api --group org.apache.nifi --artifact nifi-poi-nar --version 1.22.0 --extension-name org.apache.nifi.processors.poi.ConvertExcelToCSVProcessor -pgid 8e04f78a-0189-1000-0e6f-007ca6b51dbc

#   Name                         ID                                     Type                         Run Status   Version   
-   --------------------------   ------------------------------------   --------------------------   ----------   -------   
1   ConvertExcelToCSVProcessor   8e050129-0189-1000-62ba-09fe4588412c   ConvertExcelToCSVProcessor   RUNNING      1.22.0    

% ./cli.sh nifi change-version-processor -u http://127.0.0.1:8080/nifi-api --group org.apache.nifi --artifact nifi-poi-nar --version 2.0.0-SNAPSHOT --extension-name org.apache.nifi.processors.poi.ConvertExcelToCSVProcessor                                           

#   Name                         ID                                     Type                         Run Status   Version          
-   --------------------------   ------------------------------------   --------------------------   ----------   --------------   
1   ConvertExcelToCSVProcessor   8d695704-0189-1000-9326-47d088697fe3   ConvertExcelToCSVProcessor   RUNNING      2.0.0-SNAPSHOT   
2   ConvertExcelToCSVProcessor   8e050129-0189-1000-62ba-09fe4588412c   ConvertExcelToCSVProcessor   RUNNING      2.0.0-SNAPSHOT   

% ./cli.sh nifi change-version-processor -u http://127.0.0.1:8080/nifi-api --group org.apache.nifi --artifact nifi-poi-nar --version 1.22.0 --extension-name org.apache.nifi.processors.poi.ConvertExcelToCSVProcessor

#   Name                         ID                                     Type                         Run Status   Version   
-   --------------------------   ------------------------------------   --------------------------   ----------   -------   
1   ConvertExcelToCSVProcessor   8d695704-0189-1000-9326-47d088697fe3   ConvertExcelToCSVProcessor   RUNNING      1.22.0    
2   ConvertExcelToCSVProcessor   8e050129-0189-1000-62ba-09fe4588412c   ConvertExcelToCSVProcessor   RUNNING      1.22.0    
````

With specifying the current version:

````
% ./cli.sh nifi change-version-processor -u http://127.0.0.1:8080/nifi-api --group org.apache.nifi --artifact nifi-poi-nar --version 1.22.0 --extension-name org.apache.nifi.processors.poi.ConvertExcelToCSVProcessor --current-version 1.21.0

#   Name                         ID                                     Type                         Run Status   Version   
-   --------------------------   ------------------------------------   --------------------------   ----------   -------   
1   ConvertExcelToCSVProcessor   8d695704-0189-1000-9326-47d088697fe3   ConvertExcelToCSVProcessor   RUNNING      1.22.0    

% ./cli.sh nifi change-version-processor -u http://127.0.0.1:8080/nifi-api --group org.apache.nifi --artifact nifi-poi-nar --version 1.22.0 --extension-name org.apache.nifi.processors.poi.ConvertExcelToCSVProcessor --current-version 1.21.0

#     Name    ID                                     Type    Run Status   Version      
---   -----   ------------------------------------   -----   ----------   ----------   

````

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by pvillard31** [comment]
Something similar will need to be done for other components: controller services, reporting tasks, parameter providers, etc.

**Review by exceptionfactory — COMMENTED** [review]
> Something similar will need to be done for other components: controller services, reporting tasks, parameter providers, etc.

Thanks for highlighting this detail @pvillard31. It looks like this new command requires a decent amount of code, and so extending the same approach to other types of components seems like it would have a good deal of overlap. Rather than introduce a specific command for just Processors, would it make more sense to consider all the component types together in a common command?

**Comment by pvillard31** [comment]
Hey @exceptionfactory - thanks for looking into this. Not sure when I'll be able to find time to get back to this in the near future. The reason I didn't tackle controller services is that it raises some questions such as: after changing the version, when we re-enable the controller service, should we also restart referencing components? I could definitely look into reporting tasks though, should be easy. Thoughts for controller services?

**Comment by exceptionfactory** [comment]
Thanks for the reply @pvillard31, that's a very good point about Controller Services. It sounds like it is necessary to handle them separately, and thus calling them out in a separate command makes more sense. With that background, this approach looks good as it stands, and I can take a closer look soon.

**Review by exceptionfactory — APPROVED** [review]
Thanks again for introducing this new command @pvillard31, looks good! +1 merging

**Pull request closed without merging**
