### PR TITLE
NIFI-1887 Updating default timeout in Admin Guide

### PR DESCRIPTION
**Pull request by jvwing**
Updating the default setting for `nifi.processor.scheduling.timeout` in the Admin Guide.

### CODE REVIEW

**Comment by alopresto** [comment]
Looks good to me. Want to merge it yourself with your new committer powers?

**Comment by jvwing** [comment]
My powers are weak :(.  I waded through the new committer docs that seem heavy on Subversion setup, and I have not verified git access.  If you don't mind me thrashing on this PR a bit, this does seem like a good place to start.  Thanks for suggesting it.

**Comment by alopresto** [comment]
It definitely takes some getting used to. Here is a [cheatsheet](https://gist.github.com/alopresto/c05485f80799cd3ba02461b07f1e82de) I wrote for myself. This PR is a great one to learn on. Ping me if you need anything.

**Comment by jvwing** [comment]
@alopresto, thanks for your help.  Your cheatsheet is a great idea, I would have missed the 0.x branch without it.

**Comment by alopresto** [comment]
Should have mentioned that you're not required to put the "Signed-off-by" when merging your own commits. As long as they've been reviewed by another committer, you can just merge them. I sometimes forget and include it accidentally because it's included in the aliases I use, so it's not a big deal.

**Pull request closed without merging**
