### PR TITLE
NIFI-3205: Ensure that FlowFile Repository is updated with any Transi…

### PR DESCRIPTION
**Pull request by markap14**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

…ent Content Claims when session rollback occurs

### CODE REVIEW

**Comment by jackowaya** [comment]
Too far out of my comfort zone to give a true +1. The only thing I couldn't figure out is how the repoRecord object in StandardProcessSession works. It looks like it falls out of scope, but there must be some magic going on with that context call.

All that to say: the tests look good to me. If they're passing, this is good

**Comment by markap14** [comment]
@jackowaya thanks for verifying. The Repo Record object is stored in a HashMap in StandardProcessSession - all of them except for the TransientClaimRepositoryRecord, which gets created in the rollback() method. That one is needed only to pass to the FlowFile Repository and then it falls out of scope.

**Comment by joewitt** [comment]
@markap14 please see comments i left on the JIRA.

**Comment by joewitt** [comment]
based on mark's explanation of my observation in reviewing am now a +1.

merged to master.  thanks

**Pull request closed without merging**
