### PR TITLE
NIFI-6197 HBase Client Service uses a bad default for retries

### PR DESCRIPTION
**Pull request by lfrancke**
This changes the default to 15 as it is as of [HBASE-19660](https://issues.apache.org/jira/browse/HBASE-19660).

I ran contrib-check successfully.

### CODE REVIEW

**Comment by lfrancke** [comment]
Thanks for the background information. I understand and yes that's unfortunate but I think that's a pill we should swallow.

The way it is now normal things like when HBase moves a Region will be a fatal error. That's not good. The default used to be 10 and was upped to 15 recently.

I've actually tested today and I believe this to be even worse: The default is set to 1 so it overrides whatever is set in an hbase-site.xml. That's definitely not good. Ideally I think we should just remove the default to be honest. It _should_ fall back to the hardcoded default in HBase anyway. So I don't really see a reason to provide this option at all.

**Comment by bbende** [comment]
The reason for the option is that you can use the service without an hbase-site.xml by specifying the ZK Quorum, ZK Port, and ZK ZNode directly in the service. Although this is probably an uncommon use-case we can't assume no one is using it like this, so we have to keep the existing properties.

Also, we don't necessarily have to rely on the retry within the client, anyone can also built retry logic into their flow to route failure relationships from hbase related processors through a retry loop. I'm not totally disagreeing about increasing the default from 1, but just pointing at that I don't think users are in a terrible place as is.

**Comment by lfrancke** [comment]
Actually: I'm using it like that (i.e. without an hbase-site.xml) so I do appreciate that those options are there. But I believe that the retry option is not needed to connect to HBase. It feels very much like the odd one out from all those options.

I'll try to run a test later today against HBase without an explicitly set retry.

I'm in favor of either (ordered by priority):
1. removing the retry config option altogether or
2. remove the default (and the validation that it needs to be set) to rely on the HBase default but people can override it here or
3. change the default from 1 to 15 but make it so that hbase-site.xml overrides the setting (this is what I thought would happen from my interpretation of the documentation string)
4. change the default from 1 to 15

**Comment by lfrancke** [comment]
I verified that _not_ setting client retries defaults to 15 in HBase 2.0. So there's no reason to force users to manually choose a value and the default isn't great.

I'll change this pull request to implement option two from above. I believe options 3 and 4 don't make much sense considering that we can rely on the sane defaults that HBase itself provides.

**Comment by bbende** [comment]
I personally like #3 so that a NiFi user without a site xml can easily change the value. I still don't fully understand why we need to retry something 15 times, if it hasn't worked after 3-4 times do we really expect it to start working?

**Comment by lfrancke** [comment]
Option #2 will allow that as well!
It'll just remove the hardcoded default in NiFi (deferring to what HBase deems a reasonable default) but it will allow everyone to override the default (and also a potential value from `hbase-site.xml`).

And yes, we do :)
One example: A RegionServer crashes with lots of WALs. Those need to be processed by the new RegionServers taking over the duties of the old one. For that they need to split/read them etc.
This can take a significant amount of time but is still "expected".

I'd like to widen the scope of this PR & Jira to include fixing deprecations in the HBase 2 API as well as fixing the other properties (i.e. ZooKeeper parent node is not required, neither is ZooKeeper client port, both come with sane defaults). I'm running contrib-check now and will update then.

**Comment by lfrancke** [comment]
Uhm... I believe I broke my Pull Request somehow....trying to repair or I'll create a new one.

**Comment by lfrancke** [comment]
I'll have to open a new Pull Request. I'll reference this one. I have no idea what I did to break this :)

**Pull request closed without merging**
