### PR TITLE
NIFI-9060 Improve HTTP Cookie Path Handling

### PR DESCRIPTION
**Pull request by exceptionfactory**
#### Description of PR

NIFI-9060 Refactors HTTP cookie processing to improve integration when running NiFi behind a reverse proxy server. The `nifi.web.proxy.context.path` property provides the option for NiFi to accept forwarded context paths using HTTP headers such as `X-ProxyContextPath`. Instead of using the hard-coded root path `/` for HTTP cookies, the new `ApplicationCookieService` interface and implementation support setting the path based on the proxy header when provided.

Additional changes include adjusting the prefix of the `Authorization-Bearer` cookie name from `__Host-` to `__Secure-`.  The [__Host-](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis#section-4.1.3.2) prefix requires the cookie `Path` property set to `/`, necessitating the change to [__Secure-](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis#section-4.1.3.1) in order to support different path values.  The `__Secure-` prefix works in conjunction with the `Secure` property to ensure that the client will only send the cookie over HTTPS.

Several login and logout JavaScript functions included hard-coded `window.location` redirects to `/nifi`, which did not function correctly when running behind a reverse proxy server.  Other functions use the `../nifi/` path, which works in both reverse proxy and standard configurations, and also avoids unnecessary redirects from `/nifi` to `/nifi/`.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [X] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [X] Have you written or updated unit tests to verify your changes?
- [X] Have you verified that the full build is successful on JDK 8?
- [X] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by shearn89** [comment]
If this fixes the login/logout issues behind a reverse proxy, I'll be keen to give this a test!

**Comment by exceptionfactory** [comment]
> If this fixes the login/logout issues behind a reverse proxy, I'll be keen to give this a test!

Thanks @shearn89, feel free to give it a try.  Is there an existing Jira issue for the reverse proxy issues you are observing?  If you can provide more background in comments on this Jira issue, or a new Jira issue, that would also be helpful.

https://issues.apache.org/jira/browse/NIFI-9060

**Comment by shearn89** [comment]
> > If this fixes the login/logout issues behind a reverse proxy, I'll be keen to give this a test!
> 
> Thanks @shearn89, feel free to give it a try. Is there an existing Jira issue for the reverse proxy issues you are observing? If you can provide more background in comments on this Jira issue, or a new Jira issue, that would also be helpful.
> 
> https://issues.apache.org/jira/browse/NIFI-9060

No worries - yes, there is NIFI-7033, and this PR seems to indicate there's probably others relating to how redirects are handled. I've had a stab at making the changes myself but my JS/Java isn't so good! I've just signed up for an account on Jira and left a comment, I'll see if I can produce something to easily replicate the issue I'm seeing. Effectively it's the same issue where the redirect on login/logout ignores the context path, so I go from https://localhost:8080/nifi/nifi/login to https://localhost/nifi

**Comment by exceptionfactory** [comment]
Thanks for the additional comments and link to NIFI-7033.  I encountered the login and logout redirect issue while testing this PR, so it should address the problem reported in NIFI-7033.

**Comment by thenatog** [comment]
Tested this out also, trying to use a proxy with LDAP authentication had some funky behavior where I would log in, it would redirect to the incorrect proxy path and the cookie would be added under the '/' (root) path. Then I would not be authenticated, I could hit the 'Home' button in the NiFi UI which would redirect to the IP address version of the hosted NiFi and would have to log in again.

With this PR all the issues went away and there were no longer strange redirects to the NiFi host IP and all activity is presented under the reverse proxy https://address/port/proxypath/*. I also checked that the cookie is now stored with the correct proxy.context.path.

**Comment by thenatog** [comment]
+1 will merge.

**Pull request closed without merging**
