### PR TITLE
NIFI-10837 fixing flaky test in TestXMLReader

### PR DESCRIPTION
**Pull request by TheGreatRandall**
# Summary

[NIFI-10837](https://issues.apache.org/jira/browse/NIFI-10837)
Following the problem in the issue NIFI-10837. I dived deep to the class "TestXMLReaderProcessor" where the record has been transfer to String and stored in records.
After several printouts and checking log files and view the code in Record interface, we found that we can actually get the value and field of each record. 

The reason assertion can't pass is that the record is implemented as hashmap. When record.toString(), the order of the data is non-deterministic.

Since the record.toString() return a string variable, I did not really want to change too many codes. And the onTrigger function only put the string variable to records List. So I create a String variable to make the record in a specific format. As I said before, we can get value of the record by given function record.getValue("field")
```
String str="MapRecord[{COUNTRY="+record.getValue("COUNTRY").toString()+", ATTR_ID="+record.getValue("ATTR_ID").toString()+", NAME="+record.getValue("NAME").toString()+", AGE="+record.getValue("AGE").toString()+"}]";

```
By changing this, the compile can pass and the bug has been fixed. It is not flaky anymore and can pass the NonDex's check.
# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X] Pull Request based on current revision of the `main` branch
- [X] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [X] JDK 8
  - [ ] JDK 11
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for the contribution @TheGreatRandall. Please review the automated checks to correct the code style violations. The changes also break the unit test, so a different approach may be necessary.

**Comment by TheGreatRandall** [comment]
> Thanks for the contribution @TheGreatRandall. Please review the automated checks to correct the code style violations. The changes also break the unit test, so a different approach may be necessary.

Hi @exceptionfactory. Thank you for your feedback. May I know what part of unit tests been broken? And could you more specific about a different approach? Thank you!

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
@TheGreatRandall rather than changing the `TestXMLReaderProcessor` to build a custom representation of the Map, it looks like it would be better to trace the source of the problem. The `XMLRecordReader` creates a `HashMap` for embedded records, which might be part of the problem, but more investigation appears to be necessary.

**Comment by exceptionfactory** [comment]
@TheGreatRandall as noted previously, it would be best to trace this problem to the root cause instead of making adjustments further down. I am closing this pull request for now, but feel free to follow up on this issue and open a new pull request after evaluating the root cause with a potential solution.

**Pull request closed without merging**
