### PR TITLE
NIFI-2767 Periodically reload properties from file-based variable registry properties files

### PR DESCRIPTION
**Pull request by jfrazee**
There's one implementation decision I'm curious to hear comments on: If the schedule property is blank or 0s, should it disable the reloading? It doesn't do that at the moment.

### CODE REVIEW

**Comment by joewitt** [comment]
@jfrazee if this is still something you'd like to pursue can you rebase. I can work with you on it.  Not sure about lifecycle implications of this sort of thing though.  So long as it is only the var reg values being reloaded then it is probably fair game.

**Comment by trixpan** [comment]
@jfrazee any chance of rebasing this? 

Keen to revisit this PR and get the review going, otherwise happy for you to close it as well.

Cheers

**Comment by jfrazee** [comment]
@trixpan Just rebased it again. Made some minor changes: using MD5SumMonitor with the watcher now because the last modified monitor wasn't reliably testable, setting the check schedule to 0 disables it, and cleaned up the tests.

In the JIRA the question of whether this was safe was brought up. From the standpoint of will reloading the map in the FileBasedVariableRegistry break anything core, I think the answer is no (it's only used in EL value lookups), so, assuming I didn't make anything too buggy, it's safe in that respect. From the standpoint of will it be possible to build flows that don't behave like the author was expecting if they expected stuff to be static, the answer is probably yes.

**Comment by pvillard31** [comment]
Hey @jfrazee - I think we can close this PR with the new feature to define variables at Process Group level through the UI.

**Pull request closed without merging**
