### PR TITLE
[NIFI-2844] Update CSS styles for Cluster Summary Dialog icons and refresh button.

### PR DESCRIPTION
**Pull request by scottyaslan**

### CODE REVIEW

**Comment by scottyaslan** [comment]
Please do not merge....I will address the comments in https://issues.apache.org/jira/browse/NIFI-2844 to match these styles with that of the operate palette.

**Comment by moranr** [comment]
@scottyaslan let's go ahead and get this in since the issue is fixed and the icons are now visible. I'll file a separate jira to completely update the styling.

**Comment by mcgilman** [comment]
Reviewing...

**Comment by scottyaslan** [comment]
@moranr @mcgilman I was able to update the styles to match the operate palette so please take a look.

**Comment by mcgilman** [comment]
Thanks @scottyaslan. This has been merged to master.

**Pull request closed without merging**
