### PR TITLE
NIFI-1751 Added proxy authentication in InvokeHttp processor

### PR DESCRIPTION
**Pull request by pvillard31**

### CODE REVIEW

**Comment by apiri** [comment]
Hey @pvillard31,

I did a review of this and it seems to work mostly well using Squid with the following config:

```
auth_param basic program /usr/local/Cellar/squid/3.5.19/libexec/basic_ncsa_auth /usr/local/etc/squid.passwords
auth_param basic realm proxy
acl authenticated proxy_auth REQUIRED
http_access allow authenticated
http_port 3128
```

and created a proxy user via:
```
htpasswd -c /usr/local/etc/squid.passwords testuser
```

I read through some of your commentary on the ticket and was not able to recreate the conditions you were seeing for HTTPS sites.  I tried a few, and all seemed to work as anticipated.  I did, however, see the "Too many follow up requests" when using wrong credentials (invalid username/password combination).  

In terms of handling this, I saw the folks on square/okhttp#2464 recommended using the `Response.priorResponse()` to track such issues in the Authenticator.

Let me know your thoughts on how to address that, but overall functions as anticipated and code looks fine.

**Comment by pvillard31** [comment]
Hey @apiri,

Many thanks for the review!

Regarding HTTPS, at the time I submitted the PR I was testing it with CCProxy (on Windows computer). I can't test it again with this setup before the WE but if you didn't see the issue, it sounds good to me :)

I'll try to setup Squid on my Mac and add a control using the ``Response.priorResponse()`` but, right now, not sure to see how this should be done (get the previous response and compare it with the new one and stop if looping ?). I'll keep you posted unless you want to do it.

**Comment by apiri** [comment]
Actually, I think the Response#priorResponse probably doesn't apply to our case after thinking about it a bit more.  The key way to avoid the issues seen is a flag/counter within that authenticator to track if an attempt to authenticate has been made and then throw an exception in that case.  I think the handling is fine now, but we can bypass the HTTP client's internal retries.

**Comment by pvillard31** [comment]
Yep, not sure it's worth it. I think it is fine to let the PR as is.

**Comment by apiri** [comment]
@pvillard31 Sounds fair.  Will get this incorporated.  Thanks for the contribution.

**Pull request closed without merging**
