### PR TITLE
NIFI-2440 - Add 'file.lastModifiedTime' attribute to ListSFTP processor

### PR DESCRIPTION
**Pull request by kirkalicious**
Added 'file.lastModifiedTime' attribute to ListFileTransfer, which is
the abstract class extended by ListSFTP.
String literal attribute names were replaced with static references to
attribute name constants in ListFile.
ListFileTransfer stores the 'file.lastModifiedTime' attribute in the
format specified in ListFile.FILE_MODIFY_DATE_ATTR_FORMAT

### CODE REVIEW

**Comment by jskora** [comment]
@kirkalicious, thanks!  The changes look good and tests check out fine.

I'd prefer to move the constants to a parent common to ListFileTransfer and ListFile, but the only common parent is AbstractListProcessor which is not specifically "file" oriented and I prefer the reference as you have it to duplicating the constants.

I will commit this tomorrow, unless you, @joewitt, or someone else suggests an alternative.

Should this go into the 0.x branch as well?

**Comment by joewitt** [comment]
Should it go into the 0.x branch:
 It does not meet the criteria for backporting so doing so would require a specific need and willing merger.

The use of ListFile statics seems ok to me personally given their highly related nature and purpose - in this case.

I was initially concerned about the explicit use of Locale.US for the formatter though I see we do have docs indicating that this is the case in ListFile.  Those doc lines should probably be carried forward to our writes attributes calls here too as that format is pretty specific especially for those who use/prefer a different locale.  Ultimately we should perhaps allow it to use whatever is the default locale for formatting on a given system though that has its own tradeoffs.

**Comment by jskora** [comment]
@joewitt Thanks, from what I can tell looking at JDK source the format spec drives the output more than the Locale, so I agree that the comments should cover it.

@kirkalicious can you add the date format to the WritesAttribute description in ListSFTP like it is in [ListFile](https://github.com/apache/nifi/blob/master/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ListFile.java#L95)?  I will commit it once you are done.

Thanks!

**Comment by kirkalicious** [comment]
Done

**Comment by jskora** [comment]
@kirkalicious Please close this, I committed it, but I transposed the PR number in the comment.

**Comment by trixpan** [comment]
@jskora closed it.

Whenever this happens you can simply push an empty commit to git with the fixed reference to the PR

**Pull request closed without merging**
