### PR TITLE
NIFI-3221 ExecuteStreamCommand: Add a new property for setting the argument passing strategy, either …

### PR DESCRIPTION
**Pull request by ottobackwards**
…the existing parameter, or by adding new dynamic parameters, along with implementation and tests

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [-] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [-] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [-] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [x] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Comment by ottobackwards** [comment]
per @joewitt , tagging folks who have worked on this processor to try to scare up a review.
@JPercivall , @mattyb149 , @apiri , @joewitt, git shows you all as having experience with this, can you take a look?

**Comment by ottobackwards** [comment]
Anyone able to give this a peek?  Just trying to keep it active

**Comment by ottobackwards** [comment]
`touch pr#3396`

**Comment by joewitt** [comment]
+1 based on reviewing code/unit tests. Running full clean build and if good will merge.  THanks

**Comment by ottobackwards** [comment]
Thanks @joewitt!

**Pull request closed without merging**
