### PR TITLE
MINIFI-488: Allow flow construction from YAML config

### PR DESCRIPTION
**Pull request by mattyb149**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

Moves core MiNiFi modules to NiFi codebase, allows the specification of a MiNiFi config.yaml to replace bootstrap.conf and nifi.properties and to provide a static flow in NiFi. This is part of a larger effort (MINIFI-422) to align MiNiFi and NiFi codebases. The first commit is from Aldrin Piri who led the way on this effort.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?

- [ ] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on both JDK 8 and JDK 11?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by apiri** [comment]
reviewin'

**Comment by mattyb149** [comment]
Definitely pros and cons to both. If we incrementally bring over code from MiNiFi, we need to keep up to date with any commits that are happening in the MINIFI repo, plus there's the duplication as you mentioned. Working in a branch until MiNiFi is fully in NiFi means we have to keep up with commits in NiFi master on the branch, some of which may be fairly invasive.

If I had to pick, I think the branch strategy is the better of the two, as the code can be brought over "all at once" so to speak, and we don't have to worry about refactoring code that we bring in piecemeal. The final PR will be a beast but as you said we'll have to pay the price someday, better to only pay it once.

If you agree, I can close this PR and continuing working in my branch.

**Comment by apiri** [comment]
I think it is fair to do this piecewise.  Maybe make this a branch against our core repo and iteratively feed in PRs along the way?  Might help in striking the balance of getting the refactoring/inclusion correct without dropping a massive PR in there?

**Comment by mattyb149** [comment]
Ah you were talking about the middle ground the whole time, went right over my head :) So, I can push a branch called `MINIFI-422` up to the Apache repo, then we can do PRs against that branch until it's ready as a single PR against master?

**Comment by apiri** [comment]
@mattyb149 Yeah, it seems to make sense.  If you are onboard with that approach, maybe we leave the lower commits as squashed items for each item we are tracking.  We can build on top of those with one or more commits for a given issue being worked.  Does that sound like a reasonable approach?

**Pull request closed without merging**
