### PR TITLE
NIFI-6385 Added signal.id penalization

### PR DESCRIPTION
**Pull request by ijokarumawak**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

Adding an ordering mechanism something like 'order by priority attribute grouped by signal id':

- Added an internal state at Wait to track when each signal.id should be checked again in case it did not match release criteria
- Added a Wait processor property to specify signal.id re-check duration, "Wait Penalize Duration"
    - Similar to what 'Penalty Duration' does, but not for per FlowFile, but for signal.id unit. This is required because if there are multiple signal.ids, 'aa' and 'bb', then each signal.id has multiple FlowFiles with different priority. When Wait processor checks signal.id 'aa' and found 'aa' is not notified yet, it needs to check 'bb' at the next run
- Added FlowFile filtering at Wait processor using above data to decide which signal.id to check

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [x] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by aramatev** [comment]
@ijokarumawak is there some kind of limit as to the number of flowfiles or signals that flow through? like 16? 

I have 17 items in the queue and cant pop off the last one off the queue. 
I enabled logging and looking at the logs I see all the UUIDs show up from position 1-16 in the logs , but never the one in position 17. So it seems like its not being evaluated and that is why its not getting popped off the queue. 

But any amount less than that, i can use PriorityAttributeQueue, and pop off using any signal. so we're close..

```
2019-06-20 15:39:39,450 DEBUG [Timer-Driven Process Thread-5] org.apache.nifi.processors.standard.Wait Wait[id=750f7f2c-016b-1000-907d-5bc1ca764b99] No release signal found for 80dc2e06-f305-4157-b8dc-d9605e416a1a on FlowFile StandardFlowFileRecord[uuid=18c03aed-cf2b-430f-95a4-231fd8cdda6a,claim=,offset=0,name=18c03aed-cf2b-430f-95a4-231fd8cdda6a,size=0] yet
```

**Comment by ijokarumawak** [comment]
@aramatev That's a very good test, thanks for hardening the processor!

There is a limitation of number of signals being processed at each Wait run.
Let's say Wait is configured with:
- Run Schedule = 1 sec
- Wait Penalize Duration = 3 sec
- Release Signal Identifier = `${uuid}`

And there are 5 FlowFiles F1, F2 ... F5 in the 'wait' relationship.
Then the signal for F5 is notified.

Wait will work as follows:
1. At 00:00 Wait checks the signal for F1, not found, and penalize F1 (till 00:03)
2. At 00:01 Wait checks the signal for F2, not found, and penalize F2 (till 00:04)
3. At 00:02 Wait checks the signal for F3, not found, and penalize F3 (till 00:05)
4. At 00:03 Wait checks the signal for F4, not found, and penalize F4 (till 00:06)
5. At 00:04 Wait checks the signal for F1 again, because it's not penalized any longer
6. Repeat above cycle, thus F5 will not be released until one of F1 ... F4 is released

There are limitation of number of signals can be checked based on the combination of 'Run Schedule' and 'Wait Penalize Duration'.

To mitigate such limitation, increasing 'Run Duration' is recommended. By increasing 'Run Duration', Wait processor can keep being scheduled for that duration. For example, with 'Run Duration' `500 ms`, Wait can be loop through all 5 queued FlowFiles easily at a single run.

I think we need to document that, too. I'll add another commit.

**Comment by ijokarumawak** [comment]
@aramatev I've added additional details documentation. Please check to find if that is helpful.

@markap14 I've closed the previous PR, and addressed the issue with a different approach in this PR. Would you be able to review this one? Thanks!

**Comment by aramatev** [comment]
@ijokarumawak thank you for explaining, with the following I am able to get the performance I desire.

Run Schedule = 0 sec
Wait Penalize Duration = 1 sec
Release Signal Identifier = ${uuid}

From logging I could see (even on my laptop), its able to loop through about 450+ flowfiles in a second, or rather. Before my wait penalty was too short - at 1ms, so onTrigger() was not able to see the rest of the flowfiles.

Thank you for your work!

@markap14 The commit looks good, when can we expect this in the product?

**Comment by markap14** [comment]
Thanks for the patch @ijokarumawak and thanks for verifying also, @aramatev . Was able to verify the behavior on my side as well. This has been merged to master, so it should be available in the next minor release.

**Pull request closed without merging**
