### PR TITLE
NIFI-11686 upgrade Elasticsearch low-level REST client to 8.13.3

### PR DESCRIPTION
**Pull request by ChrisSamo632**
# Summary

[NIFI-11686](https://issues.apache.org/jira/browse/NIFI-11686) upgrade Elasticsearch low-level REST client to 8.13.3

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [x] Build completed using `mvn clean install -P contrib-check`
  - [x] JDK 21

### UI Contributions

- ~~[ ] NiFi is modernizing its UI. Any contributions that update the [current UI](https://github.com/apache/nifi/tree/main/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui) also need to be implemented in the [new UI](https://github.com/apache/nifi/tree/main/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi)~~

### Licensing

- [x] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- ~~[ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files~~

### Documentation

- ~~[ ] Documentation formatting appears as expected in rendered files~~

### CODE REVIEW

**Comment by ChrisSamo632** [comment]
Tested against (Docker based) Elasticsearch instances.

If I get a chance (or someone else does), it would be worth testing against an AWS OpenSearch instance to see whether the existing NiFi components are compatible when using the upgraded Elastic-provided dependencies.

**Comment by joewitt** [comment]
@ChrisSamo632 pulling down locally and will run the full build with CI bits as well.  thanks

**Comment by ChrisSamo632** [comment]
I managed to create an AWS OpenSearch Domain and successfully tested against that using BASIC Auth through the NiFi components 👍

I spotted that Point in Time searches aren't possible in OpenSearch (they're an Elastic XPack feature, so fair enough) - so I updated the processor docs to indicate that.

Notes added to the Jira ticket.

There's plenty more that could be done for OpenSearch, e.g.
- allow AWS Auth (hopefully with the existing NiFi AWS Controller Services)
- use the AWS OpenSearch client libraries instead (there might be additional functionality that NiFi could better use)
but they can be the subject of future tickets as/when people need them

**Comment by joewitt** [comment]
awesome turnaround thanks.  merged.

full clean build w contrib check + CI/integration tests.

**Pull request closed without merging**
