### PR TITLE
NIFI-11906 Update nifi-resources Description For Consistency

### PR DESCRIPTION
**Pull request by mr1716**
# Summary

[NIFI-11906](https://issues.apache.org/jira/browse/NIFI-11906)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI-11906) issue created

### Pull Request Tracking

- [X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X] Pull Request based on current revision of the `main` branch
- [X] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — APPROVED** [review]
This particular change is not generally necessary, so I do not recommend making similar changes in other places, but I will proceed to merge this particular change for now. +1

**Comment by mr1716** [comment]
@exceptionfactory Ok, thanks. Was just noticing that the Description for this wasnt consistent with everything else. If I notice something like this going forward, what would be the best way to get it to be consistent?

**Comment by exceptionfactory** [comment]
That's a good question, the descriptions are ad-hoc, some modules do not any description. I would recommend leaving them, unless there are actual spelling or grammar mistakes.

**Comment by mr1716** [comment]
@exceptionfactory Thanks, will do. Just thought that this might look better for consistency.

**Comment by exceptionfactory** [comment]
Sure, thanks for the attention to detail!

**Pull request closed without merging**
