### PR TITLE
NIFI-2485 - Updating standalone defaults, adding logging

### PR DESCRIPTION
**Pull request by brosander**

### CODE REVIEW

**Comment by alopresto** [comment]
I would like to see the log output contain a line for each host generated, specifying the output directory, hostname, and port. 

Example:
```bash
hw12203:...assembly/target/nifi-toolkit-1.0.0-SNAPSHOT-bin/nifi-toolkit-1.0.0-SNAPSHOT (pr790) alopresto
🔓 0s @ 10:55:43 $ ./bin/tls-toolkit.sh standalone -n host1,host2
16/08/04 10:56:00 INFO standalone.TlsToolkitStandaloneCommandLine: No nifiPropertiesFile specified, using embedded one.
16/08/04 10:56:00 INFO standalone.TlsToolkitStandalone: Running standalone certificate generation with output directory ../nifi-toolkit-1.0.0-SNAPSHOT and hostnames [host1, host2]
16/08/04 10:56:01 INFO standalone.TlsToolkitStandalone: Successfully generated TLS configuration for "host1:10443" in host1/
16/08/04 10:56:01 INFO standalone.TlsToolkitStandalone: Successfully generated TLS configuration for "host2:10443" in host2/
hw12203:...assembly/target/nifi-toolkit-1.0.0-SNAPSHOT-bin/nifi-toolkit-1.0.0-SNAPSHOT (pr790) alopresto
🔓 18s @ 10:56:02 $
```

With only one or two hosts, it's easy to see on one line, but if many are provided or the tool errors halfway through, it's nice to have a record of what was performed.

**Comment by brosander** [comment]
Thanks for the feedback, will make it so

**Comment by brosander** [comment]
```
HW13384:nifi-toolkit-1.0.0-SNAPSHOT brosander$ bin/tls-toolkit.sh standalone -n host1,host2 -o tmp
16/08/04 14:15:50 INFO standalone.TlsToolkitStandaloneCommandLine: No nifiPropertiesFile specified, using embedded one.
16/08/04 14:15:50 INFO standalone.TlsToolkitStandalone: Running standalone certificate generation with output directory tmp and hostnames [host1, host2]
16/08/04 14:15:50 INFO standalone.TlsToolkitStandalone: Successfully generated TLS configuration for host1:10443 in tmp/host1
16/08/04 14:15:50 INFO standalone.TlsToolkitStandalone: Successfully generated TLS configuration for host2:10443 in tmp/host2
16/08/04 14:15:50 INFO standalone.TlsToolkitStandalone: Successfully generated TLS configuration
```

**Comment by brosander** [comment]
```
nifi-toolkit-1.0.0-SNAPSHOT brosander$ bin/tls-toolkit.sh standalone -n host1,host2 -o tmp
16/08/04 14:19:44 INFO standalone.TlsToolkitStandaloneCommandLine: No nifiPropertiesFile specified, using embedded one.
16/08/04 14:19:45 INFO standalone.TlsToolkitStandalone: Running standalone certificate generation with output directory tmp and hostnames [host1, host2]
16/08/04 14:19:45 INFO standalone.TlsToolkitStandalone: Successfully generated TLS configuration for host1:10443 in tmp/host1
16/08/04 14:19:45 INFO standalone.TlsToolkitStandalone: Successfully generated TLS configuration for host2:10443 in tmp/host2
16/08/04 14:19:45 INFO standalone.TlsToolkitStandalone: Successfully generated TLS configuration for all hosts
```

**Comment by alopresto** [comment]
Reviewed. Rebased, squashed, and merging.

**Pull request closed without merging**
