### PR TITLE
NIFI-11673 Remove Legacy TLS Configuration Versions

### PR DESCRIPTION
**Pull request by exceptionfactory**
# Summary

[NIFI-11673](https://issues.apache.org/jira/browse/NIFI-11673) Removes legacy TLS protocol versions from the `TlsConfiguration` interface along with methods based on evaluation of Java version information.

Previous logic defaulted to TLSv1.2 for Java 8 and TLSv1.3 for Java 11 when calling several helper methods on `TlsConfiguration`. The `TlsPlatform` utility class provides feature-based detection and has been used in a number of framework and extension components. With the removal of Java 8 support from the main branch, the Java version number checking is no longer necessary.

Additional changes include applying the `SSL Protocol` property to the HTTP Notification Service for NiFi Bootstrap and removing test methods no longer necessary with the standardization of available TLS protocol versions.

For cluster socket communication, the `TlsPlatform` methods replace the Java version-based methods from `TlsConfiguration` while providing equivalent functionality.

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X] Pull Request based on current revision of the `main` branch
- [X] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [X] Build completed using `mvn clean install -P contrib-check`
  - [X] JDK 11
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by mr1716** [comment]
This would be great to implement!!

**Review by nandorsoma — APPROVED** [review]
Thanks for the change @exceptionfactory! Tested on a secured cluster, LGTM. Merging to main.

**Review by nandorsoma — COMMENTED** [review]
Noticed test failures in the `nifi-toolkit-tls` module in my last build after rebase. It could be a local env issue, but for further investigation, I'm revoking my approval for safety's sake.

**Comment by nandorsoma** [comment]
It was an env issue. Merging to main.

**Pull request closed without merging**
