### PR TITLE
NIFI-3993 Updated the ZooKeeper version to 3.4.10

### PR DESCRIPTION
**Pull request by HorizonNet**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by joewitt** [comment]
@jtstorck  @YolandaMDavis  and others interested - i recall some comments about holding off on updating zookeeper because of compatibility, etc..  Is that right?

@HorizonNet did you test the migrator and cluster functions with these changes including secure/unsecure settings by chance?

**Comment by jtstorck** [comment]
@joewitt I brought up the upgrade a while ago, but many of the services/components we integrate with are using Zookeeper 3.4.6.  Originally I wanted to use a newer version that did not explicitly depend on log4j, because it was causing some issues with the NiFi Toolkit.  Since we were able to work around the dependency issue, we didn't upgrade the version.

**Comment by HorizonNet** [comment]
@jtstorck Is an upgrade not necessary anymore? If not, let's close the ticket as won't do.

**Comment by jtstorck** [comment]
@HorizonNet I'm not familiar with the issue described in NIFI-3993, or what scenarios cause it to happen.  I did read [the referenced JIRA](https://issues.apache.org/jira/browse/ZOOKEEPER-2044), which states that it's a cosmetic error, so we'd need to investigate further to determine its impact on NiFi.

**Comment by HorizonNet** [comment]
@jtstorck If most of the services/components depend on ZooKeeper 3.4.6 then let's stick with that version and close the ticket. Any objections?

**Comment by jtstorck** [comment]
@HorizonNet No objections.  Feel free to close the PR.

**Pull request closed without merging**
