### PR TITLE
NIFI-12250: Fixing issue where the registry configuration dialog was being initialized twice

### PR DESCRIPTION
**Pull request by mcgilman**
NIFI-12250:
- Fixing issue where the registry configuration dialog was being initialized twice.

### CODE REVIEW

**Comment by mcgilman** [comment]
@sardell Any chance  you could help with a review here?

**Comment by sardell** [comment]
@mcgilman Sure, no problem. Reviewing now...

**Review by sardell — APPROVED** [review]
LGTM. Below is a screenshot with your fix. +1 (non-binding). Thanks, @mcgilman!

NIFI-12250-fixed

**Comment by markap14** [comment]
Thanks @mcgilman and @sardell. Looks good to me too. +1 will merge

**Pull request merged**
