### PR TITLE
NIFI-5226: Implement a Record API based PutInfluxDB processor

### PR DESCRIPTION
**Pull request by bednar**
- Added PutInfluxDBRecord for put data to InfluxDB by Apache NiFi Record API
- Added InfluxLineProtocolReader for parsing InfluxDB Line Protocol to Apache NiFi Record
- Added InfluxDBService for sharing connection settings to InfluxDB
- Upgraded influxdb-java to 2.10

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [x] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by bednar** [comment]
Hi NiFi team, this pull request is now ready to get reviewed. 

The script to help reviewing/testing this PR is available in the sources: `nifi-nar-bundles/nifi-influxdb-bundle/InfluxDBIntegrationTests.sh`

Jakub

**Comment by MikeThomsen** [comment]
@mans2singh @timhallinflux can y'all jump in on this and give some feedback too?

**Comment by timhallinflux** [comment]
PutInfluxDB was created as single purpose tool -- accepting line protocol only. It does not read CSVs, AVROs, JSONs out of the box. If developer wants to use it with NiFi, s/he has to extend it and write their own parsers.   That is ok...and it does support a direct integration.

However, PutInfluxDBRecord addresses the problem of reading the data. It simplifies data parsing and handling using the concept of Records ( https://blogs.apache.org/nifi/entry/record-oriented-data-with-nifi )
It more naturally works with Nifi objects and the fields, tags are configurable from within the Nifi IDE...which delivers a much more integrated experience.

For example: Reading Twitter with PutInfluxDB is not possible without coding/external configuration. On the contrary, reading Twitter JSON via PutInfluxDBRecord is no-dev effort and leverages the tools within NiFi itself.

Still, the two classes can coexist depending on the type of work that needs to be done.  I'm in favor of moving ahead with the PutInfluxDBRecord

**Comment by timhallinflux** [comment]
@MikeThomsen -- any update here?

**Comment by MikeThomsen** [comment]
@timhallinflux not at the moment. It's a huge commit, and I've been too busy to get into it.

**Comment by ivankudibal** [comment]
@MikeThomsen any update?

**Comment by ivankudibal** [comment]
@MikeThomsen

**Comment by zisisp** [comment]
Hello, what is the status of this? is it going to be merged?

**Comment by joewitt** [comment]
@zisisp the challenge with integrations like this is having people familiar with the source/target system which in this case is InfluxDB and who also have commit privileges to conduct a review.  As we bring things into the system we're taking on license/notice/dependency/code management burden and for things which we dont have an easy path to test with it can be tough.  To me, this is a perfect example of an integration which is best held/supported/promoted by the vendor and the NiFi community could then link to it but not include it in our apache distro.  I'm just sharing a personal thought - this isn't a community statement.  But am being honest about what makes these tough - even though this seems super useful.

**Comment by bednar** [comment]
Hi @joewitt, 

Thanks for your detail information. Is there anything else how we can help you (or other reviewers) with review? Do you want some additonal information, prepare a testing environment, …?

There is also an option to split this PR to smaller PRs:

1/ **InfluxDBService** for sharing connection settings to InfluxDB
2/ **InfluxLineProtocolReader** for parsing InfluxDB Line Protocol to Apache NiFi Record
3/ **PutInfluxDBRecord** for put data to InfluxDB by Apache NiFi Record API

It will be helpful for you?

Thanks for your cooperation @joewitt

**Comment by joewitt** [comment]
@bednar it is that we need special credentials or access to test that is arguably part of the problem.  That is the first clue to me that this might make more sense as something the Influx team just puts on their website and supports.  They can tell their customers/users to grab the nar and throw it in their favorite nifi distro and away they go.  This reduces the burden for the nifi community to review/test it and gives Influx total control.

The other clue that things aren't quite right in this case is that the github account we see for a lot of this says 'Influx Engineering'. We really need to be careful about such things.  Contributions to apache projects are under strong governance for important reasons.

Anyway, I'm not trying to make it seem like this cannot happen.  I'm just strongly suggesting we tackle this differently.

**Comment by MikeThomsen** [comment]
@ivankudibal 

> We can also create separate repo and distirbute nar independently on Nifi, however may this increase unecessary configuration effort on the end user?

Not at all. The only thing they'd need to do is drop in the NAR file and restart NiFi to load it up.

**Comment by ottobackwards** [comment]
There is work going on to support nar registry to not have to restart I believe too @bbende ?

**Comment by ivankudibal** [comment]
We will create the independent repo with influxdata nar, builds, examples and other docs for Nifi users. This gives us greater flexibility. Thank you @joewitt .

**Comment by joewitt** [comment]
Cool sounds good.  Can you please close out this PR and the JIRA with that information.  Please feel free to let the community know where these live whenever you do this.  Could probably put a link to it somewhere.

**Comment by ivankudibal** [comment]
The work has been done and is available in https://github.com/influxdata/nifi-influxdb-bundle
Enjoy!

This PR can be closed w/o merging.

**Comment by MikeThomsen** [comment]
@ivankudibal I'm going to close this out and update Jira to include a link to your bundle.

**Comment by BIGabor** [comment]
Hi, I tried this nar from InfluxDB, and it's usable. Not like built-in NiFi Influx. I have JSON Input. Set JSONTreereader as a source, and just typed in the JSON keys to the right params, and viola, works. It also support InfluxDB 2. 
@MikeThomsen I see your points, but it's much much better than the built-in. And you can use attributes to as params. It's really supereasy. I stopped creating execute script processors, and so on, just added an ConsumeKafka, and PutInfluxDatabaseRecord_2, that's all, it works! 
@bednar one improvement would be fine: the possibility to use Processorgroups Params too.

**Pull request closed without merging**
