### PR TITLE
NIFI-4074: Fix recursive regex search

### PR DESCRIPTION
**Pull request by champagst**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by brosander** [comment]
Hey @champagst 

Thanks for the contribution! I was digging into the ListHDFS implementation and I think the reason it doesn't work on nested files might be that it is only matching against the [file name, not the whole path.](https://github.com/apache/nifi/blob/e85081ed201bc7413e3d2d062c814e23c0ff5467/nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/ListHDFS.java#L406)

Would adding a property that tells the filter to match [on the whole path](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html#toString--), not just the name address your usecase?  That way we could default it to false and prevent existing flows from having their semantics changed.

**Comment by champagst** [comment]
@brosander  - Yes! That would work great for me if I could match along the entire path!

**Comment by champagst** [comment]
I figured out how this is intended to work. Sorry for the misunderstanding.

**Comment by sjoshidc** [comment]
I still cannot get "file filter" regex to work when doing recursive folders.  Could you give me any example of what the regex should be for recursive folders?  I already spent few hours on it but it is not intuitive so can't get anything working with modified regex for recursive folders.

**Pull request closed without merging**
