### PR TITLE
NIFI-925: Upgrade to Hadoop 2.7.1

### PR DESCRIPTION
**Pull request by jbonofre**

### CODE REVIEW

**Comment by rickysaltzer** [comment]
Is there a specific reason for depending on Hadoop 2.7? I'm not entirely certain how we should approach upgrading Hadoop packages (or other dependencies for that matter). Take other projects for instance (i.e. Spark, Flink), they have separate builds for major Hadoop version (e.g. 2.4, 2.6). I wonder if this is an option we should consider...

Preferably, I would like some sort of class loader isolation in place where you can decide which version of the library to use on a processor by processor basis.

**Comment by joewitt** [comment]
Totally with you on this Ricky.  As far as the contrib goes that is legit.  We should keep it up to date.  However, you're right that we need a better model for things like Hadoop.  It should be braindead easy for folks to plugin different Hadoop versions/providers and the user just get to select from a list.

**Comment by rickysaltzer** [comment]
Yeah I agree, keeping libraries up to date is a good thing. We should definitely discuss strategies on how we can achieve multi-version support for libraries, eventually. There's currently a JIRA ([NIFI-710](https://issues.apache.org/jira/browse/NIFI-710)) which talks about this in the context of Hadoop.

**Comment by busbey** [comment]
The problem with keeping client libraries up to date is that often times they don't work with older servers. YCSB hits this pretty hard for Cassandra, ElasticSearch, and HBase. The only real solution is something like NIFI-710.

For the specific case of Hadoop, I'd look to see if the project makes any promises about newer clients talking to older servers. Absent that, I would presume we shouldn't update the client without a big notice to downstream users. Despite that, the Hadoop 2.6.0 client library is particularly bad so if we could update to 2.6.1 in the short term, that'd be good.

**Comment by joewitt** [comment]
i am comfortable with the idea of 2.6.1 with our current approach.  Once we have NIFI-710 in play then we should support 2.6, 2.7, X.Y, whatever.  We need to do that in conjunction with having a registry model.  So many good plays to work with here.  Mark Payne was talking about some cool ideas he had to pull this off recently.  We need to get him to write those down!

**Comment by rickysaltzer** [comment]
I'm also a **+1** for upgrading to 2.6.1. I was also thinking that this would need to play into the [template registry](https://cwiki.apache.org/confluence/display/NIFI/Extension+and+Template+Registry) proposal. We should definitely continue to iron out the details so we can get that feature into a not too distant release.

**Comment by busbey** [comment]
On the one hand, I prefer to engage hadoop-as-it-is rather than waiting for changes.

On the other hand, 2.6.2 RC0 closes in 5 days, so figure about a week for there to be artifacts presuming it passes?

2.6.1 has the critical problems fixed (like corrupting data when writing to HDFS encrypted directories), so I'd rather upgrade to it now and then go to 2.6.2 if/when it gets released.

**Comment by trkurc** [comment]
My preference would be to shoot for 2.6.2 in 0.4. If it isn't done, go with 2.6.1. I do not believe 0.4 should be released with hadoop 2.6.0 client libs.

**Comment by busbey** [comment]
:+1: the 2.6.2 vote just passed last night, so I'd expect artifacts to be published with plenty of time for 0.4.

**Comment by jbonofre** [comment]
Allright, I will update this PR accordingly. Thanks guys !

**Comment by jbonofre** [comment]
PR rebased and updated.

**Pull request closed without merging**
