### PR TITLE
NIFI-2251 - Initial commit for client side provenance lineage svg download

### PR DESCRIPTION
**Pull request by YolandaMDavis**
This provides a client side solution for downloading the svg lineage graph file (essentially replacing the functionality of the DownloadSVG servlet).  There are two different download models supported (both methods using data URI for content delivery):

1) If the user clicks the download button, and the download anchor tag attribute is supported by the browser, then NiFi will automatically trigger a hidden link with the data URI referenced for file content and a file name provided for the download attribute. This will allow the browser to prompt the user to save the file with the given filename to their local drive.

2) If the download attribute is not supported (e.g. Safari) then a separate tab will open displaying the svg file which can then be saved by the user using the browser's "Save As" menu.

This was unit tested locally with Chrome (52.0.2743.116) Safari (9.1.1), and Firefox (46.0.1)

### CODE REVIEW

**Comment by mcgilman** [comment]
Will Review...

**Comment by mcgilman** [comment]
@YolandaMDavis Thanks for the PR! A couple comments...

- I ran into an issue running on Edge. The svg that is downloaded appears to contain an additional xmlns attribute in the svg tag. With the duplicate attribute, it is causing problems opening the saved svg. Once I manually removed the extra attribute the svg opens successfully.

- Also, can we update the Download icon? Using the download icon from FontAwesome [1] should be good. The existing download icon can be removed.

[1] http://fontawesome.io/icon/download/

**Comment by YolandaMDavis** [comment]
@mcgilman thanks for reviewing.  I can take a look at the svg rendered and retest.  Also I'll update the icon.

**Comment by YolandaMDavis** [comment]
@mcgilman made the changes to support Edge and switched to font awesome icon

**Comment by mcgilman** [comment]
Thanks @YolandaMDavis! This looks good. I've verified the changes in all of our supported browsers. Just a heads up, I've made a couple minor changes to some spacing/formatting to be more consistent with existing code. This has been merged to master.

**Comment by YolandaMDavis** [comment]
Thanks @mcgilman!

**Pull request closed without merging**
