### PR TITLE
NIFI-10611 upgrade ignite-core to 2.15.0

### PR DESCRIPTION
**Pull request by r-sidd**
# Summary

[NIFI-00000](https://issues.apache.org/jira/browse/NIFI-00000)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 11
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for contribution @r-sidd. The Maven configuration also includes an `ignite-slf4j` library version that needs to be updated.

**Comment by exceptionfactory** [comment]
Also `ignite-spring` has the old version. This should be moved to a Maven property named `ignite.version` and reused.

**Comment by r-sidd** [comment]
> Thanks for contribution @r-sidd. The Maven configuration also includes an `ignite-slf4j` library version that needs to be updated.

I'm sorry about that, let me commit and push the changes. Bumping both `ignite-slf4j` and `ignite-spring` to 2.15.0

**Comment by r-sidd** [comment]
> Also `ignite-spring` has the old version. This should be moved to a Maven property named `ignite.version` and reused.

Got it, will do that

**Comment by r-sidd** [comment]
Pushed the new changes @exceptionfactory

**Comment by exceptionfactory** [comment]
Thanks for the work on this @r-sidd. Although the unit tests pass, they use a mocked Ignite Processor that does not exercise actual behavior.

The integration tests fail to run when attempting connect to the internal test server.

The [Apache Ignite 2.0 Migration Guide](https://cwiki.apache.org/confluence/display/IGNITE/Apache+Ignite+2.0+Migration+Guide) highlights a number of important changes, so I'm not surprised this is failing. The current Processor implementations rely on a Spring Configuration file, which is not the best approach, and these Processors have not been maintained since the original contribution in 2016. With that background, I will plan on deprecating and removing them for NiFi 2.0 in a separate issue.

**Comment by r-sidd** [comment]
> Thanks for the work on this @r-sidd. Although the unit tests pass, they use a mocked Ignite Processor that does not exercise actual behavior.
> 
> The integration tests fail to run when attempting connect to the internal test server.
> 
> The [Apache Ignite 2.0 Migration Guide](https://cwiki.apache.org/confluence/display/IGNITE/Apache+Ignite+2.0+Migration+Guide) highlights a number of important changes, so I'm not surprised this is failing. The current Processor implementations rely on a Spring Configuration file, which is not the best approach, and these Processors have not been maintained since the original contribution in 2016. With that background, I will plan on deprecating and removing them for NiFi 2.0 in a separate issue.

Makes sense, thanks for the explanation 😄

**Pull request closed without merging**
