### PR TITLE
NIFI-2316, NIFI-2318: Ensure that we do not save the flow before init…

### PR DESCRIPTION
**Pull request by markap14**
…ializing the Run Status of components. Clarify the Node Event messages

### CODE REVIEW

**Comment by JPercivall** [comment]
This isn't fixing NIFI-2316 for me. I applied this commit to the latest master, ran a 3 node secure cluster, created 2 processors and ran them. After I restarted, all the nodes correctly joined but all had stopped processors.

It is reproducible.

**Comment by JPercivall** [comment]
I believe this is due to NIFI-2335. I will re-test.

https://issues.apache.org/jira/browse/NIFI-2335

**Comment by JPercivall** [comment]
I have two processors (generate -> logAttribute) in a 3 node secure cluster and when I restart occasionally I'll get repeating messages of "Failed to retrieve any new heartbeat information for nodes. Will not make any decisions based on heartbeats." originating from different nodes.

I think this is caused by nodes not having a consistent view of the cluster.

**Comment by markap14** [comment]
@JPercivall I think the issue that you are seeing now is related to NIFI-2292.

**Comment by JPercivall** [comment]
For tracking, I encountered this issue[1] while testing but I believe it's unrelated to this PR. I will continue reviewing.

[1] https://issues.apache.org/jira/browse/NIFI-2406

**Comment by JPercivall** [comment]
+1

Visually verified code and did a contrib check build. In a 3 node secure cluster, I did a lot of restarting, starting/stopping processors, disconnecting nodes and trying to hit corner cases and it all functioned as expected. Thanks @markap14, I will merge it in.

**Pull request closed without merging**
