### PR TITLE
NIFI-11196 Restrict ListFile to primary node only

### PR DESCRIPTION
**Pull request by nandorsoma**
# Summary

[NIFI-11196](https://issues.apache.org/jira/browse/NIFI-11196)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [x] Build completed using `mvn clean install -P contrib-check`
  - [x] JDK 11
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by mattyb149** [comment]
@markap14 This looks consistent with the docs but wanted to check with you since it could affect files landing in each node

**Comment by nandorsoma** [comment]
> @markap14 This looks consistent with the docs but wanted to check with you since it could affect files landing in each node

Thanks for looking at it [@mattyb149](https://github.com/mattyb149)! Just a little more info. I noticed after opening the PR that when the processor is [listing a local directory](https://github.com/apache/nifi/blob/a63c3594c9dbbbbd1afcb0844b7ab0e1c3e6f171/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ListFile.java#L135), it may work on multiple nodes while it is guaranteed that the local directory contains different files on each node. In that situation, the state is stored locally, so it doesn't matter whether the primary node changes. If I'm right, this pr is not acceptable. Instead, we could update the description accordingly and add a validation (of possible) that prevents using the processor on all nodes when the `Input Directory Location` is set to `Local`.

**Comment by mattyb149** [comment]
I think that was the original use case for ListFile, to list files local to each node, so I'm not sure we want to prevent that. Is the local state the issue?

**Comment by nandorsoma** [comment]
Closing this as it became clear to me that only the description of the processor is obsolete, and it is a valid use-case to use this processor on a multi-node env with `Local` Input Directory.

**Pull request closed without merging**
