### PR TITLE
[NIFI-2775] update Provenance table GoTo button visibility in FF

### PR DESCRIPTION
**Pull request by scottyaslan**

### CODE REVIEW

**Comment by mcgilman** [comment]
Reviewing...

**Comment by mcgilman** [comment]
@scottyaslan Looks like I'm seeing the same behavior with the tables in the Summary page. Can we update those as well?

**Comment by scottyaslan** [comment]
@mcgilman I have completed the changes to include the Summary page and have updated this PR. Thanks!

**Comment by mcgilman** [comment]
Thanks @scottyaslan! This has been merged to master.

**Pull request closed without merging**
