### PR TITLE
NIFI-3385 - Updating Copyright statements to reflect the new year.

### PR DESCRIPTION
**Pull request by apiri**
NIFI-3385 - Updating Copyright statements to reflect the new year.

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [-] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [-] Have you written or updated unit tests to verify your changes?
- [-] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [x] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [-] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by joewitt** [comment]
its probably not a big deal or maybe even not a thing but technically this might update too many things as it is including updates against some dependencies we have.  Such updates might not be true for the copyright years for those deps.  Perhaps only update the first occurrence in any given file so that you know you're getting our copyright header only? @apiri

**Comment by apiri** [comment]
Wondered about that.  From an ASF perspective though, unless the project was terminated, wouldn't they also carry through copyright of their previously existing works?

**Comment by joewitt** [comment]
the version of a given dependency and its licensing we use is set at a specific time.  I'm not sure.  Not a lawyer.  But I'd prefer we focus only on our nifi copyright aspects and maintain our handling of libraries as-is.  Is it a pain to update the mechanism you used to make the changes to avoid changing more than just the nifi part?

**Comment by apiri** [comment]
Nope, not a huge issue, just had a mixing of career lives.  Will retool this and get resubmitted today-ish.  Thanks!

**Comment by apiri** [comment]
@joewitt Should be good to go as per your suggestion.

**Pull request closed without merging**
