### PR TITLE
NIFI-8288 Removed nifi-security-utils dependency from nifi-web-utils

### PR DESCRIPTION
**Pull request by exceptionfactory**
#### Description of PR

NIFI-8288 Removes `nifi-security-utils` dependency from `nifi-web-utils` and eliminates the need for `OkHttpClientUtils`.  This refactor removes around 40 MB of dependencies of the assembled NiFi binary as a result of removing unnecessary references to the Bouncy Castle Security Provider.  Other changes include the following:

- Added createTrustManager() on SSLContextService
- Removed OkHttpClientUtils in favor of direct use of SSLContextService and SslContextFactory
- Removed nifi-security-utils and okhttp dependencies from nifi-web-utils

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [X] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [X] Have you written or updated unit tests to verify your changes?
- [X] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by thenatog** [comment]
Reviewing. Noticed there was an issue with Windows build (re-running jobs right now), may be easily fixed by a rebase though I'm not sure.

**Comment by exceptionfactory** [comment]
> Reviewing. Noticed there was an issue with Windows build (re-running jobs right now), may be easily fixed by a rebase though I'm not sure.

Thanks for reviewing @thenatog.  It looks like the JDK 1.8 FR build failed this time around with another one of the sporadic errors that have come up occasionally.  The previous Windows build failure also appeared to be an intermittent issue with the GitHub runner.

**Comment by thenatog** [comment]
Things seem good to me, I tried it out with a 3 node secure cluster with secured external ZK. From what I can tell, when this change is rebased onto main, the .zip build size is 1.2GB which is about 100MB smaller than the main build's zip. Does that sound right? Not a bad improvement when combined with the other PR that reduced it around 300MB.

**Comment by exceptionfactory** [comment]
> Things seem good to me, I tried it out with a 3 node secure cluster with secured external ZK. From what I can tell, when this change is rebased onto main, the .zip build size is 1.2GB which is about 100MB smaller than the main build's zip. Does that sound right? Not a bad improvement when combined with the other PR that reduced it around 300MB.

Thanks for the additional testing, that size sounds correct given the updates.

**Comment by thenatog** [comment]
Great, +1 will merge.

**Pull request closed without merging**
