### PR TITLE
NIFI-1742: Initial support for component level revisions

### PR DESCRIPTION
**Pull request by mcgilman**
- Addressing issues when creating a new inline controller service.
- Ensuring controller service referencing components are updated.
- Including revisions and status with each component on the canvas. Still need to address controller services and reporting tasks.
- Auto updating components when refreshing.

### CODE REVIEW

**Comment by mcgilman** [comment]
In this PR the components update automatically. However, it doesn't appear the authorization state is properly reflected. I will update this PR and comment when the necessary changes are pushed.

**Comment by mcgilman** [comment]
The PR has been updated with the work I described last night.

**Comment by bbende** [comment]
Reviewing...

**Comment by bbende** [comment]
+1 Verified component level revisions working as expected, full build passes with contrib-check

**Pull request closed without merging**
