### PR TITLE
NIFI-1486 added commons io and lang to nifi-amqp-nar NOTICE

### PR DESCRIPTION
**Pull request by joewitt**

### CODE REVIEW

**Comment by olegz** [comment]
Shouldn't it be implied under NiFi since those dependencies are pulled by NiFi dependencies and are not explicitly imported by AMQP NAR?

**Comment by joewitt** [comment]
Nothing is implied.  The nar has bundled binary dependencies or it does not.  If it does then each of those, regardless of why they are there, need to be accounted for in the LICENSE and NOTICE files as appropriate.

**Comment by olegz** [comment]
Ok, then what about the rest of the dependencies (i.e., antlr, slf4j etc)? Just trying to understand for the future.

**Comment by joewitt** [comment]
regarding the rest of the dependencies they do not exist within the Nar.  You have to check the nar itself for what binary dependencies are bundled.  We do not need to account for dependencies we are not bundling.  Now, those dependencies DO matter in the tar.gz for example which bundles this nar and they are indeed accounted for there.

**Comment by trkurc** [comment]
+1 I will merge it in.

**Pull request closed without merging**
