### PR TITLE
Adding GetSmbFile and PutSmbFile processors

### PR DESCRIPTION
**Pull request by si-sun**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

Added functionality to read and write from samba shares with GetSmbFile and PutSmbFile processors. The advantage is to not have to manage cifs mounts on the server/nodes. Also the processors supports windows style share locks on the files during read and write.
It's using [SMBJ client library](https://github.com/hierynomus/smbj) for the samba connection.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically `master`)?

- [X] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder? (only for :nifi-smb-bundle)
- [X] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on both JDK 8 and JDK 11?
- [X] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [X] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [X] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [X] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by patricker** [comment]
Do you need help creating a Jira ticket for this work?

There are some top level files you will need to update, since this adds a new dependency to NiFi. See: 

> If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?

Would you consider adding a ListSmb Processor also?  I saw in the documentation for the library you are using that they support this.  Also, FetchSmb would be great :D

**Comment by si-sun** [comment]
> Do you need help creating a Jira ticket for this work?

Yes, that would be great!

About the license / notice, I suppose I need to add the smbj under "Apache Software License v2" section in the respective files.
What about the [smbj maven dependencies](https://mvnrepository.com/artifact/com.hierynomus/smbj/0.9.1)? Some of them are under MIT license, where / how should I put that?

Right now I haven't considered ListSmb / FetchSmb, though I assume it's not going to be too much work. But I want to be sure that these two processors are "done" before creating new ones :)

**Comment by joewitt** [comment]
Yep this looks pretty cool but definitely needs NOTICE file updates and possibly LICENSE.  The smbj library itself appears to include a copyright line we need to carry into NOTICE like we have many examples of.  Haven't checked transitive libs.

**Comment by si-sun** [comment]
I updated the LICENSE and NOTICE files. Let me know if this is now ok.
Looks like the build is failing due a maven https issue. Seem like all the build are failing right now.

**Comment by n0amt** [comment]
Hi, any progress updates on this?
I could really use a getSMBfile (as well as a listSMBfile and fetchSMBfile) processor

**Comment by JensMKofoed** [comment]
Are there any progress in this great new features?
This is something I have waited for for a very long time.
If you need help testing, I would be glad to help

**Comment by joewitt** [comment]
this ideally needs to be rebased against latest.  The updates to NOTICE/LiCENSE look really well done.  The code itself looks quite thoughtful.  Not sure how well tests will work on different platforms but a rebase/update to latest master will help highlight that.  In general though this looks like a solid contrib

**Comment by joewitt** [comment]
..disregard the close - hit the wrong button!  reopened.  And just learned that reopening means the new builds are running - wow

**Comment by si-sun** [comment]
not sure if I was supposed to do the rebase in this manner. anyway, I hope the checks will pass and we can come to a conclusion with this PR

**Comment by joewitt** [comment]
there should only be commits on this branch that you provided.

Please rebase to latest master and have your commits be the most recent.  

a reviewer could cherry-pick your real commits out but then they have to go through the build process against lateast master themselves.

**Comment by si-sun** [comment]
I did the rebase. there are 4 commits on top, which includes the full change.
any idea why the check failed? it just says "##[error]The operation was canceled."

**Comment by joewitt** [comment]
I cancelled the workflow execution as there are other builds going on and this one isn't helpful until the commits on the PR are fixed.

If you rebased there should not be 245 commits.  There should be only the couple that actually change things.  It might be easiest for you to close this PR, make a new one off the latest master, and put a single commit in which does what you want (1.12-SNAPSHOT, code changes, License and Notice updates, pom updates in one)

**Comment by si-sun** [comment]
alright, I'll make a new one, next week

**Pull request closed without merging**
