### PR TITLE
NIFI-10562 Moved MongoDB to using testcontainers for integration test…

### PR DESCRIPTION
**Pull request by MikeThomsen**
… support.

# Summary

[NIFI-00000](https://issues.apache.org/jira/browse/NIFI-00000)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 8
  - [ ] JDK 11
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for the changes @MikeThomsen, this will be helpful for verifying MongoDB components.

Running the integration tests returned several failures:

```
[ERROR] Failures: 
[ERROR]   PutGridFSIT.testFileNameAndHashUniqueness:125->testHashUniqueness:173->testUniqueness:184 expected: <4> but was: <0>
[ERROR]   PutGridFSIT.testHashUniqueness:130->testHashUniqueness:173->testUniqueness:184 expected: <4> but was: <0>

[ERROR] Errors: 
[ERROR]   MongoDBControllerServiceIT.testVerifyWithCorrectConnectionString:71 IncompatibleClassChange Class org.apache.nifi.mongodb.MongoDBControllerService does not implement the requested interface org.apache.nifi.controller.VerifiableControllerService
[ERROR]   MongoDBControllerServiceIT.testVerifyWithIncorrectConnectionString:85 IncompatibleClassChange Class org.apache.nifi.mongodb.MongoDBControllerService does not implement the requested interface org.apache.nifi.controller.VerifiableControllerService
```

**Review by ChrisSamo632 — COMMENTED** [review]
Looks OK to me aside from the aforementioned test failures

**Comment by MikeThomsen** [comment]
> Running the integration tests returned several failures:

Those are the ones that failed due to the hash behavior we discussed in the previous PR attempt. @exceptionfactory

**Comment by MikeThomsen** [comment]
That's odd, I'll take a look at that.

**Comment by MikeThomsen** [comment]
@exceptionfactory I just ran it with `mvn clean install -Pintegration-tests` and in IntelliJ. Did not get that error. How are you running this?

**Review by exceptionfactory — APPROVED** [review]
Thanks for the reply @MikeThomsen, I was running the tests using Maven, but with a previously compiled project module, so that explains the errors. This looks good, and will provide a good baseline for addressing the PutGridFS issues in MongoDB 5 and later. +1 merging

**Pull request closed without merging**
