### PR TITLE
NIFI-8783 Moved SingleUserAuthorizer Login Provider check

### PR DESCRIPTION
**Pull request by exceptionfactory**
#### Description of PR

NIFI-8783 Moves the check for `SingleUserLoginIdentityProvider` from `setProperties()` to `initialize()` in `SingleUserAuthorizer`. This approach allows the `SingleUserAuthorizer` definition to exist in `authorizers.xml` but continues to prevent it from being used without the `SingleUserLoginIdentityProvider` being configured as the selected Login Identity Provider.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [X] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [X] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Review by gresockj — COMMENTED** [review]
I don't see any red flags in the logic, will test out runtime behavior next.

**Comment by jfrazee** [comment]
@exceptionfactory There was a thread in Slack where someone noted similar behavior for the AzureGraphUserGroupProvider so I also checked the LdapUserGroupProvider and all will try to initialize whether or not they're being used resulting in startup failures, so I don't think this is a SingleUserAuthorizer issue alone.

I checked some commits back in April and this wasn't happening. Not sure where the problem is yet though.

**Comment by bbende** [comment]
@jfrazee this issue was specially for single-user-group authorizer because it was doing a check to ensure that it can only be used with the single-user-group login identity provider.

In general though, anything declared in the provider files should be able to be instantiated and configured, even if it is not directly used in NiFi properties. So if any other provider has an issue like this we should address that too with additional JIRAs/PRs.

**Comment by exceptionfactory** [comment]
Thanks for the feedback @jfrazee. As @bbende mentioned, this particular check is specific to the `SingleUserAuthorizer`.  The purpose is to prevent the `SingleUserAuthorizer` from being used with a Login Identity Provider other than `SingleUserLoginIdentityProvider`.  The `setProperties()` method that receives the instance of `NiFiProperties` gets called before `initialize()`, so moving the logic to `initialize()` allows the Authorizer to check its own identifier and thus be defined without necessarily being enabled.

**Comment by jfrazee** [comment]
@bbende @exceptionfactory Thanks. After working through it, it's just a superficially similar thing -- any userGroupProvider present (uncommented) must have a valid configuration whether or not it or the managed-authorizer is being used. There's been no change in behavior, just new ways to bump into it.

**Review by gresockj — APPROVED** [review]
Ok, I verified that:

1. Starting up with a selected authorizer of single-user-authorizer and a login-identity-provider of ldap-provider correctly fails with `SingleUserAuthorizer requires org.apache.nifi.authentication.single.user.SingleUserLoginIdentityProvider to be configured`
2. Starting up with single-user-authorizer present in authorizers.xml, but with a selected authorizer of managed-authorizer and a login-identity-provider of ldap-provider now works.

**Comment by exceptionfactory** [comment]
> Ok, I verified that:
> 
>     1. Starting up with a selected authorizer of single-user-authorizer and a login-identity-provider of ldap-provider correctly fails with `SingleUserAuthorizer requires org.apache.nifi.authentication.single.user.SingleUserLoginIdentityProvider to be configured`
> 
>     2. Starting up with single-user-authorizer present in authorizers.xml, but with a selected authorizer of managed-authorizer and a login-identity-provider of ldap-provider now works.

Thanks for the verification @gresockj!

**Review by bbende — APPROVED** [review]
Looks good

**Pull request merged**
