### PR TITLE
NIFI-11940 Add SSLContextService to GetSplunk processor

### PR DESCRIPTION
**Pull request by nandorsoma**
# Summary

[NIFI-11940](https://issues.apache.org/jira/browse/NIFI-11940)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for the improvement @nandorsoma.

Unfortunately, the design of the Splunk SDK `Service` class is not suited for a configurable `SSLSocketFactory` based on the static configuration approach. Calling the `Service.setSSLSocketFactory` method changes the Socket Factory for all instances of the Splunk Service, which would impact all instances of the Processor, and other Processors that use the Splunk SDK.

One option might be to use instance class-loading, as used in several Hadoop-based Processors. Another more involved option would be the replace the Splunk SDK client with custom network client libraries that support configurable TLS properties.

**Comment by nandorsoma** [comment]
> Thanks for the improvement @nandorsoma.
> 
> Unfortunately, the design of the Splunk SDK `Service` class is not suited for a configurable `SSLSocketFactory` based on the static configuration approach. Calling the `Service.setSSLSocketFactory` method changes the Socket Factory for all instances of the Splunk Service, which would impact all instances of the Processor, and other Processors that use the Splunk SDK.
> 
> One option might be to use instance class-loading, as used in several Hadoop-based Processors. Another more involved option would be the replace the Splunk SDK client with custom network client libraries that support configurable TLS properties.

Thanks for the quick review @exceptionfactory! You are right about the issue regarding static configuration. Thank you for bringing that to my attention!

**Comment by Lehel44** [comment]
Thanks @nandorsoma for the contribution. I tested the SSLContextService with the GetSplunk processor and it works well.
It's important to note that as there isn't an explicit option for configuring SSL modes, using the "https" scheme requires the obligatory use of an SSLContextService. Consequently, the necessity for the new property hinges on the specified scheme value.
Regarding the proposed solution by @exceptionfactory can we move forward with @RequiredInstanceClassloading? I am open to testing it should an update be made.

**Comment by exceptionfactory** [comment]
@Lehel44 I don't think we should move forward with the `RequiresInstanceClassloading` change here unless we do it all for the Splunk Processors, and that raises some other questions. For now, it is still possible to work around this issue by updating the JVM cacerts trust store instead.

**Comment by joewitt** [comment]
@exceptionfactory What is the hesitation to use the instance classloader solution here?  It seems that is what it was made for.  It probably makes sense to ensure that is done on each splunk processor as you note but why avoid it?

**Comment by exceptionfactory** [comment]
> @exceptionfactory What is the hesitation to use the instance classloader solution here? It seems that is what it was made for. It probably makes sense to ensure that is done on each splunk processor as you note but why avoid it?

The optimal solution would involve replacing the Splunk SDK with lower-level HTTP request and response handling. However, that would be a lot more work, so going forward with instance ClassLoader approach is probably the best solution under the circumstances. I withdraw my comment on avoiding that approach.

**Comment by joewitt** [comment]
@nandorsoma @Lehel44 Do you plan to complete the change then to move to instance classloading so we can work past the poor usage of statics for security settings in the splunk libs?

**Comment by nandorsoma** [comment]
> @nandorsoma @Lehel44 Do you plan to complete the change then to move to instance classloading so we can work past the problematic usage of statics for security settings in the splunk libs?

Thanks for bumping it, @joewitt! We were about to close this PR, but as @exceptionfactory withdrew his previous comment, we will push the PR over the finish line.

**Comment by joewitt** [comment]
@nandorsoma do you still plan to complete this?

**Comment by nandorsoma** [comment]
> @nandorsoma do you still plan to complete this?

Yep, @joewitt, I intended to do this on the week starting tomorrow.

**Comment by nandorsoma** [comment]
Thanks @joewitt and @exceptionfactory for the patience. I've added the isolation functionalty and rebased the branch as it was a bit old. Tested it with splunk enterprise edition, works as intended.

**Review by exceptionfactory — APPROVED** [review]
Thanks for making the adjustments @nandorsoma, the instance ClassLoading approach looks good. +1 merging

**Comment by pvillard31** [comment]
Do we have plans to do the same for the other Splunk processors (sinks)?

**Pull request closed without merging**
