### PR TITLE
Update StandardOidcIdentityProvider.java

### PR DESCRIPTION
**Pull request by Senthilannaswamy**
ClientAuthenticationMethod is optional. Fixed made to handle the same.

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by mcgilman** [comment]
@Senthilannaswamy Thanks for issuing a PR! Sorry for the delay. Is there a JIRA that explains the issue that this PR addresses?

**Comment by Senthilannaswamy** [comment]
@mcgilman
No I've not created any Jira for this issue. The underlying reason for the change was to handle the Optional tag for ClientAuthenticationMethod.

**Comment by mcgilman** [comment]
@Senthilannaswamy I just double check the specification and the suggested changes make sense. 

> token_endpoint_auth_methods_supported
> OPTIONAL. JSON array containing a list of Client Authentication methods supported by this Token Endpoint. The options are client_secret_post, client_secret_basic, client_secret_jwt, and private_key_jwt, as described in Section 9 of OpenID Connect Core 1.0 [OpenID.Core]. Other authentication methods MAY be defined by extensions. If omitted, the default is client_secret_basic -- the HTTP Basic Authentication Scheme specified in Section 2.3.1 of OAuth 2.0 [RFC6749].

Before we accept the PR, can you please file a JIRA [1] and update your commit message to reference the ticket. Take a peek at another PR for an example.

Thanks! I can also file the JIRA for you if you prefer.

[1] https://issues.apache.org/jira/projects/NIFI

**Comment by Senthilannaswamy** [comment]
@mcgilman
I had created a Jira NIFI-4781 and updated the message. Hope its suffice.

**Comment by mcgilman** [comment]
Thanks @Senthilannaswamy! This has been merged to master.

**Pull request closed without merging**
