### PR TITLE
NIFI-2912 Allow custom text in GenerateFlowFile

### PR DESCRIPTION
**Pull request by pvillard31**

### CODE REVIEW

**Comment by alopresto** [comment]
Reviewing...

**Comment by alopresto** [comment]
@pvillard31 the only issue I encountered was that if a message is provided, the `File Size` field is still required, even though it is not used. In the custom validate method, can we either switch `File Size` required to `false` if `Custom Text` is populated, or provide a default value of `0B` for `File Size`?

Other than that, seems very useful, and I verified the `contrib-check`, tests, and build & install process.

**Comment by pvillard31** [comment]
Hey @alopresto. I definitely agree with you. In fact what do you think about setting 0B as default File Size value and setting Text as default Data Format? This way user is only required to set one single property for custom text. There is no compatibility issue and I think it will be closer to what users are doing most of the time.

I just rebased/pushed with the additional changes, let me know if it is OK for you.

**Comment by alopresto** [comment]
I like those decisions. In the middle of something but will re-verify and then merge.

**Pull request closed without merging**
