### PR TITLE
NIFI-7534 Consume MQTT Processor. Support Expression Language for Topic Filter Property

### PR DESCRIPTION
**Pull request by kpsngh1998**
NIFI-7534 Consume MQTT Processor. Support Expression Language for Topic Filter Property

Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR
Added variable registry expression language  support for Topic Filter property. 
Note: Flowfile attribute expression lanuguage support is not added since evaluation is done in OnScheduled and no flowfile is available there.

_Enables X functionality; fixes bug NIFI-7534._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [x] Have you verified that the full build is successful on JDK 8?
- [x] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by pvillard31** [comment]
Any reason for not using parameters?

**Comment by kpsngh1998** [comment]
@pvillard31  Could you elaborate which parameters? Are you asking about parameters of evaluateAttributeExpressions() method? If yes, since possible parameters are related to Flowfiles and ConsumeMQTT don't have any incoming flowfile, so didn't use any parameter.

**Comment by pvillard31** [comment]
I'd also add that with the addition of this concept of parameters (as a far better replacement of the variables), expression language should only be set where it makes sense to call some EL functions or to reference attributes of incoming flow files. But I'm not sure this is required for this specific use case since it does not accept incoming connections. Having said that, your change is valid from a code point of view, so I can merge it if there is use case that requires it.

**Comment by kpsngh1998** [comment]
Thanks for sharing info on parameters. Regarding EL usecase, I couldn't think of any atleast for MQTT source except only when you have topicName present in some registry file and you want to access it using EL. This jira was already raised so i picked it up as my first PR.

**Comment by pvillard31** [comment]
That's fine, it's not causing any issue and could be useful for people not willing to move to parameters right away. But going forward we really want to have people using Parameters instead of Variables.

**Review by pvillard31 — APPROVED** [review]
Thanks for the contribution @kpsngh1998

**Pull request closed without merging**
