### PR TITLE
NIFI-1595 fixed ReflectionUtils to honor bridge methods

### PR DESCRIPTION
**Pull request by olegz**
Refactored and simplified ReflectionUtils while at it
Added ReflectionUtilsTest

### CODE REVIEW

**Comment by apiri** [comment]
@olegz Code looks good.  As seen on the mailing list traffic I was not able to create a similar situation in OS X, but was able to do so within an Ubuntu VM.  I took master, applied @pvillard31 proposed PR, built and verified onStopped was not invoked.  I then applied this PR and verified that onStopped was invoked.  Great job knowing the issue and having a remedy.  Will merge into master shortly, but would like to first remove the formatting/whitespace changes.

**Comment by olegz** [comment]
np, most of the formatting was done to javadocs since they were too long. Is that the changes you are referring to? Just curious

**Comment by apiri** [comment]
Yep.  I believe these were valid according to checkstyle rules which permit up to 200 characters/line

**Comment by olegz** [comment]
np

**Pull request closed without merging**
