### PR TITLE
NIFIREG-395 - Implemented the ability to import and export versioned …

### PR DESCRIPTION
**Pull request by mtien-apache**
…flows through the UI.

- Added REST endpoints in BucketFlowResource for importVersionedFlow and exportVersionedFlow.

- Added import and export dialogs.

- Set the initial value for the Bucket dropdown menu in the Import dialogs.

- Added frontend and backend integration tests.

- Created ExportedVersionedFlowSnapshot object.

- Added test resource file and updated rat configuration to skip the file during contrib-check.

- Refactored frontend and server side code.

- Updated Flow Actions menu hover and focus styles.

Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Enables X functionality; fixes bug NIFI-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [ ] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by mtien-apache** [comment]
@exceptionfactory @bbende @sardell @andrewmlim Would you review one more time? Opened a new PR after NiFi Registry was migrated into NiFi. There are no code changes on my end since your last reviews/approvals. Thanks!

**Comment by andrewmlim** [comment]
+1 LGTM Ran through same test cases I did for https://github.com/apache/nifi-registry/pull/319 including some basic authorization testing.

**Comment by sardell** [comment]
Taking another look now...

**Comment by sardell** [comment]
+1 (non-binding). LGTM!

**Comment by bbende** [comment]
+1 everything still looks good, nice work!

One minor thing I noticed while doing another test... in the first import, there is no box to specify Comments for the first version, but there is Flow Description which is technically a different field for the overall versioned flow, then on future imports of additional versions there is a Comments field. I'm in no way saying to hold this up, just wanted to note it for future consideration.

**Review by exceptionfactory — APPROVED** [review]
Looks good, thanks @mtien-apache!

**Comment by mtien-apache** [comment]
> One minor thing I noticed while doing another test... in the first import, there is no box to specify Comments for the first version, but there is Flow Description which is technically a different field for the overall versioned flow, then on future imports of additional versions there is a Comments field. I'm in no way saying to hold this up, just wanted to note it for future consideration.

@bbende Do you propose adding a Comments box in the dialog for 'Import New Flow' (first version)? I can create a separate JIRA for this. Thanks.

**Comment by bbende** [comment]
Yes I think it makes sense to allow it. It would be consistent with Start Version Control from NiFi which has a Description and Comments field for the first version.

**Comment by mtien-apache** [comment]
Here is the JIRA ([NIFI-8660](https://issues.apache.org/jira/browse/NIFI-8660)) to allow adding Comments when importing a new flow.

**Comment by markap14** [comment]
I see 4 +1's but no objections. Based on that, will merge.

**Pull request merged**
