### PR TITLE
NIFI-2685 - Configure surefire to use JAVA Headless mode

### PR DESCRIPTION
**Pull request by trixpan**

### CODE REVIEW

**Comment by trixpan** [comment]
@trkurc 

it just came to my mind that the pom.xml change should be safe to commit.

The change is just pushing into the build phase a setting that is already present when nifi is executed:

```
$ grep awt bootstrap.conf
java.arg.14=-Djava.awt.headless=true
```

**Comment by trkurc** [comment]
+1, please merge in.

**Comment by mattyb149** [comment]
Thanks! With Tony's +1, merging to master.

**Comment by mattyb149** [comment]
I saw the fix version included 0.8.0, so I merged to 0.x as well.

**Pull request closed without merging**
