### PR TITLE
NIFI-5377 prevent infinite loop if a controller service circular refe…

### PR DESCRIPTION
**Pull request by markobean**
…rence exists

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by mcgilman** [comment]
Will review....

**Comment by mcgilman** [comment]
@markobean Thanks for the PR! I've tried running it and it does indeed address the issue called out in the JIRA. Previously, the infinite loop occurred when trying to configure the services in question. With the PR in place, I can now configure the services to build the reference cycle. However, if I try to enable them I encountered a different infinite loop here:

at org.apache.nifi.controller.service.StandardControllerServiceReference.findRecursiveReferences(StandardControllerServiceReference.java:125)

I also seem to recall that previously the framework would identify when a reference cycle was detected and it would set that flag in the `ControllerServiceReferencingComponentDTO`. I noticed in the UI after establishing the reference cycle, the framework did not appear to detect it. This may or may not be related to the infinite loop referenced above. I do not believe this infinite loop is a result of this PR, but it's something we should probably address now as well.

In my scenario service A did not reference any other service, service B referenced service A and C, and service C referenced service B. In your testing, did you happen to hit the same loop I did when trying to enable them?

**Comment by JonathanKessler** [comment]
@mcgilman Did you experience this behavior on the graph or in a unit test? After fixing the infinite loop locally I was never able to enable the controller services on the graph because they were never valid: A depends on B which depends on A. A is not enabled so B cannot be enabled and vice versa.

**Comment by mcgilman** [comment]
@JonathanKessler I experienced it on the graph. If you add another service (like I described) you should be able to enable the service with no dependencies. As part of that action, you can indicate whether you want referencing services to also be enabled.

**Comment by markap14** [comment]
@mcgilman I did a quick review as well and I agree with your assessment that this does in fact address the issue brought up but there are still similar issues. I attached a .patch file to the JIRA that I believe addresses those. If you want to review that .patch file and you're okay with it then we can go ahead and merge in this PR and that patch file to close this JIRA out. Thanks!

**Comment by mcgilman** [comment]
Thanks @markap14! I'll pull down this PR and apply your patch for reviewing purposes.

**Comment by mcgilman** [comment]
Thanks @markobean and @markap14. These have been merged to master.

**Pull request closed without merging**
