### PR TITLE
NIFI-7442 Add CLI commands to the registry in order to support automa…

### PR DESCRIPTION
**Pull request by simonbence**
[NIFI-7442](https://issues.apache.org/jira/browse/NIFI-7442)

New commands were added to the CLI to be able to create/update users, user groups and access policies in NiFi Registry. As NiFi depends on released Registry, some code temporarily takes place in NiFi which should be moved to the Registry in the long term. Also, this comes with some code duplication as well (which will be removed in a later point too).

#### Description of PR

_Enables X functionality; fixes bug NIFI-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [x] Have you verified that the full build is successful on JDK 8?
- [x] Have you verified that the full build is successful on JDK 11?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [x] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [x] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by bbende** [comment]
Reviewing...

**Comment by bbende** [comment]
Currently there are two separate commands for "create policy" and "update policy", where NiFi only has one command "update policy" which does a "create or update". 

The other issue is that the current "update policy" command requires the policy id, but there is no command to retrieve a policy by resource+action, so no one would know the id of the policy to update.

I think we should collapse the CreatePolicy into UpdatePolicy, and make it based on resource+action like NiFi.

**Comment by tpalfy** [comment]
I was reviewing this PR and had some additional updates.
I will submit a new PR with Bence’s work + mine (Bence's commit is preserved in the new PR).

**Comment by simonbence** [comment]
@tpalfy Thanks for taking over!

**Pull request closed without merging**
