### PR TITLE
NIFI-2715 - When performing a Queue Listing, if...

### PR DESCRIPTION
**Pull request by yuri1969**
...FlowFile has no content, UI does not indicate this fact

For FlowFiles with no content:
* Added a simple title replacing the Content Claim's one.
* Defaulted File Size to 0 bytes using common formatting.

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?

### CODE REVIEW

**Comment by scottyaslan** [comment]
Reviewing....

**Comment by scottyaslan** [comment]
@yuri1969 this is looking good however I have a few comments: For the case where the FF has no size the text 'No Content Available' is good but we should keep the .flowfile-header 'Content Claim' visible and move the text 'No Content Available' below that header and give it an .unset css class.

**Comment by scottyaslan** [comment]
@yuri1969 there are still a few style issues with the 'No Content Available' text. It seems you are incorrectly applying a font-size of 12px when it should be 13px. Also, you are applying a 'Roboto-Slab' font to the text when it should only be 'Roboto'. Let me know when you have updated this PR and I will review it again.

**Comment by yuri1969** [comment]
@scottyaslan The text's style should match the one used on detail values now.

**Pull request closed without merging**
