### PR TITLE
NIFI-13501 removed DecryptContent and DecryptContentCompatibility

### PR DESCRIPTION
**Pull request by joewitt**
# Summary

[NIFI-13501](https://issues.apache.org/jira/browse/NIFI-13501)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for putting this together @joewitt. The Processor removal looks good, but there are several other classes in `nifi-cipher-processors` that also need to be removed, including the following packages and files:

- algorithm
- compatibility
- encoded
- CipherAttributeKey
- CipherException

**Comment by joewitt** [comment]
eh yeah will take a look.  Some of the dead code hunting was more sporting than I hoped

**Comment by joewitt** [comment]
ok this next commit i think got em all

**Review by exceptionfactory — APPROVED** [review]
Thanks for including the removal of the related classes @joewitt, looks good! +1 merging

**Pull request closed without merging**
