### PR TITLE
NIFI-3405 - Add uptime to JVM section in System Diagnostics

### PR DESCRIPTION
**Pull request by pvillard31**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by ijokarumawak** [comment]
Reviewing..

**Comment by ijokarumawak** [comment]
@pvillard31 Thanks for the improvement! I've tested it with a standalone and cluster mode.
Although uptime was displayed as expected, I felt the NiFi Cluster dialog became a little bit confusing because there are two 'Uptime' columns now. One is in 'NODES' tab, and another is 'JVM' tab.

The one in 'NODES' tab is actually a timestamp denoting when the node has started.
https://github.com/apache/nifi/blob/master/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/cluster/nf-cluster-table.js#L498

I'd suggest renaming the existing one in 'NODES' tab to something like `Started At`. How do you think?

image

image

**Comment by pvillard31** [comment]
Hey @ijokarumawak, thanks a lot for your review. Nice catch for the column name and I agree with you. I pushed another commit to address the column name. Let me know if you want me to squash my commits.

**Comment by ijokarumawak** [comment]
@pvillard31 Thanks for updating the PR, LGTM. Squashed and merged it into master branch.

**Pull request closed without merging**
