### PR TITLE
NIFI-1511 now only sets groovy eclipse compiler for test compiles

### PR DESCRIPTION
**Pull request by joewitt**
NIFI-1511 now only sets groovy eclipse compiler for test compiles

### CODE REVIEW

**Comment by mattyb149** [comment]
reviewing

**Comment by mattyb149** [comment]
+1 LGTM, local and Travis tests passed, with groovy-eclipse compiler only used on modules with Groovy tests inside (nifi-web-security, nifi-standard-processors, e.g.)

**Comment by mattyb149** [comment]
Although the commits should be squashed :) Will merge once this is done

**Comment by joewitt** [comment]
operation squash that jazz be complete

**Pull request closed without merging**
