### PR TITLE
NIFI-2298 added Kafka consume attributes to a FlowFile

### PR DESCRIPTION
**Pull request by olegz**

### CODE REVIEW

**Comment by xmlking** [comment]
@olegz does consumeKafka support back pressure ?
I would like to add ControlRate processor after consumeKafka to reduce the speed of messages pumped into nifi flow.

**Comment by olegz** [comment]
@xmlking Back Pressure is the function of all processors so there is nothing specific required in ConsumeKafka to handle it. Does that answer your question?

**Comment by xmlking** [comment]
Yes. Thanks

**Comment by joewitt** [comment]
There are definitely ways to defeat backpressure from working properly when implementing processors though so definitely a fair question for something like this.

**Pull request closed without merging**
