### PR TITLE
NIFI-13528: Python processor's customValidate function does not work

### PR DESCRIPTION
**Pull request by mark-bathori**
# Summary

[NIFI-13528](https://issues.apache.org/jira/browse/NIFI-13528)

Example for customValidate usage with the current changes:

```
  def customValidate(self, context):
      validationResult = ValidationResult()
      validationResult.add_validation_result("Test subject 1", "Test validation 1", False, "Input 1")
      validationResult.add_validation_result("Test subject 2", "Test validation 2", False, "Input 2")

      return validationResult.build_validation_result_list()
```

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [x] Build completed using `mvn clean install -P contrib-check`
  - [x] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by markap14** [comment]
Hey @mark-bathori thanks for the update! I agree with the problem and the general approach. The only concern that I have here is with the new `ValidationResult` class. Specifically, I don't think it makes sense to create a `ValidationResult` and then call `add_validation_result` on that object. I would also like to avoid having to create a `ValidationResult` just to call `build_validation_result_list()` just in order to return it.

Rather, I think we should define `ValidationResult` to have an `init` that takes those 4 parameters (`subject`, `valid`, `explanation`, input`) and just return a `list` of them from the method. For example, we should be able to implement the above as:

```
  def customValidate(self, context):
      results = []
      results.append(new ValidationResult(subject="Test subject 1", explanation="Test validation 1", valid=False, input="Input 1")
      results.append(new ValidationResult(subject="Test subject 2", explanation="Test validation 2", valid=False, input="Input 1")
      return results
```

Or, alternatively,
```
  def customValidate(self, context):
      return [
            new ValidationResult(subject="Test subject 1", explanation="Test validation 1", valid=False, input="Input 1"),
            new ValidationResult(subject="Test subject 2", explanation="Test validation 2", valid=False, input="Input 1")]
```

The `PythonProcessorAdapter`, then, should be responsible for taking that Python `list` that is returned and converting it into the `ArrayList` needed by the framework.

**Comment by mark-bathori** [comment]
Thanks @markap14 for the review, I reworked the PR according to your comments.

**Review by pgyori — COMMENTED** [review]
Thank you @mark-bathori !
The Python classes you created/modified all have corresponding Java interfaces. I understand that the Python classes do not need to implement all the methods from the corresponding Java interface. However, I found it a little confusing at first that there is a slight mismatch between the Python class methods and the Java interface method declarations. I would like to suggest the following changes to sync the Python side with the Java side:
- PropertyContext in Java has a method 'getAllProperties()', please consider renaming the Python PropertyContext.getProperties() method to that.
- ProcessContext and ValidationContext in Java both have methods called 'getProperties()' and 'newPropertyValue()'. Please consider moving the corresponding Python methods from PropertyContext to the two subclasses. (getProperties() in the sublclasses could call the supercass' getAllProperties() method). I understand that this would cause code duplication, I only recommend it so that the Python code matches the Java code.

I believe these small changes would make it a little more straightforward to understand the code should someone in the future continue extending the Python classes based on the Java interfaces.

**Comment by mark-bathori** [comment]
Thanks @pgyori  for the review. I think that it is a good approach to offer the same functionality both in Python and Java side, however I feel it is unnecessary to add methods that are currently unused. Over time we can further extend the Python side with additional methods when new functionalities will require them.

- Renaming 'getProperties()' to 'getAllProperties()' wouldn't be good because they have different return type in Java side
- At this point I would also avoid code duplication, since both contexts use the same approach for 'getProperties()' and 'newPropertyValue()' so I would keep it as it is for now.

**Comment by pgyori** [comment]
Thank you @mark-bathori , I understand and accept your reasoning.
+1 merging.

**Pull request closed without merging**
