### PR TITLE
Add table attributes to flow files

### PR DESCRIPTION
**Pull request by ambud**
https://issues.apache.org/jira/browse/NIFI-3525

Adding table name to flowfile attributes

### CODE REVIEW

**Comment by jvwing** [comment]
@ambud - Welcome to NiFi!  Thank you for contributing this, I will review.  In the future, please keep the PR boilerplate comment and fill out the checklist.  It has some helpful tips on the PR  and commit naming conventions and info for reviewers.

**Comment by jvwing** [comment]
I also recommend running a full build with `mvn clean install -Pcontrib-check`.  It looks like several of the QueryDatabaseTableTest unit tests are failing:

>Tests run: 11, Failures: 8, Errors: 0, Skipped: 0, Time elapsed: 1.006 sec <<< FAILURE! - in org.apache.nifi.processors.standard.QueryDatabaseTableTest
testWithRuntimeException(org.apache.nifi.processors.standard.QueryDatabaseTableTest)  Time elapsed: 0.388 sec  <<< FAILURE!
java.lang.AssertionError: org.apache.nifi.processor.exception.FlowFileHandlingException: Cannot commit session because the following FlowFiles have not been removed or transferred: [0]

My quick take is that the happy-path works fine with your code, but paths that do not result in a flowfile output are failing because the session is not cleaned up.  How about moving the call to `session.putAttribute` down to line ~300 by where RESULT_ROW_COUNT is added?  A viable output flowfile is being formatted here, and being in the same neighborhood with other attribute assignments might be easier to understand.  What do you think?

**Comment by ambud** [comment]
@jvwing thanks for the input, changed and fixed. The issue was i didn't reassign the flow file variable fromt the put attribute statement.

**Comment by jvwing** [comment]
Thanks for the update @ambud, the tests are passing.  I have two other comments:

1.) Similar attributes, like RESULT_ROW_COUNT are defined as static final member variables, so they can be referenced consistently (mostly in tests).  I recommend we do the same for table.name.

2.) I looked for an established attribute naming convention that would apply to `table.name`.  
* The ListDatabaseTables processor uses `db.table.name`, but it has a consistent `db.*` pattern for all of its attributes that QueryDatabaseTable does not.  
* QueryDatabaseTable has `querydbtable.row.count`, which might suggest a `querydbtable.*` pattern like `querydbtable.table.name`, except that there is only one such attribute (the fragment attributes are idiomatic and might not apply, `maxvalue.*` is the only other existing attribute written).  

Having done this research, I'm now more confused than when I started :), so I don't have the concrete recommendation I was hoping to arrive at.  Have you looked into this, and how did you arrive at `table.name`?

**Comment by ambud** [comment]
1) Agreed, I overlooked it and will add that

2) Ideally I would just do tablename (one word) without delimiters for simplicity of downstream processing. Let me know if there's another preferred convention here.

**Comment by jvwing** [comment]
No, there doesn't seem to be a convention to guide us.  If you prefer `tablename`, I'm OK with it.

**Comment by ambud** [comment]
@jvwing changed the name, squashed commits.

**Comment by jvwing** [comment]
Thanks, @ambud, we're getting closer.  There are a few items in the latest commit:

* QueryDatabaseTable has class members TABLE_NAME for the input property descriptor, and TABLENAME for the output attribute name.  How about renaming TABLENAME to RESULT_TABLENAME to clarify?
* The unit test testAddedRows is failing because it is still using `"table.name"` as a literal string.
* There is a checkstyle error for a tab in QueryDatabaseTable.java:106.

You can see the test and checkstyle errors when you run `mvn clean install -Pcontrib-check` for the NiFi project.

**Comment by ambud** [comment]
Sorry about that, fixed.

**Comment by jvwing** [comment]
Thanks again for contributing this, @ambud!

**Comment by ambud** [comment]
Thanks for your help in fixing the unit tests @jvwing

**Pull request closed without merging**
