### PR TITLE
NIFI-6057 allow request body to come from an expression

### PR DESCRIPTION
**Pull request by SavtechSolutions**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [x] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [x] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by pvillard31** [comment]
Hi @SavtechSolutions - can you elaborate on the use case? do you have a situation where you want to send a request with a body which is not the content of the flow file? can't you just replace the content of the flow file before the InvokeHTTP processor?

**Comment by SavtechSolutions** [comment]
Not if you want to retain the flowfile content for further processing. Consider, for example, a case of writing a confluent-encoded record set, if you want to account for the cases when the schema might not have been registered yet. You'd want to issue a POST against the schema registry, with the schema as body, but you'd also want to keep the record set for subsequent writing.

**Comment by mattyb149** [comment]
Sounds like a similar use case to PutSQL where we added a property to use instead of the content ([NIFI-4522](https://issues.apache.org/jira/browse/NIFI-4522)), the user would want to issue a statement based on receiving the flow file, but retain the contents for further downstream processing.

I haven't reviewed this PR, but I mention the above to recommend we handle such things in a consistent manner across components, for best practices and patterns with a friendly user experience.

**Comment by joewitt** [comment]
closing due to inactivity

**Pull request closed without merging**
