### PR TITLE
Fix for NIFI-1838 & NIFI-1152 & Code modification for typeSafety

### PR DESCRIPTION
**Pull request by PuspenduBanerjee**
In post 1.4 Java era we should adhere to stricter code compliance.

### CODE REVIEW

**Comment by PuspenduBanerjee** [comment]
@joewitt @apiri Please guide. Not sure why appveyor build is failing

**Comment by apiri** [comment]
@PuspenduBanerjee unfortunately the appveyor results are a bit of noise at the moment as the associated PR #370 has yet to be incorporated.  As a result, out of the box, it is trying to build its default which is not a Maven based project.

**Comment by PuspenduBanerjee** [comment]
@apiri Please incorporate PR #370 as soon as you can. It will be a great help.

**Comment by apiri** [comment]
@PuspenduBanerjee Certainly will.  Currently pending review before I am able to incorporate.

**Comment by PuspenduBanerjee** [comment]
Updated to address Fix for NIFI-1838 & NIFI-1152

**Comment by PuspenduBanerjee** [comment]
@markap14 If it looks good, will you be able to check in?

**Comment by PuspenduBanerjee** [comment]
@markap14  @trkurc @apiri Will anyone get a chance to merge it in.

**Pull request closed without merging**
