### PR TITLE
NIFI-5542 Added support for node groups to FileAccessPolicyProvider

### PR DESCRIPTION
**Pull request by achristianson**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [x] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [x] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by achristianson** [comment]
@pepov @mcgilman new PR where we authorize the node group rather than its users. Please take a look when you get a chance.

**Comment by pepov** [comment]
+1 looks good to me now

**Comment by pepov** [comment]
Thanks for pointing this out! Of course we need identity here, but if I'm right `identity` is called `name` in case of groups.

**Comment by pepov** [comment]
I'm not trying to suggest naming just to point out that the Group has the `name` property instead of the `identity` that the User has. The workaround should be as simple as looping through the groups and finding the one with a matching name, am I right?

**Comment by kevdoran** [comment]
Yes, that should work fine to lookup group by name. Good point regarding the field name of the Group object. Thanks for looking into this!

**Comment by achristianson** [comment]
@pepov @kevdoran thanks for the feedback. I'll update the docs to reflect the property change, and update the code to reflect that the group name is provided and look up the group identifier accordingly.

**Comment by pepov** [comment]
Some unit tests are failing according to the travis build that are relevant:
```
[ERROR] testOnConfiguredWhenInitialAdminAndLegacyUsersProvided(org.apache.nifi.authorization.FileAccessPolicyProviderTest)  Time elapsed: 0.114 s  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<org.apache.nifi.authorization.exception.AuthorizerCreationException> but was<java.lang.NullPointerException>
	at org.apache.nifi.authorization.FileAccessPolicyProviderTest.testOnConfiguredWhenInitialAdminAndLegacyUsersProvided(FileAccessPolicyProviderTest.java:523)

[ERROR] testOnConfiguredWhenBadLegacyUsersFileProvided(org.apache.nifi.authorization.FileAccessPolicyProviderTest)  Time elapsed: 0.036 s  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<org.apache.nifi.authorization.exception.AuthorizerCreationException> but was<java.lang.NullPointerException>
	at org.apache.nifi.authorization.FileAccessPolicyProviderTest.testOnConfiguredWhenBadLegacyUsersFileProvided(FileAccessPolicyProviderTest.java:509)
```
https://api.travis-ci.org/v3/job/422545351/log.txt

**Comment by achristianson** [comment]
The group id lookup logic was running even if group name was not specified. Fixed that. All tests are passing locally.

**Comment by pepov** [comment]
Nitpicking but now we do 2 lookups. First we look up the group to get the identifier then we lookup the same group using that identifier. I beleive it would be enough to store the group name property and look it up in the populateNodes method only, but this is nitpicking, since there is no performance or memory penalty in it, so overall this looks good to me.

**Comment by achristianson** [comment]
@pepov is the second lookup you're referring to this line?

```java

            Group nodeGroup = userGroupProvider.getGroup(nodeGroupIdentifier);
```

**Comment by pepov** [comment]
yes

**Comment by achristianson** [comment]
@pepov I took that lookup out. It appeared to be completely unnecessary.

**Comment by pepov** [comment]
Even better, thanks!

**Comment by pepov** [comment]
@kevdoran Are you okay with the current state? Also @mcgilman can you take a look at this?

**Comment by pepov** [comment]
@kevdoran @achristianson created a follow up PR to avoid an issue with the default empty "Node Group" in authorizers.xml: https://github.com/apache/nifi/pull/3043

**Pull request closed without merging**
