### PR TITLE
NIFI-11754 Refactored Groovy test in nifi-jetty to Java (and JUnit 5)

### PR DESCRIPTION
**Pull request by dan-s1**
# Summary

[NIFI-11754](https://issues.apache.org/jira/browse/NIFI-11754)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [x] Build completed using `mvn clean install -P contrib-check`
  - [x] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by dan-s1** [comment]
@exceptionfactory I was able to refactor the unit test and test it locally but I am not sure why though when I run
`mvn clean install -P contrib-check`
the tests in the `nifi-jetty` are skipped.

**Comment by dan-s1** [comment]
@exceptionfactory Hmm again the failure does not relate to my change.

**Review by exceptionfactory — APPROVED** [review]
Thanks @dan-s1, the changes look good, the system test failure is unrelated. +1 merging

**Comment by dan-s1** [comment]
@exceptionfactory Thank you for accepting my PR and merging. I still do have a remaining question. I looked at the raw logs from the build(s) yet I do not see `org.apache.nifi.web.server.HostHeaderHandlerTest` being run. What am I missing?

**Comment by exceptionfactory** [comment]
@dan-s1 The GitHub Actions builds have the default log level set to warning, so they do not print every test class status. This may be something to revisit, but it does generate a lot of output. The `HostHeaderHandlerTest` shows up in a local build.

**Pull request closed without merging**
