### PR TITLE
NIFI-3220 Add support for basic auth to Solr processors

### PR DESCRIPTION
**Pull request by bbende**
Also made the Solr Location support expression location so it can be paramterized with the variable registry.

### CODE REVIEW

**Comment by ijokarumawak** [comment]
Start reviewing, and testing with Solr..

@bbende 
This is an out of scope question, but let me ask..
Should GetSolr utilize NiFi state management to store last query timestamp, so that other node can takeover if the node goes down? (I assume this processor is designed to run on a primary node) Or to retain the state across NiFi restart? 
If so, I think I will create a JIRA for that.

**Comment by bbende** [comment]
@ijokarumawak yes we should definitely create another JIRA to convert GetSolr to use state management, I keep forgetting that it doesn't do that already.

If you need any help with the basic auth setup let me know, I just followed Solr's wiki page:
https://cwiki.apache.org/confluence/display/solr/Basic+Authentication+Plugin

**Comment by ijokarumawak** [comment]
Thanks @bbende I've created [NIFI-3252: Make use of State management in GetSolr](https://issues.apache.org/jira/browse/NIFI-3252).

**Comment by ijokarumawak** [comment]
Tested with Solr cluster with basic authentication, both GetSolr and PutSolrContentStream were able to communicate with the Solr cluster.
Thanks @bbende , I've merged this into master!

**Pull request closed without merging**
