### PR TITLE
NIFI-10875 fixed flaky test

### PR DESCRIPTION
**Pull request by tt0suzy**
# Summary

[NIFI-10875](https://issues.apache.org/jira/browse/NIFI-10875)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [x] JDK 8
  - [ ] JDK 11
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by exceptionfactory** [comment]
Thanks for the contribution @tt0suzy. Instead of changing the test to use the inline conditional, a better approach would be to assert the presence of the individual key=value parameters. That would avoid depending on parameter order while keeping the test clear.

**Comment by tt0suzy** [comment]
Hi @exceptionfactory, are you suggesting something like
```
String querySrting = attributes.get(QuerySolr.ATTRIBUTE_SOLR_QUERY)
//"q=*:*&qt=/select&start=0&rows=10&stats=true&facet=true"
assertTrue(queryString.contains("q=*:*") && queryString.contains("qt=/select") && querystring.contains("start=0") && queryString.contains("rows=10") && queryString.contains("stats=true") && queryString.contains("facet=true"));
```

**Comment by exceptionfactory** [comment]
> Hi @exceptionfactory, are you suggesting something like
> 
> ```
> String querySrting = attributes.get(QuerySolr.ATTRIBUTE_SOLR_QUERY)
> //"q=*:*&qt=/select&start=0&rows=10&stats=true&facet=true"
> assertTrue(queryString.contains("q=*:*") && queryString.contains("qt=/select") && querystring.contains("start=0") && queryString.contains("rows=10") && queryString.contains("stats=true") && queryString.contains("facet=true"));
> ```

Thanks for the reply @tt0suzy. Yes, that is the basic idea. Instead of multiple `queryString.contains()` calls with in one `assertTrue`.  Having one assert per check would be helpful to keep the code clear:

```
assertTrue(queryString.contains("q=*:*"));
assertTrue(queryString.contains("qt=/select"));
...

**Comment by tt0suzy** [comment]
Updated, thanks for the advice.

**Review by exceptionfactory — APPROVED** [review]
Thanks for making the changes @tt0suzy, the latest version looks good. +1 merging

**Pull request closed without merging**
