### PR TITLE
NIFI-2406: Ensure that hearbeat monitor continues to run while instance …

### PR DESCRIPTION
**Pull request by markap14**
…is running. This way if a node sends heartbeat to this node as elected coordinator changes, we notify the node accordingly. Handle Exceptions more gracefully in leader election code.

### CODE REVIEW

**Comment by YolandaMDavis** [comment]
@markap14 started review

**Comment by YolandaMDavis** [comment]
@markap14 was able to rebase and resolve conflicts locally on FlowController (conflict was based on imports). Executed on small cluster was able to trigger exception on takeLeadership (listener.onLeaderElecetion) and that properly logged error instead of throwing exception. Did not see the messages detailed in log in [NIFI-2406](https://issues.apache.org/jira/browse/NIFI-2406) after trying different combinations of removing nodes and restoring. 

+1 (pending rebase/merge)

**Comment by markap14** [comment]
@YolandaMDavis thanks - PR i was rebased & pushed

**Comment by YolandaMDavis** [comment]
@markap14 thanks! have retested tried disconnecting nodes as well as restarting nodes in cluster.  Did see the error logged "This node was elected Leader for Role 'Cluster Coordinator' but failed to take leadership. Will relinquish leadership role." on one node with error thrown due to the node not being part of the cluster.  That was also followed up with the logged warning "Failed to determine which node is elected active Cluster Coordinator: ZooKeeper reports the address as 127.0.0.1:11001, but there is no node with this address".  This occurred during initial startup and appeared to resolve once the cluster coodinator (node 2, on port 11001) came online.

I also shutdown node 2 (which was Cluster Coordinator) and noted the repeated "Failed to send heartbeat due to: org.apache.nifi.cluster.protocol.ProtocolException: Failed to send message to Cluster Coordinator due to: java.net.ConnectException: Connection refused" warning in node 1's log.  This was expected based on notes in Jira.  Node 1 was primary node at the time.  When node 2 was back online the heartbeat warning no longer appeared in node 1's log however I could not access node 1's UI (it was displaying an error demonstrated in the snapshot below).

I've included just the nifi-app logs from both servers since it seemed to have the most relevant information. Would focus on logs with timestamps beginning at 13:35 (08-04-2016). Please let me know if you need any additional information or logs.


node1-error-cc-restart

[logs.zip](https://github.com/apache/nifi/files/402267/logs.zip)

**Comment by markap14** [comment]
@YolandaMDavis is this cluster running an embedded zookeeper? If so, which node(s)?

**Comment by markap14** [comment]
@YolandaMDavis I've been able to replicate this running a 2-node cluster. I tweaked a few things to address how nodes reconnect and ensure that they are in-sync with the rest of the cluster. I pushed as a separate commit so you can see what's changed.

**Comment by YolandaMDavis** [comment]
@markap14 awesome will review as soon as possible thanks!

**Comment by YolandaMDavis** [comment]
@markap14 thank you for this update. I executed my tests as previously described and ran into no issues. When disconnecting a node designated as cluster coordinator from both the UI and on the command line (through stop/restart) the remaining nodes behaves as expected. It properly displays an error to the user and nots in logs it's inability to determine a cluster coordinator. When the coordinator is back online the logs indicate successful reconnection and communication. Refresh of the screen properly demonstrates the flow and configured flow (which consists of use of remote process groups communicating with a standalone nifi node) operate successfully

+1

thank you @markap14 for the quick turnaround on this!

**Pull request closed without merging**
