### PR TITLE
Introduce data resource for authorizing Provenance and Queue interactions

### PR DESCRIPTION
**Pull request by mcgilman**
NIFI-2346:
- Introducing data resource for authorizing provenance events and queue listing.
- Authorizing entire proxy chain for data resource and data transfer resource.

NIFI-2338:
- Ensuring that replay authorization only happens once.

- Allowing users with access to policies for a component to be able to access all policies for that component.
-- Includes the component, data, data transfers, and policies.
- Fixing drop request completion to update the correct queued field.
- Fixing access control check for listing and emptying queues.
- Reseting selected policy when re-opening the policy management page.
- Fixing button/link visibility for available actions in policy management page.
- Fixing policy issues with policy removal when the underlying component is deleted.

### CODE REVIEW

**Comment by markap14** [comment]
Things look good on here, but I noticed that the seeding of the authorizations.xml file does not include the DN's of the hosts in my authorizers.xml file, but it did include my 'admin dn' from the authorizers.xml file (for the 'view data' and 'modify data' policies of the root group).

**Comment by mcgilman** [comment]
@markap14 Good catch. We also need to do this for site to site data transfers. Will update the seeding.

**Comment by mcgilman** [comment]
@markap14 PR has been updated to address the comments.

**Comment by markap14** [comment]
Code looks good now. Unit tests are good. Tested functionality and all appears to work as expected. +1 merged to master. Thanks!

**Pull request closed without merging**
