### PR TITLE
Fix for unit tests that are causing build failures in certain environ…

### PR DESCRIPTION
**Pull request by markap14**
…ments

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by markap14** [comment]
This PR exists solely to check that it addresses a build failure that occurs on Travis CI. I have been unable to replicate locally but believe that I understand the issue. If this addresses the build failure, I will handle merging to master.

**Comment by mosermw** [comment]
@markap14  I tried your change locally and it does fix one of the two test failures.  The validateConsumeWithCustomHeadersAndProperties() is fixed but validateFailOnUnsupportedMessageType() still fails.  I haven't been able to figure out why, yet.

**Comment by mosermw** [comment]
Nevermind my last comment.  It looks like this is going to resolve both unit test failures.

**Comment by markap14** [comment]
@mosermw thanks for confirming that you were able to replicate and see the correct results. Was able to confirm that Travis now builds properly as well. Pushed fix to master.

**Pull request closed without merging**
