### PR TITLE
NIFI-2684 - Change AbstractConfigurableComponent to use displayName w…

### PR DESCRIPTION
**Pull request by trixpan**
…hen available

### CODE REVIEW

**Comment by trixpan** [comment]
@joewitt this commit is quite small (intent is just aesthetics / UX) but ventures into waters I don't usually sail... Would you mind having a look?

I thank you in advance

**Comment by joewitt** [comment]
@trixpan from  DRY/readability perspective consider creating the builder ahead of the if/else.  So an alternative approach would look like this (formatting aside)

`
                    ValidationResult.Builder  builder = new ValidationResult.Builder().valid(false).input(null).subject(descriptor.getDisplayName());
                  builder = (descriptor.getDisplayName() != null) ? builder.explanation(descriptor.getDisplayName() + " is required") : .explanation(descriptor.getName() + " is required");
                    results.add(builder.build());
`

**Comment by trixpan** [comment]
@joewitt hopefully last commit addresses your feedback. Mind having another look?

Cheers

**Comment by mattyb149** [comment]
Per a discussion with @trixpan, I offered to make the final change and add the commit when merging this PR.

**Pull request closed without merging**
