### PR TITLE
NIFI-12265 Fix StandardPGPPublicKeyService key search issue with subkey starts with 0

### PR DESCRIPTION
**Pull request by nathluu**
# Summary

[NIFI-12265](https://issues.apache.org/jira/browse/NIFI-12265)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for highlighting this issue @nathluu.

This change makes sense in light of the [Long.toHexString()](https://docs.oracle.com/javase/8/docs/api/java/lang/Long.html#toHexString-long-) documentation that notes the return value will not return any leading zeroes. Given that the general hexadecimal representation includes leading zeroes, this change is helpful.

There are a couple other places in `nifi-pgp-bundle` that use `Long.toHexString()` right now. Many of those are for debugging purposes, but all of them should be addressed. The Processors module has a `KeyIdentifierConverter.format()` method that centralizes the formatting, so that should be straightforward.

Can you adjust those other references? I could also make those adjustments and push an update to this branch if you prefer.

**Comment by nathluu** [comment]
Hi @exceptionfactory, PR was updated. Please help to review it again. Thanks

**Review by exceptionfactory — COMMENTED** [review]
Thanks for making the adjustments @nathluu, the changes look good. On closer review, it makes sense to consolidate all key formatting in the `KeyIdentifierConverter`. I pushed one more commit moving the `KeyIdentifierConverter` class so that it is accessible to both Controller Services and Processors. With these changes, this should be ready to merge soon.

**Review by exceptionfactory — APPROVED** [review]
Thanks again @nathluu! +1 merging

**Pull request closed without merging**
