### PR TITLE
Nifi 4141 - Adding a processor for convert Json to Orc

### PR DESCRIPTION
**Pull request by bbasosuho**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by alopresto** [comment]
Hi,

With the release of Apache NiFi 1.2.0 and 1.3.0, the *record* paradigm has been introduced to better support protocol/format/schema conversion. This moves away from the `ConvertXToY` type processors in favor of providing custom *record reader* and *recordset writer* controller service implementations which can be leveraged and re-used by `LookupRecord`, `ConvertRecord`, `PartitionRecord`, `QueryRecord`, `MergeRecord`, `UpdateRecord`, etc. There is already a `JsonTreeReader`, `JsonPathReader`, and `JsonRecordSetWriter` available, so if you were to provide an `OrcReader` and `OrcRecordSetWriter`, you would be able to perform bidirectional conversion of JSON to/from Orc, along with Grok, CSV, Avro, freeform text, and scripted implementations.

**Comment by claudiu-stanciu** [comment]
Hi,
Just a small suggestion: would you mind modifying the PR name by starting it with the exact project - story number : 	"NIFI-4141 - Adding a processor for convert Json to Orc"?
Like this it will get picked up by the bot and added to the story https://issues.apache.org/jira/browse/NIFI-4141

From the bot: " Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character."

**Comment by joewitt** [comment]
Agree with AndyLoPrestos feedback.  Also, the libraries for columnar formats like ORC/Parquet may not make in-line conversion like this very clean.  Take a look at Fetch/Put Parquet.  We should do fetch/put ORC which operates on records.  Then as Andy mentions we can easily stream in/out for any format/schema combination that we have a reader/writer.

**Comment by pvillard31** [comment]
@bbasosuho - do you mind closing this PR now we added the PutORC processor in NiFi? Thanks.

**Comment by MikeThomsen** [comment]
@pvillard31 I agree and I'm closing based on age and the fact that the record paradigm is so entrenched that adding another convert-from-a-to-b processor doesn't make sense at this point.

**Pull request closed without merging**
