### PR TITLE
NIFI-2615 Adding support for GetTCP processor

### PR DESCRIPTION
**Pull request by apsaltis**
This is a major refactoring of a previous version of this processor that was never merged due to poor design. Special thanks to @olegz for all of his help in refactoring this processor to bring it inline with NiFi best practices.

### CODE REVIEW

**Comment by mosermw** [comment]
Nice contribution, @apsaltis. Does this need to be in its own nifi-gettcp-bundle? PutTCP is in the nifi-standard-bundle and I would expect GetTCP and PutTCP to be located in the same NAR.

**Comment by apsaltis** [comment]
@mosermw -- I can totally see how this processor would be at home in the same NAR, the reasoning for keeping it separate was to have one less processor to modify and hopefully ease the effort to integrate it into the extension registry [1] when that is ready.

[1] https://cwiki.apache.org/confluence/display/NIFI/Extension+Repositories+%28aka+Extension+Registry%29+for+Dynamically-loaded+Extensions

**Comment by mosermw** [comment]
That's definitely a fair reason.  I believe this would be the first NAR whose name contains the name of a processor.  Would you consider changing the name to nifi-tcp-bundle and nifi-tcp-nar?  When the extension registry is ready, then we could move PutTCP into this nar?

**Comment by olegz** [comment]
@mosermw +1 to the name change!

**Comment by apsaltis** [comment]
@mosermw Changing the name certainly makes sense to me. Honestly had not dawned on my that it was the first processor whose name matches the nar.

**Pull request closed without merging**
