### PR TITLE
[NIFI-2205] [NIFI-2217] [NIFI-2219] [NIFI-2180] [NIFI-2140] [NIFI-2131] [NIFI-2099] [NIFI-2233]

### PR DESCRIPTION
**Pull request by scottyaslan**

### CODE REVIEW

**Comment by moranr** [comment]
@scottyaslan I don't see headerText for Processor Group Configuration – for example if you edit a process group name and click APPLY – dialog header is empty.

**Comment by scottyaslan** [comment]
@moranr copy/paste error...I have updated the PR

**Comment by mcgilman** [comment]
Reviewing...

**Comment by mcgilman** [comment]
@scottyaslan Looks good... Ran into a couple minor issues...

1) Progress bar flickers and seems to default to 100%.
2) Label color preview does not update automatically.

**Comment by mcgilman** [comment]
Thanks @scottyaslan. This has been merged to master.

**Pull request closed without merging**
