### PR TITLE
NIFI-1968 ExtractHL7Attributes is squashing empty components

### PR DESCRIPTION
**Pull request by jfrazee**
This updates ExtractHL7Attributes and corresponding tests so it works with empty components (^^) in sub-segments. It uses the built in encoding functionality from the HAPI HL7 API so the NiFi getValue() is removed. It's worth noting that HL7's encoding of some fields (MSH.1 and MSH.2) aren't the plain text so these are unescaped in this fix. Escaping them would be a breaking change that arguably doesn't relate to any bug. Not sure what the right thing there is.

### CODE REVIEW

**Comment by mattyb149** [comment]
Reviewing...

**Comment by mattyb149** [comment]
+1 LGTM, built and ran the tests, also ran with a NiFi flow, verified the attributes with empty segment components are displayed correctly.

Mind squashing your commits? Also I was having trouble applying the patch, I may need to manually intervene but I will keep you as author of the commit(s).

**Comment by jfrazee** [comment]
@mattyb149 All squashed. The original was off of 0.x and the squashed commits are rebased onto the last few days's changes, so I think it should be clean. Not sure why it wouldn't be.

**Comment by mattyb149** [comment]
Merged this to 0.x and master, but forgot the magic string to close the PR, do you mind closing?

**Pull request closed without merging**
