### PR TITLE
NIFI-13287: Added note to msal4j dependency in Azure bundle's pom

### PR DESCRIPTION
**Pull request by turcsanyip**
# Summary

[NIFI-13287](https://issues.apache.org/jira/browse/NIFI-13287)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [x] Build completed using `mvn clean install -P contrib-check`
  - [x] JDK 21

### UI Contributions

- [ ] NiFi is modernizing its UI. Any contributions that update the [current UI](https://github.com/apache/nifi/tree/main/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui) also need to be implemented in the [new UI](https://github.com/apache/nifi/tree/main/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi).  

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by joewitt** [comment]
Is there more guidance on where that version will be found though?  It mentions match msal with the graph identity.  Can you add more context for where to look?

**Comment by turcsanyip** [comment]
Usually I check the pom's on https://search.maven.org/.

First get the `azure-identity` version from the BOM's pom, e.g.:
https://search.maven.org/artifact/com.azure/azure-sdk-bom/1.2.23/pom
=> 1.12.0
Then look for the `msal4j` version in the given `azure-identity`'s pom:
https://search.maven.org/artifact/com.azure/azure-identity/1.12.0/jar
=> 1.15.0

These are version specific URLs so I would not add them in the code.

Our `nifi-azure-graph-authorizer` uses a few `msal4j` [classes](https://github.com/apache/nifi/blob/7951b4be80f4416d2cc9b4272fb7e004c64a989e/nifi-extension-bundles/nifi-azure-bundle/nifi-azure-graph-authorizer/src/main/java/org/apache/nifi/authorization/azure/ClientCredentialAuthProvider.java#L30-L33). If no compilation error, it should be fine. If there was no common `msal4j` version for `azure-identity` and `nifi-azure-graph-authorizer`, then we would need to separate the components into 2 nars, I'm afraid. Hopefully, it will not happen.

**Comment by joewitt** [comment]
Think about it from the perspective of the people in the community that actively work to keep things up to date for vulnerability and other reasons.  The note if it is to be useful will direct on where to look/what to look for.  Notes that simply warn result in things not getting updated (we can't have that).  Notes that describe how, specifically, to improve it increase accessibility for more people to do this work.  ie: i'd use exactly those URLs and indicate they're examples.

Thanks

**Comment by turcsanyip** [comment]
@joewitt Thanks for merging it. I believe one can find enough information if they check the Jira / PR.

**Pull request closed without merging**
