### PR TITLE
NIFI-5886: Add RPM profile for NiFi Toolkit

### PR DESCRIPTION
**Pull request by yoshiata**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by sbgoodm** [comment]
An RPM build profile for the main nifi-assembly module would also be of great value. I found this PR by searching the NiFi JIRA for 'rpm', because I was about to create my own JIRA ticket and PR for an rpm profile.

Would you be willing to adjust this pull request to also create a nifi-assembly RPM that installs to `/opt/nifi/nifi-${project.version}`?

**Comment by bbende** [comment]
@sbgoodm just wanted to mention that there is already an RPM profile for the main NiFi assembly:

https://github.com/apache/nifi/blob/master/nifi-assembly/pom.xml#L802

**Comment by joewitt** [comment]
closing due to inactivity

**Comment by tasanuma** [comment]
This feature is still missing in the main branch. I hope for the new PR.

**Comment by yoshiata** [comment]
@tasanuma Thanks. I will submit the new PR.

**Pull request closed without merging**
