### PR TITLE
NIFI-2866 The Initial Max Value of QueryDatabaseTable won't be case

### PR DESCRIPTION
**Pull request by combineads**
sensitive

Now, the Initial Max Value of QueryDatabaseTable is allowed the only lowercase so I think to change the below code, it added .toLowerCase() method.
for(final Map.Entry<String,String> maxProp : maxValueProperties.entrySet()){
if (!statePropertyMap.containsKey(maxProp.getKey().toLowerCase()))
{ statePropertyMap.put(maxProp.getKey().toLowerCase(), maxProp.getValue()); }
}
When I set the property that is initial.maxvalue.UPDATE_TIME, QueryDatabaseTable doesn't have WHERE clause with UPDATE_TIME.
Thanks.

### CODE REVIEW

**Comment by combineads** [comment]
Hello, @mattyb149 .
Cloud you review this PR?

Thank you for your effort.

**Comment by mattyb149** [comment]
Can you add a unit test for this? One option is to update the testInitialMaxValue() test to change the name of the "created_on" column to uppercase, as well as the max-value column name and the initial.maxvalue.CREATED_ON attribute. That should be enough to illustrate the problem before applying your change, then the test passes after your change.

**Comment by combineads** [comment]
@mattyb149
I changed the initial.maxvalue.CREATED_ON attribute of testInitialMaxValue() test.
Thanks for your review.

**Comment by mattyb149** [comment]
Looking good, I will give this a try. However the commit that updated the unit test seems to have a title that came from a different PR/Jira case, do you mind changing the name of the commit to be more indicative of the change that was made? Thanks for the contribution!

**Comment by combineads** [comment]
@mattyb149
Sorry to bother you again. I changed the commit message.
Thanks for your review.

**Pull request closed without merging**
