### PR TITLE
NIFI-6529 Updated tests that fail with non en_US locales

### PR DESCRIPTION
**Pull request by jtstorck**
To test the fixes in this PR, run:

1. `mvn test -Pcontrib-check,include-grpc -Dmaven.surefire.arguments="-Duser.language=fr -Duser.region=FR -Duser.timezone=UTC"`
1. `mvn test -Pcontrib-check,include-grpc -Dmaven.surefire.arguments="-Duser.language=ja -Duser.region=JP -Duser.timezone=UTC"`
1. `mvn test -Pcontrib-check,include-grpc -Dmaven.surefire.arguments="-Duser.timezone=UTC"`

All three builds should finish successfully.

The `-Duser.timezone=UTC` argument for the `maven.surefire.arguments` property is to avoid the TestJdbcCommon issues in [NIFI-6479](https://issues.apache.org/jira/browse/NIFI-6479).

----

Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Updated tests that fail with non en_US locales._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by pvillard31** [comment]
Reviewing

**Comment by jtstorck** [comment]
The test code may be cleaner using NumberFormatter/Currency over String.format.  I'll take a look and update the PR today if it improves the readability of the tests.

**Comment by jtstorck** [comment]
@pvillard31 I'm taking a look at a few changes now, and I'll post an update regardless of pushing the changes to let you know that it can be merged. Thanks!

**Comment by jtstorck** [comment]
@pvillard31 In order to use NumberFormat, several instances (in almost every test case) need to be created to generate the numbers formatted properly to use as the expected value.  At this point I think we should just stick with the String.format() option; we can always update it later. 
 Most importantly, the tests work as written currently in the PR.

Please merge the PR if you are comfortable with this.

**Comment by pvillard31** [comment]
Sounds good to me ;) merging to master.
Thanks @jtstorck !

**Pull request closed without merging**
