### PR TITLE
NIFI-3780 - Should be able to specify Service...

### PR DESCRIPTION
**Pull request by yuri1969**
...name when I create a new Controller Service within a Processor/Service configuration dialog

I'm not sure how to integrate/style the text box. Suggestions are welcome.

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?

### CODE REVIEW

**Comment by scottyaslan** [comment]
Reviewing...

**Comment by moranr** [comment]
This will be a nice addition from a usability perspective.

It could be helpful to go ahead and generate a default name for the service following some type of simple naming convention (e.g., StandardSSLContextService**-1**, StandardSSLContextService**-2**, and so on). This would actually be helpful to follow for _any_ controller service that is created, not just if it is created via a processor/service configuration dialog. 

I also notice in the dialog that the name field is at the bottom of the dialog and not seen unless scrolled to. It would be helpful see that field at or near the top so the user can immediately relate to the new service by its name.

**Comment by scottyaslan** [comment]
@moranr I am not sure we could do that (currently) without the UI knowing how many CS's are named 'StandardSSLContextService-*' . I think that would require a bit more effort to create some REST endpoints etc. Maybe for this iteration we can just move the new CS name field up above the 'Compatible Controller Services'  drop down and use the class name of the selected CS in the 'Compatible Controller Services'  drop down as the default name?

**Comment by moranr** [comment]
@scottyaslan – agreed, likely a larger and separate effort to know all existing CSs. I'll create a new jira to capture the idea.

I think your suggestion as a first step is a good one. One thing I would recommend is that the CS Name field be placed _after_ the Compatible CS dropdown since the default name will be dependent of the user's Compatible CS selection.

And just to add more complexity ;) – if the user edits the default name and then goes back to choose a different Compatible CS, I'd recommend leaving the user-entered name as is.

**Comment by yuri1969** [comment]
OK, @scottyaslan and @moranr. I'll try to push an update tomorrow.

**Comment by yuri1969** [comment]
A misclick, sorry.

**Comment by scottyaslan** [comment]
Thanks @yuri1969 this has been merged to master.

**Pull request closed without merging**
