### PR TITLE
NIFI-13399 Implemented a different function that allows for Unicode

### PR DESCRIPTION
**Pull request by sashsuji**
NIFI-13399 Implemented a different function that allows for Unicode characters in the encoding of strings to base64

# Summary

[NIFI-13399](https://issues.apache.org/jira/browse/NIFI-13399)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X] Pull Request based on current revision of the `main` branch
- [X] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — COMMENTED** [review]
@sashsuji Have you tested this approach with non-ASCII characters authenticating to Registry? The Registry BasicAuth implementation is capable of decoding Base64 bytes into UTF-8, but this approach appears to encode the username and password using URI encoding before passing the bytes to the `btoa()` function.

**Comment by nightgryphon** [comment]
@exceptionfactory the URI encoding is the intermediate step and escaped characters are than converted back to 'char' with regexp replace(). I didn't test this patch at the moment but looks like it should work.

**Comment by sashsuji** [comment]
Full transparency, I've been trying to test this but I can't figure out how to get to the login page. I've only been able to run the registry site. How can I properly test this?

**Comment by exceptionfactory** [comment]
@sashsuji Thanks for following up, and thanks for the comment @nightgryphon. This type of change to character encoding could have a serious impact if not implemented properly. It is very important to test changes as part of the pull request process. Reviewers are also responsible for evaluating and testing, but it is important for authors to do the initial work.

The [NiFi Registry Admin Guide](https://nifi.apache.org/docs/nifi-registry-docs/html/administration-guide.html#user_authentication) provides details on configuring security integrated with LDAP as one option. Unfortunately, NiFi Registry does not support the single-user style of authentication that NiFi provides, so I understand it requires more work to setup a test scenario.

With that background, I am closing this pull request for now, but feel free to reopen after running some tests with different types of inputs.

**Review by mohamedmeqlad99 — COMMENTED** [review]
You replaced the plain btoa with utils.b64UnicodeEncode, which provides support for encoding Unicode characters (e.g., if a username or password contains special characters).
This change is beneficial in scenarios where credentials might include non-ASCII characters, as btoa alone would fail in those cases.

**Pull request closed without merging**
