### PR TITLE
NIFI-2662 - Fix style violations previously missed

### PR DESCRIPTION
**Pull request by trixpan**
Fix styles missed during PR940

### CODE REVIEW

**Comment by trixpan** [comment]
@mattyb149

**Comment by JPercivall** [comment]
@trixpan please don't merge this in. I want to make sure all the changes in PR 933 are accounted for first and if they are the check style issues should go away.

**Comment by trixpan** [comment]
@JPercivall - no worries at all.

Please note PR940 is already live so we may be worth checking that as well

**Comment by mcgilman** [comment]
@trixpan @JPercivall I've opened a new PR-943 that is rebased against current master. The commits that were lost did address the contrib check issues along with some other features/bugs. Since we needed to account for the other changes that were lost, can we close out this PR and related JIRA in favor of the PR-943. I've already reopened NIFI-2635.

Thanks!

**Comment by trixpan** [comment]
closed as per @mcgilman request

**Pull request closed without merging**
