### PR TITLE
NIFI-6072: Add sub project to package nifi-minifi-jni required NARs a…

### PR DESCRIPTION
**Pull request by phrocker**
…nd JARS for basic usage

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by phrocker** [comment]
@jdye64 and @apiri  -- feel free to take a look
For other reviewers, here is the corresponding funcitonality
https://github.com/apache/nifi-minifi-cpp/pull/489

**Comment by apiri** [comment]
@phrocker is the main rationale to avoid needing this build and the associated tooling in cpp land?  I see this is currently in a profile and I think that is okay for the common case, but do you think this would be a standard inclusion in our release process for NiFi such that the generated artifacts are readily available?

**Comment by phrocker** [comment]
> @phrocker is the main rationale to avoid needing this build and the associated tooling in cpp land? I see this is currently in a profile and I think that is okay for the common case, but do you think this would be a standard inclusion in our release process for NiFi such that the generated artifacts are readily available?

@apiri The primary rationale is actually that we will eventually be able to create regression tests in this or a related package to avoid making releases that could potentially break this linkage. Secondarily, the hope is that this feature appears more official by being a release artifact of Apache NiFi proper ( this feeds back into the first point ). 

The target could certainly live in C++, referencing the remote parent, without any issue whatsoever, but these two primary points were what I wanted to discuss. 

I would anticipate this breaking often without ownership in NiFi, and I know some profiles exist for various entities, so precedent seemed to exist in that aspect. Certainly open to discussion where we put this. My preference due to the risk to MiNiFi C++, and perceived less risk to NiFi is that if we don't put this here we don't put this in MINiFi C++ and instead provide it as documentation only.

**Comment by apiri** [comment]
I think I’m good with it if there are no strong objections.  Certainly makes sense to avoid some of the headaches that can happen with maintenance and disjoint release cycles.  Incorporation with an optional profile sounds good and is something we should incorporate in CI

**Comment by phrocker** [comment]
After much deliberation I have decided to put this into the MiNiFi C++ project

**Comment by apiri** [comment]
functionality was merged in apache/nifi-minifi-cpp#498

**Pull request closed without merging**
