### PR TITLE
NIFI-1738 - Repair logger names for ControllerStatusReportingTask

### PR DESCRIPTION
**Pull request by Hejki**

### CODE REVIEW

**Comment by jvwing** [comment]
@Hejki, this looks like a solid fix to me.  One thing I suggest you add is some unit tests, which I missed when I "fixed" this a couple months ago.  If that sounds like overkill for such a simple change, well... I use to agree :).

I made some [sample tests to verify your fix](https://github.com/jvwing/nifi/commit/004ca21e50dd4f4c98923dbb9a49528ad8544179), you are welcome to use them.

**Comment by olegz** [comment]
@Hejki please let us know if you are good with the tests from @jvwing , then we can amend your commit with @jvwing changes and merge.

**Comment by Hejki** [comment]
I'm ok with @jvwing tests, thanks.

**Comment by olegz** [comment]
Perfect, working on it now

**Pull request closed without merging**
