### PR TITLE
NIFI-10262: Ensure that when an Exception is thrown from a Controller…

### PR DESCRIPTION
**Pull request by markap14**
… Service's @OnEnabled method that we properly handle that Exception and continue enabling the other services in the given collection of services

# Summary

[NIFI-00000](https://issues.apache.org/jira/browse/NIFI-00000)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 8
  - [ ] JDK 11
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by exceptionfactory** [comment]
The automated build failures seem specific to the GitHub runner. Will rebase on current main branch to see that resolves the issues.

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Although a local build appears to work, it looks like rebasing did not improve the automated output. Unfortunately there seems to be something strange with the source files, which should be resolved before merging.

**Comment by exceptionfactory** [comment]
@markap14 after taking a closer look, apparently the rebase resulted in code changes resulting from the merge of NIFI-10246 in PR #6219. Although the merge did not produce any Git conflicts, it resulted in making `StandardControllerServiceProvider` invalid. I restored the `else` block added in NIFI-10246 to the `disableControllerServices()` method and force-pushed changes to the branch.

That change should allow the build process to move forward, but I will avoid making any additional changes and let you confirm that the current state of this branch reflects the original changes intended.

**Comment by markap14** [comment]
Ah, wow. Good catch. All looks good to me. Thanks @exceptionfactory !

**Review by exceptionfactory — APPROVED** [review]
Thanks for confirming that the current rebased version looks good @markap14! +1 merging

**Pull request closed without merging**
