### PR TITLE
NIFI-7842 Return Lists when multiple records are returned to the restlookupservice

### PR DESCRIPTION
**Pull request by pcgrenier**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here: Noticed when trying to query a rest service for a list of items, only the first record was attached in place and the other records were ignored. This pull request will return the same single record if only a single record is found or a list if multiple are returned. This does change the restlookupservice from implementing the recordlookupservice to a lookupservice<Object>. This works well with the LookupRecord processor since it will fall back on inferring the type in the chance it is not a record.

#### Description of PR

fixes bug NIFI-7842 

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [x] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by czobrisky** [comment]
+1 Looks good to me.
Commits need to be squashed. Is there concern about backwards compatibility? I'd say the previous implementation was a bug due to how it could handle an array response but would just pop the result, but this may break some people using the current functionality since it is a change to that.

**Review by czobrisky — APPROVED** [review]

**Review by czobrisky — APPROVED** [review]

**Comment by markap14** [comment]
I don't think we can accept this change into the codebase. It has the potential to break a lot of things. Any component that previously declared a property to reference a RecordLookupService would no longer be able to use this service, and that component would become invalid. And any component that declared a property as a LookupService that previously worked as expected could start to behave very differently. Consider that a REST service previously had a response that had 3 records, and it just returned the first one. Now it returns 3. That can result in all kinds of problems in the users' data.

However, I can understand the desire to support returning multiple Records. So we could either have a separate implementation (with shared, common code), or we could add a property that determines what to do if multiple records are returned (defaulting to return the first record in order to maintain backward compatibility). Adding the property comes with 2 downsides, though. (1) It means that the Controller Service still would no longer be a RecordLookupService but just a `LookupService<List<Record>>`. This is probably ok, though. I don't think we even have anywhere in the codebase where we expect a RecordLookupService explicitly to be configured. (2) The default really should be to return multiple records, not to return the first and ignore the rest. But defaulting to that would change the default behavior in a very unexpected way for some users.

**Comment by pcgrenier** [comment]
Yeah, I thought about the default current behavior. It just seems "wrong" or not intuitive to return the first element in the array. The only processor that I found that used this service was LookupRecord and it fully handles the change in response and puts it more inline with the other lookup services. I do agree a simple boolean to keep the current default behavior would be a good in-between solution

**Comment by pcgrenier** [comment]
Or as you said, shared code and create a RestObjectLookupService

**Pull request closed without merging**
