### PR TITLE
NIFI-1192 added support for Dynamic Properties in Get/PutKafka

### PR DESCRIPTION
**Pull request by olegz**

### CODE REVIEW

**Comment by trkurc** [comment]
Should the descriptions of the fields like "ZooKeeper Communications Timeout" include the property name (zk.connectiontimeout.ms) to make it obvious that they'll be clobbered if set as a dynamic property?

**Comment by trkurc** [comment]
I believe that this description: "These properties will be set on the Kafka configuration after loading any provided configuration properties"

I think it is a bit ... left open for interpretation. (and maybe not grave enough?) should it state something to the extent of "these properties will *override* any previously set Kafka configuration properties". I couldn't come up with a wording I liked a lot because you could form a description using the work 'properties' which means several different things.

**Comment by olegz** [comment]
@trkurc @joewitt @markap14 
Guys, please see the updated commit. This one has a bit more work as it includes some polishing since we discovered few more issues, one being that there was an non-existing property etc. See commit message for more details.

Tony, in relation to your last message, they will not override any previously set property since NiFi will not allow it. Basically one of the biggest changes that went in with this commit is setting _name_ and _displayName_. So when one attempts to set the property (e.g., 'client.id') as dynamic property, the NiFi will pop up with the message 'A property with this name already exists.’. So I think we're good, but let me know if you still see an issue.

**Comment by trkurc** [comment]
reviewing now

**Comment by olegz** [comment]
After discussing it with @joewitt pulling it back as it breaks backward compatibility

**Pull request closed without merging**
