### PR TITLE
NIFI-5648: Enable to launch NiFi and ignore the failed extensions.

### PR DESCRIPTION
**Pull request by kemixkoo**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by joewitt** [comment]
@kemixkoo I can understand where the desire for this comes from but I think this is a dangerous approach.  Fundamentally we're saying that we know at startup time there is a classpath issue.  Continuing to startup as if it appears ok despite knowing that and without a more holistic approach leads to a poor user experience.  Instead of this change I think we should focus on adding an extension registry api to the Flow Registry project.  There we can have nars live and NiFi instances can source them at runtime.  Issues with those nars are then well managed/clear and don't affect a live instance.  It also means instances dont require restart to source new versions/etc..

**Comment by kemixkoo** [comment]
Yes, I see. If can to manage the extensions dynamically, should be better, but need more refactor, so I just do a simple fix to load instance well.

**Comment by bbende** [comment]
I agree with the points made by @joewitt , although this PR did make me compare what we are doing for processors vs. controller services...
 
I noticed that for processors the try/catch wraps the Class.forName AND the newInstance() call, and then creates a ghost component an exception is thrown, where as controller services only catch exceptions from Class.forName and anything outside of that would not create a ghost component.

Technically exceptions from Class.forName would be the ones that indicate the class for the component is not present, and exceptions from newInstance() would indicate an exception thrown from the constructor.

So I'm not sure which is more correct, or if anything should be changed, but I did notice the difference in behavior, and some of the changes in this PR seem to be for making the controller service behavior more similar to processors.

**Comment by joewitt** [comment]
closing due to inactivity

**Pull request closed without merging**
