### PR TITLE
NIFI-4444: Ensuring the /nifi-api/controller redirection filter runs

### PR DESCRIPTION
**Pull request by mcgilman**
NIFI-4444:
- Ensure the /nifi-api/controller redirection filter executes before matching.

### CODE REVIEW

**Comment by alopresto** [comment]
Reviewing...

**Comment by alopresto** [comment]
Tested by visiting http://localhost:8080/nifi-api/controller without the patch applied -- error "The specified resource could not be found". With the patch applied -- returns expected JSON:

`{"controller":{"id":"b76231af-0160-1000-11f3-3e937575391f","runningCount":0,"stoppedCount":0,"invalidCount":0,"disabledCount":0,"inputPortCount":0,"outputPortCount":0,"siteToSiteSecure":false,"instanceId":"b76231b1-0160-1000-9062-ebe2c82af742","inputPorts":[],"outputPorts":[]}}`

Ran `contrib-check` and all tests pass. +1, merging.

**Comment by alopresto** [comment]
@mcgilman there was a space in the magic incantation to close this PR. Please close it at your convenience. The merge commit is [10755e2](https://github.com/apache/nifi/commit/b7c9c88f9f786f9a84b0c1dc34026194010755e2).

**Comment by mcgilman** [comment]
Thanks @alopresto! Closing...

**Pull request closed without merging**
