### PR TITLE
NIFI-9607: Honor Update Keys when Quoting Identifiers in PutDatabaseRecord

### PR DESCRIPTION
**Pull request by mattyb149**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

Update Keys weren't being used when Quoted Identifiers were set. Refactored and added unit test.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [x] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by mi-volodin** [comment]
@mattyb149 Hi, we have hit the same problem recently and were also going to think about PR, so many thanks for your work.

I would like to clarify one thing if you mind and maybe suggest some additional fixes.
We had the problem with `generateUpdate` function. 
And... I am not sure it is addressed here.

According to the code ( [@@ 1135](https://github.com/apache/nifi/pull/5701/files#diff-2a3826165c1a121489bf9a7d8e2536f3781138b24090ed1f5fb9771cd8c7a3c9R1135) in your version) there's a step when all keys are being normalized by `normalizeKeyColumnNamesAndCheckForValues` which also performs quotation if it is set by parameters.

However, on  [@@ 1170](https://github.com/apache/nifi/pull/5701/files#diff-2a3826165c1a121489bf9a7d8e2536f3781138b24090ed1f5fb9771cd8c7a3c9R1170) we have

```java
                // Check if this column is an Update Key. If so, skip it for now. We will come
                // back to it after we finish the SET clause
                if (!normalizedKeyColumnNames.contains(normalizedColName)) {
```

I.e. `normalizedKeyColumnNames` contains quoted identifiers, while `normalizedColName` is obtained by `normalizeColumnName` [here](https://github.com/mattyb149/nifi/blob/3f7cced8090df6f866eb667b1efb83577e399290/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/PutDatabaseRecord.java#L1367), which does no quotation.

Thus, during this step Key columns will still be included into `SET` block of  `UPDATE` statement, which is syntactically wrong.

What do you think?

**Comment by thenatog** [comment]
Will review

**Comment by thenatog** [comment]
I tested out these changes and they look good to me. I wasn't sure if we want to include the changes mi-volodin suggested as well.

**Comment by mattyb149** [comment]
@mi-volodin I didn't see the same behavior you describe, but did find a bug. I debugged the unit test and `normalizeKeyColumnNamesAndCheckForValues` doesn't quote the column names, just normalizes it by uppercasing it and removing underscores and such. Also the normalized column name it matches against isn't quoted, it should only be quoted when generating the SQL. However it was using `normalizedColumnName` as the column name in the `WHERE` clause when it should be using `desc.getColumnName()` like the `SET` clause does. That can cause issues, I will issue another commit to update the unit test to illustrate this, along with the fix to get the test to pass :)

**Comment by thenatog** [comment]
+1 will merge. If we can get more information/a specific case where the issue mentioned by mi-volodin we can create another Jira to resolve it.

**Pull request closed without merging**
