### PR TITLE
NIFI-1460 Test Performance improvement. test Timeout Mitigation. less IO, less depen…

### PR DESCRIPTION
**Pull request by PuspenduBanerjee**
Performance improvement. test Timeout Mitigation. less IO, less dependency on /dev/(u)random.
Stats are as follows for my linux desktop for org.apache.nifi.controller.TestStandardFlowFileQueue
:

- Without RNGD, no mouse move or key-press -- Timeout Exception
- With RNGD -- 26.5 Seconds
- With this PR, Without RNGD, no mouse move or key-press -- 19.6 Seconds

### CODE REVIEW

**Comment by PuspenduBanerjee** [comment]
@joewitt Another chance of improving test performance & less IO  by replacing  `UUID.randomUUID()` with` AtomicLong#incrementAndGet()`, which is sufficient for our test cases at org.apache.nifi.controller#TestStandardFlowFileQueue.

UUID.randomUUID() affects linux/unix systems heavily with Blocking IO from /dev/(u)random, entropy starvation etc., so let's not use that unless necessary.

**Comment by olegz** [comment]
@PuspenduBanerjee could you please raise JIRAs before submitting PRs. This is kind of the process that these projects follow and its easier for planning as well as compelling release notes during the actual release. Also it helps traceability since (as you have seen) the convention that everyone follows is to include JIRA number in the commit message. It allows us to trace any discussions straight down to the code.

**Comment by PuspenduBanerjee** [comment]
@oleg Sure. Raising one now.

**Comment by trkurc** [comment]
Reviewing now. Anything that makes tests faster makes me happy!

**Comment by PuspenduBanerjee** [comment]
Raised issue :  https://issues.apache.org/jira/browse/NIFI-1460

**Comment by PuspenduBanerjee** [comment]
@trkurc  Thanks for reviewing. let me know in case can be merged or if I need to create a patch.

**Comment by trkurc** [comment]
I did a quick experiment (code below), generated a 10^20 "UUID"'s using a few mechanisms

1. as you did in this pr (~120ms)
2. an slightly different version of what is in the PR  (~55ms)
3. using UUID with the atomic long as the low order bits (~800ms)
4. what was there originally (~3400ms)
5. Using JUG [1] to generate a time-based UUID (~800ms)

So, I think it is a net win with changing the method you created to return a String rather than a Long (based on 1 vs 2). On the long as a string vs UUID as a string, although it is faster by a factor of  6, I do think returning a UUID as a string may better fit the contract of the UUID core attribute. Although pretty much everywhere it is stored, it is done so as a String, the comments clearly say UUID [2]. I'm not sure the technical debt accrued for a Long vs UUID performance increase is a good trade in this instance. 

Side note - the JUG github page is an interesting read. There are some good benchmarks talking about how awesome it is.

[1] https://github.com/cowtowncoder/java-uuid-generator
[2] https://github.com/apache/nifi/blob/master/nifi-commons/nifi-utils/src/main/java/org/apache/nifi/flowfile/attributes/CoreAttributes.java#L34
```java
    public static void main(String args[]){
        long iter = 1<<20;
        AtomicLong ai = new AtomicLong(0);
        long now = System.currentTimeMillis();
        for(int i=0; i < iter; i++) {
            Long x = ai.getAndIncrement();
            String x2 = x.toString();
        }
        System.out.printf("%d elapsed\n", (System.currentTimeMillis() - now ));

        now = System.currentTimeMillis();
        for(int i=0; i < iter; i++) {
            
            String x2 = Long.toString(ai.getAndIncrement());
        }
        System.out.printf("%d elapsed\n", (System.currentTimeMillis() - now ));

        now = System.currentTimeMillis();
        for(int i=0; i < iter; i++) {
            UUID u = new UUID(0, ai.getAndIncrement());
            String x2 = u.toString();
        }
        System.out.printf("%d elapsed\n", (System.currentTimeMillis() - now ));
        
        now = System.currentTimeMillis();
        for(int i=0; i < iter; i++) {
            UUID u = UUID.randomUUID();
            String x2 = u.toString();
        }
        System.out.printf("%d elapsed\n", (System.currentTimeMillis() - now ));
    
        now = System.currentTimeMillis();
        TimeBasedGenerator g = Generators.timeBasedGenerator();
        for(int i=0; i < iter; i++) {
            UUID u = g.generate();
            String x2 = u.toString();
        }
        System.out.printf("%d elapsed\n", (System.currentTimeMillis() - now ));
    }
```

**Comment by PuspenduBanerjee** [comment]
@trkurc :+1:  That's a good catch. Yes Long.toString(long) is faster but the difference is only about ~60 milliSeconds for 10^20 iteration because:
```java
    /**
     * Returns a {@code String} object representing this
     * {@code Long}'s value.  The value is converted to signed
     * decimal representation and returned as a string, exactly as if
     * the {@code long} value were given as an argument to the
     * {@link java.lang.Long#toString(long)} method.
     *
     * @return  a string representation of the value of this object in
     *          base&nbsp;10.
     */
    public String toString() {
        return toString(value);
    }
```
But, do you think that should be accounted against the manageability of the method in context of the provided test scenario?
And, please try the following code, try to run it &  you will  something noticeable:
```java
    public static void main(String args[]){
        for (int i = 0; i < 100; i++) {
            main1();
        }
    }
    
    public static void main1(){
        long iter = 1<<20;
        AtomicLong ai = new AtomicLong(0);
        long now = System.currentTimeMillis();
        for(int i=0; i < iter; i++) {
            Long x = ai.getAndIncrement();
            String x2 = x.toString();
        }
        System.out.printf("1 ===== %d elapsed\n", (System.currentTimeMillis() - now ));

        now = System.currentTimeMillis();
        for(int i=0; i < iter; i++) {

            String x2 = Long.toString(ai.getAndIncrement());
        }
        System.out.printf("2 ===== %d elapsed\n", (System.currentTimeMillis() - now ));

       
        System.out.println("=============================DONE========================");
    }
```

**Comment by trkurc** [comment]
> But, do you think that should be accounted against the manageability of the method in context of the provided test scenario?

I'm not sure I'm following. To give you an idea of my thought process with 2, "if we're going for maximum speed, changing the method signature, and avoiding some boxing would be ideal". 

However, it was the latter part of my claim about 3 being "performant enough" and not dependent on a RNG, and still a "UUID" which I thought more thought provoking - fast enough, potentially less tech debt, everyone wins?

**Comment by PuspenduBanerjee** [comment]
@trkurc  I think, if UUID format is of concern the following piece will run more than 2 times faster compared to `UUID(0,long)`, could you please re-verify:
```java
private static String createFakeUUIDString(final AtomicLong atomicLong){
         final String s=Long.toHexString(atomicLong.incrementAndGet());
        return new StringBuffer("00000000-0000-0000-0000000000000000"
                                      .substring(0,(35-s.length()))+s)
                                       .insert(23, '-').toString();
    }
```
I hope, everyone wins that way too along with more performance benefit.

**Comment by trkurc** [comment]
I am not able to verify right now (no compiler at hand), but I like this approach. Do you plan to update the PR?

**Comment by PuspenduBanerjee** [comment]
@trkurc Yes , updated ..

**Comment by PuspenduBanerjee** [comment]
Probably a basic question, but am I missing any process to request a PR to merge?

**Comment by trkurc** [comment]
@PuspenduBanerjee - not missing anything, I should be able to merge in your patch tonight

**Comment by taftster** [comment]
1) StringBuilder should probably be preferred to StringBuffer in this case.  Though it probably won't matter for performance, the intention is that this is the unsychronized (thread safe) usage.

2)  I'm opting for readability over speed.  What's wrong with something like:

```
private static String createFakeUUID() {
    return new StringBuilder()
        .append("00000000-0000-0000-")
        .append(String.format("%016x", id)
        .insert(23, '-')
        .toString();
}
```

**Comment by trkurc** [comment]
@taftster  - code readability is subjective, I prefer actually prefer what is in the PR. The String.format makes it an order of magnitude slower based on my initial tests. I see no appreciable difference between StringBuffer and StringBuilder

The results of the below code:
``
1 ===== 304 elapsed
2 ===== 1717 elapsed
3 ===== 248 elapsed
```
The StringBuffer is faster, but it is likely due to some of the JVM string magic.

```java
        int iter = 1<<20;
        AtomicLong ai = new AtomicLong(0);

        long now = System.currentTimeMillis();

        for(int i=0; i < iter; i++) {
            final String s=Long.toHexString(ai.getAndIncrement());
            String x2 = new StringBuilder("00000000-0000-0000-0000000000000000".substring(0,(35-s.length()))+s).insert(23, '-').toString();
            
        }
        System.out.printf("1 ===== %d elapsed\n", (System.currentTimeMillis() - now ));
        
        now = System.currentTimeMillis();

        for(int i=0; i < iter; i++) {
            String x2 =        new StringBuilder()
            .append("00000000-0000-0000-")
            .append(String.format("%016x", ai.getAndIncrement()))
             .insert(23, '-')
            .toString();     
        }
        System.out.printf("2 ===== %d elapsed\n", (System.currentTimeMillis() - now ));
        
        
        now = System.currentTimeMillis();

        for(int i=0; i < iter; i++) {
            final String s=Long.toHexString(ai.getAndIncrement());

            String x2 = new StringBuffer("00000000-0000-0000-0000000000000000".substring(0,(35-s.length()))+s).insert(23, '-').toString();

        }
        System.out.printf("3 ===== %d elapsed\n", (System.currentTimeMillis() - now ));
```

**Pull request closed without merging**
