### PR TITLE
NIFI-13970 added disclaimer to source and key assemblies

### PR DESCRIPTION
**Pull request by joewitt**
# Summary

[NIFI-13970](https://issues.apache.org/jira/browse/NIFI-13970)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by joewitt** [comment]
🤦 Doh!   on it.     Why didn't someone else less thorough review this.....

**Comment by joewitt** [comment]
Rebased to latest support/nifi-1.x and added registry assembly and force pushed.

**Comment by szaszm** [comment]
Minor nitpick, but the last line is missing a line ending in the DISCLAIMER files.

In the Unix/-like world, a line in a text file is ending by a line ending `\n` by definition. On Windows, `\r\n` is more like a line separator, so adding it after the last line is not needed. I prefer the Unix way. Normally text editors on Linux (and I think macOS too) add this automatically, but some IDEs follow the Windows convention, except using a Unix `\n` line ending character as their line separator when on Linux/macOS.

**Comment by joewitt** [comment]
i added a commit to ensure each disclaimer ends with a newline.

**Review by exceptionfactory — APPROVED** [review]
Thanks again for putting this together @joewitt, these disclaimers should provide helpful clarity regarding the status of the NiFi 1 version series. +1 merging

**Comment by exceptionfactory** [comment]
Merged to support 1.x branch in https://github.com/apache/nifi/commit/ca10d7abc00060453bdb0451f6b7fe3f5503c058

Merged to support 1.28 branch in https://github.com/apache/nifi/commit/26e4598abb64d79f3c927c3fc8949c62f024c05e

**Pull request closed without merging**
