### PR TITLE
NIFI-1336 - Ensure that flowfiles are penalized upon exception due to…

### PR DESCRIPTION
**Pull request by trixpan**
… inability to delete hold

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [] Have you written or updated unit tests to verify your changes?
- [X] ~~~If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?~~~
- [X] ~~~If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?~~~
- [X] ~~~If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?~~~
- [X] ~~~If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?~~~

### For documentation related changes:
- [X] ~~~Have you ensured that format looks appropriate for the output in which it is rendered?~~~

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by trixpan** [comment]
@markap14 hope this PR addresses the issue you reported. Could you confirm and merge/provide feedback?

Cheers!

**Comment by markap14** [comment]
@trixpan sorry - the email that github sent me got lost in my inbox. Just saw it. I think the logic here is still not quite right, though. And I think I may have actually misunderstood what was happening initially, as well. If unable to delete the 'hold' that the other side places on the FlowFile, PostHTTP enters a loop of continually attempting to delete the hold, until it gets a response back. If an IOException occurs, with the logic you added in, it will route to failure and then the next iteration of the loop will try to transfer the FlowFile again. I think the best approach would be to limit the loop to happen some number of times (e.g., 3 or 5 or 10 times) and if unable to communicate with the remote instance for that number of times, at that point we should route to failure and return. We used a loop here, I think, because we don't want to send say 1 GB of data and then have a garbage collection or a network hiccup or whatever prevent the delete and have to re-transmit all that data. So a few retries is likely a good idea. We should probably also not be logging the errors/stack traces until we finish retrying though.

**Comment by trixpan** [comment]
@markap14 no worries. Thanks for the clarification I will try to give it another go.

**Comment by joewitt** [comment]
Closing due to inactivity.

**Pull request closed without merging**
