### PR TITLE
NIFI-4196 - Expose AWS proxy authentication settings

### PR DESCRIPTION
**Pull request by trixpan**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [X] Have you written or updated unit tests to verify your changes?
- [X] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [X] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [X] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [X] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [X] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by trixpan** [comment]
Please note the displayName settings were not added as most of the AWS related processors lack these

**Comment by pvillard31** [comment]
Hey @trixpan, regarding ``.displayName`` and ``.name``, I tend to think that we should use both for new properties in a processor, even though it is not the case for legacy properties.

Besides, some tests are now failing:
````
Failed tests: 
  TestDeleteS3Object.testGetPropertyDescriptors:144 size should be eq expected:<20> but was:<22>
  TestFetchS3Object.testGetPropertyDescriptors:181 size should be eq expected:<14> but was:<16>
  TestListS3.testGetPropertyDescriptors:197 size should be eq expected:<15> but was:<17>
  TestPutS3Object.testGetPropertyDescriptors:153 size should be eq expected:<28> but was:<30>
````

**Comment by trixpan** [comment]
hopefully fixed

**Comment by pvillard31** [comment]
Thanks @trixpan, what about my comment on ``displayName``? I know this is kind of cosmetic but when using proper ``name``, it makes things easier when moving templates from one environment to another and that values should be changed in the process.

**Comment by trixpan** [comment]
@pvillard31 will rebase and resubmit...

**Comment by ottobackwards** [comment]
How can these be tested?

**Comment by ottobackwards** [comment]
in https://github.com/apache/nifi/pull/2588 I have done this as well, but only in my processor ( scope ).  I would like to see this land.  What can be done to move this forward?

**Comment by ottobackwards** [comment]
@trixpan can you de-conflict?

**Comment by ijokarumawak** [comment]
@trixpan Similar to #2018, I took the liberty of taking over this PR into #2704. By cherry-picking your commits into my branch, so that we can respect your work and, when mine is merged, this PR will be closed properly.

I've rebased with the latest master, check unit tests and expand the proxy supports to other AWS processors, such as DynamoDB, Kinesis and Lambda there.

@trixpan @ottobackwards @pvillard31 Please keep reviewing these stuffs at #2704. It's ready for finalizing review process. Thanks!

**Pull request closed without merging**
