### PR TITLE
NIFI-7229 - Upgrade jackson-databind direct dependencies

### PR DESCRIPTION
**Pull request by pvillard31**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Enables X functionality; fixes bug NIFI-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [x] Have you verified that the full build is successful on both JDK 8 and JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by adenes** [comment]
LGTM 👍 

Sidenote: the following modules directly refer the `jackson-databind` library with explicit version instead of using the `jackson-databind.version` variable:
- `nifi-elasticsearch-client-service-api` (2.9.8)
- `nifi-graph-processor` (2.9.9)
- `nifi-easyrules-service` (2.9.10)

I don't know if these are intentional or need to be updated as well.

**Comment by pvillard31** [comment]
Thanks @adenes for the feedback, I updated the PR to reference the property instead of hard-coded versions in the modules you listed.

**Comment by pvillard31** [comment]
I actually reverted the change for the bundles you mentioned as I'm not sure about the impact it could have. I filed a specific JIRA for this:
https://issues.apache.org/jira/browse/NIFI-7253

**Comment by mcgilman** [comment]
Also reviewing...

**Comment by mcgilman** [comment]
There appears to be a number of transitive dependencies on `jackson-databind`.

> work/nar/extensions/nifi-jolt-record-nar-1.12.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/jackson-databind-2.9.4.jar
work/nar/extensions/nifi-hadoop-libraries-nar-1.12.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/jackson-databind-2.9.8.jar
work/nar/extensions/nifi-elasticsearch-client-service-api-nar-1.12.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/jackson-databind-2.9.8.jar
work/nar/extensions/nifi-datadog-nar-1.12.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/jackson-databind-2.4.2.jar
work/nar/extensions/nifi-proxy-configuration-nar-1.12.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/jackson-databind-2.9.4.jar
work/nar/extensions/nifi-enrich-nar-1.12.0-SNAPSHOT.nar-unpacked/NAR-INF/bundled-dependencies/jackson-databind-2.9.5.jar

I went through each and while some offer a newer version of our dependency in question, only the `enrich-nar` could offer a newer version of `jackson-databind`. I will create a follow on JIRA to address this instance.

**Comment by mcgilman** [comment]
JIRA created: https://issues.apache.org/jira/browse/NIFI-7254

**Comment by mcgilman** [comment]
Thanks @pvillard31 and @adenes! This has been merged to master.

**Pull request closed without merging**
