### PR TITLE
NIFI-5950: Use temp port names during flow updates

### PR DESCRIPTION
**Pull request by kevdoran**
Use temporary values for port names when updated process groups as part of a Change Flow Version operation. This avoids the potential for a name conflict between a ports during the update process.

Add a final step to the update process group logic to set the final name on all ports.

---

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [x] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by kevdoran** [comment]
@markap14 If you get a change to review this, that would be much appreciated! I have verified the fix manually. The steps to reproduce the issue this addresses are on the Jira: https://issues.apache.org/jira/browse/NIFI-5950

**Comment by alopresto** [comment]
Reviewing...

**Comment by alopresto** [comment]
Ok so the code Kevin provided works, passes tests & checkstyle. I made some additional [refactoring changes](https://github.com/alopresto/nifi/commits/pr3301) available in a branch on my fork. I am a +1 for the PR as it is here if it needs to be merged immediately without my refactoring being reviewed, but I think I cleaned up the duplicated code and made it easier to follow (understanding that Kevin was just trying to get a fix for the issue in). If @kevdoran or @markap14 want to review that, I will handle the rebasing & merging tomorrow.

**Comment by kevdoran** [comment]
Thanks @alopresto. Unfortunately, I don't have any more additional time to spend on this issue until after the 1.9.0 release (as it was, it took up significantly more time than I anticipated and I have a backlog of other items folks are waiting on). 

When looking at the code to plan the fix, @markap14 and I did notice some things that could be refactored for code de-duplication and to break this class file up a little bit, so maybe that is a larger effort that could be addressed after 1.9.0, using your branch as a starting point.

**Pull request closed without merging**
