### PR TITLE
NIFI-13724 - Added additional metadata to events (#9239) on 1.x branch

### PR DESCRIPTION
**Pull request by Dye357**
# Summary

[NIFI-13724](https://issues.apache.org/jira/browse/NIFI-13724)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X ] Pull Request based on current revision of the `main` branch
- [X ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ X] Build completed using `mvn clean install -P contrib-check`
  - [ X] JDK 21

### Licensing

- [ n/a] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ n/a] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ X] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
@Dye357 The automated workflows failed to build on Java 8 due to the use of `Objects.requireNonNullElse()`, which is not available on that version of Java. This will need to replaced with an alternative approach in order to work on the support branch.

**Comment by Dye357** [comment]
@exceptionfactory -thanks for catching that - I updated the code to work with Java 8.

**Comment by bbende** [comment]
It looks like some tweaking will be needed to make this compatible with Java 8, the two failing builds show errors for this
```
2024-10-21T20:15:41.8320930Z [ERROR] /Users/runner/work/nifi/nifi/nifi-registry/nifi-registry-core/nifi-registry-framework/src/main/java/org/apache/nifi/registry/event/EventFactory.java:[97,110] error: cannot find symbol
2024-10-21T20:15:41.8321900Z [ERROR]   symbol:   method requireNonNullElse(String,String)
2024-10-21T20:15:41.8322250Z [ERROR]   location: class Objects
```
I assume that method was added in Java 11 since the 11 and 17 builds pass, but the 8 builds don't.

**Comment by bbende** [comment]
Woops sorry I missed the existing comments here, hadn't refreshed my page.

**Review by exceptionfactory — APPROVED** [review]
Thanks @Dye357, +1 merging

**Pull request merged**
