### PR TITLE
NIFI-1378 fixed JMS URI validation

### PR DESCRIPTION
**Pull request by olegz**
simplified JmsFactory check for SSL and scheme-less URIs
ensured URI validation is handled by ActiveMqConnectionFactory
ensured informative error messages are shown to the user

### CODE REVIEW

**Comment by trkurc** [comment]
reviewing now.

**Comment by trkurc** [comment]
@olegz  - to sort of summarize, I definitely understand the issue with the uri and only being able to fully verify "at runtime", it also makes sense to deal with obvious mistakes in the validator. In that sense, my expectation was better error handling, not wholesale removal. 

I had thought you were operating along these lines too, by leaving in the URI_VALIDATOR, but removing the unit tests for that were a surprise.

**Comment by olegz** [comment]
@trkurc I do see your point, so let me throw something else at you. The _URI_VALIDATOR_ simply validates based on success of this ```new URI(input);``` and we can certainly add the test back, but consider that that test was added by Joe to validate the previous fix that we all seem to agree was inefficient given what we know now. So instead I've added 3 more tests to test specific invalid conditions. 
That leaves us with one thing and that is testing that 'any validator' works in the processor and as I said before I think those tests already exists at the higher level.

**Comment by trkurc** [comment]
Not sure that I agree, but I do agree this is a step in the right direction, so I'll merge it in.

**Comment by olegz** [comment]
@trkurc I understand and thank you for merging it. That said, there are improvements efforts under way which hopefully would address all of our concerns.

**Pull request closed without merging**
