### PR TITLE
NIFI-13196: Added new isAutoTerminated(Relationship) method to Proces…

### PR DESCRIPTION
**Pull request by markap14**
…sContext, which simply delegates to Connectable.isAutoTerminated(Relationship)

# Summary

[NIFI-00000](https://issues.apache.org/jira/browse/NIFI-00000)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### UI Contributions

- [ ] NiFi is modernizing its UI. Any contributions that update the [current UI](https://github.com/apache/nifi/tree/main/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui) also need to be implemented in the [new UI](https://github.com/apache/nifi/tree/main/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi).  

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by joewitt** [comment]
@markap14 one has to wonder how on earth we did not have this mechanism long ago.  So if I'm writing a processor, such as a custom processor or otherwise, I can now ask "Hey if I make this potentially expensive output is it going to get thrown away anyway so I can just bypass doing so?"     Very nice!  

Once this lands makes sense to have follow-on JIRA(s) to take advantage of it.

**Comment by markap14** [comment]
@joewitt yes correct, I was sure that we had this method already, then I found that it exists on Connectable but was not surfaced in the ProcessContext. I am almost sure that we have processors that could take advantage of it already, and will do a scan through, creating any Jiras as necessary.

**Comment by markap14** [comment]
@joewitt just created a Jira for RouteText, for example. https://issues.apache.org/jira/browse/NIFI-13198
Will take some thinking through which processors can make use of this, but for several Route types processors, especially those with an 'unmatched' type of relationship it will make sense.

**Comment by joewitt** [comment]
Thanks.  This makes sense and I'm a +1.  Will merge tomorrow pending any further inputs.  The change is specific, well documented, and the two JIRAs filed are good examples of how it can be applied well.

**Pull request closed without merging**
