### PR TITLE
NIFI-6196 Upgrade version of Jetty

### PR DESCRIPTION
**Pull request by jtstorck**
This PR should be merged after https://github.com/apache/nifi/pull/3416 to avoid merge conflicts due to regenerated certs in nifi-standard-processor.

While reviewing code, it is important to verify that server certs are not reused as client certs.  This PR updates several tests that reused server certs, but more investigation is needed for other areas of code that reuse them.

To test this PR:
- Specific components that use Jetty:  ListenHTTP, HandleHttpRequest, InvokeHTTP, JettyWebSocketClient, JettyWebSocketServer, TlsCertificateAuthorityService

Each component should be tested in the following scenarios:
- Verify an unsecured standalone instance of NiFi
- Verify a secured anonymous standalone instance of NiFi
- Verify a secured standalone instance of NiFi
- Verify a secured cluster of NiFi

To test the TlsCertificateAuthorityService, certs for secured NiFi instances should be generated by a running NiFi CA service.

Please see https://issues.apache.org/jira/browse/NIFI-6196 for the list of issues encountered and their resolutions implemented in this PR.

#### **NOTE:** Please retain the flows used to verify this PR.  They can be reused for verifying functionality when NiFi supports builds on Java 11.
----

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [x] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by mcgilman** [comment]
Happy to review once out of Draft status.

**Comment by jtstorck** [comment]
@thenatog Could you review this PR, please?

**Comment by mcgilman** [comment]
@jtstorck I am a +1 on this PR. Ran through a number of different functional tests including standalone (secured both two way and one way SSL and unsecured). Also verified functionality with several of our processors that utilize embedded Jetty instances.

Once @thenatog signs off, please merge.

**Comment by thenatog** [comment]
I have verified the endpointIdentificationAlgorithm settings are at least checking for SANs using a clientSocket and serverSocket with certs that did and didn't contain SANs. For the moment, I recommend we set the clientSocket endpointIdenticationAlgorithm to null as well as this could be considered a breaking change that would require users to regenerate server certs for services external to NiFi. However, I think that it's generally accepted practice to expect SANs are set correctly for certificates. So, in future, we should flip this to require SAN validation in a major version change down the line.

Once you set the algorithm to null for the serverSocket, +1.

**Pull request closed without merging**
