### PR TITLE
NIFI-385 Add Kerberos Support to Kite

### PR DESCRIPTION
**Pull request by WilliamNouet**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

For all changes:

[Y] Is there a JIRA ticket associated with this PR? Is it referenced
in the commit message?

[Y] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

[Y] Has your PR been rebased against the latest commit within the target branch (typically master)?

[Y] Is your initial contribution a single, squashed commit?

For code changes:

[Y] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
[Y] Have you written or updated unit tests to verify your changes?
[N] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under ASF 2.0?
[N/A] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
[N/A] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
[N/A] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?
For documentation related changes:

[N/A] Have you ensured that format looks appropriate for the output in which it is rendered?
Note:

Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by WilliamNouet** [comment]
From @jtstorck:
FYI, some issues have been noticed with Hadoop and Kerberos in the NiFi HDFS processors. There's JIRA that I'm working on to fix a scenario where Kerberos principals end up getting switched between multiple processors. It's due to the UserGroupInformation class being shared by two instances of processors from the same NAR. The fix involves not depending on nifi-hadoop-libraries-nar, and including the hadoop-client dependency directly in the nifi-hdfs-processors pom.

Once the Kite processors support Kerberos, they'll most likely have the same issue, and a similar change will have to be made to the POMs.

For reference, the JIRA is: https://issues.apache.org/jira/browse/NIFI-3520

**Comment by WilliamNouet** [comment]
@pvillard31 @trixpan Any update on this PR?

**Comment by joewitt** [comment]
@williamnouet sorry for the delay on this.  the kite stuff is tough as it was contributed by someone who has not been active in a while and I dont think there are many folks familiar with it.  A lot of what it would be used to do we have very strong alternatives for so that should be considered as well.  

Anyone familiar with kite that could validate this work?

**Comment by WilliamNouet** [comment]
@joewitt what do you have in mind when saying "we have very strong alternatives for so that should be considered as well."?

This does not need to be validate by someone familiar with Kite as the PR only deals with Kerberos related changes and as such, keeps the native Kite code which was developed.

Also, closing this PR and opening #2029

**Pull request closed without merging**
