### PR TITLE
[NIFI-10252] Processor PutDatabaseRecord generating invalid UPDATE SQL

### PR DESCRIPTION
**Pull request by eduardofontes**
Not always UpdateKey comes at first position

# Summary

[NIFI-10252](https://issues.apache.org/jira/browse/NIFI-10252)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 8
  - [ ] JDK 11
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by mattyb149** [comment]
Can you add a unit test that validates the fix?

**Comment by eduardofontes** [comment]
@mattyb149 
I'll try to do something by next week. There is only one unit test for this processor (testInsertNonRequiredColumnsUnmatchedField), so there is a lot of work to do here.

**Comment by eduardofontes** [comment]
@mattyb149 
I hadn't seen the groovy test file. It has a lot of unit tests on PutDatabaseRecord.
I added a unit test for this issue, as you asked.

**Comment by mattyb149** [comment]
Reviewing...

**Pull request closed without merging**
