### PR TITLE
NIFI-1656 Added locale support to ConvertAvroSchema and fixed locale …

### PR DESCRIPTION
**Pull request by trkurc**
…problems in unit tests
See:
https://issues.apache.org/jira/browse/NIFI-1656

### CODE REVIEW

**Comment by trkurc** [comment]
@pvillard31 - can you try this one?

**Comment by pvillard31** [comment]
Everything OK, I'm a :+1:

**Comment by trkurc** [comment]
Thanks for following up, @pvillard31 . I think maybe building with other default locales may be worth exploring to add to travis-ci (tagging @apiri who may know if that's possible (I added -Duser.language=fr -Duser.region=FR to my env when testing))

**Comment by apiri** [comment]
Yeah, can certainly figure something out with the build matrix.

**Comment by apiri** [comment]
Created a ticket to handle this task:  https://issues.apache.org/jira/browse/NIFI-1657

**Pull request closed without merging**
