### PR TITLE
NIFI-10189 Added WriteText processor to the standard bundle.

### PR DESCRIPTION
**Pull request by MikeThomsen**
# Summary

[NIFI-00000](https://issues.apache.org/jira/browse/NIFI-00000)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 8
  - [ ] JDK 11
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by MikeThomsen** [comment]
Quick copy pasta from the Jira ticket to explain why I didn't update `ReplaceText`:

> We often encounter a scenario where after doing a number of operations, we need to just do the equivalent of a ReplaceText operation that evaluates the whole file and replaces it with a simple string literal such as a SQL query or JSON object. The reason I am proposing a new processor is to keep this dead simple and not complicate the validation logic of ReplaceText.

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for proposing the new Processor @MikeThomsen.

Although I can see some potential value, I'm not sure it is enough to warrant introducing a new standard component for this limited purpose. I would be interested in other opinions.

Should there be a desire to move forward, the unit test should be rewritten in standard Java to avoid introducing new Groovy-based unit tests. It seems unnecessary to perform the JSON parsing, so it could be simplified.

**Comment by MikeThomsen** [comment]
>  I'm not sure it is enough to warrant introducing a new standard component for this limited purpose

I've seen this use case from data engineers I work with all over the place in the last few years. The problem with ReplaceText is that it requires you to evaluate the flowfile content which can cause significant performance problems if the flowfile is large.

**Comment by exceptionfactory** [comment]
> I've seen this use case from data engineers I work with all over the place in the last few years. The problem with ReplaceText is that it requires you to evaluate the flowfile content which can cause significant performance problems if the flowfile is large.

Thanks for the reply, that is good point about ReplaceText. For that use case, however, would GenerateFlowFile work?

**Comment by MikeThomsen** [comment]
> would GenerateFlowFile

Theoretically, it would, but I think the name would be complete unintuitive. That alone could cause many people to just jump right into ReplaceText.

**Comment by pvillard31** [comment]
ReplaceText with "Always Replace" as the strategy won't evaluate the flowfile's content. We're also checking the specified regex to see if Always Replace should be applied by default. In that case, if the user does not change the replacement strategy we would skip the regex evaluation anyway.

https://github.com/apache/nifi/blob/main/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ReplaceText.java#L277-L281

**Comment by exceptionfactory** [comment]
As @pvillard31 noted, the `Always Replace` strategy seems to meet the use case described, and would seem to obviate the need for a new processor.

**Comment by joewitt** [comment]
So I agree with the spirit of what Mike is trying to solve.  Make it easier for users to find the right function with minimal additional complexity to do the thing.  Especially for simple stuff.

I agree with Pierre/David on what the solution is for this case.

So how can we meet in the middle?  Perhaps a tag or set of tags added to the processor would aid in finding the component faster.  Perhaps add a processor tag that is literally 'WriteText' or even 'Write Text' though I'm not sure what we do with spaces.  

That simple step might be just enough.

**Comment by ottobackwards** [comment]
Maybe some additionalDocumentation with a use case?

**Pull request closed without merging**
