### PR TITLE
NIFI-12999: Revert "Bump webpack-dev-middleware and karma-webpack (#8547)"

### PR DESCRIPTION
**Pull request by sardell**
Link to Jira: https://issues.apache.org/jira/browse/NIFI-12999

This PR reverts commit 69f1a3be4dd0ede7912ee8cfd67d39bdc3d6eca0 (PR #8547). This commit on `main` is currently causing local builds of NiFi to fail due to a dependency in nifi-registry's package-lock.json requiring a version of Node.js higher than the one we use to build nifi-registry. cc @scottyaslan 

revert-1

revert-2

# Summary

[NIFI-00000](https://issues.apache.org/jira/browse/NIFI-00000)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for flagging this issue @sardell.

As the previous PR has been merged for [NIFI-12935](https://issues.apache.org/jira/browse/NIFI-12935), this PR should have a new Jira issue for tracking.

To the substance of the issue, however, can you clarify how this is a problem for a local build as opposed to GitHub Actions build? I see that `package-lock.json` references Node 18, so it is unclear how this works in automated builds. It also works on recent local builds, so is the issue limited to running Registry unit tests? If it is possible to rescope the changes, as opposed to just reverting that would be ideal, but I understand it may be more complicated.

**Comment by sardell** [comment]
@exceptionfactory Thanks for taking a look. I created https://issues.apache.org/jira/browse/NIFI-12999 to track the issue.

> To the substance of the issue, however, can you clarify how this is a problem for a local build as opposed to GitHub Actions build?

That is a great question, and I'm not 100% sure. Maybe there is some global caching going on with those deps in GitHub Actions or some configuration that causes them to fail silently in that environment, but I'm not sure. I would have to investigate further.

>  It also works on recent local builds, so is the issue limited to running Registry unit tests? If it is possible to rescope the changes, as opposed to just reverting that would be ideal, but I understand it may be more complicated.

The issue happens to me whenever I try to build the project with maven (used `./mvnw clean install` initially and `mvn clean install` at the root level to see that error. I also cannot cd into nifi-registry's ui and manually install npm deps either. If others aren't running into this issue on `main`, I'll gladly close this and chalk it up to a local issue I need to investigate. I found this issue late last night and wanted to have a PR ready to discuss in the morning due to the potential impact a failing build on `main` would have.

**Comment by sardell** [comment]
@exceptionfactory I've confirmed with @koccs that he's able to reproduce the issue building the latest from `main` locally.

**Comment by scottyaslan** [comment]
> Node 18, so it is unclear how this works in automated builds. It also works on recent local builds, so is the issue limited to running Registry unit tests? If it is possible to rescope the changes, as opposed to just reverting that would be ideal, but I understand it may be more complicated.

@sardell Is it possible to update the version of node that this requires? Possibly in the pom.xml? Or maybe even update the registry's package.json such that we don't fail because of it? I know we don't want to support npm versions less than the minimum but I think newer versions of npm are fine right?

**Comment by scottyaslan** [comment]
@sardell Running `mvn clean install -DskipTests -PjsUnitTests` from /nifi/nifi-registry also builds successfully for me.

Can you please provide more details on your environment and how you are running this to see this failure?

**Comment by sardell** [comment]
I'm simply building the project from the root with `./mvnw clean install -T2C` (also tried without the parallel build). When I try to install npm dependencies by running `npm run ci` at `nifi/nifi-registry/nifi-registry-core/nifi-registry-web-ui/src/main` like the build does, I receive a dependency mismatch error.

```
nifi-registry-web-ui/src/main on  NIFI-11520-with-backend [$] via  v16.19.0
❯ npm run ci

> nifi-registry@0.0.5-SNAPSHOT ci
> npm ci --ignore-scripts

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @angular/http@4.4.7
npm ERR! Found: @angular/core@11.2.14
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"11.2.14" from the root project
npm ERR!   peer @angular/core@"11.2.14" from @angular/animations@11.2.14
npm ERR!   node_modules/@angular/animations
npm ERR!     @angular/animations@"11.2.14" from the root project
npm ERR!     peer @angular/animations@"^11.0.0 || ^12.0.0-0" from @angular/material@11.2.13
npm ERR!     node_modules/@angular/material
npm ERR!       @angular/material@"11.2.13" from the root project
npm ERR!       2 more (@covalent/core, @nifi-fds/core)
npm ERR!     2 more (@angular/platform-browser, @nifi-fds/core)
npm ERR!   10 more (@angular/cdk, @angular/common, @angular/flex-layout, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"4.4.7" from @angular/http@4.4.7
npm ERR! node_modules/@angular/http
npm ERR!   peer @angular/http@"^2.0.0||^4.0.0" from angular2-jwt@0.2.3
npm ERR!   node_modules/angular2-jwt
npm ERR!     angular2-jwt@"0.2.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/core@4.4.7
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"4.4.7" from @angular/http@4.4.7
npm ERR!   node_modules/@angular/http
npm ERR!     peer @angular/http@"^2.0.0||^4.0.0" from angular2-jwt@0.2.3
npm ERR!     node_modules/angular2-jwt
npm ERR!       angular2-jwt@"0.2.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/sardell/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sardell/.npm/_logs/2024-04-05T12_58_50_575Z-debug-0.log
```

**Comment by exceptionfactory** [comment]
Thanks for providing additional details @sardell. As an additional point of reference, I am able to build `nifi-registry-web-ui`, but NPM reports warnings, not errors, for the version mismatch:

```
[INFO] --- frontend:1.14.2:npm (npm-install) @ nifi-registry-web-ui ---
[INFO] Running 'npm run ci' in /Users/exceptionfactory/projects/nifi/nifi-registry/nifi-registry-core/nifi-registry-web-ui/target/frontend-working-directory
[INFO] 
[INFO] > nifi-registry@0.0.5-SNAPSHOT ci
[INFO] > npm ci --ignore-scripts
[INFO] 
[INFO] npm WARN EBADENGINE Unsupported engine {
[INFO] npm WARN EBADENGINE   package: 'karma-webpack@5.0.1',
[INFO] npm WARN EBADENGINE   required: { node: '>= 18' },
[INFO] npm WARN EBADENGINE   current: { node: 'v16.13.2', npm: '8.1.2' }
[INFO] npm WARN EBADENGINE }
```

**Comment by sardell** [comment]
@exceptionfactory Thanks for sharing. I investigated a little more and I think I found the issue. There's a configuration property for npm called `engine-strict`. When set to true, version mismatches will cause a failure. I looked in my .npmrc file and saw mine was set to true. Rebuilding now after removing that property. If successful, I'll close this PR and issue.

**Pull request closed without merging**
