### PR TITLE
NIFI-6164 - Added CLI commands related to NiFi Registry extension bun…

### PR DESCRIPTION
**Pull request by bbende**
…dles

- Adding CLI commands fro uploading extension bundles
- Adding commands for listing extension bundles and their versions
- Adding checksums to UploadNarBundles command
- Adding sha256 to UploadExtensionBundle command, and refactoring result classes to be better organized
- Improvements for CLI commands to interact with extension registry.
- Added download-extension-bundle commands.
- Refactoring ProcessGroupBox

### CODE REVIEW

**Comment by kevdoran** [comment]
Will review...

**Comment by bbende** [comment]
@kevdoran just wanted to ping you to see if you had a chance to look at this, no worries if you're busy

**Comment by kevdoran** [comment]
@bbende Have not looked at it yet. Given the size of the PR, was waiting until I had a big chunk of time to devote to it. I think that should happen this week!

**Comment by bbende** [comment]
Sounds good, thanks! Hopefully it won't be as bad as it looks, I think about half the files changed are from moving to a new package.

**Comment by kevdoran** [comment]
Ah ok, that's a good point. I saw the file count and put this one on hold, but the line count is not bad, so yeah, should be able to knock it out this week. thanks!

**Comment by bbende** [comment]
@kevdoran thanks for the review! Here are my thoughts on the comments...

- I definitely agree that we may want to be consistent with the bucket id. In Registry's REST API there are basically two different ways to navigate the bundle stuff:

    - The "extension repository" end points which were meant to act kind of like Nexus. These end points have the following paths:
    ```
    /extension-repository/ (returns buckets)
    /extension-repository/{bucket-name} (returns groups)
    /extension-repository/{bucket-name}/{group-id} (returns artifacts)
    /extension-repository/{bucket-name}/{group-id}/{artifact-id} (returns versions)
    /extension-repository/{bucket-name}/{group-id}/{artifact-id}/{version}/content 
    ```
    -  The end points that use ids which are more similar to the flow end-points:
    ```
    /buckets/{bucketId}/bundles
    /bundles
    /bundles/{bundle-id}
    /bundles/{bundle-id}/versions
    /bundles/{bundle-id}/versions/{version}/content
    ```
    So right now the list commands are basically just following the extension repo end-points, so it    would be similar to navigating those links in your browser. We can switch to the others if we think it makes more sense, but not sure that both can easily be supported through the same command since the params are different.

- Ironically I originally had a list end point exactly like you described, but then decided to change to the idea of navigating the extension repo end points above. The issue with the list end point is that if you don't know what to filter on, then it just returns this crazy long list of everything. For example, there are 103 NARs in NiFi currently, so you get rows = 103 * versions per NAR.  We could maybe add it back but require at least a group id?

- I think the way the upload commands evolved I had implemented `upload-bundle` first which could be used for any type, then I just wanted an easy way to upload everything from NIFI without having to worry about understanding the bundleType parameter. So I figured we would just add another command for `upload-minifi-bundles`, but I see your point that really a single `upload-bundles` command could work for any type, so I can work on that change.

- You are probably right that there is limited use for the tag commands from the CLI perspective, but I guess I was thinking that we might not have a UX on NiFi side for a while, so this is another way to search for extensions rather than using the Registry REST API. From an automation perspective, really only the upload and download commands actually make sense. The rest of the stuff is more for interactive use. I think the ideas you had about how to change the tag commands make sense, I'll work on that.

**Comment by kevdoran** [comment]
@bbende Thanks for the detailed explanation. This all makes a lot more sense now.

- On the first point, Let's leave it as bucketName for now, but I would open up a Jira to make either command (flows or bundles) work with either name or id. For flows, if a name is given, we can make the CLI get buckets, find the matching id, and then call the existing endpoint with an ID param. For bundles, if an ID is given, we can do the same call to get buckets in order to lookup the name, and then continue as it works today. We could probably make this easier by adding some lookup methods to the NiFiRegistryClient that wraps the API to perform bucket lookup by name or id.

- On the second point, I feel like the current implementation method (drilling into group, artifact, version) is optimized for interactive shell use, whereas the other method we are discussing (listing all bundles) would be optimized for scripting automation use. Just thinking that if I were scripting calls to the CLI and needed all bundles, it would be tedious to write three nested for loops that uses the results of each "level" to make another call. I see both sides though - a huge table of results in the interactive shell might not be as useable as the current way you have it.

- I think we are on the same page with the last two points.

Thanks for all the hard work on this feature. From the backend through the REST API and client and now CLI, it's a very complete implementation!

**Comment by bbende** [comment]
Pushed two new commits...

1) Make upload-nars generic and become upload-bundles
2) Refactoring of the tag commands as we discussed

Not sure if there was anything we decided to change from the above discussion. I can add a command to list-bundles with some optional filters, or we can add that later.

**Comment by kevdoran** [comment]
I think these changes look good now @bbende. Let's leave the list-bundles commands as-is for now. Can always add list-bundles later.

In your most recent commit I saw this code comment:

> NOTE: There is a bug in the nifi-registry-client that sends bundleType from filter params using the name() instead of toString(). When that is resolved we can update this command to have an optional argument for bundle type and set it in the filter params.

I saw PR apache/nifi-registry#200 which fixes this, and I reviewed and merged that today. Given that, do you want to update this PR now, or address the extension type filter in a future PR? Just let me know, I'm holding off running to test the functionality for now.

**Comment by kevdoran** [comment]
On second thought, I guess we need to wait for the next release of NiFi Registry to get the bugfix in the client. Nevermind - Friday afternoon brain haze over here. Will review and merge as-is.

**Comment by bbende** [comment]
Thanks for checking out the latest changes. Yea, we'll need to wait for next release to update that one, probably not a big deal since we are only really storing NARs for now anyway, but just wanted to leave a reminder.

**Comment by bbende** [comment]
@kevdoran thanks for the final review... I accepted your changed and going to squash and merge this

**Pull request merged**
