### PR TITLE
NIFI-3600 Improve logging and relationship routing for failures in De…

### PR DESCRIPTION
**Pull request by jdye64**
…leteHDFS

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by trixpan** [comment]
@jdye64 can you please solve the conflicts?

Cheers!

**Comment by jdye64** [comment]
@trixpan I tried talking it out but that didn't seem to solve the conflict?? Will try more forceful procedures when I get off the road and near a computer ;) thanks for taking a look at this!

**Comment by trixpan** [comment]
:rofl:

**Comment by jdye64** [comment]
@trixpan refactoring due to NIFI-3204 #1561 which caused some conflicts

**Comment by trixpan** [comment]
Glad you managed to get the  lines out of their conflict... 😀 will review

**Comment by trixpan** [comment]
From a first look the code seems ok but I have a quick question:

Do we truly need a permission denied relationship? It seems like a deviation from the general nature of failure relationships (generally they are nearly all encompassing). 

Perhaps we could add the failure reason to an attribute and route to failure? 

Reason I ask is that I like the strong similarity between the *HDFS, the *File and *S3 processors and I suspect this change would introduce change that will move some of them appart?

**Comment by jdye64** [comment]
My reasoning for adding the extra relationship was for end users to understand that certain directories or files had improper permissions and have a visible way to see that with the extra relationship. However your right we could just add something like a "error.code" and "error.message" attributes and route to failure. I would like the "error.code" for sure however since that would be easy to route against while error.message might contain different messages from the exceptions when dependency versions change

**Comment by mattyb149** [comment]
Reviewer consensus (see the Jira case for details) is to exclude the hdfs.error.code for now, rather than possibly reporting an incorrect cause of an IOException. Once we can tell the difference, we can add that attribute back in.  In that state, @bbende and I are a +1

Adding a unit test, removing the attribute, and merging to master.   Thanks much!

**Pull request closed without merging**
