### PR TITLE
NIFI-8533: Replace deprecated jython-shaded dependency with jython-slim

### PR DESCRIPTION
**Pull request by mattyb149**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

The jython-shaded jar is deprecated and its dependencies can cause issues, the maintainers recommend switching to the jython-slim artifact.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [x] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by MikeThomsen** [comment]
@mattyb149 @joewitt I can't figure out what's going on here. I can pull down this branch and run `mvn clean install -Pcontrib-check` in the scripting bundle, and it builds just fine. Here, it fails with a class not found exception. It looks like it's a Github-specific problem.

**Comment by mattyb149** [comment]
@MikeThomsen I'm looking into this, it's the damndest thing, if you set `user.timezone` it fails, which is what we do even for the EN build (Australia). I'll change this to draft until I get it figured out

**Comment by mattyb149** [comment]
@MikeThomsen I'm looking into this, it's the damndest thing, if you set `user.timezone` it fails, which is what we do even for the EN build (Australia). I'll change this to draft until I get it figured out

**Review by exceptionfactory — APPROVED** [review]
@mattyb149 After rebasing, builds on all platforms succeeded.

https://github.com/exceptionfactory/nifi/runs/6262767858

Several recent improvements to the Maven build configuration included removing the explicit setting of the `user.timezone` property in `pom.xml`, and instead set the value through variables in the GitHub actions workflow. Verified a local build as well. +1 merging.

**Pull request closed without merging**
