### PR TITLE
NIFI-2711 - Making top-level nifi-assemblies directory with nifi-asse…

### PR DESCRIPTION
**Pull request by brosander**
…mbly and nifi-toolkit-assembly underneath it

### CODE REVIEW

**Comment by olegz** [comment]
@brosander there seems to be merge conflicts now. Would you mind addressing them?

**Comment by brosander** [comment]
@olegz rebased and fixed conflicts, diffed assemblies before and after

**Comment by trixpan** [comment]
@brosander conflicts again... :cry:

**Comment by trixpan** [comment]
@brosander is the PR still wanted? If yes, mind rebasing?

**Comment by brosander** [comment]
Seems like lack of demand for this change, probably should raise visibility on impact via a discuss thread before messing with assemblies anyway

**Pull request closed without merging**
