### PR TITLE
NIFI-5791: Add Apache Daffodil (incubating) bundle

### PR DESCRIPTION
**Pull request by stevedlawrence**
Adds a new daffodil bundle containing two processors (DaffodilParse and
DaffodilUnparse) used to convert fixed format data to XML or JSON using
Apache Daffodil and DFDL schemas.

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [X] Have you written or updated unit tests to verify your changes?
- [X] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [X] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [X] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [X] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [X] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by joewitt** [comment]
First of all this looks like a really thought out contribution and huge thanks for taking the time to create what looks like a well done NOTICE file!

I'm not sure about the naming/intent that is communicated to the user.  And in general we try to name things VerbSubject style.  What are some other names to consider?

**Comment by pvillard31** [comment]
Not related to the naming discussions but would it make sense to consider a DFDLReader and a DFDLWriter implementation? Didn't look into the code but since it can parse/unparse into JSON, it should be doable? It would be a nice addition.

**Comment by stevedlawrence** [comment]
I'm not too familiar with the Reader/Writer idiom. From what I can tell, a Reader converts data to a Record, and a Writer converts those Records back to the data format? Is that accurate? My one concern is that although DFDL/Daffodil can handle record oriented data, often times it is much more complex. For example, the [daffodil examples](https://daffodil.apache.org/examples/) page shows two examples of how DFDL can convert data to XML. The first example is CSV data and is clearly record oriented. But the second example is PCAP (used in the above template) which could be seen as records, but is a complex nesting and there's a global header that isn't really a record. Most data formats we've seen DFDL used for a more like the latter. 

The SchemaRegistry concept that looks to be used by Readers/Writers seems like a really nice way to provide a DFDL schema (if possible without using the Records?), but I'm not sure how well the Record concept fits in. Does it make sense to keep the XML/JSON output as in the PR, and then if a particular infoset does map well to a Record the user could add a JSON/XMLReader to convert to a record?

**Comment by ottobackwards** [comment]
Isn't this like the Jolt capability?

**Comment by stevedlawrence** [comment]
From my understanding of Jolt, this capability is pretty different.

Jolt reads JSON data, performs various transformations as described by a JOLT specification, and then writes out back to JSON.

Daffodil/DFDL (Data Format Description Language) on the other hand, reads a wide array of data formats (text, binary, scientific, military, financial, etc.) and parses the data format as described by a DFDL schema (see @DFDLSchemas for some publicly available schemas), and outputs the data to an infoset, which can be projected into XML or JSON for consumption. It is also capable of the reverse, by reading in the XML/JSON infoset and "unparsing" it back to the original data format.

So while JOLT is a transformation from JSON to JSON, Daffodil/DFDL could be considered a transformation from arbitrary data to XML or JSON, as described by a DFDL schema.

**Comment by ottobackwards** [comment]
What I mean is that from a high level, it is a transformational capability, and may be used as an alternative.

**Comment by stevedlawrence** [comment]
Ah yes, you are correct.

**Comment by stevedlawrence** [comment]
Actually, I should probably add a little more clarification.

It is correct to say that Daffodil could be considered a transformation capability, but I'm not sure it could really be seen as an alternative to Jolt specifically.

One could definitely write a DFDL schema to describe and parse JSON data, similar to what Jolt can do, but the resulting infoset would just be JSON that is probably more generic and less useful that what Jolt would create. Daffodil does not have the same transformational capabilities that Jolt has (e.g. filtering, sorting, reordering). It really just takes a data format that is not natively supported and transforms it to a logically similar representation in a natively supported format (i.e. XML/JSON). If your data is already in something like XML or JSON, it doesn't really make sense to use Daffodil.

So for example, you might take PCAP data, like in the above template, and feed it through Daffodill to transform it to JSON. But there might be extraneous data that Daffodil parsed that you don't need or care about. So you might then feed that JSON through Jolt to to transform it to something that has only the fields you care about, or is reordered/renamed to be something more useful to ones usecase.

So this isn't something that could be viewed as an alternative to Jolt, but more like something that could be used in conjunction with Jolt to allow one to transform JSON data that wasn't originally JSON.

**Comment by ottobackwards** [comment]
Thanks for taking the time to explain further.  I see what you mean.  Nifi needs a better way to get across to users when to use what processor in general.

**Comment by mattyb149** [comment]
This is interesting stuff, I need to read more up on DFDL, might make a good schema definition language as an alternative to Avro schemas. Also at first glance it seems the Daffodil infoset is analogous to a NiFi Record for data, and/or a NiFi RecordSchema for its schema. Having an infoset as the underlying data model seems to overlap a bit with how the NiFi Record stuff works, for example we could have a PCAPReader and any writer such as JSONWriter, then the ConvertRecord processor can convert PCAP to JSON. I think someone was working on a PCAP reader, not sure how they handled the global stuff. If Avro schemas are not sufficient to capture this kind of model, then we should definitely look at DFDL as an alternative (we've been considering XSD as a more expressive alternative).

Quick note about JOLT, the "normal" use case is for JSON-to-JSON conversion, but the underlying library does the transformation on a POJO, not JSON. So the usual entry point for JOLT is to give it a JSON string, it converts to a POJO, runs the transformation, and takes the resulting POJO and writes it out as JSON. In NiFi I wrote JoltTransformRecord, which instead of explicit JSON uses the NiFi Record API, so it gets each record (in whichever format) as a NiFi Record, translates it to a POJO, then runs the JOLT transforms, then translates back into a NiFi Record, which is written out in whatever format is specified by the RecordWriter.

**Comment by stevedlawrence** [comment]
After some research and reading the [Avro specification](https://avro.apache.org/docs/1.8.1/spec.html) , I'd agree that the DFDL infoset does seem somewhat similar to a Record.

DFDL does support all the primitive types (null, boolean, int, long, float, double, bytes, string) and logical types (date, time, decimal), plus a few others (integer, byte, short, signed/unsigned) . But as far as complex types, it only really supports "records" and arrays. Below is the list of things in Avro that the DFDL infoset does not support:

* It sort of supports enums, but only in the sense that it can validate that a primitive type is one of the valid enum values via the xsd:restriction.
* Maps. In DFDL, a map would be implemented as a sequence of key/value pairs, so there wouldn't be any enforcement of unique keys.
* Unions. Each element in the infoset must have an explicit primitive type. Each element can be optional or nulled, but cannot be a union of multiple primitive types. In DFDL, that is handled by an xs:choice of two different elements with different types and some method (often a discriminator) to determine which branch of the choice.
* Namespaces are slightly different, but probably similar enough. DFDL uses XML namespacing.
* Aliases are not supported.
* Sort order. DFDL outputs infoset elements in the order in which they appear in schema.
* The DFDL infoset does not contain the schema. One must keep track of the associated schema outside of the data.
* The isn't really a concept of different serializations like Avro looks to have. Instead, the DFDL schema defines the physical data format via DFDL annotations, which are used to determine how to serialize/deserialize data. Theoretically, one could have different schemas with the same logical format but with with different DFDL annotations to describe physical formats, but that isn't a comment use case we've come across.

The Daffodil devs would be happen to discuss the possibility of integrating Daffodil/DFDL as an alternative to Avro. Not sure if any of the above limitations are blockers. The core of Avro and DFDL definitely do seem to have some overlap.

**Comment by MikeThomsen** [comment]
Reading over the comments here, I'm wondering if it would make sense to consider creating a wrapper around our record readers for this instead of going to a straight competition with Avro. For example, I could see potential with the PCAP [example](https://daffodil.apache.org/examples/) reading the PCAP data into JSON and then transforming the JSON into Avro by having a `DaffodilReader` that could wrap `JsonTreeReader` and emit JSON to the reader. Thoughts?

**Comment by stevedlawrence** [comment]
That doesn't seem totally unreasonble to me. I'm relatievely new to the Record/Avro concept. It sounds to me like to take that route we would need to convert the DFDL schema to an Avro schema that the wrapped JsonTreeReader would use to parse the Daffodil-created JSON? Daffodil doesn't currently have an API to do that, so we'd need to develop that.

If instead Daffodil were to create Records directly like mentioned in previous comments, would something like that converter still be necessary? Or can one build up records without really having a concept of a schema?

**Comment by MikeThomsen** [comment]
> Or can one build up records without really having a concept of a schema?

In 1.9, we can do schema inference, but I wasn't thinking schemaless here. If someone uses Daffodil to convert data the way you did in your sample, they should be able to create an Avro schema that matches the output of Daffodil (at least in most cases).

**Comment by stevedlawrence** [comment]
Yep, but most of the military related scheas have restricted access due to the nature of the formats. The following are current available on [DI2E.net](https://di2e.net) if you have access to that, under the "DFDL/Daffodil" project. Some schemas are more complete and more tested than others:
* USMTF
* VMF
* Link16
* USCG UCOP
* AGNOSC Remedy
* Army DRRS
* CEF
* GMTIF

The [MIL-STD-2045](https://github.com/DFDLSchemas/mil-std-2045) schema is publicly available on GitHub if you want an idea of how something like VMF or Link16 might be described in DFDL.

I haven't heard of ICPUBS--as far as I know a schema for that has not been developed.

**Comment by MikeThomsen** [comment]
@stevedlawrence I think [this](https://www.dni.gov/index.php/who-we-are/organizations/enterprise-capacity/ic-cio/ic-cio-related-menus/ic-cio-related-links/ic-technical-specifications/intelligence-publications) is a legit download of the PUBS specification. It's a rather comprehensive XML data format with all that that implies and insinuates.

**Comment by stevedlawrence** [comment]
@MikeThomsen DFDL/Daffodil aren't really designed or intended to parse XML data like PUBS. It's theoretically possible, but it's a pain. Generally we reccomend if your data is already in XML then it's beset tod just use one of they XML parsers out there. Where Daffodil really shines is when the data isn't in XML or some readily accessable format. In that case, Daffodil can be used to convert the data to XML so that is is more readily accessable.

Note that often times the XML you get out of of Daffodil doesn't match what you soemtimes want, due to restrcitions on how DFDL schemas are written and how infoset are represented in XML. For example, MTFXML is a standard that tries to describe USMTF data but in a XML format. Daffodil is not able to convert USMTF data directly to MTFXML. If that was the goal, one would describe USMTF data with a DFDL schema, parse it to an XML representation using Daffodil. and then transform that XML to MTFXML via something like XSLT.

**Comment by joewitt** [comment]
closing due to inactivity

**Pull request closed without merging**
