### PR TITLE
NIFI-1037 Ported processor for HDFS' inotify events to 0.x.

### PR DESCRIPTION
**Pull request by jjmeyer0**
Ported processor for HDFS' inotify events.

### CODE REVIEW

**Comment by jjmeyer0** [comment]
@pvillard31 fixed java 7 issues of this processor as requested.

**Comment by pvillard31** [comment]
@jjmeyer0 Thanks! I just merged it in 0.x branch.

**Comment by JPercivall** [comment]
@jjmeyer0 this was committed to 0.x but unfortunately the magic "This closes #536." commit line only works for the master branch. Could you manually close this PR?

**Comment by pvillard31** [comment]
Thanks @JPercivall! I didn't realize that...

**Pull request closed without merging**
