### PR TITLE
[WIP] NIFI-5505 Added Java 11 build to Travis CI

### PR DESCRIPTION
**Pull request by jtstorck**
```
Introduced stages to cache dependencies before build and test
Added --fail-never to dependency cache stage to allow dependency:go-offline to finish and update the cache with any dependencies that were able to be downloaded
Added download of AdoptOpenJDK 11.0.4 for the Java 11 build
Removed setting environment variables to enable easier sharing of cache between build, region/language settings are passed in via the command line when invoking maven
Formatted scripts to allow multiline commands for more readability
Replaced "exit ${PIPESTATUS[0]}" with "test ${PIPESTATUS[0]} -eq 0" to avoid using "exit" in script, which prevents Travis from completing the cache upload after the build completes
Install Maven 3.6.1 for the -ntp (no-transfer-progress) feature
Updated all build stages to exclude non-api nar and assembly modules to decrease build time
Dependency cache stages check if the cached maven repository doesn't exist or is empty before attempting to download dependencies
```
----
To verify this PR, Travis should have a completed build, with two stages executed to download and cache dependencies for openjdk8 and non-explicit-jdk Cache stages, and four stages for the various locale and JDK version builds.

Please be aware that the four stages which build and test the code exclude assembly and -nar modules to decrease build time, so that all stages can finish in less than 50 minutes.

----
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Added Java 11 build to Travis CI._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [n/a] Have you written or updated unit tests to verify your changes?
- [n/a] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [n/a] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [n/a] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [n/a] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [n/a] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by jtstorck** [comment]
@pvillard31 There are a couple things that can be done to share the Maven repo.  I need to tweak the script that determines if the dependency:go-offline stage should run or not.  It's checking to see if there's an .m2 directory, but it needs to also check if there are directories within .m2, since the cache step creates .m2 even if there isn't anything in it.

The way that Travis creates caches is based on a few factors/settings, and one of them is the JDK being used by the job/stage.  Since the builds either specify a JDK, or use a custom JDK with no label, two separate caches are created by Travis.  I could specify that all the build stages should use the same cache, but I'd like to avoid messing with the cache functionality.  On my branch (before I created the PR) the builds were working because the dependencies were cached.  After tweaking the caching stage jobs, the builds should complete successfully.

**Comment by jtstorck** [comment]
@pvillard31 To get all the builds to finish in time, I had to exclude the nar and assembly modules, which is not optimal, but we can remove the exclusion once we break up the repo.

The non-default bundles, from the quick look in the pom I did before, are still compiled and tested without referring to their profiles.  I'll double-check, but the profiles are just for including them in nifi-assembly, which is excluded from the build, so there's no reason to activate their profiles in the Travis build.

Thanks for reviewing the PR, I appreciate it!  We can get this merged as soon as #3404 is merged to master.

**Comment by pvillard31** [comment]
Yes, you're right, just had a quick look and the non-default bundles are compiled and tested. That's awesome 👍

**Comment by pvillard31** [comment]
Hey @jtstorck - now #3404 is merged, do you mind rebasing/squashing the PR for a final round?

**Comment by jtstorck** [comment]
@pvillard31 Yes, rebasing now...

**Comment by jtstorck** [comment]
@pvillard31 Rebased and pushed.  I'll monitor the Travis build and restart any jobs that time out or fail due to test inconsistencies (that exist outside this PR anyway) until they're all green.  Feel free to merge when you're comfortable with the results. 😄

**Comment by jtstorck** [comment]
All green... didn't need to restart any jobs.

**Comment by pvillard31** [comment]
That's awesome, thanks @jtstorck ! Merging to master

**Pull request closed without merging**
