### PR TITLE
NIFI-3024 - Encrypt-toolkit flow.xml.gz support

### PR DESCRIPTION
**Pull request by brosander**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [x] - N/A - If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] - N/A - If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [x] - N/A - If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [x] - N/A - If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by alopresto** [comment]
@brosander and I discussed this today and there are a couple small edge cases outstanding. As he will be away from his computer for a few days, I am taking over and will have an updated PR (may need to open a new one as I cannot push to his branch) tomorrow. Will update/close here and link to the new one then.

**Comment by olegz** [comment]
@brosander not sure if you noticed there is a merge conflict that needs to be addressed

**Comment by YolandaMDavis** [comment]
@olegz I think @alopresto is taking over this PR and may create a new one, per his comment

**Comment by alopresto** [comment]
I have created [PR 1261](https://github.com/apache/nifi/pull/1261) to implement this. Recommend this PR be closed.

**Comment by brosander** [comment]
closing in favor of #1261

**Pull request closed without merging**
