### PR TITLE
NIFI-12074 updated images to base on Java 21 and added Python3

### PR DESCRIPTION
**Pull request by joewitt**
# Summary

[NIFI-00000](https://issues.apache.org/jira/browse/NIFI-00000)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by joewitt** [comment]
The resulting image grew from 1.7GB to 2.2GB.  Most of this is from the inclusion of Python3 which we'll want so users can leverage the new Python capabilities in NiFi 2.x.  We will need to find ways to reduce the overall size more as we go.

**Review by exceptionfactory — COMMENTED** [review]
Thanks for putting together these changes @joewitt! Switching to the BellSoft [Liberica JDK](https://bell-sw.com/libericajdk/) image looks good, which aligns with the default JDK that Spring Framework builds use for container images.

I also agree with disabling plain HTTP access given the inherent security issues. We should evaluate removing plain HTTP access completely in a separate issue, but these changes look good.

I would like to do some testing, but the changes look straightforward on initial review. If others get to reviewing this before I have the opportunity to test, no need to wait for further review, but I will try to follow up soon.

**Comment by markap14** [comment]
Thanks @joewitt and @exceptionfactory . I did some light testing. I was able to verify that it started up as expected running Java 21 and that Python is installed. Unfortunately, though, it does not uncomment the line in nifi.properties needed in order to enable Python processors. Probably should get that line uncommented in the docker image. Otherwise, all looks good to me.

**Comment by markap14** [comment]
Thanks for the update @joewitt . Looks good to me. Was able to bring it up, pointing to my local branch's `nifi-nar-bundles/nifi-py4j-bundle/nifi-python-test-extensions/src/main/resources/extensions` directory as a mount and it successfully started up and allowed me to start using Python processors. +1 will merge to main.

**Pull request merged**
