### PR TITLE
NIFI-2116 Initial Draft for Spanish readme.md

### PR DESCRIPTION
**Pull request by chagara**

### CODE REVIEW

**Comment by olegz** [comment]
I would really love to merge this one as I truly believe these types of PRs are so important to grow the community, but I don't speak Spanish, it would be nice if another Spanish-speaking community member would go through it.

**Comment by alopresto** [comment]
If I can finish my 1.0 tickets I will review this.

**Comment by trixpan** [comment]
@chagara - any chances of updating this README to match the version 1.0? 

@alopresto @olegz - Do we have Spanish speaking committers? It would be unfortunate to merge this but be unable to keep it in parity with the English document.

Cheers

**Comment by chagara** [comment]
I'll work on this to update it to the latest.

**Comment by chagara** [comment]
I'm going to close this pull request since the documentation changed a lot and the changes added here are not needed anymore. I have been trying to translate the overview doc and will take some time since the new information when translated makes barely any sense so I have to connect everything correctly.

**Pull request closed without merging**
