### PR TITLE
NIFI-3272: GC stats in Cluster view

### PR DESCRIPTION
**Pull request by mcgilman**
NIFI-3272:
- Adding explicit support for the default and G1 garbage collector in the JVM tab of the cluster table.

### CODE REVIEW

**Comment by joewitt** [comment]
@mcgilman this is really useful.  Can you please update the webpage to tell the user that it currently only supports two GCs (and their names) and if using an alternative GC it will not show the results at this time.

**Comment by mcgilman** [comment]
Thanks @joewitt! Will update accordingly.

**Comment by mcgilman** [comment]
@joewitt I took a different approach. Please pull down the latest and re-review. Thanks!

**Comment by joewitt** [comment]
@mcgilman it appears there is a merge conflict with the second commit.

**Comment by mcgilman** [comment]
Rebased, squashed, and pushed. Thanks!

**Pull request closed without merging**
