### PR TITLE
NIFI-5155: Add host address info to bulletins

### PR DESCRIPTION
**Pull request by mattyb149**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by mattyb149** [comment]
@zenfenan Good point. The reporting tasks haven't had this information available before, is this a "no-harm-no-foul" thing, and if not, how should it be handled?

**Comment by zenfenan** [comment]
I'm not entirely sure if this poses an immediate threat, but in the future when other extensions try to use the `getNodeAddress()` API, it might possibly be an issue, especially on the user experience perspective i.e. chances of the user getting confused when all the bulletins print 127.0.0.1 are there, IMO.

For the workaround, this feels like a good approach: https://stackoverflow.com/a/28346117

**Comment by mcgilman** [comment]
I'm not exactly sure why the Bulletin itself has a `nodeAddress` field. However, I can offer that the corresponding BulletinDTO contains a `nodeAddress` to help differentiate between which node in the cluster is reporting the message. This is populated when the responses are merged at the cluster coordinator. In standalone mode, there is only a single instance so this field does not need to be populated. This is also how component `validationErrors` work.

**Comment by zenfenan** [comment]
@mcgilman Are you saying regardless of the `setNodeAddress` API not setting anything, the cluster coordinator takes care of populating it ?

**Comment by mcgilman** [comment]
@zenfenan Correct. The cluster coordinator handles setting the node address for the bulletins that are returned through the REST API. However, those are not the same objects that are available in the `SiteToSiteBulletinReportingTask`. I wasn't considering this in my previous response.

**Comment by markap14** [comment]
@mattyb149 I think this makes sense but have a couple of thoughts on the PR:
- Probably should use the value set in NiFiProperties for the http/https hostname if it is populated. This would be more consistent with the value provided to the Cluster Coordinator and also is better for multi-homed environments.
- If not available, I would do the `InetAddress.getLocalHost().getHostAddress()` address only once and stash away that value in a `final` member variable rather than performing the lookup for each Bulletin that is created.

**Comment by mattyb149** [comment]
@markap14 How would we get at the value in NiFiProperties? They're not readily available from the FlowController (nor is the FlowController interface itself IIRC). Perhaps we call a static method on BulletinFactory?

Agreed about storing away getHostAddress(), that was a hasty copy-pasty :)

**Pull request closed without merging**
