### PR TITLE
NIFI-4007 Update azure EventHubs client to latest version

### PR DESCRIPTION
**Pull request by SreeramGarlapati**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [y ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ y] Have you written or updated unit tests to verify your changes?
- [ y] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ y] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ y] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ y] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ y] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

Couple of azure eventhubs customers using apache-nifi-processor are running into known issues fixed in later versions. So updating the version to the latest - for the next release to pick this up.
https://issues.apache.org/jira/browse/NIFI-4007

### CODE REVIEW

**Comment by SreeramGarlapati** [comment]
Hello Folks! can someone please help with the next steps...
Thanks!

**Comment by pvillard31** [comment]
Hi @SreeramGarlapati, thanks for your contribution. I looked at the release notes from
https://github.com/Azure/azure-event-hubs-java/
And it seems there are few breaking changes between 0.9.0 and 0.14.0.

In particular:
- The ``EventData.ApplicationProperties`` is now a ``Map<String, object>``. 
- Simplified EventData by deprecating the ``getBody*`` API's. As such, the following methods have been deprecated (#81):
    ``EventData.getBody()`` replaced with ``EventData.getBytes()``
    ``EventData.getBodyOffset()``
    ``EventData.getBodyLength()``

I think we are only concerned by the deprecation of the ``getBody()`` that should be replaced by ``getBytes()`` in ``GetAzureEventHub``. Could you take care of that?

Otherwise, I did few tests and it seems to be working as expected.

Thanks!

**Comment by pvillard31** [comment]
Also, right now, 0.14.2 is available, I'd suggest to go with this version.

**Comment by pvillard31** [comment]
+1, merging, thanks @SreeramGarlapati

**Pull request closed without merging**
