### PR TITLE
NIFI-7522 : Add Kafka 2.5 Processors set

### PR DESCRIPTION
**Pull request by gitfirenz**
[Test Template NIFI-7522.zip](https://github.com/apache/nifi/files/4795521/Test.Template.NIFI-7522.zip)

#### Description of PR

Add Kafka 2.5 Processors set (NIFI-7522), in order to : 
* Have the last fixes from Kafka
* Use the static Membership Consumers (to reduce rebalancing)

### For all changes:
 - [x] Is there a JIRA ticket associated with this PR? Is it referenced
in the commit message?
 - [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
 - [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?
 - [x] Is your initial contribution a single, squashed commit? Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not squash or use --force when pushing to allow for clean monitoring of changes.

### For code changes:
 - [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
 - [x] Have you written or updated unit tests to verify your changes?
 - [x] Have you verified that the full build is successful on JDK 8?
 - [x] Have you verified that the full build is successful on JDK 11? **(TLS 1 & TLS &1.1 tests failure, not present on JDK11+Centos8)**
 - [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under ASF 2.0?
 - [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
 - [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
 - [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
 - [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Testing
**Infra :** 
The static kafka membership has been tested with a kafka 2.5 single node, topic "test" with 5 partitions (Centos 8 Stream 20191219 with JDK8)

**Code :** A NIFI template with 3 consumers is attached (NIFI template). 

The 3 consumers have a group.instance.id 01 02 03 and a session.timeout.ms of 10minutes. 

**Results :** 
* The consumer consumes (like in 2.0)
* The  kafka server log show the join of the static consumer : "Static member Some(01) of group CG with unknown member id rejoins".

### CODE REVIEW

**Comment by MikeThomsen** [comment]
Read over your Jira ticket, and updating the Kafka 2.X processors might make more sense. We're running out of space in our convenience binary so it might be a hard fit to have Kafka 2.0 and 2.5 processors at the same time. Could also make it a lot easier to review if we can merge this into the 2.X processors. Do you know of any breaking changes between 2.0 and 2.5?

**Comment by joewitt** [comment]
Kafka is a different animal.  We should just dump an older nar from the assembly but we should add a new Kafka 2.5 specific nar.

I'll review this as it gets closer to ready for review.

**Comment by MikeThomsen** [comment]
We have 0.9, 0.10 and 0.11 in nifi-assembly. Are any of them worth keeping in the convenience binary at this point vs moving them to profiles?

**Comment by joewitt** [comment]
I'd punt 0.9 and 0.10 for sure.  I still run into 0.11 in the wild so prob good to hang onto that a bit longer.

**Comment by gitfirenz** [comment]
Hello, i've just finished compiling with JDK8 and JDK11 on Centos8. So i'm technically ready

My POV is : 
- putting 2.5 client in the 2.0 processor is a bit confusing for the user, despite doc
- the 2.5 client is 2.0-protocol-compatible, but i haven't tested.
- The 2.6 client will implement "incremental rebalancing", so i'd be good to anticipate it.
- There will be a Kafka 3.x [Roadmap](https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Improvement+Proposals)
- Maybe can we create a "2.5+" Processor with the 2.5 and further 2.6, 2.7 etc

**Pull request closed without merging**
