### PR TITLE
NIFI-5596 Upgraded splunk-sdk-java version

### PR DESCRIPTION
**Pull request by mohitgargk**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by MikeThomsen** [comment]
@joewitt I noticed that it adds bouncy castle and jbCrypt. These are transitive depdenencies that come in from security-utils. Should the be added to L&N?

```
[INFO] org.apache.nifi:nifi-splunk-nar:nar:1.8.0-SNAPSHOT
[INFO] +- org.apache.nifi:nifi-splunk-processors:jar:1.8.0-SNAPSHOT:compile
[INFO] |  +- com.splunk:splunk:jar:1.6.3.0:compile
[INFO] |  \- org.apache.nifi:nifi-processor-utils:jar:1.8.0-SNAPSHOT:compile
[INFO] |     +- org.apache.nifi:nifi-utils:jar:1.8.0-SNAPSHOT:compile
[INFO] |     |  \- org.apache.nifi:nifi-api:jar:1.8.0-SNAPSHOT:provided
[INFO] |     +- org.apache.nifi:nifi-security-utils:jar:1.8.0-SNAPSHOT:compile
[INFO] |     |  +- org.apache.commons:commons-lang3:jar:3.7:compile
[INFO] |     |  +- commons-codec:commons-codec:jar:1.11:compile
[INFO] |     |  +- org.bouncycastle:bcprov-jdk15on:jar:1.59:compile
[INFO] |     |  +- org.bouncycastle:bcpkix-jdk15on:jar:1.59:compile
[INFO] |     |  +- org.apache.nifi:nifi-properties:jar:1.8.0-SNAPSHOT:provided
[INFO] |     |  \- de.svenkubiak:jBCrypt:jar:0.4.1:compile
[INFO] |     +- commons-io:commons-io:jar:2.6:compile
[INFO] |     \- com.fasterxml.jackson.core:jackson-databind:jar:2.9.5:compile
[INFO] |        +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[INFO] |        \- com.fasterxml.jackson.core:jackson-core:jar:2.9.5:compile
[INFO] +- org.apache.nifi:nifi-standard-services-api-nar:nar:1.8.0-SNAPSHOT:compile
```

**Comment by MikeThomsen** [comment]
The change itself LGTM, but awaiting L&N feedback.

**Comment by joewitt** [comment]
@MikeThomsen if the nar now includes a dependency it did not previously include then the L&N will need to be updated, if necessary, to reflect that.  I dont recall the case of jbcrypt but I dont think that is a new dependency in nifi overall.  If we have it in a L or N of a binary artifact elsewhere then we'll want it here too.  Make sense?

**Comment by MikeThomsen** [comment]
Yes. Wanted to verify before putting @mohitgargk on a wild goose chase.

**Comment by MikeThomsen** [comment]
@mohitgargk it's mostly copy pasta, so I'll do it.

**Comment by MikeThomsen** [comment]
Merged, thanks for the contribution. @mohitgargk can you manually close this? I got distracted and forgot to add the "closes" line. Thanks.

**Comment by mohitgargk** [comment]
Thanks @MikeThomsen .

**Pull request closed without merging**
