### PR TITLE
WIP NIFI-12996 removing commons-compress from shared nar/bom and ensuring…

### PR DESCRIPTION
**Pull request by joewitt**
… optional deps depended on are synced on version

# Summary

[NIFI-00000](https://issues.apache.org/jira/browse/NIFI-00000)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — COMMENTED** [review]
Thanks for evaluating the details of these optional dependencies @joewitt.

Based on the number of references to Commons Compress listed, it seems like it would be better to move the optional compression libraries into the `nifi-standard-shared-nar`. That would make them available in the same ClassLoader, as required for standard operation.

I agree that the Netty dependencies, in particular `netty-codec`, need to be evaluated along these lines.

**Comment by joewitt** [comment]
paraphrasing you're basically saying "Hey this is great.  How about doing it exactly the opposite way" :).  Haha all good.  You're probably right.  Will give that a go.  only means we need zstd as the other deps are direct deps and bypass commons compress anyway.

**Comment by joewitt** [comment]
@exceptionfactory Ok I believe I've updated to what you've described.  Tested on a live install and it works as well.  Checked where commons-compress and zstd libs are now as well and checks out

**Review by exceptionfactory — APPROVED** [review]
Thanks for making the adjustments @joewitt, the latest version looks good and resolves the issue. We can address any other issues with other libraries separately if needed. +1 merging

**Pull request closed without merging**
