### PR TITLE
NIFI-8604 Upgraded Apache Accumulo to 2.0.1

### PR DESCRIPTION
**Pull request by exceptionfactory**
#### Description of PR

NIFI-8604 Upgrades Apache Accumulo libraries from 2.0.0 to 2.0.1.  This update brings the client version up to date with the current server version and avoids the OWASP library vulnerability notification that impacted Apache Accumulo server 2.0.0.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [X] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [X] Have you verified that the full build is successful on JDK 8?
- [X] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by thenatog** [comment]
I checked the Accumulo page for release notes on this and checked the commits for the 2.0.1 tag, looks like there shouldn't be any compatibility issues with this patch version (as we'd expect). Do you foresee any issues with this upgrade? I ran the ScanAccumuloIT which passed just fine.

**Comment by exceptionfactory** [comment]
> I checked the Accumulo page for release notes on this and checked the commits for the 2.0.1 tag, looks like there shouldn't be any compatibility issues with this patch version (as we'd expect). Do you foresee any issues with this upgrade? I ran the ScanAccumuloIT which passed just fine.

Thanks for checking @thenatog.  I also reviewed the release notes and changes from 2.0.0 and 2.0.1.  The changes primarily related to Accumulo server, so I don't see any concerns with upgrading versions.

**Comment by phrocker** [comment]
@thenatog and @exceptionfactory  I haven't tested this bundle with the updated pom specifically but have tested 2.0.1 -> 2.0.0 and there should be no issues previously. The only possible concern would be Thrift interconnect changes but the API was not changed in that patch release. The changes made [1] are within a thrift server implementation for better exception management and as @exceptionfactory suggested, not particularly pertinent to this bundle [0] . I would have no heartburn merging this . 

Would you both feel more confident if I tried to find some time to test this? I have a queue of various PRs that I'm trying to test across various projects  -- so I'd likely not be able to get to it until the end of the week; however, since this is so minor I can probably get to it sooner. 

[0] https://github.com/apache/accumulo/compare/rel/2.0.0...rel/2.0.1#diff-ca2a04249ba6f604c36af23d96e2c3949e6098223a6b7cffea8ea299f1644095R149
[1] https://github.com/apache/accumulo/compare/rel/2.0.0...rel/2.0.1

**Comment by exceptionfactory** [comment]
Thanks for the feedback @phrocker!  Given the apparent low impact of the changes from 2.0.0 from 2.0.1, I'm comfortable moving forward, however, I defer to you and @thenatog to decide whether additional verification is necessary.  The version upgrade isn't pressing from my perspective, so there is time for additional verification if either of you think it is worth spending the cycles.

**Comment by thenatog** [comment]
@phrocker I'm also comfortable merging this one in as is, given the commit log for this version is short and specific to fixes only. Hope you're doing well man!

**Comment by thenatog** [comment]
+1 merging :)

**Pull request closed without merging**
