### PR TITLE
NIFI-1655 - Add .gitattributes to specifically define

### PR DESCRIPTION
**Pull request by trixpan**
the line ending format of particular file type (i.e. .java = LF, .bat=CRLF)

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [X] ~~~Have you written or updated unit tests to verify your changes?~~~
- [X] ~~~If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?~~~ 
- [X] ~~~If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?~~~
- [X] ~~~If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?~~~
- [X] ~~~If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?~~~

### For documentation related changes:
- [X] ~~~Have you ensured that format looks appropriate for the output in which it is rendered?~~~

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by trixpan** [comment]
@joewitt - When doing this change I noticed some changes to HL7 files and looking online it seems like HL7 uses CR as a "segment separator".

Would you mind if I renamed the relevant files with extension .hl7 (which seems to be accepted as a de-facto HL7 file extension) and exclude them accordingly?

Cheers

**Comment by trixpan** [comment]
@joewitt as suspected HL7 does inded use CR as a segment separator so I renamed the files to hl7 and treated hl7 as binary. Tests passed locally and I am now checking what travis has to say

**Comment by mattyb149** [comment]
Travis no likey :(  Looks like some test files related to decompression were created when the line endings were CRLF, they would have to be recreated as well.

**Comment by jfrazee** [comment]
@trixpan You're right about the HL7 and it's actually ill-formed if you don't use CR, crazy. For best results, though, we should just move the HL7 content into a String in the test class. Renaming/dealing in git is okayish, but I think sets us up to have pain here and there. I opened [NIFI-3771](https://issues.apache.org/jira/browse/NIFI-3771) to address.

**Comment by trixpan** [comment]
@jfrazee while we are doing HL7 is there any chance you can look at the EncryptContent tests as well?

Due to the nature of PGP ASCII Armor files they use a mix of DOS and Unix line format as well.

**Comment by jfrazee** [comment]
@trixpan Do you know which files are problematic? I'm assuming the *.txt; i.e., the content that's being encrypted. I'd figure it wouldn't matter for the *.asc and *.pgp.

**Comment by trixpan** [comment]
@jfrazee now that HL7 is out of the way, giving it another try... Will let you know when I am happy with code.

Cheers

**Comment by trixpan** [comment]
@jfrazee this seems to be passing tests now. Let me know what you think

**Comment by trixpan** [comment]
@jfrazee?

**Comment by jfrazee** [comment]
@trixpan I think there's a mistake in the last line of .gitattributes. It is missing the 'text' qualifier and just is the file pattern and then eol. Let me know if I've misunderstood; otherwise I'll +1 and I can fix it during the merge.

**Comment by trixpan** [comment]
@jfrazee I resolved conflict with master (unrelated to the change).

I would agree that the "text" qualifier was indeed missing. Fixed.

**Comment by MikeThomsen** [comment]
@trixpan if you still want to pursue this, feel free to clean it up and rebase it off main and tag me.

**Pull request closed without merging**
