### PR TITLE
NIFI-8530 updated worfklow to hopefully better handle artifact retrieval

### PR DESCRIPTION
**Pull request by joewitt**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Enables X functionality; fixes bug NIFI-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [ ] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by ottobackwards** [comment]
I found another issue similar to this, with _almost_ the same fix, but they also set the ttl, do we want to try that?
https://github.com/actions/virtual-environments/issues/1499#issuecomment-689467080

**Comment by joewitt** [comment]
The commentary in the link I provided suggests the TTL might not be that valuable as i read it.  So I'll keep it out for now.  Updated JIRA to reference it for future purposes in case this change doesn't do enough.  I'm also a little concerned about build performance getting even worse by adding anything else.  WE'll see.

**Comment by ottobackwards** [comment]
Fair enough, waiting for builds to finish.
Wondering if we should see 
```bash
Warning:  Could not generate extensions' documentation
2237
org.apache.maven.plugin.MojoExecutionException: Failed to create Extension Documentation
2238
    at org.apache.nifi.NarMojo.generateDocumentation (NarMojo.java:596)
2239
    at org.apache.nifi.NarMojo.execute (NarMojo.java:499)
```
at all.  They *are* warnings not errors.

**Comment by joewitt** [comment]
we should kill all warnings.  but that isn't part of this JIRA/PR.

**Comment by ottobackwards** [comment]
I'll try to create a jira on it

**Comment by ottobackwards** [comment]
+1, the failure is not due to these settings.  The changes look good and we should get them running

**Review by exceptionfactory — APPROVED** [review]
+1 Looks good, should reduce the number of failures related to dependency retrieval issues.

**Comment by exceptionfactory** [comment]
@joewitt Minor note, it looks like the PR title has the incorrect Jira issue number, it should be NIFI-8350 in order for the PR to be linked.

**Pull request closed without merging**
