### PR TITLE
NIFI-4575 Added ability to convert from a date to a timestamp within …

### PR DESCRIPTION
**Pull request by MikeThomsen**
…the record API.

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by MikeThomsen** [comment]
@mattyb149 do you think you could take a look at this? It's only a 3 line change to one of the conversion APIs in the Record API package. The scenario where it came up was Mongo's client API returns a java.util.Date object for dates and to convert a Mongo date to a Record API timestamp field, I had to enable a conversion of java.util.Date to a java.sql.Timestamp.

**Comment by MikeThomsen** [comment]
@m-hogue Since you have done a lot with the record api, could take you a look at this? It's only a few lines.

**Comment by mattyb149** [comment]
Reviewing...

**Comment by mattyb149** [comment]
+1 LGTM, ran a full build with contrib-check, tested with a MongoDBLookupService, verified that the error occurs when retrieving a Date field, but is successfully converted with this fix. Thanks for the improvement! Merging to master

**Pull request closed without merging**
