### PR TITLE
NIFI-3112 Revert "NIFI-2199 - allows nifi.sh restart through ssh"

### PR DESCRIPTION
**Pull request by JPercivall**
This reverts commit 88d125137e3bf3faf80b522edf5cf14f99419d60.

### CODE REVIEW

**Comment by alopresto** [comment]
Reviewing...

**Comment by trixpan** [comment]
Joe, Andy,  I am away from my dev station but assuming both "ssh host.name service nifi restart",  "ssh host.name /path/to/nifi/bin/nifi.sh restart" continue working I would imagine nobody will miss the redirection. If those stop working we will have to try to find a solution as both approaches tend to be used by puppet, ansible, etc

**Comment by JPercivall** [comment]
@trixpan I have not tried as a service since the original ticket didn't mention it. That said without redirection the nifi.sh call would hang because the bootstrap is still running. If you redirect stdout and stderr in the ssh call (like in the command I put on the ticket) it works as expected.

**Comment by alopresto** [comment]
Ok, ran `contrib-check`, all tests, etc. even though this change didn't affect them. Built the application and intentionally introduced an invalid property value to `nifi.properties` to reproduce. On bootstrap startup via `./bin/nifi.sh start`, the errors were correctly propagated to `logs/nifi-app.log`. I resolved the invalid property and restarted successfully. 

+1, merged.

**Pull request closed without merging**
