### PR TITLE
NIFI-4250 - Elasticsearch 5 delete processor

### PR DESCRIPTION
**Pull request by mans2singh**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [x] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by mans2singh** [comment]
Hey Folks:

The travis-ci build is failing (? timing out) with the error included below.  Can someone let me know how to resolve this ?  

Thanks

```Output file /home/travis/build/apache/nifi/nifi-commons/nifi-expression-language/target/generated-sources/antlr3/org/apache/nifi/attribute/expression/language/antlr/AttributeExpressionLexer.java does not exist: must build /home/travis/build/apache/nifi/nifi-commons/nifi-expression-language/src/main/antlr3/org/apache/nifi/attribute/expression/language/antlr/AttributeExpressionLexer.g
org/apache/nifi/attribute/expression/language/antlr/AttributeExpressionLexer.g
Output file /home/travis/build/apache/nifi/nifi-commons/nifi-expression-language/target/generated-sources/antlr3/org/apache/nifi/attribute/expression/language/antlr/AttributeExpressionParser.java does not exist: must build /home/travis/build/apache/nifi/nifi-commons/nifi-expression-language/src/main/antlr3/org/apache/nifi/attribute/expression/language/antlr/AttributeExpressionParser.g
org/apache/nifi/attribute/expression/language/antlr/AttributeExpressionParser.g


No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

**Comment by mans2singh** [comment]
Hey Folks:

Let me know if you have any feedback/recommends for this processor.

Thanks

Mans

**Comment by mattyb149** [comment]
Don't worry about the ANTLR stuff, that seems to trip up Travis sometimes. I can review this either this weekend or early next week. One quick question is whether you think it would be too confusing for the user to just add "delete" as an operation to PutElasticsearch(5), it would require doc updates and such. I'm just thinking that after one version of a Delete ES processor is available, the rest would be desired, requested, and possibly implemented. If that were the case, would it be better to have 3 new processors for delete, or to update the 3 Put processors to accept delete? I'm not leaning one way or the other, I'm interested in your thoughts and others' in order to provide the best user experience.

**Comment by mans2singh** [comment]
@mattyb149 

Regarding having a separate delete processor - I prefer single responsibility principle since it avoids confusion and mixing up configuration, processing logic, error handling, testing, maintenance etc.  Along the same lines ElasticSearch provides separate JAVA delete/put/get request builders.  Besides, overloading put and delete is confusing to me from the REST semantics.

Let me know your thoughts.

**Comment by mattyb149** [comment]
Makes sense to me, plus once the Extension Registry is in place, that might be the right spot for additional delete ES processors etc. I will review this for inclusion, thanks in advance!

**Comment by mans2singh** [comment]
@mattyb149 - Please let me know if you have any comments/recommendations on this processor.  Thanks.

**Comment by mattyb149** [comment]
+1 LGTM, ran the build and tests, and tried a flow with various conditions (success, not found, failure), everything works well.  Thanks for the contribution!  Merging to master

**Comment by mans2singh** [comment]
Thanks @mattyb149

**Pull request closed without merging**
