### PR TITLE
NIFI-4031: Allow nullable arrays

### PR DESCRIPTION
**Pull request by champagst**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by markap14** [comment]
Will Review...

**Comment by markap14** [comment]
Hey @champagst sorry for the delay in getting this reviewed. I think the solution that you provided here will work for this use case, but I'm a little bit concerned with this approach. I say that because if a field has a type of ARRAY, then the object should be array, not a List. Avro, however, comes with some oddities, and so in the AvroTypeUtil class, there is a method named isCompatibleDataType(). It checks if the "avro form" of an object is compatible with a given data type. So I think this is where we should add this logic. Adding it to DataTypeUtils may result in a different writer expecting an array but getting a List object. If we instead just update AvroTypeUtil#isCompatibleDataType to allow for a List in the case of Arrays, then I think we will still have the desired outcome but will prevent passing List objects around generically for ARRAY data types. Does that make sense?

**Comment by champagst** [comment]
Ah, yeah, that does make sense. I will make the change. Thanks for the feedback! 

I had messed up my fork after I submitted this and decided to start from scratch, so it might come in as a new pull request. Sorry for any inconvenience.

**Comment by alopresto** [comment]
@champagst , as you have made a new PR, can you please mark this one as closed? Thank you.

**Pull request closed without merging**
