### PR TITLE
NIFI-12765 Remove Apache Ranger modules

### PR DESCRIPTION
**Pull request by exceptionfactory**
# Summary

[NIFI-12765](https://issues.apache.org/jira/browse/NIFI-12765) Removes Apache Ranger modules from NiFi and NiFi Registry based on incompatibilities with Jetty 12 and related libraries.

Ranger libraries depend on Jetty 9, which was marked as End of Community Support in 2022. Although Jetty 10 and 11 provided some level of compatibility with earlier versions, both of those versions of End of Community Support as of January 2024.

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X] Pull Request based on current revision of the `main` branch
- [X] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [X] Build completed using `mvn clean install -P contrib-check`
  - [X] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by pvillard31 — CHANGES_REQUESTED** [review]
https://github.com/apache/nifi/blob/main/nifi-assembly/src/main/assembly/ranger.xml

**Comment by exceptionfactory** [comment]
> https://github.com/apache/nifi/blob/main/nifi-assembly/src/main/assembly/ranger.xml

@pvillard31 is there something particular about calling out this assembly descriptor file? It is part of the optional build for Ranger, so it should no longer be needed, but perhaps I am missing something.

**Comment by pvillard31** [comment]
My apologies @exceptionfactory - I did the review on my phone and that was obviously stupid. My comment was because I thought you missed the removal of that file but it's not the case now that I look at it on my laptop... My bad. It LGTM as is.

**Comment by exceptionfactory** [comment]
> My apologies @exceptionfactory - I did the review on my phone and that was obviously stupid. My comment was because I thought you missed the removal of that file but it's not the case now that I look at it on my laptop... My bad. It LGTM as is.

No problem, thanks for clarifying!

**Comment by exceptionfactory** [comment]
Rebased

**Pull request closed without merging**
