### PR TITLE
NIFI-3388 Add encrypted content repository implementation

### PR DESCRIPTION
**Pull request by alopresto**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Allows users to configure and use an encrypted content repository to further protect flowfile content when it is persisted on disk._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [x] Have you written or updated unit tests to verify your changes?
- [x] Have you verified that the full build is successful on both JDK 8 and JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by joewitt** [comment]
@alopresto this is super exciting.  Can you please tackle checkstyle.  Also can you describe what testing steps you've already taken?

**Comment by joewitt** [comment]
also pelase squash this thing so if we have review cycles we can go from there

**Comment by alopresto** [comment]
* Squashed initial commit. 
* Fixed checkstyle issue. 
* Fixed test failure due to error message change. 
* Built on Java 8 and Java 11. 

Existing testing:
* Unit tests for cryptographic operations
* Unit tests for streaming behavior
* Smoke tested with various processors generating and retrieving content from encrypted content repository
* Tested disk space exhaustion (see below)

Disk space exhaustion test:
1. Configured content repo to use space-limited disk (100 MB)
2. Created flow (`GenerateFlowFile` -> `LogAttribute`) to generate arbitrary data and log it
3. Verified that after ~ 100 MB, the `GenerateFlowFile` processor got error bulletins complaining about no available disk space
4. Verified stack trace present in `nifi-app.log`
5. Verified that content repository still encrypted
6. Verified that data provenance (for content claims still in repository) allowed viewing of plaintext content
7. Verified other normal operation of NiFi application
8. Verified shutting down NiFi, deleting content repository directory, and restarting NiFi resolves issue

**Comment by joewitt** [comment]
@alopresto Things are looking good. And I'll be spending more time on it.  But what strikes me is that this is now the content repo.  We already have provenance repo.  There is another PR from troy related to flowfile repo encryption.  I think if this content repo one is ready we should incorporate it and flag/mark both it and provenance as experimental and indicate they could change at anytime.  Their API, implementation, logic, etc.. and also that we're not yet positive of its behavior over long running flows in different environments and are not yet vouching for it being well done.  Do you agree?  If so can you update the docs for it to clearly call this out?  Ideally too we'd put a comment in the classes but that isn't necessary.

**Comment by alopresto** [comment]
Will add the tag to the classes and update the AG/UG docs.

**Comment by joewitt** [comment]
Cool.  Have also build on java11/osx.  Java8/linux.

**Comment by joewitt** [comment]
+1 will merge to master.

Given all the testing done, experimental flag, verified no apparent impact if unused, strong docs.  Will merge.  Once flow file repo encryption is merged we should rationalize how to most effectively configure all three and what range of testing we'll need to do before calling it ready.  We also do not provide default property entries for the content repo like we did for the encrypted provenance repo. 

Waiting on final clean build now with latest commits that landed in master.  If good will push
Also pushing/marking as NIFI-3834 rather than the parent JIRA NIFI-3388 so that we're showing progress on the right specific item.

**Pull request closed without merging**
