### PR TITLE
NIFI-4424 org.apache.nifi.NiFi does not allow programmatic access to …

### PR DESCRIPTION
**Pull request by peter-gergely-horvath**
This pull request adds support described in [NIFI-4424
org.apache.nifi.NiFi does not allow programmatic access to the NiFi engine](https://issues.apache.org/jira/browse/NIFI-4424)

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by joewitt** [comment]
@peter-gergely-horvath  please go into the file it references that lists the RAT issues and share what you're seeing.  The entire full clean build with contribution check should be perfectly clear and I run it often and it is.  But some folks are reporting issues like you're noting. 

Thanks

**Comment by peter-gergely-horvath** [comment]
@joewitt Apparently, RAT is complaining about some web files, so it is definitely not my change:


```
*****************************************************
Summary
-------
Generated at: 2017-09-26T15:51:59+02:00
Notes: 5
Binaries: 24
Archives: 0
Standards: 288

Apache Licensed: 277
Generated Documents: 0

JavaDocs are generated and so license header is optional
Generated files do not required license headers

11 Unknown Licenses

*******************************

Unapproved licenses:

  /Users/FOOBAR/Projects/OpenSource/nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/frontend/package.json
  /Users/FOOBAR/Projects/OpenSource/nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/fonts/flowfont/flowfont.css
  /Users/FOOBAR/Projects/OpenSource/nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/fonts/flowfont/flowfont.svg
  /Users/FOOBAR/Projects/OpenSource/nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/codemirror/addon/fold/foldgutter.css
  /Users/FOOBAR/Projects/OpenSource/nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/codemirror/addon/hint/show-hint.css
  /Users/FOOBAR/Projects/OpenSource/nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/codemirror/addon/lint/json-lint.js
  /Users/FOOBAR/Projects/OpenSource/nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/codemirror/addon/lint/lint.css
  /Users/FOOBAR/Projects/OpenSource/nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/codemirror/addon/lint/lint.js
  /Users/FOOBAR/Projects/OpenSource/nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/codemirror/lib/codemirror-compressed.js
  /Users/FOOBAR/Projects/OpenSource/nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/codemirror/lib/codemirror.css
  /Users/FOOBAR/Projects/OpenSource/nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/jquery/jquery.base64.js

*******************************
```

If that helps the investigation, I can send a more detailed extract of the build in private.

**Comment by joewitt** [comment]
@peter-gergely-horvath I've seen RAT complaints on files that are no longer part of the actual source repository.  I run 'git clean -fxd' to get to a very clean/repo intended state but this can remove temp files and things folks need for their IDE.  Could you please verify this is happening on a fresh/updated repo and that these aren't just files that were lying after rebases/etc..

**Comment by peter-gergely-horvath** [comment]
I've just ran a build with `mvn -Pcontrib-check clean install `and it **completed successfully**.

Apparently this, issue was indeed caused by some stale local files. Really confusing....

**Pull request closed without merging**
