### PR TITLE
NIFI-3556 - ValidateCSV - fixed schema parsing when ending by Null op…

### PR DESCRIPTION
**Pull request by pvillard31**
…erator

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [X] Have you written or updated unit tests to verify your changes?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by jvwing** [comment]
Reviewing...

**Comment by jvwing** [comment]
@pvillard31, this PR looks pretty good to me:

* Passes full build with contrib-check
* Unit test exercises the schema parsing issue
* Processor change fixes the schema parsing issue

One thing I would mention is that the unit test captures the complete context of the user experience from Jinli Liang, but it is more than necessary for the underlying issue.  A smaller unit test would still cover the issue and be clearer about the focus:

    @Test
    public void testParseSchemaCommaBoundary() {
        final TestRunner runner = TestRunners.newTestRunner(new ValidateCsv());
        runner.setProperty(ValidateCsv.SCHEMA, "Null(),Null");
        runner.assertValid();
    }
    
What do you think?

**Comment by pvillard31** [comment]
Hey @jvwing, thanks for the review! I agree with you, let me update the PR, should be OK in a minute.

**Comment by jvwing** [comment]
Looks great, @pvillard31, thanks for fixing this.

**Pull request closed without merging**
