### PR TITLE
NIFI-3759 - avro append for PutHDFS processor

### PR DESCRIPTION
**Pull request by jonashartwig**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ X ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ X ] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ X ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ X ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ X ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes? (there were no tests for append)
- [ X ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by trixpan** [comment]
@jonashartwig thank you for your contribution. 

I was looking at your code and was wondering if have you had a chance to see the put / fetch parquet @bbende submitted a few hours ago?

**Comment by jonashartwig** [comment]
hi, no I did not. why?

**Comment by trixpan** [comment]
Speed and overall project roadmap. 

The approach introduced there brings significant advantages to the use of PutHDFS.

https://github.com/apache/nifi/pull/1712

**Comment by jonashartwig** [comment]
I am sorry. I do not quite follow your latest comment.

**Comment by jonashartwig** [comment]
Hi, just to make sure: you want me to make a separate avro put processor?

**Comment by bbende** [comment]
@jonashartwig have you seen Joe's comment here? 
https://issues.apache.org/jira/browse/NIFI-3759?focusedCommentId=15988716&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15988716

**Comment by jonashartwig** [comment]
ah no, i did not. i did not get notifications :) thanks!

**Comment by jonashartwig** [comment]
closing this for inactivity

**Pull request closed without merging**
