### PR TITLE
LDAP - Configurable strategy to identify users

### PR DESCRIPTION
**Pull request by mcgilman**
NIFI-3020:
- Introducing a user identity strategy for identifying users.
- Fixing issue with the referral strategy error message.
- Adding code to shutdown the application when the authorizer or login identity provider are not initialized successfully.

### CODE REVIEW

**Comment by ijokarumawak** [comment]
Reviewing..

**Comment by mcgilman** [comment]
Good call. I've updated the Admin Guide in a second commit. Thanks @ijokarumawak!

**Comment by olegz** [comment]
I am +1 now. If @ijokarumawak has no issues let's merge

**Comment by ijokarumawak** [comment]
@mcgilman Thanks for updating the docs! Exception handling at shutdown looks good. +1
Would you squash the commits to get it merged?

**Comment by olegz** [comment]
@mcgilman @ijokarumawak squashing and merging

**Pull request closed without merging**
