### PR TITLE
NIFI-1131 renamed relationships

### PR DESCRIPTION
**Pull request by josephxsxn**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by josephxsxn** [comment]
Trival change in names didnt impact tests.

**Comment by joewitt** [comment]
@josephxsxn unfortunately making the change this way would be rather disruptive to existing flows.  We learned this lesson on PropertyDescriptor object and for that we added an additional characteristic called 'displayName'.  What I'm suggesting is we do the same for Relationship.

By adding a 'displayName' we can allow developers to change/tweak that over time whereas the 'name' cannot change once it is put out in a release unless the change is made during a major release cycle and even then we should try to minimize the frequency since it can make porting flows harder.

The bottom line is the 'name' is an important part of how we establish the persistent knowledge of a connection between two components.  If you look in the flow.xml.gz of a flow with a connection you'll see the 'relationship' and in it is the name of the source processors relationship used in that connection.  So, changing the 'name' breaks old flows.  We can instead add 'displayName' and now that value is what will show up in the UI but is not what is used for underlying persistence.  By default the displayName if not set will be whatever the name was (and vice versa) in the code just like PropertyDescriptor but over time the value of name and displayName can diverge and that will be ok provided the Relationship still means what it meant before.

I'll stop rambling.  Does this make sense?

**Comment by trixpan** [comment]
@josephxsxn  in light of Joe's comments, would you like to close this PR?

Cheers!

**Comment by josephxsxn** [comment]
Closed in light of Joes comments.

**Pull request closed without merging**
