### PR TITLE
NIFI-4424 org.apache.nifi.NiFi does not allow programmatic access to …

### PR DESCRIPTION
**Pull request by peter-gergely-horvath**
…the NiFi engine

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

Please note that the `mvn -Pcontrib-check clean install` failed with the following test case errororing out, which I believe to be a timing issue, that cannot be related to the change.
`testStateTooLargeExceptionThrownOnReplace(org.apache.nifi.controller.state.providers.zookeeper.TestZooKeeperStateProvider)  Time elapsed: 90.345 sec  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 20000 milliseconds`.

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by peter-gergely-horvath** [comment]
Hi @patricker, please let me know if there is anything that requires clarification or if there is any way I could help the review. I would love to see this pull request being merged.

**Comment by joewitt** [comment]
This looks fine to me (have a full clean build w/contrib check running but i expect it will be fine).  Travis-CI would probably work fine now too given all the improvements that have been made.

I am fine with this change personally though.  @markap14  and @alopresto as people that have worked on code in here please take a look and see if there is anything of concern.  Otherwise either @patricker or i will merge.  Thanks

**Comment by alopresto** [comment]
I don't see any breaking changes.

**Comment by peter-gergely-horvath** [comment]
@patricker, @joewitt Would it be possible for you to perform the merge? Based on my understanding, the changes have been approved by @alopresto.

I have some additional pull requests that depend on this one: it would be awesome to have this in the code base.

**Comment by alopresto** [comment]
@peter-gergely-horvath I will merge this today.

**Comment by alopresto** [comment]
Ran `contrib-check` and all tests pass. Fired up an instance of the application and it performed normally. +1, merging.

**Pull request closed without merging**
