### PR TITLE
NIFI-6385 Add option to penalize waiting FlowFiles

### PR DESCRIPTION
**Pull request by ijokarumawak**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

Added new 'Penalize Waiting FlowFiles' property to Wait processor. Please see property descriptor description for details on what it does.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [x] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by aramatev** [comment]
Are you sure this solves the Jira it refers to ? The title of the jira and description dont match the PR body description 
NIFI-6385
Wait processor ignores all FlowFiles except for the first one in the queue.

**Comment by aramatev** [comment]
@ijokarumawak , Are you sure this solves the Jira it refers to ? The title of the jira and description dont match the PR body description
NIFI-6385
Wait processor ignores all FlowFiles except for the first one in the queue.

**Comment by ijokarumawak** [comment]
@markap14 I was wondering if we should penalize the 'wait' relationship, too. But ended up adding a property.

The main reason is to avoid unexpected negative performance impact to existing flows.
We haven't penalized 'wait' relationship, and I imagine users left 'Penalize Duration' as the default value, which is '30 secs'. And what if we start penalizing it automatically?
When a FlowFile arrives at 10:30:30 and its signal is not notified yet, the FlowFile would be penalized. Then even if the signal is notified right after, like 10:30:31, the FlowFile won't be released until 10:31:00.
We could enable penalizing by default and write a migration guide to update 'Penalize Duration' to more adequate value, but I thought it will be a bad user experience.

Similar to that, not penalizing FlowFiles would provide the best latency to release a FlowFile when its signal arrive(processor works busier, though). And I think the current behavior may be expected in some context, that is, wait for the highest priority FlowFile to be released before any other FlowFiles even if their signal arrives.

**Comment by ijokarumawak** [comment]
@aramatev Yes, this PR addresses NIFI-6385. When a FlowFile is penalized, it won't be processed again until configured 'Penalized Duration' passes, 30 secs by default.

So, if there are two FlowFiles attributed with `signal=a, priority=1` and `signal=b, priority=2` queued at 'wait' relationship which has PriorityPrioritizer, and signal `b` is notified, Wait processor checks `signal=a, priority=1` FlowFile first because it's higher priority, but signal `a` is not notified, then the FlowFile is penalized. At the next Wait processor run, `signal=b, priority=2` FlowFile get processed by Wait processor, and be released. Because signal `b` is already notified.

I believe that addresses the use-case described by the JIRA. Am I missing something?

**Comment by aramatev** [comment]
image

The Jira should really state that not all prioritizers incorrectly look at the front of the queue. 
When using FirstInFirstOutPrioritizer, the Wait processor is able to look at the entirety of the queue and process the signal. 
But for all other prioritizers, for some reason only the first flowfile in the queue is evaluated against the current signal. 

So its not that all prioritizers are broken, FIFO works fine, the others dont. And FIFO works w/o penalizing the flowfile in the front. This solution actually seems a bit of a hack, since it doesnt match the signal and its sent to the back of the queue. 
I'd be interested to know why the entire queue is not available to all priortizers but only FIFO sees the entire queue and can process any signal that matches any flowfiles in its queue.

**Comment by ijokarumawak** [comment]
Hi @aramatev let me try to explain.

Wait processor only processes one signal per run, regardless of what Prioritizer is used. FIFO passes the First-In FlowFile to Wait processor. PriorityPrioritizer passes the most priority FlowFile. It's not like 'With FIFO, entire queue can be processed by Wait processor', it's more like 'With FIFO, each queued FlowFile can be processed by Wait processor one by one at each scheduled run'. Wait processor runs at every configured 'Run Schedule' ('0 ms' by default, which means the processor keeps running if there's a thread available).

The reason why FIFO works is that when Wait processor route a FlowFile to 'wait' relationship, the FlowFile is added at the end of the queue. Then the next FlowFile is processed at the next Wait processor run.

With PriorityPrioritizer, the same FlowFile is processed again and again, because that is the most priority one.

Actually all Prioritizer sees entire queue. I don't think this is an issue on Prioritizer implementations.

If you have alternative solutions, I'd be interested in hearing that. This PR is just one of many possible approaches. Thanks!

**Comment by aramatev** [comment]
That actually makes sense. 

So if one was to set 0 ms Penalty using the other prioritizers. Would we see the same behavior  as with FIFO ? 
Maybe 0ms wouldn't work, so 1 ms for Penalty with this Patch to get similar behavior as the '0 ms' run schedule using FIFO?

**Comment by ijokarumawak** [comment]
@aramatev Glad to know we are on the same page.

It will work with any Prioritizer as long as `Penalty Duration > Run Schedule` and a thread is available. One caveat hear, NiFi has a thread pool for running each Processors (Maximum Timer Driven Thread Count, 10 by default). Wait processor may have longer interval than configured 'Run Schedule' if it has to wait for acquiring a thread.

I'm wondering what is the purpose of using Prioritizers other than FIFO for Wait processor in your use case. Would you elaborate some situations that FIFO alone won't work?
You could use FIFO at 'wait' relationship without penalizing if you'd like to release FlowFiles as fast as its signal is notified. Then use PriorityPrioritizer at the 'success' relationship to control processing order at the next processor.

**Comment by aramatev** [comment]
I suppose that Prioritizer at the success relationship level could work for some scenarios. 

But if we're setting releasableFlowFileCount =1, then only 1 item would match our signal and fall and we're already consume it, its not like we request for signal =aa, twice and then we only use the flowfile with higher priority. 

The situation that your solution doesnt solve is if we have several signals with same id with different priorities.

Say you have these 2 in your queue, and you send a Notify for signal=a.
signal=a, priority=2 and signal=a, priority=1, 
You'd incorrectly get the signal=a with priority=2 out, and youd already consume that, and it would be too late to have them wait in another success relationship to get sorted out.

**Comment by ijokarumawak** [comment]
@aramatev Thanks for the explanation. That makes sense. You're right, Penalizing FlowFiles won't help in that case.

So, what needed is an ordering mechanism something like 'order by priority attribute grouped by signal id'.
That is actually difficult to address at NiFi framework layer such as Prioritizers or Penalization. We need more coding at Wait processor.

My idea is:
- Add internal state at Wait to track when each signal.id is checked
- Add a Wait processor property to specify signal.id re-check duration
    - Similar to what 'Penalty Duration' does, but not for per FlowFile, but for signal.id unit. This is required because if there are multiple signal.ids, 'aa' and 'bb', then each signal.id has multiple FlowFiles with different priority. When Wait processor checks signal.id 'aa' and found 'aa' is not notified yet, it needs to check 'bb' at the next run
    - `0 ms` by default
- Add FlowFile filtering at Wait processor using above data to decide which signal.id to check

I will implement that and update this PR later. Thanks!

**Comment by ijokarumawak** [comment]
Closing this PR as Penalization per FlowFile doesn't address the target issue.
I've submit another PR with a different approach. #3540

**Pull request closed without merging**
