### PR TITLE
NIFI 7525 - Create a nullValue() Subjectless Functions and support null type on Expression Language

### PR DESCRIPTION
**Pull request by Fabryprog**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Enables NIFI-7525 functionality_

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [X] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [X] Have you written or updated unit tests to verify your changes?
- [X] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [x] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [x] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [X] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by Fabryprog** [comment]
Note: **ci-workflow** failed in other modules. I modified only **nifi-expression-language**

**Comment by Fabryprog** [comment]
Hello friend @adarmiento @mgaido91 

How to about that?

**Comment by mgaido91** [comment]
I don't see the usefulness of such a method and I am not sure it is worth the big code change, sorry

**Comment by Fabryprog** [comment]
> I don't see the usefulness of such a method and I am not sure it is worth the big code change, sorry

Hello Marco! Thanks for your time!

In the past I've been use NiFi for some data trasformations and, sometime, some automatical conversions (for example from JSON -> Avro) wasn't compatible with the "empty value filosofy" used inside NiFi. For example: When I have an empty value: what is it? Is it a string? is a number? It could be a "null" values?

This change skips this misunderstanding enabling the user to use programmatically NULL value (inside of expression language)

if you think it's better, I can create an article to expose that!

Kind regards

**Comment by mgaido91** [comment]
I think you can maybe send an email in the community list to check whether this is a feature many people need and in case of a favorable result we can go ahead with the PR. Thanks.

**Comment by adarmiento** [comment]
Hello @Fabryprog, 
Whatever the outcome of the discussion with the community, I would undersline that you are not actually interested in the null value itself (if I understood correctly) but rather in propagating the type a field which is null for a specific in-transit object

**Pull request closed without merging**
