### PR TITLE
NIFI-4169: Enhance PutWebSocket error handling

### PR DESCRIPTION
**Pull request by ijokarumawak**
**NOTE**
Submitting this PR just for code review purpose. Not ready to be merged yet.

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by ijokarumawak** [comment]
This PR is now ready to get reviewed.

A flow template is available here for testing both NiFi as a WebSocket client and server.
https://gist.github.com/ijokarumawak/f36668b193bc413da3e0d968bb6b47c1

This PR is based on the contribution from Y Wikander. 

- Added "Fork Failed Broadcast Sessions" property to specify whether
  failed FlowFiles should be forked and transferred individually so that
  user can construct a error handling flow using each session id.
- Added "Enable Detailed Failure Relationships" property to separate
  failure routes into more detailed ones, such as 'no connected sessions'
  or 'communication failure'
- Added "websocket.broadcast.succeeded" and "websocket.broadcast.failed"
  attributes to outgoing FlowFiles when a message is broadcast.

**Comment by EmilioCC** [comment]
Would be nice to have this included in the next release.

**Comment by alopresto** [comment]
Unfortunately there are branch conflicts which will require some attention as well as performing an actual review. As the next release candidate is probably being cut as we speak, this will not make it in to 1.9.0.

**Comment by EmilioCC** [comment]
Let's say I resolve the merge conflict, who will perform the actual review? This is an old pull request. It might get other conflicts in the 2 next years.

**Comment by joewitt** [comment]
The merge conflict looks pretty easy to resolve.  What is often harder is finding someone to review it.  Reviews do not have to be done by a committer - it only requires a committer to do the final merge.  You volunteering to do a test/review would be most valuable.

**Comment by EmilioCC** [comment]
It would be my first time contributing to NiFi. Actually it would be the first time I contribute to an ASF project. Is the process of reviewing really what is explained here https://cwiki.apache.org/confluence/display/NIFI/Contributor+Guide#ContributorGuide-CodeReviewProcess ? I would need a bit of guidance if it's not what you guys actually do.

**Comment by ijokarumawak** [comment]
@EmilioCC Thanks for your interest for this PR and excuse my slow response. I've rebased this PR with the latest master to resolve conflicts. (I hope you haven't tried it yourself yet..)
If you have time, please review the changes.

Actually, this change has originally initiated by Y Wikander a year ago. And I added additional commit while I was reviewing that.
I haven't merged this because I haven't got +1 from anyone else.
If you can give your +1, then I will merge this. Thanks!

**Comment by EmilioCC** [comment]
@ijokarumawak I'll review it first and look at the failing tests. It looks like you have few tests that are failing for those new changes. I'll give you my +1 soon!

**Comment by ijokarumawak** [comment]
@EmilioCC Updated the failing tests. Thanks!

**Comment by ijokarumawak** [comment]
Hi @EmilioCC, just wanted to check if there's any issue to test this PR. Hope everything is working fine for you. Thanks!

**Pull request closed without merging**
