### PR TITLE
NIFI-10576 - ParquetRecordSetWriter doesn't write avro schema to attribute

### PR DESCRIPTION
**Pull request by thenatog**
# Summary

[NiFi-10576](https://issues.apache.org/jira/browse/NiFi-10576)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NiFi-10576`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NiFi-10576`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 8
  - [x] JDK 11
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by mattyb149** [comment]
Looks good. Is there any way to add a unit test for this?

**Review by exceptionfactory — COMMENTED** [review]
Thanks for working on this @thenatog. I updated the `TestParquetRecordSetWriter` to include an optional setting for writing the schema name in one test method, which verifies the changes. Planning to merge pending a successful build.

**Comment by thenatog** [comment]
Thanks, if the avro.schema attribute is coming through on flowfiles coming out of the runner, then that sounds good to me. The simplest test would be to see that the attributes are now returned from the method I added, but I noticed that at run time it didn't come through until I added a schema cache service. Entirely possible I didn't understand how the schemas worked, and that setting it to use schema name(?) should work.

**Review by exceptionfactory — APPROVED** [review]
Thanks @thenatog, the default behavior does not necessarily return any attributes, so that's why I extended the current unit test to specific the Schema Write Strategy. As there is no direct test class for `WriteParquetResult`, the changes to `TestParquetRecordSetWriter` exercise the changes. +1 merging

**Pull request closed without merging**
