### PR TITLE
NIFI-13211: Decoupling other UIs from exiting NiFi UI

### PR DESCRIPTION
**Pull request by mcgilman**
NIFI-13211:

NiFi is comprised of numerous UIs that all get deployed at start up. These UIs piggybacked on some shared stylesheets, components, and dependencies by directly loading them through a relative path. In preparation for moving away from the existing UI, these UIs are being updated to bundle these items directly. In time, these UIs will all be modernized as well so this is just a transitional step in that process.

### CODE REVIEW

**Comment by rfellows** [comment]
will review...

**Review by exceptionfactory — COMMENTED** [review]
Quick note regarding license checking, the following two files were flagged as missing the standard license header:

```
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-content-viewer/src/main/webapp/fonts/flowfont/flowfont.svg
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-content-viewer/src/main/webapp/fonts/flowfont/flowfont.css
```

**Comment by mcgilman** [comment]
> the following two files were flagged as missing the standard license header

Thanks @exceptionfactory. I see I have some `rat` config that needs updating. New commit coming shortly.

**Review by rfellows — APPROVED** [review]
Looks good. This sets nifi up to start to transition to the new UI exclusively.

**Pull request merged**
