### PR TITLE
NIFI-2631: Adding 'Commit Mode' and 'Use Versions' to ListS3

### PR DESCRIPTION
**Pull request by gresockj**

### CODE REVIEW

**Comment by jvwing** [comment]
@gresockj, would it be OK if we review/polish this PR first and leave the 0.x PR #916 unit we're finished?  I don't want you to have to duplicate effort -- I believe the branches are fairly similar with respect to ListS3, and it may be as simple as just merging twice when we're finished.  Does that match what you've experienced on the two branches so far?

**Comment by gresockj** [comment]
Sounds good, I believe ListS3 is the same on both branches, so finishing this PR first should work.

**Comment by jvwing** [comment]
Build with contrib-check passes OK.  The TravisCI failure was from memory ("GC overhead limit exceeded"), not code issues.  All of my manual testing went well, both with and without versioning.  The code quality looks very good.

One small thing -- the integration test ITListS3::testGetPropertyDescriptors fails due to the new property descriptors.  Would you please update that test?  Also, what would you think about a test or two for the versioning feature?  Even if you copy/pasted one of the existing integration tests and added `runner.setProperty(ListS3.USE_VERSIONS, "true");`, running it against the non-version-enabled bucket, it would still exercise the S3VersionBucketLister code paths.

**Comment by gresockj** [comment]
ITListS3 idea sounds good, I'll work on it when I get a chance.

**Comment by gresockj** [comment]
Hmm, so this is strange.  I was testing ListS3 out in NiFi today and I noticed that I cannot see the state in the View State window.  However, the processor behaves as if the state is being persisted (i.e., it won't list any flow files until I actually put another object in the bucket).  However, other processors allow me to see the state in the View State window.  I'm positive I was able to see this state when I initially tested the processor in NiFi, but I can't think of what might have changed.  Have you experienced this at all, @jvwing?

**Comment by jvwing** [comment]
@gresockj No, I have not noticed that, and I've been viewing and clearing the state along with my testing.  Are there javascript errors in your browser? Are you familiar with browser debugging tools?  When you open the state dialog, there should be an XHR call to the server to get this state information, something like:

http://localhost:8080/nifi-api/processors/dc5e91e6-0156-1000-ef9e-9d07ae89516c/state

And this returns JSON with the state in it.  Can you check if that query is being run, and if it is failing or returning nothing?

**Comment by gresockj** [comment]
Yes, it's requesting this:
https://localhost:8443/nifi-api/controller/process-groups/66ef7ae5-4bdb-4c50-9811-429be759f6fb/processors/7738f82e-d185-3931-a98e-c1156cd21cbc/state

totalEntryCount is 0 for both clusterState and localState

**Comment by jvwing** [comment]
Are you running a cluster?  I have so far tested only a standalone instance.

**Comment by gresockj** [comment]
Yeah, I'm on a cluster.  I'll keep digging.

**Comment by jvwing** [comment]
I tried a simple cluster running in a docker container, and state seemed to work just fine.  I tested ListS3 running both on the primary node only and across the cluster nodes.  The state API json reflected clustered state in both cases.

**Comment by gresockj** [comment]
Thanks for checking that out, gives me some more confidence that it's unrelated to this.  For now I'll proceed with the ITListS3 tests when I get a chance.

**Comment by jvwing** [comment]
Thanks for the test upgrades, @gresockj, they look good.  I will merge shortly.

**Pull request closed without merging**
