### PR TITLE
NIFI-10520 Upgrade hazelcast to 4.2.5

### PR DESCRIPTION
**Pull request by mr1716**
# Summary

[NIFI-10520](https://issues.apache.org/jira/browse/NIFI-10520)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI-10520) issue created

### Pull Request Tracking

- [X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X] Pull Request based on current revision of the `main` branch
- [X] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [X] JDK 8
  - [X] JDK 11
  - [X] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by mr1716** [comment]
This ran successfully when I ran it in my local branch. Might need to rerun the failed jobs

**Comment by mr1716** [comment]
@exceptionfactory this is the pull request which was discussed. Wanted to let you know, so you're aware of it.

**Comment by mattyb149** [comment]
+1 LGTM, went through the release notes and noted no backwards incompatibilities. Please note that your commits in the future should start with the Jira case number and have a description about why you changed a file, not the file that was changed. I've updated this one before merging, just wanted to make you aware.

Thanks for the upgrade! Merging to main

**Comment by mr1716** [comment]
@mattyb149 Thanks. Much appreciated. Will make note for future work. I did put the JIRA case number here and did add a reason for the change in the JIRA case, but will add that here.

**Pull request closed without merging**
