### PR TITLE
UI - Verifying permissions prior to checking Remote Process Group transmission status

### PR DESCRIPTION
**Pull request by mcgilman**
NIFI-3023:
- Verifying permissions prior to checking Remote Process Group transmission status.

### CODE REVIEW

**Comment by scottyaslan** [comment]
Reviewing....

**Comment by scottyaslan** [comment]
The proposed changes look good and prevent the app from throwing an error when the user does not have permissions to read the remote process group. However, I noticed that the 'transmitting' and 'not-transmitting' classes are being applied even when the remote process group is 'invalid'. This is causing the warning icon fill color to be overridden to #728e9b instead of the #cf9f5d. Could you please add a check for invalid state when applying the 'transmitting' and 'not-transmitting' class?

**Comment by mcgilman** [comment]
Will do. Thanks!

**Comment by scottyaslan** [comment]
Thanks @mcgilman this has been merged to master.

**Pull request closed without merging**
