### PR TITLE
NIFI-6105: Fix handling of arrays of records/maps in record utilities

### PR DESCRIPTION
**Pull request by mattyb149**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by ijokarumawak** [comment]
@mattyb149 Thanks for the fix! I reviewed and tested the PR, and wanted to discuss about the change a bit.

As a summary, here are the key points:
1. The reported issue at StackOverflow has been addressed by other changes since NiFI 1.9.0.
2. But the same flow doesn't work well with schema inference, conversion result has `null` elements.
3. To fix no.2 (I assume), this PR modifies DataTypeUtils.isCompatibleDataType. However, I suggest fixing DataTypeUtils.toRecord method instead. DataTypeUtils.toRecord converts Java Map to MapRecord before isCompatibleDataType is called, but it doesn't do so recursively. https://github.com/apache/nifi/blob/master/nifi-commons/nifi-record/src/main/java/org/apache/nifi/serialization/record/util/DataTypeUtils.java#L302

I may be wrong about above analysis.. How do you think?

Please refer followings for details.

---
Details:

I've tested the Stackoverflow questions flow with NiFi 1.8.0 and I got the reported exception:
```
2019-03-07 16:51:40,061 ERROR [Timer-Driven Process Thread-6] o.a.n.p.jolt.record.JoltTransformRecord JoltTransformRecord[id=72a28625-3c23-3bc6-73cd-c06d247bf8dc] Unable to write transformed records StandardFlowFileRecord[uuid=c8b59dad-ff78-4c49-898b-9ac6923eb94c,claim=StandardContentClaim [resourceClaim=StandardResourceClaim[id=1551945098069-1, container=default, section=1], offset=0, length=873],offset=0,name=c8b59dad-ff78-4c49-898b-9ac6923eb94c,size=873] due to org.apache.nifi.serialization.record.util.IllegalTypeConversionException: Cannot convert value of class [Ljava.lang.Object; because the type is not supported: org.apache.nifi.serialization.record.util.IllegalTypeConversionException: Cannot convert value of class [Ljava.lang.Object; because the type is not supported
org.apache.nifi.serialization.record.util.IllegalTypeConversionException: Cannot convert value of class [Ljava.lang.Object; because the type is not supported
        at org.apache.nifi.serialization.record.util.DataTypeUtils.convertRecordFieldtoObject(DataTypeUtils.java:460)
        at org.apache.nifi.serialization.record.util.DataTypeUtils.convertRecordMapToJavaMap(DataTypeUtils.java:472)
        at org.apache.nifi.serialization.record.util.DataTypeUtils.convertRecordFieldtoObject(DataTypeUtils.java:444)
        at org.apache.nifi.processors.jolt.record.JoltTransformRecord.onTrigger(JoltTransformRecord.java:318)
```

However, the flow works fine with NiFi 1.9.0 which has been released recently.
So, the reported issue at Stackoverflow has been fixed by different commit.

Further testing, I found that with NiFi 1.10.0 snapshot master branch, if I used schema inference, result becomes null like this:
Before applying this fix, conversion result was:
```
[{"DataItems":[null,null,null,null]}]
```
This happened because the output data type was not found for the inferred Choice[Record, Record] was not compatible with the Java Map type. I assume that's why you fixed isCompatibleDataType method.
https://github.com/apache/nifi/blob/master/nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/json/WriteJsonResult.java#L284


Although I got the expected result with this fix even with schema inference, I think it's more appropriate to fix DataTypeUtils.toRecord method, instead of isCompatibleDataType.
Specifically, following linked line should convert java Map type to MapRecord recursively. Then isCompatibleDataType didn't have to be modified.
https://github.com/apache/nifi/blob/master/nifi-commons/nifi-record/src/main/java/org/apache/nifi/serialization/record/util/DataTypeUtils.java#L302

**Comment by mattyb149** [comment]
Makes sense to me, I'll take a look at the toRecord() method, you are right that I fixed isCompatibleDataType because that's where I got to in the debugging where the record choice returned not compatible when given a Map.

**Comment by bbende** [comment]
@mattyb149 @ijokarumawak I ran this branch against the schemas and data in the stackoverflow questions and got the below error..
```

org.apache.nifi.serialization.record.util.IllegalTypeConversionException: Cannot convert value [{uuid=MFMS1-MC5, componentId=path1, eventType=Samples, type=PathFeedrate, dataItemId=pf, timestamp=2019-03-01T21:48:27.940558Z, sequence=68104, value=425.5333, name=Fact, subType=ACTUAL, sampleRate=null, statistic=null, duration=null, sampleCount=null, compositionId=null, resetTriggered=null}] of type class java.util.LinkedHashMap for field a to any of the following available Sub-Types for a Choice: [RECORD, RECORD]
	at org.apache.nifi.serialization.record.util.DataTypeUtils.convertType(DataTypeUtils.java:185)
	at org.apache.nifi.serialization.record.util.DataTypeUtils.convertType(DataTypeUtils.java:101)
	at org.apache.nifi.serialization.record.util.DataTypeUtils.convertType(DataTypeUtils.java:97)
	at org.apache.nifi.serialization.record.util.DataTypeUtils.convertType(DataTypeUtils.java:165)
	at org.apache.nifi.serialization.record.util.DataTypeUtils.convertType(DataTypeUtils.java:101)
	at org.apache.nifi.serialization.record.util.DataTypeUtils.toRecord(DataTypeUtils.java:388)
	at org.apache.nifi.serialization.record.util.DataTypeUtils.toRecord(DataTypeUtils.java:329)
	at org.apache.nifi.processors.jolt.record.JoltTransformRecord.transform(JoltTransformRecord.java:390)
	at org.apache.nifi.processors.jolt.record.JoltTransformRecord.onTrigger(JoltTransformRecord.java:333)
	at org.apache.nifi.processor.AbstractProcessor.onTrigger(AbstractProcessor.java:27)
	at org.apache.nifi.controller.StandardProcessorNode.onTrigger(StandardProcessorNode.java:1162)
	at org.apache.nifi.controller.tasks.ConnectableTask.invoke(ConnectableTask.java:205)
	at org.apache.nifi.controller.scheduling.TimerDrivenSchedulingAgent$1.run(TimerDrivenSchedulingAgent.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Seems like something is still not lining up.

**Comment by mattyb149** [comment]
Looks like we're still getting into the `isCompatibleDataType()` code, @ijokarumawak did I miss something in the `toRecord()` changes, or do I need to put the `isCompatibleDataType()` changes back in too? Seems like it shouldn't hurt by having it in there just in case, but I believe you were picturing something else with respect to the `toRecord()` changes.

**Comment by ijokarumawak** [comment]
Hi @mattyb149 @bbende 
Sorry for the confusion. I tested the issue again
1. With the latest master 1.10.0-SNAPSHOT
    1. With implicit input and output schemas, The reported issue still occurs.
        ```
        org.apache.nifi.serialization.record.util.IllegalTypeConversionException: Cannot convert value of class [Ljava.lang.Object; because the type is not supported
        ```
    2. But if I use infer-schema with the JsonTreeReader, the same flow works fine. I think this is why I misunderstood the issue is addressed with NiFi 1.9.0. Sorry about that.
2. With this PR, I got the same exception that Bryan saw:
    ```
    org.apache.nifi.serialization.record.util.IllegalTypeConversionException: Cannot convert value [{uuid=MFMS1-MC5, componentId=path1, eventType=Samples, type=PathFeedrate, dataItemId=pf, timestamp=2019-03-01T21:48:27.940558Z, sequence=68104, value=425.5333, name=Fact, subType=ACTUAL, sampleRate=null, statistic=null, duration=null, sampleCount=null, compositionId=null, resetTriggered=null}] of type class java.util.LinkedHashMap for field a to any of the following available Sub-Types for a Choice: [RECORD, RECORD]
    ```

I'll take a look on the exception and toRecord updates. Thanks!

**Comment by ijokarumawak** [comment]
Hi @mattyb149 
Sorry, you were right with the 1st commit, and I was wrong. I've submitted #3367 based on your 1st commit with my little refactoring. Please check [the comment](https://github.com/apache/nifi/pull/3367#issue-260631441) on the PR for detail.

**Pull request closed without merging**
