### PR TITLE
NIFI-8106 An "Are you sure?" prompt when deleting a PG

### PR DESCRIPTION
**Pull request by ahmedshaaban1999**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

NIFI-8106: Added an "Are you sure?" prompt when deleting a PG

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [x] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by exceptionfactory** [comment]
Thanks for your contribution @ahmedshaaban1999!  The JavaScript code appears to include a number of unrelated changes. Although your branch is based off the current main, can you take a closer look at the changes narrow down what is needed to implement the feature?

**Comment by ahmedshaaban1999** [comment]
Hi,
yeah sorry about that. To be honest I myself don't know what was all that about. I copied the file from the main branch and re-applied my changes and it seems that only the related parts of code changed so I guess we are good to go.

**Comment by exceptionfactory** [comment]
Thanks @ahmedshaaban1999, that looks much better!

**Comment by exceptionfactory** [comment]
@ahmedshaaban1999 The system-tests are unfortunately brittle on GitHub, so don't worry about those failures for now.  The main branch recently included an update to address the Ubuntu JDK 11 failure for maven-surefire-plugin, so it would be helpful to rebase once more to pull in those changes.

**Comment by ahmedshaaban1999** [comment]
I pulled the latest commits from main branch and tried `mvn package` on main branch itself and the surefire error is still there
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project nifi-stateless-processor-tests: There are test failures.`
Should I rebase and push a new commit ? or wait till this issue is fixed ?

**Comment by exceptionfactory** [comment]
The reference to `nifi-stateless-processor-tests` seems to indicate something else. I would go ahead and rebase.  Given that this is only one file changed, you could also take the opportunity to squash the two commits into one.

**Comment by ahmedshaaban1999** [comment]
well, it seems that I messed up the files while trying to squash the two commits. I will close this PR and create another one.

**Pull request closed without merging**
