### PR TITLE
NIFI-11587: Update questdb to 6.7

### PR DESCRIPTION
**Pull request by r-sidd**
# Summary

[NIFI-11587](https://issues.apache.org/jira/browse/NIFI-11587)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 11
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by r-sidd** [comment]
@pvillard31 @MikeThomsen @exceptionfactory can someone review this 🙂

**Comment by pvillard31** [comment]
@simonbence - you may be the best one to review this one

**Comment by exceptionfactory** [comment]
The version [6.7 Release Notes](https://github.com/questdb/questdb/releases/tag/6.7) do not highlight any breaking changes that would appear to impact project usage, so it looks like this should be good, but it would be helpful if @simonbence could confirm.

**Comment by r-sidd** [comment]
> The version [6.7 Release Notes](https://github.com/questdb/questdb/releases/tag/6.7) do not highlight any breaking changes that would appear to impact project usage, so it looks like this should be good, but it would be helpful if @simonbence could confirm.

Okay cool 🫡

**Comment by simonbence** [comment]
Thanks for mentioning! I did take a look and it looks good to me. I am not sure about why there is a breaking change there but based on the QuestDb repository it looks like intentional (However I find no mention in the release notes). I will wait up to tomorrow for seeing rollback with non-empty datasets and if everyhings look right, I will merge the PR.

**Comment by r-sidd** [comment]
> Thanks for mentioning! I did take a look and it looks good to me. I am not sure about why there is a breaking change there but based on the QuestDb repository it looks like intentional (However I find no mention in the release notes). I will wait up to tomorrow for seeing rollback with non-empty datasets and if everyhings look right, I will merge the PR.

Okay cool 🫡

**Comment by simonbence** [comment]
Just a FYI: I got confirmation on the QuestDB Slack that the expected behaviour with this changes is the same.

**Comment by simonbence** [comment]
The rollover did not produced any errors.

**Pull request closed without merging**
