### PR TITLE
NIFI-3940 upgraded to latest jruby which resolves an apparent lgpl bu…

### PR DESCRIPTION
**Pull request by joewitt**
…nding issue

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by joewitt** [comment]
isn't quite right yet.  Breaks a test.  I am not a ruby expert so phoning a friend.

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.446 sec - in org.apache.nifi.reporting.script.ScriptedReportingTaskGroovyTest

Results :

Failed tests:
  TestExecuteJRuby.testReadFlowFileContentAndStoreInFlowFileAttribute:52 java.lang.NoSuchFieldError: O_TMPFILE

**Comment by alopresto** [comment]
Taking a look.

**Comment by joewitt** [comment]
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.231 sec <<< FAILURE! - in org.apache.nifi.processors.script.TestExecuteJRuby
testReadFlowFileContentAndStoreInFlowFileAttribute(org.apache.nifi.processors.script.TestExecuteJRuby)  Time elapsed: 1.205 sec  <<< FAILURE!
java.lang.AssertionError: java.lang.NoSuchFieldError: O_TMPFILE
	at org.apache.nifi.util.StandardProcessorTestRunner.run(StandardProcessorTestRunner.java:201)
	at org.apache.nifi.util.StandardProcessorTestRunner.run(StandardProcessorTestRunner.java:160)
	at org.apache.nifi.util.StandardProcessorTestRunner.run(StandardProcessorTestRunner.java:155)
	at org.apache.nifi.util.StandardProcessorTestRunner.run(StandardProcessorTestRunner.java:150)
	at org.apache.nifi.util.StandardProcessorTestRunner.run(StandardProcessorTestRunner.java:145)
	at org.apache.nifi.processors.script.TestExecuteJRuby.testReadFlowFileContentAndStoreInFlowFileAttribute(TestExecuteJRuby.java:52)
Caused by: java.lang.NoSuchFieldError: O_TMPFILE
	at org.jruby.RubyFile.createFileClass(RubyFile.java:202)
	at org.jruby.Ruby.initCore(Ruby.java:1490)
	at org.jruby.Ruby.bootstrap(Ruby.java:1274)
	at org.jruby.Ruby.init(Ruby.java:1173)
	at org.jruby.Ruby.newInstance(Ruby.java:338)
	at org.jruby.embed.internal.AbstractLocalContextProvider.getGlobalRuntime(AbstractLocalContextProvider.java:82)
	at org.jruby.embed.internal.SingletonLocalContextProvider.getRuntime(SingletonLocalContextProvider.java:99)
	at org.jruby.embed.internal.BiVariableMap.getRuntime(BiVariableMap.java:109)
	at org.jruby.embed.internal.BiVariableMap.getTopSelf(BiVariableMap.java:241)
	at org.jruby.embed.internal.BiVariableMap.getReceiverObject(BiVariableMap.java:237)
	at org.jruby.embed.internal.BiVariableMap.put(BiVariableMap.java:332)
	at org.jruby.embed.ScriptingContainer.put(ScriptingContainer.java:1185)
	at org.jruby.embed.jsr223.Utils.put(Utils.java:234)
	at org.jruby.embed.jsr223.Utils.preEval(Utils.java:109)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:88)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:142)
	at org.apache.nifi.processors.script.ExecuteScript.onTrigger(ExecuteScript.java:220)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:251)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:245)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by alopresto** [comment]
The issue is that `jython` uses a binary build instead of Maven so it is an "unshaded JAR" (described in far more detail [here](https://github.com/scijava/jython-shaded)). It includes libraries that conflict with `jruby` but Maven can't resolve them, so there are runtime errors. 

Rather than separate the dependencies into separate modules, we can use the `jython-shaded` dependency mentioned above to resolve this. 

I can't push the changes to this branch, but you can make the following changes in `nifi-scripting-processor/pom.xml`:

```
    <dependency>
        <groupId>org.python</groupId>
        <artifactId>jython-standalone</artifactId>
        <version>2.7.1b3</version>
    </dependency>
```

with

```
<dependency>
	<groupId>org.scijava</groupId>
	<artifactId>jython-shaded</artifactId>
	<version>2.7.0</version>
</dependency>
```

Tests all pass:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.apache.nifi.processors.script.ExecuteScriptGroovyTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 2.533 sec - in org.apache.nifi.processors.script.ExecuteScriptGroovyTest
Running org.apache.nifi.processors.script.TestExecuteClojure
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.029 sec - in org.apache.nifi.processors.script.TestExecuteClojure
Running org.apache.nifi.processors.script.TestExecuteGroovy
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.648 sec - in org.apache.nifi.processors.script.TestExecuteGroovy
Running org.apache.nifi.processors.script.TestExecuteJavascript
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.979 sec - in org.apache.nifi.processors.script.TestExecuteJavascript
Running org.apache.nifi.processors.script.TestExecuteJRuby
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.77 sec - in org.apache.nifi.processors.script.TestExecuteJRuby
Running org.apache.nifi.processors.script.TestExecuteJython
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.72 sec - in org.apache.nifi.processors.script.TestExecuteJython
Running org.apache.nifi.processors.script.TestExecuteLua
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.068 sec - in org.apache.nifi.processors.script.TestExecuteLua
Running org.apache.nifi.processors.script.TestInvokeGroovy
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.517 sec - in org.apache.nifi.processors.script.TestInvokeGroovy
Running org.apache.nifi.processors.script.TestInvokeJavascript
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.396 sec - in org.apache.nifi.processors.script.TestInvokeJavascript
Running org.apache.nifi.processors.script.TestInvokeJython
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.263 sec - in org.apache.nifi.processors.script.TestInvokeJython
Running org.apache.nifi.record.script.ScriptedReaderTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.515 sec - in org.apache.nifi.record.script.ScriptedReaderTest
Running org.apache.nifi.record.script.ScriptedRecordSetWriterTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.24 sec - in org.apache.nifi.record.script.ScriptedRecordSetWriterTest
Running org.apache.nifi.reporting.script.ScriptedReportingTaskGroovyTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.269 sec - in org.apache.nifi.reporting.script.ScriptedReportingTaskGroovyTest

Results :




Tests run: 45, Failures: 0, Errors: 0, Skipped: 1
```

**Comment by joewitt** [comment]
unreal.  Great find.  Pushing squashed in a sec.  Thanks!

**Comment by alopresto** [comment]
Ran a full build on OS X and everything worked. Verified `contrib-check` as well. Merged.

**Pull request closed without merging**
