### PR TITLE
NIFI-6403: Fixed FIELD_INCLUDE_QUERY_PARAM value for Elastic 6.6+

### PR DESCRIPTION
**Pull request by wietze**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

This fixes a break change made in Elastic 6.6 (officially deprecated in 7.0) which replaces the `source_include` parameter for HTTP requests by `source_includes` (i.e. plural). 

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically `master`)?

- [X] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by wietze** [comment]
Anyone?

**Comment by pvillard31** [comment]
@MikeThomsen, you're more familiar with ES than I am, any opinion on this change? or @ijokarumawak maybe?

**Comment by ijokarumawak** [comment]
I think we need to handle different Elasticsearch major versions better. Currently we only have `nifi-elasticsearch-5-nar` and `nifi-elasticsearch-nar`. If we are going to maintain `nifi-elasticsearch-nar` for the latest Elasticsearch version, we probably have to add `nifi-elasticsearch-6-nar`.

That is probably what @MikeThomsen tried to implement with #2782 . Then I'd finish review/merge #2782 first. We also have to add documentation what Elasticsearch version `nifi-elasticsearch-nar` is designed to work.

@MikeThomsen do you agree with that? If so, I'll resume reviewing #2782.

**Comment by wietze** [comment]
Any updates on this?

**Comment by ijokarumawak** [comment]
Thanks for your contribution @wietze !
There is another PR trying to address the same issue and which covers a little bit more issues with the recent Elasticsearch versions. Would you join the review process at #4153 ? To see if that resolves your problem. Thanks!

**Comment by wietze** [comment]
It does indeed, will close this one.

**Pull request closed without merging**
