### PR TITLE
NIFI-12124: Added a new RenameRecordField processor. In testing, also…

### PR DESCRIPTION
**Pull request by markap14**
… noticed that the Descendant Wildcard operator (//*) and Descendant Field Path Operator (//name, for instance) did not properly account for array of records or map elements, so addressed those concerns.

# Summary

[NIFI-00000](https://issues.apache.org/jira/browse/NIFI-00000)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by joewitt** [comment]
reviewing

**Comment by ChrisSamo632** [comment]
I'll try to take a look through if possible (but don't wait for me if someone else reviews first)

I just noticed this and wondered whether it also addresses [NIFI-7194](https://issues.apache.org/jira/browse/NIFI-7194) as well - not suggesting it needs to be updated to do so if the changes don't already provide the suggested improvement

**Comment by joewitt** [comment]
looks good - merged to main.  Not sure on nifi7194

**Comment by markap14** [comment]
@ChrisSamo632 the Jira you pointed out appears to get pretty complex. I am not 100% sure if this address all cases identified there, but it will certainly help on that front.

**Comment by markap14** [comment]
Thanks @joewitt

**Pull request closed without merging**
