### PR TITLE
NIFI-7883 replace explicit type with diamond type

### PR DESCRIPTION
**Pull request by deekim**
#### Description of PR
→ [NIFI-7883](https://issues.apache.org/jira/browse/NIFI-7883)

_cleanup_ code: minor refactoring for Java syntax updates.

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

→ I didn't think this was necessary for such a small change, but I can do this if necessary.

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
→ ran, but got what I assume to be an unrelated error:
```
[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.13:check (default) on project nifi: Too many files with unapproved license: 814 See RAT report in: /home/codespace/workspace/nifi/target/rat.txt -> [Help 1]
```
- [ ] Have you written or updated unit tests to verify your changes?
- [x] Have you verified that the full build is successful on JDK 8?
- [x] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Review by MikeThomsen — CHANGES_REQUESTED** [review]
Can you go to our Jira board and create a ticket for this?

**Comment by deekim** [comment]
Thanks, @MikeThomsen. Should I also go ahead and update the commit message as well?

**Comment by MikeThomsen** [comment]
Sure.

**Review by MikeThomsen — APPROVED** [review]
@deekim NM on changing the commit message. I'll do it.

**Pull request closed without merging**
