### PR TITLE
NIFI-3004 Improved StandardSSLContextService customValidate

### PR DESCRIPTION
**Pull request by pvillard31**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [X] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by pvillard31** [comment]
**Note**: This PR needs #1374 first, otherwise the unit test will fail.

**Comment by alopresto** [comment]
@pvillard31 I added some logic to handle repeated invocations of the `customValidate` method and expire the results after 5 invocations even if the properties had not changed (added unit test demonstrating that if the keystore file is modified on the filesystem, `customValidate` will incorrectly report the service is valid as an example). 

Please review my changes [here](https://github.com/apache/nifi/compare/master...alopresto:NIFI-3004) and provide feedback, potentially incorporating them into your PR if you agree. Thanks.

**Comment by pvillard31** [comment]
Hey @alopresto, thanks for the review! I added your work as an additional commit to this PR. It looks good to me. Maybe the threshold could be added as a controller service property (however it could sound like a strange property to users not aware of the internal validation process), but I agree that it seems like a fine value as-is.

**Comment by alopresto** [comment]
Thanks @pvillard31 . I'm merging this in.

**Pull request closed without merging**
