### PR TITLE
NIFI-2115 Detailed Version Info for About Box

### PR DESCRIPTION
**Pull request by jvwing**
- Java version and vendor
- OS name and version
- Build number(commit SHA), branch, and timestamp

### CODE REVIEW

**Comment by jvwing** [comment]
Here's what the result looks like while the details section is expanded. I plead guilty to being a bad UI designer, any tips would be appreciated.

nifi-2115-about-box-info

**Comment by jvwing** [comment]
I force-pushed a substantial update/rewrite.  Changes from the previous implementation include:

* Moving most of the logic to the nifi-assembly pom rather than the parent pom
* Including the Tag property with the build information (typically HEAD for snapshot builds, RC tags for release builds)
* Handling formal releases by using Tag, ignoring revision and branch.
* More gracefully handling a source build outside git by using empty revision and branch
* Updated the about box UI to selectively include information based on availability
 - Tag displayed when not HEAD
 - Revision and branch displayed when not empty
* Included a sample UI using the System Diagnostics dialog.  I'm not suggesting we need both About and System Diagnostics, just showing sample options for discussion.
* Rebased on recent master

**Comment by jvwing** [comment]
I did not push my updates correctly yesterday, I just fixed the branch.

**Comment by trixpan** [comment]
Looks amazing but I would add some flashing/blinking HTML and a construction sign as homage to the good old GeoCities pages. :-)

On a more serious note, @jvwing could you rebase?

**Comment by jvwing** [comment]
I pushed another update to rebase on the latest master, and add a Versions tab to the Cluster UI using the version-enriched system diagnostics data.

**Comment by trixpan** [comment]
@mcgilman not sure if you seen this PR but feels to me like something we should consider merging. What do you think?

**Comment by mcgilman** [comment]
Cool... Will review. Thanks!

**Comment by mcgilman** [comment]
Hey @jvwing, this is really nice. Just a couple general comments...

I'm not sure we want to include all the System/Java version details in the about dialog. The `AboutDTO` which had these items added will be available for any user who has permissions to access the UI. I have concern allowing all users who can access the UI to know the server's OS/architecture/version and what vendor/version of Java is running. Including these items in the System Diagnostics is good IMO as users need to be granted explicit permission for viewing system level details.

Leaving the build details in the About Dialog is good IMO. I would suggest that we use the `DateTimeAdapter` on the build timestamp field to be consistent with other timestamps rendered throughout the UI. Since these only add a couple rows, it may make sense to remove the toggle and make the dialog a little bit taller.

Thoughts?

**Comment by jvwing** [comment]
@mcgilman Thanks, I had not considered the API access distinction, and that sounds like a sensible split between system diagnostics and the about dialog.  I'll try that out with an adjusted about dialog.

**Comment by jvwing** [comment]
I pushed another update with changes from feedback:

- Removed OS/JVM information from the AboutDTO and About Dialog
- Updated the layout of the About Dialog to always show the additional build information, if available
- Formatted build timestamp with DateTimeAdapter

**Comment by mcgilman** [comment]
Thanks for the update! I'm going to be in and out the next few days. Just a heads up, I might not be able to revisit until later this week. Thanks again!

**Comment by mcgilman** [comment]
Hey @jvwing... I had a chance to check out the update. Everything looks good but I do have one other comment that I probably should have noticed before. Given the build details ultimately come from `nifi.properties` I don't think we can rely on their presence. Often times, folks upgrade by retaining their consisting `conf` directory so we typically try to ensure things still work when the properties do not exist. In the System Diagnostics, it probably makes sense to simply populate the fields with a message indicating that the value isn't set. Additionally, you can style the elements with `unset`. In the About dialog is probably makes sense to just not render anything under the version. Currently, it just says 'Tagged'.

Thoughts?

**Comment by mcgilman** [comment]
@jvwing Just wanted to comment again to make sure you saw my last note. This PR is really close, just wanted to get your thoughts on my last comment. I think a couple client side checks should suffice. I'd be happy to knock them out for you just so we can get this guy in as we wind down towards our 1.1.0 release.

**Comment by jvwing** [comment]
@mcgilman You caught me :), sorry, I did miss your previous comment.  Let me see what I can do.

**Comment by jvwing** [comment]
@mcgilman - I fixed two issues that you pointed out:

1. The About dialog no longer shows the "Tagged" label when there is nothing in nifi.properties
2. I added "(not available)" to the System Diagnostics properties with the "unset" style where info is not provided in nifi.properties

Then I did some testing that I should have done last time, with these four typical scenarios for data combinations in nifi.properties:

1.) Build from source release, screenshots: [About](https://cloud.githubusercontent.com/assets/3151078/19955878/3a4c8cc0-a143-11e6-9c42-568d57f026b5.png) | [System Diagnostics](https://cloud.githubusercontent.com/assets/3151078/19955879/3a4fb8e6-a143-11e6-8e4e-bd0b190d1b86.png)
```
# Build info
nifi.build.tag=nifi-1.1.0-RC-test
nifi.build.branch=
nifi.build.revision=
nifi.build.timestamp=2016-11-02T21:32:02Z
```

2.) SNAPSHOT Build from git repo, screenshots: [About](https://cloud.githubusercontent.com/assets/3151078/19955880/3a55946e-a143-11e6-9804-4f2249fb869c.png) | [System Diagnostics](https://cloud.githubusercontent.com/assets/3151078/19955883/3a58ca76-a143-11e6-9a68-40fdd9b4f23f.png)
```
# Build info
nifi.build.tag=HEAD
nifi.build.branch=NIFI-2115-about-box-info-2
nifi.build.revision=7057cfc
nifi.build.timestamp=2016-10-24T18:21:35Z
```

3.) Build from non-release source without git, screenshots: [About](https://cloud.githubusercontent.com/assets/3151078/19955881/3a55bf8e-a143-11e6-8988-498f6dee50e7.png) | [System Diagnostics](https://cloud.githubusercontent.com/assets/3151078/19955882/3a5610a6-a143-11e6-9f61-2313855fa812.png)
```
# Build info
nifi.build.tag=HEAD
nifi.build.branch=
nifi.build.revision=
nifi.build.timestamp=2016-11-02T18:57:11Z
```

4.) Upgrade - nothing in nifi.properties, screenshots: [About](https://cloud.githubusercontent.com/assets/3151078/19955885/3a639e60-a143-11e6-9637-362461480b80.png) |  [System Diagnostics](https://cloud.githubusercontent.com/assets/3151078/19955884/3a639b2c-a143-11e6-827d-55c94988a4b6.png)

I know this isn't an exhaustive list, I believe arbitrary combinations should now be more gracefully supported.

**Comment by mcgilman** [comment]
Thanks @jvwing. Looks good! This has been merged to master.

**Comment by jvwing** [comment]
Thanks for your help, @mcgilman.

**Pull request closed without merging**
