### PR TITLE
NIFI-7669 Changed custom PBE AEAD algorithm to derive key once rather…

### PR DESCRIPTION
**Pull request by alopresto**
… than on every encrypt/decrypt operation, leading to substantial performance gains.

Updated documentation.
Added unit tests.

Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Improves performance of custom encryption algorithms by deriving key once during initialization rather than on-demand during frequent encryption/decryption operations._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by pvillard31** [comment]
Hey @alopresto, the code LGTM and I'm a +1 but it sounds like the unit test might fail:
https://github.com/apache/nifi/pull/4435/checks?check_run_id=916555010
https://github.com/apache/nifi/pull/4435/checks?check_run_id=916555051
````
[ERROR] Tests run: 18, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.423 s <<< FAILURE! - in org.apache.nifi.encrypt.StringEncryptorTest
[ERROR] testCustomAlgorithmShouldOnlyDeriveKeyOnce(org.apache.nifi.encrypt.StringEncryptorTest)  Time elapsed: 1.312 s  <<< FAILURE!
org.codehaus.groovy.runtime.powerassert.PowerAssertionError: 
assert resultDurations.max() <= FAST_DURATION_NANOS * 2
       |               |     |  |                   |
       |               |     |  1000000             2000000
       |               |     false
       |               3963600
       [281700, 3963600, 231200, 192100, 204600, 185400, 179400, 197200, 199600, 362100, 189300, 180800, 224400, 188400, 407100, 1036600, 191400, 159700, 178100, 1294400, 179600, 169200, 155300, 338600, 169400, 148200, 202200, 161300, 163100, 3188600, 368200, 462900, 182400, 198400, 184400, 286700, 181900, 167700, 173100, 697000, 203000, 168300, 172600, 719900, 213200, 560300, 198000, 348200, 198900, 143600, 147800, 266700, 154000, 669400, 236200, 169600, 157700, 165800, 163600, 138100, 141900, 186300, 380900, 687500, 168900, 1063000, 177100, 137400, 590800, 156200, 175000, 172600, 165100, 133800, 139600, 137500, 140800, 129100, 138700, 1290300, 148000, 123900, 169500, 451800, 151200, 113400, 152500, 110600, 119000, 295200, 130900, 123800, 320100, 141700, 139500, 103400, 170500, 110200, 116000, 99300, 588500, 130600, 116800, 95800, 106800, 1168300, 162600, 131100, 118300, 108400, 107200, 93500, 334800, 126700, 118900, 99300, 111700, 1587500, 155000, 112400, 112500, 229600, 114400, 93900, 135800, 103200, 117900, 140400, 130400, 126700, 113100, 86100, 95600, 84600, 99700, 81500, 109900, 116100, 103500, 88200, 98400, 106400, 109500, 89800, 101200, 430100, 127000, 90200, 97500, 81500, 92100, 152600, 522500, 505400, 126700, 96900, 126000, 95400, 289200, 110900, 114500, 368400, 125700, 1378600, 147500, 109700, 111100, 96000, 142600, 96000, 153300, 95800, 103900, 90300, 98400, 83400, 104700, 77100, 119800, 92500, 537300, 451000, 1746000, 175900, 236600, 114000, 109500, 102600, 103800, 87400, 103400, 95300, 100800, 112900, 147000, 90300, 98700, 112400, 118100, 3420700]
	at org.apache.nifi.encrypt.StringEncryptorTest.testCustomAlgorithmShouldOnlyDeriveKeyOnce(StringEncryptorTest.groovy:740)


[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 s - in org.apache.nifi.wali.EncryptedSequentialAccessWriteAheadLogTest
[ERROR] Failures: 
[ERROR]   StringEncryptorTest.testCustomAlgorithmShouldOnlyDeriveKeyOnce:740 assert resultDurations.max() <= FAST_DURATION_NANOS * 2
       |               |     |  |                   |
       |               |     |  1000000             2000000
       |               |     false
       |               3963600
       [281700, 3963600, 231200, 192100, 204600, 185400, 179400, 197200, 199600, 362100, 189300, 180800, 224400, 188400, 407100, 1036600, 191400, 159700, 178100, 1294400, 179600, 169200, 155300, 338600, 169400, 148200, 202200, 161300, 163100, 3188600, 368200, 462900, 182400, 198400, 184400, 286700, 181900, 167700, 173100, 697000, 203000, 168300, 172600, 719900, 213200, 560300, 198000, 348200, 198900, 143600, 147800, 266700, 154000, 669400, 236200, 169600, 157700, 165800, 163600, 138100, 141900, 186300, 380900, 687500, 168900, 1063000, 177100, 137400, 590800, 156200, 175000, 172600, 165100, 133800, 139600, 137500, 140800, 129100, 138700, 1290300, 148000, 123900, 169500, 451800, 151200, 113400, 152500, 110600, 119000, 295200, 130900, 123800, 320100, 141700, 139500, 103400, 170500, 110200, 116000, 99300, 588500, 130600, 116800, 95800, 106800, 1168300, 162600, 131100, 118300, 108400, 107200, 93500, 334800, 126700, 118900, 99300, 111700, 1587500, 155000, 112400, 112500, 229600, 114400, 93900, 135800, 103200, 117900, 140400, 130400, 126700, 113100, 86100, 95600, 84600, 99700, 81500, 109900, 116100, 103500, 88200, 98400, 106400, 109500, 89800, 101200, 430100, 127000, 90200, 97500, 81500, 92100, 152600, 522500, 505400, 126700, 96900, 126000, 95400, 289200, 110900, 114500, 368400, 125700, 1378600, 147500, 109700, 111100, 96000, 142600, 96000, 153300, 95800, 103900, 90300, 98400, 83400, 104700, 77100, 119800, 92500, 537300, 451000, 1746000, 175900, 236600, 114000, 109500, 102600, 103800, 87400, 103400, 95300, 100800, 112900, 147000, 90300, 98700, 112400, 118100, 3420700]
[ERROR] Tests run: 450, Failures: 1, Errors: 0, Skipped: 13
````

**Comment by alopresto** [comment]
It seems the CI/CD machines are overloaded and/or lower performance than many of the developer environments. I'll ignore those tests with a comment that they can be enabled locally to prove the separation of the key derivation from the encrypt/decrypt operation.

**Comment by joewitt** [comment]
@alopresto maybe just convert them to integration tests which we dont run in CI/CD but folks do tend to run for validating RCs....?

**Comment by pvillard31** [comment]
I see other unit test failures that could be related to #4434 (already merged into main)

**Comment by pvillard31** [comment]
Merged to main, thanks @alopresto

**Pull request closed without merging**
