### PR TITLE
NIFI-8635: Add Status Message natively to HandleHTTPResponse

### PR DESCRIPTION
**Pull request by naddym**
#### Description of PR

HTTP Status Codes are helpful while responding back to the successful requests but they become little less meaningful when something actual failed internally such as Processor/DataFlow errored and message needs to be communicated back to client to make little more meaningful. This is usually done today by using another Processor like ReplaceText which actually writes failed message before sending to HandleHTTPResponse.

`HandleHTTPRequest --> .... ReplaceText -> HandleHTTPResponse`

This sequence becomes little overloaded when failures need to be handled at different step such as processor exception/custom message etc.

Introducing new optional property 'HTTP Status Message' which can remove the need to use ReplaceText can be a lot beneficial where dataflow users can directly write the message or use EL from Parameter/Variable Registry to denote canonical messages based on status code which can used across all HandleHTTPResponse directly.

_Enables X functionality; fixes bug NIFI-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [x] Have you written or updated unit tests to verify your changes?
- [x] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by markap14** [comment]
Thanks for the improvement @naddym ! I think it makes a lot of sense to add in a Status Message property. Setting the flowfile content is often what we want for a "200 OK" type of response but this makes a lot of sense for other scenarios. The only thing that I'm not sure about is the idea of having this processor update the FlowFile content. I think it makes more sense to send back the use-configured response but not change the FlowFile. I can definitely see cases where we will want to receive an HTTP message, do something with it, then send back a response, and afterwards continue with the FlowFile to do something else. And in the case that we don't want to do anything and want to terminate the flow after HandleHttpResponse, there's no benefit to the overhead of updating FlowFile content.

So it seems to me that we should instead not have the processor update the FlowFile's content at all. But perhaps you have a different viewpoint that I'm missing?

**Comment by naddym** [comment]
Thank you @markap14 for the review and suggestion. Definitely, it make lot of sense to not write to a flowfile when HandleHttpResponse is not terminated and if the previous content is needed. Also, it will add additional overhead of overwriting when HandleHttpResponse is terminated like you mentioned. Instead, we can send status message to `response.getOutputStream()` when `Http Status Message` property is set otherwise follow existing step of exporting flowfile content to response.getOutputStream()

``` 
// if statusMessage property is set
if (!StringUtils.isBlank(statusMessage)) {
   try(OutputStream out = response.getOutputStream();) {
        out.write(statusMessage.getBytes());
   }
} else {
   session.export(flowfile, response.getOutputStream());
}
```   

This will also be beneficial to send different response back when failed and further continue to process the failure such as sending email or writing the failed content somewhere. It will also avoid using Processors like ReplaceText (for writing failure response message) and ExtractText for example ( to restore back our previous content if we want to continue further processing if HandleHttpResponse is not terminated) specifically on failures. 

**Example**

Existing approach
` HandleHttpRequest -> ... ExtractText -> ReplaceText --> HandleHttpResponse -> (restore back content for further processing from ExtractText)`

When Status Message property is set
 ` HandleHttpRequest -> ....... --> HandleHttpResponse (set status message) -> (continue rest of the processing)`

 Please suggest if this looks. I can make above changes. Thanks again.

**Comment by markap14** [comment]
@naddym yes that is exactly what I had in mind.
One other interesting note to consider: Your check above:
`if (!StringUtils.isBlank(statusMessage)) {` may not be exactly correct, because the status message may be an empty string, and if I'm not mistaken that is perfectly valid. And in fact, I think for something like a 204 it MUST be empty.
So we'd want to check:
```
try(OutputStream out = response.getOutputStream()) {
    if (statusMessage == null) {
         session.export(flowfile, response.getOutputStream());
    } else {
        out.write(statusMessage.getBytes());
    }
}
```

**Comment by naddym** [comment]
Good catch @markap14 Thanks. In case of `204 No Content` status code, the response outputstream is ignored and only headers are updated. However, make sense to allow property for empty string. I have made requested changes..

**Comment by naddym** [comment]
@markap14 I have made requested changes, can you please review and let me know for any changes. Thanks.

**Pull request closed without merging**
