### PR TITLE
NIFI-8622: Reuse of GenericRecord instance eliminated from AvroReader…

### PR DESCRIPTION
**Pull request by pgyori**
…WithExplicitSchema to avoid issues when parsing fields of type "bytes"

https://issues.apache.org/jira/browse/NIFI-8622

Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

Eliminates the reuse of a GenericRecord instance in AvroReaderWithExplicitSchema to avoid issues when parsing fields of type "bytes" (especially when "logicalType": "decimal" is used). More details in the referenced Apache Jira ticket.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [x] Have you written or updated unit tests to verify your changes?
- [x] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Review by gresockj — APPROVED** [review]
Thanks @pgyori for this contribution!  I ran NiFi with the patch and observed that it fixes the problem.  Do you have a sense of whether this change impacts the performance of the processor?  I wasn't able to detect any appreciable performance hit during my testing.

**Comment by pgyori** [comment]
Thank you for approving, @gresockj ! I did not measure the difference in performance. I assume that creating a new instance of a GenericRecord type has some overhead. The other type inheriting from AvroRecordReader (AvroReaderWithEmbeddedSchema) has been using this approach for years ( https://github.com/apache/nifi/blob/7fe8858d22f580ad9dcd96ebafb59dbe5e73f5cb/nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/avro/AvroReaderWithEmbeddedSchema.java#L53 ).

**Comment by pgyori** [comment]
I created a test class to measure the performance before and after the change. The source code of the test is available here:
https://gist.github.com/pgyori/5fa9499182d544f12ce2e5deeeba6d00
AvroRecordReader performance
Attached the results of my measurements before and after the fix. In my tests execution time increased by 6%-15%. I did not experience any change in memory consumption.

**Review by Lehel44 — APPROVED** [review]

**Comment by markap14** [comment]
Thanks @Lehel44 this looks good to me. +1 will merge to main

**Pull request merged**
