### PR TITLE
improve foreground run mode of nifi

### PR DESCRIPTION
**Pull request by automaticgiant**
- add exec to RUN_NIFI_CMD
- remove subshell for else
- tested compatible with runit with these changes

### CODE REVIEW

**Comment by automaticgiant** [comment]
https://issues.apache.org/jira/browse/NIFI-2689

**Comment by trixpan** [comment]
@automaticgiant thank you for the contribution.

This look to me, but I would like someone like @alopresto  or @apiri to have a second look.

**Comment by apiri** [comment]
will review

**Comment by apiri** [comment]
changes seem fair and will merge.  thanks for contributing.

**Pull request closed without merging**
