### PR TITLE
NIFI-6666 Add Useragent Header to InvokeHTTP requests

### PR DESCRIPTION
**Pull request by nielsbasjes**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

This enables the option of sending out a Useragent header to all InvokeHTTP requests and also adds a sensible default value.

Something like this was present before in the (now deprecated) GetHTTP (but without the default value).

The default useragent value is based on a combination of the version of Nifi at hand, the java version and the operating system version.

In my local environment the end result was this default useragent:

`Apache Nifi/1.10.0-SNAPSHOT (git:rel/nifi-1.9.0-347-gec3ea46; Java/1.8.0_222; Linux 4.4.0-159-generic; amd64; https://nifi.apache.org/)`

To make this possible I changed:
1. The nifi-api now has a generated class that contains several build time variables (like project version, build time and git information).
1. The VariableRegistry ENVIRONMENT_SYSTEM_REGISTRY includes these variables.
1. The StandardProcessorTestRunner now loads the ENVIRONMENT_SYSTEM_REGISTRY variables by default to allow any testing on these variables.
1. The InvokeHTTP now has a property with that holds the useragent value that uses the Expression language to make it dynamic. It is dynamic per flow file so people have the option of writing a flow that changes the useragent per flowfile going through.

This improvement fixes NIFI-6666.

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [x] Have you written or updated unit tests to verify your changes?
- [x] Have you verified that the full build is successful on both JDK 8 and JDK 11?
**Checked using the Travis build**

- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [x] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [x] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by nielsbasjes** [comment]
Can someone please add me as a contributor in Jira please?
And assign https://issues.apache.org/jira/browse/NIFI-6666 to me?

**Comment by nielsbasjes** [comment]
@MikeThomsen 
I did a rebase onto the latest master branch.
I changed the way the values are stored in the properties.

Just now I noticed that the BUILD_TIMESTAMP is incorrect so I'm going to fix that later today.

**Comment by nielsbasjes** [comment]
I fixed the timestamp issue I mentioned.

The User-Agent header generated on my machine looks like this:
```Apache Nifi/1.12.0-SNAPSHOT (git:rel/nifi-1.11.0-231-gd98a0f5-dirty; Java/1.8.0_252; Linux 4.4.0-178-generic; amd64; https://nifi.apache.org/)```

In a released version it should look like this:
```Apache Nifi/1.12.0 (git:rel/nifi-1.12.0; Java/1.8.0_252; Linux 4.4.0-178-generic; amd64; https://nifi.apache.org/)```

**Comment by MikeThomsen** [comment]
I'll try to get a review done tonight. Thanks for responding so fast.

**Comment by MikeThomsen** [comment]
Found a build error. It might be due to your updates to the StandardTestRunner:

```
 [WARNING] Tests run: 6, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.044 s - in org.apache.nifi.avro.TestWriteAvroResultWithoutSchema
[WARNING] Tests run: 20, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 0.031 s - in org.apache.nifi.json.TestJsonTreeRowRecordReader
[WARNING] Tests run: 5, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 0.01 s - in org.apache.nifi.json.TestInferJsonSchemaAccessStrategy
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.08 s <<< FAILURE! - in org.apache.nifi.text.TestFreeFormTextRecordSetWriter
[ERROR] testDefaultSingleRecord(org.apache.nifi.text.TestFreeFormTextRecordSetWriter)  Time elapsed: 0.063 s  <<< FAILURE!
org.junit.ComparisonFailure: 
expected:<...try: USA, Username: []
> but was:<...try: USA, Username: [runner]
>
	at org.apache.nifi.text.TestFreeFormTextRecordSetWriter.testDefaultSingleRecord(TestFreeFormTextRecordSetWriter.java:90)

[ERROR] Failures: 
[ERROR]   TestFreeFormTextRecordSetWriter.testDefaultSingleRecord:90 expected:<...try: USA, Username: []
> but was:<...try: USA, Username: [runner]
>
[ERROR] Tests run: 265, Failures: 1, Errors: 0, Skipped: 5
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project nifi-record-serialization-services: There are test failures.
```

**Comment by nielsbasjes** [comment]
@MikeThomsen Yes indeed my change broke the build.
The problem here is that the variable `${user.name}` is undefined in the "normal" setup and my change simply introduces in in the system with a valid value.
This test assumes this value not to be set at all and thus fails because it now has an unexpected default value.
I fixed this by renaming this test variable from user.name to login.name

**Comment by nielsbasjes** [comment]
I checked why my patch didn't fail the build when I first submitted it: The test that failed was added only a few weeks ago.

**Comment by MikeThomsen** [comment]
@nielsbasjes thanks. I'll try to get back to the review tonight. Overall LGTM now.

**Comment by MikeThomsen** [comment]
Merged. Thanks for the contribution!

**Pull request closed without merging**
