### PR TITLE
NIFI-12175 update Docker Image builds to Java 21, rationalise base image name and tag across all components

### PR DESCRIPTION
**Pull request by ChrisSamo632**
# Summary

[NIFI-12175](https://issues.apache.org/jira/browse/NIFI-12175) update Docker Image builds to Java 21, rationalise base image name and tag across all components

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [x] Build completed using `mvn clean install -P contrib-check`
  - [x] JDK 21

### Licensing

- ~[ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)~
- ~[ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files~

### Documentation

- ~[ ] Documentation formatting appears as expected in rendered files~

### CODE REVIEW

**Comment by ChrisSamo632** [comment]
This PR blocks NIFI-12178 (see #7858)

**Comment by briansolo1985** [comment]
Hi @ChrisSamo632!
Thank you for the change. I noticed that the docker images in minifi/minifi-c2/minifi-c2-docker are still using the eclipse-temurin:17-jre base image. Could we include upgrading those in this change as well?

**Comment by ChrisSamo632** [comment]
@briansolo1985 thanks for the catch, thought I'd updated all of those, but evidently I either mised some or forgot to add them to the commit!

Had missed the same for `nifi-registry`'s `dockerhub` file too

**Review by briansolo1985 — APPROVED** [review]

**Review by exceptionfactory — APPROVED** [review]
Thanks for making these improvements @ChrisSamo632, moving the Docker Image Name and version to the root Maven configuration will definitely help keep things clear. The other changes look good. +1 merging

**Pull request closed without merging**
