### PR TITLE
NIFI-3536 Adding GetSOAP processor which supports generically invokin…

### PR DESCRIPTION
**Pull request by apsaltis**
…g SOAP endpoints

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [X] Have you written or updated unit tests to verify your changes?
- [X] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [X] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by trixpan** [comment]
@apsaltis 

Is it my impression or the new dependencies weren't added to the nifi-assembly `NOTICE` ?

**Comment by apsaltis** [comment]
@trixpan - You are correct, sorry about that. I will update it accordingly

**Comment by apsaltis** [comment]
@trixpan - Considering this P/R was before 1.2 was GA, is it worth just closing this, rebasing, updating pom's accordingly and then create a new P/R?

**Comment by apsaltis** [comment]
Closing this P/R to rebase it off of the 1.3.0-SNAPSHOT codebase

**Pull request closed without merging**
