### PR TITLE
NIFI-3484 GenerateTableFetch Should Allow for Right Boundary

### PR DESCRIPTION
**Pull request by patricker**
When using GenerateTableFetch it places no right hand boundary on pages of data.  This can lead to issues when the statement says to get the next 1000 records greater then a specific key, but records were added to the table between the time the processor executed and when the SQL is being executed. As a result it pulls in records that did not exist when the processor was run.  On the next execution of the processor these records will be pulled in a second time.

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [x] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by ilyatau** [comment]
Are you going to finish this request?

**Comment by patricker** [comment]
@ilyatau Why do you feel that this request isn't finished?
While I do have a newer version, the functionality it adds is a bit more advanced and I've had a hard time automating the testing.

The additional functionality I have working will generate a premature right boundary to reduce the number of records brought back. You might think that this is already the point of Generate Table Fetch, but I found that even with an indexed timestamp column you still have to page the index when paging through data on some systems. In one case we found that on SAP Hana we ran into some internal limitations which did not allow you to page past more than 2 billion rows of data. The table we were loading with Generate Table Fetch had ~6 billion rows. Using the un-committed change you can provide a per execution limit to Generate Table Fetch so that it will only generate pages of `x` size for the first `y` rows in the table.

When I tried to test this on SQL Lite it did not work, though it is working on other SQL systems we've tried it on.

**Comment by ilyatau** [comment]
It's cool.
My question was about when this commits will be in master branch?
because our architecture very needs this functionality.
Thanks

**Comment by patricker** [comment]
@ilyatau That's up to the reviewers...

**Comment by ilyatau** [comment]
I thought what you need to do something for fix failed checks

**Comment by pvillard31** [comment]
Hey @patricker, thanks for this PR and sorry it took so long to get into it. I just reviewed your work and it looks valid. I was able to confirm that it fixes the data duplication issue I was seeing in my environment.

I have pushed a commit here:
https://github.com/pvillard31/nifi/tree/PR1513

It fixes a check style issue in your PR and also adds a unit test to show the existing data duplication possibility. If you agree with it, can you add it into your PR and I'll get everything merged?

Thanks a lot!

**Comment by patricker** [comment]
@pvillard31 Thanks. There have been some more changes recently to GenerateTableFetch. Let me work through the rebase.

**Comment by pvillard31** [comment]
@patricker just a quick message on this one to check if all is OK on your side? If you're busy at the moment, I can open a PR containing your commit and mine. Let me know what you prefer.

**Comment by patricker** [comment]
@pvillard31 Would you mind? I tried pulling it in (see my commits), but I hadn't rebased against master and ended up bringing in a change and ended up with some duplicate code... got messy.

**Comment by pvillard31** [comment]
No problem @patricker, just opened #2091. Let me know if it looks good to you.

**Comment by pvillard31** [comment]
This is now merged with #2091. Can you close this one @patricker ? Thanks!

**Pull request closed without merging**
