### PR TITLE
NIFI-3702 AWS SDK Update:

### PR DESCRIPTION
**Pull request by jvwing**
* Updated the AWS SDK dependency version to 1.11.8
* Removed GetDynamoDBTest references to JsonObject class dropped from AWS SDK
* Fixed integration test ITPutSNS.testPublish() - exception from not evaluating expressions
* Ignored integration test ITPutS3Object.testS3MultipartAgeoff() - did not work before or after SDK update
----

**Reviewers**: In [NIFI-2062](https://issues.apache.org/jira/browse/NIFI-2062) we upgraded the master branch from AWS SDK 1.10.32 to 1.11.8.  The change included some adjustments to unit tests to account for Amazon's JSON changes.  We probably should have merged this to 0.x last year, but didn't.  So I recycled commit [a7c5b88](https://github.com/apache/nifi/commit/a7c5b88a470d832e1690faede9a5b2f606196342), changed the names to protect the innocent, and present it fresh for 0.x.

---
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [X] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by mosermw** [comment]
Thanks for this @jvwing.  Would you mind updating the nifi-nar-bundles/nifi-aws-bundle/nifi-aws-nar/src/main/resources/META-INF/NOTICE and nifi-assembly/NOTICE files to remove the 1 line from each that says "JSON parsing and utility functions from JSON.org - Copyright 2002 JSON.org" in the Amazon Web Services SDK section?  If you could take care of that in this PR, then I won't need another!

**Comment by jvwing** [comment]
@mosermw, sorry I left that out.  I updated both NOTICE files and checked the [AWS SDK NOTICE](https://github.com/aws/aws-sdk-java/blob/master/NOTICE.txt) to verify that was the only change.  I force pushed the branch with the modified commit.

**Comment by mosermw** [comment]
+1 will merge.  Thanks @jvwing. 
It looks like I should also migrate the changes from NIFI-2763 and NIFI-2902 (V4 Signer support) over to the 0.x branch as well, to avoid breaking that functionality.  I will create a new JIRA for that.

**Comment by mosermw** [comment]
Would you close this PR @jvwing?  Thank you.

**Comment by jvwing** [comment]
Thanks, @mosermw.

**Pull request closed without merging**
