### PR TITLE
NIFI-4256 - Add support for all AWS S3 Encryption Options

### PR DESCRIPTION
**Pull request by nadenf**
Submitting for peer review.

### CODE REVIEW

**Comment by jvwing** [comment]
Reviewing...

**Comment by jvwing** [comment]
@baank Thanks for putting together this PR, it looks like you put a lot of thought into covering all the possible encryption scenarios.  I haven't run it yet, but I have a few starter questions after looking over some of the code:

1. What was the driver behind updating the AWS SDK version?
1. Although the service interfaces and their methods are named specific to encryption, the substance of their interaction are not necessarily limited to encryption.  What would you think about making the interfaces more generic?  For example:
    * Could the S3ClientSideEncryptionService be "S3ClientService" with only `getClient` methods, with the `needsEncryptedClient()` logic being performed internally by the concrete implementation StandardS3ClientSideEncryptionService.  I can see a number of use cases beyond encryption that could be covered by a custom client factory.
    * Could the S3ServerSideEncryptionService be a more generic S3 put request modifier?  My efforts at thinking up a good name failed miserably here.  But the interface allows many non-encryption modifications of an S3 request, which might indeed be useful, despite the `encrypt()` naming of the methods.

**Comment by joewitt** [comment]
@baank will you be in a position to help work with @jvwing on review/contrib cycles?

**Comment by baank** [comment]
Sure not a problem. I have already implemented his changes but just need to get a new PR approved and also there was a comment in JIRA regarding whether to include the client side S3 work at all.

**Comment by alopresto** [comment]
I believe this PR was superseded by PR #2248 and PR #2291. Can this be closed?

**Comment by jvwing** [comment]
@alopresto - Yes, I believe this can be closed.

**Pull request closed without merging**
