### PR TITLE
NIFI-12491 Added Starting Row Schema Strategy to ExcelReader for 1.x branch

### PR DESCRIPTION
**Pull request by dan-s1**
# Summary
[NIFI-12491](https://issues.apache.org/jira/browse/NIFI-12491)

This feature has been added for the 2.x branch with #9064. This PR is to have it added to the 1.x branch. Per the comments in [NIFI-11167](https://issues.apache.org/jira/browse/NIFI-11167)  and [NIFI-13304](https://issues.apache.org/jira/browse/NIFI-13304) it would seem this feature along with `SplitExcel` processor will help customers who had used `ConvertExcelToCSV` in 1.x be able to make a smoother transition from 1.x to  2.x.

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [x] Build completed using `mvn clean install -P contrib-check`
  - [x] JDK ~21~  8

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by dan-s1** [comment]
@exceptionfactory I cannot seem to restart the `MacOs`  build (as the current failure has nothing to do with my changes). I  do not see an icon on the side of the build on [this page](https://github.com/apache/nifi/actions/runs/9943050208) nor on [this page](https://github.com/apache/nifi/actions/runs/9943050208/job/27465945749?pr=9081) which would allow me to restart. Please advise. Thanks!

**Comment by dan-s1** [comment]
@exceptionfactory I noticed I was able to restart (i.e. the icon was available) after all the jobs were done. If you changed something thank you!

**Comment by dan-s1** [comment]
@exceptionfactory 
The `MacOS` build seems to consistently fail on the test below which I do not think has anything to do with my changes. I have already run this build three times. Please advise.

```
Error:  Tests run: 17, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 25.52 s <<< FAILURE! -- in org.apache.nifi.processors.standard.TestListFile
Error:  org.apache.nifi.processors.standard.TestListFile.testFilterAge -- Time elapsed: 6.549 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <age2.txt> but was: <age1.txt>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1145)
	at org.apache.nifi.processors.standard.TestListFile.testFilterAge(TestListFile.java:330)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
```

**Comment by exceptionfactory** [comment]
> @exceptionfactory The `MacOS` build seems to consistently fail on the test below which I do not think has anything to do with my changes. I have already run this build three times. Please advise.
> 
> ```
> Error:  Tests run: 17, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 25.52 s <<< FAILURE! -- in org.apache.nifi.processors.standard.TestListFile
> Error:  org.apache.nifi.processors.standard.TestListFile.testFilterAge -- Time elapsed: 6.549 s <<< FAILURE!
> org.opentest4j.AssertionFailedError: expected: <age2.txt> but was: <age1.txt>
> 	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
> 	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
> 	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
> 	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
> 	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
> 	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1145)
> 	at org.apache.nifi.processors.standard.TestListFile.testFilterAge(TestListFile.java:330)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at java.util.ArrayList.forEach(ArrayList.java:1259)
> 	at java.util.ArrayList.forEach(ArrayList.java:1259)
> ```

This is an unstable test, which we adjusted on the main branch, so not a concern for this pull request.

**Review by exceptionfactory — APPROVED** [review]
Thanks for backporting this improvement @dan-s1! +1 merging

**Pull request merged**
