### PR TITLE
NIFI-13454: Renaming FileParameterProvider to KubernetesSecretParamet…

### PR DESCRIPTION
**Pull request by gresockj**
…erProvider

# Summary

[NIFI-13454](https://issues.apache.org/jira/browse/NIFI-13454)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for the update @gresockj. Although renaming may help, it would also break existing deployments.

Instead of renaming the class, I recommend limiting the change to updating the Capability Description, which provides helpful background on the intended purpose.

**Comment by joewitt** [comment]
I share the view that this is a wise move as it is not otherwise clear this is specifically intended for K8S based deployment scenarios.  I think we should ensure this ends up in the migration guidance but I think this is far more intentional about its purpose.

**Comment by exceptionfactory** [comment]
Thanks for the additional perspective @joewitt. I'm fine with renaming the class, we can just note the change in a migration guide step.

**Comment by gresockj** [comment]
> Thanks for the additional perspective @joewitt. I'm fine with renaming the class, we can just note the change in a migration guide step.

Thanks, @exceptionfactory.  Are there any additional changes needed on this?

**Review by exceptionfactory — APPROVED** [review]
Thanks @gresockj, the current version looks good! +1 merging, and I will add a note to the migration guide when I prepare the 2.0.0-M4 release candidate build.

**Pull request closed without merging**
