### PR TITLE
NIFI-4444: Upgrade to Jersey 2.x

### PR DESCRIPTION
**Pull request by mcgilman**
NIFI-4444: 
- Upgrading to Jersey 2.x.
- Updating NOTICE files where necessary.

### CODE REVIEW

**Comment by mcgilman** [comment]
This PR upgrades Jersey throughout NiFi where it is used directly. Most transitive Jersey dependencies are left intact. The most significant changes are centered in the clustering framework, UpdateAttribute custom UI, JoltTransform custom UI, and the toolkit groovy scripts. To most easily evaluate these changes try the template attached in the JIRA in clustered mode and run the node manager toolkit utility.

**Comment by bbende** [comment]
There is a minor check style violation in RedirectResourceFilter for the @return java doc.

**Comment by bbende** [comment]
Also some unused imports in the Yandex bundle

**Comment by alopresto** [comment]
Reviewing...

**Comment by mcgilman** [comment]
Thanks @bbende. I've pushed another commit that addresses the checkstyle issues.

**Comment by alopresto** [comment]
I had some trouble getting the cluster configured successfully due to Zookeeper port conflicts (will be filing a Jira to improve the error messaging there). I got it working and the flow operates successfully on both branches. 

I can't get the toolkit to work, however. Both `notify.sh` and `node-manager.sh` are reporting errors parsing the `-b` option for the existing `bootstrap.conf` file, so I will keep playing with that. 

Meanwhile, the unit tests and contrib-check all pass on the latest commit.

**Comment by alopresto** [comment]
I discovered some issues with the admin toolkit and will be opening a Jira to resolve that. In the meantime, I validated everything except the toolkit behavior for this PR, but that was confirmed by @bbende and @mcgilman . 

Ran `contrib-check` and all tests pass. +1, merging.

**Pull request closed without merging**
