### PR TITLE
NIFI-4917: Externalize Keytab and Principal configuration from Proces…

### PR DESCRIPTION
**Pull request by markap14**
…sors to a Controller Service. This gives us the ability to allow users to interact with those Keytabs/Principals to which they've been given access without allowing them access to all Keytabs and Principals

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by markap14** [comment]
@pvillard31 no, we don't want the ALLOW_EXPLICIT_KEYTAB stuff in nifi.properties for a couple of reasons. For one, it is really intended to be a fairly short-lived thing - eventually we will want to remove the properties for principal & keytab from the processors all together. They are allowed there now only in order to ease the transition of upgrading, so that we don't immediately force all users to reconfigure all processors that use keytabs. So adding it to nifi.properties in that respect feels a bit odd.

Additionally, processors themselves don't have access to nifi.properties. These are system-level properties, not intended to be used by processors. (Processors probably could still get access to the properties if you really want to desperately enough, but it would mean doing some rather hack-ish things in code, I do believe, as they are not intended to be used by processors).

Finally, we don't want to allow someone to access the NiFiProperties class and call setProperty in order to disable this checking.

**Comment by markap14** [comment]
The logic above could be moved into a static method within KerberosCredentialsService, but I would avoid doing so for a couple of reasons:
1. I'm not sure that all processors are already using the exactly same name of the properties. And if not, then adding it to that interface would complicate things.
2. Doing so would mean that we need to move the Property Descriptors themselves into that interface as well. As described above, these are "legacy" property descriptors that are intended to go away, so I would not want to add them into the interface for the "new way to do things", if that makes sense.

**Comment by bbende** [comment]
@markap14 do you think it makes sense to update the default nifi-env.sh/.bat so that the environment variable is already there (defaulting to allow) and can easily be toggled?

https://github.com/apache/nifi/blob/master/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-resources/src/main/resources/bin/nifi-env.sh

Something like:
```
# Set to false to force the use of Keytab controller service
export NIFI_ALLOW_EXPLICIT_KEYTAB=true
```

**Comment by bbende** [comment]
Several of the HDFS & Parquet processors still have the `@Restriction(requiredPermission = RequiredPermission.ACCESS_KEYTAB` which I believe shouldn't be there anymore.

- DeleteHDFS
- FetchHDFS
- GetHDFS
- MoveHDFS
- PutHDFS
- FetchParquet
- PutParquet

**Comment by claudiu-stanciu** [comment]
@markap14 would you consider adding the _HOST replacement for the principal as well? I've made a PR to address this here https://github.com/apache/nifi/pull/2569, but it's only for the existing processors and services.

**Comment by bbende** [comment]
@claudiu-stanciu since the principal property supports expression language, can you just do this?

`foo/${hostname(true)}@ABC.COM`

The parameter to the hostname function indicates to use a fully qualified hostname:

https://nifi.apache.org/docs/nifi-docs/html/expression-language-guide.html#hostname

**Comment by claudiu-stanciu** [comment]
@bbende thanks for pointing it out. In that case I can cancel that PR and make a PR to replace the _HOST for the nifi principal property. I didn't find it there.

**Comment by markap14** [comment]
@bbende thanks for the careful review! I have pushed a new PR that I believe should address all of your comments.

**Pull request closed without merging**
