### PR TITLE
NIFI-10504 Update OpenCSV From 5.4 to 5.7.0

### PR DESCRIPTION
**Pull request by UcanInfosec**
# Summary

[NIFI-10504](https://issues.apache.org/jira/browse/NIFI-10504)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI-10504) issue created

### Pull Request Tracking

- [X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X] Pull Request based on current revision of the `main` branch
- [X] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [X] JDK 8
  - [X] JDK 11
  - [X] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by UcanInfosec** [comment]
Hey, @exceptionfactory, if I have this change and also some other smaller changes, how should I do it?

**Comment by exceptionfactory** [comment]
@UcanInfosec Any changes unrelated to OpenCSV should be part of a separate Jira issue and pull request. Those changes can be submitted in a branch on your fork, other than `main`.

**Comment by UcanInfosec** [comment]
@exceptionfactory Thanks. So if I have like 3-4 other software to update, I will wait for this to be closed before opening a new ticket for each.

**Review by exceptionfactory — APPROVED** [review]
Thanks for the upgrade @UcanInfosec, reviewing the [release notes](https://sourceforge.net/p/opencsv/wiki/What%27s%20new/) and evaluating the usage looks good. +1 merging

**Pull request closed without merging**
