### PR TITLE
Dummy commit focused in closing stalled PR requests

### PR DESCRIPTION
**Pull request by trixpan**
@apiri 

hope this is what you had in mind.

Cheers

### CODE REVIEW

**Comment by apiri** [comment]
@trixpan Yep, looks good, and also agree with the superseded items.  Thanks for combing through and finding these.  Personally, I think this is good to go, but will give the email thread in Apache a bit more time to see if other folks have an opinion otherwise.

**Comment by trixpan** [comment]
@apiri should we go ahead and commit the PR?

**Comment by apiri** [comment]
@trixpan yeah, feel free to merge.  I think there has been sufficient time for folks to chime in.  Thanks!

**Comment by trixpan** [comment]
@apiri done

**Pull request closed without merging**
