### PR TITLE
NIFI-5706 : Added ConvertAvroToParquet processor

### PR DESCRIPTION
**Pull request by mohitgargk**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [x] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [x] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by bbende** [comment]
@MikeThomsen the advantage is not having to write the parquet out to local disk somewhere, and then have a disconnected flow where another part reads it back in. With this approach the data stays in NiFi's repositories and the ConvertAvroToParquet can be directly connected to the next processor.

I will try to give this a review in the coming days... Since this processor is already developed, the best approach here maybe to commit this as is (assuming the processor works as expected) and then afterwards refactor the utility classes into a nifi-parquet-utils under nifi-nar-bundles/nifi-extension-utils and this way the code can be shared by this processor and the eventual record writer.

**Comment by mohitgargk** [comment]
thanks @bbende for the feedback, will work on the fix tomorrow.

**Comment by mattyb149** [comment]
What is the use case for having Parquet files flow through NiFi? I wrote ConvertAvroToORC and every time I saw it used, it was immediately followed by PutHDFS. So I followed the PutParquet lead and wrote a PutORC for the Hive 3 NAR. We can't currently do anything with a Parquet file (or ORC for that matter) in NiFi, so just curious as to how you envision it being used.

Also I wonder if a ParquetRecordWriter might be a better idea? It would do the same thing as a processor but the record processors can read in something in any format, not just Avro. This was another impetus for having PutORC instead of ConvertAvroToORC.

**Comment by mohitgargk** [comment]
> What is the use case for having Parquet files flow through NiFi?
I have a use case where I am writing the parquet files into data lake (in azure) and also need to write them on a network storage device. The intent here is keep the parquet in flowfile, so that it can flow into any sink later on. If we don't have Convert*ToParquet (or similar processors), we would require a hop (an i/o endpoint) that may not give good performance.

**Comment by mohitgargk** [comment]
@bbende i have made the suggested changes. Please review.

**Comment by bbende** [comment]
Busy with some other things at the moment, but will take a look when I get a chance.

**Comment by mohitgargk** [comment]
@bbende Make sense ! I have merged the ParquetBuilderProperties merged in ParquetUtils in the latest commit.

**Pull request closed without merging**
