### PR TITLE
NIFI-2339 made exception statements more vague and limited to identifiers

### PR DESCRIPTION
**Pull request by joewitt**
…to identifiers only to avoid any authorization issues

### CODE REVIEW

**Comment by mcgilman** [comment]
Reviewing...

**Comment by mcgilman** [comment]
Looks like there were some checkstyle violations that we're introduced with this PR.

**Comment by joewitt** [comment]
absolutely baffling how I keep screwing up checkstyle.  I run -Pcontrib-check all the time.  Argh!  Will resolve.

**Comment by mcgilman** [comment]
Thanks @joewitt! Looks good, this has been merged to master.

**Pull request closed without merging**
