### PR TITLE
NIFI-4612: Allow AvroSchemaRegistry to disable name validation

### PR DESCRIPTION
**Pull request by mattyb149**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [x] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by pvillard31** [comment]
Code change LGTM, full build OK, merging to master, thanks @mattyb149

**Comment by AdityaSurve96** [comment]
Hello Team I am currently facing the hyphen ( dash ) issue in Apache Avro schema that we use along with Schema Registry for deserialization.   Few field names in our Avro Schema contain dashes. I need help to locate the above proposed solution i.e. how to use the AvroSchemaRegistry and the boolean value to disable the validation. I assume its not a property in the Confluent Schema Registry. Can someone share any resource which shows how to bring in AvroSchemaRegistry in picture with the Avro Schema so that I can set the property to disable the field name validation somwhere.

We Specify the .avsc files in aspring boot microservice which after compiled generated the corresponging POJOS that we use in other micro-services (spring boot apps). We do not have any other Java implementation to manipulate the avro schemas.

**Comment by mattyb149** [comment]
How do the other apps work with an invalid schema? If you need to "normalize" the names so the schema is valid (and the data is not already in Avro format), I wrote a [blog post ](https://funnifi.blogspot.com/2023/08/change-record-field-names-with.html)showing how to do that.

**Comment by AdityaSurve96** [comment]
Hi @mattyb149 , other apps dont work with invalid schema . What I mean in until now we did not have any case where avro schema field name had dash ( hiphen) in it.   But now in some use cases we do have field names with dash ( hiphen ) which does not get compiled by Avro.  So can you please help me to understand where and how can I implement / incorporate the given solution in this ticket to disable name validation.

**Pull request closed without merging**
