### PR TITLE
NIFI-11852 - CLI - connect two process groups

### PR DESCRIPTION
**Pull request by pvillard31**
# Summary

[NIFI-11852](https://issues.apache.org/jira/browse/NIFI-11852) - CLI - connect two process groups

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by pvillard31** [comment]
````
% ./cli.sh nifi pg-connect -u http://127.0.0.1:8080/nifi-api --source-pg 88cd342c-0189-1000-5dda-c0b32b993abc --source-output-port output --destination-pg 88cd4837-0189-1000-cc5c-94a25d3e2dc4 --destination-input-port input -verbose
8d38a631-0189-1000-567c-e93eb7925b14

% ./cli.sh nifi pg-connect -u http://127.0.0.1:8080/nifi-api --source-pg 88cd342c-0189-1000-5dda-c0b32b993abc --source-output-port output --destination-pg a8ea3b2c-0186-1000-bf05-34a9849ef1fe --destination-input-port input -verbose

ERROR: Error executing command 'pg-connect' : The source process group and the destination process group are not at the same level

% ./cli.sh nifi pg-connect -u http://127.0.0.1:8080/nifi-api --source-pg 88cd342c-0189-1000-5dda-c0b32b993abc --source-output-port output --destination-pg 88cd4837-0189-1000-cc5c-94a25d3e2dc4 --destination-input-port input2 -verbose

ERROR: Error executing command 'pg-connect' : Unable to find an input port with the name 'input2' in the destination process group
````

**Review by nandorsoma — APPROVED** [review]
Thanks @pvillard31 for this contribution! I've tested it, and it works as expected. One thing came to my mind. Wouldn't it make sense to make it possible to configure the same set of properties that are available on the UI? Like "Load Balancing Strategy" and "Selected Prioritizers". If not, I'm happy to merge as is.

**Comment by pvillard31** [comment]
hey @nandorsoma - thanks for the review, that could be a follow up improvement, it does make sense

**Comment by nandorsoma** [comment]
Created a follow-up ticket: [NIFI-12077](https://issues.apache.org/jira/browse/NIFI-12077)
Merging to main and support-1.x, thanks @pvillard31

**Pull request closed without merging**
