### PR TITLE
NIFI-1121 Show and hide processor properties dependent on another property.

### PR DESCRIPTION
**Pull request by mtien-apache**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Processor properties will show or hide depending on another property that is selected. 
For example, if Property A depends on Property B, then Property A should not be shown in the Configure dialog unless a value is selected for Property B._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [x] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by markap14** [comment]
Thanks @mtien-apache , will review.

**Comment by ottobackwards** [comment]
This is pretty neat.  There should be tests added for this though, for the processors that were changed etc.

**Comment by mtien-apache** [comment]
The front-end part is now working. Still need to make a few backend changes and add unit tests. @scottyaslan @markap14 Can you review? Thanks.

**Comment by scottyaslan** [comment]
LGTM +1 on the frontend code.

**Comment by markap14** [comment]
@mtien-apache I opened a PR, #4512, that addresses the remaining work on the backend, such as validation. And adds some unit/integration/system tests. It includes all of your commits as well (some squashed). OK to close this one in favor of 4512?

**Comment by mtien-apache** [comment]
@markap14 OK to close this for PR 4512. Thanks for the remaining work.

**Pull request closed without merging**
