### PR TITLE
NIFI-7728: FetchS3Object sends a flowfile to failure relationship if the given bucket or object key is empty

### PR DESCRIPTION
**Pull request by kotarot**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

This change will fix https://issues.apache.org/jira/browse/NIFI-7728

The original contributor has left working this development, I'm fixing it in this PR instead.
Previous PR: https://github.com/apache/nifi/pull/4515

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [ ] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [X] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [X] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Review by pvillard31 — COMMENTED** [review]
I'm wondering if this is really what we want. For the other flow files we're routing to ``failure``, that's because of a failure we don't "control" and a user might want to self-loop the relationship on the processor to retry the action. However, in this case, the error will never go away and I don't see why we would penalize the flow files, it does not provide any value. Ideally, I'd think of a new relationship (like ``invalid``) for this specific case but adding a new relationship would make the processor invalid after an upgrade unless we auto-terminate this new relationship by default, but that could be mean "data loss" for some users. 

What about adding an attribute like ``failure.reason`` with a default value for the cases you added and the error message from the exception for the existing cases? That would provide an option to users to use RouteOnAttribute in case of failure. Not great but I don't have a better idea. Thoughts?

**Comment by kotarot** [comment]
Thank you for looking at this change.

Assume that the "Bucket" property of FetchS3Object is set to "${bucket}" and "Object Key" property is set to "${key}". If we set `bucket = "valid-bucket-name"` and `key = "" (empty string)` in Variables in the process group, after this change the flowfile will be routed to failure instead of stucking as the current implementation. If a user set the failure relationship to self-loop, changing `key = "valid-key-name"` correctly while being penalized would fix this error, and the flowfiles would be then routed to success with fetching an S3 object successfully. I think this is the same semantic as the other kinds of errors, penalizing in this case also meaningful.

**Comment by kotarot** [comment]
In case of the variable in the incoming flowfile attributes, yes, penalizing has no meanings. So like `failure.reason` idea makes sense to me.

**Comment by pvillard31** [comment]
Yeah but would someone use variables/parameters for bucket and key in this processor? Wouldn't it always be based on flow files attributes?

**Comment by kotarot** [comment]
Yes I definitely agree with using flow files attributes is typical cases. I'll try to think over and fix the code based on the ideas.

**Pull request closed without merging**
