### PR TITLE
NIFI-7313:fix bug on 'Quote Table Identifiers'

### PR DESCRIPTION
**Pull request by wanghongqi**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Enables X functionality; fixes bug NIFI-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [x] Have you written or updated unit tests to verify your changes?
- [x] Have you verified that the full build is successful on both JDK 8 and JDK 11?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [x] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [x] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by pvillard31** [comment]
Can you revert the Splunk related change and squash your commits? Thanks @wanghongqi

**Comment by wanghongqi** [comment]
ok.I will do that

**Comment by wanghongqi** [comment]
> Can you revert the Splunk related change and squash your commits? Thanks @wanghongqi

I revert the Splunk related change

**Comment by pvillard31** [comment]
It looks good to me. Could you add a unit test to confirm that catalog and schema are correctly quoted? (cc @mattyb149 to have a second pair of eyes).

For the unit test, I'd duplicate ``testGeneratePreparedStatements`` and confirm that the generated statements are correctly quoted. The test is here: https://github.com/apache/nifi/blob/master/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/groovy/org/apache/nifi/processors/standard/TestPutDatabaseRecord.groovy#L119

**Comment by wanghongqi** [comment]
Ok,I will add a test function.

**Comment by wanghongqi** [comment]
> It looks good to me. Could you add a unit test to confirm that catalog and schema are correctly quoted? (cc @mattyb149 to have a second pair of eyes).
> 
> For the unit test, I'd duplicate `testGeneratePreparedStatements` and confirm that the generated statements are correctly quoted. The test is here: https://github.com/apache/nifi/blob/master/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/groovy/org/apache/nifi/processors/standard/TestPutDatabaseRecord.groovy#L119

I add the test,please look that

**Comment by pvillard31** [comment]
Can you rebase against master and squash your commits? Right now the PR include commits already merged to master that are unrelated to your change and this makes the PR really hard to review.

**Comment by wanghongqi** [comment]
I squash my commits,it's ok?

**Comment by pvillard31** [comment]
No it's not, at the top of the pull request you can see that it contains 13 commits, modified 73 files, adds 2046 lines of code and removes 490 lines of code which is much more than your changes alone.

Rebasing and squashing really depends on how you have your local git configured but usually I do it this way:
``git merge-base <branch name> <master>`` (example ``git merge-base NIFI-7313 apache/master``)
this returns a ``<commit ID>``
``git rebase -i <commit ID>``
it'll open a list of commits, I'd delete the ones that are not related to your work, and squash the additional commits you added (and only keep untouched the first one in the list)
then ``git push -f``
to force push the changes here.

At the end, the pull request here should only show 1 commit.

**Comment by wanghongqi** [comment]
> No it's not, at the top of the pull request you can see that it contains 13 commits, modified 73 files, adds 2046 lines of code and removes 490 lines of code which is much more than your changes alone.
> 
> Rebasing and squashing really depends on how you have your local git configured but usually I do it this way:
> `git merge-base <branch name> <master>` (example `git merge-base NIFI-7313 apache/master`)
> this returns a `<commit ID>`
> `git rebase -i <commit ID>`
> it'll open a list of commits, I'd delete the ones that are not related to your work, and squash the additional commits you added (and only keep untouched the first one in the list)
> then `git push -f`
> to force push the changes here.
> 
> At the end, the pull request here should only show 1 commit.

A ha.Thanks very muth.I squash is.It's only 1 commit!

**Comment by mattyb149** [comment]
+1 LGTM, verified the correct fully-qualified name is generated and works with PutDatabaseRecord against a real database (MySQL). Thanks for the fix! Merging to master

**Pull request closed without merging**
