### PR TITLE
NIFI-8275 Add NET_BIND_SERVICE capability to Java in Docker image

### PR DESCRIPTION
**Pull request by jlpedrosa**
#### Description of PR

By setting the capability NET_BIND_SERVICE to the java process, users can specify a low port for any of the listeners,
without requiring more privileges or running as root.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced   in the commit message?

- [X] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [X] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [x] Have you written or updated unit tests to verify your changes? (Does not apply)
- [x] Have you verified that the full build is successful on JDK 8?
- [x] Have you verified that the full build is successful on JDK 11?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [x] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [x] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by jfrazee** [comment]
@jlpedrosa Can you open a JIRA for this at http://issues.apache.org/jira/browse/NIFI ?

**Comment by jlpedrosa** [comment]
> @jlpedrosa Can you open a JIRA for this at http://issues.apache.org/jira/browse/NIFI ?

**Comment by joewitt** [comment]
it is not uncommon for spurious artifact collection failures to mess those up.  It usually still passes on other builds within the same run though so generally not a big deal.

**Comment by jlpedrosa** [comment]
Just a clarification. Adding the capability to the process, it does NOT allow the pod immediately to bind to a low port, on top of this change, the user needs to create the container (or pod if running in k8s),  with that capability. So this change is a requirement to bind to low ports, but it won't be enabled by default, users needs to allow it on the container level.

**Pull request closed without merging**
