### PR TITLE
NIFI-4019: Added support for X-Forwarded-* headers

### PR DESCRIPTION
**Pull request by mcgilman**
NIFI-4019:
- Adding support for X-Forwarded-* headers.
- Unrelated code clean up.

### CODE REVIEW

**Comment by jtstorck** [comment]
Reviewing...

**Comment by jtstorck** [comment]
@mcgilman There are a couple issues with the proxying support:
* When the proxy that sets the X-Forwarded-* headers is running on a non-standard port for HTTP or HTTPS, the "X-Forwarded-Host" header value can contain the host and the port, such as localhost:8008 or localhost:8443.
* There are some resources that are at absolute paths, like in nifi-docs.  The documentation is showing up, but the css isn't loading.
* If the NiFi service is terminated, and the NiFi client UI shows its general error page, the "home" link  does not point the browser back at the proxy's URL for NiFi.

**Comment by mcgilman** [comment]
Thanks for catching those @jtstorck! Will update.

**Comment by jtstorck** [comment]
These changes look good with a couple extra fixes, merged to master.

**Comment by mcgilman** [comment]
Yup. Thanks again!

**Pull request closed without merging**
