### PR TITLE
AbstractKiteProcessor.getSchema leaks file handles

### PR DESCRIPTION
**Pull request by jackowaya**
Close file handles when reading schema from resources or paths in AbstractKiteProcessor.getSchema

### CODE REVIEW

**Comment by joey** [comment]
+1, lgtm

**Comment by joey** [comment]
Is there a JIRA associated with this?

**Comment by jackowaya** [comment]
Yes. I screwed up making the commit message. It's https://issues.apache.org/jira/browse/NIFI-1035

**Comment by jackowaya** [comment]
Just force pushed with a message that has the jira ID in it. Hopefully that doesn't screw anything up.

**Comment by joey** [comment]
No worries, it still looks good to me :)

**Comment by rdblue** [comment]
+1, thanks for fixing this @jackowaya!

**Comment by joewitt** [comment]
looks good - am merging.  Sorry for the delay Alan

**Pull request closed without merging**
