### PR TITLE
NIFI-4912: Update jackson version to latest stable version (2.9.4)

### PR DESCRIPTION
**Pull request by derekstraka**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [X] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by jomach** [comment]
+1

**Comment by MikeThomsen** [comment]
@derekstraka You have a merge conflict now.

**Comment by derekstraka** [comment]
@MikeThomsen Thanks for the heads up.  I see that #2512 (8f66454) changed all of the pom files.  I've created a four or five PRs for different issues, but they don't seem to get reviewed.  Are there module maintainers that I should be assigning tickets+PRs to get it reviewed in a timely fashion? I can rebase it, but I don't want to have to keep revisiting it.

**Comment by joewitt** [comment]
@derekstraka thanks for contributing.  I'll evaluate this one as part of the 1.6.0 rm process.

With regard to your comment about PR reviews please know that we have a lot of outstanding PRs.  More contributions are great of course but what we need is more review/testing of outstanding PRs.  If you can help with reviews/testing it will improve overall community throughput on PR management.  Again, not discouraging you from contributing just helping you see the other side of the equation.

Thanks

**Comment by derekstraka** [comment]
@joewitt - I'd love to get more involved in the community.  It just wasn't clear how.  Is there a process for reviewing/testing or is it more ad-hoc?

**Comment by joewitt** [comment]
https://cwiki.apache.org/confluence/display/NIFI/Contributor+Guide is a good place to start.

You can search through open PRs here https://github.com/apache/nifi/pulls  If you see PRs of interest there we'd love help getting them reviewed and actually tested.  That is the long pole in many cases.  There is often some old/outdated just needing to be closed PRs but there are ones that just need some time/love to get to the finish line.  

You can also look in JIRA for open items as sometimes, though rarely, there are patches submitted the old-fashioned way via JIRA.

Thanks!

**Comment by MikeThomsen** [comment]
@derekstraka feel free to ping me on reviews for stuff that's been languishing in the backlog.

**Pull request closed without merging**
