### PR TITLE
[NIFI-2888] Display processor fill color when sufficiently zoomed out.

### PR DESCRIPTION
**Pull request by scottyaslan**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by pvillard31** [comment]
Successfully tested the PR and I'm a +1.
I am not a UI guru though, so I'll defer to someone else to check the code modifications to be sure I'm not missing something here.

**Comment by scottyaslan** [comment]
I will have an update to the PR later on today @pvillard31....please do not merge yet as this PR currently only addresses the zoomed out color of the processors. The plan is to have all items on the canvas match their birdseye view colors when sufficiently zoomed out (PG's, ports and filters).

**Comment by scottyaslan** [comment]
Ok guys....this PR has been updated and is ready for review.

**Comment by mcgilman** [comment]
Reviewing...

**Comment by mcgilman** [comment]
@scottyaslan After checking out the most recent PR I think we may want to to make a few more adjustments.

Coloring the components to align with the birdseye view takes away from the components that have explicitly been colored. I think we may want to revert back to the previous implementation for the zoomed out mode. 

Coloring the background of the Processor icon may be sufficient while retaining the current zoomed out effect. This may also make the zoomed in coloration more prominent.

Thoughts?

**Comment by scottyaslan** [comment]
Thanks for the input @mcgilman! I will close this PR so that the work can remain on this branch in case we want to revisit this later. For now I will open a new PR for NIFI-2888.

**Pull request closed without merging**
