### PR TITLE
NIFI-11410 - Upgrade a bunch of dependencies

### PR DESCRIPTION
**Pull request by pvillard31**
# Summary

[NIFI-11410](https://issues.apache.org/jira/browse/NIFI-11410)

- com.jcraft:jsch from 0.1.54 to 0.1.55
- io.swagger.core.v3:swagger-annotations from 2.2.8 to 2.2.9
- com.box:box-java-sdk from 4.0.0 to 4.0.1
- com.github.jknack:handlebars from 4.3.0 to 4.3.1
- com.github.luben:zstd-jni from 1.5.2-3 to 1.5.5-1
- com.sun.jersey:jersey-bundle from 1.19.3 to 1.19.4
- org.antlr:antlr-runtime from 3.5.2 to 3.5.3
- org.apache.ant:ant from 1.10.12 to 1.10.13
- org.apache.commons:commons-pool2 from 2.4.1 to 2.4.3
- org.apache.iotdb from 1.0.0 to 1.0.1
- org.apache.kafka:connect-api from 2.6.0 to 2.6.3
- org.apache.lucene from 8.11.1 to 8.11.2
- org.apache.solr:solr-solrj from 8.11.1 to 8.11.2
- org.apache.santuario:xmlsec from 2.3.1 to 2.3.3
- org.mariadb.jdbc:mariadb-java-client from 3.1.1 to 3.1.3
- org.springframework.boot:spring-boot-X from 2.7.9 to 2.7.10

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 11
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for continuing to work through these dependency upgrades @pvillard31!

The majority of these changes look good.

Can you pull out the Caffeine upgrade into a separate PR? Caffeine version 3 requires Java 11. We should move to that for the main branch, but first we should upgrade to the latest version 2 and backport the change. The centralization of the dependency management at the root level looks good, so if we could handle that in two steps, that would be ideal.

The rest of the dependency updates look good.

**Comment by pvillard31** [comment]
Yep, good point!

**Comment by pvillard31** [comment]
@exceptionfactory thanks for your comment about caffeine, I removed the changes from this PR and will work on two dedicated PR for this change.

**Review by exceptionfactory — APPROVED** [review]
Thanks for separating out the Caffeine upgrade @pvillard31, the rest of these incremental upgrades look good!

**Pull request closed without merging**
