### PR TITLE
NIFI-4894: Ensuring that any proxy paths are retained when querying for bulletins

### PR DESCRIPTION
**Pull request by mcgilman**
NIFI-4894:
- Ensuring that any proxy paths are retained when querying for bulletins.

### CODE REVIEW

**Comment by scottyaslan** [comment]
Reviewing...

**Comment by scottyaslan** [comment]
@mcgilman I have reviewed and built these changes and all looks good.

**Comment by jtstorck** [comment]
@mcgilman @scottyaslan I was able to reproduce the bug in master while proxying with Knox by creating a HandleHttpRequest processor with a StandardHttpContextMap controller service.  Attempting to enable the service through the UI resulted in the 404.  After applying the PR to master and restarting, I was able to go through the same steps and successfully enable the StandardHttpContextMap controller service.

+1 LGTM!

**Comment by scottyaslan** [comment]
Thanks @jtstorck! Thanks @mcgilman this has been merged to master.

**Pull request closed without merging**
