### PR TITLE
NIFI-8037 Support TLSv1.3 in SSLContextService on Java 8

### PR DESCRIPTION
**Pull request by exceptionfactory**
#### Description of PR

NIFI-8037 Updates `StandardSSLContextService` and `StandardRestrictedSSLContextService` to use the internal `TlsPlatform.getSupportedProtocols()` method to determine which protocol versions are supported as allowable values for the `TLS Protocol` property.  This approach uses runtime detection of supported protocol versions, which allows for selecting `TLSv1.3` when it is available on supported versions of Java 8 and higher.

It is important to note that various processors use `SSLContextService` in different ways, so separate work may be needed in order for particular processors to honor the `TLS Protocol` property.  This PR includes unit test updates to ensure that an `SSLContext` can be constructed using preferred protocols as indicated from the `TlsPlatform` class.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [X] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [X] Have you written or updated unit tests to verify your changes?
- [X] Have you verified that the full build is successful on JDK 8?
- [X] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [X] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by gresockj** [comment]
Code logic and style looks good to me.  I tested this out with Azul Zulu JDK 1.8.0_282, and was able to verify in Chrome that using a HandleHttpRequest processor configured with an SSL context using TLSv1.3 does indeed use TLSv1.3.

**Comment by exceptionfactory** [comment]
> Code logic and style looks good to me. I tested this out with Azul Zulu JDK 1.8.0_282, and was able to verify in Chrome that using a HandleHttpRequest processor configured with an SSL context using TLSv1.3 does indeed use TLSv1.3.

Thanks for the review @gresockj!

**Comment by thenatog** [comment]
Testing this out

**Comment by thenatog** [comment]
Looks good to me, tested this out with Java 8 OpenJDK jdk1.8.0_172 and did not see TLS v1.3 as an option in StandardRestrictedSSLContextService. Then tried Java 8 OpenJDK jdk1.8.0_261 and was able to select TLS v1.3. Also tried AdoptOpenJDK 1.8.0_265 and was able to select TLS v1.3. +1 will merge.

**Pull request closed without merging**
