### PR TITLE
NIFI-4297 Updated dependency versions

### PR DESCRIPTION
**Pull request by alopresto**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by alopresto** [comment]
I [published the results](https://gist.github.com/alopresto/df899c1e379fe48d830663313cf34db4) of `mvn dependency:tree` on my local machine, and the reviewer can verify that the only instances of `jackson-core` < 2.8.6 are:

* `nifi-gcp-processors - google-http-client-jackson2 - 2.1.3`
* `nifi-gcp-nar - google-http-client-jackson2 - 2.1.3`
* `nifi-spark-receiver - com.fasterxml.jackson.core.jackson-databind - 2.6.5`

by using the regex `jackson-core:jar:2.[^8]`. 

All unit tests pass.

**Comment by alopresto** [comment]
I ran the `mvn dependency:tree` on current `master` and compared to the output above. There are only 2 differences aside from the version upgrades:

1. `aopalliance:aopalliance:1.0` moves from `org.springframework:spring-aop:jar:4.2.4.RELEASE` to `org.springframework.security:spring-security-core:jar:4.2.3.RELEASE` but has the same version and license as currently exists.
1. `ring-cors:ring-cors:0.1.5` is a new transitive dependency brought in by `org.apache.storm:storm-core:jar:1.1.1` after it was upgraded from `1.0.1`. `ring-cors` uses the [EPL 1.0](https://eclipse.org/org/documents/epl-v10.php), which is considered [Category B by Apache](https://www.apache.org/legal/resolved.html#category-b). I believe this is acceptable from the statement:

> For small amounts of source that is directly consumed by the ASF product at runtime in source form, and for which that source is unmodified and unlikely to be changed anyway (say, by virtue of being specified by a standard), inclusion of appropriately labeled source is also permitted.

There is no existing `LICENSE` or `NOTICE` file in the `nifi-external` or `nifi-external/nifi-storm-spout` modules, which is where this code is brought in. @joewitt , please advise on proper license/notice model to follow/copy here.

**Comment by joewitt** [comment]
@mcgilman @alopresto the lack of L&N on that is because we're not publishing a bundled artifact for it (like we do with nars).  We're simply putting source up or the binary of our external but then normal dep/maven magic takes over.  So, we're ok as-is and having a cat-b dependency is still fair game.  Once someone pulls in our library (which depends on that stuff) then they would have to consider the EPL implications.  In short, i think we're good here for L&N based on andy's above assessment.

**Comment by mcgilman** [comment]
@joewitt Thanks for reviewing the L&N concerns...

@alopresto Reviewing...

**Comment by mcgilman** [comment]
@alopresto I believe the exclusions for the solr processors are incorrect. `jackson-core` has been excluded but not explicitly added. Also, I noticed that the change to `jackson-annotations` made in the root pom, affects the version of `jackson-annotations` which `solr-solrj` brings in transitively. It appears that prior to this PR it also overriding (2.6.1 vs 2.5.4). Because the use of jackson is so widespread and the behavior of dependency management with regards to transitive dependencies, I'm wondering if it makes to remove `jackson-annotations` and allow individual modules to pull it in using the `jackson.version` property introduced here. Thoughts?

**Comment by alopresto** [comment]
Thanks @mcgilman and @joewitt . I rebased against `1.5.0-SNAPSHOT master`, added the explicit dependency on `jackson-core` in `nifi-solr-processors/pom.xml` and removed `jackson-databind` from the `<dependencyManagement>` block in `nifi/pom.xml` and explicitly referenced the `${jackson.version}` variable throughout the children poms. The full build works, and I verified that not only does it compile, the project seems to be able to correctly perform JSON parsing in a variety of ways (used [this template](https://gist.github.com/alopresto/63c087854c5300f7c0763ce118c1eef6)) to verify. 

Web Server and JSON Parsing Template

I still need to evaluate if `org.codehaus.jackson:jackson-mapper-asl:1.9.13` is used anywhere, as discussion between @mcgilman and myself [revealed it is replaced by `com.fasterxml.jackson.core:jackson-core:2.9.1`](https://mvnrepository.com/artifact/org.codehaus.jackson/jackson-mapper-asl/1.9.13).

**Comment by alopresto** [comment]
Matt and I discussed and I will try to minimize further differences in order to get this merged in a working state, as he is currently upgrading the version of Jersey and it changes a lot of the jackson dependencies as well. In that vein, rather than attempting to remove the `jackson-mapper-asl` completely, I will remove it from dependency management and explicitly list the version in child poms. New commit forthcoming.

**Comment by alopresto** [comment]
I believe this is ready to be merged @mcgilman .

**Comment by mcgilman** [comment]
Thanks @alopresto! Looks good. This has been merged to master.

**Pull request closed without merging**
