### PR TITLE
NIFI-3520 Refactoring instance class loading

### PR DESCRIPTION
**Pull request by bbende**
This PR addresses the issue mentioned on NIFI-3520 regarding using the "Additional Resources" property on the HDFS processors. The fix is a fundamental refactoring of how the instance class loading isolation works.

Changes:
- Fixing FlowController to use appropriate class loader when instantiating processor
- Updating ExtensionManager to leverage new MANIFEST entry to know when to stop including resources from parent class loaders
- Adding ReloadComponent interface and refactoring instance class loading to use it
- Fixing FetchHDFS issue with TDE by using ugi.doAs

### CODE REVIEW

**Comment by mcgilman** [comment]
Will review...

**Comment by mcgilman** [comment]
@bbende The code changes look good. However, I think the implication of the using the `RequiresInstanceClassLoading` annotation with the `cloneDuringInstanceClassLoading` flag on an NAR could lead to some confusing deployments. I think the confusion will come from the fact that the flag on the NAR will only be honored when the entire chain from the component that `RequiresInstanceClassLoading` is also flagged. Rather than trying to identify cases that could be problematic like forgetting the flag in a NAR in the chain or setting the flag on a NAR that contains a service API, should we investigate a way to automatically clone when possible?

**Comment by bbende** [comment]
@mcgilman Thanks for the review. I definitely agree that the current use of `cloneDuringInstanceClassLoading` allows for some confusing situations to arise and makes it challenging for the framework to try and prevent incorrect/unexpected behavior.

Thinking about this some more... the main reason for creating that flag was because at component creation time we only have the class name (String) and bundle for the component, and we need to make a decision about how far to go up the class loader hierarchy when cloning resources. 

If we had an instance of the component already then we could use the same logic we have in other places where we look at the property descriptors that reference controller service APIs, and determine which bundle they came from, and then stop cloning resources when that bundle is reached. We already have temp instances of every component when performing the service loading so we could potentially cache these instances to do a lookup by className+bundle, and possibly even replace a lot of our other temp component creation with look ups to these temp instances.

If we did the above we would be more aggressively cloning class loader resources, essentially always cloning until we see controller service API references. For cases where we don't want this behavior we could possibly change the meaning of `cloneDuringInstanceClassLoading`. It could instead be used on the NAR where the component with `@RequiresInstanceClassLoading` lives to indicate that the ancestor resources should be considered (stopping at first CS API as described above). If `cloneDuringInstanceClassLoading` isn't provided or is set to false, then a component with `@RequiresInstanceClassLoading` only gets a copy of it's own NAR resources.

Example 1 - `PutHDFS` has `@RequiresInstanceClassLoading` and `nifi-hadoop-nar` has `cloneDuringInstanceClassLoading` set to true, so the `InstanceClassLoader` for `PutHDFS` gets all the resources from `nifi-hadoop-nar` back to the first NAR that has a CS API referenced by` PutHDFS`, or back to `nifi-jetty-nar` (exclusive).

Example 2 - `HBaseClientService_1_1_2` has `@RequiresInstanceClassLoading` and `nifi-hbase-client-service-1-1-2-nar` does not have `cloneDuringInstanceClassLoading`, so the `InstanceClassLoader` for `HBaseClientService_1_1_2` gets only the resources from `nifi-hbase-client-service-1-1-2`.

Thoughts?

**Comment by mcgilman** [comment]
I think the proposed solution will offer clear, concise rules for when resources are cloned. It also offers further granularity has it puts the cloning of the parent resources in control of the extension. The only downside is that when specified the entire ancestry will be cloned until a referenced service API is encountered. However, this downside is outweighed by the benefits of component-based cloning when the flag was previously specified on the entire parent nar and would affect all descendent components that required instance classloading even if they didn't actually need it.

**Comment by bbende** [comment]
@mcgilman I rebased and squashed the commits, this PR now reflects all the changes described in the previous discussion/comments above. Let me know of any questions or anything else to update.

**Comment by mcgilman** [comment]
Thanks will review...

**Comment by mcgilman** [comment]
Thanks @bbende. This looks good. It has been merged to master.

**Pull request closed without merging**
