### PR TITLE
NIFI-12753 updating various github actions versions

### PR DESCRIPTION
**Pull request by joewitt**
# Summary

[NIFI-12753](https://issues.apache.org/jira/browse/NIFI-12753)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by joewitt** [comment]
Actually the build passes for all areas but we do see in the codecov step of the ci-workflow

Error: Codecov token not found. Please provide Codecov token with -t flag.
Warning: Codecov: Failed to properly create commit: The process '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov' failed with exit code 1

**Comment by joewitt** [comment]
I'm not sure on next steps for codecov.  I see how to get our apache/nifi token but not familiar with next steps.

**Review by exceptionfactory — COMMENTED** [review]
Thanks for updating the various action versions @joewitt. In the interest of making progress, one option could be to leave the Codecov action as it stands for now, and then address that separately.

GitHub supports repository secrets, but creating an entry probably requires coordination with the Apache Infrastructure Team.

**Review by exceptionfactory — APPROVED** [review]
On closer review and discussion with @joewitt, the Codecov action is working as expected when running on the Apache NiFi repository, so this looks good. +1 merging

**Pull request closed without merging**
