### PR TITLE
NIFI-4814 - Add distinctive attribute to S2S reporting tasks

### PR DESCRIPTION
**Pull request by pvillard31**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by pvillard31** [comment]
I'll need to update this PR if #2430 is merged first.

**Comment by mattyb149** [comment]
Should we add the ID as well? The name may not be unique, which although that can be used strategically to "group" things with RouteOnAttribute, it's not exactly "distinct". The onus could be on the user to uniquely name their reporting tasks, but if they had access to both attributes, they could do different levels of grouping, filtering, etc.

**Comment by pvillard31** [comment]
Yes you're right, I'll add the UUID as well!

**Comment by mattyb149** [comment]
Also, not required but it might be a good idea to add the type as well. Either way, let me know and I'll merge

**Comment by pvillard31** [comment]
Yep, there could be some situations where it would be useful. Added! Thanks!

**Comment by mattyb149** [comment]
Ugh, bad news. The Reporting Task name, although available in the UI, is only set on the ReportingTask itself during initialize(), which is only called the first time the ReportingTask is instantiated. This means if you change the name of the ReportingTask and restart it, it is the original name that is reported in your name attribute above. However if you restart NiFi it will pick up the new name.  That's not your fault, it's a bug; but I wonder if we should bring this in before or after any fix for that part?

**Comment by mattyb149** [comment]
I've written [NIFI-4816](https://issues.apache.org/jira/browse/NIFI-4816) to cover the name issue.

**Comment by mattyb149** [comment]
+1 LGTM, ran all three reporting tasks and verified the attributes are present and correct. Thanks for the improvement! Merging to master

**Pull request closed without merging**
