### PR TITLE
NIFI-8471 Parameter Contexts - show referencing process groups

### PR DESCRIPTION
**Pull request by s9514171**
#### Description of PR

[https://issues.apache.org/jira/browse/NIFI-8471](https://issues.apache.org/jira/browse/NIFI-8471)
Improve the UI for list of all the process groups that are referencing this parameter context

image

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [X] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [X] Have you verified that the full build is successful on JDK 8?
- [X] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Review by pvillard31 — CHANGES_REQUESTED** [review]
Hi @s9514171 - thanks for the pull request!

It seems to be working as expected for most of it. Example:

Screenshot 2021-05-04 at 18 51 13

However:
- it's not showing the process groups that are referencing the parameter context but without any component using any of the parameters. I guess that's OK but I think it could also be useful to have the information about process groups referencing a parameter context even if they are not actually using any of the parameters. More like an improvement thought.
- I do see an issue though. When opening the parameter context for the first time, I see this:
Screenshot 2021-05-04 at 18 51 33
As you can see, my parameter for the Kafka group ID is not used anywhere (this is expected). Then I select my Kafka brokers parameter and I see the referencing components (see first screenshot). I click OK and then open my parameter context again, I see this:
Screenshot 2021-05-04 at 19 05 44
which is not correct because it shows that my parameter for consumer group id is used where the broker parameter is used. So there is something wrong somewhere.

**Comment by s9514171** [comment]
@pvillard31 I’m sorry I didn’t make it clear in the description of my changes. 
the change show in the picture below.

I display all reference processors on the SETTINGS tab, mainly I think if add them in PARAMETERS tab that will be too mass

the bug you mentioned seems cause by another commit, but easy to fix, should I fix it directly or create another JIRA to fix it?

image

**Comment by pvillard31** [comment]
Oh my bad :-D
Makes much more sense now! Will have another look.
For the bug I mentioned another JIRA/PR would be preferred.
Thanks!

**Comment by s9514171** [comment]
@pvillard31 I have created another JIRA and the pull request for the bug [https://github.com/apache/nifi/pull/5060](url)
Thanks

**Review by pvillard31 — APPROVED** [review]

**Comment by pvillard31** [comment]
I had another look today and it's looking good to me. Maybe someone like @mcgilman or @moranr can also have a quick look (as I'm not familiar with the UI code) just to confirm I didn't miss anything obvious.

**Comment by scottyaslan** [comment]
@s9514171 thanks for this commt. I am a +1!

**Pull request closed without merging**
