### PR TITLE
UI inconsistencies

### PR DESCRIPTION
**Pull request by mcgilman**
NiFi-2468:
- Addressing numerous inconsistencies throughout the UI (button placement above tables, timestamp styles, etc)

### CODE REVIEW

**Comment by moranr** [comment]
Overall it looks good @mcgilman but I think one item was overlooked. For Process Group Config, the Add Controller Service button is still on top of the tabs. Just need to move below like the others.

**Comment by mcgilman** [comment]
Thanks @moranr. Will update shortly.

**Comment by mcgilman** [comment]
I'm added another commit to address @moranr comments.

**Comment by moranr** [comment]
Looks good @mcgilman . Thanks!

**Comment by alopresto** [comment]
Reviewing...

**Comment by alopresto** [comment]
Squashed, merged, closed. @scottyaslan got the credit in the commit. Sorry to ruin your stats, @mcgilman.

**Pull request closed without merging**
