### PR TITLE
NIFI-7486 Make InvokeHttp authentication properties able to read from variables.	

### PR DESCRIPTION
**Pull request by adarmiento**
#### Description of PR

* InvokeHTTP Basic HTTP credentials support variable registry

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically `master`)?

- [X] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [X] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by pvillard31** [comment]
Hey @adarmiento - does it really makes sense now that we have the parameters concept in NiFi? Besides variables should not be used for sensitive properties so I'd definitely not recommend using a variable on the password property.

**Comment by adarmiento** [comment]
> Hey @adarmiento - does it really makes sense now that we have the parameters concept in NiFi? Besides variables should not be used for sensitive properties so I'd definitely not recommend using a variable on the password property.

Hello @pvillard31, I did not think about it, probably because I was still using old 1.9.2 until now. 
Probably could be a security bad choice then (I noted that also the proxy credentials allow variables, maybe we should then update those two properties for consistency)
 
Thanks for the tips anyway, I'll keep this in mind for the future

**Comment by pvillard31** [comment]
I think it's hard to remove variable support after the fact because of backward compatibility concerns (even though I'd be a +1 for removing variable support on sensitive properties). I think that (to be discussed though) when the community will start working around Apache NiFi 2.x, we would possibly remove the variables to only support parameters.

If you think that a change would still make sense, let me know and we can have a look.

**Comment by axdmoraes** [comment]
In my case, I´m running NIFI under Kubernets and the usage of variables in sensitive properties is needed to use environment variables. These type of properties are injected in the container during the execution and then can be used in NIFI. 
If it´s not supported, I need to write in each processor the user and password. 
Maybe, in version 2.x, NIFI can have a different expression language scopes. One for environment variable and other for variables.

**Comment by pvillard31** [comment]
@axdmoraes - thanks for the feedback. How is the flow published in NiFi? As part of the Docker image? via a volume? or from a NiFi Registry instance?

**Comment by axdmoraes** [comment]
Using Nifi registry instance. We use the same registry for different environments.

**Comment by pvillard31** [comment]
In that case, would it be an option to use the CLI or REST API to set the parameters values after the flow has been deployed in NiFi from the NiFi Registry. On my side, with my k8s deployments, I'm doing something looking like the below

````
# add the Registry client in NiFi (to adapt for your secured NiFi instances)
curl 'http://nifi:8080/nifi-api/controller/registry-clients' -H 'Content-Type: application/json' --data-binary '{"revision":{"version":0},"component":{"name":"NiFi Registry","uri":"http://nifi-registry:18080/nifi-registry"}}'

# Deploy the flow in NiFi (add the logic to retrieve the bucket/flow/version)
/opt/nifi/nifi-toolkit-1.11.4/bin/cli.sh nifi pg-import -u http://nifi:8080 --bucketIdentifier $bucketID --flowIdentifier $flow --flowVersion $version

# Get the parameter context ID
paramContextID=`/opt/nifi/nifi-toolkit-1.11.4/bin/cli.sh nifi list-param-contexts -u http://nifi:8080 -ot json | grep -v cli.sh | jq -r '.parameterContexts[].id'`

# Set the parameters values (you can do something dynamic based on your needs)
/opt/nifi/nifi-toolkit-1.11.4/bin/cli.sh nifi set-param -u http://nifi:8080 --paramContextId $paramContextID --paramName MY_PARAMETER --paramValue MY_VALUE

# Start the controller services (add your logic to retrieve the PG ID)
/opt/nifi/nifi-toolkit-1.11.4/bin/cli.sh nifi pg-enable-services -u http://nifi:8080 --processGroupId $pgid

# Start the process group (add your logic to retrieve the PG ID)
/opt/nifi/nifi-toolkit-1.11.4/bin/cli.sh nifi pg-start -u http://nifi:8080 --processGroupId $pgid
````

**Comment by axdmoraes** [comment]
Thanks for the suggestion. I will try. We were using version 1.9.2 and I didn't know about parameters context.

**Pull request closed without merging**
