### PR TITLE
NIFI-5600 - Restore node location display on queue listing

### PR DESCRIPTION
**Pull request by pvillard31**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by pvillard31** [comment]
@mcgilman @scottyaslan - friendly ping to be sure I didn't do something against the purpose of NIFI-5208 (#2740)

**Comment by mcgilman** [comment]
Sorry for missing the mention... Will review

**Comment by mcgilman** [comment]
@pvillard31 Thanks for the PR! I can see what is happening here and I think a slightly different solution is required. With the introduction of NIFI-5208 we should be watching the cluster status actively so we can track the disconnected state. Because this state can change, I think we need to reconsider the columns we show when the listing is opened (not when the UI is bootstrapped). We actually have the same issue showing component state. I am going to open up another PR with this alternate solution.

**Comment by mcgilman** [comment]
Provided an alternate solution here: https://github.com/apache/nifi/pull/3055

**Comment by pvillard31** [comment]
Thanks much @mcgilman !

**Pull request closed without merging**
