### PR TITLE
[NIFI-2496] Zoom Fit now accounts for an open palette as well as the …

### PR DESCRIPTION
**Pull request by scottyaslan**
…breadcrumb bar

### CODE REVIEW

**Comment by mcgilman** [comment]
Reviewing..

**Comment by mcgilman** [comment]
The proposed changes seem to help introduce some space from the upper left hand corner of the canvas but don't seem to account for the entire width of the graph controls. Could it possible be an issue with the scale?

**Comment by joewitt** [comment]
@scottyaslan @mcgilman is this still relevant/open?

**Comment by scottyaslan** [comment]
@mcgilman @joewitt it appears as though this approach does something to adjust the zoom behavior but is not solving the root of the problem. I am closing this PR and cancelling the patch. We will need to revisit the issue...

**Pull request closed without merging**
