### PR TITLE
NIFI-4172: renamed ClusteSummaryEntity to ClusterSummaryEntity

### PR DESCRIPTION
**Pull request by m-hogue**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by mcgilman** [comment]
Thanks for the PR @m-hogue. I almost made this fix myself awhile back and held off. Technically, this class is part of a domain model for the REST API. Folks should be able to use this model in conjunction with frameworks like Jersey or RestEasy to interact with the REST API. Because of this, we treat this as another public API and we don't introduce breaking changes outside of major releases. 

Fortunately, the typo is not visible to folks consuming the REST API without our DTO domain model (through curl for instance).

**Comment by m-hogue** [comment]
Ah, okay. I'd thought the potential for this to be a breaking API change prior to making the fix, but I was thinking from a REST API perspective since the response type isn't part of a json response.

Feel free to close this. It's fairly trivial, so it's easy to do again prior to a major release. Thanks!

**Comment by mcgilman** [comment]
I've updated the fix version on the JIRA so we'll catch it for 2.0.0. Unfortunately, I cannot close the PR without a commit. Only the person that created the PR can do so. Do you mind closing? Thanks!

**Comment by m-hogue** [comment]
Closing, to be merged for 2.0.0.

**Pull request closed without merging**
