### PR TITLE
NIFI-11555-Upgrade-apacheds-all-to-2.0.0.AM26

### PR DESCRIPTION
**Pull request by jbalchan**
# Summary

[NIFI-00000](https://issues.apache.org/jira/browse/NIFI-00000)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 11
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by jbalchan** [comment]
@exceptionfactory  Could you please review it.

**Comment by jbalchan** [comment]
@exceptionfactory , I'm sorry about that. I had updated M24 to M26. 
But as you suggested, the latest available in maven repository is AM26.
I have updated to that now.

Could you please review

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
@jbalchan, the Surefire plugin upgrade did not appear to resolve the issue, so it is probably best to back out that change and evaluate the source of the problem.

**Comment by jbalchan** [comment]
Sure @exceptionfactory . I have backed out that surefire plugin upgrade change. I'll look deeper into the logs.

**Comment by exceptionfactory** [comment]
Thanks for your work on this @jbalchan. It appears that more recent versions of the Apache DS All JAR introduced issues with manifest signatures. On further investigation, the library is no longer used, so I created a new Jira issue and a separate pull request to remove the references. This was helpful for highlighting the opportunity to remove the dependency.

Closing in favor of #7264.

**Comment by jbalchan** [comment]
Sure. Thanks @exceptionfactory.

**Pull request closed without merging**
