### PR TITLE
NIFI-8472 Add NGSIToMongo processor and NGSI libraries

### PR DESCRIPTION
**Pull request by anmunoz**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

This processor allows persisting historic context data into MongoDB using NGSI format in any FIWARE ecosystem.

Thus, this code provides the capability to use a custom processor for receiving NGSI notifications and store this data into a MongoDB database using the NGSI data structure convention for creating the Documents, collections, and databases according to the data received in the notification.

[NIFI-8472](https://issues.apache.org/jira/browse/NIFI-8472)

_Enables NGSI functionality; fixes bug NIFI-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [ ] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [X] Have you verified that the full build is successful on JDK 11?
- [X] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [X] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by MikeThomsen** [comment]
After reviewing your docs a little bit, I would recommend closing out this PR and releasing the processors under your repository at a release cadence that makes sense for your project.

**Comment by anmunoz** [comment]
Hello Mike,

Thanks for your quick review. Just to give you a little context, we had discussed this contribution in the NiFi mailing list a few months ago and as a result, we received feedback that this could be a good contribution to the NiFi project. Due to this reason, we are creating this pull request.

Moreover, this initiative is promoted by FIWARE foundation which has a huge number of members in many countries that are adopting this technology. Even, some of this software is part of the core building blocks promoted by the CEF Telecom https://ec.europa.eu/inea/en/connecting-europe-facility/cef-telecom for contributing to the creation of a European ecosystem of interoperable and interconnected digital services.

Maybe @jason-fox member of the FIWARE foundation could help to clarify the dimension of this contribution for the FIWARE's as well as NiFi's community.

**Comment by joewitt** [comment]
First it is great that there is a desire to collaborate/contribute and certainly it looks like an interesting project/effort.

I'll also share the view that Mike and David have put here.  This seems ideal to host by the draco project.  We can put it on our list of externally supported/made available components for people to use as they like.

**Comment by anmunoz** [comment]
Thank you so much to all of you for your feedback, for us sound very interesting to be included in the externally supported component list. Please, what is the procedure for materializing the inclusion of our components in that list, and where is the pointer for checking the external supported components?

**Comment by anmunoz** [comment]
Hello @joewitt,

Please, can you help us with any information about how to included our components in the externally supported component list?

**Comment by joewitt** [comment]
Hello. We would update this page here.   https://cwiki.apache.org/confluence/display/NIFI/Community+Contributions

Just have your stuff in a github repo with licensing, readme, and have the artifacts published to some publicly accessible artifact repository and you should be in good shape.

Feel free to tell us what you'd like in each of those boxes and we'd be happy to help people know about it/point to it.     Going to close this PR and JIRA based on the discussion thus far.

Thanks

**Pull request closed without merging**
