### PR TITLE
NIFI-9625 Refactor Distributed Cache Server and Client Tests

### PR DESCRIPTION
**Pull request by exceptionfactory**
#### Description of PR

NIFI-9625 Refactors the `TestServerAndClient` class into separate unit test classes for Distributed Set Cache Server and Distributed Map Cache Server. The refactored classes leverage standard JUnit 5 `BeforeEach` and `AfterEach` annotations to configure and stop server instances in a reliable manner. Additional changes include wrapping communication handling in try-finally blocks to ensure that test methods close client instances.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [X] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [X] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by joewitt** [comment]
Cool thanks David.  Will give this a run on Java 11 builds and several on Java8

**Comment by joewitt** [comment]
[ERROR] Errors:
[ERROR]   TestDistributedMapServerAndClient.setRunner:70 » IllegalArgument File system e...
[ERROR]   TestDistributedMapServerAndClient.setRunner:70 » IllegalArgument File system e...
[ERROR]   TestDistributedMapServerAndClient.setRunner:70 » IllegalArgument File system e...
[ERROR]   TestDistributedMapServerAndClient.setRunner:70 » IllegalArgument File system e...
[ERROR]   TestDistributedSetServerAndClient.setRunner:63 » IllegalArgument File system e...
[ERROR]   TestDistributedSetServerAndClient.setRunner:63 » IllegalArgument File system e...
[ERROR]   TestDistributedSetServerAndClient.setRunner:63 » IllegalArgument File system e...
[ERROR]   TestDistributedSetServerAndClient.setRunner:63 » IllegalArgument File system e...
[ERROR]   TestDistributedSetServerAndClient.setRunner:63 » IllegalArgument File system e...
[INFO]
[ERROR] Tests run: 22, Failures: 0, Errors: 9, Skipped: 0

**Comment by joewitt** [comment]
Error:  Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.057 s <<< FAILURE! - in org.apache.nifi.distributed.cache.server.set.TestDistributedSetServerAndClient
Error:  org.apache.nifi.distributed.cache.server.set.TestDistributedSetServerAndClient.testLimitServiceReadSize  Time elapsed: 0.028 s  <<< ERROR!
java.lang.IllegalArgumentException: File system element for parameter 'directory' does not exist: 'target/cache-data'
	at org.apache.nifi.distributed.cache.server.set.TestDistributedSetServerAndClient.setRunner(TestDistributedSetServerAndClient.java:63)

Error:  org.apache.nifi.distributed.cache.server.set.TestDistributedSetServerAndClient.testPersistentSetServerAndClientWithLFUEvictions  Time elapsed: 0.002 s  <<< ERROR!
java.lang.IllegalArgumentException: File system element for parameter 'directory' does not exist: 'target/cache-data'
	at org.apache.nifi.distributed.cache.server.set.TestDistributedSetServerAndClient.setRunner(TestDistributedSetServerAndClient.java:63)

Error:  org.apache.nifi.distributed.cache.server.set.TestDistributedSetServerAndClient.testPersistentSetServerAndClient  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalArgumentException: File system element for parameter 'directory' does not exist: 'target/cache-data'
	at org.apache.nifi.distributed.cache.server.set.TestDistributedSetServerAndClient.setRunner(TestDistributedSetServerAndClient.java:63)

Error:  org.apache.nifi.distributed.cache.server.set.TestDistributedSetServerAndClient.testPersistentSetServerAndClientWithFIFOEvictions  Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalArgumentException: File system element for parameter 'directory' does not exist: 'target/cache-data'
	at org.apache.nifi.distributed.cache.server.set.TestDistributedSetServerAndClient.setRunner(TestDistributedSetServerAndClient.java:63)

Error:  org.apache.nifi.distributed.cache.server.set.TestDistributedSetServerAndClient.testNonPersistentSetServerAndClient  Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalArgumentException: File system element for parameter 'directory' does not exist: 'target/cache-data'
	at org.apache.nifi.distributed.cache.server.set.TestDistributedSetServerAndClient.setRunner(TestDistributedSetServerAndClient.java:63)

Error:  Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.01 s <<< FAILURE! - in org.apache.nifi.distributed.cache.server.map.TestDistributedMapServerAndClient
Error:  org.apache.nifi.distributed.cache.server.map.TestDistributedMapServerAndClient.testLimitServiceReadSize  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalArgumentException: File system element for parameter 'directory' does not exist: 'target/cache-data'
	at org.apache.nifi.distributed.cache.server.map.TestDistributedMapServerAndClient.setRunner(TestDistributedMapServerAndClient.java:70)

Error:  org.apache.nifi.distributed.cache.server.map.TestDistributedMapServerAndClient.testOptimisticLock  Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalArgumentException: File system element for parameter 'directory' does not exist: 'target/cache-data'
	at org.apache.nifi.distributed.cache.server.map.TestDistributedMapServerAndClient.setRunner(TestDistributedMapServerAndClient.java:70)

Error:  org.apache.nifi.distributed.cache.server.map.TestDistributedMapServerAndClient.testNonPersistentMapServerAndClient  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalArgumentException: File system element for parameter 'directory' does not exist: 'target/cache-data'
	at org.apache.nifi.distributed.cache.server.map.TestDistributedMapServerAndClient.setRunner(TestDistributedMapServerAndClient.java:70)

Error:  org.apache.nifi.distributed.cache.server.map.TestDistributedMapServerAndClient.testBackwardCompatibility  Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalArgumentException: File system element for parameter 'directory' does not exist: 'target/cache-data'
	at org.apache.nifi.distributed.cache.server.map.TestDistributedMapServerAndClient.setRunner(TestDistributedMapServerAndClient.java:70)

Error:  Errors: 
Error:    TestDistributedMapServerAndClient.setRunner:70 » IllegalArgument File system e...
Error:    TestDistributedMapServerAndClient.setRunner:70 » IllegalArgument File system e...
Error:    TestDistributedMapServerAndClient.setRunner:70 » IllegalArgument File system e...
Error:    TestDistributedMapServerAndClient.setRunner:70 » IllegalArgument File system e...
Error:    TestDistributedSetServerAndClient.setRunner:63 » IllegalArgument File system e...
Error:    TestDistributedSetServerAndClient.setRunner:63 » IllegalArgument File system e...
Error:    TestDistributedSetServerAndClient.setRunner:63 » IllegalArgument File system e...
Error:    TestDistributedSetServerAndClient.setRunner:63 » IllegalArgument File system e...
Error:    TestDistributedSetServerAndClient.setRunner:63 » IllegalArgument File system e...
Error:  Tests run: 22, Failures: 0, Errors: 9, Skipped: 0

**Comment by exceptionfactory** [comment]
Thanks for the feedback @joewitt, it looks like the local test run was relying on the previous existence of the cache data directory. I pushed an update to check for the existence of the directory before running the clean method.

**Comment by joewitt** [comment]
java 11 now happy.  will give java 8 many rounds of fun and will comment back

**Comment by joewitt** [comment]
First try on Java 8

[ERROR] Failures:
[ERROR]   DistributedSetCacheTest Multiple Failures (2 failures)
	org.opentest4j.AssertionFailedError: Failed to enable Controller Service DistributedSetCacheServer[id=org.apache.nifi.distributed.cache.server.DistributedSetCacheServer] due to java.net.BindException: Address already in use
	java.lang.NullPointerException: <no message>
[INFO]
[ERROR] Tests run: 22, Failures: 1, Errors: 0, Skipped: 0

**Comment by joewitt** [comment]
<system-err><![CDATA[java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:461)
        at sun.nio.ch.Net.bind(Net.java:453)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:222)
        at java.nio.channels.ServerSocketChannel.bind(ServerSocketChannel.java:157)
        at org.apache.nifi.distributed.cache.server.AbstractCacheServer.start(AbstractCacheServer.java:76)
        at org.apache.nifi.distributed.cache.server.DistributedCacheServer.startServer(DistributedCacheServer.java:98)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.nifi.util.ReflectionUtils.invokeMethodsWithAnnotation(ReflectionUtils.java:68)
        at org.apache.nifi.util.StandardProcessorTestRunner.enableControllerService(StandardProcessorTestRunner.java:725)
        at org.apache.nifi.distributed.cache.server.set.DistributedSetCacheTest.beforeClass(DistributedSetCacheTest.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:43)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
        at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:82)
        at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:73)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)

**Comment by exceptionfactory** [comment]
Interesting that the `DistributedSetCacheTest` happened to fail, since it is not directly related to these changes. However, it looks like it uses the default port, which could be in use, so I will change that to use a random available port as well.

**Comment by exceptionfactory** [comment]
Pushed another commit that improves the behavior of the other test classes in the `nifi-distributed-cache-server` module to use `NetworkUtils.getAvailableTcpPort()` to avoid unexpected conflicts.  Since multiple test classes were using the default port number, concurrent execution could result in the `BindException`.

**Pull request closed without merging**
