### PR TITLE
NIFI-11874: apply new layout of Process Group configuration into two columns

### PR DESCRIPTION
**Pull request by markobean**
# Summary

[NIFI-11874](https://issues.apache.org/jira/browse/NIFI-11874)
UI modification for the layout of Process Group configuration. It separates the increasing number of configuration options into two columns. This presents better in the UI and keeps the Apply button easily accessible without the need to scroll (for most display resolutions.)

Includes additional details for several of the Process Group properties to explicitly clarify that the default connections settings apply only to new connections - not existing connections.

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X] Pull Request based on current revision of the `main` branch
- [X] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [X] Build completed using `mvn clean install -P contrib-check`
  - [X] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — COMMENTED** [review]
Thanks for the contribution @markobean.

The initial pull request has some merge conflicts, most likely due to a recent change on the main branch.

It is important to note that the pull request introducing Stateless Execution mode for Process Groups will also introduce some changes to this screen.

@mcgilman and @mtien-apache have evaluated some of these changes, and after the Stateless Execution pull request is merged, that would be a better time to consider the overall layout of the Process Group dialog. Some of the changes will be specific to the main branch, so we may also need to consider the version 1 branch separately.

**Comment by mcgilman** [comment]
Thanks for the PR @markobean! As @exceptionfactory mentioned there are some further additions to this page currently under development. There is absolutely a need to update the layout here to avoid the concerns around scrolling as you've mentioned. It may even make sense to introduce a third column and ensure that appropriate fields are co-located.

**Comment by markobean** [comment]
> 

Do you know when the additions to this dialog are expected to be added? Is there a Pull Request yet?

**Comment by exceptionfactory** [comment]
@markobean With the changes merged for the Stateless execution pull request, this pull request could be rebased and re-evaluated. However, given the number of changes, it is probably better to consider the overall approach.

**Comment by markobean** [comment]
Closing this PR. I will refactor given the changes in NIFI-11556 and resubmit a new PR.

**Pull request closed without merging**
