### PR TITLE
NIFI-3650 - Adjust travis to forcefuly remove $HOME/.m2/repository/or…

### PR DESCRIPTION
**Pull request by trixpan**
…g/apache/nifi/

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [X] ~~~Have you written or updated unit tests to verify your changes?~~~
- [X] ~~~If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?~~~ 
- [X] ~~~If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?~~~
- [X] ~~~If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?~~~
- [X] ~~~If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?~~~

### For documentation related changes:
- [X] ~~~Have you ensured that format looks appropriate for the output in which it is rendered?~~~

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by trixpan** [comment]
@apiri @jfrazee - hopefully this will work.

**Comment by apiri** [comment]
@trixpan Do you think it makes more sense to use the before_cache directive instead?  (https://docs.travis-ci.com/user/caching/#before_cache-phase)  May just be struggling in the morning, but I believe this is likely the preferred approach.

**Comment by jfrazee** [comment]
@apiri I think there might be two tasks here to make sure everything is copacetic: (1) remove that part of the tree so we don't bother caching it/downloading it period and (2) removing it before the build just to make sure it's not there (will need that the first time this runs anyway if we don't invalidate the cache).

So I think it makes sense to add this but also keep the other.

**Comment by jfrazee** [comment]
@apiri Oh, I see now. You're saying move the one in `script` to `before_cache`.

**Comment by trixpan** [comment]
@apiri good catch. I wasn't aware of that feature. I pushed a modified version. let me know what you think

**Comment by trixpan** [comment]
I am obviously happy to remove the pre-build cache "rm -rf" but since it should not return error, so I reckon we can leave it there as a safety mechanism in case before_cache fails

**Comment by apiri** [comment]
@trixpan don't think removing it is necessary by any means.  I also find it hard to say exactly how all these Travis options play out, but I think this is a step in the right direction.  Scientific Method at its finest!  Anyway, changes look good and I shall merge it.

**Pull request closed without merging**
