### PR TITLE
NIFI-3056 Updated User Guide screenshot and text with latest UI color…

### PR DESCRIPTION
**Pull request by thesolson**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

… changes

### CODE REVIEW

**Comment by andrewmlim** [comment]
I don't think we need to replace nifi-connection-bend-points.png.  It has been updated already for the color changes.  The nifi-connection-bend-points.png included with this PR also references "endpoints" instead of "bend points".

Also, I don't think nifi-connection.png needs to be replaced either.

These connection images were updated in https://github.com/apache/nifi/pull/1234 for NIFI-2985

**Comment by andrewmlim** [comment]
processor-connection-bubble.png also doesn't need an update

**Comment by andrewmlim** [comment]
I think these are great updates for the User Guide, but I don't this PR fully covers the intent of NIFI-3056.  There are Operate Palette and context menu buttons that still require creation/replacement in the doc.

**Comment by andrewmlim** [comment]
nifi-toolbar-components.png also should not be replaced.  It is used to show a blank canvas, so with no processors, there is no need to update any colors.

**Comment by andrewmlim** [comment]
Incorporated some of my comments above and also added some additional screenshots to make PR complete.

[0001-NIFI-3056-Incorporated-feedback-and-added-additional.txt](https://github.com/apache/nifi/files/625776/0001-NIFI-3056-Incorporated-feedback-and-added-additional.txt)

**Comment by thesolson** [comment]
Hi Drew! These updates look great to me. Thanks for doing that. Please go ahead and merge as appropriate.

**Pull request closed without merging**
