### PR TITLE
NIFI-10614 blocked bouncycastle jdk15on deps. Forced jdk18on deps and…

### PR DESCRIPTION
**Pull request by joewitt**
… validated across entire build

# Summary

[NIFI-00000](https://issues.apache.org/jira/browse/NIFI-00000)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 8
  - [ ] JDK 11
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for working through these changes and making the adjustments necessary for the upgrade @joewitt!

Running a full build with optional profiles and running a standard build works as expected.

Taking a closer look at the build artifacts, however, the new bcprov-jdk18on library jumped from 6 MB to 11 MB. With multiple components bundling the library, this had a notable impact on the size of the convenience binary build, bringing it over 1.5 GB.

Researching the source of the changes, Bouncy Castle 1.72 included support for [SIKE](https://sike.org/) algorithm, which added several very large properties files accounting for multiple additional megabytes. Apparently the SIKE algorithm has already been broken, and Bouncy Castle is planning to [remove support for SIKE](https://bouncycastle.org/releasenotes.html#r1rv72) in version 1.73.

For these reasons, it seems like we should skip the upgrade to 1.72. These changes are still necessary, so one option is to upgrade to 1.71 for now, and then upgrade to 1.73 when it becomes available. With the current changes implemented for the switch from `jdk15on` to `jdk18on`, the upgrade from 1.71 to 1.73 should be easier.

What do you think?

**Comment by joewitt** [comment]
Err yep makes sense.  Let me try that and build.  Then we skip 72 and go 73.  Got ya

**Comment by joewitt** [comment]
ok @exceptionfactory i think we're cookin.  Had to update iceberg but otherwise it looks better.

**Review by exceptionfactory — APPROVED** [review]
Thanks for making the adjustments @joewitt, a local build and start looks good with version 1.71. +1 merging

**Pull request closed without merging**
