### PR TITLE
NIFI-13323 For 1.x, Removed the instantiation of Object arrays for arguments in ComponentLog log and org.slf4j.Logger statements

### PR DESCRIPTION
**Pull request by dan-s1**
# Summary

[NIFI-13323](https://issues.apache.org/jira/browse/NIFI-13323)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [x] Build completed using `mvn clean install -P contrib-check`
  - [x] JDK ~21~ 8

### UI Contributions

- [ ] NiFi is modernizing its UI. Any contributions that update the [current UI](https://github.com/apache/nifi/tree/main/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui) also need to be implemented in the [new UI](https://github.com/apache/nifi/tree/main/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi).  

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by dan-s1** [comment]
@exceptionfactory I wanted to restart the MacOS build as the failure seems unrelated to the code I changed but there is no icon for me on the right hand side of that build  when I navigate to under checks that would allow me to restart it. Please advise. Thanks!

**Comment by dan-s1** [comment]
@exceptionfactory I have made the changes to the 1.x branch to remove the instantiated Object arrays in log statements. I want to just make sure this PR is not to big as in addition to the two files already done I ended up changing 296 files (so in total this PR will be changes to 298 files). Please advise.

**Comment by exceptionfactory** [comment]
> @exceptionfactory I have made the changes to the 1.x branch to remove the instantiated Object arrays in log statements. I want to just make sure this PR is not to big as in addition to the two files already done I ended up changing 296 files (so in total this PR will be changes to 298 files). Please advise.

@dan-s1, I'm not quite following the concern. If you have the changes required for the 1.x branch, I would go ahead and push them to this branch.

**Comment by dan-s1** [comment]
@exceptionfactory I just thought a review of ~300 files may be too big for one review.

**Comment by exceptionfactory** [comment]
> @exceptionfactory I just thought a review of ~300 files may be too big for one review.

I see, thanks for the consideration. It is large, but we have had larger, and for something like this, it seems acceptable to bundle the changes together.

**Comment by exceptionfactory** [comment]
> @exceptionfactory In `PutElasticsearchHttp` on line 252 `logger.error("No value for index in for {}, transferring to failure", id_attribute, file);` there is only one parameter (`{}`) specified in the logging statement yet there are two parameter arguments ( `id_attribute, file`) given.
> 
> should the log statement be `logger.error("No value for index in {} for {}, transferring to failure", id_attribute, file);` ?

@dan-s1 On further consideration, I'm not sure it is worth back-porting this change. Especially for this type of syntax change, there is very little value in bringing it over, given the current focus on getting 2.0 finalized.

**Comment by exceptionfactory** [comment]
Of note, the system-tests failure on Ubuntu Java 17 is not related to these changes, so that would be worth a separate evaluation.

**Pull request closed without merging**
