### PR TITLE
NIFI-5479 - Fixed up dependencies to remove the WARNs caused by the A…

### PR DESCRIPTION
**Pull request by thenatog**
…nnotationParser in Jetty.

NIFI-5479 - Deleted instead of commented out.

NIFI-5479 - Removed empty line.

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by thenatog** [comment]
Let me know whether the way I've changed these dependencies is acceptable. The dependencies that were modified were causing WARN messages to be shown when NiFi started, for example:

```
2018-09-26 14:07:54,806 WARN [NiFi Web Server-21] o.e.jetty.annotations.AnnotationParser javax.inject.Provider scanned from multiple locations: jar:file:///.../.../.../nifi/nifi-assembly/target/nifi-1.8.0-SNAPSHOT-bin/nifi-1.8.0-SNAPSHOT/work/jetty/nifi-update-attribute-ui-1.8.0-SNAPSHOT.war/webapp/WEB-INF/lib/javax.inject-1.jar!/javax/inject/Provi
der.class, jar:file:///.../.../.../nifi/nifi-assembly/target/nifi-1.8.0-SNAPSHOT-bin/nifi-1.8.0-SNAPSHOT/work/jetty/nifi-update-attribute-ui-1.8.0-SNAPSHOT.war/webapp/WEB-INF/lib/javax.inject-2.5.0-b42.jar!/javax/inject/Provider.class
```

This was a result of the Jetty AnnotationParser scanning all classes for annotations. It would add these to a list of scanned classes, and if a new class is scanned which has a previous entry it emits a warning. 

We saw these warnings for a few reasons:
* servlet-api was resolving as 'compile' rather than 'provided', causing it to be included in two places and then scanned twice.
* Some libraries were transitive dependencies with older versions.
* Some transitive dependencies were what appeared to be repackaged dependencies ie. bundled in a different package name but the same set of classes within.

**Comment by joewitt** [comment]
reviewing

**Comment by joewitt** [comment]
I still see this one 

2018-10-04 10:36:50,626 WARN [main] o.e.jetty.annotations.AnnotationParser Unknown asm implementation version, assuming version 393216

Did you see it?

**Comment by thenatog** [comment]
I did see that one, let me figure out what happened with that.

**Comment by thenatog** [comment]
https://issues.apache.org/jira/browse/NIFI-5479?focusedCommentId=16607187&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16607187

**Comment by joewitt** [comment]
also in checking the jolt transform processor's advanced ui i get this error now

2018-10-04 11:46:42,041 WARN [NiFi Web Server-87] o.e.j.s.h.C._nifi_jolt_transform_json_ui_1_8_0_SNAPSHOT unavailable
java.lang.IllegalStateException: InjectionManagerFactory not found.
	at org.glassfish.jersey.internal.inject.Injections.lambda$lookupInjectionManagerFactory$0(Injections.java:98)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:98)
	at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:93)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:282)
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:335)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:178)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:370)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:670)
	at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:519)
	at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:803)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:530)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:724)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.lang.Thread.run(Thread.java:748)
2018-10-04 11:46:42,042 WARN [NiFi Web Server-87] org.eclipse.jetty.server.HttpChannel /nifi-jolt-transform-json-ui-1.8.0-SNAPSHOT/api/standard/processor/details
javax.servlet.ServletException: javax.servlet.ServletException: api@17a1a==org.glassfish.jersey.servlet.ServletContainer,jsp=null,order=-1,inst=false
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:724)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.servlet.ServletException: api@17a1a==org.glassfish.jersey.servlet.ServletContainer,jsp=null,order=-1,inst=false
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:691)
	at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:519)
	at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:803)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:530)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	... 17 common frames omitted
Caused by: java.lang.IllegalStateException: InjectionManagerFactory not found.
	at org.glassfish.jersey.internal.inject.Injections.lambda$lookupInjectionManagerFactory$0(Injections.java:98)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:98)
	at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:93)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:282)
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:335)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:178)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:370)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:670)
	... 34 common frames omitted

**Comment by mcgilman** [comment]
@thenatog @joewitt Happy to continue reviewing here...

**Comment by mcgilman** [comment]
Thanks @thenatog @joewitt. This has been merged to master.

**Comment by rahulbhanushali** [comment]
Hey,

I'm facing this issue while trying to upgrade from 1.6.0 to 1.8.0.

PFB the logs
```WARN [main] o.e.jetty.annotations.AnnotationParser Unknown asm implementation version, assuming version 393216
2018-11-30 15:36:58,500 WARN [Process Cluster Protocol Request-2] org.apache.nifi.io.socket.SocketListener Dispatching socket request encountered exception due to: java.lang.NullPointerException
java.lang.NullPointerException: null
2018-11-30 15:36:58,500 WARN [Process Cluster Protocol Request-1] org.apache.nifi.io.socket.SocketListener Dispatching socket request encountered exception due to: java.lang.NullPointerException
java.lang.NullPointerException: null
2018-11-30 15:36:58,647 WARN [main] o.a.nifi.controller.StandardFlowService Failed to connect to cluster due to: java.lang.NullPointerException```

This are WARN logs but the node doesn't connect to the cluster when doing a rolling restart of the servers.

**Comment by thenatog** [comment]
> Hey,
> 
> I'm facing this issue while trying to upgrade from 1.6.0 to 1.8.0.
> 
> PFB the logs
> 
> ```
> 2018-11-30 15:36:58,500 WARN [Process Cluster Protocol Request-2] org.apache.nifi.io.socket.SocketListener Dispatching socket request encountered exception due to: java.lang.NullPointerException
> java.lang.NullPointerException: null
> 2018-11-30 15:36:58,500 WARN [Process Cluster Protocol Request-1] org.apache.nifi.io.socket.SocketListener Dispatching socket request encountered exception due to: java.lang.NullPointerException
> java.lang.NullPointerException: null
> 2018-11-30 15:36:58,647 WARN [main] o.a.nifi.controller.StandardFlowService Failed to connect to cluster due to: java.lang.NullPointerException
> ```
> This are WARN logs but the node doesn't connect to the cluster when doing a rolling restart of the servers.

Was there a reason you replied to this PR specifically? This PR was submitted to suppress specific warning logs Jetty was producing.

**Comment by rahulbhanushali** [comment]
Yes, the reason being I still this logs on 1.80. and the node doesn't connect to the cluster.
There's no  other log apart from this in the file so I am assuming this may be the reason the node doesn't connect to the cluster.

**Pull request closed without merging**
