### PR TITLE
NIFI-3681 - Controller Service for Processor Leader Elections

### PR DESCRIPTION
**Pull request by josephxsxn**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [X ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

-- Looking for feedback on this implementation before squashing into a single commit for merge. Any feedback is welcome. I have done some testing with the current build on a 3 node cluster and it works very well in terms of keeping leader etc.    @Xsixteen @GrayGwizdz can you guys take a read over this before the real commiters comment?

### CODE REVIEW

**Comment by GrayGwizdz** [comment]
You might want to consider importing KeeperException so catch (KeeperException.NodeExistsException e) doesn't need the class in multiple places
You also might want to consider refactoring to extract the inner classes to be their own classes!

**Comment by joewitt** [comment]
couple of quick thoughts.
- we'll need to get all the version numbers aligned with whatever nifi version this would be committed into.  Currently that would be 1.3.0-SNAPSHOT.
- It would probably be a good idea to have the notion of 'nifi-leaderelection-api' which is not about zookeeper but rather just generic election/tracking of a leader for a given thing (a partition?) Then there would be zookeeper based implementations of those.  Processors then can leverage the api for their code but users can select whichever types of services exist (zookeeper being the obvious initial example).  The structure appears already in place for this other than the current naming and perhaps the API referencing zookeeper.  Thoughts?
- It would be good to have a processor which leverages this or some docs that go along with it to show suggested usage.

**Comment by josephxsxn** [comment]
1) I'll look into taking the inner classes out but will need to look at how the permissions scopes are working between them first.
2) Will look into applying the KeeperException recommendation to clean the code up some.
3) Will fix versions
4)  I agree, I got tired of fighting maven's arch type generator. Will repackage things to facilitate a generic election API like the jira kinda talks about.
5) Plan is to make the GetEventHubProcessor use this as it has some major issues in clustered deployments with duplication of data. Unlike Kafka which uses a consumer group to only allow 1 reader per partition. In EventHub your allowed 5 readers per partition, so we need a method to discover alive workers, elect the leader, have the leader assign partition work into the shared cache, and then run.

**Comment by joewitt** [comment]
Closing due to inactivity.

**Pull request closed without merging**
