### PR TITLE
NIFI-5474: When using Regex Replace with ReplaceText, and there are capturing groups, ensure that we populate the 'additionalVariables' map for each match of the regex. This allows Expression Language to reference the back-references properly even when there are multiple matches

### PR DESCRIPTION
**Pull request by markap14**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by ottobackwards** [comment]
Ran with contrib-check, and stepped through.

@markap14 this is certainly a better fix for the issues than my other PR's.  I learned something I didn't know about the el evaluation and the additional attributes.  I certainly tackled this from the wrong angle.

I enthusiastically support this code's replacement of my initial PR and closing out my current one when this lands. +1

@mosermw, since you reviewed my other pr, can you take a look at this?

**Comment by mosermw** [comment]
Well since I was the judge on the original NIFI-4272 case and didn't catch the side effects, perhaps I shouldn't be the one to hear the appeal.

**Comment by markap14** [comment]
@mosermw ha! It's *really* easy to miss these things when reviewing! @ottobackwards for what it's worth, I learned some new things about the Pattern/Matcher API as well, when looking into this. I wasn't aware that there was essentially an iterative alternative to "replaceAll". Pretty neat.

**Comment by mattyb149** [comment]
I'll take a look here too, and will merge after my +1 unless there are objections

**Comment by mattyb149** [comment]
+1 LGTM, ran unit tests and contrib-check, tried on a live NiFi instance. Thanks for the fix! Merging to master

**Pull request closed without merging**
