### PR TITLE
NIFI-8155 - add banner text in page title

### PR DESCRIPTION
**Pull request by pvillard31**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Enables X functionality; fixes bug NIFI-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [x] Have you verified that the full build is successful on JDK 8?
- [x] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by pvillard31** [comment]
Screenshot 2021-01-20 at 16 13 11

**Comment by exceptionfactory** [comment]
This change looks straightforward as it stands, but there are several other places where the `document.title` is set when opening new windows, such as Provenance contents or Bulletin Board messages.  Should those other references also be updated?

**Comment by pvillard31** [comment]
Thanks for looking into this @exceptionfactory. As far as I can tell the other places you mentioned are not "really" opening new windows and this not impacting the overall page title:

Screenshot 2021-01-21 at 11 53 43

The only edge case I can think of is when looking at the content of a flow file: this will open a new tab/window and the title won't contain the info. But I believe this a very special edge case and I think this is best to leave it outside of the change.

Screenshot 2021-01-21 at 11 53 43

**Comment by mattyb149** [comment]
+1 LGTM, even tried script injection to the `nifi.ui.banner.text` property and it still worked as expected. I agree with pvillard31's answers to exceptionfactory's good question, so thanks for the improvement! Merging to main. If we need to handle more use cases please feel free to re-open the Jira and document the desired changes.

**Pull request closed without merging**
