### PR TITLE
NIFI-6682 SplitJson does not work if the input is null

### PR DESCRIPTION
**Pull request by ottobackwards**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

fixes bug NIFI-6682

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [x] Have you written or updated unit tests to verify your changes?
- [x] Have you verified that the full build is successful on both JDK 8 and JDK 11?
https://travis-ci.org/ottobackwards/nifi/builds/590176405
- [-] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [-] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [-] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [-] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [-] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

---
This change is [Reviewable](https://reviewable.io/reviews/apache/nifi/3772)

### CODE REVIEW

**Comment by ottobackwards** [comment]
close and reopen to rebuild, I don't know why the java 8 builds failed travis.

**Comment by ottobackwards** [comment]
https://issues.apache.org/jira/browse/NIFI-6694  Is the reason for the build failure, I *think*

**Comment by joewitt** [comment]
@ottobackwards  rather than waiting for the illegal argument to occur lets please do a null check and break out properly.  Avoiding exceptions for flow control where reasonably possible, as is the case here, is far better for performance.

**Comment by ottobackwards** [comment]
Just to be clear, the stream is not `null`, the _value_ of the string in the stream is literally "null".
I don't think reading the stream there, checking for null and resetting the stream or creating a new stream is great either.

**Comment by joewitt** [comment]
Ok.  Your comment of the exception catching says "It is possible for the json parsing to complete without error, but produce a null object. In this case the context creation will fail and throw an IllegalArgumentException"

I am suggesting that the resulting null ctx object should be checked to be null and then not attempted to be set knowing that this would result in an exception.  If that is the case just check that the ctx object is null and handle rather than waiting for the exception.

Did I misread your note?

**Comment by ottobackwards** [comment]
No, you read it correctly, but that operation is _inside jsonpath_, not nifi.
in ParseContextImpl.java
```java
 @Override
    public DocumentContext parse(InputStream json, String charset) {
        notNull(json, "json input stream can not be null");
        notNull(json, "charset can not be null");
        try {
            Object obj = configuration.jsonProvider().parse(json, charset);
            return new JsonContext(obj, configuration);
        } finally {
            Utils.closeQuietly(json);
        }
    }
```
the Object obj for "null" is a null, and boom.  I think I'm going to do a PR to that project on this as well.

**Comment by ottobackwards** [comment]
@joewitt any feedback?  any chance of this for release or it is out of scope?

**Comment by aloneface** [comment]
I think all the exceptions should be caught and transfer to failure in SplitJson ,right? @joewitt @ottobackwards

**Comment by ottobackwards** [comment]
That is what happens as a result of this PR, see the modified test.

**Comment by aloneface** [comment]
https://github.com/apache/nifi/pull/3816 Another way to solve it by catching all the throwables.I think it might be better .

**Pull request closed without merging**
