### PR TITLE
NIFI-7863 - Recursively create directories, in case of a missing parent directory

### PR DESCRIPTION
**Pull request by jayaaditya**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

Fixes issue described in NIFI-7863
https://issues.apache.org/jira/browse/NIFI-7863
Since samba does not allow recursive creation of directories, I modified the PutSmbFile processor to recursively create directories if it is missing,

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [x] Have you written or updated unit tests to verify your changes?
- [x] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by si-sun** [comment]
hello @jayaaditya, could you check on a running nifi instance the behavior when substituting multiple variable, like directory set to "parent\${'dir1'}\${'dir2'}"? It looks to me like there is a bug with evaluateAttributeExpressions so that only the first variable is replaced when there are backslashes present.

**Comment by jayaaditya** [comment]
Hello @si-sun! I just tried executing the processor with the parent dirs as nifi expression attributes. There seems to no particular issue in directory creation. This was the properties I set in my PutSmbFile processor. 

And these were the debug logs after execution.
```
13:08:26 JSTDEBUG0289ea7d-0175-1000-714f-a2965bf8530d
PutSmbFile[id=0289ea7d-0175-1000-714f-a2965bf8530d] Processing next 1 flowfiles
13:08:26 JSTDEBUG0289ea7d-0175-1000-714f-a2965bf8530d
PutSmbFile[id=0289ea7d-0175-1000-714f-a2965bf8530d] 2
13:08:26 JSTDEBUG0289ea7d-0175-1000-714f-a2965bf8530d
PutSmbFile[id=0289ea7d-0175-1000-714f-a2965bf8530d] 1
13:08:26 JSTDEBUG0289ea7d-0175-1000-714f-a2965bf8530d
PutSmbFile[id=0289ea7d-0175-1000-714f-a2965bf8530d] Creating folder 2020-10-09
13:08:26 JSTDEBUG0289ea7d-0175-1000-714f-a2965bf8530d
PutSmbFile[id=0289ea7d-0175-1000-714f-a2965bf8530d] Creating folder 2020-10-09\13
```
I verified whether the directories are getting created in my sambashare folder as well.
Thanks for pointing out this test case!

**Comment by jayaaditya** [comment]
Could anyone please review my PR ? Thanks in advance!

**Comment by kullervo16** [comment]
@si-sun : could this PR be re-activated as this would be a very interesting fix...

**Comment by JensMKofoed** [comment]
I would like this to be fixed too. I have implemented it my self and added one more thing
All forward slashes in the folder part should be replaced with backward slashes, if not it will not work.

**Comment by malthe** [comment]
This was actually fixed elsewhere, in #5495.

**Pull request closed without merging**
