### PR TITLE
NIFI-2403 Ensuring uniqueness on user identities and group names

### PR DESCRIPTION
**Pull request by bbende**

### CODE REVIEW

**Comment by mcgilman** [comment]
Reviewing....

**Comment by mcgilman** [comment]
@bbende This is a great start. I've verified that we can no longer add new users or groups with the same name as existing users or groups. However, I think we need to additionally ensure uniqueness between user identities and group names. Also, the unique constraint appears to only be checked when creating the user or group. Updating still allows the identities to become the same.

**Comment by bbende** [comment]
@mcgilman thanks for reviewing, great points... i just pushed a new commit that addresses the uniqueness across users and groups, and on updates

**Comment by mcgilman** [comment]
Thanks @bbende! While testing I found a condition where the UI wasn't displaying the error returned from the server. I included that minor addition into your commit. This has been merged to master. Thanks!

**Pull request closed without merging**
