### PR TITLE
NIFI-9570 Separate classpath for NiFi Registry sensitive property pro…

### PR DESCRIPTION
**Pull request by bbende**
…viders

This PR creates `lib/spp` under NiFi Registry's lib directory to isolate all of the sensitive property provider dependencies, and also separates `NiFiRegistryPropertiesLoader` into it's own module. It then uses a similar approach from `NiFi` to load `NiFiRegistryPropertiesLoader` via reflection in `NiFiRegistry` using a special ClassLoader that has `lib/spp` resources.

### CODE REVIEW

**Comment by exceptionfactory** [comment]
Thanks for the improvement @bbende! The pull request appears to include a number of test properties files, are all of those necessary as part of this change?

**Comment by bbende** [comment]
@exceptionfactory thanks for taking a look... as part of splitting apart the properties and properties loader, there was also a test class for properties loader that used several of these files. At the time I was mostly trying to get the tests passing and just duplicated the resources, so we can probably narrow it down a little bit, a bunch of them are used though.

**Comment by exceptionfactory** [comment]
Thanks @bbende, if there is an opportunity to cut down the number of test cases and corresponding properties files, that would be helpful.

**Comment by bbende** [comment]
@exceptionfactory pushed a new commit that cleans up the test resources... from the original resources, the bootstrap ones were needed only by nifi-registry-properties and the nifi-registry.properties ones were needed only by nifi-registry-properties-loader.

**Review by exceptionfactory — APPROVED** [review]
Thanks for the updates @bbende! Verified runtime handling of AES-GCM encrypted properties. This definitely cleans up the NiFi Registry class path, looks great! +1 Merging.

**Pull request closed without merging**
