### PR TITLE
NIFI-4923 Updated nifi-hadoop-libraries-nar, nifi-hdfs-processors, an…

### PR DESCRIPTION
**Pull request by jtstorck**
…d nifi-hadoop-utils dependency on hadoop-client from 2.7.3 to 3.0.0

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by MikeThomsen** [comment]
@jtstorck have you tried these changes against a Hadoop 2.X cluster?

**Comment by bbende** [comment]
Will review this soon...

@MikeThomsen I think the intent here is to move master to use Hadoop 3.0.0 dependencies (3.1.0 is even out now)... If anyone needs to continue using the Hadoop 2.x dependencies then they can take the NARs from the previous release and add them in. For example, if 1.7.0 moves to 3.0.0, someone can take the nifi-hadoop-nar and nifi-hadoop-libraries-nar from 1.6.0 and drop them into 1.7.0.

**Comment by jtstorck** [comment]
@MikeThomsen I did run against HDP 2.6.  Using client configs downloaded from a secure HDP 2.6 cluster, I was able to test Put/List/Fetch/DeleteHDFS, including TDE directories.

**Comment by tasanuma** [comment]
Thanks for working on this task. 

Basically, Wire Protocols between Hadoop clients and servers can be broken if they aren't within a major version. I think we should carefully proceed.

FYI:
http://hadoop.apache.org/docs/r3.1.0/hadoop-project-dist/hadoop-common/Compatibility.html#Wire_Protocols
https://cwiki.apache.org/confluence/display/HADOOP/Hadoop+3.0.0+Release

**Comment by bbende** [comment]
@jtstorck I tested this against a 2.6 Hadoop with Kerberos and also a 3.0.0 and it appears to work against both so I'm planning to merge this.

I do think we should make it as easy as possible for users to get the older NARs if for some reason they really do need to use the 2.x Hadoop client.

The easiest way to do this would be to just grab from Nexus and drop them into the lib directory:

http://central.maven.org/maven2/org/apache/nifi/nifi-hadoop-libraries-nar/1.6.0/nifi-hadoop-libraries-nar-1.6.0.nar
http://central.maven.org/maven2/org/apache/nifi/nifi-hadoop-nar/1.6.0/nifi-hadoop-nar-1.6.0.nar

I'm thinking we can either put links to these on our main Downloads page, or we can link to them in the Migration Guidance Wiki page.

**Pull request closed without merging**
