### PR TITLE
NIFI-6293 Fix for MongoDB Aggregation does not parse dates

### PR DESCRIPTION
**Pull request by esarkissian-rythmos**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by MikeThomsen** [comment]
I'll try to review this today.

**Comment by MikeThomsen** [comment]
Looks like your IDE might have introduced a bunch of style errors:

```
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[67,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[68,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[69,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[70,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[72,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[73] (regexp) RegexpSinglelineJava: Line has trailing whitespace.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[73,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[74] (regexp) RegexpSinglelineJava: Line has trailing whitespace.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[74,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[75] (regexp) RegexpSinglelineJava: Line has trailing whitespace.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[75,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[76,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[77,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[78,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[79] (regexp) RegexpSinglelineJava: Line has trailing whitespace.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[79,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[80,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[81,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[82,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[84,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[85,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[86] (regexp) RegexpSinglelineJava: Line has trailing whitespace.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[86,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[87,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[88,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[89,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[90,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[91,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[92,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[93,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[94,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[95] (regexp) RegexpSinglelineJava: Line has trailing whitespace.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[95,1] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[112] (regexp) RegexpSinglelineJava: Line has trailing whitespace.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[112,91] (whitespace) FileTabCharacter: Line contains a tab character.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[116] (regexp) RegexpSinglelineJava: Line has trailing whitespace.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[120] (regexp) RegexpSinglelineJava: Line has trailing whitespace.
[WARNING] src/main/java/org/apache/nifi/processors/mongodb/RunMongoAggregation.java:[192] (regexp) RegexpSinglelineJava: Line has trailing whitespace.
```

**Comment by MikeThomsen** [comment]
Also, could you give me a sample aggregation that isn't working? I'm mostly familiar with the mongo date functions for this sort of thing.

**Comment by esarkissian-rythmos** [comment]
Any "$match" statement that requires date checking, for example:

```json
[ { "$match": { "someDateField": { "$gt": "2019-01-01T00:00:00.000Z" } } } ]
```

The problem is that internally this is sent as a string to Mongo, instead of a date object. So the comparison does not work.

I am later finding out that this PR may not be the most straightforward way to do this. I think the other MongoDB processors allow the use of Extended JSON to do this, e.g. GetMongo:

```
{ "someDateField": { "$gt": { "$date": "2019-01-01T00:00:00.000Z" } } }
```

I think if we use the BasicDBObject.parse() static method we can achieve the same functionality. This is much better than what I have done in this PR. In fact we should probably kill this PR.

**Comment by MikeThomsen** [comment]
Ok, go ahead and close it out.

**Pull request closed without merging**
