### PR TITLE
NIFI-2751 NIFI-2848 Get batch of flow files in a round-robin manner

### PR DESCRIPTION
**Pull request by pvillard31**

### CODE REVIEW

**Comment by trixpan** [comment]
@gresock can you confirm thij has this fixed NIFI-2848 (as per your template)?

**Comment by trixpan** [comment]
@gresockj  can you confirm thij has this fixed NIFI-2848 (as per your template)?

**Comment by gresockj** [comment]
Yes, I will take a look today

**Comment by mattyb149** [comment]
+1 LGTM, tried with and without the fix, verified that the flow files are drained in a fair manner. Merging to master

**Pull request closed without merging**
