### PR TITLE
NIFI-10728 Update Derby to 10.16.1.1

### PR DESCRIPTION
**Pull request by mr1716**
# Summary

[NIFI-10728](https://issues.apache.org/jira/browse/NIFI-10728)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI-10728) issue created

### Pull Request Tracking

- [X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X] Pull Request based on current revision of the `main` branch
- [X] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — COMMENTED** [review]
@mr1716 Please combine these changes into a single commit, instead of one commit per file. Thanks!

**Comment by pvillard31** [comment]
Also, don't we want to have a property for this version in the root pom.xml (given the versions also defined in #7491)?

**Comment by mr1716** [comment]
> Also, don't we want to have a property for this version in the root pom.xml (given the versions also defined in #7491)?

@pvillard31 they're 2 separate things

**Comment by exceptionfactory** [comment]
@mr1716 On further review, the changes required for Derby 10.16.1.1 include depending on the `derbytools` library in several places, so the change involves more than just incrementing the version. I have opened a new pull request incorporating the necessary changes in #7497. Thanks for helping move this forward.

**Pull request closed without merging**
