### PR TITLE
NIFI-5562 - Upgraded guava versions from v18.0 to v26.0-jre. Verified all…

### PR DESCRIPTION
**Pull request by thenatog**
… tests work as expected except for 1.

NIFI-5562 - Upgraded to Guava 26.0-jre which fixes a cache eviction bug for Cache.asMap.compute* method. This caused a failing test in NiFi's TestRouteText.java.

NIFI-5562 - Cleaning up some stuff.

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by MikeThomsen** [comment]
Saw @bbende's jira comment:

> We should only update Guava dependencies that we directly use in our own code, but not transitive dependencies used by client libraries (i.e. do not change the Guava version for things like Hadoop processors, or HBase processors, etc.).

I saw Kudu, Kite and Ignite get updated, but according to `mvn dependency:tree` they're not transitive. So I'm putting this here for documentation purposes. Overall LGTM but will take another look tomorrow.

**Comment by alopresto** [comment]
Reviewing...

**Comment by thenatog** [comment]
Updating this PR, don't merge.

**Comment by mcgilman** [comment]
Happy to help review this PR once it's ready.

**Comment by thenatog** [comment]
Discovered issues within the core nifi framework related to guava, zookeeper and curator. Unable to bump guava without upgrading the others. This is a bigger task that just upgrading guava.

**Pull request closed without merging**
