### PR TITLE
NIFI-10639 Fix testAddedRowsTwoTables

### PR DESCRIPTION
**Pull request by ZhewenFu**
# Summary

[NIFI-10639](https://issues.apache.org/jira/browse/NIFI-10639)
Fix test `org.apache.nifi.processors.standard.QueryDatabaseTableRecordTest.testAddedRowsTwoTables` and `org.apache.nifi.processors.standard.QueryDatabaseTableTest.testAddedRowsTwoTables`. Those two tests are flaky since they didn't do the sanity check where no flowfiles/rows should be transferred and would occasionally fail. To fix the test, I added the sanity check before asserting the `maxvalue.id`. I also changed the parameter `QueryDatabaseTable.MAX_ROWS_PER_FLOW_FILE` to 3 to make the tests clearer and more consistent.

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [x] Build completed using `mvn clean install -P contrib-check`
  - [x] JDK 8
  - [ ] JDK 11
  - [ ] JDK 17

### Licensing

- [x] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [x] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [x] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by thenatog** [comment]
Will review

**Comment by thenatog** [comment]
I'm not sure how this addresses the flakiness of the test. Is this test failing frequently in Github Actions? I don't quite understand how running the runner a second time and verifying no FlowFiles were transferred fixes the test.

**Comment by ZhewenFu** [comment]
> I'm not sure how this addresses the flakiness of the test. Is this test failing frequently in Github Actions? I don't quite understand how running the runner a second time and verifying no FlowFiles were transferred fixes the test.

* Sorry for the late response. I detected that the test results are flaky using the NonDex tool for catching non-deterministic/flaky tests (https://github.com/TestingResearchIllinois/NonDex).

  You may reproduce the nondeterministic behavior using the following steps:
  Clone the repo and cd into it.
`mvn install -pl modules/configuration-governance -am -DskipTests`
`mvn -pl modules/configuration-governance test -Dtest=com.ibm.cloud.platform_services.configuration_governance.v1.model.RuleRequestTest#testRuleRequest`
`mvn -pl modules/configuration-governance edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=com.ibm.cloud.platform_services.configuration_governance.v1.model.RuleRequestTest#testRuleRequest`

* I think I made a mistake in my previous descriptions. I think the real solve of flaky tests lies on the line `runner.setProperty(QueryDatabaseTableRecord.MAX_ROWS_PER_FLOW_FILE, "0");` due to some inconsistent or asychronized reading/writing. But I am not sure about this for now and still diving into the code to see what's the exact cause of this problem. I will let you know when I find more about it.

**Comment by exceptionfactory** [comment]
Thanks for the contribution @ZhewenFu. Based on the latest comments, it sounds like further work is necessary to understanding the underlying cause of non-deterministic behavior. With that background, I am closing the current pull request, but feel free to follow up with a new pull request when you have narrowed down the source of the behavior.

**Pull request closed without merging**
