### PR TITLE
NIFI-5552 - Add option to normalize header column names in CSVRecordR…

### PR DESCRIPTION
**Pull request by pvillard31**
…eader

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [x] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by markap14** [comment]
Hey @pvillard31 thanks for putting up a PR! I looked through it, and I do believe that it would resolve the issue that is being described in NIFI-5552. However, I'm not entirely sure that this is the best approach. This approach is adding property to the CSV Reader that are very much tailored toward Avro. I think the better approach would be to instead update the WriteAvroSchemaAttributeStrategy and AvroTypeUtil classes to normalize the names as necessary, so that Avro-related concerns are confined to the Avro-specific strategy.

**Comment by pvillard31** [comment]
Hey @markap14 - thanks for the review. You're right, it's much better to address it when creating the Avro schema. That would prevent this error to happen again if one day we add a Reader for a format that would accept non Avro compatible field names.

Just a quick remark. Initially in ``AvroTypeUtil`` I just wanted to change L123 from:
````java
final Field field = new Field(recordField.getFieldName(), schema, null, recordField.getDefaultValue());
````
to
````java
final Field field = new Field(normalizeNameForAvro(recordField.getFieldName()), schema, null, recordField.getDefaultValue());
````

But not sure changing the name just here is really a good idea and if it's not going to break some things in other places. In the end, I changed all the occurrences of ``recordField.getFieldName()`` to normalize the name. Thoughts?

**Comment by markap14** [comment]
@pvillard31 we don't want to change `recordField.getFieldName()` - that is the NiFi class and has nothing to do with Avro. We really want to avoid enforcing any Avro naming peculiarities on NiFi - we should only enforce them for Avro, so I think the `AvroTypeUtil` is the right place to put this. You should not need to worry about breaking backward compatibility, because the `normalizeNameForAvro` method should make no changes to the name unless the name is invalid - in which case it would have thrown an Exception previously.

**Comment by pvillard31** [comment]
> we don't want to change recordField.getFieldName() - that is the NiFi class and has nothing to do with Avro. We really want to avoid enforcing any Avro naming peculiarities on NiFi - we should only enforce them for Avro, so I think the AvroTypeUtil is the right place to put this.

Yeah totally agree here.

I didn't change ``recordField.getFieldName()``, I just wrapped it, in ``AvroTypeUtil``, to ensure the name is normalized. My concern was more about methods like ``lookupField`` where we assign the field name to the record field object. Just want to ensure that this pair/map is not used outside of the ``AvroTypeUtil`` where we would try to access the record field object with a non-normalized field name. Does that make sense?

**Comment by joewitt** [comment]
closing due to inactivity

**Pull request closed without merging**
