### PR TITLE
NIFI-9184 Refactor shared methods in Sensitive Property Providers

### PR DESCRIPTION
**Pull request by exceptionfactory**
#### Description of PR

NIFI-9184 Refactors shared methods for Base64 encoding and client status handling in the following Sensitive Property Providers:

- AWS KMS
- Azure Key Vault Key
- GCP KMS

Changes include abstracting client initialization to a `ClientProvider` interface with a shared method for reading client properties from a referenced configuration file. Abstracting client initialization provided the opportunity to introduced unit tests for AWS KMS and Azure Key Vault Key providers. the GCP `KeyManagementServiceClient` does not implement an interface and has methods marked as `final`, which does not lend itself to mocked unit testing.

The client initialization approach in `BoostrapPropertiesClientProvider` checks for the presence of the specified path property as well as the existence of the referenced properties file. As multiple Sensitive Property Provider implementations are not designed to be used together, commenting out the referenced configuration file properties in the default `bootstrap.conf` provides a better approach to the default system configuration.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [X] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [X] Have you written or updated unit tests to verify your changes?
- [X] Have you verified that the full build is successful on JDK 8?
- [X] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by emiliosetiadarma** [comment]
Hey David!

Thanks for continuing to build on what I worked on the past summer! Just have a few input. I was able to run the build and verify that it was working. I was wondering, documentation-wise, if we could probably put a note about uncommenting the `bootstrap-*.conf` file path in the `bootstrap.conf` for each specific cloud provider somewhere in `toolkit-guide.adoc` or `administration-guide.adoc`? 

Also I was wondering if it would be better if `EncodedSensitivePropertiesProvider` extends `AbstractSensitivePropertyProvider`, that way the shared methods `getName()` and `getIdentifierKey()` would not have to be rewritten and the `getProtectionScheme()` could be implemented there.

Other minor suggestions include changing naming of `EncodedSensitivePropertiesProvider` to`EncodedSensitivePropertyProvider`. And also similarly for the `ClientBasedEncodedSensitivePropertiesProvider`. That way the naming will be consistent.

**Comment by exceptionfactory** [comment]
Thanks for the feedback @emiliosetiadarma!

Good catch on the class names, I made the adjustments you suggested and also added a note to the Administrator's Guide regarding commented file reference properties.

I considered having `EncodedSensitivePropertyProvider` extend `AbstractSensitivePropertyProvider`, but since other classes handle instantiation differently and override the `getIdentifier` method in some cases, it did not seem like the best approach.

Please let me know if you have any additional comments.

**Comment by emiliosetiadarma** [comment]
Hey @exceptionfactory, that makes sense, especially if more non-client based SPPs are developed in the future as well.

**Review by gresockj — COMMENTED** [review]
Thanks for this contribution, @exceptionfactory!  I agree with the purpose and implementation, and will be testing the runtime behavior.

**Review by gresockj — COMMENTED** [review]
FWIW, I just tested the AWS KMS SPP successfully.

**Comment by exceptionfactory** [comment]
Thanks for the feedback and verification @gresockj!

**Review by gresockj — APPROVED** [review]

**Pull request closed without merging**
