### PR TITLE
NIFI-1423 Allow to penalize FlowFiles to No Retry

### PR DESCRIPTION
**Pull request by ledor473**

### CODE REVIEW

**Comment by olegz** [comment]
+1

**Comment by JPercivall** [comment]
I believe flowfiles should be removed from the penalized list when MockProcessSession.remove() is called: https://github.com/apache/nifi/blob/fd35b8ffd7d4a66ef149c1bd1341dfee3ede80c7/nifi-mock/src/main/java/org/apache/nifi/util/MockProcessSession.java#L430

**Comment by JPercivall** [comment]
When MockProcessSession.rollback(boolean)[1] is called it is, the boolean is telling the session whether or not the flowfiles should be penalized. In the event the boolean is true if the session shouldn't it clear the penalized list then add all the flowfiles to the list?

[1] https://github.com/apache/nifi/blob/fd35b8ffd7d4a66ef149c1bd1341dfee3ede80c7/nifi-mock/src/main/java/org/apache/nifi/util/MockProcessSession.java#L522-L522

**Comment by JPercivall** [comment]
I know this isn't part of the ticket but, there are numerous lines in the unit tests that say " // getMyFlowFiles();". I believe they're relicts from before the refactor. Could you remove them in this commit?

**Comment by JPercivall** [comment]
Did a maven contrib check build and verified the functionality using a test http server. Once the comments are addressed I can merge in.

**Comment by apiri** [comment]
Agree with @JPercivall regarding the rollback to be able to get a full handle on rolled back files for a given session/execution to understand how the processor behaved.  Scanning through the codebase, these are a minority of usages and typically would only get invoked when there is a dev issue causing exceptions, but could see it getting more usage within AbstractionSessionFactory based processors where that functionality could be preferred.  Seems like a quick effort for consistency.

**Comment by ledor473** [comment]
All very valid points there, I'll have a look at them.
The merge request will be updated with the fixes soon and will also be up-to-date with the current master

**Comment by ledor473** [comment]
I've pushed the new version that includes all the fixes for the comments above. 
Contrib check done and up-to-date to master.

**Pull request closed without merging**
