### PR TITLE
added voltatile provenance repository docstring

### PR DESCRIPTION
**Pull request by randerzander**

### CODE REVIEW

**Comment by apiri** [comment]
Created NIFI-1807 to track this effort.

**Comment by apiri** [comment]
Hey @randerzander!

Looks good.  There are some additional properties that are also configurable which are also not documented concerning the volatile content repository.  I created a commit that would include those 00ec1892fc9002f992e41d9015dcee697b428428 and would like to accompany the improvements in this contribution.  Let me know your thoughts and thanks for improving our docs.

**Comment by randerzander** [comment]
The additional info is nice. Are there additional voltatile provenance repository properties that should be added as well?

**Comment by apiri** [comment]
There are not.  Volatile provenance only uses nifi.provenance.repository.buffer.size which is reusing that of the persistent repo.

**Pull request closed without merging**
