### PR TITLE
NIFI-4139 Extract key provider to framework-level service

### PR DESCRIPTION
**Pull request by alopresto**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by mcgilman** [comment]
@alopresto These refactorings look good. The backward compatibility support for legacy configurations is also solid. One minor thing I'd like to investigate further if we can remove the dependency between the nifi-security-utils and the nifi-properties-loader. The nifi-security-utils are referenced and pulled into many NARs and the additional dependency would introduce further duplication of the nifi-properties-loader jar (and it's transitive dependencies not already included). This dependency is only used to load the master key from the bootstrap.conf. While it's not a showstopper, it would be nice if we didn't need this additional dependency and instead allowed the client of the nifi-security-utils provide the master key when necessary.

Thanks

**Comment by alopresto** [comment]
Thanks @mcgilman. I have moved the master key extraction out to `EncryptedWriteAheadProvenanceRepository` and removed the `nifi-security-utils` dependency on `nifi-properties-loader`. That module is now included in 16 production modules and 4 test modules (I believe this is down from 39 previously). Let me know if you feel this is sufficient.

**Comment by alopresto** [comment]
I also considered passing a supplier rather than the master key to the `KeyProviderFactory`, but the `EncryptedWriteAheadProvenanceRepository` already has access to the master key retrieval code, so I didn't yet. 

I also considered making a DTO for the `KeyProvider` configuration values used in the factory, as the parameter list is getting a little long, but the only place they are currently used is in the EWAPR. When I implement NIFI-3888 subtasks for content and flowfile repository, I may refactor this to be more concise.

**Comment by mcgilman** [comment]
Thanks @alopresto! This has been merged to master. I accidentally forgot to add the 'This closes...' text to the commit message. Would you mind closing this PR out? Thanks!

**Comment by alopresto** [comment]
Closing per @mcgilman.

**Pull request closed without merging**
