### PR TITLE
[NIFI-1459] add css translate3d to properties table editors in order …

### PR DESCRIPTION
**Pull request by scottyaslan**
…to move the element along the z-axis of the 3D space and allow the scrollbars to properly be poistioned

### CODE REVIEW

**Comment by mcgilman** [comment]
Reviewing...

**Comment by mcgilman** [comment]
@scottyaslan This addresses the issue in the property table used throughout the canvas, however the same problem exists in the UpdateAttribute Custom UI. Would you be able to update that too?

**Comment by scottyaslan** [comment]
@mcgilman I have updated the tables in the UA Custom UI to account for overlaid scrollbars. This PR should be ready to merge.

**Comment by mcgilman** [comment]
Thanks @scottyaslan. This has been merged to master.

**Pull request closed without merging**
