### PR TITLE
NIFI-2145: Auto flow.xml archive

### PR DESCRIPTION
**Pull request by ijokarumawak**
Hello,

I've added auto flow.xml archive support. Since the existing 'Back-up flow' link overlaps and can be replaced with this, removed the link and corresponding API as well.
Please review it, look forward to see any feedback, thanks!

- Added following properties:
  - nifi.flow.configuration.archive.enabled
  - nifi.flow.configuration.archive.max.time
  - nifi.flow.configuration.archive.max.storage
- Removed manual archive operation:
  - Removed 'Back-up flow' link from UI since it's not needed any longer
  - Removed corresponding REST API controller/archive and its
    implementations
- Added FlowConfigurationArchiveManager to enclose archive related code
- Updated related docs

### CODE REVIEW

**Comment by JPercivall** [comment]
Hey @ijokarumawak, looks like this now has merge conflicts. Could you address them?

**Comment by ijokarumawak** [comment]
@JPercivall Fixed merge conflicts. Please check this out, thanks!

**Comment by markap14** [comment]
Oh no! As always, I forgot to add the magical words to close the PR. Can you close this PR manually?

**Comment by ijokarumawak** [comment]
@markap14 @JPercivall Glad to hear! Thank you for reviewing and merging!

**Pull request closed without merging**
