### PR TITLE
NIFI-11794 - Fix NPE + configure max attempts for Redis State Provider

### PR DESCRIPTION
**Pull request by pvillard31**
# Summary

[NIFI-11794](https://issues.apache.org/jira/browse/NIFI-11794) - Fix NPE + configure max attempts for Redis State Provider

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by ottobackwards** [comment]
This looks good, is there a way to test this specifically that we should cover?

**Comment by pvillard31** [comment]
I tried adding a unit test showing the issue but didn't find a way to reproduce it. You have to simulate two nodes at the same time trying to access the same key.

**Comment by ottobackwards** [comment]
would a failure to connect over max attempts ( to get the `null` and new check) work?  without the nodes at all? or would that fail a different way?

**Comment by ottobackwards** [comment]
then again, a null check is a pretty obvious fix there, maybe we don't need to....

**Comment by pvillard31** [comment]
That would not cause the null error. EXEC returns null in case the transaction has been aborted. So you'd need to simulate one node/thread to have a transaction starting with a WATCH on the key, then another node/thread completing a transaction on the same key, to have the first one receiving a null. The logs I shared in the JIRA comment are coming from a cluster that I patched with this fix.

**Comment by pvillard31** [comment]
Thanks @ottobackwards

**Pull request merged**
