### PR TITLE
NIFI-8785 - Confluent Schema Registry REST client - refactoring, debu…

### PR DESCRIPTION
**Pull request by pvillard31**
…g logs and a new method to get schema info without making subjects API calls

Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Enables X functionality; fixes bug NIFI-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [x] Have you verified that the full build is successful on JDK 8?
- [x] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for the updates @pvillard31! I noted some minor recommendations to use parameterized log messages.

Reviewing the implementation itself and reading the comments, are there any options for querying the Schema Registry API to determine the supported REST resources? If it is possible to determine the Schema Registry API version or supported REST resources during initialization, that might simplify the schema retrieval logic.

**Comment by pvillard31** [comment]
Hey @exceptionfactory - thanks for the review and suggestions.

Regarding the version of the schema registry and what APIs can be used or not, I didn't find anything that could be used to simplify the retrieval logic and, in the end, ensure to have the smallest number of calls against the schema registry. However, since the schemas are cached, we're not making too many calls. The initial implementation that was listing all subjects and checking the schema for each of the subject was super expensive (when the schema registry contains a lot of schemas). The recently added option (#4872) and this new option should make things much better in terms of performance.

https://docs.confluent.io/platform/current/schema-registry/develop/api.html

**Comment by exceptionfactory** [comment]
Thanks for the updates and reply @pvillard31, that's a helpful point regarding caching. I will look at verifying the changes soon.

**Review by exceptionfactory — APPROVED** [review]
Verified using Confluent Schema Registry 6.2.1. Thanks @pvillard31! +1 Merging.

**Pull request closed without merging**
