### PR TITLE
NIFI-11643: Upgrade geoip2 to 4.0.1

### PR DESCRIPTION
**Pull request by r-sidd**
# Summary

[NIFI-11643](https://issues.apache.org/jira/browse/NIFI-11643)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 11
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by r-sidd** [comment]
@exceptionfactory can you review this pls? Build success in local 🙂

**Review by exceptionfactory — COMMENTED** [review]
Version 4.0.1 includes changes from [3.0.0](https://github.com/maxmind/GeoIP2-java/releases/tag/v3.0.0) that require Java 11 as the minimum version, so this should be suitable for inclusion on the main branch, but cannot be backported to the version 1 support branch.

**Comment by r-sidd** [comment]
> Version 4.0.1 includes changes from [3.0.0](https://github.com/maxmind/GeoIP2-java/releases/tag/v3.0.0) that require Java 11 as the minimum version, so this should be suitable for inclusion on the main branch, but cannot be backported to the version 1 support branch.

Cool, how should we go about it 🙂

**Review by exceptionfactory — APPROVED** [review]
Thanks @r-sidd, this upgrade looks good for the main branch. This cannot be backported to the support branch due to Java 11 requirements, but this is helpful for the next major release version. +1 merging

**Comment by r-sidd** [comment]
> Thanks @r-sidd, this upgrade looks good for the main branch. This cannot be backported to the support branch due to Java 11 requirements, but this is helpful for the next major release version. +1 merging

Cool 🫡

**Pull request closed without merging**
