### PR TITLE
NIFI-5481 Additional Sensitive Property Providers (#3)

### PR DESCRIPTION
**Pull request by natural**
### Description of PR 

The code in this change-set provides the following:

  - refactors Sensitive Property Providers
  - adds AWS KMS sensitive property provider (https://issues.apache.org/jira/browse/NIFI-6325)
  - adds Key Store sensitive property provider (https://issues.apache.org/jira/browse/NIFI-6326)
  - adds HashiCorp Vault sensitive property provider (https://issues.apache.org/jira/browse/NIFI-6324)
  - adds GCP sensitive property provider (https://issues.apache.org/jira/browse/NIFI-6616)
  - adds Azure sensitive property provider (https://issues.apache.org/jira/browse/NIFI-6515)
  - integrates the above with the Config Encryption Toolkit (https://issues.apache.org/jira/browse/NIFI-6363)
  - unit tests, integration tests, documentation for the above

This PR replaces #3542 and #3672.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [x] Have you written or updated unit tests to verify your changes?
- [x] Have you verified that the full build is successful on both JDK 8 and JDK 11?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by bahlulh** [comment]
@natural, Thank you very much for the PR to add the secret providers in nifi. Since this change is big, I wanted to start by building your branch and running nifi locally with your change to test the providers. But looks like there are some missing dependencies in you PR. I will take a look again after you fix the build errors.

**Comment by sjyang18** [comment]
The JIRA link for Azure SPP got wrong in the description. It is 'https://issues.apache.org/jira/browse/NIFI-6615'

**Comment by thenatog** [comment]
I am still reviewing this PR, but as others said above I also had errors:

* There were compilation errors as a result of building with Java 8. I set to build with Java 11 instead, however it should be backwards compatible so some changes will need to be made.
* Small issue with javadoc for loadKeyStore() in HadoopCredentialsSensitivePropertyProvider.java:184.
* Had issues with RAT (contrib-check) check on the password files password.sidefile and bad-password.sidefile in nifi-properties-loader. I added a RAT exclude to nifi-properties-loader/pom.xml
* Issue with grpc dependency conflict, the nifi-properties-loader added dependency google-cloud-kms which included its own grpc. Had to exclude it from the google-cloud-kms dependency in the pom.

I can submit these fixes for merging, but the Java 8 compatibility still needs to be looked at.

**Comment by jfrazee** [comment]
I'm coming in a little late on this, but am wondering if it'd be easier to push this along by breaking it back apart into different PRs. I think that might also have the benefit of making the boundary between framework changes and implementations more clear since this currently adds some heavy-ish dependencies into nifi-framework.

**Pull request closed without merging**
