### PR TITLE
NIFI-4439: When a Provenance Event File is rolled over, we were faili…

### PR DESCRIPTION
**Pull request by markap14**
…ng to close the resource before attempting to compress it. Fixed that.

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by joewitt** [comment]
will validate on the environment i could cause this in

**Comment by joewitt** [comment]
I have run with the patch applied on the same system i saw the behavior on.  It is not fixed and there is now a NullPointerException.

Will post details shortly

**Comment by joewitt** [comment]
Still seeing the problem with patch applied.  And now a new error is present (i believe it is new).

2017-10-09 16:30:15,482 ERROR [Timer-Driven Process Thread-3] o.a.n.p.attributes.UpdateAttribute UpdateAttribute[id=cad5fe36-015e-1000-5ae7-ed36010ca5be] Failed to commit session StandardProcessSession[id=36876] due to java.lang.NullPointerException; rolling back: java.lang.NullPointerException
java.lang.NullPointerException: null
2017-10-09 16:30:15,498 WARN [Timer-Driven Process Thread-8] o.a.n.provenance.store.RecordWriterLease Failed to close org.apache.nifi.provenance.EventIdFirstSchemaRecordWriter@64bf8434
java.lang.NullPointerException: null
	at org.apache.nifi.provenance.serialization.CompressableRecordWriter.flush(CompressableRecordWriter.java:190)
	at org.apache.nifi.provenance.AbstractRecordWriter.close(AbstractRecordWriter.java:66)
	at org.apache.nifi.provenance.store.RecordWriterLease.close(RecordWriterLease.java:87)
	at org.apache.nifi.provenance.store.WriteAheadStorePartition.tryRollover(WriteAheadStorePartition.java:261)
	at org.apache.nifi.provenance.store.WriteAheadStorePartition.addEvents(WriteAheadStorePartition.java:186)
	at org.apache.nifi.provenance.store.PartitionedEventStore.addEvents(PartitionedEventStore.java:103)
	at org.apache.nifi.provenance.WriteAheadProvenanceRepository.registerEvents(WriteAheadProvenanceRepository.java:179)
	at org.apache.nifi.controller.repository.StandardProcessSession.updateProvenanceRepo(StandardProcessSession.java:766)
	at org.apache.nifi.controller.repository.StandardProcessSession.commit(StandardProcessSession.java:339)
	at org.apache.nifi.controller.repository.StandardProcessSession.commit(StandardProcessSession.java:322)
	at org.apache.nifi.controller.tasks.ContinuallyRunProcessorTask.call(ContinuallyRunProcessorTask.java:193)
	at org.apache.nifi.controller.tasks.ContinuallyRunProcessorTask.call(ContinuallyRunProcessorTask.java:47)
	at org.apache.nifi.controller.scheduling.TimerDrivenSchedulingAgent$1.run(TimerDrivenSchedulingAgent.java:128)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-10-09 16:30:15,498 WARN [Compress Provenance Logs-1-thread-1] o.a.n.p.s.EventFileCompressor Failed to delete .\provenance_repository\91731935.prov; this file should be cleaned up manually

**Comment by markap14** [comment]
@joewitt it looks like there was a threading issue that previously existed, but this patch made it far more likely to occur. Was able to easily replicate the issue that you mention above and addressed it with a new commit. Was also able to run for quite a while and verify that only a single .prov file had an open file handle. Please give this another try when you have a chance.

**Comment by joewitt** [comment]
on it - will advise

**Pull request closed without merging**
