### PR TITLE
NIFI-3799 - added input requirement info for processor documentation

### PR DESCRIPTION
**Pull request by pvillard31**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [X] Have you written or updated unit tests to verify your changes?

### For documentation related changes:
- [X] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by jvwing** [comment]
Reviewing...

**Comment by jvwing** [comment]
@pvillard31 - Everything works well in my testing.  Why add the notation to the bottom of the Description section, rather than creating a new section with heading?  For example, the Restricted section seems comparable, but it has a heading and then the text describing the restriction under the heading.

**Comment by pvillard31** [comment]
Hey @jvwing! Thanks for the review, you're right following the same "style" is more consistent. I updated the PR to follow the same approach as for restricted components.

**Comment by jvwing** [comment]
Thanks for that change, @pvillard31, it looks good.

**Comment by pvillard31** [comment]
Thanks @jvwing

**Pull request closed without merging**
