### PR TITLE
NIFI-2310 - Shiftr Transform in JoltTransformJSON Processor Does Not Support Escaping Special Characters

### PR DESCRIPTION
**Pull request by YolandaMDavis**
upgrade Jolt version to 0.0.21 which resolved issue.

### CODE REVIEW

**Comment by YolandaMDavis** [comment]
Here is the error that occurred before this fix shiftrparseerror

To test use the following specification for Shiftr ensure that spec is valid:

`{
      "\\@context": {
        "name": "&1.Name",
        "ingredient": "&1.Inputs",
        "yield": "\\@context.Makes",
        "*": "&1.&"
      },
      "name": "Name",
      "ingredient": "Inputs",
      "yield": "Makes",
      "*": "&"
    }
 `

Also the below test input can be used in the Advance (from http://jolt-demo.appspot.com/#json-ld-escaping)

`{
  "comment" : "pulled from http://json-ld.org/playground/ example recipe.  Also, Mojitos are good.",

  "@context": {
    "name": "http://rdf.data-vocabulary.org/#name",
    "ingredient": "http://rdf.data-vocabulary.org/#ingredients",
    "yield": "http://rdf.data-vocabulary.org/#yield",
    "instructions": "http://rdf.data-vocabulary.org/#instructions",
    "step": {
      "@id": "http://rdf.data-vocabulary.org/#step",
      "@type": "xsd:integer"
    },
    "description": "http://rdf.data-vocabulary.org/#description",
    "xsd": "http://www.w3.org/2001/XMLSchema#"
  },
  "name": "Mojito",
  "ingredient": [
    "12 fresh mint leaves",
    "1/2 lime, juiced with pulp",
    "1 tablespoons white sugar",
    "1 cup ice cubes",
    "2 fluid ounces white rum",
    "1/2 cup club soda"
  ],
  "yield": "1 cocktail",
  "instructions": [
    {
      "step": 1,
      "description": "Crush lime juice, mint and sugar together in glass."
    },
    {
      "step": 2,
      "description": "Fill glass to top with ice cubes."
    },
    {
      "step": 3,
      "description": "Pour white rum over ice."
    },
    {
      "step": 4,
      "description": "Fill the rest of glass with club soda, stir."
    },
    {
      "step": 5,
      "description": "Garnish with a lime wedge."
    }
  ]
}`

**Comment by ijokarumawak** [comment]
Start reviewing...

**Comment by ijokarumawak** [comment]
+1

I reproduced the validation error before applying this fix using the sample input and spec you shared, and confirmed that it's valid with this fix. Run a NiFi data-flow to transform Json using Jolt processor. It worked without problem.
Passed local contrib check successfully.

I will merge it in master branch.
Also I am going to test this with 0.x branch.

Thanks @YolandaMDavis !

**Comment by ijokarumawak** [comment]
Merged this commit to branch 0.x, too. Confirmed the sample Jolt spec with escape characters is validated and transformed successfully.

**Pull request closed without merging**
