### PR TITLE
NIFI-11595: StateProvider.replace() supports creating the initial state

### PR DESCRIPTION
**Pull request by turcsanyip**
# Summary

[NIFI-11595](https://issues.apache.org/jira/browse/NIFI-11595)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [x] JDK 11
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by Lehel44 — APPROVED** [review]
Thank you, @turcsanyip, for your contribution. The code appears to be in good shape and functions well. During testing, I explored the WriteAheadLocalStateProvider and observed that state operations using sessions utilize StandardProcessSession, while the ProcessContext's StateManager leverages the WriteAheadLocalStateProvider, which stores state data in NIFI_HOME/local.

However, it's worth noting that despite the 'replace' method being synchronized, I encountered a race condition scenario where the 'oldState' gets overwritten by one thread while the other is within the 'replace' method's monitor. This occurred due to 'WriteAheadLocalStateProvider.ComponentProvider.stateMap' not being declared as 'final.' and does not guarantee thread safety.

**Comment by Lehel44** [comment]
After further discussion, it was determined that the race condition problem came up as a result of debugger anomaly.

**Review by exceptionfactory — COMMENTED** [review]
Thanks for the improvements @turcsanyip and thanks for the review @Lehel44! I am planning to run a few more tests, but it should be ready to go soon.

**Review by exceptionfactory — APPROVED** [review]
Thanks for the improvements @turcsanyip! +1 merging

**Pull request closed without merging**
