### PR TITLE
NIFI-1959 Added length and timestamp to detect rollover

### PR DESCRIPTION
**Pull request by pvillard31**
It improves robustness of the processor in case the property “Rolling filename pattern” is not set and the tailed file is moved for some reasons.

### CODE REVIEW

**Comment by pvillard31** [comment]
It remains an issue I have not been able to solve at this point: the case where the new file contains more data than the tailed file before being moved. In this case we ends up in the same situation: the new data in not ingested and the processor is not yielded. This situation should not happen really often... but still... if someone has an idea.

To reproduce: tail on /tmp/test.log
echo "test" >> /tmp/test.log
rm /tmp/test.log
echo "testtest" >> /tmp/test.log

In this case, both timestamp and size cannot be used to detect a pseudo-rollover and we are stuck with the previous state and reader. Not sure to see an easy solution.

**Comment by JPercivall** [comment]
Hey @pvillard31, I'm gonna start reviewing this. I noticed this was initially committed back in June, sorry no one has reviewed this yet but could you rebase? I know there are no conflicts but a lot has happened on the master branch in last month that could have an impact.

**Comment by JPercivall** [comment]
@pvillard31 I think you should be able to leverage the checksum in order to check if the file that is there is the one that was previously read. Maybe convert the logic found [here](https://github.com/apache/nifi/blob/d3d59d58a51ded47ba1b7ebf87a79f678ab41cf2/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/TailFile.java#L791-L791) into it's own function and reuse it. This might need to be a configurable property though (not sure about the performance implications, esp for an extreme corner case).

**Comment by pvillard31** [comment]
Closing - implemented with #980

**Pull request closed without merging**
