### PR TITLE
NIFI 1922

### PR DESCRIPTION
**Pull request by atilcock**
NIFI-1922 : Added dependencies for HDInsight wasb file format.

### CODE REVIEW

**Comment by mattyb149** [comment]
The file "NIFI-1922-patch" is included in this commit and should not be, just the changes it implies (which have been applied). Can you remove this file from the commit? Please and thanks!

**Comment by mattyb149** [comment]
Also it looks like like you've got a merge commit in your chain here. Can you start with a fresh master branch, apply your patch, then push the pull request? If you have two commits, perhaps you could squash them after applying them before pushing the branch/PR.  Please let me know if you have any questions, I can help with these operations if need be :)

**Comment by atilcock** [comment]
Have rebuilt on base master branch - currently running tests - hope to resubmit in the next day or so.

**Comment by JPercivall** [comment]
@atilcock I see you opened another PR for this issue. Could you close this one?

**Comment by atilcock** [comment]
closing - replaced with updated PR #626

**Pull request closed without merging**
