### PR TITLE
NIFI-4834: Updated AbstractJMSProcessor to use a separate SingleConne…

### PR DESCRIPTION
**Pull request by markap14**
…ctionFactory per concurrent task instead of sharing one across the entire processor

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by alopresto** [comment]
Reviewing...

**Comment by alopresto** [comment]
I ran this with an ActiveMQ instance in Docker and a [simple flow](https://gist.github.com/alopresto/aec7eadd2ed8affd7be8e4056699e5f4) which published JMS messages to a queue and then consumed them. It ran very well at first, and I saw 10 threads on the ConsumeJMS once I configured it that way. But after starting and stopping a few times, the ActiveMQ admin panel showed 30 consumers (3 times start/stopping 10 consumers) and no messages were being consumed anymore. I have attached the bootstrap log which should have the thread dump contents.

**Comment by alopresto** [comment]
[thread_dump.txt](https://github.com/apache/nifi/files/1689929/thread_dump.txt)

**Comment by markap14** [comment]
@alopresto thanks, that's a great catch! I pushed a new commit that should address both of these issues. We were not properly shutting down the connections on the Processor was stopped. As a result, those Consumers were also not closed and so any prefetched messages were not rolled back. This caused you to also receive no more messages because the messages were all prefetched by the unclosed Consumers.

**Comment by alopresto** [comment]
With the fix Mark provided, everything looks great. 

Ran `contrib-check` and all tests pass. +1, merging.

**Comment by mgaido91** [comment]
this is causing some test failures on travis, but I am not able to reproduce the failures locally (https://api.travis-ci.org/v3/job/338096661/log.txt). Maybe we can revert it for the moment and merge it again after understanding and fixing the issue?

**Comment by mosermw** [comment]
I get the exact same unit test failures on Ubuntu 16.04.  I was working on NIFI-2630, so I thought it was my code changes, but the test failure happens when I build master without any changes.  Interestingly, when I build master on Windows 10, these unit tests pass.

**Comment by mgaido91** [comment]
on OSX they are passing too, so it may be a platform related error

**Pull request closed without merging**
