### PR TITLE
NIFI-5143: Support column values for paging results

### PR DESCRIPTION
**Pull request by mattyb149**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [x] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by pvillard31** [comment]
reviewing...

**Comment by pvillard31** [comment]
Code LGTM. I won't be a position to test all the adapters but will do some tests later (I'm in the middle of something else right now but should be able to get back on this tomorrow).

**Comment by pvillard31** [comment]
OK, I've been doing some tests against a Postgres database and everything is working as I'd expect. I've only one minor feedback regarding the property description.

> This property should only be used when the default queries are not performing well, when there is no maximum-value column or a single maximum-value column whose type can be coerced to a long integer (i.e. not date or timestamp), and the column values are evenly distributed and not sparse, for best performance.

I'd just add something regarding the "and the column values are evenly distributed and not sparse": I'd say that if this condition is not met, it could generate a lot of flow files (and back-pressure won't apply), and a lot of the generated queries would lead to query execution with no returned rows.

Not saying this should be added in the property description, but it could be something nice to add/mention in an "additional details" page?

That's really minor and can be ignored. Overall I'm a +1 on this PR and can merge whenever that's OK for you.

**Comment by mattyb149** [comment]
@pvillard31 I added an Additional Details page per your request. It is complicated behavior so definitely needed more explanation, hopefully it's not too confusing :)

**Comment by pvillard31** [comment]
Great, thanks @mattyb149 !
Merging to master.

**Pull request closed without merging**
