### PR TITLE
NIFI-12977: enable Netty leak detector extension

### PR DESCRIPTION
**Pull request by sullis**
# Summary

[NIFI-12977](https://issues.apache.org/jira/browse/NIFI-12977)

# Netty leak detector library
https://github.com/nettyplus/netty-leak-detector-junit-extension 

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [x] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for the contribution @sullis.

Although Netty is used in a number of extension components, it is not used for core framework communication, so this check does not seem particularly useful in the context of system tests.

Is there a particular issue you noticed when enabling this extension?

**Comment by sullis** [comment]
> Is there a particular issue you noticed when enabling this extension?

I have not noticed any Netty resource leaks.  The goal of this PR is to prevent future resource leaks.

Perhaps I should have put the Leak Detector extension on the ListenOLTPTest class.

I pushed an update that modifies ListenOLTPTest.java 

image

**Comment by joewitt** [comment]
`[ERROR] Tests run: 12, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 1.175 s <<< FAILURE! -- in org.apache.nifi.processors.opentelemetry.ListenOTLPTest
[ERROR] org.apache.nifi.processors.opentelemetry.ListenOTLPTest.testPostProtobuf -- Time elapsed: 0.018 s <<< ERROR!
java.lang.IllegalStateException: Netty leaks: after [testPostProtobuf()] [ByteBuf]
	at io.github.nettyplus.leakdetector.junit.NettyLeakListener.assertZeroLeaks(NettyLeakListener.java:31)
	at io.github.nettyplus.leakdetector.junit.NettyLeakDetectorExtension.afterEach(NettyLeakDetectorExtension.java:70)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

[ERROR] org.apache.nifi.processors.opentelemetry.ListenOTLPTest.testRequiredProperties -- Time elapsed: 0.001 s <<< ERROR!
java.lang.IllegalStateException: Netty leaks: [ByteBuf]
	at io.github.nettyplus.leakdetector.junit.NettyLeakListener.assertZeroLeaks(NettyLeakListener.java:31)
	at io.github.nettyplus.leakdetector.junit.NettyLeakListener.assertZeroLeaks(NettyLeakListener.java:20)
	at io.github.nettyplus.leakdetector.junit.NettyLeakDetectorExtension.beforeEach(NettyLeakDetectorExtension.java:77)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: java.lang.IllegalStateException: Netty leaks: after [testRequiredProperties()] [ByteBuf]
		at io.github.nettyplus.leakdetector.junit.NettyLeakListener.assertZeroLeaks(NettyLeakListener.java:31)
		at io.github.nettyplus.leakdetector.junit.NettyLeakDetectorExtension.afterEach(NettyLeakDetectorExtension.java:70)
		... 2 more

[ERROR] org.apache.nifi.processors.opentelemetry.ListenOTLPTest.testPostJsonPartialSuccess -- Time elapsed: 0.001 s <<< ERROR!
java.lang.IllegalStateException: Netty leaks: [ByteBuf]
	at io.github.nettyplus.leakdetector.junit.NettyLeakListener.assertZeroLeaks(NettyLeakListener.java:31)
	at io.github.nettyplus.leakdetector.junit.NettyLeakListener.assertZeroLeaks(NettyLeakListener.java:20)
	at io.github.nettyplus.leakdetector.junit.NettyLeakDetectorExtension.beforeEach(NettyLeakDetectorExtension.java:77)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: java.lang.IllegalStateException: Netty leaks: after [testPostJsonPartialSuccess()] [ByteBuf]
		at io.github.nettyplus.leakdetector.junit.NettyLeakListener.assertZeroLeaks(NettyLeakListener.java:31)
		at io.github.nettyplus.leakdetector.junit.NettyLeakDetectorExtension.afterEach(NettyLeakDetectorExtension.java:70)
		... 2 more

[ERROR] org.apache.nifi.processors.opentelemetry.ListenOTLPTest.testPostPathNotFound -- Time elapsed: 0.001 s <<< ERROR!
java.lang.IllegalStateException: Netty leaks: [ByteBuf]
	at io.github.nettyplus.leakdetector.junit.NettyLeakListener.assertZeroLeaks(NettyLeakListener.java:31)
	at io.github.nettyplus.leakdetector.junit.NettyLeakListener.assertZeroLeaks(NettyLeakListener.java:20)
	at io.github.nettyplus.leakdetector.junit.NettyLeakDetectorExtension.beforeEach(NettyLeakDetectorExtension.java:77)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: java.lang.IllegalStateException: Netty leaks: after [testPostPathNotFound()] [ByteBuf]
		at io.github.nettyplus.leakdetector.junit.NettyLeakListener.assertZeroLeaks(NettyLeakListener.java:31)
		at io.github.nettyplus.leakdetector.junit.NettyLeakDetectorExtension.afterEach(NettyLeakDetectorExtension.java:70)
		... 2 more

[ERROR] org.apache.nifi.processors.opentelemetry.ListenOTLPTest.testGetMethodNotAllowed -- Time elapsed: 0.001 s <<< ERROR!
java.lang.IllegalStateException: Netty leaks: [ByteBuf]
	at io.github.nettyplus.leakdetector.junit.NettyLeakListener.assertZeroLeaks(NettyLeakListener.java:31)
	at io.github.nettyplus.leakdetector.junit.NettyLeakListener.assertZeroLeaks(NettyLeakListener.java:20)
	at io.github.nettyplus.leakdetector.junit.NettyLeakDetectorExtension.beforeEach(NettyLeakDetectorExtension.java:77)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: java.lang.IllegalStateException: Netty leaks: after [testGetMethodNotAllowed()] [ByteBuf]
		at io.github.nettyplus.leakdetector.junit.NettyLeakListener.assertZeroLeaks(NettyLeakListener.java:31)
		at io.github.nettyplus.leakdetector.junit.NettyLeakDetectorExtension.afterEach(NettyLeakDetectorExtension.java:70)
		... 2 more

[ERROR] org.apache.nifi.processors.opentelemetry.ListenOTLPTest -- Time elapsed: 1.175 s <<< ERROR!
java.lang.IllegalStateException: Netty leaks: [ByteBuf]
	at io.github.nettyplus.leakdetector.junit.NettyLeakListener.assertZeroLeaks(NettyLeakListener.java:31)
	at io.github.nettyplus.leakdetector.junit.NettyLeakListener.assertZeroLeaks(NettyLeakListener.java:20)
	at io.github.nettyplus.leakdetector.junit.NettyLeakDetectorExtension.afterAll(NettyLeakDetectorExtension.java:57)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   ListenOTLPTest » IllegalState Netty leaks: [ByteBuf]
[ERROR]   ListenOTLPTest.testGetMethodNotAllowed » IllegalState Netty leaks: [ByteBuf]
[ERROR]   ListenOTLPTest.testPostJsonPartialSuccess » IllegalState Netty leaks: [ByteBuf]
[ERROR]   ListenOTLPTest.testPostPathNotFound » IllegalState Netty leaks: [ByteBuf]
[ERROR]   ListenOTLPTest.testPostProtobuf » IllegalState Netty leaks: after [testPostProtobuf()] [ByteBuf]
[ERROR]   ListenOTLPTest.testRequiredProperties » IllegalState Netty leaks: [ByteBuf]`

**Comment by joewitt** [comment]
To try and cause something to output I added a line into one of the  OTEL tests to just create a ByteBuf and leave it alone.  And indeed the tests started failing.  I then released the ByteBuf and indeed the tests again works.  However, they didn't make it clear which test had the issue and it isn't the one listed in the above output.  So as a general alerting perhaps that is helpful but in finding the core issue it didn't seem particularly helpful. 

Notably a full clean build with all the checks still works. The full system tests still work.  So to a certain sense this might give some added confidence about handling ByteBuf in the case of Netty well.  But we have a lot of cases of resource leak concerns and this only covers one.   For the most part our code reviews should consider such things. 

That said - I'm not confident pulling in this dependency and adding to these tests like this is currently warranted.  Our otel stuff for instance doesn't appear to make the byte buffers itself but rather the underlying library seems to.  If so that is the thing which should have such checks.  I might be wrong on that but worth noting.

I'm a -0 on this change as it stands.

**Comment by exceptionfactory** [comment]
Thanks for the updates @sullis, and thanks for evaluating the functionality @joewitt.

Although detecting resource leaks is an important part of developing with Netty, I agree with @joewitt that the failure messages are too generic to be useful under the circumstances.

With general efforts to reduce the dependency footprint of Apache NiFi over the last year, any new dependency needs to be evaluated carefully. If the error reporting were more fine-grained, or if it detected some existing issues, that might be more of a reason for inclusion.

As it stands however, I am a -1 and will close the PR for now. If new versions of the library are capable of more fine-grained error detection, this could be worth revisiting.

**Pull request closed without merging**
