### PR TITLE
NIFI-1623 Add new processor ConvertXmlToJson

### PR DESCRIPTION
**Pull request by claudiu-stanciu**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [X] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [x] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by claudiu-stanciu** [comment]
Looks like Travis failed 2/5 on some other tests, unrelated to my work.
AppVeyor as well, failed on unrelated tests.

Can someone relaunch the builds?

**Comment by joewitt** [comment]
@claudiu-stanciu no worries.  As long as it passes on one or more then we know the tests pass and contrib check is good.  We do see instability on travis.  It is still very useful as an aid as-is so no worries.  Just need someone who can help review the contrib at this stage.

Thanks for contributing!

**Comment by alopresto** [comment]
While I appreciate the effort that went into developing this processor, I think the ticket may be outdated, similar to [PR 1964 - NIFI-4141 (JSON to Orc)](https://github.com/apache/nifi/pull/1964). 

As I commented there, 

> Hi,
> 
> With the release of Apache NiFi 1.2.0 and 1.3.0, the record paradigm has been introduced to better support protocol/format/schema conversion. This moves away from the ConvertXToY type processors in favor of providing custom record reader and recordset writer controller service implementations which can be leveraged and re-used by LookupRecord, ConvertRecord, PartitionRecord, QueryRecord, MergeRecord, UpdateRecord, etc. There is already a JsonTreeReader, JsonPathReader, and JsonRecordSetWriter available, so if you were to provide an OrcReader and OrcRecordSetWriter, you would be able to perform bidirectional conversion of JSON to/from Orc, along with Grok, CSV, Avro, freeform text, and scripted implementations.

Similarly, I believe the community would be better served by creating a `XmlRecordReader` and `XmlRecordSetWriter` controller services which can be leveraged by the entire "record" ecosystem of processors.

**Comment by claudiu-stanciu** [comment]
Thank you for your feedbacks.

@alopresto sounds like a better long term strategy than individual converts, which are harder to maintain and to use. I'll take a look at the controller services around RecordSet.
+ Is there a thread around the record paradigm discussion? I can't find any :(

Should I make a new Jira ticket for XmlRecord controller services, or someone can update the existing one? Not so sure yet how things go on around here, as I'm pretty new :)

This was a fast workaround for me to ingest XML into my Hive tables :D (so xml -> json, and ingest json in hive ...)

Thanks

**Comment by alopresto** [comment]
@claudiu-stanciu Thanks for being understanding. I don't have an email thread on hand for the record stuff, but these articles ([Records and Schema Registries](http://bryanbende.com/development/2017/06/20/apache-nifi-records-and-schema-registries),
 [Record-Oriented Data with NiFi](https://blogs.apache.org/nifi/entry/record-oriented-data-with-nifi), and [Real-Time SQL On Event Streams](https://blogs.apache.org/nifi/entry/real-time-sql-on-event)) should give you a solid understanding. If you have specific questions, I can help, as can @markap14 and @mattyb149 among others. 

I'd suggest you make a new Jira for `XmlRecord*` and I will link it to the existing ticket and close that one as "Won't Fix"/OBE. Totally understand the need for XML ingest/transformation, and I think your contribution will be a big help to the community.

**Comment by alopresto** [comment]
I closed [NIFI-1623](https://issues.apache.org/jira/browse/NIFI-1623) and opened a new ticket [NIFI-4185 -- Add XML record reader & writer services](https://issues.apache.org/jira/browse/NIFI-4185) for the record-based XML reading/writing. I am going to close this PR as well and @claudiu-stanciu will open a new PR against NIFI-4185 with the services.

**Comment by claudiu-stanciu** [comment]
Closing PR as discussed

**Pull request closed without merging**
