### PR TITLE
NiFI-747: ListenHTTP exposes property for the URL path to accept data on

### PR DESCRIPTION
**Pull request by vs186031**
NiFI-747 : ListenHTTP exposes a URL path with a default value of /contentListener (to preserve backwards compatibility) . A user can now change the path to something convenient to them.

### CODE REVIEW

**Comment by trkurc** [comment]
One issue. The property will validate, but the processor will not run. I set the URI to 'content5000', but this causes errors like these
```
2015-10-16 20:37:08,755 ERROR [pool-28-thread-2] o.a.n.c.s.StandardProcessScheduler Failed to invoke @OnScheduled method due to java.lang.IllegalArgumentException: PathSpec contentListener5000/holds/*. must start with '/' or '*.'
```

**Comment by trkurc** [comment]
Aside from the property validation, it works as expected. I confirmed POSTs and DELETEs on HOLDs work (using Poster)
 
Just a quick style question, did you give any thought to not removing the annotation below and maybe instead changing it to 'Path("*")'?
'''
-@Path(ListenHTTP.URI)
'''

The reason I ask, I was trying to reason through the loop below, and thought your change may be an opportunity to remove the 'path == null' condition
'''
   for (final Class<? extends Servlet> cls : getServerClasses()) {
            final Path path = cls.getAnnotation(Path.class);
            if (path == null) {
                contextHandler.addServlet(cls, uri + "/*");
            } else {
                contextHandler.addServlet(cls, uri + "/" + path.value());
            }
        }
...
'''

**Comment by vs186031** [comment]
"I set the URI to 'content5000', but this causes errors like these..." 

- That's a good catch , i suspect this is due to the standard URI validator 

"Just a quick style question, did you give any thought to not removing the annotation below and maybe instead changing it to 'Path("*")'?"

- I did and then backed off to keep the first commit change minimal, however i agree this is a good opportunity to change the (if path==null) condition. 

One question : "I confirmed POSTs and DELETEs on HOLDs work (using Poster)" 

- What exactly is Poster ?

**Comment by trkurc** [comment]
>  What exactly is Poster ?
Ah, sorry, it is a firefox browser extension I like to use that makes it easy to do do arbitrary HTTP requests.

**Comment by vs186031** [comment]
>Aside from the property validation, it works as expected. I confirmed POSTs and DELETEs on HOLDs work (using Poster)

Added a small Regex to ensure that the Property Validation works.

>Just a quick style question, did you give any thought to not removing the annotation below and maybe instead changing it to 'Path("*")'?

Made this change as well.

I did the changes as two separate change-sets, just in case.

>Ah, sorry, it is a firefox browser extension I like to use that makes it easy to do do arbitrary HTTP requests.

This is actually quite cool , thanks for that.

**Comment by trkurc** [comment]
@vs186031  - I merged in your changes with some edits - please take a look at the final squashed commit (https://github.com/apache/nifi/commit/88b1b844fba5e4dded6242bb17f2096ff4172ed3). As @joewitt  mentioned on Jira, this ticket probably was mislabeled as a newbie ticket. Nice work!

**Pull request closed without merging**
