### PR TITLE
NIFI-766 Added icon on connection when backpressure is enabled

### PR DESCRIPTION
**Pull request by pvillard31**
Here is a proposition to display an icon on a connection when back pressure is enabled.

At the moment, there is no icon displayed whether back pressure is configured or not. (I am not sure it is worth adding information that is not that important to users: back pressure is configured by default)

First time I take a shot at UI dev, please review with care ;)

### CODE REVIEW

**Comment by mcgilman** [comment]
Reviewing...

**Comment by mcgilman** [comment]
@pvillard31,

Following some of the discussion on the mailing list recently and the original commentary on the JIRA [1], I'd like to propose shifting from an icon based approach when back pressure is engaged to a progress bar style approach where the user can quickly get a sense of how 'full' the queue is currently.

backpressure

The mockup shows various configuration scenarios. 

- Expiration (clock icon)
- Object and Data size backpressure (left and right bars respectively)
- Empty bar - backpressure not configured
- Partial bar - backpressure configured, partial represent precentage full
- Full solid bar - backpressure engaged

If you're up for some additional cycles on this PR I'd be happy to work through the changes with you. If not, I'm happy to take what you started and continue toward the mockup above.

Thanks!

[1] https://issues.apache.org/jira/browse/NIFI-766

**Comment by mcgilman** [comment]
Can someone else finish up the review of this PR? I helped contribute to this PR and would prefer someone else's eyes on. Thanks!

**Comment by markap14** [comment]
@mcgilman @pvillard31 I made one slight change to ConnectionStatus to rename the getters/setters from setBackpressureDataSizeThresholdLong to setBackpressureBytesThreshold to align with the existing naming convention. Otherwise, all looks great! Tested and verified that all worked as expected. The UI looks great. Thanks for updating this, guys. It's been a long time coming and will be very helpful! +1 merged to master.

**Pull request closed without merging**
