### PR TITLE
NIFI-8493: PutDatabaseRecord incorrect type resolution when column values are ordered differently

### PR DESCRIPTION
**Pull request by naddym**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR
When PutDatabaseRecord is projected to different column values ordering, it incorrectly tries to convert type and results in exception such as NumberFormatException for conversion of string to int. 

_Enables X functionality; fixes bug NIFI-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by tonykoval** [comment]
@naddym I think, this is duplicate #5024

**Comment by naddym** [comment]
Oh, Thanks @tonykoval . I didn't know as the PR was created few days back and the issue I worked on was created just yesterday. Will close  this PR as there is already with same implementation #5024 but would like to also include different column ordering testcase in that PR #5024. 

@mattyb149 Please comment if the testcase looks good.

**Comment by mattyb149** [comment]
The test case looks good, thank you! I've incorporated it into my PR, which will hopefully be reviewed/merged shortly.

**Comment by naddym** [comment]
Thanks @mattyb149

**Pull request closed without merging**
