### PR TITLE
NIFI-1805

### PR DESCRIPTION
**Pull request by jdye64**
Expose BackPressureObjectThreshold and BackPressureDataSizeThreshold to
ConnectionStatus

### CODE REVIEW

**Comment by aperepel** [comment]
I wonder if, upon crossing a threshold, we should raise a bulletin maybe?

**Comment by jdye64** [comment]
@aperepel that isn't a bad idea. That takes a little more discussion around how often we continue to post that bulletin if the threshold is constantly exceeded, what severity, etc

**Comment by jdye64** [comment]
It might make more sense to leave those sort of operations to a ReportingTask however? Does anyone have any thoughts around that?

**Comment by apiri** [comment]
I like the ReportingTask path.

**Comment by markap14** [comment]
We have talked before about having some sort of icon on a connection that indicates that back pressure is configured and then some sort of indicator that back pressure is applied. Perhaps an icon on the connection that is grey when configured but the threshold is not met, and then it would turn red or something if backpressure is actively being applied. The only issue with this approach is that we always have more & more things that we want to show and we have to balance what to show vs. how much screen real estate should be used. I am hoping that the UI redesign going on for 1.0 will make this work much better.

**Comment by aperepel** [comment]
@markap14 don't show more, change _how_ things are shown. in case of a connection and backpressure a simple gradient change in color (or a binary ok/throttled color) of the black is all it takes, IMO.

**Comment by apiri** [comment]
@jdye64 Apologies for delays.  These changes look fine and everything builds fine.  As far as the other commentary on this thread, I will leave that to folks to generate other issues to track, but these changes should certainly help as a means for any of those enhancements.

**Pull request closed without merging**
