### PR TITLE
NIFI-4307 Added Kotlin 1.1.X support to ExecuteScript.

### PR DESCRIPTION
**Pull request by MikeThomsen**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by mattyb149** [comment]
I had started work in this area as well but hadn't sufficiently tested it to make sure it was working. Do you mind taking a look and including anything you think is relevant (such as unit tests, the configurator to handle the weird bindings thing, etc.)? https://github.com/apache/nifi/compare/master...mattyb149:kotlin-scripting?expand=1
I hope to review this week

**Comment by mattyb149** [comment]
@MikeThomsen We've talked a bit on the mailing lists, what do you want to do here? I want to make sure your contribution is recognized, as those changes were an integral part of my own branch, except I hadn't cherry-picked and tried to overlay my commits. If (as you mentioned) you'd like to start from the branch I had, would you like to test/add/change/delete from there and then push a new branch/PR? Would be happy to review and merge (and yes of course you could alter whatever you want from anything I had!)

**Comment by MikeThomsen** [comment]
@mattyb149 I did a sample flow with each of ours and found the performance to be awful. I did some investigation and experimentation with the Kotlin ScriptEngine and found that after repeatedly running the same script over and over again, the performance seems to progressively degrade. At least that is what I am seeing.

I tried using the Compilable (I think) interface for it, which seems to actually run code through the Kotlin compiler and execute only the generated output. That ran like a champ (as one would hope), but that means we might have to gut a lot of ExecutScript and such and start over with Compilable to make this work.

I am not sure if that is viable because I don't know if all of the supplied engines support that interface.

**Comment by mattyb149** [comment]
Your instinct about Compilable is spot-on, it's exactly when I stopped working this branch :P For ExecuteScript, I'd thought such a processor would be for quick onTrigger() implementations, and due to multithread issues with [NIFI-1822](https://issues.apache.org/jira/browse/NIFI-1822) (concurrent tasks) with various scripting engines, things might get dicey for Compilable engines.  However this would be an excellent enhancement for InvokeScriptedProcessor (ISP), with the caveat that the engine is also Invocable. I haven't run thru the list of engines thus far (to include Kotlin) to see what that would look like, but I have investigated it and for the sake of generality I left it out of the current code. If we can improve ISP (or even ExecuteScript) by leveraging Compilable, I am totally on board!

**Comment by MikeThomsen** [comment]
I think Kotlin makes no sense in light of this because it's really not a scripting language. Focusing on InvokeScriptProcessor would make more sense because that is where a language like Kotlin could really shine. It also opens up the potential use of Scala there too.

**Comment by MikeThomsen** [comment]
I closed this pull request because I think there is a lot of refactoring that will be required to make this work.

**Pull request closed without merging**
