### PR TITLE
NIFI-9944: Fixed issue with using modules in InvokeScriptedProcessor

### PR DESCRIPTION
**Pull request by mattyb149**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Enables X functionality; fixes bug NIFI-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [ ] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by exceptionfactory** [comment]
Thanks for addressing this issue @mattyb149!

At a high level, are there other approaches to implementing a unit test that would avoid committing a binary library `commons-math3` to the repository? Is it possible to depend on another NiFi module and use that for testing, perhaps use the Maven download plugin to retrieve the dependency?

**Comment by mattyb149** [comment]
Originally I was using `commons-text` which got brought in transitively (in test scope) but wanted to prove it was actually using the JAR specified in the Module Directory property. If that's not necessary I can change it back, or if there's a better way to do it, I just didn't know how to bring something in with Maven and then set the Module Directory property to that location

**Comment by exceptionfactory** [comment]
One option to achieve a similar result would be to use the Maven Dependency [copy-dependencies](https://maven.apache.org/plugins/maven-dependency-plugin/copy-dependencies-mojo.html) goal to specify the the `commons-math3` dependency to be copied into the target directory. With the correct dependency scope, most likely `optional`, this should avoided putting the dependency on the test class path, but allow it to be available for test execution. I can take a closer look at providing a working example based on your PR soon.

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
@mattyb149 I created a branch based on your PR and pushed a commit that removes `commons-math3` from the repository and instead uses the `maven-dependency-plugin` to copy the JAR into the expected directory during the processing of test resources. This makes it available exclusively for `TestInvokeJavascript`, without impacting either the test or runtime class path directly.

I also made some adjustments to `TestInvokeJavascript` so that it should use the full path to the test script and modules directory.

https://github.com/exceptionfactory/nifi/commit/6cfb1f146909e7848189164bb133303085ff6057

If this works as intended, feel free to pull the commit into your PR branch.

**Comment by exceptionfactory** [comment]
@mattyb149 I went ahead and pushed the commit to the PR branch, feel free to make additional adjustments as needed.

**Comment by mattyb149** [comment]
Thanks @exceptionfactory ! I was just about to push a commit with the Maven plugin but I like yours better as it improves the tests as well :)  +1 LGTM, merging to main

**Pull request closed without merging**
