### PR TITLE
NIFI-10730 Update Splunk to 1.7.1

### PR DESCRIPTION
**Pull request by mr1716**
# Summary

[NIFI-10730](https://issues.apache.org/jira/browse/NIFI-10730)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI-10730) issue created

### Pull Request Tracking

- [X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X] Pull Request based on current revision of the `main` branch
- [X] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [X] JDK 8
  - [X] JDK 11
  - [X] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by mr1716** [comment]
All of the workflows did work and run successfully the other day

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for the upgrade @mr1716.

Unfortunately it looks like version 1.7.1 introduces a dependency on a Maven plugin, which appears to be a build problem.

However, the latest version, [1.9.1](https://dev.splunk.com/enterprise/docs/relnotes/relnotes-javasdk/whatsnew#Version-191) appears to have a clean set of dependencies.

It looks like version 1.8.0 required certificate validation, but that seems like a reasonable change given standard deployments.

Can you change the version upgrade to 1.9.1?

**Comment by mr1716** [comment]
@exceptionfactory thanks for the heads up. I made the change to 1..91

**Review by exceptionfactory — APPROVED** [review]
Thanks @mr1716 +1 merging

**Pull request closed without merging**
