### PR TITLE
NIFI-6852 Don't Validate Processors that accept any ControllerService…

### PR DESCRIPTION
**Pull request by shawnweeks**
… Implementation

Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

Validating Controller Services in Dynamic Properties broke ExecuteGroovyScript. In this fix I'm not validating the controller service if your not looking for a concrete definition.

_Enables X functionality; fixes bug NIFI-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on both JDK 8 and JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by joewitt** [comment]
Definitely need good reviews/thought here as this might have unintended consequences

**Comment by shawnweeks** [comment]
I'm going to check the lookup services and make sure they still work. Technically anything coming in this way should have been failing like the groovy processor was.

**Comment by shawnweeks** [comment]
@joewitt Do you have any suggestions on building a test case for this. We have basically no test cases for this class at all and I'm not having much luck getting enough of it stubbed out to actually test it.

**Comment by shawnweeks** [comment]
I've added some integration tests. Since part of the tests require the controller service to come from a separate bundle I've added another bundle to the test suite. To test one of the scenarios I have to disable document generation for the bundle so I tried to keep the more drastic changes to the second bundle. If anyone has suggestions of options on how everything should be named let me know. I've verified that testMatchingGenericControllerService and testMatchingGenericDynamicPropertyControllerService  tests failed before making the change to AbstractComponentNode.

**Comment by joewitt** [comment]
I did not quite understand what this change was for.  I thought we were going to skip validation of a configured service just because the component that might use it was ok with any service.  However, I discussed it offline with Bryan Bende and he explained the reason this change is good is that what we're actually relaxing is enforcing whether the configured service matches the particular API.  In this case a component is saying "I'll use any controller service so dont bother verifying it is of a particular type".

The tests look relevant to the issue at hand and the change is reported to by support by burgess, bende, shawn, and markbean.  +1 will merge

**Comment by joewitt** [comment]
super annoyingly Travis says all is fine.  However when I build locally I see the new test class does indeed not have a license header and the build fails.  Resolving.

**Comment by shawnweeks** [comment]
Sorry about the license, I thought I had copy/pasted it everywhere.

**Pull request closed without merging**
