### PR TITLE
NIFI-12242: Added ability to route data that exceeds the configured t…

### PR DESCRIPTION
**Pull request by markap14**
…hreshold in ControlRate to be routed to  'rate exceeded' instead of just staying in the queue. Added Use Case documentation to ControlRate.

# Summary

[NIFI-00000](https://issues.apache.org/jira/browse/NIFI-00000)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by mosermw** [comment]
reviewing

**Review by mosermw — COMMENTED** [review]
Just a couple documentation comments, the rest of the code looks good.  I tested the logic in running NiFi and the new options and relationships work as expected.

**Comment by markap14** [comment]
Thanks @mosermw pushed a commit that addresses the above.

**Comment by mosermw** [comment]
+1 merging to main

**Pull request closed without merging**
