### PR TITLE
NIFI-12573 Improve support for Enum values in PropertyDescriptor.Builder

### PR DESCRIPTION
**Pull request by EndzeitBegins**
# Summary

[NIFI-12573](https://issues.apache.org/jira/browse/NIFI-12573)
Lowers type restrictions on three methods in `PropertyDescriptor.Builder` to allow to work with `DescribedValue` instead of child class `AllowableValue` and with both `Enum` classes that do and do not implement `DescribedValue`.

Also addresses [NIFI-12574](https://issues.apache.org/jira/browse/NIFI-12574) by adding a new method `clearDefaultValue` to `PropertyDescriptor.Builder`. 

Adds several test cases for the affected code.

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [x] Build completed using `mvn clean install -P contrib-check`
  - [x] JDK 21

### Licensing

- [x] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [x] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [x] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — COMMENTED** [review]
Thanks for the contribution @EndzeitBegins. Supporting any `enum` would follow a similar pattern to the existing methods that take a set of strings. Is there any other particular reason prompting these changes? In the course of new implementations, providing an enum that implements `DescribedValue` is always preferred because it requires methods for display name and description.

**Comment by EndzeitBegins** [comment]
Thanks for the questions @exceptionfactory.
First of all I agree that it should be preferred to let the enums implement `DescribedValue` whenever feasible.
Maybe that's something worth to better highlight in the code documentation. 

In particular I thought about two situations, where the more adaptive approach introduced in this PR would be beneficial.
1. There might be cases we're an existing enum (e.g. from a library) is used that cannot be altered. Even though I'd personally prefer creating one's own enum (implementing DescribedValue) that maps to the library one (similar to the azure bundle) I can see how someone might not want to go "the extra mile".
2. And by far more important to me, I noticed that when using the existing `public <E extends Enum<E>> Builder allowableValues(final E[] values)` with an enum that actually implements DescribedValue, those values will be ignored, which might come as a surprise.

**Comment by exceptionfactory** [comment]
Thanks for the quick reply @EndzeitBegins. That's a very good point about the second scenario, and the first one is also reasonable. With that background, I agree with the changes and will proceed with merging. +1

**Review by exceptionfactory — APPROVED** [review]

**Comment by EndzeitBegins** [comment]
As always, thank you for input and taking on the merge process @exceptionfactory. 🙂👍🏻

**Pull request closed without merging**
