### PR TITLE
NIFI-11899 - Clear bulletin metrics registry to ensure it is reset with latest bulletins

### PR DESCRIPTION
**Pull request by YolandaMDavis**
# Summary

[NIFI-11899](https://issues.apache.org/jira/browse/NIFI-11899)

The JIRA resolves an issue where the nifi_bulletin metric value was not reset to reflect bulletins that are currently firing. Previously any bulletin that fired was added to the metric registry however the registry was never updated, giving a false sense that the bulletin is still firing. 

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X] Pull Request based on current revision of the `main` branch
- [X] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

1. Create a flow which would generate an error.  For example the flow below uses ConsumeTwitter and LogAttribute with ConsumeTwitter bearer token misconfigured purposefully. Do not start the flow.

image

2. Capture current metrics available using the Prometheus metrics api endpoint (e.g. https://127.0.0.1:8443/nifi-api/flow/metrics/prometheus) and search output to confirm that the nifi_bulletin metric does not appear, indicating there are no bulletins present

4. Start flow and confirm that bulletins showing an error/warning is present

image

5. On the metrics endpoint confirm that the nifi_bulletin metrics appear with values corresponding to each component demonstrating an error. With the example flow metrics show a single metric entry with a value of 1

image

6. Stop the flow and await for bulletins to clear from the UI

7. Confirm on metrics endpoint that nifi_bulletin metric no longer appears or no longer contains the specific bulletin that was created

### Build

- [X] Build completed using `mvn clean install -P contrib-check`
- [X] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — COMMENTED** [review]
Thanks for addressing this issue @YolandaMDavis!

Given that `bulletinMetricsRegistry` is a member variable on the `StandardNiFiServiceFacade`, would it make more sense to change the approach to make it a method-local variable? This would require some additional adjustments, but it would help clarify that the Bulletin Metrics Registry is a transitory collection, and might also avoid potential threading issues.

**Comment by YolandaMDavis** [comment]
> Thanks for addressing this issue @YolandaMDavis!
> 
> Given that `bulletinMetricsRegistry` is a member variable on the `StandardNiFiServiceFacade`, would it make more sense to change the approach to make it a method-local variable? This would require some additional adjustments, but it would help clarify that the Bulletin Metrics Registry is a transitory collection, and might also avoid potential threading issues.

 @exceptionfactory thanks for the quick review.  Sure that shouldn't be a problem.

**Comment by YolandaMDavis** [comment]
@exceptionfactory I've posted an update based on your comments. Please let me know if there's any other changes needed.

**Review by exceptionfactory — APPROVED** [review]
Thanks for making the adjustments @YolandaMDavis, verified the corrected bulletin metrics output at runtime, and the code changes look good! +1 merging

**Pull request closed without merging**
