### PR TITLE
NIFI-1710 - Resolve path name to nifi.sh script

### PR DESCRIPTION
**Pull request by trixpan**
## Description:
This commit allows nifi.sh to recursively traverse its path, allowing the simple linkage of nifi.sh to a script within /etc/init.d/ , therefore minimising the number of changes outside NIFI_HOME, required to implement a NIFI node.

Fixes: NIFI-1710
Closes #315 

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [x] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### CODE REVIEW

**Comment by trixpan** [comment]
@jfrazee @arpitgupta @busbey 

Since PR#315 got stalled, I reworked from scratch.

Would appreciate your feedback if this solves the problem reported on NIFI-1710

@apiri @YolandaMDavis - Can you see any issues with the approach?

**Comment by trixpan** [comment]
From my tests, path finding seems to work well:

```
[trixpan@development init.d]$ ls -l nifi
lrwxrwxrwx 1 root root 34 Oct 14 15:02 nifi -> /home/trixpan/development/nifi.sh
[trixpan@development init.d]$ ls -l /home/trixpan/development/nifi.sh
lrwxrwxrwx 1 trixpan trixpan 108 Oct 14 15:01 /home/trixpan/development/nifi.sh -> /home/trixpan/development/nifi/nifi-assembly/target/nifi-1.1.0-SNAPSHOT-bin/nifi-1.1.0-SNAPSHOT/bin/nifi.sh
[trixpan@development init.d]$ ./nifi status

Java home: /etc/alternatives/java_sdk_1.8.0/
NiFi home: /home/trixpan/development/nifi/nifi-assembly/target/nifi-1.1.0-SNAPSHOT-bin/nifi-1.1.0-SNAPSHOT

Bootstrap Config File: /home/trixpan/development/nifi/nifi-assembly/target/nifi-1.1.0-SNAPSHOT-bin/nifi-1.1.0-SNAPSHOT/conf/bootstrap.conf

2016-10-14 15:03:02,399 INFO [main] org.apache.nifi.bootstrap.Command Apache NiFi is currently running, listening to Bootstrap on port 35711, PID=16000

[trixpan@development init.d]$
```

**Comment by jfrazee** [comment]
@trixpan Thanks for picking this up again! Since this is just about variation in the arguments that readlink supports or the availability of realpath, I would have thought it'd just be simpler to have a case statement around the platform/uname. I don't see anything wrong with it at all, it's just a little complicated.

**Comment by trixpan** [comment]
Indeed. 

Yet, as discussed in the original stackoverflow thread, the shell approach is greatly portable and eliminate the need to have any of the external utils. 

At least we didn't end up uaing python. :-) 

Would appreciate if you could confirm it works with you as well. 

Cheers

**Comment by alopresto** [comment]
Reviewing...

**Comment by alopresto** [comment]
Built with `contrib-check`, all tests pass (Mac OS X 10.11.6, GNU bash, version 4.3.42(1)-release (x86_64-apple-darwin15.0.0), Java 1.8.0_101). Created a symlink to `bin/nifi.sh` in another directory and was able to execute the script. +1, merging. 

```
hw12203:/Users/alopresto/Workspace (master) alopresto
🔓 27s @ 16:32:11 $ cd scratch/
hw12203:/Users/alopresto/Workspace/scratch (master) alopresto
🔓 14s @ 16:32:30 $ ln -s /Users/alopresto/Workspace/nifi/nifi-assembly/target/nifi-1.1.0-SNAPSHOT-bin/nifi-1.1.0-SNAPSHOT/bin/nifi.sh nifi
hw12203:/Users/alopresto/Workspace/scratch (master) alopresto
🔓 10s @ 16:33:43 $ ls -l nifi
lrwxr-xr-x  1 alopresto  staff  108 Oct 18 16:32 nifi -> /Users/alopresto/Workspace/nifi/nifi-assembly/target/nifi-1.1.0-SNAPSHOT-bin/nifi-1.1.0-SNAPSHOT/bin/nifi.sh
hw12203:/Users/alopresto/Workspace/scratch (master) alopresto
🔓 4s @ 16:33:52 $ ./nifi status

Java home: /Users/alopresto/.jenv/versions/1.8
NiFi home: /Users/alopresto/Workspace/nifi/nifi-assembly/target/nifi-1.1.0-SNAPSHOT-bin/nifi-1.1.0-SNAPSHOT

Bootstrap Config File: /Users/alopresto/Workspace/nifi/nifi-assembly/target/nifi-1.1.0-SNAPSHOT-bin/nifi-1.1.0-SNAPSHOT/conf/bootstrap.conf

2016-10-18 16:33:58,029 INFO [main] org.apache.nifi.bootstrap.Command Apache NiFi is currently running, listening to Bootstrap on port 58166, PID=78128

hw12203:/Users/alopresto/Workspace/scratch (master) alopresto
🔓 9s @ 16:34:01 $ ./nifi stop

Java home: /Users/alopresto/.jenv/versions/1.8
NiFi home: /Users/alopresto/Workspace/nifi/nifi-assembly/target/nifi-1.1.0-SNAPSHOT-bin/nifi-1.1.0-SNAPSHOT

Bootstrap Config File: /Users/alopresto/Workspace/nifi/nifi-assembly/target/nifi-1.1.0-SNAPSHOT-bin/nifi-1.1.0-SNAPSHOT/conf/bootstrap.conf

2016-10-18 16:35:43,851 INFO [main] org.apache.nifi.bootstrap.Command Apache NiFi has accepted the Shutdown Command and is shutting down now
2016-10-18 16:35:43,883 INFO [main] org.apache.nifi.bootstrap.Command Waiting for Apache NiFi to finish shutting down...
2016-10-18 16:35:45,893 INFO [main] org.apache.nifi.bootstrap.Command NiFi has finished shutting down.

hw12203:/Users/alopresto/Workspace/scratch (master) alopresto
🔓 107s @ 16:35:49 $ 
```

**Pull request closed without merging**
