### PR TITLE
NIFI-79 - Introduces the ability to set Bulletin Level to NONE

### PR DESCRIPTION
**Pull request by trixpan**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [X] Have you written or updated unit tests to verify your changes?
- [X] ~~~If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?~~~ 
- [X] ~~~If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?~~~
- [X] ~~~If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?~~~
- [X] ~~~If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?~~~

### For documentation related changes:
- [X] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by trixpan** [comment]
@mcgilman would you be able to give me a hand by reviewing this PR? I was able to reproduce the desired behavior but not sure if the implementation is adequate

**Comment by mcgilman** [comment]
Will review...

**Comment by mcgilman** [comment]
@trixpan Thanks for the PR. Everything functions correctly but behind the scenes we were recording observers for the NONE log level because the observers are registered according to the severity. For instance, configuring for INFO will register an observer for INFO, WARN, ERROR, etc. The tweak I'm proposing would be to not register an observer for NONE since that is not really a true log level (no component will ever log a message to the NONE level). I've added this to your commit here [1]. If your happy with this too, I'll merge to master.

Thanks!

[1] https://github.com/mcgilman/nifi/commit/b38dc41b7ce8777d26d5394184efcc0e20c64312#diff-3d6bee4e7568e4e4034ef059df9e2b47

**Comment by trixpan** [comment]
@mcgilman I suspected I could be  missing something. Thanks for the clarification and improvement. Happy for you to merge

**Comment by mcgilman** [comment]
Thanks @trixpan! This has been merged.

**Comment by mcgilman** [comment]
@trixpan Totally forgot to add the 'This closes...' bit to the commit message. Can you please close the PR? Thanks!

**Comment by trixpan** [comment]
closing as requested by @mcgilman

**Pull request closed without merging**
