### PR TITLE
NIFI-4971: ReportLineageToAtlas complete path can miss one-time lineages

### PR DESCRIPTION
**Pull request by ijokarumawak**
The detailed explanation of this issue is written in the [NIFI-4971](https://issues.apache.org/jira/browse/NIFI-4971) JIRA description and comment. Please refer those as well.

- Separated Hook message de-duplication logic from NiFiAtlasHook to
NotificationSender
- NiFiAtlasHook used to send individual CREATE_ENTITY messages for each entities,
this commit changed it to bundle all new entities into a single
CREATE_ENTITY to preserve entity creation order, so that new DataSet
entities can be referred from new nifi_flow_path entities
- Added more unit tests

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by ijokarumawak** [comment]
This PR has been superseded by #2577.

**Comment by ijokarumawak** [comment]
Closed different PR by mistake. Reopening ..

**Comment by MikeThomsen** [comment]
@ijokarumawak Needs a rebase. I might have time tomorrow to fire up Atlas and help you on this.

**Comment by ijokarumawak** [comment]
Thank you @MikeThomsen for jumping on this. Rebased with the latest master.

**Comment by MikeThomsen** [comment]
I have to rebuild and setup Atlas.

**Comment by MikeThomsen** [comment]
I set everything up and set it to do `complete path.` This is what I got in Atlas:

screen shot 2018-04-24 at 10 17 16 am
screen shot 2018-04-24 at 10 18 03 am

**Comment by ijokarumawak** [comment]
@MikeThomsen I might have missed your points, but let me answer to your comments.

For the lineage graphs showing two outgoing links from /tmp/in/test to two `GetFile, PutFile` processes going to the final /temp/out/test, I assume having two processes is what you are concerning. Can you share what the `qualified name` attributes of those two `nifi_flow_path` entities? I guess those have different qualified name and probably each created by 'simple path' and 'complete path' if you run the same flow with both strategies.

For the comment of not seeing any lineage with 'simple_path', Atlas does not draw lineage if you choose an entity which is subclass of 'Process'. When you selected the 'nifi_flow_path' entity, didn't its input/output attribute have link to the `fs_path` entities? If you follow the link, then lineage will be shown from the `fs_path` entity, which is a subclass of 'DataSet'.

Please let me know if above descriptions address your issues. Thanks!

**Comment by MikeThomsen** [comment]
I'm not entirely sure. My experience with Atlas is very limited, and I'm mostly trying to figure out what to expect vs what I'd like to see if that makes any sense.

**Comment by MikeThomsen** [comment]
@ijokarumawak I went back and looked at the Jira ticket again, and my interpretation is that what I saw in the screenshots above (with the graph) matches your description of the behavior you wanted to implement.

**Comment by ijokarumawak** [comment]
Thanks @MikeThomsen for confirming that. I hope that confirms this PR addresses the issue it supposed to fix. Are we good to merge this now?

**Pull request closed without merging**
