### PR TITLE
NIFI-12100_deprecate Added DeprecationNotice annotation to the ConvertExcelToCSVProcessor

### PR DESCRIPTION
**Pull request by dan-s1**
# Summary

[NIFI-12100](https://issues.apache.org/jira/browse/NIFI-12100)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [x] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for the contribution @dan-s1. The change itself looks good, but the target branch needs to be `support/nifi-1.x` instead of `support/nifi-1.23`.

**Comment by dan-s1** [comment]
@exceptionfactory Does that mean I have to create a branch off of support/nifi-1.x with my change and then create a new PR or does it just mean editing this PR with the new target branch?

**Comment by exceptionfactory** [comment]
> @exceptionfactory Does that mean I have to create a branch off of support/nifi-1.x with my change and then create a new PR or does it just mean editing this PR with the new target branch?

@dan-s1 Changing the base branch of this pull request to `support/nifi-1.x` should be sufficient provided that is does not result in bringing in any additional commits. If it does result in additional commits, then you will need to create a new pull request with this specific commit, from the `support/nifi-1.x` branch. Thanks!

**Comment by dan-s1** [comment]
@exceptionfactory It resulted in other commits so I created a new branch off of support/nifi-1.x and I will create another PR. Interesting I am doing the build with the contrib profile and there was a Checkstyle violation on another piece of code SplitJson

**Comment by exceptionfactory** [comment]
> @exceptionfactory It resulted in other commits so I created a new branch off of support/nifi-1.x and I will create another PR. Interesting I am doing the build with the contrib profile and there was a Checkstyle violation on another piece of code SplitJson

Thanks @dan-s1. Feel free to close this pull request when you have the new one submitted.

**Pull request closed without merging**
