### PR TITLE
NIFI-3052 Update screenshots in Admin Guide and Getting Starting guid…

### PR DESCRIPTION
**Pull request by andrewmlim**
…e for additional colors added to UI.  Also updated Global Menu (text alignment has been fixed) and lineage graph (download icon has been added).

### CODE REVIEW

**Comment by scottyaslan** [comment]
Reviewing...

**Comment by scottyaslan** [comment]
@andrewmlim I dont think you can just change the start and stop icons since the context menu and the operate pallet still use the blue icons...

**Comment by andrewmlim** [comment]
@scottyaslan Thanks for catching that.  I think we can go through with this PR because for the Admin Guide and Getting Started Guide, we do want to use the colored icons.  So iconRun, iconStop, iconAlert will be the screenshots that show _status_.   I will create a separate Jira to capture the blue icons needed for the operate pallete and context menu buttons.

**Comment by andrewmlim** [comment]
Filed as:  https://issues.apache.org/jira/browse/NIFI-3056

**Comment by scottyaslan** [comment]
@andrewmlim  another item to be addressed here would be the enabled/disabled and the transmitting/not-transmitting icons as the color of these icons have changed recently as well....

**Comment by andrewmlim** [comment]
Thanks @scottyaslan.  I modified https://issues.apache.org/jira/browse/NIFI-3056 to be more generic to capture all the screenshots that still need to be updated as a a result of https://issues.apache.org/jira/browse/NIFI-2603.   But I think this PR should go through since all the screenshots for the Admin Guide and Getting Started guide do not need any additional changes.

**Comment by scottyaslan** [comment]
Thanks @andrewmlim this has been merged to master.

**Pull request closed without merging**
