### PR TITLE
NIFI-5154: When Processor or Controller Service is added to a Process…

### PR DESCRIPTION
**Pull request by markap14**
… Group, remove any references from it to any other Controller Service that is not reachable from the newly assigned Process Group

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by mcgilman** [comment]
Will review...

**Comment by mcgilman** [comment]
Thanks for the PR @markap14! I ran into an issue with the proposed solution. Steps to replicate:

- Create a PG
- Add a Processor (InvokeHTTP) to the PG.
- Add a CS (SSLContextService) to the PG.
- Reference the CS in the Processor.
- Copy the Processor out of the PG.
- Processor CS reference is no longer valid and it's no longer a referencing component of the CS. Yay!
- Create another PG at the same level as the in Step 1.
- Move the copied Processor into the new PG.
- Move the new PG inside the PG created in Step 1.
- Copied Processor CS reference is valid again. Yay!
- However, it does not appear as a referencing component of the CS :/

**Comment by markap14** [comment]
@mcgilman that's a great catch! I did try a scenario similar to what you outline, but in my scenario I moved that processor back into the original PG directly - not with the extra Process Group in between. I will make the necessary updates and push another commit. Thanks for reviewing!

**Comment by markap14** [comment]
@mcgilman I have pushed another commit, which I believe addresses the issue that you raised. I also found that if we have Group A that has a processor and that processor referenced a controller service in the same group, we didn't allow the user to move the processor outside of Group A. However, if the processor lived within Group B and Group B lived within Group A (i.e., GroupA is the outer group, which has child Group B, and child group has a Processor) then we did actually allow the entire Group B to be moved outside of A. I updated the verifyMove() logic to also prevent this, since we don't allow the processor to be moved out directly.

**Comment by mcgilman** [comment]
Thanks @markap14! This has been merged to master.

**Pull request closed without merging**
