### PR TITLE
NIFI-1333 fixed FlowController shutdown deadlock

### PR DESCRIPTION
**Pull request by olegz**
The relevant test is available here: https://github.com/olegz/nifi/blob/int-test/nifi-integration-tests/src/test/java/org/apache/nifi/test/flowcontroll/FlowControllerTests.java#L50 

Unfortunately this is one of those multi-module situations.

### CODE REVIEW

**Comment by trkurc** [comment]
Adding some comments on the ticket

**Comment by joewitt** [comment]
Mark Payne commented on NIFI-1333 ticket.  In short the write lock does appear no longer necessary but a readLock still is.

**Comment by olegz** [comment]
@markap14 @joewitt Guys, please review. As agreed I've put read lock back in.

**Comment by joewitt** [comment]
thanks oleg.  i won't be able to help today most likely . Hopefully payne-monster or someone else can.

**Comment by trkurc** [comment]
@olegz  - I'll dig my old notes out and try to verify that a read-lock won't continue to cause a deadlock. I will likely have some time later this evening.

**Comment by trkurc** [comment]
I think it may still deadlock. I scripted a startup and shutdown over and over again for a few days, and it still was hanging on occasion. I should have added a jstack..

**Comment by olegz** [comment]
I am not surprised, that's why I was against having a lock in a shutdown in the first place. It doesn't bring any value since If you follow the logic of shutting down executors we are shutting them down cold anyway if they have not shut down in timely fashion.

**Comment by olegz** [comment]
@trkurc @joewitt @markap14  Ok, I was not able to reproduce the deadlock with _readLock_, that said I am voting for removal of any lock from stop routine to avoid further confusion and potential to a misleading message to be interpreted by a user, especially since we will still bring NiFi to a halt - no matter what.

**Comment by trkurc** [comment]
@olegz - I am still working through the locking on paper. I gave up on getting stack traces. We have a week or so before 0.5.0, if I don't make progress I think we go with deadlock. I am beginning to think you're right about it not being necessary.

**Comment by trkurc** [comment]
That 'deadlock' above should be readlock

**Comment by olegz** [comment]
So it appears that all who reviewed are in the agreement, so it could be merged as it stands now.

**Comment by mcgilman** [comment]
Would just like to confirm with @trkurc before merging in. Sounds like he may have been still working through some of the details. If he's content I'm happy to merge this in.

**Comment by trkurc** [comment]
Still working it - I'll be done tonight. I can take care of the merge.

**Comment by mcgilman** [comment]
Sounds good. Thanks!

**Comment by mcgilman** [comment]
With the github outage last night, ended up merging today. Thanks @trkurc and @olegz !!!

**Pull request closed without merging**
