### PR TITLE
NIFI-3737 - Ran optipng on all png files

### PR DESCRIPTION
**Pull request by brosander**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [X] - N/A - Have you written or updated unit tests to verify your changes?
- [X] - N/A - If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [X] - N/A - If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [X] - N/A - If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [X] - N/A - If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [X] - N/A - Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by scottyaslan** [comment]
Reviewing...

**Comment by andrewmlim** [comment]
I did a quick check of the optimized images and the majority of images look great (no perceptible image degradation to my naked eye).  However, for some reason the PNGs that have a transparent background (bcrypt-salt.png, for example) are having issues.  They render fine in my browser, but get cut-off at the bottom in Preview and a screenshot capturing tool that I use (SnagIt) on my Mac.  Maybe exclude images with transparent backgrounds for now.

**Comment by trixpan** [comment]
@andrewmlim :+1: :+1: :+1: :+1: for catching this...

**Comment by andrewmlim** [comment]
I believe these are the images to exclude:

nifi-legacy-salt.png
openssl-salt.png
bcrypt-salt.png
scrypt-salt.png
pbkdf2-salt.png

**Comment by brosander** [comment]
@andrewmlim those images work fine for me on OSx Sierra (10.12.4) and on Ubuntu Linux.  I asked @mattyb149 to try them and he said they worked for him on Sierra and not El Capitan.

I think we may have found an already resolved bug in the OSx png rendering functionality.  Still backed images out so that we don't cause confusion or problems for El Capitan users.

**Comment by andrewmlim** [comment]
Thanks @brosander.  Confirming that I am on El Capitan.

**Comment by scottyaslan** [comment]
@brosander @andrewmlim I was running OSx version 10.11.6 and was able to see the error in these images. I then updated my OSx to version 10.12 and I can confirm that the pngs are now properly displayed.

screen shot 2017-04-25 at 12 21 21 pm

**Comment by scottyaslan** [comment]
@brosander Thanks this has been merged to master!

**Comment by alopresto** [comment]
This has already been merged but the common thread with the affected images is that I am responsible for all of them. Can confirm I took them on Mac OS X 10.11.6.

**Pull request closed without merging**
