### PR TITLE
NIFI-3382 New test keystore, truststore

### PR DESCRIPTION
**Pull request by jvwing**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

---
I generated new keystore `localhost-ks.jks` and truststore `localhost-ts.jks` to match the previous ones through the following incantation:

```
keytool -genkeypair -alias localhost -keyalg RSA -storepass localtest -keypass localtest -keystore localhost-ks.jks -dname "CN=localhost, OU=Apache NiFi, O=Apache, L=Santa Monica, ST=CA, C=US" -startdate "2017/01/05" -validity 10000 -noprompt
keytool -genkeypair -alias mykey -keyalg DSA -storepass localtest -keypass localtest -keystore localhost-ks.jks -dname "CN=localhost, OU=Testing, O=Research, L=Metropolis, ST=New York, C=US" -startdate "2017/01/05" -validity 10000 -noprompt

keytool -exportcert -rfc -alias localhost -keystore localhost-ks.jks -storepass localtest -file localhost_cert.pem
keytool -importcert -v -trustcacerts -alias localhost -file localhost_cert.pem -keystore localhost-ts.jks -storepass localtest -noprompt

keytool -exportcert -rfc -alias mykey -keystore localhost-ks.jks -storepass localtest -file mykey_cert.pem
keytool -importcert -v -trustcacerts -alias mykey -file mykey_cert.pem -keystore localhost-ts.jks -storepass localtest -noprompt
```

They seem to make the 0.x unit tests and master integration tests happy.

### CODE REVIEW

**Comment by mcgilman** [comment]
Hey @jvwing. I actually updated these in a separate PR that's been awaiting review for awhile now. Specifically, they were regenerated in #1399.

**Comment by jvwing** [comment]
I'm sorry I didn't find that earlier, @mcgilman.  I would still like to fix this for the 0.x branch.  I'll close this PR and open a new PR that is focused only on the certs for 0.x.

**Comment by jvwing** [comment]
The proposed 0.x change is in PR #1439.

**Comment by mcgilman** [comment]
No worries. Sounds like a plan. I could have opened a new JIRA but decided to just address in that PR since I was updating the integration tests. Thanks for opening the 0.x PR!

**Pull request closed without merging**
