### PR TITLE
NIFI-12229 Refine NiFiRegistry client lifecycle: replacing actual client when SSL service changes

### PR DESCRIPTION
**Pull request by simonbence**
# Summary

[NIFI-12229](https://issues.apache.org/jira/browse/NIFI-12229)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [x] Build completed using `mvn clean install -P contrib-check`
  - [x] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by pvillard31** [comment]
I feel like the reported problem could happen in any implementation of the Registry Client, not just this one. Instead of taking this approach that is quite specific to the SSL controller service, should we consider adding something at the framework level to trigger a "refresh" method anytime the configuration of the component is changed? It would then be up to the component to implement whatever makes sense in this refresh method. Thoughts?

Note: I'm fine with this approach to solve the immediate problem but I feel like we could have a more generic approach in case there are some other implementations of the Registry Client interface.

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for working on this issue @simonbence, and thanks for the perspective @pvillard31.

I am concerned about this approach because it seems to be attempting to solve a framework-level concern at the component level.

Some of this appears to be the result of introducing the Flow Registry Client as a component without having a lifecycle for the component, such as enabling and disabling of Controller Services. This is apparent from the fallback to the System SSL Context, which would have similar concerns if selected as the configuration approach.

Instead of this approach, it seems like the Flow Registry Client should be reinitialized when a referencing Controller Service is enabled. Although this approach would be more involved, it seems like something along this line is necessary.

**Comment by simonbence** [comment]
@pvillard31 @exceptionfactory  Thanks for the feedback!

As of this given case, the behaviour is specific to the way this particular implementation works. Other implementations, if they are caching some internal state depending on "controller service" property might have a similar challenge.

@exceptionfactory You are perfectly right, the Flow Registry Client currently has no such lifecycle states like active-deactivated, that is correct. At the time of changing the Client to a component, this was an intentional choice due to the number of questions would come with this behavioural change (and due to avoiding any break in the previous behaviour). The questions include: what should happen with the existing versioned flows when the registry is deactivated? It looks like a different case compared to the situation when the registry is unintenionally unreachable and might result some confusion. An other possibility you mention is to "hook on" some existing event like validation or as you mention, the (de)activation of the dependent Controller Services but I am not aware of any support in the framework for this.

What I propose to do is to move on with this fix (which in some cases can cause misbehaviour as it is now) and for a wider scope solution it would be beneficial to start a discussion about the level of support we aim for: I can easily imagine that an additional hookpoint might be useful for other components as well.

**Comment by markap14** [comment]
Yeah, I think it's better to solve this at the framework level as well. The approach I would recommend would probably be to update the Registry Client Node object so that when validation is performed, if it goes from INVALID to VALID, we call any method annotated with `@OnEnabled`. That way, if a Controller Service that it uses were to be disabled and re-enabled, it would call the `@OnEnabled` method and that, in turn, would be responsible for recreating the underlying client based on the new SSL Context configuration.

**Comment by simonbence** [comment]
As suggested I will raise a new PR with a framework level solution. I think, @markap14 's suggestion might be the best balance between feature richness and unnecessary complexity I will aim for that.

**Pull request closed without merging**
