### PR TITLE
NIFI-5070 Fix java.sql.SQLException: ERROR 1101 (XCL01): ResultSet is…

### PR DESCRIPTION
**Pull request by gardellajuanpablo**
… closed

Discovered on Phoenix Database by using QueryDatabaseTable processor. The fix consists
on applying Matt Burgess' suggestion:

"I think we'd need a try/catch around the next() only to see if the result set is closed,
and an inner try/catch around everything else, to catch other errors not related to
this behavior. "

The solution was verified against Phoenix DB. Also added unit tests to cover the
change.

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [x] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [x] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by gardellajuanpablo** [comment]
@zenfenan fixed checkstyle violations. Thanks

**Comment by patricker** [comment]
I like the unit tests, but what about moving your check?
If you created a `catch` block at the end of the existing `try` block in `convertToAvroStream` it would probably simplify the flow a lot. Keep the same `isClosed` check... maybe?

Also, this seems to specifically be for Phoenix. With the fix as is, I don't know if it's possible to tell the difference between a database going offline for maintenance mid resultset read and a Phoenix end of resulset closure.

Could we check the Exception Message for the specific Phoenix error code so we don't block visibility to legitimate early connection closure errors?

**Comment by gardellajuanpablo** [comment]
Hi @patricker,

Regarding:
"Also, this seems to specifically be for Phoenix. With the fix as is, I don't know if it's possible to tell the difference between a database going offline for maintenance mid resultset read and a Phoenix end of resulset closure."
I discovered by using Phoenix, but Phoenix follows the JDBC spec. As I implemented, if there is a DB error the original exception is propagated to the caller. Please refer to the change I've did, if I'm missing something, please let me know.

**Comment by patricker** [comment]
The database error only propagates if `isClosed` returns false; I was thinking that it might be possible to have a connection close before all results are read. The documentation isn't clear on this point, it just says isClosed will be true either when specifically closed, or if automatically closed... which basically leaves it open to any circumstance a driver might want to cover...

**Pull request closed without merging**
