### PR TITLE
NIFI-13529: Update the Calcite Connection properties to indicate that…

### PR DESCRIPTION
**Pull request by markap14**
… timezone is UTC timezone. We do this because we already take care to ensure that timestamps, etc. are normalized to UTC timezone before passing them in. We do not want the Avatica ResultSet then treating Timestamp objects as local timestamps. We want them treated as UTC timestamps.

# Summary

[NIFI-13529](https://issues.apache.org/jira/browse/NIFI-13529)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by Kapkiai** [comment]
+1
I have verified that the changes fixes bug. Thanks @markap14 for the quick fix!

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
I'm concerned about this type of change, we should not override local time zone settings as it could have other impacts when handling localized dates. We should consider other approaches rather than hard-coding UTC.

**Comment by exceptionfactory** [comment]
@markap14 Can you provide a reference to where we are already converting input timestamps to UTC?

**Comment by markap14** [comment]
Hey @exceptionfactory I suppose you're right, we are not necessarily converting to UTC before providing the object to Calcite. But what we really want is for Calcite not to mess with the Timestamp object we give it at all. When you call `ResultSet.getTimestamp(1)`, it should be returning the same object as if you call `Result.getObject(1)` but Avatica doesn't it see it that way. Instead, when you call `ResultSet.getTimestamp(1)` with Avatica it attempts to localize the Timestamp according to its configured TimeZone. If not specified, it uses the local timezone as that configured TimeZone. In essence what I'm doing with this PR is telling it to use UTC as the configured TImeZone so that it doesn't do any manipulation / localization.

So that's why I wrote the unit test as I did - when I give it a timestamp, and then get back a timezone, it should be:
(a) the same value that I gave to it, and
(b) the same result regardless of whether I call `ResultSet.getObject` vs. `ResultSet.getTimestamp`

**Review by exceptionfactory — APPROVED** [review]
Thanks for the explanation @markap14. Reviewing some of the Calcite code, I see places where it changes the returned timestamp, so setting the Calcite timeZone to UTC makes sense as the offset is `0`, avoiding any changes.

With that clarification, the tests are helpful, and this looks good! +1 merging

**Pull request closed without merging**
