### PR TITLE
NIFI-4632: Add the local hostname to the list of validated host headers

### PR DESCRIPTION
**Pull request by markap14**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by alopresto** [comment]
Thanks Mark. I’ll take a look and hopefully merge this in tonight.

**Comment by alopresto** [comment]
I built this and set up a local instance doing S2S without having to populate the `nifi.web.http.host` value. I got a weird error message briefly but I had put the wrong remote port in to the RPG configuration. With the correct values, everything worked normally. 

Error message for posterity/future recall:

`2017-11-27 19:01:38,897 ERROR [Site-to-Site Worker Thread-11] o.a.nifi.remote.SocketRemoteSiteListener Unable to communicate with remote instance null due to org.apache.nifi.remote.exception.HandshakeException: Handshake with nifi://localhost:56899 failed because the Magic Header was not present; closing connection`

Ran `contrib-check` and all tests pass. +1, merging.

**Comment by simnotes** [comment]
I ran into an issue with this change:
I built this into a pod on kubernetes and configured a load-balancer-service as a proxy in kubernetes. Got the error-message: 

System Error
The request contained an invalid host header [<service-proxy-url>:8080] in the request [/nifi]. Check for request manipulation or third-party intercept.

**Comment by elgalu** [comment]
@simnotes how are you deploying to K8s? did you use https://github.com/AlexsJones/kubernetes-nifi-cluster ?

**Pull request closed without merging**
