### PR TITLE
NIFI-12212: Upgrading DynamoDB processors to AWS SDK 2.x

### PR DESCRIPTION
**Pull request by gresockj**
# Summary

[NIFI-12212](https://issues.apache.org/jira/browse/NIFI-12212)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — COMMENTED** [review]
Thanks for working on this SDK upgrade @gresockj! Can you rebase on the current main branch? Changes for [NIFI-12220](https://issues.apache.org/jira/browse/NIFI-12220) impacted a number of the integration tests.

**Review by emiliosetiadarma — APPROVED** [review]
Changes look good to me and I was able to spin up a simple flow to get, put (both using and not using the records) and delete stuff from DynamoDB.

**Comment by emiliosetiadarma** [comment]
I would think so, I don't have write access to this repository so I can't merge it, but it looks good to me

**Review by exceptionfactory — APPROVED** [review]
Thanks for the work on this upgrade @gresockj, and thank for the review and testing @emiliosetiadarma, these changes look good! +1 merging

**Pull request closed without merging**
