### PR TITLE
NIFI-9227 Run Once not working when scheduling strategy is CRON or Ev…

### PR DESCRIPTION
**Pull request by s9514171**
…ent driven

#### Description of PR

[https://issues.apache.org/jira/browse/NIFI-9227](https://issues.apache.org/jira/browse/NIFI-9227)

This PR fix the thread hang after run once in CRON scheduling strategy

~and support run once when processor is set in Event Driven~

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [X] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [X] Have you written or updated unit tests to verify your changes?
- [X] Have you verified that the full build is successful on JDK 8?
- [X] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by cemremengu** [comment]
I am also seeing this behaviour and it is kind of an annoying bug actually. 

Anything we can do to push this PR through?

**Comment by markap14** [comment]
Thanks for adding this @s9514171! I tested it out, and I can verify that CRON driven did in fact remain in a bad state originally and after this PR it does not, so that part works well.

I also tested it with event-driven, though, and it did not work. I created a flow: GenerateFlowFile (CRON driven) -> UpdateAttribute (EventDriven) -> UpdateAttribute.
Run Once on GenerateFlowFile produced the desired FlowFile. Run Once on the event-driven UpdateAttribute did NOT process the FlowFile. It just left it in the queue. It also left the processor in a state of "RUN_ONCE" which means that I could not start it, edit it, delete it, or run it again.

To be honest, my recommendation would be to revert the changes to the EventDrivenSchedulingStrategy completely and leave it as an unsupported operation. Event Driven was an experiment that we tried, in order to reduce CPU utilization that we had with Timer-Driven processors and provide potentially even better latency. However, once we introduced the "Bored Yield Duration" to timer-driven processors, we no longer had an issue with high CPU utilization, and the expense of event-driven ended up being more expensive than Timer-Driven. We've since found a few issues with Event-Driven scheduling strategy that have not been addressed, simply because we marked the feature as Experimental and we expect to remove it entirely (or otherwise completely rewrite it) in the next major version (2.0). Because of this, nobody should ever use the Event-Driven scheduling strategy, right now, and that's why we didn't implement the Run Once capability there to begin with. But the original behavior, of immediately failing, is preferable over this behavior of simply not doing anything and leaving the processor in a bad state.

**Comment by cemremengu** [comment]
@s9514171 if you don't have time to work on this I can make the required changes. Please let me know.

**Comment by s9514171** [comment]
@markap14 Thanks for your suggestion. I'll revert the change of EventDrivenSchedulingStrategy

@cemremengu I'm taking on it

**Comment by s9514171** [comment]
@markap14 I force-push a version only fix the CRON driven issue

and also create a patch for event-driven, including the issue you mentions upper and integration testing
[NIFI-9227-fix-event-driven.patch.txt](https://github.com/apache/nifi/files/8109254/NIFI-9227-fix-event-driven.patch.txt)

**Comment by markap14** [comment]
Thanks @s9514171 the changes look good to me. Will merge to main.

**Pull request merged**
