### PR TITLE
NIFI-13430 for support/nifi-1.x

### PR DESCRIPTION
**Pull request by MikeThomsen**
# Summary

[NIFI-00000](https://issues.apache.org/jira/browse/NIFI-00000)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by MikeThomsen** [comment]
@exceptionfactory Updated for the 1.x support branch.

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
@MikeThomsen The Java 8 builds are failing due to syntax issues, particularly the use of `List.of()` and `Set.of()`, so changing those to the older style with `Collections.unmodifiable...` and a concrete type will be required for backporting.

**Comment by MikeThomsen** [comment]
@exceptionfactory addressed and builds are starting.

**Review by exceptionfactory — APPROVED** [review]
Thanks for making the correction @MikeThomsen, looks good! +1 merging

**Comment by exceptionfactory** [comment]
Merged in https://github.com/apache/nifi/commit/a044af8d6cb64f53d4ee851a8c7bffe73e3eaf0b

**Pull request closed without merging**
