### PR TITLE
NIFI-9816: Implementing a way of dynamically setting the 'lang' attribute…

### PR DESCRIPTION
**Pull request by jocovo**
… on each html tag (where possible) to meet WCAG 2.1 Accessibility standards.

Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

These changes provide a dynamic way of ensuring every <html> tag has a "lang" attribute with a [valid BCP 47 language](https://www.w3.org/International/questions/qa-choosing-language-tags#question) value, which is used by accessibility devices like screen readers to correctly pronounce on-screen text. This also meets success criteria for [accessibility standards in WCAG 2.1](https://www.w3.org/WAI/WCAG21/Techniques/html/H57). Resolves ticket NIFI-9816.

Testing the changes in this PR requires manual inspection of the <html> elements on the affected pages, noting that the changes in the nifi-web-api package are verified by inspecting the contents of the Documentation view's iframe.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [X] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [X] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Review by exceptionfactory — COMMENTED** [review]
Thanks for the contribution @jocovo! In light of the fact that NiFi does not currently support internalized representations of the UI, it seems like the best approach for now is to hard-code `en` in the `lang` attribute on the `html` tag. Injecting a value from the request directly into the document could also introduce security concerns.

What do you think about hard-coding a value for now as a starting point?

**Comment by jocovo** [comment]
I _had_ been wondering if I was over-engineering this solution given the current lack of localization. Hard-coding "en" would accurately represent the site's contents as it stands now, so I think that's a good idea. Will make the changes and push them.

**Comment by exceptionfactory** [comment]
> Will make the changes and push them.

Sounds good, thanks!

**Comment by jocovo** [comment]
@exceptionfactory I just pushed some changes I missed the first time around. Can you please re-approve the workflow process?

**Comment by jocovo** [comment]
@exceptionfactory Thanks for re-running the workflow. It appears one of the checks wasn't successful due to an error that definitely doesn't look like something my changes would have caused:
- HikariCPConnectionPoolTest.testGetConnection:152 » Process Connection retrieva...
- HikariCPConnectionPoolTest.testCreateInsertSelect:172 » Process Connection ret...


Could you please re-kick that workflow for me?

**Comment by jocovo** [comment]
@exceptionfactory Everything looks good on my end. Do you approve?

**Review by exceptionfactory — APPROVED** [review]
Thanks for the updates @jocovo, this looks good. Verified lang attribute at runtime across several pages. +1 merging.

**Pull request closed without merging**
