### PR TITLE
NIFI 945:  New property (wrap as array) in avro2json converter

### PR DESCRIPTION
**Pull request by joemeszaros**
Create a new property (wrap as array) in ConvertAvroToJson, which determines how stream of records is exposed: either as a sequence of single Objects (false), writing every Object to a new line, or as an array of Objects. Default value is true, meaning that the Avro content is exposed as an array of Object entries. False value is useful, when you want to write your records as single instances to a target component (e.g. Kafka).

Let's assume you have an Avro content as stream of tracking events ```({"id":"user1", "item":"itemX", "action": "buy"}, {"id":"user2", "item":"itemY", "action": "like"})...{"id":"userN", ...})```. 

If wrap as array is false, the converter will expose the records as sequence of single JSON objects:
```
{"id":"user1", "item":"itemX", "action": "buy"}
{"id":"user2", "item":"itemY", "action": "like"}
...
{"id":"userN", ...}
```
Please bear in mind, that the final output is not a valid JSON content. You can then forward this content e.g. to Kafka, where every record will be a single Kafka message.

If wrap as array is true, the output looks like this:
```
[{"id":"user1", "item":"itemX", "action": "buy"},{"id":"user2", "item":"itemY", "action": "like"},...,{"id":"userN", ...}]
```
It is useful when you want to convert your Avro content to a valid JSON array.

### CODE REVIEW

**Comment by trkurc** [comment]
I'm having a heck of a time getting this to merge clean due to whitespace issues (^M newlines)

**Comment by trkurc** [comment]
I commented on https://issues.apache.org/jira/browse/NIFI-945 - looks good, modulo some minor tweaks

**Comment by trkurc** [comment]
@joemeszaros - I amended your changes to get it to merge clean and for some consistency with other processors in that thread (see commit d1acd152). I just noticed a the getBytes on 140 needs a charset though. Hoping you can look it over and confirm the amendments are representative of your intent?

**Comment by joemeszaros** [comment]
I can confirm the amendments, please find my inline comments at the referenced commit.

**Comment by joemeszaros** [comment]
Thanks for your help!

**Pull request closed without merging**
