### PR TITLE
NIFI-4279 PutDatabaseRecord and ConvertJSONToSQL stream has already b…

### PR DESCRIPTION
**Pull request by patricker**
…een closed error on Oracle

Make sure to read the Jira, and this article, https://blog.jooq.org/2015/12/30/oracle-long-and-long-raw-causing-stream-has-already-been-closed-exception/, before reviewing :)

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by lfrancke** [comment]
I did read the JIRA and referenced article. I also found https://jira.apache.org/jira/browse/DDLUTILS-29 which fixes the same issue in another project.

The only comment I have about the patch itself is that it'd be great to add a link to the comment (for example to either the blog post or the NIFI-4279 issue itself.

**Comment by patricker** [comment]
@lfrancke I considered adding a link to the article or ticket, but it's not something that I see done frequently in NiFi; if you feel it makes sense to do so in this scenario I gladly will.

Thanks for the additional research, good to see other people resolved the same issue 13 years ago in another project :)

**Comment by mattyb149** [comment]
Reviewing... (I think since the link is in the Jira already that should be fine)

**Comment by mattyb149** [comment]
+1 LGTM, reproduced the issue before this fix, and verified the correct behavior is implemented. Sorry you had to do this lol, but very thankful for the fix! Merging to master

**Comment by lfrancke** [comment]
@mattyb149 I'd still argue that adding a hint to the JIRA would be a good thing. Now there's no context at all. What is the bug you're referring to?

Sure, I can dig in the history but all it takes is a "see NIFI-4279", shall I open a new issue for that?

**Pull request closed without merging**
