### PR TITLE
NIFI-1777 Prevent deleting a connection going to a running processor

### PR DESCRIPTION
**Pull request by pvillard31**

### CODE REVIEW

**Comment by olegz** [comment]
@pvillard31 I know this is a simple one, but would you consider adding a simple unit test for it as well?

**Comment by pvillard31** [comment]
@olegz You're right, just added a unit test. (Note: I believe that travis build failure is not related to this PR)

**Comment by olegz** [comment]
Perfect, reviewing now

**Comment by olegz** [comment]
@pvillard31 also, when you submit PR click on "Submit Patch" in JIRA (without writing anything in description). I know it may be a bit awkward but this is how we signal that JIRA is ready for review/resolution.

**Comment by olegz** [comment]
Was able to validate that when/if someone attempts to delete a connected processor a window pops up with the error message "Destination of Connection (LogAttribute[id=7a37a5bb-1017-4732-8c31-a6c1f44eea18]) is running". So all good, adequate tests provided, +1.

@mcgilman @scottyaslan  perhaps in the future we can further address it (as an additional feature) in the UI and disable "Delete" option all together.

**Pull request closed without merging**
