### PR TITLE
NIFI-7920: When node that is connected to cluster is asked to reconne…

### PR DESCRIPTION
**Pull request by markap14**
…ct, ensure that it relinquishes role of Cluster Coordinator and Primary Node

Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Enables X functionality; fixes bug NIFI-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [ ] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by exceptionfactory** [comment]
This seems like an important correction, how feasible is it to unit test the solution?

**Review by tpalfy — COMMENTED** [review]
Tested manually.
LGTM+1

**Comment by markap14** [comment]
Thanks for reviewing @tpalfy and @exceptionfactory.
@exceptionfactory I don't think we can really unit test this. I mean, we could write a test that verifies that if connected to a cluster, that `controller.onClusterDisconnect()` gets called. But it's pretty clear that it does given the code snippet:
```
if (controller.isConnected()) {
  controller.onClusterDisconnect();
}
```
I don't think an integration test would really be any more help. A system-level test could potentially be written. I may consider that as a follow-on. But given that it's easy to verify the fix manually and @tpalfy and I have, I don't think it's worth holding up the PR for that.

**Comment by markap14** [comment]
Merging based on @tpalfy +1

**Comment by markap14** [comment]
To provide a clearer explanation of what this change is doing (since looking at the code change doesn't make it clear that anything related to component revisions changed)...

When a node is disconnected from the cluster because it fails to make an update, it will immediately attempt to reconnect. If that reconnection is successful, then the node can remain part of the cluster. This is done because there are some changes that can happen that our fingerprinting logic says is okay. For example, if the position of a component moves, or if a component is stopped. Upon cluster reconnect, the joining node will simply update that component to match the cluster. For other changes, such as a processor property change, fingerprinting logic will prevent the node from joining, and the node will then transition to a DISCONNECTED state.

When that change initially happens, because the node will immediately attempt to connect to the cluster again, it transitions from CONNECTED to CONNECTING (not DISCONNECTED). As a result, it does not relinquish any roles that it holds as Primary Node / Cluster Coordinator. This results in an issue where the Cluster Coordinator may fail to update a component and as such has an old Revision number and then attempts to connect to the Cluster. The node is allowed to join and downloads the list of Component Revisions from the Cluster Coordinator. BUT, in this situation, the Cluster Coordinator is the node with the outdated Component Revisions, so it never gets the list that the rest of the cluster has.

This fix addresses the issue by making the node relinquish any roles that it holds (Cluster Coordinator, Primary Node) so that another node will pick up the roles. This causes the old Cluster Coordinator to then get the list of Component Revisions from a newly elected Cluster Coordinator, so that the revisions are up to date.

**Pull request merged**
