### PR TITLE
NIFI-2652 [WIP] Handle encrypted config key migration

### PR DESCRIPTION
**Pull request by alopresto**
Submitting a WIP PR because other features depend on this work. There is an unrelated test failure that I got locally after rebasing against master, so I will investigate that, but the module where I did all of this work is fine. 

I will also update the Admin Guide with instructions for key migration and squash these commits.  

---
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by YolandaMDavis** [comment]
@alopresto happy to review (understanding this is WIP)

**Comment by YolandaMDavis** [comment]
@alopresto I also received problems running unit test but confirmed that I could migrate keys using several scenarios:

raw key -> raw key
password -> password
password -> raw key
raw key -> password

Also  tried negative conditions including incorrect old password/rawkey and received expected exception.  

Once unit test issue is resolved I can reevaluate for merge. Thanks @alopresto!

**Comment by YolandaMDavis** [comment]
@alopresto just to add clarity on unit test failures, I am specifically receiving a problem when running the ConfigEncryptionToolTest. Several tests are failing for me and the failure appears to be due to a generated key that looks truncated.

**Comment by alopresto** [comment]
@YolandaMDavis made a good catch; the tests are ambivalent in regards to JCE jurisdiction policy, but some of the test resources I generated relied on 256-bit keys and so were not compatible with an environment that did not have the policies installed. I am provided resources with 128-bit keys to allow them to run on any environment.

**Comment by alopresto** [comment]
@YolandaMDavis I believe I have resolved the issue you were encountering, and the unrelated test failure was due to DNS settings on my machine which I have now fixed. Please perform the review. Thank you.

**Comment by YolandaMDavis** [comment]
@alopresto re-ran the unit tests and scenarios looks good

+1

**Pull request closed without merging**
