### PR TITLE
NIFI-10570 Upgrade SnakeYaml to 1.33

### PR DESCRIPTION
**Pull request by UcanInfosec**
# Summary

[NIFI-10570](https://issues.apache.org/jira/browse/NIFI-10570) Upgrade SnakeYaml to 1.33

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI-10570) issue created

### Pull Request Tracking

- [X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X] Pull Request based on current revision of the `main` branch
- [X] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [X] JDK 8
  - [X] JDK 11
  - [X] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by MikeThomsen — CHANGES_REQUESTED** [review]
As previously requested, we need a better git commit message that describes what the purpose of the patch is. Ex:

`NIFI-10570 Upgrade SnakeYaml to 1.33`

**Comment by UcanInfosec** [comment]
@MikeThomsen change made.

**Comment by MikeThomsen** [comment]
Did you forget to push the updated changes?

Screen Shot 2022-10-01 at 10 07 22 AM

**Comment by UcanInfosec** [comment]
> Did you forget to push the updated changes?
> 
> Screen Shot 2022-10-01 at 10 07 22 AM

Just done. Apologies for the delay

**Comment by MikeThomsen** [comment]
@UcanInfosec You're going to need to back out that last change, as it renamed the file rather than changing the commit message.

**Comment by UcanInfosec** [comment]
@MikeThomsen What I'll do is just delete this pull and create a new one that is better aligned

**Pull request closed without merging**
