### PR TITLE
NIFI-10718 Update mongo.driver.version to 4.7.2

### PR DESCRIPTION
**Pull request by UcanInfosec**
# Summary

[NIFI-10718](https://issues.apache.org/jira/browse/NIFI-10718)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI-10718) issue created

### Pull Request Tracking

- [X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X] Pull Request based on current revision of the `main` branch
- [X] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [X] JDK 8
  - [X] JDK 11
  - [X] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by MikeThomsen** [comment]
@UcanInfosec for the kind of updates you do, there's nothing wrong with you pushing a PR that has multiple Jira tickets in it to save time on creating and reviewing the PR.

**Comment by UcanInfosec** [comment]
@MikeThomsen thanks, much appreciated. Will look into that. But dont want to complicate things and make things harder for everyone.

**Comment by exceptionfactory** [comment]
@MikeThomsen Just a note, although it creates more tickets, it is helpful to keep the updates focused on a single dependency, or directly related group of dependencies. Updating different types can create confusion and make it more difficult to review. It is a case-by-case question, but in general, I think it is better to keep the updates limited for easier review and tracking.

**Comment by UcanInfosec** [comment]
When I ran the actions locally, the pull request ran successfully. The JDK11 failure might need to be run again

**Comment by MikeThomsen** [comment]
@exceptionfactory 

> Just a note, although it creates more tickets

To be clear, I said @UcanInfosec can push multiple Jira tickets in the same PR. When doing these bulk updates of dependencies, it would make more sense for @UcanInfosec/@mr1716 to do a big PR that has multiple commits, one for each Jira ticket.

**Comment by exceptionfactory** [comment]
Thanks for clarifying @MikeThomsen, that makes sense. Depending on the scope of the changes, we still should be careful in terms of how many changes to include in a single PR, but I agree that some updates could be grouped together.

**Comment by UcanInfosec** [comment]
@MikeThomsen @exceptionfactory Thanks. Will do. After this is merged, I will ramp it down for PR requests and commits going forward for a while.

**Pull request closed without merging**
