### PR TITLE
NIFI-1121: Support making properties dependent upon one another

### PR DESCRIPTION
**Pull request by markap14**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Enables X functionality; fixes bug NIFI-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [ ] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by bbende** [comment]
This is an awesome feature! I'm loving the simplification of the record reader properties :)

I came across one issue while testing this which looks like a UI issue. I took the test processor from this PR that is named `DependsOnProperties` and I put it in a NAR and deployed it to my NiFi. I added an instance of it to the canvas and it was correctly invalid, but when I tried to open the configuration to change the properties I got this error in the browser console:

```
jquery.propertytable.js?1.13.0-SNAPSHOT:1 Uncaught TypeError: Cannot read property 'includes' of undefined
    at Object.<anonymous> (jquery.propertytable.js?1.13.0-SNAPSHOT:1)
    at Function.each (jquery.min.js:2)
    at Function.b.each (jquery.each.js:1)
    at Object.<anonymous> (jquery.propertytable.js?1.13.0-SNAPSHOT:1)
    at Function.each (jquery.min.js:2)
    at Function.b.each (jquery.each.js:1)
    at jquery.propertytable.js?1.13.0-SNAPSHOT:1
    at Function.each (jquery.min.js:2)
    at Function.b.each (jquery.each.js:1)
    at D (jquery.propertytable.js?1.13.0-SNAPSHOT:1)
    at HTMLDivElement.<anonymous> (jquery.propertytable.js?1.13.0-SNAPSHOT:1)
    at Function.each (jquery.min.js:2)
    at Function.b.each (jquery.each.js:1)
    at S.fn.init.each (jquery.min.js:2)
    at S.fn.init.loadProperties (jquery.propertytable.js?1.13.0-SNAPSHOT:1)
    at S.fn.init.t.fn.propertytable (jquery.propertytable.js?1.13.0-SNAPSHOT:1)
    at Array.<anonymous> (nf-canvas-all.js?1.13.0-SNAPSHOT:25)
    at c (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Object.<anonymous> (jquery.min.js:2)
    at c (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at l (jquery.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2)
```

**Comment by mtien-apache** [comment]
@bbende Thanks for checking it out. Will look into this.

**Comment by mtien-apache** [comment]
I fixed the error and submitted a patch to markap14. I added another check for dependent values. Thank you. @bbende

**Comment by markap14** [comment]
@bbende I rebased the branch against `main` and included the patch from @mtien-apache . Can you check it again? Thanks!

**Comment by bbende** [comment]
Thanks, latest updates look good. I noticed one minor issue with the dependency setup for the "Schema Branch" and "Schema Version" properties, the PR has them set to depend on the two HWX strategies, but really they go with the "Schema Name" strategy. I'm going to include a small commit that corrects that, the diff looks like this...


```+++ b/nifi-nar-bundles/nifi-extension-utils/nifi-record-utils/nifi-avro-record-utils/src/main/java/org/apache/nifi/schema/access/SchemaAccessUtils.java
@@ -88,7 +88,7 @@ public class SchemaAccessUtils {
                     "If the chosen Schema Registry does not support branching, this value will be ignored.")
             .addValidator(StandardValidators.NON_EMPTY_VALIDATOR)
             .expressionLanguageSupported(ExpressionLanguageScope.FLOWFILE_ATTRIBUTES)
-            .dependsOn(SCHEMA_ACCESS_STRATEGY, HWX_SCHEMA_REF_ATTRIBUTES, HWX_CONTENT_ENCODED_SCHEMA)
+            .dependsOn(SCHEMA_ACCESS_STRATEGY, SCHEMA_NAME_PROPERTY)
             .required(false)
             .build();

@@ -99,7 +99,7 @@ public class SchemaAccessUtils {
                     "If not specified then the latest version of the schema will be retrieved.")
             .addValidator(StandardValidators.POSITIVE_INTEGER_VALIDATOR)
             .expressionLanguageSupported(ExpressionLanguageScope.FLOWFILE_ATTRIBUTES)
-            .dependsOn(SCHEMA_ACCESS_STRATEGY, HWX_SCHEMA_REF_ATTRIBUTES, HWX_CONTENT_ENCODED_SCHEMA)
+            .dependsOn(SCHEMA_ACCESS_STRATEGY, SCHEMA_NAME_PROPERTY)
             .required(false)
             .build();

**Pull request closed without merging**
