### PR TITLE
NIFI-10645: Add cloud profiles for Iceberg processors

### PR DESCRIPTION
**Pull request by mark-bathori**
# Summary

[NIFI-10645](https://issues.apache.org/jira/browse/NIFI-10645)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 8
  - [ ] JDK 11
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by bbende** [comment]
For consistency with other components that have these profiles, we should probably add `include-hadoop-cloud-storage` and `include-hadoop-ozone`.

**Comment by mark-bathori** [comment]
Thanks @bbende for the review, I tested the PutIceberg processor with Ozone and added the two missing profiles.

**Comment by bbende** [comment]
I just noticed one more thing, the profiles are currently added to the `nifi-iceberg-services-api` pom, but should they be added to the `nifi-iceberg-services-nar` pom since we want the extra jars to end up with the implementations? or do we really want them in the API?

**Comment by mark-bathori** [comment]
Yes you are right, I've checked other processors that contains these profiles and they also include them in their nar module. I also moved them to `nifi-iceberg-services-nar` in my last commit.

**Review by turcsanyip — APPROVED** [review]
@bbende Thanks for your review comments!

+1 LGTM
Merging to main.

**Pull request closed without merging**
