### PR TITLE
NIFI-13650: Fixing condition when including References Parameter... o…

### PR DESCRIPTION
**Pull request by mcgilman**
…ption.

- Removing supportsParameter input in favor of using existing parameterContext input.
- Fixing minor layout issue in Processor schedule tab.
- Fix combo editor unit tests.

# Summary

[NIFI-00000](https://issues.apache.org/jira/browse/NIFI-00000)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by rfellows** [comment]
reviewing...

**Review by rfellows — CHANGES_REQUESTED** [review]
There is a regression with these changes. If there is no mapped parameter context and you edit a property of a component, it indicates that parameters are not supported. This isn't technically correct as parameters are supported, there just aren't any available due to no parameter context.

Screenshot 2024-08-15 at 10 16 13 AM

This can be confusing as the same component property in 2 different process groups could indicate it does support params in one and does not in the other.


I can see some possible solutions. Go back to determining if parameters are supported by a separate flag or updating the logic to understand this distinction.

_A nice addition could be to alter the `PARAM` indicator to a caution icon when parameters are supported but no parameter context is available. But definitely not required_

**Review by rfellows — APPROVED** [review]
Changes look good now. Thanks, @mcgilman.

**Review by scottyaslan — COMMENTED** [review]
LGTM

**Pull request merged**
