### PR TITLE
NIFI-13513 remove ListenSMTP

### PR DESCRIPTION
**Pull request by joewitt**
# Summary

[NIFI-13513](https://issues.apache.org/jira/browse/NIFI-13513)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
The removal of `ListenSMTP` looks good, but the dependency on `subethasmtp` should be removed.

**Comment by mattyb149** [comment]
Is this because the libraries are vulnerable and/or not up to date?

**Comment by exceptionfactory** [comment]
> Is this because the libraries are vulnerable and/or not up to date?

The `subethasmtp` library has gone through several iterations of forking, and the [most recent fork](https://github.com/davidmoten/subethasmtp) has had some helpful recent updates.

The Netty framework has some SMTP codec classes that could provide a better foundation, but I think the fundamental question relates to the use of ListenSMTP itself. The component description notes that it does not perform any email validation, which effectively requires an external SMTP server for runtime use. Running ListenSMTP with direct network exposure is very dangerous, so its current use cases are limited.

**Review by exceptionfactory — APPROVED** [review]
Thanks for the dependency removal update, +1 merging

**Pull request closed without merging**
