### PR TITLE
NIFI-3422 Run Once Scheduling

### PR DESCRIPTION
**Pull request by NazIrizarry**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by NazIrizarry** [comment]
The AppVeyor tests that fail seem related to the standard build and npm (which was not changed on the PR).  How do I get these to clear or does it matter?

**Comment by markap14** [comment]
@NazIrizarry Thanks for the contribution! I can certainly understand how this is a useful feature to have. The only concern that I have is that I don't believe that "Run Once" fits as a Scheduling Strategy. Instead, I think the user should have the ability to right-click on a Processor and click "Run Once" and the Processor would then immediately run, regardless of what the scheduling strategy is (though if configured to run on Primary Node only, it should still only run on Primary Node).

Thanks
-Mark

**Comment by markap14** [comment]
@NazIrizarry re: AppVeyor I think it has always failed. I believe there is some configuration that needs to be fixed. You don't have to worry about that for now.

**Comment by markap14** [comment]
Closing Pull Request, as it's nearly 4 years old and has no traction. I think there's another pull request for the same feature that is recent.

**Pull request closed without merging**
