### PR TITLE
NIFI-4675 Lifted restriction on demarcator and kafka.key usage together

### PR DESCRIPTION
**Pull request by jasper-k**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?
 YES, NIFI-4675

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [x] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [x] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by joewitt** [comment]
Given your description of the user understanding the decision they're making I think I agree with you.

@markap14  what do you think?

@jasper-k we'll want to make sure kafka 10, 11, and 1 are all updated for this but lets see what mark thinks too.

Thanks for contributing and sharing your findings

**Comment by joewitt** [comment]
@jasper-k the travis-ci builds show there are some contrib-check failures.  Make sure you run that locally so you can see them more easily.  "mvn clean install -Pcontrib-check"  Please rebase to latest master, resolve the contrib-check, and force push.

**Comment by jasper-k** [comment]
@joewitt It seems to be checkstyle errors, but there is no obvious error. Any tip to setup IntelliJ to use the <checkstyleRules> embedded in the pom.xml?

**Comment by markap14** [comment]
@jasper-k @joewitt I think I am ok with this change. I do tend to expect Kafka keys to be unique because otherwise Kafka may lose the data. However, I know there are use cases where some users want to use the same key anyway, so given the apt description in the property this is probably a good improvement. Will merge to master.

**Comment by markap14** [comment]
OK tested locally and all looks good. +1 merged to master. Thanks for contributing the improvement!

**Pull request closed without merging**
