### PR TITLE
NIFI-2305: Do not run processors that are marked as Primary Node Only…

### PR DESCRIPTION
**Pull request by markap14**
… if disconnected from cluster

### CODE REVIEW

**Comment by JPercivall** [comment]
Reviewing this and came across a state that I'm not if its intended or not.

ncm and 2 node cluster with a flow GenerateFF (primary node only) -> LogAttribute
set a break point on line 3809 of FlowController.java to cause the primary node to stop sending heartbeats
after 45 seconds of not receiving heartbeats the NCM disconnects the node from the cluster
at that time observe that the FFs are no longer getting logged (assume because the GenerateFF is no longer being scheduled)

Also I cannot access the UI of the node that is disconnected.

**Comment by JPercivall** [comment]
FYI, in order to track for 0.8 I created a separate Jira ticket for adding this 0.x and closed the 1.0 ticket. Please update the commit when you get a chance.

[1] https://issues.apache.org/jira/browse/NIFI-2433

**Comment by trixpan** [comment]
@markap14 @JPercivall 

Given we getting well into 1.2, should this PR still go ahead?

**Comment by joewitt** [comment]
@markap14 I think we should close this.  It is already fixed on the 1.x line.  Doing a stale PR sweep and this comes up.  Would like to close it out or push it across the finish line.

**Comment by JPercivall** [comment]
I'm in favor of closing it, sound good @markap14?

**Comment by markap14** [comment]
Sounds good to me. Done.

**Pull request closed without merging**
