### PR TITLE
NIFI-5960 add compatibility rating to RECORD schemas

### PR DESCRIPTION
**Pull request by SavtechSolutions**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [x] ~If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?~
- [x] ~If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?~
- [x] ~If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?~
- [x] ~If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?~

### For documentation related changes:
- [x] ~Have you ensured that format looks appropriate for the output in which it is rendered?~

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by joewitt** [comment]
I think it will be important, in the JIRA, to explain the plan/strategy for what a compatibility score would mean and how it would be calculated in general.  It is probably best to discuss if that score would be sufficiently meaningful or not before diving too far into the PR itself.  The idea is certainly interesting but we probably need to discuss what it means, how it is calculated, how it is used.

**Comment by SavtechSolutions** [comment]
I intended for JIRA to only describe the issue, not the solution (as I'd prefer not to steer anyone trying to solve that issue into a particular solution, there might be alternate approaches).

The issue at hand is that, when determining if a record is compatible with a given schema, we consider nullable fields to be compatible with null values. Generally, this makes sense, but not for union types. If one of the union choices is a record with only nullable fields, this choice suddenly becomes compatible with pretty much everything - like, you can feed it a record with completely unrelated field names, and it would still be considered compatible (see JIRA for an example).

This PR aims to address that issue by keeping track of how many non-nullable fields were found compatible, as a ratio to the total # of fields checked. The ratio goes from -1 (not compatible) to 100 (fully compatible). So the above example would still be considered "sorta-compatible", with a rating of 0, but the compatibility check would still continue, and if a schema choice with a higher rating is found (all it takes for that is one non-nullable field to be found compatible), that schema would be used instead.

**Comment by joewitt** [comment]
Ok I now think I understand what you are proposing.  The JIRA states the problem is that we can choose a suboptimal type in certain situations.  Your PR aims to address this by having a compatibility scoring approach and then iterate through all possible compatible options and choose the most compatible.

Is the choice of 0...100 as ints an optimization over using a double between 0...1?

Thanks
Joe

**Comment by SavtechSolutions** [comment]
The range goes -1..100, not 0..100. The reason is because a schema with rating 0 (all nullable fields) is still a valid backup choice, if we can't find anything better. So I either had to make the formula more complex, or to have the "incompatible" value be outside of range (I chose the latter). As for why using integers - I prefer not to deal with floating point arithmetic unless it's genuinely necessary.

**Comment by SavtechSolutions** [comment]
Merged latest master and resolved conflicts (record compatibility check was refactored into a separate method, made my job a little easier)

**Comment by SavtechSolutions** [comment]
Fixed the Javadoc for the new method

**Comment by joewitt** [comment]
closing due to inactivity

**Pull request closed without merging**
