### PR TITLE
[NIFI-2898] restore ellipsis for processor type, controller servies t…

### PR DESCRIPTION
**Pull request by scottyaslan**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

…ype, and reporting task type descriptions

### CODE REVIEW

**Comment by mcgilman** [comment]
Reviewing...

**Comment by mcgilman** [comment]
I have verified that the ellipsis have been restored to the descriptions of the new Processor, Controller Service, and Reporting Task table. However, it appears as though we are still using a scrollable area for the View State dialog. Should we make these consistent?

**Comment by moranr** [comment]
@mcgilman  I think it makes sense to use the ellipsis for view state too.

@scottyaslan I'm still seeing the scrollable class applied on the Add Processor description as well, so I can both scroll _and_ hover to see the full description.

Also, can we apply the the styling that I outlined in my earlier jira comment to all these areas? This way both behavior and design will be consistent.

**Comment by scottyaslan** [comment]
@moranr @mcgilman I have updated this PR to also include a 'fix' to the ellipsis plugin for the view state description.

@moranr I think you were seeing a caching issue with the scrollable style...anyway, it should be fixed now with the latest update to this PR. Also I was able to apply the styles you suggested in the Jira. Be aware, however, there is an issue with the spacing you outlined in the Jira. The issue is that the ellipsis plugin requires the width and height of the element be set in 'px'. With the responsive nature of the dialogs I do not believe we can support these descriptions as responsive divs that would be necessary to fulfill said spacing (i.e. to support a responsive description area div we would need to apply position:absolute). This will require a much larger effort and as the original ask for NIFI-2898 was to restore the 0.x ellipsis functionality I think we could consider the spacing you outlined as part of a follow on Jira that will support the scrollable description areas (as discussed in https://issues.apache.org/jira/browse/NIFI-2898). Please let me know what you think...

**Comment by moranr** [comment]
Thanks for the info @scottyaslan – I understand the issue regarding the spacing/height so addressing in a follow on Jira is best. 

I did just check out the latest and it looks good!

**Comment by mcgilman** [comment]
Looks good @scottyaslan! This has been merged to master.

**Pull request closed without merging**
