### PR TITLE
NIFI-6016 PutCassandraRecord batch size

### PR DESCRIPTION
**Pull request by dnsbtchr**
Adds resetting the batch size to fix broken batch processing

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by mattyb149** [comment]
Can you add a unit test for this? Should be able to confirm that you're getting the expected number of flow files, and the flow files have the expected number of records

**Comment by dnsbtchr** [comment]
Hi @mattyb149, I could create a test but why should it test the number of flow files/records cause it only changes the C* statement handling.

**Comment by mattyb149** [comment]
Looks like the PutCassandraRecordTest is a copy-paste for something like QueryCassandra, unfortunately it doesn't mock the methods that PutCassandraRecord calls (like `execute`). We should really refactor that unit test (specifically the mock), if we had we could've tested the number of statements in the batch and caught this error ahead of time.

Having said that, I reviewed the code, +1 LGTM, we can do the test refactor in a separate Jira. Thanks for the fix! Merging to master

**Comment by dnsbtchr** [comment]
@mattyb149 cool thanks. I saw the existing test and wasn't sure how to include a test case for my logic in there because of the not existing mocking. Thanks for merging it!

**Pull request closed without merging**
