### PR TITLE
NIFI-11208 Remove Hortonworks Schema Registry

### PR DESCRIPTION
**Pull request by exceptionfactory**
# Summary

[NIFI-11208](https://issues.apache.org/jira/browse/NIFI-11208) Removes the `HortonworksSchemaRegistry` Controller Service and associated Maven modules, based on deprecation notices in NiFi 1.20.0.

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X] Pull Request based on current revision of the `main` branch
- [X] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 11
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by mattyb149** [comment]
Reviewing...

**Comment by MikeThomsen** [comment]
What is the preferred approach at this point for schema registries?

**Comment by exceptionfactory** [comment]
> What is the preferred approach at this point for schema registries?

That's a good question. The answer may depend on the environment in which NiFi is deployed. This pull request follows through with the deprecation. There appears to be some additional momentum recently with the Hortonworks Registry, which might provide opportunity for a new implementation. The current client version is still pre-1.0.0, so removing this implementation opens options for new approaches. New work could be considered in a new Jira issue.

**Comment by mattyb149** [comment]
+1 LGTM, with the opportunity for new work in the future and the previous deprecation of this one I agree this is the way to go. Thanks for working through the list! Merging to main

**Comment by MikeThomsen** [comment]
Is there a FOSS, updated version of the HWX registry @exceptionfactory ?

**Comment by exceptionfactory** [comment]
The [Hortonworks Registry](https://github.com/hortonworks/registry) repository includes a more recent release of version [1.0.0](https://github.com/hortonworks/registry/releases/tag/1.0.0-rc2). It is probably some additional conversation to evaluate the roadmap for the project and potential integration options.

**Pull request closed without merging**
