### PR TITLE
NIFI-9801 Fixed error in previous correction of AccessToken.isExpired() margin calculation

### PR DESCRIPTION
**Pull request by tpalfy**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Review by MikeThomsen — CHANGES_REQUESTED** [review]
A hard-coded value here could be problematic for services with shorter-lived bearer tokens. Can we make it user-configurable with a minimum of 30 sec?

**Comment by exceptionfactory** [comment]
Thanks for the feedback @MikeThomsen.  Are you suggesting that this should be a new property on the StandardOauth2Provider service?  Given that the initial version did not have this margin feature, it seems like the options are either introducing a configurable property, or reverting to the original behavior that did not include any margin.  It would be helpful to figure out a path forward soon as this is currently blocking the next release candidate for 1.16.0.

**Comment by exceptionfactory** [comment]
Thanks @MikeThomsen, I agree that making the margin a configurable property on `StandardOauth2AccessTokenProvider` would provide the greatest amount of flexibility, and also address the issue at hand.

@tpalfy, realizing that this changes the scope of the initial issue, what do you think about making the new property part of this PR?

**Comment by tpalfy** [comment]
@MikeThomsen, @exceptionfactory
I would consider the need to add a property for the margin not urgent, if necessary at all.

A 5 minute access token is extreme on its own but the service would handle such a scenario just fine. The service gets a new token if it considers the current one close to being expired. It doesn't break, doesn't throw exception, doesn't report error. Gets a new token thats all.

In the extreme cases this would simply mean getting a new token ever time.

**Review by exceptionfactory — APPROVED** [review]
Thanks for the reply @tpalfy.

Some OAuth2 services can have short token expirations, and of course others can be much longer, so ultimately introducing a configurable property seems like the best way to go.

For the purpose of moving things I forward, I am in favor of merging this PR as it stands. It corrects the margin calculation, and keeps the margin minimal. I will create a separate Jira issue to introduce the configurable property.

Does that sounds good to you @MikeThomsen?

**Review by MikeThomsen — APPROVED** [review]

**Pull request closed without merging**
