### PR TITLE
NIFI-9696 : DeleteS3Object don't have provenance

### PR DESCRIPTION
**Pull request by lawye1973**
Changed from AmazonS3 to AmazonS3client.
Add SEND provenance event with transitUri value of "DELETE <url>"

Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Enables X functionality; fixes bug NIFI-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [ ] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [x] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [x] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Review by turcsanyip — CHANGES_REQUESTED** [review]
@lawye1973 Thank you for implementing this missing feature!

`SEND` event is for indicating a provenance event for sending data to an external system.
Please use `REMOTE_INVOCATION` instead, like in case of [DeleteHDFS](https://github.com/apache/nifi/blob/67880765365e033d0d772f5c7b5c2e2186a1086c/nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/DeleteHDFS.java#L179) or [DeleteAzureDatalakeStorege](https://github.com/apache/nifi/blob/67880765365e033d0d772f5c7b5c2e2186a1086c/nifi-nar-bundles/nifi-azure-bundle/nifi-azure-processors/src/main/java/org/apache/nifi/processors/azure/storage/DeleteAzureDataLakeStorage.java#L104). Thanks!

**Comment by lawye1973** [comment]
> @lawye1973 Thank you for implementing this missing feature!
> 
> `SEND` event is for indicating a provenance event for sending data to an external system. Please use `REMOTE_INVOCATION` instead, like in case of [DeleteHDFS](https://github.com/apache/nifi/blob/67880765365e033d0d772f5c7b5c2e2186a1086c/nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/DeleteHDFS.java#L179) or [DeleteAzureDatalakeStorege](https://github.com/apache/nifi/blob/67880765365e033d0d772f5c7b5c2e2186a1086c/nifi-nar-bundles/nifi-azure-bundle/nifi-azure-processors/src/main/java/org/apache/nifi/processors/azure/storage/DeleteAzureDataLakeStorage.java#L104). Thanks!

@turcsanyip , thanks for the guidance. I'd updated the code.

**Comment by markap14** [comment]
@lawye1973 this PR is also set to merge into the `master` branch. But that branch hasn't been used in a long time. Please create with an upstream branch of `main`.

**Comment by lawye1973** [comment]
@pvillard31  / @markap14 , I'd managed to change the base to apache/main. Thanks.

**Comment by turcsanyip** [comment]
@lawye1973 Please also rebase your branch onto main and then force push it. You have a couple of conflicts.

**Pull request closed without merging**
