### PR TITLE
NIFI-3452: Add Wait processor Wait Mode property

### PR DESCRIPTION
**Pull request by ijokarumawak**
Ensure back-pressure is active until downstream processing completes.

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by ijokarumawak** [comment]
Dear reviewer, 
an example flow template is available here:
https://gist.github.com/ijokarumawak/85a3d77297ea94614e9f3f2a9dabca67

**Comment by basvank** [comment]
@ijokarumawak I have tested your patch on a single node with 3 the same flows and it does exactly what I expected and required as explained in [my mailing list entry](http://apache-nifi-users-list.2361937.n4.nabble.com/Problem-when-using-backpressure-to-distribute-load-over-nodes-in-a-cluster-tp863p903.html). I am not able to test in the cluster setting at this moment but I see no reason why it wouldn't work there.

Thanks for your effort!

**Comment by ijokarumawak** [comment]
@basvank Thanks for confirming the change, that certainly make the review & merge process easier!

**Comment by pvillard31** [comment]
Hi @ijokarumawak, thanks for this improvement, that's really nice. And thanks for the template, it was really useful to review this PR! I just have a minor styling issue and since this processor is not released yet: could you just update the properties to use both ``.name()`` and ``.displayName()``? Otherwise LGTM and I'll merge as soon as you let me know.

**Comment by ijokarumawak** [comment]
Thanks for reviewing, @pvillard31 .
I've updated this PR:
- Rebased with the latest master, just in case
- Added display name and name
- Corrected indent (probably this is the minor styling issue..?)
Please let me know if there's anything else. Thanks!

**Comment by ijokarumawak** [comment]
As a side note, there's Notify processor which is designed to work together with Wait processor. Since there's an existing PR #1466 adding properties to Notify, I didn't touch it by this PR. Please check #1466 for Notify processor update.

**Comment by pvillard31** [comment]
Perfect, 👍 merging to master, thanks @ijokarumawak

**Pull request closed without merging**
