### PR TITLE
NIFI-1662 adding Expression Language decimal support

### PR DESCRIPTION
**Pull request by JPercivall**

### CODE REVIEW

**Comment by mattyb149** [comment]
Why are decimal literals expected to be in String format? Seems like the Lexer should be able to determine a decimal literal from a whole number literal?

**Comment by JPercivall** [comment]
@mattyb149 the problem was that the parsing for the various representations of doubles in Java is crazy, Check out the pattern used in this documentation[1]. I guess we could offer a sub-set of the representations as literals?

[1] https://docs.oracle.com/javase/8/docs/api/java/lang/Double.html#valueOf-java.lang.String-

**Comment by mattyb149** [comment]
I like the idea of a subset, we can probably cover 90% of the cases people have for floating-point literals (who uses Hex literals for floating point?!), but it might warrant a discussion with the community.

**Comment by JPercivall** [comment]
@mattyb149, I agree with adding it to the lexer as a subset. I thought through it a bit more and is someone passes "toLiteral('1.1')" they should expect they would get a string with the value "1.1". 

I'll do some research on the best way to parse double/floating points via Antlr and post a new commit.

Thanks!

**Comment by mattyb149** [comment]
I'm a big ANTLR fan :) so I tried adding decimal literals to the grammar, feel free to take a look and use whatever you like: https://github.com/mattyb149/nifi/commit/9ed3fb4f17b0ec64fbe9d861ff255750c3ec7e5a

**Comment by JPercivall** [comment]
@mattyb149 this is awesome! I was having bit of trouble trying with the grammar due to not knowing much about ANTLR. I'm gonna add your commit to my branch, test it a bit and then add it to the PR.

**Comment by JPercivall** [comment]
@mattyb149 just pushed out a new commit along with yours. I added proper support for literal decimals in the UI as well.

**Comment by trixpan** [comment]
> (who uses Hex literals for floating point?!),

I do! Like... All the time!

But I also joke sometimes...

:smiley:

**Comment by mattyb149** [comment]
+1 LGTM, great addition here, thanks! Merging to master

**Pull request closed without merging**
