### PR TITLE
NIFI-2905: Log error stream of ExecuteProcess cmd

### PR DESCRIPTION
**Pull request by ijokarumawak**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by pvillard31** [comment]
Hey @ijokarumawak 
One of the unit tests is failing on my side:
Failed tests:
  TestExecuteProcess.testNotRedirectErrorStream:226 If redirect error stream is false, the output should be logged as a warning so that user can notice on bulletin. expected:<1> but was:<0>

Note: the test is failing while running a maven build, although everything is fine in my IDE.

**Comment by ijokarumawak** [comment]
@pvillard31 Thanks for catching that, I was able to reproduce that the test fails with mvn command. Investigating how to address it. I'll send an updated PR once it's get fixed. Thank you!

**Comment by alopresto** [comment]
Reviewing...

**Comment by alopresto** [comment]
Built with `contrib-check` and verified all tests pass. I started the application, and used an `ExecuteProcess` processor with command `cd` and arguments `non-existent-dir`. With `Redirect Error Stream` set to **false** (default), the errors appeared as bulletins. With `Redirect Error Stream` set to **true**, no bulletins were raised, and the error message was found in the resulting flowfile contents. 

+1, merging.

**Comment by JPercivall** [comment]
@ijokarumawak @alopresto @pvillard31 I am seeing errors in travis related to this PR[1]. I am going to re-open the ticket in order to investigate

[1] https://s3.amazonaws.com/archive.travis-ci.org/jobs/170218968/log.txt

**Pull request closed without merging**
