### PR TITLE
NIFI-12079 - Remove Variables / Variable Registry

### PR DESCRIPTION
**Pull request by pvillard31**
# Summary

[NIFI-12079](https://issues.apache.org/jira/browse/NIFI-12079) - Remove Variables / Variable Registry

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by pvillard31** [comment]
The user guide still needs to be updated with new screenshots. I'll add this tomorrow but opening the draft PR to get some builds running and if someone wants to have a look.

**Review by exceptionfactory — COMMENTED** [review]
It looks like at least one Flow Configuration in the system test suite needs to be updated to remove the reference to Variables:

```
rror:    Unrecognized field "variables" (class org.apache.nifi.flow.VersionedProcessGroup), not marked as ignorable (28 known properties: "groupIdentifier", "statelessFlowTimeout", "name", "outputPorts", "maxConcurrentTasks", "connections", "componentType", "controllerServices", "instanceIdentifier", "processors", "processGroups", "scheduledState", "inputPorts", "identifier", "flowFileOutboundPolicy", "parameterContextName", "defaultBackPressureDataSizeThreshold", "comments", "versionedFlowCoordinates", "defaultFlowFileExpiration", "remoteProcessGroups", "labels", "logFileSuffix", "position", "executionEngine", "funnels", "defaultBackPressureObjectThreshold", "flowFileConcurrency"])
 at [Source: (FileInputStream); line: 155, column: 19] (through reference chain: org.apache.nifi.registry.flow.VersionedFlowSnapshot["flowContents"]->org.apache.nifi.flow.VersionedProcessGroup["variables"])
 ```

**Comment by pvillard31** [comment]
Thanks David, yeah, I noticed that one (had some troubles running system tests locally). I'm trying to figure out some UI issues with my changes but not my domain of expertise.

**Comment by joewitt** [comment]
What a thorough update!   I can tell there was some complexity with what to name this thing.  EnvironmentRegistry.  EnvSystemRegistry.  EnvironmentSystemRegistry, etc..  I recommend we just consistently call this thing ENVIRONMENT as the scope like you did then just use the term Environment everywhere else.  Define this scope as providing values in the order of JVM System Properties first then Environment variables available to the process and just leave it referred to as 'Environment'.    What do you think?

**Comment by exceptionfactory** [comment]
> What a thorough update! I can tell there was some complexity with what to name this thing. EnvironmentRegistry. EnvSystemRegistry. EnvironmentSystemRegistry, etc.. I recommend we just consistently call this thing ENVIRONMENT as the scope like you did then just use the term Environment everywhere else. Define this scope as providing values in the order of JVM System Properties first then Environment variables available to the process and just leave it referred to as 'Environment'. What do you think?

+1 for `ENVIRONMENT` as the name of the scope going forward.

**Comment by joewitt** [comment]
@pvillard31 you mind rebasing given the changes?  What do you think about getting rid of the EnvSys naming and just referring to it uniformly as EnvironmentVariables instead?

**Comment by pvillard31** [comment]
For now I just rebased against the main branch (I hope I did it correctly). Going through the changes to be more consistent with the naming.

**Comment by joewitt** [comment]
Full clean build with contrib check good.  And Github CI looking great.
Reviewed each changed file all looks good.  Some of the changes in files seemed massive due to perhaps whitespace but doesn't seem worth delaying this further.
Ran a series of tests using system properties.  Environment variables. Parameter contexts.  Looking each up either directly in the processor properties of UpdateAttribute or via parameter context lookup.  All worked as expected.

Great work Pierre.  This is a massive PR.  But dont want to delay it further as it will impact many things going into 2.x from here out.  This one is so expansive it likely starts to really make the break betweeen 2.x and 1.x.

Other notable changing the scope from VARIABLE to ENVIRONMENT will surely make 1.x processors not run on 2.x but I think we're likely well into needing people to rebuild for 2.x anyway a thing. 

+1 merging to main

**Pull request closed without merging**
