### PR TITLE
NIFI-3964 KeyValue lookup service and Grok patterns controller

### PR DESCRIPTION
**Pull request by pvillard31**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [X] Have you written or updated unit tests to verify your changes?
- [X] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by pvillard31** [comment]
Just rebased this one against master, if someone wants to have a look.

**Comment by pvillard31** [comment]
@ottobackwards - you're completely right and by rebasing the PR, I missed something.
Instead of using
````java
grokCompiler.register(String,String);
````
I should use
````java
grokCompiler.register(Map<String,String>);
````
That would solve the issue you're mentioning, right?

The reasoning behind this PR is to remove the need of a file (deploying files on every node of a NiFi cluster can be annoying... and by using a controller service, this can be part of the flow development lifecycle since it can be saved in the NiFi Registry).

What do you think?

**Comment by ottobackwards** [comment]
No.  I'm not talking about getting all the groks from the controller and registering them.
I'm talking about having to setup the controller, and type in a dynamic property for all the groks required.

The concept that there is one or more groks is wrong in my mind.  For every one of the _user's_ groks, the groks they want to use, there may be a dozen groks composited in and need to be compiled in to execute them.

Usability wise, entering the dynamic property this way will only work for the simplest cases.

**Comment by pvillard31** [comment]
I'm certainly not a grok expert and probably using it in simplest cases, but in all the log ingestion use cases I'm working on, I'm usually fine with the default patterns file (already loaded from classpath with the processor/reader CS) and a few additional patterns for the log sources I'm dealing with.

I'm not sure to see why composite groks would be an issue here? (I updated the unit test to use one)
Do you have an example in mind? (again not a Grok expert :))

**Comment by ottobackwards** [comment]
I am tainted by my work on Metron

https://github.com/apache/metron/tree/master/metron-platform/metron-parsers/src/main/resources/patterns

**Comment by joewitt** [comment]
Closing due to inactivity.

**Pull request closed without merging**
