### PR TITLE
NIFI-12488: Add support for dynamic sensitive properties for the ExecuteProcess processor

### PR DESCRIPTION
**Pull request by lfrancke**
# Summary

[NIFI-12488](https://issues.apache.org/jira/browse/NIFI-12488)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [x] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [x] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [x] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by lfrancke** [comment]
The build failed for me locally but on totally unrelated tests (Registry) so I assume it's okay.

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for proposing this improvement @lfrancke.

The change itself looks useful, but there are some important additional changes required before this can go forward. Reviewing the Processor implementation, it currently logs commands at the info level and also reports commands to Provenance. These are at least two items that need to be changed.

Part of the general contract for sensitive property handling is that components will not leak sensitive information to the best of their ability. In a Processor like ExecuteProcess, called commands are still responsible for proper handling, but at least in terms of the Processor itself, it should not log sensitive information, which would be visible to NiFi operators.

For other Processors, the most straightforward approach was to remove the logging. That may be acceptable in this case, or ideally, only the base command would be logged, without the arguments. That may require more changes. If you are willing to work on making those additional changes and review the code or any other potential references writing configured arguments, then this can go forward.

**Comment by exceptionfactory** [comment]
Thanks for the quick reply @lfrancke. If you get to the point where you don't think you will be able to complete the changes, I recommend noting these details on the Jira issue for future implementation.

**Comment by exceptionfactory** [comment]
Thanks again for suggesting this improvement @lfrancke. Based on the current state of the PR and previous comments, I am closing it for now, but feel free to open it again if you have the opportunity to work through the rest of the Processor and implement the additional changes necessary.

**Comment by lfrancke** [comment]
I'm sorry for the silence. Thank you!
I'm back with the customer that requested this only in February and might pick it up then, we'll see if they are still interested.

**Pull request closed without merging**
