### PR TITLE
NIFI-2821 - Convert DNS_TIMEOUT property to TIME_PERIOD

### PR DESCRIPTION
**Pull request by trixpan**

### CODE REVIEW

**Comment by trixpan** [comment]
@pvillard31 this escaped our initial PR

**Comment by pvillard31** [comment]
@trixpan correct, +1, merging...

**Comment by pvillard31** [comment]
@trixpan  I don't know why GitHub is not complaining about it but this is already in master:
````
commit f6ba92229224504d0bbd1126bd8428a010bb4c45
Author: Andre F de Miranda <trixpan@users.noreply.github.com>
Date:   Tue Aug 9 23:08:16 2016 +1000
NIFI-1965  This closes #819. COnvert DNS_TIMEOUT property to TIME_PERIOD
````

**Comment by trixpan** [comment]
github seems to be experiencing some issues. It should sync automagically later on. Thanks for merging, will close the JIRA

**Comment by pvillard31** [comment]
@trixpan My point is that this modification has been made early August, there is nothing to merge ;)

**Comment by trixpan** [comment]
wow... bizarre

**Comment by trixpan** [comment]
I knew I had spotted that before the merge... weird stuff.

**Pull request closed without merging**
