### PR TITLE
NIFI-2754

### PR DESCRIPTION
**Pull request by patricker**
If the Active queue is empty and the number of FlowFiles added to the queue is perfectly splitable by the current Swap size (100000 Flow Files / 20000 files per swap file = 5 with no remainder), then no FlowFiles will move to Active and all will remain in Swap.

Apart from NIFI-2754, there was also a style violation in the existing code, which I fixed.

### CODE REVIEW

**Comment by mcgilman** [comment]
Thanks for the PR @patricker! The proposed solution makes sense to me but I would love to get @markap14 input before signing off as I know he's much more familiar with this part of the codebase.

**Comment by markap14** [comment]
@patricker @mcgilman looking at the PR, I do think that this will resolve the specific use case that you're running into, Peter. I think, though, that it is addressing a very specific corner case and could actually be solved a little more generally, though. Instead of changing the number of swap files based on the specific condition of `activeQueue.size() == 0 && numSwapFiles > 0 && swapQueue.size() % SWAP_RECORD_POLL_SIZE == 0` what do you think of just calling `migrateSwapToActive()` at the beginning of the `writeSwapFilesIfNecessary()`? This should also ensure that we keep with the same ordering guarantees that we have provided throughout the rest of the class.

**Comment by patricker** [comment]
@markap14 I changed the code per your suggestion and the test I wrote still worked as expected.
PR updated.

**Comment by mcgilman** [comment]
Thanks @patricker! Following Mark's suggestion and your update, I've gone ahead and merged this into master.

**Pull request closed without merging**
