### PR TITLE
NIFI-3781 - Controller Service Config Dialog...

### PR DESCRIPTION
**Pull request by yuri1969**
..'View Details' button feels confusing and inconsistent with Processors

* Merged 'View Details' and 'Edit' buttons to a single 'Configure'/'View Details' one.
* Fixed confusing 'View Details' modal's title.

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?

### CODE REVIEW

**Comment by moranr** [comment]
This looks pretty good @yuri1969 . Another thing that would probably makes sense is to change the icon's tooltip (title) to 'View configuration' since it does not use the view details icon anymore. That, of course, would only happen when the controller service is enabled.

**Comment by scottyaslan** [comment]
Will review...

**Comment by moranr** [comment]
I also commented in original JIRA looking for feedback from some others as well.

**Comment by yuri1969** [comment]
@moranr @scottyaslan Changed the tooltip to _View Configuration_.

**Comment by scottyaslan** [comment]
Reviewing...

**Comment by scottyaslan** [comment]
Thanks @yuri1969 this has been merged to master.

**Pull request closed without merging**
