### PR TITLE
NIFI-7761 Allow HandleHttpRequest to add specified form data to FlowF…

### PR DESCRIPTION
**Pull request by ottobackwards**
[http_template.xml.zip](https://github.com/apache/nifi/files/5181358/http_template.xml.zip)

…ile attributes

To verify:
- add the attached template
- configure the HandleHttpRequest `Parameters to Attributes List` property to have `data1,DataTwo`
- Enable the context service
run the flow.

Observe the new attributes in the nifi-app.log

Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Enables X functionality; fixes bug NIFI-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [-] Have you written or updated unit tests to verify your changes?
- [x] Have you verified that the full build is successful on JDK 8?
- [-] Have you verified that the full build is successful on JDK 11?
- [-] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [-] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [-] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [x] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

---
This change is [Reviewable](https://reviewable.io/reviews/apache/nifi/4513)

### CODE REVIEW

**Comment by ottobackwards** [comment]
touch

**Comment by grego33** [comment]
I've not built and tested this but the code looks good.  Very clear.  I can see how simply specifying a comma-separated list of form names will result in http.param.XXX FlowFile attributes.  This will be nice as it will even allow simplification of some flows to eliminate UpdateAttribute processors whose job is just to trim out unwanted attributes.

I'm happy to build/test as well.  I should be able to do that this week.  But wanted to give *some* response since I just realized you've been waiting for me for quite a while.  Apologies about that - I didn't notice until your "touch" comment.

**Comment by ottobackwards** [comment]
touch

**Comment by grego33** [comment]
Checked this out and ran it locally today.  Worked great!  Thanks so much.

**Comment by ottobackwards** [comment]
Thanks @grego33, hopefully we can get some eyes on this soon

**Comment by ottobackwards** [comment]
touch - mic tap - wave

**Comment by joewitt** [comment]
@ottobackwards this processor doesn't have unit tests or this new thing is too difficult to have a unit test for?

**Comment by ottobackwards** [comment]
I think there is only `ITestHandleHttpRequest`, which I took to be an integration test.  I will add something there

**Comment by ottobackwards** [comment]
Ok, added.  I would like to say why I didn't do so at the start, but I've forgotten

**Comment by joewitt** [comment]
Understood - thanks

**Comment by ottobackwards** [comment]
Happy New Year!

**Comment by markap14** [comment]
@ottobackwards changes look good to me. I'm a +1 on this, but it looks like it has some conflicts. Can you resolve and ping me? Then I'll be happy to merge. Happy new year!

**Comment by ottobackwards** [comment]
Screen Shot 2021-01-04 at 16 34 50

???

**Comment by joewitt** [comment]
This branch cannot be rebased due to conflicts
Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch.

**Comment by joewitt** [comment]
I think the merge thing done might have messed it up.  You might want to rebase the two real commits to the latest main then force push without any merge commits.

**Comment by ottobackwards** [comment]
sure thing!

**Comment by ottobackwards** [comment]
ok, should be set

**Comment by joewitt** [comment]
cool that looks better. lets see if it builds

**Comment by ottobackwards** [comment]
@joewitt, sorry for the confusion

**Review by pvillard31 — APPROVED** [review]

**Comment by pvillard31** [comment]
Merged to main based on previous comments. Thanks @ottobackwards @joewitt @markap14 @grego33

**Pull request closed without merging**
