### PR TITLE
NIFI-10649 update commons-cli to 1.5.0

### PR DESCRIPTION
**Pull request by UcanInfosec**
# Summary

[NIFI-10649](https://issues.apache.org/jira/browse/NIFI-10649)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI-10649) issue created

### Pull Request Tracking

- [X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X] Pull Request based on current revision of the `main` branch
- [X] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [X] JDK 8
  - [X] JDK 11
  - [X] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for the upgrade @UcanInfosec. The basic upgrade looks good, but given the usage of `commons-cli` across NiFi, Registry, and MiNiFi, and the general stability of the library, it looks like a good candidate to promote to root pom.xml managed dependency version, similar to Apache Commons Lang3. This would eliminate the need for explicit versions in each pom.xml.  Changes should also be squashed into a single commit for initial pull request submission.

Can you make the changes?

**Comment by UcanInfosec** [comment]
@exceptionfactory I’m currently a bit busy, so I am not able to take the time to do this. But if I learn how to do this, I can do it in the future

**Comment by exceptionfactory** [comment]
Thanks for the reply @UcanInfosec, I can make the changes and push an update to your branch for reference on the approach I am suggesting.

**Comment by exceptionfactory** [comment]
@UcanInfosec I pushed an update with the proposed changes, where the version is now managed in the parent Maven configuration. If this passes the automated checks, will plan on merging.

**Review by exceptionfactory — APPROVED** [review]
The current builds look good, thanks @UcanInfosec. +1 merging

**Comment by UcanInfosec** [comment]
@exceptionfactory thanks. This makes sense now. Will make sure to follow this procedure when doing these types of updates going forward.

**Comment by exceptionfactory** [comment]
You're welcome @UcanInfosec. Moving certain dependencies to the parent level is something to evaluate on a case-by-case basis, but hopefully this is a helpful example.

**Pull request closed without merging**
