### PR TITLE
NIFI-1956 added 'keyboard-interactive' option to SFTPTransfer

### PR DESCRIPTION
**Pull request by olegz**

### CODE REVIEW

**Comment by pvillard31** [comment]
@olegz 
Just to be sure before merging in: do you plan to add a unit test?
My guess is that it is not possible to simulate this server-side behavior, but I want to confirm.

**Comment by olegz** [comment]
Well, while you can simulate the server behavior by changing SSH server configs locally, indeed it would be impossible to ensure consistency on all machines where build may be running. So the only thing I can test is that it is set which I should probably do.

**Comment by olegz** [comment]
@pvillard31gave it some time and it looks like with regard to testing this one will be one of those exceptions. In other words there is no easy way to reliably write a test case to validate that this property is set since it is set in private _getChannel(..)_ method. And even if I use reflection to invoke it, it would still require the running SSH server which may not be the case on other build environments. 
Now, I don't want to say that it's completely impossible, but at the moment I am willing to say it is not worth the effort. Let m know what you think.

**Comment by pvillard31** [comment]
Agree. Merging...

**Pull request closed without merging**
