### PR TITLE
NIFI-13856: Capture build scans on ge.apache.org to benefit from deep build insights

### PR DESCRIPTION
**Pull request by clayburn**
# Summary

[NIFI-13856](https://issues.apache.org/jira/browse/NIFI-13856)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [x] Build completed using `mvn clean install -P contrib-check`
  - [x] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — COMMENTED** [review]
Thanks for putting together the changes to enable integration with the Apache instance of [Develocity](https://ge.apache.org) @clayburn! This looks like it should provide some helpful insights into the build process.

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
@clayburn Unfortunately a number of the builds failed with heap memory errors:

```
Error: Exception in thread "JNA Cleaner" java.lang.OutOfMemoryError: Java heap space
Error:  Java heap space -> [Help 1]
```

Are there minimum heap requirements for running the Develocity extension?

**Comment by exceptionfactory** [comment]
In order to focus on the heap usage concerns, it would be helpful to scope the changes to just the `ci-workflow` for standard builds. Can that be handled through an explicit environment variable added to the workflow?

**Comment by clayburn** [comment]
@exceptionfactory - unfortunately there is no good way to disable the extension via an env var. Being in the extensions.xml, it will always get picked up. I suppose we could add a step that deletes that file, but it would be an awkward way to do it.

For the moment, I tried adding max heap to each job to see if that gives some breathing room here. We can discuss whether that is the right change or not.

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks again for working on this integration with Develocity @clayburn.

Given the failures after increasing the maximum heap size, it looks like some closer evaluation of the memory impact is necessary. Perhaps another incremental increase is worth a try, but as this appears to be reproducible on a local machine when setting a maximum heap size, it may only be worth revisiting after confirming a successful local build.

I'll leave this open for a few days for continued discussion. If no immediate solution is apparent, we can collaborate offline and circle back on a new PR after considering the options.

**Comment by clayburn** [comment]
@exceptionfactory - I still need to do some experimenting, but don't see me achieving that this week given other obligations. I'll close this for now and reopen once I have more conclusive data.

**Pull request closed without merging**
