### PR TITLE
NIFI-5714 - Hive[3]ConnectionPool - Kerberos Authentication issue/mis…

### PR DESCRIPTION
**Pull request by pvillard31**
…leading

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by pvillard31** [comment]
Hey @mattyb149 - could you let me know if this LGTY ;)

**Comment by pvillard31** [comment]
hold on - just realized that the unit test does not work in the Travis env for the kerb stuff

**Comment by mattyb149** [comment]
Looks like the unit test is throwing the wrong exception, IllegalArgumentException instead of InitializationException

**Comment by pvillard31** [comment]
The unit test is working fine locally on my side but does not work in Travis. I assume it could be because I've Kerberos related configs on my laptop. Didn't find any similar testing in other processors? Not sure how to address it (tried few things). What do you think? Just adding @Ignore on the test? =/

**Comment by mattyb149** [comment]
Same here, the relevant error in the Travis log is "Cannot locate default realm". Looking at other tests that load krb5.conf, one (TestHBase_1_1_2_ClientService) has this:

```
// needed for calls to UserGroupInformation.setConfiguration() to work when passing in
// config with Kerberos authentication enabled
System.setProperty("java.security.krb5.realm", "nifi.com");
System.setProperty("java.security.krb5.kdc", "nifi.kdc");
```

and another (TestRangerNiFiAuthorizer) has this:

```
// have to initialize this system property before anything else
File krb5conf = new File("src/test/resources/krb5.conf");
assertTrue(krb5conf.exists());
System.setProperty("java.security.krb5.conf", krb5conf.getAbsolutePath());
```

Perhaps one or both of these would fix the issue? Not sure how to reproduce, I guess you could try one and push the commit to see if Travis succeeds...

**Comment by mattyb149** [comment]
First one didn't work :(

**Comment by pvillard31** [comment]
Tried few things... no luck :(

**Comment by mattyb149** [comment]
The krb5.conf from the TestRangerNiFiAuthorizer looks like this:

```
[libdefaults]
         default_realm = EXAMPLE.COM
         dns_lookup_kdc = false
         dns_lookup_realm = false

[realms]
         EXAMPLE.COM = {
             kdc = kerberos.example.com
             admin_server = kerberos.example.com
         }
```

And doesn't have the setting of the `java.security.krb5.realm` or `java.security.krb5.kdc` (I assume because they are unnecessary based on the dns_lookup_* properties?). Might be worth a try...

**Comment by mattyb149** [comment]
Doesn't look like the tests were run due to a bad artifact. Maybe rebase the PR (squashing just the commits where you tried individual things?) and force push, hopefully it'll go through this time :( Sorry this is such a pain.

**Comment by pvillard31** [comment]
tried to squash everything and force push, but same result - tried to look in the code if something is different and should be initialized differently but didn't find anything obvious :(

**Comment by pvillard31** [comment]
Hey @mattyb149 - I gave up on the unit test and added the Ignore annotation. I confirmed in my environment that the controller service won't be enabled if Kerberos authentication fails and that we are not logging the "authentication successful" message anymore.

**Comment by mattyb149** [comment]
+1 LGTM, tested successfully. Thanks for the fix! Merging to master

**Pull request closed without merging**
