### PR TITLE
Backport NIFI-2728 to 0.x tree

### PR DESCRIPTION
**Pull request by trixpan**

### CODE REVIEW

**Comment by mcgilman** [comment]
Reviewing...

**Comment by trixpan** [comment]
don't... still not ready. I suspect -T 2.0C is hitting 0.x build too heavily. Not sure why but I had all sort of crazy travis failures, including a jvm core dump!

**Comment by trixpan** [comment]
because this is 0.x (and as such less likely to be under constant builds, are you ok with us building without -T?

**Comment by mcgilman** [comment]
I was just going to comment that I can't seem to get the Java 7 builds to pass. Still not sure if it's related to your changes or not though. I'll sit tight until you update.

I don't have any issue removing the multi-threaded builds here.

Thanks!

**Comment by mcgilman** [comment]
Thanks @trixpan! This has been merged to the 0.x branch.

**Pull request closed without merging**
