### PR TITLE
NIFI-1651 unit tests work on windows. removed contributor name/package from data and schema

### PR DESCRIPTION
**Pull request by trkurc**

### CODE REVIEW

**Comment by apiri** [comment]
reviewing

**Comment by pvillard31** [comment]
Tried a mvn clean install without success on my side (I missed something?):
[mvn_output.txt](https://github.com/apache/nifi/files/181411/mvn_output.txt)

**Comment by trkurc** [comment]
Pierre, what environment are you running on?

**Comment by pvillard31** [comment]
Windows 7 Pro / Maven 3.3.9 / Java 1.8.0_74

**Comment by trkurc** [comment]
Did you clone the code with autocrlf? Does the schema in src/test/resources have line endings?

**Comment by mosermw** [comment]
Using Windows 10, maven 3.3.9, java 1.7.0_79 the nifi-kite-bundle fails on this unit test before this patch.  nifi-kite-bundle unit tests work fine after this patch.  +1 from me.

**Comment by apiri** [comment]
Windows 7, Maven 3.3.3, and JDK 8u71 looks good here.  

Will look for updates from @pvillard31

**Comment by pvillard31** [comment]
Sorry for the delay... I am on a different computer than usual and forgot to check the git property. Did a full clone again (so slow with airport wifi...) and checked the schema (looks OK to me). The git property solved most of the issues, but some are remaining:

```
Running org.apache.nifi.processors.kite.TestAvroRecordConverter
Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.377 sec <<< FAILURE! - in org.apache.nifi.processors.kite.TestAvroRecordConverter
testDefaultConversion(org.apache.nifi.processors.kite.TestAvroRecordConverter)  Time elapsed: 0.011 sec  <<< ERROR!
org.apache.nifi.processors.kite.AvroRecordConverter$AvroConversionException: Cannot convert 5.5 to double
        at org.apache.nifi.processors.kite.AvroRecordConverter.convertData(AvroRecordConverter.java:246)
        at org.apache.nifi.processors.kite.AvroRecordConverter.convert(AvroRecordConverter.java:170)
        at org.apache.nifi.processors.kite.TestAvroRecordConverter.testDefaultConversion(TestAvroRecordConverter.java:98)

Running org.apache.nifi.processors.kite.TestConfigurationProperty
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.849 sec - in org.apache.nifi.processors.kite.TestConfigurationProperty
Running org.apache.nifi.processors.kite.TestConvertAvroSchema
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.22 sec <<< FAILURE! - in org.apache.nifi.processors.kite.TestConvertAvroSchema
testBasicConversion(org.apache.nifi.processors.kite.TestConvertAvroSchema)  Time elapsed: 0.21 sec  <<< FAILURE!
java.lang.AssertionError: Should convert 2 rows expected:<2> but was:<1>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.apache.nifi.processors.kite.TestConvertAvroSchema.testBasicConversion(TestConvertAvroSchema.java:78)
```

**Comment by trkurc** [comment]
@pvillard31 - I was able to replicate the errors in the txt file you included by adding \r's to the file (windows line endings). The other errors are on tests that haven't changed in this PR, but I can dig in.

**Comment by pvillard31** [comment]
@trkurc I am currently checking on my side why the other unit tests are in failure. But as you said, this is not related to this PR, so it is OK for me.

**Comment by pvillard31** [comment]
Just for the record, the error is because of my local env. This is fixed by setting the locale to US on the scanner:

`scanner.useLocale(java.util.Locale.US);`

I don't know if there is a way to set this at a global scale.

**Comment by joewitt** [comment]
hmm good find @pvillard31  We need to make the code more locale tolerant apparently.

**Comment by trkurc** [comment]
So, likely needs a processor change to add a default locale and some ability to override it

**Pull request closed without merging**
