### PR TITLE
NIFI-6379: Added SSL context to PutSNS, DeleteSQS, GetSQS, and PutSQS

### PR DESCRIPTION
**Pull request by Freedom9339**
# Summary

[NIFI-6379](https://issues.apache.org/jira/browse/NIFI-6379) - Added SSL Context Service  to PutSNS, DeleteSQS, GetSQS, and PutSQS. 

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X] Pull Request based on current revision of the `main` branch
- [X] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [X] Build completed using `mvn clean install -P contrib-check`
  - [X] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [X] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for the contribution @Freedom9339.

Adding support for custom SSL Context Service configuration requires more than adding the property itself. It is also required to update the build client build process to retrieve the SSLContext and plug it into the client for runtime usage.

This feature is not generally necessary because AWS SQS services have certificates signed by standard authorities, although it can be useful in some environments with restricted outbound network configurations.

If you are planning on working through the implementation details, this could be evaluated, but it will not work as it stands.

**Comment by Freedom9339** [comment]
@exceptionfactory 

Thank you for the review. The SSL_CONTEXT_SERVICE property lives in AbstractAWSProcessor and can be used by any processor that uses it. The SSL context is added to the client here:

https://github.com/apache/nifi/blob/129130fc0966fee6dfcf8fa514841ebc07045579/nifi-nar-bundles/nifi-aws-bundle/nifi-aws-abstract-processors/src/main/java/org/apache/nifi/processors/aws/v2/AbstractAwsProcessor.java#L318C9-L326C10

I have tested this using a custom truststore and keystore and the processors do use them when it is set.

**Comment by exceptionfactory** [comment]
Thanks for the reply and reference @Freedom9339. My apologies, I missed the fact the the class hierarchy now integrates the SSL Context Service when building the HTTP Client for the appropriate Client Builder.

With that understanding, it looks like this is ready to go forward. Thanks again for the helpful reply!

**Comment by Freedom9339** [comment]
@exceptionfactory 

Thank You! Do you mind setting the requested changes as approved?

**Review by exceptionfactory — APPROVED** [review]
Thanks again @Freedom9339! +1 merging

**Pull request closed without merging**
