### PR TITLE
NIFI-5319 Utilize NiFi Registry 0.2.0 client

### PR DESCRIPTION
**Pull request by bbende**
NOTE: This should only be merged after the NiFi Registry 0.2.0 release is complete and the 0.2.0 artifacts are available in Maven central.

### CODE REVIEW

**Comment by ottobackwards** [comment]
I think you have the wrong jira

**Comment by bbende** [comment]
@ottobackwards thanks, i mixed up the numbers, will force push with the correct commit message

**Comment by ottobackwards** [comment]
Np, I am watching 5319 and got excited for a minute ;)

**Comment by alopresto** [comment]
Reviewing...

**Comment by alopresto** [comment]
Verified against NiFi Registry 0.2.0 (RC1). Ran `contrib-check` and all tests pass. +1, merging.

**Pull request closed without merging**
