### PR TITLE
NIFI-11540 Remove legacy FlowFile attributes

### PR DESCRIPTION
**Pull request by jbalchan**
# Summary

[NIFI-11540](https://issues.apache.org/jira/browse/NIFI-11540)
The following attributes were replaced and only maintained for backwards compatibility. As part of removing technical debt in the 2.0 release, we should no longer support them.

segment.identifier
segment.index
segment.count
They were replaced by identical fragment.identifier, fragment.index and fragment.count.
Hence, Removing them in MergeContent and SegmentContent, their processor documentation and their unit tests.

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 11
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for the contribution @jbalchan.

Please run a local build prior to submitting a pull request to avoid known failures. The current pull request fails on all platforms due to the removal of `preprocessFlowFile`, so the approach needs further changes. The method might not be necessary, but other references need to be adjusted.

**Comment by jbalchan** [comment]
@exceptionfactory , Sure. I'll first fix those on local and push the changes after the local build is successful.

**Comment by mosermw** [comment]
Your additional commit looks good to me @exceptionfactory

**Comment by exceptionfactory** [comment]
> Your additional commit looks good to me @exceptionfactory

Thanks @mosermw! With that confirmation, I will proceed to merge soon.

**Review by exceptionfactory — APPROVED** [review]

**Pull request closed without merging**
