### PR TITLE
NIFI-7410 Fix CLOB would be unreadable code in ExecuteSql or QueryDataBaseTable

### PR DESCRIPTION
**Pull request by KuKuDeCheng**
https://issues.apache.org/jira/browse/NIFI-7410

#### Description of PR

fixes bug NIFI-7410 

when ExecuteSql or QueryDataBaseTable processor trigger below code in JdbcCommon.java ,clob would be unreadable code（with Chinese character）,because it used
`InputStream is = clob.getAsciiStream();` and ` rec.put(i - 1, new String(buffer));`

Update JdbcCommon.java when javaSqlType is CLOB or NCLOB in convertToAvroStream method, use the DataTypeUtils.toString(clob/nClob,(String) null, StandardCharsets.UTF_8)) method to get the String

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ √] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ √] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ √] Has your PR been rebased against the latest commit within the target branch (typically `master`)?

- [√ ] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ √] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ √] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on both JDK 8 and JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by mattyb149** [comment]
Is there a way to add a unit test for this? Maybe inserting Chinese characters into a Derby table with a CLOB column and reading the results?

**Comment by KuKuDeCheng** [comment]
> Is there a way to add a unit test for this? Maybe inserting Chinese characters into a Derby table with a CLOB column and reading the results?

Thanks for reply. I will add a unit test for this situation.

**Comment by KuKuDeCheng** [comment]
> Is there a way to add a unit test for this? Maybe inserting Chinese characters into a Derby table with a CLOB column and reading the results?

Hi @mattyb149 I have added one unit test.Clould you help me to check the PR of the `NIFI-7403 - PutSQL's transactions support #4239` if you have time? Thanks.

**Comment by pvillard31** [comment]
Hey @mattyb149 - does it look good to you?

**Comment by pvillard31** [comment]
Manually fixed the checkstyle violations and added the license to make the RAT check happy. Merging to main. Thanks @KuKuDeCheng (next time, please make sure to add the header and check the build with ``-Pcontrib-check``)

**Pull request closed without merging**
