### PR TITLE
NIFI-8297: Report incompatible value if it doesn't fit in an Integer

### PR DESCRIPTION
**Pull request by mattyb149**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

isIntegerCompatible() was letting "too large" values be compatible with integers. This causes downstream issues when the value is to be written as an integer (i.e. if the schema is inferred to be of Integer type rather than Long, etc.).

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [x] Have you written or updated unit tests to verify your changes?
- [x] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by gutosantos82** [comment]
I'm having a similar problem, but I believe Nifi is incorrectly assuming the table schema.
Nifi is using the column type from the column just before (n-1) to validate the value with the column type.
In this case, the column is varchar and the column just before is smallint.
Nifi accuses error because it can't cast "1x/dia" to short.
By changing the type of column n-1 the problem solves.

Do you think these two issues are related? Thanks.

------- Nifi version -----------
Nifi 1.13.0
02/10/2021 19:15:44 BRT
Tagged nifi-1.13.0-RC4
From 3bc6a12 on branch UNKNOWN

------ JDBC PostgreSQL Version ----
42.2.19


------------------- Nifi Interface Bulletin  ----------------
18:54:55 BRT ERROR
PutDatabaseRecord[id=2d23c61d-bfe8-351a-d7e5-84332341d827] Failed to put Records to database for StandardFlowFileRecord[uuid=2cbcd514-b0a5-4de7-b19d-79fa4891d39b,claim=StandardContentClaim [resourceClaim=StandardResourceClaim[id=1615382414416-4, container=default, section=4], offset=18303, length=980],offset=0,name=2cbcd514-b0a5-4de7-b19d-79fa4891d39b,size=718]. Routing to failure.: For input string: "1x/dia"
 
----------------- Nifi logs/nifi-app.log ------------------------

2021-03-10 18:54:55,175 ERROR [Timer-Driven Process Thread-7] o.a.n.p.standard.PutDatabaseRecord PutDatabaseRecord[id=2d23c61d-bfe8-351a-d7e5-84332341d827] Failed to put Records to database for StandardFlowFileRecord[uuid=2cbcd514-b0a5-4de7-b19d-79fa4891d39b,claim=StandardContentClaim [resourceClaim=StandardResourceClaim[id=1615382414416-4, container=default, section=4], offset=18303, length=980],offset=0,name=2cbcd514-b0a5-4de7-b19d-79fa4891d39b,size=718]. Routing to failure.: java.lang.NumberFormatException: For input string: "1x/dia"
java.lang.NumberFormatException: For input string: "1x/dia"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Short.parseShort(Short.java:118)
	at java.lang.Short.parseShort(Short.java:144)
	at org.apache.nifi.serialization.record.util.DataTypeUtils.toShort(DataTypeUtils.java:1614)
	at org.apache.nifi.serialization.record.util.DataTypeUtils.convertType(DataTypeUtils.java:203)
	at org.apache.nifi.serialization.record.util.DataTypeUtils.convertType(DataTypeUtils.java:152)
	at org.apache.nifi.serialization.record.util.DataTypeUtils.convertType(DataTypeUtils.java:148)
	at org.apache.nifi.processors.standard.PutDatabaseRecord.executeDML(PutDatabaseRecord.java:707)
	at org.apache.nifi.processors.standard.PutDatabaseRecord.putToDatabase(PutDatabaseRecord.java:838)
	at org.apache.nifi.processors.standard.PutDatabaseRecord.onTrigger(PutDatabaseRecord.java:487)
	at org.apache.nifi.processor.AbstractProcessor.onTrigger(AbstractProcessor.java:27)
	at org.apache.nifi.controller.StandardProcessorNode.onTrigger(StandardProcessorNode.java:1173)
	at org.apache.nifi.controller.tasks.ConnectableTask.invoke(ConnectableTask.java:214)
	at org.apache.nifi.controller.scheduling.TimerDrivenSchedulingAgent$1.run(TimerDrivenSchedulingAgent.java:117)
	at org.apache.nifi.engine.FlowEngine$2.run(FlowEngine.java:110)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mattyb149** [comment]
@gutosantos82 That's probably a separate issue, please feel free to open a Jira and include all relevant details (CREATE TABLE statement, sample input, etc.)

**Review by pvillard31 — APPROVED** [review]

**Comment by pvillard31** [comment]
Merged to main, thanks @mattyb149 
@gutosantos82 - I agree with Matt, it sounds to be something different, can you file a JIRA and provide any information you can relative to the error?

**Comment by gutosantos82** [comment]
Ok, I will do that. Thanks

**Pull request closed without merging**
