### PR TITLE
NIFI-13490 bumped aws, gcp, fabric8

### PR DESCRIPTION
**Pull request by joewitt**
com.amazonaws 1.12.748 1.12.755
com.google libraries-bom 26.40.0 26.42.0
io.fabric8 6.13.0 6.13.1
org.apache.groovy 4.0.21 4.0.22
org.apache.lucene 9.11.0 9.11.1
org.checkerframework 3.44.0 3.45.0
org.junit.jupiter 5.10.2 5.10.3
org.junit.platform 1.10.2 1.10.3
org.junit.vintage 5.10.2 5.10.3
org.mockito 5.11.0 5.12.0
software.amazon.awssdk 2.26.8 2.26.14
com.slack.api 1.40.0 1.40.2
org.apache.iotdb 1.3.1 1.3.2
org.apache.kafka 3.7.0 3.7.1
org.flywaydb 10.15.0 1.15.2
org.neo4j.driver 5.21.0 5.22.0

# Summary

[NIFI-13490](https://issues.apache.org/jira/browse/NIFI-13490)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by joewitt** [comment]
not sure why dep thing failed but i think unrelated to this PR.  Local builds and dep runs are fine.

**Comment by exceptionfactory** [comment]
> not sure why dep thing failed but i think unrelated to this PR. Local builds and dep runs are fine.

The dependency check fails due the time required for uncached retrieval of NVD information. I will evaluate removing this from the pull request workflow for now in a separate issue.

**Review by exceptionfactory — APPROVED** [review]
Thanks for the upgrades @joewitt, looks good! +1 merging

**Comment by exceptionfactory** [comment]
Merged in https://github.com/apache/nifi/commit/5f2ae3db3d8757d5c445940d8a0032aeffecd0f3

**Pull request closed without merging**
