### PR TITLE
NIFI-11177: Add defensive code for null values for Iceberg

### PR DESCRIPTION
**Pull request by mattyb149**
# Summary
[NIFI-11177](https://issues.apache.org/jira/browse/NIFI-11177) This PR adds defensive checks to return null values when any conversions occur

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [x] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by mark-bathori — COMMENTED** [review]
Thanks @mattyb149 for fixing this null handling issue. Since every converter needs a null check in the `convert(Object data)` method I think it would be a better solution to add this null check in a new method in the `DataConverter<S, T>` abstract class and then this would call to the `convert` method. With this change we don't need to add the same null check to every implementation.

**Comment by mattyb149** [comment]
This should work since the top-level `convert()` is for each RecordField in the Record, but shouldn't we have the null checks in the individual `convert()s` too just in case `convert()` is called directly from somewhere else? Or do we trust in having the Record/Map/Array converters call the new method (I'm calling it `convertWithNullCheck()`)?

**Review by mark-bathori — APPROVED** [review]
It shouldn't be called from other places but of course it could happen. I'm fine with the current solution also.
LGTM +1

**Comment by mattyb149** [comment]
I'll push a commit with the new method and change the complex types to call that, just for safety :)

**Comment by mark-bathori** [comment]
I think the last commit is not needed since the original solution contains null check in every `convert` implementation, so we have 2 options here:

1. Add null check in every `convert` method implementation, so the `convertWithNullCheck` is not needed.
2. Use the `convertWithNullCheck`, make the original `convert` method private and remove the null checks from the implementations.

**Comment by mark-bathori** [comment]
I think the last commit is not needed since the original solution contains null check in every `convert` implementation. The only issue could be if a new implementation would be added without a null check but it is very unlikely.

**Review by pvillard31 — APPROVED** [review]

**Pull request closed without merging**
