### PR TITLE
NIFI-13566 Catch Throwable during JettyServer start to ensure any iss…

### PR DESCRIPTION
**Pull request by bbende**
…ue during start will exit

# Summary

[NIFI-13566](https://issues.apache.org/jira/browse/NIFI-13566)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X] Pull Request based on current revision of the `main` branch
- [X] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by joewitt** [comment]
@bbende What type of exception/Errors were getting through?  Out of memory exceptions would do it...

**Comment by bbende** [comment]
@joewitt in this case it was `ClassNotFoundError` and it left NiFi in a very strange state where the Java process was running and you could even get into the canvas, but trying to add a processor produce some stranger exception. In this case the `ClassNotFoundError` came from `DocGenerator.generate` in the middle of the start method.

**Comment by joewitt** [comment]
ahh perfect - thanks

**Comment by mattyb149** [comment]
+1 LGTM, thanks for the improvement! Merging to support/nifi-1.x and main

**Pull request closed without merging**
