### PR TITLE
[NIFI-3015] Run NiFi service from nifi user instead of root

### PR DESCRIPTION
**Pull request by fidget83**
When install NiFi using command nifi.sh install, NiFi will start from user root.
I suggest to run it from user nifi which is created during rpm installation.

### CODE REVIEW

**Comment by trixpan** [comment]
Have you configured bootstrap after install? The runas setting is where this logic happens, not within the init script

**Comment by jfrazee** [comment]
@fidget83 I think the right thing is to find some way to update the run.as setting, as @trixpan mentions, from the rpm since we know the nifi user exists then and fold that into the rpm spec. Right now, `nifi.sh install` can and does get used on non-RedHat derived platforms without rpms and in tarball installs so there's no guarantee the user exists. It's a good change if done right though.

**Comment by trixpan** [comment]
@jfrazee - odd. Should the bootstrap.conf `run.as`  be [populated](https://github.com/apache/nifi/blob/d838f61291d2582592754a37314911b701c6891b/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-resources/src/main/resources/conf/bootstrap.conf) from the [RPM profile](https://github.com/apache/nifi/blame/92f17a995b7c6b7aaaa63a55974fffda00780c56/nifi-assembly/pom.xml#L429) already?

**Comment by trixpan** [comment]
Found the reason:

https://github.com/apache/nifi/blob/master/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-resources/pom.xml#L30

**Comment by joewitt** [comment]
@fidget83 thank you for the contribution.  It looks as though the desired behavior is now addressed by @trixpan patch.  If you agree can you close this PR?  Thanks!

**Pull request closed without merging**
