### PR TITLE
Addressing issues surrounding Template uploading

### PR DESCRIPTION
**Pull request by mcgilman**
NIFI-2224:
- Ensuring the template form is reset when the upload template dialog is closed.

NIFI-2175:
- Not submitting the template form is a template isn't choosen.

NIFI-2176:
- Ensuring a template is specified during creation.

NIFI-2223:
- Ensuring templates with the same name cannot be added.

NIFI-2296:
- Updating the tooltip for the upload template browse button.

- Cleaning up un-used parameters to REST endpoints.

### CODE REVIEW

**Comment by JPercivall** [comment]
3 node secure cluster testing NIFI-2223, I see "conflict" and not "A template named 'XYZ' already exists."

screen shot 2016-07-27 at 2 17 59 pm

**Comment by JPercivall** [comment]
Empty name template checking appears to only occur as a server side check. This would be a simple client side check to add and would be a nice UX addition.

**Comment by mcgilman** [comment]
Good catch and great suggestion. I've updated the PR accordingly. Thanks!

**Comment by JPercivall** [comment]
+1

Visually verified code and did a contrib check build. In both standalone and 3 node secure cluster, I tested all 5 situations and various other checks relating to templates. Thanks @mcgilman, I will merge it in.

**Pull request closed without merging**
