### PR TITLE
[NIFI-3439] when users type into sensitive property fields in NiFI, t…

### PR DESCRIPTION
**Pull request by scottyaslan**
…he values on the screen/browser should be masked *** unless specified by user to show plain text.

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by mcgilman** [comment]
Will review...

**Comment by mcgilman** [comment]
Hey @scottyaslan,

This is a great start, but I think there are a few fundamental issues with how `PropertyDescriptors` relay what sort of editor should be used. There does not appear to be a cross-browser support for masking `textareas` (multi-line input). There exists sensitive properties that currently expect the field to support multi-line input. The `input[type=password]` only supports a single line.

I think we would need to introduce a new attribute of `PropetyDescriptor` which would drive whether or not to use a masked single line input or the existing multi-line `textarea`. The existing multi-line `textareas` support sensitive by not returning/showing the value once set. We would not be able to support a `PropertyDescriptor` that requires masking and multi-line input.

Additional complications exist for sensitive properties that support expression language. We'd have to spend some time to determine if `CodeMirror` supports masking or if it's possible to introduce that sort of capability. If not, we would not be able to support a `PropertyDescriptor` that requires masking and supports expression language.

**Comment by trixpan** [comment]
@scottyaslan - have you tested this?

http://jsfiddle.net/Ldr07h2r/6/

Source:
http://stackoverflow.com/questions/25822682/webkit-text-security-compatibility

**Comment by trixpan** [comment]
The approach linked above seems to work on chrome without the javascript but firefox required the js code.

**Comment by trixpan** [comment]
forget it. Seen what @mcgilman was referring to. Possible to play with text area but it becomes single line. :-(

**Comment by Ramakrishnan-V** [comment]
Hi @mcgilman,

I strongly agree on your point that need to introduce new attribute of PropetyDescriptor which would drive whether or not to use a masked single line input or the existing multi-line textarea. Our focus is only on properties that require user to enter password. All sensitive properties need not be a password property. And password properties are supposed to be single line and should not support expression-language. (Also i believe password boxes cannot be created without <input type="password">)

**Pull request closed without merging**
