### PR TITLE
NIFI-4980: Typo in ReportAtlasLineage kafka kerberos service name pro…

### PR DESCRIPTION
**Pull request by ijokarumawak**
…perty

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by pvillard31** [comment]
Hey @ijokarumawak, I'm a bit concerned by this change since this code has already been released in NiFi 1.5.0. I believe that changing the name() of this property could be a breaking change for people already using the reporting task, no?

**Comment by ijokarumawak** [comment]
@pvillard31 Yes, it's a breaking change. I wrote a comment on the JIRA.
https://issues.apache.org/jira/browse/NIFI-4980?focusedCommentId=16400035&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16400035

Should we implement some migration code? I was concerning about that, too, but didn't want to make it to complex for this little change..

**Comment by pvillard31** [comment]
Agree that's an overkill... What do you think @joewitt? Since you seem to be the next RM for NiFi 1.6.0, it could be enough to mention it in the release note?

**Comment by ijokarumawak** [comment]
@pvillard31 @MikeThomsen I thought adding backward compatibility would make it complex, but it was not that much than I thought if I tried.

I added another commit to add few more lines of code to support migration from old property to the new renamed one. It lets user to keep the reporting task running using the old configuration until they remove the old property.

I think this approach will guide users to the right direction better than providing migration guide in release note. Thanks!

**Comment by MikeThomsen** [comment]
@ijokarumawak I say we just go ahead and merge a breaking change here. Atlas is not even at a stable 1.0 release, so anyone using it should be prepared for a few bumps as things get ironed out. If you want me to pare down the commit, let me know. I have some free time today.

**Comment by ijokarumawak** [comment]
Thank you @mattyb149 @MikeThomsen for your comments. I agree with that. @MikeThomsen would you cherry-pick only the 1st commit into master branch?

**Comment by MikeThomsen** [comment]
Done.

**Comment by MikeThomsen** [comment]
@ijokarumawak you can also reach out to @dmkoster for reviews on Atlas.

**Pull request closed without merging**
