### PR TITLE
[NIFI-1394] - Unit test creates resources in HOME directory

### PR DESCRIPTION
**Pull request by smarthi**
Changed to create a TemporaryFolder.

### CODE REVIEW

**Comment by mattyb149** [comment]
I agree that the file should not be created relative to the HOME directory, but can we use something relative to the local target/ directory instead of an absolute path?

**Comment by vincentrussell** [comment]
You should use:

@Rule
    public TemporaryFolder testFolder = new TemporaryFolder();

**Comment by smarthi** [comment]
@mattyb149 I think the reason it had an absolute path was due to the below error from the H2 driver:

org.h2.jdbc.JdbcSQLException: A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:file:target/db/testdb7". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-187]

**Comment by mcgilman** [comment]
Build looks good. No more artifacts showing up in user home directory. Thanks!

**Comment by smarthi** [comment]
Thanks for merging this PR. Do we similarly modify all of the other TestJdbc* to take a TemporaryFolder ?

**Comment by mcgilman** [comment]
I wasn't aware of any issues with the other JDBC tests. This JIRA was created to specifically address the tests resources being created in the user's HOME directory. If there are any issues with the other tests we should address those as well with a separate ticket. Thanks again for the contribution!

**Pull request closed without merging**
