### PR TITLE
Ensuring all component specific policies are removed when the component is deleted

### PR DESCRIPTION
**Pull request by mcgilman**
NIFI-2301:
- Ensure all component specific policies are removed when the component is removed.

### CODE REVIEW

**Comment by JPercivall** [comment]
Reviewing

**Comment by JPercivall** [comment]
I believe there is the unintended consequence of preventing deleting multiple components at a time that I have write permissions but no view permissions. To recreated:

Multiple different components without view permission but write permission
select 2 or more and attempt to delete
See pop-up saying your denied
try to delete them individually and succeed

screen shot 2016-08-03 at 11 01 09 am

**Comment by mcgilman** [comment]
Great catch @JPercivall. I've updated the PR to address the comments. Thanks!

**Comment by JPercivall** [comment]
Sorry for not noticing this earlier but it appears that encapsulated components (processors, controller services, etc.) inside a process group that gets deleted do not have their associated policies deleted too.

Also I believe there is a small oversight with the UI in regards to CS and RT, when you have "write" but not "view" the button for deleting a CS or RT does not appear. Probably a super simple fix if you wanted to add it.

**Comment by mcgilman** [comment]
Another good catch. I've updated the PR accordingly. Thanks!

**Comment by JPercivall** [comment]
@mcgilman I don't think the UI button to delete the CS/RT works properly. When I tried to use it when I had "write" but not "view" I saw a 405.

screen shot 2016-08-03 at 4 17 16 pm

**Comment by mcgilman** [comment]
Thanks @JPercivall. PR updating accordingly.

**Comment by JPercivall** [comment]
+1

Visually verified code and did a contrib check build. In a 3 node secure cluster tried adding and modifying policies for every component and then deleting each. Saw policies removed as components were deleted as expected. Thanks @mcgilman, I will merge it in.

**Pull request closed without merging**
