### PR TITLE
NIFI-6425 Made executeQuery able to reconnect to the Gremlin cluster.

### PR DESCRIPTION
**Pull request by MikeThomsen**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Enables X functionality; fixes bug NIFI-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?

- [ ] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by MikeThomsen** [comment]
Testing is simple:

1. Setup ExecuteGraphQuery against JanusGraph 0.3.2.
2. Run a query. Ex: `g.V().count().next()`
3. Stop the processor.
4. Restart JanusGraph.
5. Verify that it starts querying again without having to disable and reenable the client service.

**Comment by MikeThomsen** [comment]
@mattyb149 did you get a chance to review this?

**Comment by mattyb149** [comment]
I tried the reproduction path but when I restart the processor (without restarting the service), the query times out.

**Comment by MikeThomsen** [comment]
Looking back at that, the instructions were bad.

This is what should happen:

1. Load up some queries.
2. Shutdown and restart Janus as they're running.
3. The service should reconnect to Janus and be able to start processing again without having to be restarted.

**Comment by mattyb149** [comment]
I tried once with stopping the processor, restarting Janus, then restarting the processor, and I also tried leaving the processor running while restarting Janus (I did a restart of the Docker container from the Kitematic UI). Neither scenario caused the original error, but both scenarios eventually failed due to a connection timeout. I'll try to queue up some queries, are they supposed to queue up on the Janus side (it gets a new one while still executing the last one) or the NiFi side (flowfile queue and/or scheduling ExecuteGraphQuery to run a little slower)?

**Comment by MikeThomsen** [comment]
What I was seeing before this patch was that once the connection is broken, the Gremlin API wasn't attempting a reconnect before throwing an exception. So any flowfile sent would be reflexively sent to failure for having no connection to Janus.

**Comment by mattyb149** [comment]
Looks like it was just taking Janus a couple minutes to recuperate from the restart, I kept a stream of queries going into ExecuteGraphQuery and eventually (1-2 mins) they started going to success (without restarting the service). I tried the two scenarios again but just let them run a while longer and everything eventually got back to normal.

**Comment by mattyb149** [comment]
+1 LGTM, reproduced the error and verified that this PR fixes it (i.e. the Graph CS doesn't need to be restarted for the processor to reconnect). Thanks for the improvement! Merging to master

**Pull request closed without merging**
