### PR TITLE
NIFI-12493 Update Documentation References to Java 21

### PR DESCRIPTION
**Pull request by exceptionfactory**
# Summary

[NIFI-12493](https://issues.apache.org/jira/browse/NIFI-12493) Updates documentation references to indicate that Java 21 is the minimum required version. Additional changes include removing the need to download Apache Maven and instead referencing the Apache Maven Wrapper command.

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X] Pull Request based on current revision of the `main` branch
- [X] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by EndzeitBegins** [comment]
Looks good to me. 
I followed all the changed links and they're still working. 

If found some other places in the codebase where older Java versions are mentioned. Maybe we want to update those places as well. However, I'm not sure 21 is required there as well. 

- [ ] [README.md of nifi-assembly](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/nifi-assembly/README.md?plain=1#L71)
- [ ] [README.md of minify-assembly](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/minifi/minifi-assembly/README.md?plain=1#L42)
- [ ] [README.md of minify-c2-assembly](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/minifi/minifi-c2/minifi-c2-assembly/README.md?plain=1#L29)
- [ ] [Admin guide of NiFi registry](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/nifi-registry/nifi-registry-core/nifi-registry-docs/src/main/asciidoc/administration-guide.adoc#L26)
- [ ] [Admin guide of minify](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/minifi/minifi-docs/src/main/markdown/System_Admin_Guide.md?plain=1#L385)
- [ ] [README.md of nifi-registry-assembly](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/nifi-registry/nifi-registry-assembly/README.md?plain=1#L28)
- [ ] [NiFi in depth contains a keytool example using Java 1.8](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/nifi-docs/src/main/asciidoc/nifi-in-depth.adoc#L116)
- [ ] [README.md of nifi-registry-web-api](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/nifi-registry/nifi-registry-core/nifi-registry-web-api/src/test/resources/keys/README.md?plain=1#L63)

I also found some code places with workarounds to be compatible with older Java versions. I think some of those could be removed now, though may be out of scope for this ticket / PR.
- [ ] [AllowListClassLoader](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/nifi-stateless/nifi-stateless-bootstrap/src/main/java/org/apache/nifi/stateless/bootstrap/AllowListClassLoader.java#L105)
- [ ] [KeyStoreUtilsTest](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/nifi-commons/nifi-security-utils/src/test/java/org/apache/nifi/security/util/KeyStoreUtilsTest.java#L184)

**Comment by exceptionfactory** [comment]
Thanks for the helpful pointers to additional references @EndzeitBegins! I pushed a change updating references to Java 21, and in a couple comments, removed version numbers as it was not necessary.

That's also a good point regarding those class references. There are probably other similar types of things, and it would be useful to address those in a separate pull request that covers general minor changes for workarounds that are no longer necessary.

**Comment by EndzeitBegins** [comment]
Looks good. Thanks for incorporating the additional adjustments. 👍🏻

**Comment by dan-s1** [comment]
@exceptionfactory I have found 2 comments in files which reference Java 1.8
`nifi-commons/nifi-security-utils/src/test/java/org/apache/nifi/security/util/KeyStoreUtilsTest.java` on line 184

> // Select Key Protection Algorithm for PKCS12 to avoid unsupported algorithm on Java 1.8.0.292

and

`nifi-stateless/nifi-stateless-bootstrap/src/main/java/org/apache/nifi/stateless/bootstrap/AllowListClassLoader.java` lines 102-105

> // If the class has a module whose name is allowed, allow it.
>  // The module is obtained by calling Class.getModule(). However, that method is only available in Java 9.
>  // Since this codebase must be Java 8 compatible we can't make that method call. So we use Reflection to determine
>  // if the getModule method exists (which it will for Java 9+ but not Java 1.8), and if so get the name of the module.

Do these comments make sense anymore if this branch only supports Java 21?

**Comment by dan-s1** [comment]
@exceptionfactory The following are other places I found JDK versions other than 21 mentioned:

- [StandardALPNProcessor](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/nifi-commons/nifi-jetty-configuration/src/main/java/org/apache/nifi/jetty/configuration/connector/alpn/StandardALPNProcessor.java#L33)
- [StringUtils](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/nifi-commons/nifi-property-utils/src/main/java/org/apache/nifi/util/StringUtils.java#L388)
- [EnforceOrder](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/EnforceOrder.java#L419-L421)
- [TestDataTypeUtils](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/nifi-commons/nifi-record/src/test/java/org/apache/nifi/serialization/record/TestDataTypeUtils.java#L104-L105)
- [TestNiFiRecordSerDe](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/nifi-nar-bundles/nifi-hive-bundle/nifi-hive3-processors/src/test/java/org/apache/hive/streaming/TestNiFiRecordSerDe.java#L48)
- [TestPutHive3Streaming](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/nifi-nar-bundles/nifi-hive-bundle/nifi-hive3-processors/src/test/java/org/apache/nifi/processors/hive/TestPutHive3Streaming.java#L126)
-

**Comment by exceptionfactory** [comment]
> @exceptionfactory The following are other places in the code I found JDK versions other than 21 mentioned:
> 
>     * [StandardALPNProcessor](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/nifi-commons/nifi-jetty-configuration/src/main/java/org/apache/nifi/jetty/configuration/connector/alpn/StandardALPNProcessor.java#L33)
> 
>     * [StringUtils](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/nifi-commons/nifi-property-utils/src/main/java/org/apache/nifi/util/StringUtils.java#L388)
> 
>     * [EnforceOrder](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/EnforceOrder.java#L419-L421)
> 
>     * [TestDataTypeUtils](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/nifi-commons/nifi-record/src/test/java/org/apache/nifi/serialization/record/TestDataTypeUtils.java#L104-L105)
> 
>     * [TestNiFiRecordSerDe](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/nifi-nar-bundles/nifi-hive-bundle/nifi-hive3-processors/src/test/java/org/apache/hive/streaming/TestNiFiRecordSerDe.java#L48)
> 
>     * [TestPutHive3Streaming](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/nifi-nar-bundles/nifi-hive-bundle/nifi-hive3-processors/src/test/java/org/apache/nifi/processors/hive/TestPutHive3Streaming.java#L126)

@dan-s1 Those code references are for different types of issues. Some of them can be changed, but that should be covered separately. For example, the StandardALPNProcessor is something that will go away with some subsequent upgrades to new Jetty versions. The TestDataTypeUtils is a reference to NiFi 1.8, not Java 1.8. From that perspective, these items are worth noting, but it appears better to handle them on a case-by-case basis.

**Comment by dan-s1** [comment]
@exceptionfactory Thanks for clarifying those. Here a few more to consider

- [StandardProcessSession](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/controller/repository/StandardProcessSession.java#L972-L974)
- [ParseCEF](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ParseCEF.java#L97)
- [pom.xml](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/pom.xml#L1003)
- [pom.xml](https://github.com/apache/nifi/blob/f73888e7dd4b0df37f5845bc318a7ad85f22d75d/pom.xml#L1302)

**Comment by exceptionfactory** [comment]
Thanks @dan-s1. All of these are worth noting, but fall outside of the intended scope of Documentation References for this particular pull request. Anything that requires code changes probably needs to be more targeted, such as DateTimeFormatter for instance. So for these issues, there may be existing Jira tickets, but if not, it may be worth writing up some of them for tracking.

**Review by bbende — APPROVED** [review]
Looks good!

**Pull request merged**
