### PR TITLE
NIFI-12099 Repurpose Template icon in top left bar

### PR DESCRIPTION
**Pull request by elcsiga**
# Summary

[NIFI-12099](https://issues.apache.org/jira/browse/NIFI-12099)

https://github.com/apache/nifi/assets/1295926/364ef977-26b8-4eaf-ae19-29ed32ef2dc7

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [x] Build completed using `mvn clean install -P contrib-check`
  - [x] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by sardell** [comment]
It looks like the draggable icons are no longer centered in their container, which is more obvious when hovering over an icon.

Before your changes:

before

After:
after

**Comment by rfellows** [comment]
reviewing...

**Comment by rfellows** [comment]
This is good and works pretty well. The only improvement I could recommend would be to refresh the `current-user` after configuring a registry client. As it stands now, we are relying on the background polling of the current-user endpoint to update the current user which is where it is determined if `canVersionFlows` is true or false. It is this property that determines if we show the `No Registry Client available` dialog or the `Import Version` dialog.
If you delete the registry client and then try to drag on a new import before the polling happens, you can be shown import dialog with no registries:
Screenshot 2023-10-18 at 3 35 34 PM

Similarly, if you do the same too soon after configuring a registry client, you can get a stale `No Registry Client available` dialog even though you have one configured.

Maybe @scottyaslan can provide some more insight into if this is consistent with other areas of the application.

**Comment by elcsiga** [comment]
@rfellows good point, now adding or removing a registry client also reloads `/current-user`

**Review by rfellows — APPROVED** [review]
Changes look good to me 👍 
Thanks @elcsiga

**Pull request merged**
