### PR TITLE
NIFI-3055 StandardRecordWriter Can Throw UTFDataFormatException (0.x)

### PR DESCRIPTION
**Pull request by jskora**
* Remove function based on JDK source.
* Add new function to find bytes based on RFC3629.
* Add field name to log entry when field is truncated.

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x ] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by mosermw** [comment]
Reviewed, along with #1475.  Licensing concern about the code looks to be resolved.   +1 will merge

**Comment by markap14** [comment]
@jskora not sure what's going on here, but it see a comment above that asfgit pushed a commit that indicates that it closes this PR. But this PR is still open. Can you close manually? Thanks!

**Comment by trixpan** [comment]
@markap14 I suspect the reason is @mosermw  added the closure after the signature and closure should come above sign-off-by?

**Comment by mosermw** [comment]
@trixpan the "This closes" commit hook doesn't work on the 0.x branch.

**Comment by trixpan** [comment]
@mosermw ohhh. wasn't aware of it. thanks for sharing

**Comment by jskora** [comment]
Closed by commit [4f72e34](https://git-wip-us.apache.org/repos/asf?p=nifi.git;a=commit;h=4f72e3491f2372c8c45afb96a765c1f5cdd2f07d).  Thanks @mosermw!

**Pull request closed without merging**
