### PR TITLE
NIFI-3653: Introduce ManagedAuthorizer

### PR DESCRIPTION
**Pull request by mcgilman**
NIFI-3653:
- Introducing UserGroup and Policy provider interfaces.
- Introducing FileUserGroupProvider and FileAccessPolicyProvider.
- Refactoring FileAuthorizer to utilize the file based implementations.
- Introducing the StandardManagedAuthorizer.
- Decorating the configured ManagedAuthorizer to ensure integrity checks are still performed.
- Loading user groups if possible to use during access decisions.
- Merging responses for requests for AccessPolicies, Users, and UserGroups.
- Adding unit tests as appropriate.

### CODE REVIEW

**Comment by bbende** [comment]
This looks cool, will review...

**Comment by pvillard31** [comment]
Thanks for this work @mcgilman ! Will give it a try as well!

**Comment by mcgilman** [comment]
I'll be posting another commit to this PR to more easily allow providers to map their users, groups, and policies to the internal data model. Also, have minor documentation and error message tweaks.

**Comment by mcgilman** [comment]
For those reviewing... just pushed a follow-up commit.

**Comment by bbende** [comment]
Thanks Matt, I've been testing this for the past two days and so far everything seems to be working well. I will take a look at the latest commit.

**Pull request closed without merging**
