### PR TITLE
NIFI-12161: While waiting for node to startup, time out after 5 minut…

### PR DESCRIPTION
**Pull request by markap14**
…es and throw an Exception

# Summary

[NIFI-00000](https://issues.apache.org/jira/browse/NIFI-00000)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by joewitt** [comment]
Should change the title of the PR and JIRA now given what this is finding...

**Comment by joewitt** [comment]
system tests ran successfully on linux.  running again for good measure as they never pass two times in a row :)

**Comment by exceptionfactory** [comment]
@markap14 Are you planning to keep the additional logging added, or remove some of it once the tests pass consistently?

**Comment by joewitt** [comment]
i closed my laptop before they finished so it timed out/closed.  but it was going well.  this seems much more stable

**Comment by markap14** [comment]
@joewitt thanks. I agree, I think the stability is significantly improved. @exceptionfactory I think the logging is helpful. I considered changing much of it to DEBUG. However, what we find is that when something does time out, it's often very often intermittent so changing the log level to DEBUG and then triggering it to happen again is generally not easy to accomplish and can take a huge amount of time. While most of the log levels would not be appropriate for a running application, I feel like INFO level log messages are fair for system tests to denote what it's waiting on. So I think it makes sense to keep the log levels as they are.

**Comment by exceptionfactory** [comment]
> @exceptionfactory I think the logging is helpful. I considered changing much of it to DEBUG. However, what we find is that when something does time out, it's often very often intermittent so changing the log level to DEBUG and then triggering it to happen again is generally not easy to accomplish and can take a huge amount of time. While most of the log levels would not be appropriate for a running application, I feel like INFO level log messages are fair for system tests to denote what it's waiting on. So I think it makes sense to keep the log levels as they are.

Thanks for the reply @markap14, on further review, I see the the logging statements are primarily in the test suite class, so more logging there makes sense for debugging.

**Pull request closed without merging**
