### PR TITLE
NIFI-4012 Azure Event Hub UI typos and cleanup

### PR DESCRIPTION
**Pull request by aperepel**
- use name and displayName consistently
- fixed user-facing typos
- extracted a common superclass for DRY

### CODE REVIEW

**Comment by pvillard31** [comment]
Hey @aperepel, unfortunately we cannot change the ``.name()`` on the existing (already released) code because the template would not be backward compatible anymore. You can definitely add the ``.displayName()`` to be more consistent but I fear we can't do much for a minor release.

**Comment by aperepel** [comment]
Which version did you have in mind, Pierre? I'd say the number of templates out there with the Azure event hub processor is negligible and the migration requirement could be pointed out in the release doc.

**Comment by pvillard31** [comment]
I agree with you that there should not be a lot of templates using this code at this time. But, even though we document the change, updating ``.name()`` is not required, it's not a fix. I'm totally fine with adding ``.displayName()`` to fix typos or improve unclear wording but we should not introduce anything breaking existing workflows on minor releases (as per our [dev guide](https://cwiki.apache.org/confluence/display/NIFI/Version+Scheme+and+API+Compatibility)).

**Comment by joewitt** [comment]
Technically we *can* change the name but unless there is a strong advantage to the user and/or the developer to justify it we should avoid it.  We've designed the system to tolerate such things but it requires the user to make changes.  Since this case is helping neither the dev or the user (it is a static var so no issue for dev) then it just simply isn't worth changing the name.  Go ahead and make the 'displayName' reflect what is appropriate but I recommend leaving the name as Pierre is advocating.

**Comment by ijokarumawak** [comment]
Closing this as #3749 has taken over fixing typos. Thanks @aperepel for initiating the fix!

**Pull request closed without merging**
