### PR TITLE
NIFI-10904 Changed the font color for drop down menus to avoid the app…

### PR DESCRIPTION
**Pull request by Freedom9339**
…earance of menu items being disabled

# Summary

[NIFI-00000](https://issues.apache.org/jira/browse/NIFI-00000) - Changed the font color for drop down menus in controller and processor properties. The current color gives the appearance that the drop down option is disabled.

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X] Pull Request based on current revision of the `main` branch
- [X] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [X] Build completed using `mvn clean install -P contrib-check`
  - [X] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for the contribution @Freedom9339!

The user interface has a large number of references to the `unset` CSS class, so this change would have a broader impact than just the drop-down menu items. For that reason, it may be necessary to introduce a new CSS class or use a different class to implement a more targeted adjustment.

**Comment by Freedom9339** [comment]
Thank you for your feedback @exceptionfactory. I've changed it to use .combo-option-text instead of .unset to set the color. This should only affect the color of drop down menu texts.

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
Thanks for the update @Freedom9339. Unfortunately this approach is also too broad because it changes the styles of all disabled elements. The best approach will involve a new style class that applies specifically to selectable options that are not disabled.

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
@Freedom9339 Sorry for the delay in reply. Unfortunately this change does not work either because the color property is not getting applied when rendering in the browser.

**Comment by Freedom9339** [comment]
@markobean Yes, that's what I expected it to be displayed. Thank You.

**Review by exceptionfactory — COMMENTED** [review]
@Freedom9339 and @markobean, I tested the change on Firefox 116 and confirmed that the new CSS is present, but it does not change the color. According to Web Developer Tools, the `color` style is not applied because the `unset` class takes precedence with its associated color. It appears that adding the `!important` flag to the color declaration could work.

On that note, however, it seems like it would still be helpful to distinguished the `Reference parameter...` and `Create Controller Service...` options from other options. Perhaps italicizing would be helpful as a way to differentiate these choices from other available options.

**Comment by mtien-apache** [comment]
I checked in Chrome and the `unset` class still takes precedence.

Screenshot 2023-08-25 at 6 38 37 PM

I wonder if we just need to remove the `unset` class. It seems like this class is used for disabled, unavailable, or sensitive items. Also not a bad idea to italicize `Reference parameter...` and `Create Controller Service...` options to help differentiate from other options.

**Comment by Freedom9339** [comment]
@mtien-apache Yea, so for those 2 cases, Reference parameter and Create Controller Service, the unset tag does take precedence, However, I thought this was intended for these 2 options, as well as any disabled options. If there are any other options, they will get the new tag and be colored black. I can remove the unset tag for these 2 options and italicize them. That way they will be colored black, but still be distinguishable from other non disabled options.

**Comment by mtien-apache** [comment]
@Freedom9339 Looks like the `unset` tag is initially added when the the option item is created, but should have probably been removed after verifying the option is valid. I don't think the new tag is necessary. If the `unset` tag is not present, then the text color will default to black.

**Review by mtien-apache — APPROVED** [review]
LGTM! Thanks for all the fixes. There are some CI build failures but it doesn't look like they're related to your work. Will merge soon.

**Pull request merged**
