### PR TITLE
NIFI-2624 JdbcCommon treats BigDecimals now as Avro Logical type usin…

### PR DESCRIPTION
**Pull request by ToivoAdams**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:
### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
   in the commit message?
- [ ] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?
- [ ] Is your initial contribution a single, squashed commit?
### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?
### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
### Note:

Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

…g bytes to hold data (not String as is was before).

### CODE REVIEW

**Comment by ijokarumawak** [comment]
Hi @ToivoAdams @trixpan 

I've encountered similar issue. So I've researched and tried to use Avro 1.8.1 LogicalTypes, without knowing there's an existing JIRA and PR to solve that, thanks for tackling this!

I've modified the code similarly, but used a bit different approach, so I wanted you to look at mine, too. It's available in my [remote branch](https://github.com/ijokarumawak/nifi/commit/dbde98e1b3a7dc9316308170fb4b66b6deeed606).

I felt that it can be better if we can opt-in this new conversion, so that existing flow can work with String representation. Also, we might be able to resolve other data types such as Date, using the same mechanism.

How do you think?

**Comment by joewitt** [comment]
@ijokarumawak @ToivoAdams @trixpan can we reach consensus on next steps here and go for it?

**Comment by trixpan** [comment]
Adding @ToivoAdams comment here as his last comment on JIRA did use github's @ mentions instead of JIRAs [~  ] mentions:

> @ijokarumawak 
> 
> Sorry I didn't have time to look your code.
> Your approach looks much better.
> My only concern is – do we generate record which conforms to Avro standard?
> Can any other consumer (outside NiFi) read our Avro record and get back same BigDecimal?
> 
> @joewitt 
> Right, let’s try to finish this.
> Thanks
> Toivo

**Comment by ijokarumawak** [comment]
@trixpan Thanks for sharing the comment. @ToivoAdams @joewitt Sorry for not responding, I hadn't watched the JIRA issue and didn't notice this has been updated. I will polish my commit and do more testing then send another PR for NIFI-2624. Probably my PR will be available sometime in the next week. Thanks!

**Comment by ijokarumawak** [comment]
Just wanted to share my progress on this.

I've add Logical Decimal support as well as Date/Time/Timestamp. As @ToivoAdams pointed out, it's important to make this enhancement work with other part of NiFi and outside of NiFi.

We have AvroReader controller service now to consume Avro records for various processors. I've been testing logical types can be ready by AvroReader correctly and it works well so far.

I think I'm very close to send a PR. I'll do more testing with databases other than MySQL. 
My branch is available here if you are interested:
https://github.com/ijokarumawak/nifi/commit/1ebb9ee9ac16e7651c3e09c6f4f2b6d33d20e7cb

Thanks!

**Comment by ijokarumawak** [comment]
@ToivoAdams it took longer than I estimated, but I've submitted a PR #1798 for NIFI-2624 as an alternative. Do you mind closing this PR if it looks ok and there is no issue? Thank you!

**Pull request closed without merging**
