### PR TITLE
NIFI-5407: Add a MetricsReportingTask to send to ElasticSearch.

### PR DESCRIPTION
**Pull request by richmidwinter**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by pvillard31** [comment]
Hi @richmidwinter - usually we recommend to use the Site To Site Reporting tasks to re-ingest data generated by NiFi at framework level (such as controller status, bulletins, provenance events, etc) as flow files so you can use the existing processors to do whatever you want with this data. In your case you'd have the SiteToSiteControllerStatusReportingTask sending the data to an InputPort at the root level of the canvas and you would then use one of the Elasticsearch processor to send the data to ES. You can have a look here: https://pierrevillard.com/2017/05/13/monitoring-nifi-site2site-reporting-tasks/

Not saying that we don't want the reporting task you created, it's just that this reporting task is probably tied to a specific ES version and would need to be updated if new ES versions introduce major changes.

Let me know what you think.

**Comment by richmidwinter** [comment]
Thanks for taking a look.

It shouldn't be strictly coupled to the ES version, but they obviously could introduce breaking changes, as they could for the existing ES processors. AIUI the next major version should maintain the REST API, but certainly the transport client is getting deprecated in the next major version and removed in the subsequent and I've no idea what they'd do beyond that.

I can see pros and cons to both (for instance we've really suffered as the complexity of the flows grow, mostly with the overhead of developers understanding and working in parallel on them so we have a probably exceptional aversion to adding to them). This is just something that's worked for me - I'd understand if you guys choose not to take it.

**Comment by MikeThomsen** [comment]
> It shouldn't be strictly coupled to the ES version, but they obviously could introduce breaking changes, as they could for the existing ES processors. AIUI the next major version should maintain the REST API, but certainly the transport client is getting deprecated in the next major version and removed in the subsequent and I've no idea what they'd do beyond that.

We have a new bundle in progress called nifi-elasticsearch-restapi that is based on the high level rest client from Elastic. V5 i the only one officially in, but I have a PR for adding V6 as well with a cloned copy of the controller service.

If you want to discuss this issue in depth, we can take it to the mailing list because my team has done a lot w/ NiFi and ELK.

**Comment by MikeThomsen** [comment]
2/3 passed.

**Pull request closed without merging**
