### PR TITLE
NIFI-6403 and NIFI-6404

### PR DESCRIPTION
**Pull request by ChrisSamo632**
#### Description of PR

Continuation of PR #4153 (which appears to have stalled) by @gresockj.

Addressed (@ijokarumawak & @MikeThomsen) comments from the above PR and:

* NIFI-6403 - made TYPE optional on all Elasticsearch HTTP/Record processors
  * default `_type` to `_all` for Fetch processor where TYPE property is unset/blank
  * note that using `_type` is still possible in ES 6 & 7, but deprecated and discouraged; the expectation is that trying to use `_type` as of ES 8+ will not be possible, so some processors might then be unusable
  * decided to take the approach that Elasticsearch should apply its own version-specific logic and not to try and replicate parts of that within NiFi (this is the main difference between this PR and the original one linked above)
* NIFI-6404 - use `_source` query string parameter instead of `_source_include(s)` as it's compatible between ES <6 and 6+

Commits:

1. Original PR content from #4153 re-based against `main`
2. Changes to address comments (and see below)

Templates for integration tests added to Jira ticket.

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [x] Have you verified that the full build is successful on JDK 11?
- [ ] ~~If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?~~
- [ ] ~~If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?~~
- [ ] ~~If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?~~
- [ ] ~~If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?~~

### For documentation related changes:
- [ ] ~~Have you ensured that format looks appropriate for the output in which it is rendered?~~

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by pvillard31** [comment]
I just had a look over the code and it LGTM.
@ijokarumawak, I'm pinging you in case you want to have a look as well on your side?

**Comment by ChrisSamo632** [comment]
> I just had a look over the code and it LGTM.
> @ijokarumawak, I'm pinging you in case you want to have a look as well on your side?

Noticed that while the `PutElasticsearchRecord` and other processors that use the `ElasticsearchClient` (mentioned by @MikeThomsen in the original PR) already support optional `type`, it could be a little more explicit and a test added, so I'll aim to do that along with rebasing against `main` following the recent merge of #4665.

**Comment by ijokarumawak** [comment]
Thanks @ChrisSamo632 for the changes and @pvillard31 for pinging me. I took a look briefly, the changes look good to me. I will have some time in the next few days to look at this closely with different ES versions. I will let you know if I find anything, but otherwise, please go ahead!

**Comment by ChrisSamo632** [comment]
Addressed my own comment above and rebased from `main`.

Looks like I might have done something funny with the rebase (I don't normally do that in Git) - not sure what to do on my branch to fix that (I've certainly not changed 165 files as part of this PR!!)

**Comment by ChrisSamo632** [comment]
> Addressed my own comment above and rebased from `main`.
> 
> Looks like I might have done something funny with the rebase (I don't normally do that in Git) - not sure what to do on my branch to fix that (I've certainly not changed 165 files as part of this PR!!)

OK so definitely looks like I broke things here - got unexpected changes to the classes I intentionally changed (that I'd made then thought I'd rolled back) - will look to cherry-pick the appropriate changes and either rebase this branch correctly *or* start a new PR if necessary

**Comment by ChrisSamo632** [comment]
> > Addressed my own comment above and rebased from `main`.
> > Looks like I might have done something funny with the rebase (I don't normally do that in Git) - not sure what to do on my branch to fix that (I've certainly not changed 165 files as part of this PR!!)
> 
> OK so definitely looks like I broke things here - got unexpected changes to the classes I intentionally changed (that I'd made then thought I'd rolled back) - will look to cherry-pick the appropriate changes and either rebase this branch correctly _or_ start a new PR if necessary

Think I've sorted out my rebase mess now and applied the changes I intended.

Ready for (re)review/test when you're able @ijokarumawak / @pvillard31

**Comment by ijokarumawak** [comment]
@ChrisSamo632 @pvillard31 I've tested the fix with Elasticsearch 5.5, 6.x and 7.x. All processor worked as expected (PutElasticsearchHttp, PutElasticsearchHttpRecord, FetchElasticsearchHttp, QueryElasticsearchHttp, ScrollElasticsearchHttp, DeleteByQueryElasticsearch, JsonQueryElasticsearch, PutElasticsearchRecord).

I will squash commits and merge them to main. Thanks!

**Pull request closed without merging**
