### PR TITLE
NIFI-6542: Upgrade nifi-hadoop-bundles Hadoop version dependency to 3…

### PR DESCRIPTION
**Pull request by belugabehr**
….2.0

Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Enables X functionality; fixes bug NIFI-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?

- [ ] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [x] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by belugabehr** [comment]
I think that upgrading to Hadoop 3.2 removed an implicit dependency that the NiFi module had on `commons-lang`.  I've added in the dependency explicitly.

**Comment by belugabehr** [comment]
```[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project nifi-hive-processors: Compilation failure
[ERROR] error: error reading /home/travis/.m2/repository/org/apache/hive/hive-exec/1.2.1/hive-exec-1.2.1.jar; error in opening zip file```

Doesn't seem related to the patch.  Can someone please kick off build again?

**Comment by belugabehr** [comment]
@tpalfy Can you please help kick off the CI tests again?  Seems like they failed due to a network error.

**Comment by tpalfy** [comment]
@belugabehr 
Unfortunately I can't do much about the failed CI jobs. I can't rerun them. They are partially successful, which is not really a rare case. So I think they can be considered ok overall.

**Comment by joewitt** [comment]
has a review of all the dependencies in 3.0 vs 3.2 been done and if so was there no changes - no new libs and no removed libs such that we have no need to update Licensing and Notice information?

**Comment by belugabehr** [comment]
I ran `mvn dependency:list` against both version.

The only meaningful change in dependency is the addition of:

`org.apache.yetus:audience-annotations:jar:0.5.0`
`dnsjava:dnsjava:jar:2.1.7`

**Comment by joewitt** [comment]
the yetus one is fine but we need to add the dnsjava entry to the LICENSE file of the nifi-assembly/LICENSE and the nifi-hadoop-*-nar that this gets bundled into.  The entry we want to add comes straight from https://github.com/dnsjava/dnsjava/blob/master/LICENSE and you can follow the examples of other licenses.

**Comment by belugabehr** [comment]
@joewitt Excellent.  Thanks for the guidance.  Updated.

**Comment by belugabehr** [comment]
```[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project nifi-hive-processors: Compilation failure
[ERROR] error: error reading /home/travis/.m2/repository/org/apache/hive/hive-exec/1.2.1/hive-exec-1.2.1.jar; error in opening zip file```

Failure doesn't really seem related.  How do I kick off the CI tests suite again?

**Comment by bbende** [comment]
It looks like this also adds commons-text to hadoop libraries NAR which we already have mentioned in our top-level NOTICE, but not in the NOTICE for hadoop libraries NAR.

https://github.com/apache/commons-text/blob/master/NOTICE.txt

We should probably bump the one in the top-level from 2018 to 2019 as well.

**Comment by joewitt** [comment]
Merged to master but forgot the hook.  Will add the info via JIRA manually.  Thanks for contrib.  +1 merged to master.

**Pull request closed without merging**
