### PR TITLE
NIFI-2892 Implement AWS Kinesis Stream Get Processor

### PR DESCRIPTION
**Pull request by udaykale**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Enables X functionality; fixes bug NIFI-2892

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [x] Have you written or updated unit tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by turcsanyip** [comment]
Reviewing...

**Comment by turcsanyip** [comment]
@udaykale Thanks for the contribution!
First I would like to have a look at the new processor on the UI, but it is not shown there. You need to register the processor as a service in `META-INF/services/org.apache.nifi.processor.Processor` file.

**Comment by udaykale** [comment]
@turcsanyip thanks for reviwing the code. 
I am having issues seeing the new processor. I registered the processor as service in `META-INF/services/org.apache.nifi.processor.Processor`. However, the processor is still not visible in the UI. Is there something I am still missing?

**Comment by turcsanyip** [comment]
@udaykale I can add the processor to the canvas now.
After checking out your last commit, I rebuilt `nifi-aws-bundle` module, copied `nifi-aws-nar-1.10.0-SNAPSHOT.nar` to the lib folder of NiFi and restarted NiFi. It should work for you too. No other changes needed.

**Comment by udaykale** [comment]
@turcsanyip Yes it worked for me too. I was building the wrong module.

**Comment by jaynpearl** [comment]
Tested the build and got some issue on using the GetKinesisStream Processor.
I was tried to get data from a stream in us-west-2 but it kept saying resource not found. And I sure I am set the region to us-west-2.
This is wired that the DynamoDB created by the processor was in us-east-1.

**Comment by ChrisSamo632** [comment]
Updated PR for latest `main` branch (1.13.0) - https://github.com/apache/nifi/pull/4822

Updated KCL version, changed so KCL is shutdown when nifi processor shutdown requested and added plenty of unit tests (changing some of the implementation to try and provide a better user experience)

**Comment by pvillard31** [comment]
Closing this one in favor of #4822.

**Pull request closed without merging**
