### PR TITLE
NIFI-4106 Lower loglevel of authentication request and success

### PR DESCRIPTION
**Pull request by NielsZeilemaker**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by alopresto** [comment]
Hi Niels,

Thank you for making a submission to improve NiFi. I totally understand your concern that the logs can be busy with these messages when you have a high number of users connecting. To even need to deal with this situation means you're using NiFi in a productive manner. However, we find that this message in particular is extremely helpful in debugging for users who are not as successful in configuring and using the application. Being able to identify the attempted authentication requests without having to walk them through making substantial configuration changes allows faster and more detailed responses. 

However, I definitely empathize with your situation. Can I suggest making a local change in your `$NIFI_HOME/conf/logback.xml` file? Two possible solutions are changing the log level of the entire package to be `WARN`, as you seem to have a good handle on the application and don't need informational alerts on successful actions, or elevating the log level for that specific class while retaining `INFO` messages for the other actions in that package. 

## Option 1:

Replace 

    <logger name="org.apache.nifi.web.security" level="INFO" additivity="false">
        <appender-ref ref="USER_FILE"/>
    </logger>

with

    <logger name="org.apache.nifi.web.security" level="WARN" additivity="false">
        <appender-ref ref="USER_FILE"/>
    </logger>


## Option 2:

Add

    <logger name="org.apache.nifi.web.security.NiFiAuthenticationFilter" level="WARN" additivity="false">
        <appender-ref ref="USER_FILE"/>
    </logger>

Either of these two solutions should improve your situation while still allowing the community to easily support people who need a bit more help. Thanks.

**Comment by NielsZeilemaker** [comment]
Hi @alopresto, thanks for the suggestion. However, raising the loglevel would also cause us to miss the "Rejecting access..." messages, as those are logged @ info as well.
Should I change the level of that rejection to warn? Then I can keep the other messages as info level, but will still see the rejections.

**Comment by jfrazee** [comment]
@NielsZeilemaker I looked at this and that was exactly my concern as well and I think your suggestion of inverting the change to make the rejection WARN is a good one. You get the control over successes via the level for the class but you won't lose the rejection which the defaults really should include to not undermine security.

**Comment by NielsZeilemaker** [comment]
done, thanks @alopresto @jfrazee

**Comment by alopresto** [comment]
Great. Thanks @NielsZeilemaker . I'll review this and it should be merged into master today.

**Comment by alopresto** [comment]
Ran with contrib-check and all tests pass. Will merge.

**Pull request closed without merging**
