### PR TITLE
NIFI-2564 Add support for HL7 composite component names

### PR DESCRIPTION
**Pull request by jfrazee**
Wanted to start getting some feedback on this.

ExtractHL7Attributes can currently parse composite components, e.g., output PID.PatientName.XPN.2, which corresponds to the patient's given name, but it'd be more helpful if the attribute was something like PID.PatientName.GivenName or PID.PatientName.XPN.GivenName.

Unfortunately, the underlying library doesn't provide a common way or interfaces around the composite types that make it possible to get at that, so this change gets at them with reflection.

### CODE REVIEW

**Comment by trixpan** [comment]
@jfrazee apologies for the delay,  would you mind rebasing this against master so it can be reviewed?

I thank you in advance

**Comment by jfrazee** [comment]
@trixpan I'll be getting back to this today. There was a bug fix that had to slide in before this too so it's not going to rebase cleanly anymore.

**Comment by joewitt** [comment]
@jfrazee i'd like to help you get this pushed across the finish line.  Can you please rebase?

**Comment by jfrazee** [comment]
@joewitt It's rebased against master again.

**Pull request closed without merging**
