### PR TITLE
NIFI-10393 Update Lucene To 8.11.1

### PR DESCRIPTION
**Pull request by mr1716**
# Summary

[NIFI-10393](https://issues.apache.org/jira/browse/NIFI-10393)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI-10393) issue created

### Pull Request Tracking

- [X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X] Pull Request based on current revision of the `main` branch
- [X] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [X] JDK 8
  - [X] JDK 11
  - [X] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by MikeThomsen — CHANGES_REQUESTED** [review]
Thanks for the contribution, but we need this to be associated with an Apache Jira ticket number.

**Comment by UcanInfosec** [comment]
@MikeThomsen it says JIRA ticket 10393 in the ticket. https://issues.apache.org/jira/plugins/servlet/mobile#issue/NIFI-10393

**Comment by MikeThomsen** [comment]
My bad, I can't believe I missed that. I'll pull the commit and clean up the git description so this can be merged.

**Comment by UcanInfosec** [comment]
No worries. My apologies if I didn’t put the best description for everything. Just glad to help out!

**Review by MikeThomsen — APPROVED** [review]
LGTM and was able to reproduce the successful build from the CI/CD locally so will merge in a few.

**Pull request closed without merging**
