### PR TITLE
NIFI-400 removed depricated file EvaluateRegularExpression

### PR DESCRIPTION
**Pull request by ZJaffee**

### CODE REVIEW

**Comment by mosermw** [comment]
To complete this, you will also have to modify the nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/resources/META-INF/services/org.apache.nifi.processor.Processor file to remove its reference to EvaluateRegularExpression.

**Comment by ZJaffee** [comment]
Fixed

**Comment by apiri** [comment]
@ZJaffee thanks for the contribution.  This item is currently considered a "breaking" change in that it would cause a manual intervention for those folks currently using the processor in their existing flows.  As part of our versioning scheme, this will coincide with our 1.x release.

**Comment by trkurc** [comment]
@apiri  - should I make this a patch and attach it to the ticket to decrease likelyhood of missing this for into 1.x?

**Comment by apiri** [comment]
that sounds fair. this is a nice reminder that we certainly need to revive the talk about our versioning process and support schedule on the mailing list so we can establish a path forward in handling these types of items

**Comment by apiri** [comment]
@ZJaffee we finally have established an appropriate branching model to support this and will be merging this in.  Thanks for fixing this up and your patience! 👍

**Pull request closed without merging**
