### PR TITLE
NIFI-7845 Better handling on malformed/empty strings

### PR DESCRIPTION
**Pull request by themanifold**
_Better handling on malformed/empty strings_

#### Description of PR

At the moment, the `validateAMQPHeaderProperty()` does not handle `amqpPropValues` that are appended and prepended by curly braces, like `{a=b}`.

Nor does the function deal with an empty `amqpPropValues` properly.

This is particularly a problem because if the AMQP queue you're reading from with the `ConsumeAMQP.java` processor has a message with an *empty* header, then `ConsumeAMQP.java` creates a flowfile-attribute `ampq$header` of the form `{}` - which causes `validateAMQPHeaderProperty()` to pollute the NiFi error box.

According to [1] the AMQP header attribute is optional anyway, so we need to handle blank entries.

[1]: https://www.rabbitmq.com/tutorials/amqp-concepts.html#messages

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [ ] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by pvillard31** [comment]
Hi @themanifold - thanks for this contribution. Can you please create a JIRA describing the issue/improvement (https://issues.apache.org/jira/browse/NIFI)? And then update the title of this PR to prefix it with the JIRA reference? This helps us keeping track of everything. Thank you.

**Comment by themanifold** [comment]
> Hi @themanifold - thanks for this contribution. Can you please create a JIRA describing the issue/improvement (https://issues.apache.org/jira/browse/NIFI)? And then update the title of this PR to prefix it with the JIRA reference? This helps us keeping track of everything. Thank you.

Done: https://issues.apache.org/jira/browse/NIFI-7845

**Comment by pvillard31** [comment]
Thanks @themanifold. Hey @turcsanyip - I know you worked on this recently, you might want to have a look?

**Comment by themanifold** [comment]
With reference to the ci-workflow tests, I don't actually see any valid errors unless I'm missing something...

**Comment by turcsanyip** [comment]
This is the error in the build:
```
Error:  COMPILATION ERROR : 
Error:  /home/runner/work/nifi/nifi/nifi-nar-bundles/nifi-amqp-bundle/nifi-amqp-processors/src/main/java/org/apache/nifi/amqp/processors/PublishAMQP.java:[258,8] error: cannot find symbol
  symbol:   variable amqpPropValueLen
```
I checked it locally too and `amqpPropValueLen` does not seem to be declared.

**Comment by themanifold** [comment]
> This is the error in the build:
> 
> ```
> Error:  COMPILATION ERROR : 
> Error:  /home/runner/work/nifi/nifi/nifi-nar-bundles/nifi-amqp-bundle/nifi-amqp-processors/src/main/java/org/apache/nifi/amqp/processors/PublishAMQP.java:[258,8] error: cannot find symbol
>   symbol:   variable amqpPropValueLen
> ```
> 
> I checked it locally too and `amqpPropValueLen` does not seem to be declared.

My bad. I've never written any Java before and I didn't check this on my own machine as I'm hoping this is just a quick fix.

**Comment by themanifold** [comment]
I suspect that the cancellation is just unlucky - given the french version failed. I don't know how to re-run it - can't find a button for it @pvillard31

**Comment by pvillard31** [comment]
That's fine, no worries 3 builds out of four passed, so we're good on this side. Just need someone to review your code. I'm not very familiar with this part so I'd prefer another pair of eyes. My only recommendation would be to update an existing unit test or create a new one to confirm the change (unit test or integration test).

**Comment by turcsanyip** [comment]
@themanifold Could you please clarify your use case and the problem you would like to solve in more detail?

If I understand correctly, `ConsumeAMQP` can emit the following `amqp$headers` attribute values (as strings):
- `{a=1}` if there is 1 key=value pair in the message headers
- `{a=1,b=2}` if there are 2 key=value pairs in the headers of the received message
- `{}` if the headers of the received message is empty

And you would like 'PublishAMQP' to be able to parse these strings properly. Eg. in case of `{a=1,b=2}`, remove the curly braces and add 2 headers (`a=1` and `b=2`), and in case of `{}`, no headers need to be added.

So your flow is `ConsumeAMQP` (from a queue) => process data => 'PublishAMQP' (to another queue with keeping the same headers). Is my understanding correct?

**Comment by themanifold** [comment]
> @themanifold Could you please clarify your use case and the problem you would like to solve in more detail?
> 
> If I understand correctly, `ConsumeAMQP` can emit the following `amqp$headers` attribute values (as strings):
> 
>     * `{a=1}` if there is 1 key=value pair in the message headers
> 
>     * `{a=1,b=2}` if there are 2 key=value pairs in the headers of the received message
> 
>     * `{}` if the headers of the received message is empty
> 
> 
> And you would like `PublishAMQP` to be able to parse these strings properly. Eg. in case of `{a=1,b=2}`, remove the curly braces and add 2 headers (`a=1` and `b=2`), and in case of `{}`, no headers need to be added.
> 
> So your flow is `ConsumeAMQP` (from a queue) => process data => `PublishAMQP` (to another queue with keeping the same headers). Is my understanding correct?

Everything here is correct apart from the flow. My initial attempt in NiFi didn't actually do any data processing. I did: `ConsumeAMQP` (from a queue) => `PublishAMQP` (exchange). If you try this in NiFi, you'll find that the `PublishAMQP` can't cope with `{}` (if your incoming message has no headers). Additionally, you'll see that `ConsumeAMQP` actually can't cope with curly braces full stop and will end up making some invalid headers - specifically the first key and the last key will have `{` and `}` appended and prepended, respectively. When I say that it can't cope, I mean that throws up a warning that will obscure any real errors.

My work around right now is to actually delete the empty header using the `update attribute` processor.

**Comment by themanifold** [comment]
Please can someone review/merge this? @turcsanyip

**Comment by themanifold** [comment]
AFAIK this is still good to merge

**Pull request closed without merging**
