### PR TITLE
NIFI-4470 - Variables Registry: Increase space...

### PR DESCRIPTION
**Pull request by yuri1969**
...between Bulletin icon and Controller Service name

Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by scottyaslan** [comment]
Reviewing...

**Comment by scottyaslan** [comment]
@yuri1969 Thanks this has been merged to master. I really appreciate these PR's! Can you please do one other thing? It is a small thing I promise. When you start work on a JIRA don't forget to assign it to yourself and mark it as "In Progress". Once you have submitted the PR you can move the JIRA into "Patch Available". Then once the PR has been merged to master the reviewer will mark the ticket as "Resolved". This way everyone in the community will know who is working on it, be able to comment on it and discuss, and also so we won't duplicate effort. Thanks again!

**Comment by yuri1969** [comment]
@scottyaslan You are welcome.

I'm afraid, I don't have permissions to assign JIRA Issues to myself. Who should I ask to elevate my JIRA permissions? Thanks.

**Comment by mcgilman** [comment]
@yuri1969 What is your JIRA username? I should be able to grant you additional permissions. Thanks.

**Comment by scottyaslan** [comment]
https://cwiki.apache.org/confluence/display/NIFI/Contributor+Guide

**Pull request closed without merging**
