### PR TITLE
NIFI-9638 Refactor Google Guava usage in extensions

### PR DESCRIPTION
**Pull request by exceptionfactory**
#### Description of PR

NIFI-9638 is the second set of changes refactoring Google Guava references across multiple extension modules.

The majority of the changes involve updates to test classes. Several updates include updating Google Guava to 31.0.1. Additional updates include removing direct references to Google Guava classes, although the library remains a required dependency in some modules.

Changes impact the following modules:

- nifi-accumulo-processors
  - Refactored collections references
- nifi-aws-processors
  - Updated unit test class
- nifi-azure-bundle
  - Removed direct references and upgraded transitive dependency to 31.0.1
- nifi-cassandra-bundle
  - Set provided scope in Processor and Services NAR modules to avoid unnecessary copies
  - Set cassandra.guava.version to 19.0, which is the latest version supported in the Cassandra driver
- nifi-datadog-reporting-task
  - Refactored references and removed direct dependency
- nifi-enrich-processors
  - Refactored references and removed direct dependency
- nifi-evtx-processors
  - Upgraded dependency from 28.0 to 31.0.1
- nifi-gcp-bundle
  - Removed direct references and upgraded transitive dependency to 31.0.1
- nifi-graph-processors
  - Removed unused test dependency
- nifi-hwx-schema-registry-bundle
  - Refactored references and upgraded transitive dependency to 31.0.1
- nifi-kudu-processors
  - Removed direct class references to shaded class
- nifi-mongo-processors
  - Refactored and removed test dependency
- nifi-sql-reporting-tasks
  - Removed reference in test class
- nifi-standard-bundle
  - Upgraded transitive dependency to 31.0.1 overriding version from Apache Calcite libraries

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [X] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [X] Have you written or updated unit tests to verify your changes?
- [X] Have you verified that the full build is successful on JDK 8?
- [X] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by kevdoran** [comment]
Will review...

**Review by kevdoran — APPROVED** [review]
Thanks again @exceptionfactory! Reviewed all the changes, and the CI builds are happy, so this is a +1 from me

**Comment by exceptionfactory** [comment]
Thanks @kevdoran! Rebased to resolve merge conflict with `TestMetricsEventReportingTask`.

**Comment by mattyb149** [comment]
+1 LGTM, with Kevin's +1 and a happy CI this is good to go. Thanks for the improvement! Merging to main

**Comment by kevdoran** [comment]
Thanks @mattyb149!

**Pull request closed without merging**
