### PR TITLE
NIFI-11648: Bump archetype-packaging version to 3.2.1

### PR DESCRIPTION
**Pull request by r-sidd**
# Summary

[NIFI-11648](https://issues.apache.org/jira/browse/NIFI-11648)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 11
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — CHANGES_REQUESTED** [review]
@r-sidd These changes do not include updating the `maven-archetype-plugin` itself, which is also necessary in the referencing Maven configuration. Please review the entire file for related references.

**Comment by r-sidd** [comment]
> @r-sidd These changes do not include updating the `maven-archetype-plugin` itself, which is also necessary in the referencing Maven configuration. Please review the entire file for related references.

Sorry about that, let me check on this, thanks

**Comment by r-sidd** [comment]
Bumped maven-archetype-plugin version as well

**Review by exceptionfactory — APPROVED** [review]
Thanks for the update @r-sidd, that changes look good. +1 merging

**Pull request closed without merging**
