### PR TITLE
NIFI-12908 provide powershell versions of the nifi-env.cmd and nifi.cmd

### PR DESCRIPTION
**Pull request by phreed**
# Summary

[NIFI-12908](https://issues.apache.org/jira/browse/NIFI-12908)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — COMMENTED** [review]
Thanks for the contribution @phreed.

As you noted in the Jira issue, the `nifi.cmd` script is not clearly highlighted in documentation, so that could also be a useful improvement.

Can you provide some additional background on the reason for introducing a PowerShell alternative to the `nifi.cmd` script for Windows? It would be ideal to maintain a unified approach for Windows, as opposed to maintaining two separate scripts for the same OS.

**Comment by phreed** [comment]
> Can you provide some additional background on the reason for introducing a PowerShell alternative to the `nifi.cmd` script for Windows? It would be ideal to maintain a unified approach for Windows, as opposed to maintaining two separate scripts for the same OS.

I am just starting out with NiFi, so I will have to speak in generalities.

Making changes to *.cmd/*.bat files is fraught.
Every time I think I am going to make a small change to one it ends up being a time sink.

I am planning on extensively using NiFi for a project I am working on.
A lot of the work will involve dynamic deployment of NiFi components on a dynamic cluster.
I anticipate building tooling to support this work.
I would much prefer to use powershell over CMD/BAT.
I plan on contributing this tooling back to Apache.

It may be that the tooling would be better written in one of the JVM scripting languages (i.e. Groovy, Kotlin, Clojure).
That said I expect that some of the tooling would still best be written as powershell modules on Windows.

Obviously, the `nifi.ps1` is not (yet) a powershell module, I am getting a feel for how the NiFi project operates.
I would like to see the `nifi.cmd` deprecated in favor of  powershell modules.

**Comment by exceptionfactory** [comment]
> > Can you provide some additional background on the reason for introducing a PowerShell alternative to the `nifi.cmd` script for Windows? It would be ideal to maintain a unified approach for Windows, as opposed to maintaining two separate scripts for the same OS.
> 
> I am just starting out with NiFi, so I will have to speak in generalities.
> 
> Making changes to _.cmd/_.bat files is fraught (for me). Every time I think I am going to make a small change to one it ends up being a time sink.
> 
> I am planning on extensively using NiFi for a project I am working on. A lot of the work will involve dynamic deployment of NiFi components on a dynamic cluster. I anticipate building tooling to support this work. I would much prefer to use powershell over CMD/BAT. I plan on contributing this tooling back to Apache.
> 
> It may be that the tooling would be better written in one of the JVM scripting languages (i.e. Groovy, Kotlin, Clojure). That said I expect that some of the tooling would still best be written as powershell modules on Windows.
> 
> Obviously, the `nifi.ps1` is not (yet) a powershell module, I am getting a feel for how the NiFi project operates. I would like to see the `nifi.cmd` deprecated in favor of powershell modules.

Thanks for additional background @phreed.

The shell scripts are intended to provide a minimum wrapper around the environment settings necessary to start NiFi Java processes. For that reason, these scripts should be as minimal as possible, and provide the broadest base of compatibility. That is why the current scripts for Windows do not use PowerShell, and should avoid additional complexity. That is also the reason why they do not use any type of JVM scripting.

Running NiFi on Windows is supported in general, but running scalable production deployments most often depends on Linux as the operating system.

So with that background, any shell script changes should continue to follow the minimalist approach to maintain compatibility across modern distributions of Windows. With that in mind, it may be best to avoid introducing PowerShell scripts in favor of retaining the limited scope of command scripting. This does highlight the need for reviewing the general approach of Windows startup scripts, including the removal of the `BAT` scripts.

If the PowerShell approach works without installing any additional Windows packages on current versions of both Home and Pro, then this seems like a potential option. Are you aware of any compatibility issues with PowerShell on recent Windows versions, particularly on non-server editions?

**Comment by phreed** [comment]
Not compatibility issues per se but powershell does have a stronger security model requiring changing the default security settings. So, maybe dropping this PR would be the best move. I originally make this port because there was a problem with the nifi.cmd and rather than debug nifi.cmd I did this port. 
I mostly use linux, so I am far from a powershell expert (but I really do not like bat/cmd).

**Comment by exceptionfactory** [comment]
> Not compatibility issues per se but powershell does have a stronger security model requiring changing the default security settings. So, maybe dropping this PR would be the best move. I originally make this port because there was a problem with the nifi.cmd and rather than debug nifi.cmd I did this port. I mostly use linux, so I am far from a powershell expert (but I really do not like bat/cmd).

That's good to know. NiFi usage is much more common on Linux and macOS, but development on Windows is common enough. Based on the security requirements you mentioned, I agree that closing the current pull request is the best option for now.

If you are able to track down issues with the `nifi.cmd`, that would be helpful to maintain.

**Comment by exceptionfactory** [comment]
@phreed I am closing this pull request for now based on the discussion. As mentioned, if you find particular problems with the current `nifi.cmd`, it would be helpful to highlight those in the Jira issue so we can track down the problem.

**Pull request closed without merging**
