### PR TITLE
NIFI-4944: Guard against race condition in Snappy for PutHiveStreaming

### PR DESCRIPTION
**Pull request by mattyb149**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by MikeThomsen** [comment]
+1 LGTM. Unit tests ran and the solution looks like a sensible and effective one.

**Comment by mcgilman** [comment]
@mattyb149 Previously the loading of Snappy happened during onTrigger. This could lead to the race condition described in the JIRA/PR. Moving this to a static initializer should alleviate the issue. Additionally, the act of service discovery (Java SPI) will load the class. Because of this, I actually don't believe the synchronization here is necessary. Thoughts?

**Comment by moonkev** [comment]
Hi

Seeing this same issue with the PutHDFS processor and came across this.  Curious with this solution, won't the same condition arise with this same solution?  Won't the static initializer here be called in each instance class loader which makes use of this processor?  I was reading [here](https://bryanbende.com/development/2016/11/24/apache-nifi-class-loading) and it seems that each processor itself will be loaded again, thus causing snappy's static initializer to be called, which in turn will again attempt to load its native library.  

Thanks
Kevin

**Comment by mcgilman** [comment]
@moonkev I think there a couple different scenario's here. This is admittedly pretty complicated, but my understanding is as follows:

- In a case like PutHDFS, snappy compression is supported through the native hadoop library. In this case, the native snappy library is not loaded. Issues seen here are do to multiple classloaders attempting to load "hadoop" native library.
- In a case like CompressContent, snappy support is supplied by the native snappy library loaded indirectly through snappy-java. In more recent version, they effectively bypass the native loading issues by copying the native library to a temp directory and loading it with a UUID appended to the name. This allows the native library to multiple times (since the name is different each time).
- In a case like PutHiveStreaming, snappy support is also supplied through snappy-java. The difference is that its an old version of snappy-java that does not perform the UUID trick. Force upgrading in this case is tricky since it is a transitive dependency (PutHiveStreaming -> Hive -> avro -> snappy). The legacy snappy-java addresses the native library issue by directly injecting the class that loads the native library into the root classloader. The ultimate issue here was that multiple processors were attempting to do this loading at the same time (due to the loading happening in onTrigger). 

@mattyb149 Please chime in here if any of my understanding isn't correct.

Hope this helps

**Comment by mcgilman** [comment]
Thanks @mattyb149! This has been merged to master.

**Comment by moonkev** [comment]
I was aware that PutHiveStreaming used snappy-java vs native snappy, but was unaware of the methods that snappy-java protect against loading in multiple class loaders.  Many thanks for the detailed explanation @mcgilman!

**Pull request closed without merging**
