### PR TITLE
NIFI-8389 - Grok Reader - raw data strategy when no match

### PR DESCRIPTION
**Pull request by pvillard31**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Enables X functionality; fixes bug NIFI-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [x] Have you written or updated unit tests to verify your changes?
- [x] Have you verified that the full build is successful on JDK 8?
- [x] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by ottobackwards** [comment]
@pvillard31, this looks good, but I don't don't see where you actually have the Property added?  I'm sorry if I'm missing something obvious.  I haven't finished my first coffee.

Also, when this is working, and if raw is configured vs. something else, would I get records when I previously wouldn't?

**Comment by pvillard31** [comment]
Thanks for the quick review @ottobackwards - I completely missed the addition of the allowable value in the property... I just relied on the unit tests... I guess I should not push a pull request at 2 in the morning :)

Right now, if using ``append``, this would add the message into the ``_raw`` field of the previous message, while ``skip`` would completely dismiss the message.

Example:

I'm sending two messages
- ``<6>Feb 28 12:00:00 192.168.0.1 aliyun[11111]: [error] Syslog test``
- ``This is a bad message...``

I'm using the Grok Reader with the following pattern:
``<%{POSINT:priority}>%{SYSLOGTIMESTAMP:timestamp} %{SYSLOGHOST:hostname} %{WORD:ident}%{GREEDYDATA:message}``

If using ``skip`` with a JSON Writer, I'd get:
````
[ {
  "priority" : "6",
  "timestamp" : "Feb 28 12:00:00",
  "hostname" : "192.168.0.1",
  "ident" : "aliyun",
  "message" : "[11111]: [error] Syslog test",
  "stackTrace" : null,
  "_raw" : "<6>Feb 28 12:00:00 192.168.0.1 aliyun[11111]: [error] Syslog test"
} ]
````

If using ``append``:
````
[ {
  "priority" : "6",
  "timestamp" : "Feb 28 12:00:00",
  "hostname" : "192.168.0.1",
  "ident" : "aliyun",
  "message" : "[11111]: [error] Syslog test\nThis is a bad message...",
  "stackTrace" : null,
  "_raw" : "<6>Feb 28 12:00:00 192.168.0.1 aliyun[11111]: [error] Syslog test\nThis is a bad message..."
} ]
````

If using ``raw``:
````
[ {
  "priority" : "6",
  "timestamp" : "Feb 28 12:00:00",
  "hostname" : "192.168.0.1",
  "ident" : "aliyun",
  "message" : "[11111]: [error] Syslog test",
  "stackTrace" : null,
  "_raw" : "<6>Feb 28 12:00:00 192.168.0.1 aliyun[11111]: [error] Syslog test"
}, {
  "priority" : null,
  "timestamp" : null,
  "hostname" : null,
  "ident" : null,
  "message" : null,
  "stackTrace" : null,
  "_raw" : "This is a bad message..."
} ]
````

**Comment by ottobackwards** [comment]
That is a perfect explanation, thank you @pvillard31.

**Review by ottobackwards — APPROVED** [review]
The looks really useful, if it confuses users, the example here would make a good additional details down the road.
@pvillard31 I'm not on my dev machine, and I'm trying to avoid GitHub merges, can you merge?

**Comment by pvillard31** [comment]
I'll add the example in the additional details page, this is a good point.

**Comment by pvillard31** [comment]
Doc/example added

**Comment by ottobackwards** [comment]
Awesome.  Ship it

**Comment by turcsanyip** [comment]
@pvillard31 Thanks for the improvement!
@ottobackwards Thanks for the review!

Merging to main.

**Pull request closed without merging**
