### PR TITLE
NIFI-12191 simplify integration-tests and docker-tests GitHub Action workflows

### PR DESCRIPTION
**Pull request by ChrisSamo632**
# Summary

[NIFI-12191](https://issues.apache.org/jira/browse/NIFI-12191) simplify integration-tests and docker-tests GitHub Action workflows

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [x] Build completed using `mvn clean install -P contrib-check`
  - [x] JDK 21

### Licensing

- ~[ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)~
- ~[ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files~

### Documentation

- ~[ ] Documentation formatting appears as expected in rendered files~

### CODE REVIEW

**Review by exceptionfactory — COMMENTED** [review]
Thanks for working on this @ChrisSamo632.

I am wondering about the value of testing multiple platforms. For the Docker tests, there seems to be little value on running the builds on multiple platforms, since the tests involve the container, not necessarily the host OS.

For the integration tests, there may be some additional value, but there is also a cost in terms of time to execute the tests.

What do you think of limiting the Docker tests to just Linux, while keeping the integration tests for both Linux and macOS?

**Comment by ChrisSamo632** [comment]
@exceptionfactory I agree that there's concern over the increased cost vs. possible utility - to a degree, I was more wondering whether things would work at all with `colima` instead of `docker`

I suspect (the Checks will tell in time) that using MacOS for the ITs will prove more tempremental that worthwhile, so for that reason alone I'm leaning on the side of not including those unless there are obvious benefits - the only real one I can come up with is that MacOS as a development environment is probably more common that Linux (but that's a assumption on my part). How useful regular IT runs are in that environment though, I'm as yet unconvinced

For similar reasons, I was thinking the `docker-tests` might be worthwhile, and they're also a lot faster to run so would be cheaper in terms of build resources. But that said, I suspect that building and running the Docker Images with `colima` (or any tool other than `docker`) is probably relatively rare / not something we're looking to directly support here

So I think it probably comes down to whether we think there is sufficient benefit in (more regularly) running the extended tests in the (assumed) more common development environment

**Comment by exceptionfactory** [comment]
Thanks for the thoughtful reply @ChrisSamo632. Those are definitely points worth considering as far as Colima versus standard Docker.

I have been in touch with Apache Infrastructure support about testing their new hosted GitHub Runners, which will hopefully provide some performance improvements. However, I'm not sure about the operating systems supported, so that may be limiting.

With that background, and considering the resources used, I think it would be better to keep the Docker and Integration Test workflows limited to one OS (Linux). Although it might not cover every possible situation, it is much better than no coverage.

What do you think about re-scoping this pull request to removing the matrix configuration and just targeting the one OS?

**Comment by ChrisSamo632** [comment]
@exceptionfactory with the discussion and the continued failure of the Docker-based tests on MacOS runners, I'm certainly happy to re-scope this to be a simplification of the existing Workflows to focus on Ubuntu-based testing only

**Review by exceptionfactory — APPROVED** [review]
Thanks for work on this and re-scoping the changes @ChrisSamo632, the latest version looks good! +1 merging

**Pull request closed without merging**
