### PR TITLE
NIFI-11036: Add Cluster Summary Metrics to Prometheus endpoint

### PR DESCRIPTION
**Pull request by mattyb149**
# Summary

[NIFI-11036](https://issues.apache.org/jira/browse/NIFI-11036)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-11036`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-11036`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 8
  - [x] JDK 11
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by MikeThomsen** [comment]
@mattyb149 I started NiFi on this branch and didn't see any of the metrics you added exposed on the metrics endpoint. Do these only get generated in clustered mode?

**Review by taz1988 — APPROVED** [review]
I didn't find any error, if I use https://localhost:8443/nifi-api/flow/metrics/prometheus?includedRegistries=CLUSTER I got the data:

```
# HELP cluster_is_clustered Whether this NiFi instance is clustered. Values are 0 or 1
# TYPE cluster_is_clustered gauge
cluster_is_clustered{instance="7f34c4ca-b48e-489c-8533-ddd9882c4a43",} 1.0
# HELP cluster_connected_node_count The number of connected nodes in this cluster
# TYPE cluster_connected_node_count gauge
cluster_connected_node_count{instance="7f34c4ca-b48e-489c-8533-ddd9882c4a43",connected_nodes="3 / 3",} 3.0
cluster_connected_node_count{instance="7f34c4ca-b48e-489c-8533-ddd9882c4a43",connected_nodes="2 / 3",} 2.0
# HELP cluster_is_connected_to_cluster Whether this NiFi instance is connected to a cluster. Values are 0 or 1
# TYPE cluster_is_connected_to_cluster gauge
cluster_is_connected_to_cluster{instance="7f34c4ca-b48e-489c-8533-ddd9882c4a43",} 1.0
# HELP cluster_total_node_count The total number of nodes in this cluster
# TYPE cluster_total_node_count gauge
cluster_total_node_count{instance="7f34c4ca-b48e-489c-8533-ddd9882c4a43",} 3.0
```

👍

**Comment by taz1988** [comment]
+1

**Review by pvillard31 — APPROVED** [review]

**Comment by shayki5** [comment]
Can you add it to `/metrics` endpoint? (when enable PrometheusReportingTask)

**Comment by shayki5** [comment]
@taz1988 How can you use this endpoint in Prometheus? which authentication you need?

**Comment by uxapj** [comment]
How can I request an improvement on this implementation?
As @shayki5 asked, we would love to see this in the /metrics endpoint that is generated from the PrometheusReportingTask...

**Pull request closed without merging**
