### PR TITLE
NIFI-9557: Change C2 OperandType to Enum

### PR DESCRIPTION
**Pull request by bejancsaba**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

As OperationType and Operand is well defined and central in the C2 specification their values and valid mappings should be reflected in the API so we could avoid invalid operation configurations on the protocol level. Similarly to OperationType OperandType was introduced and known mappings were defined.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [x] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by bejancsaba** [comment]
Follow up of the closed PR: https://github.com/apache/nifi/pull/5648

**Comment by kevdoran** [comment]
I left this comment on the close PR, but will copy it here just in case:

> Regarding operand being an Enum vs String, I think the original intent of that field was to be a place for a target component id for operations that can target individual components, e.g., Processors. So something like a stop/start/restart-component operation that is targeting a single component in the flow rather than the entire flow could pass a component id as the operand. For this reason, String seems more suitable to me.

**Comment by kevdoran** [comment]
Yep, I'm good with that

**Comment by mattyb149** [comment]
+1 LGTM, thanks for the improvement! Merging to main

**Pull request closed without merging**
