### PR TITLE
NIFI-8486 Added Support for Parquet, ORC and DataStoreBackup

### PR DESCRIPTION
**Pull request by harjitdotsingh**
Thank you for submitting a contribution to Apache NiFi.

#### Description of PR
Added Support for ParQuet, ORC and DataStoreBackup

Enables Functionality reported in Issue Nifi-8486

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message? Yes

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character. Yes

- [x] Has your PR been rebased against the latest commit within the target branch (typically `main`)? YEs

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?y
- [x] Have you written or updated unit tests to verify your changes?n
- [x] Have you verified that the full build is successful on JDK 8?y
- [x] Have you verified that the full build is successful on JDK 11?y
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by pvillard31** [comment]
Hi @harjitdotsingh - happy to review these changes but can you make sure the PR is only changing what needs to be changed? there is a lot of formatting related changes that are making the review harder. Can we also have tests for the changes?

**Comment by harjitdotsingh** [comment]
I knew that was coming. For some reasons my IDE formatted the code. Let me
fix that. I will add that. I didn't see tests for any other cases other
than JSON so left it but let me see if I can find some sample files for
Parquet,ORC and DataStoreBackup.

Thanks

- harjit

**Comment by harjitdotsingh** [comment]
@pvillard31 - Quick Question. I was planning to write the tests for the formats I had added. Should I create new test for each format or create the tests in the PutBigQueryBatchTest.java. I don't see any tests for CSV format. I only see it for JSON format. Please advise.

**Comment by pvillard31** [comment]
If you only add tests for the new formats, that's fine for me ;)

**Comment by harjitdotsingh** [comment]
@pvillard31  - Added test run integration tests and unit tests without any issues. Pls let me know if there any issues which you see.

**Comment by pvillard31** [comment]
Can you look at the checkstyle errors? Also I think you'll need to exclude your new data test files from the rat plugin
https://github.com/apache/nifi/blob/main/nifi-nar-bundles/nifi-gcp-bundle/nifi-gcp-processors/pom.xml#L128

**Comment by harjitdotsingh** [comment]
@pvillard31 The checkStyle.xml file mentioned in the Developer guide doesn't work. Gives a parsing error when I try to add it to IntelliJ. I will  add try to run the checkstyle manually and see if I can see the errors. Looks my IDE reformated the code.  I have one from Accumulo project ? Will that work ?

**Comment by pvillard31** [comment]
You may be able to run the build directly from the gcp bundle `mvn clean install -Pcontrib-check`. You may need to do a full build first to make sure you have all the dependencies in your local Maven repo first, something like `mvn clean install -DskipTests`.

**Comment by harjitdotsingh** [comment]
@pvillard31 - Fixed the errors,  thanks for all your help :-)

**Comment by harjitdotsingh** [comment]
@pvillard31 - The  PR had merge issues with the main branch, hence resubmitting.

**Comment by exceptionfactory** [comment]
This PR also references the wrong Jira issue number (NIFI-8646), is there a different Jira issue for this PR?

**Comment by harjitdotsingh** [comment]
Its 8486.  I will fix the title

**Comment by harjitdotsingh** [comment]
@pvillard31 - How can we fix the commit message ?

**Pull request closed without merging**
