### PR TITLE
NIFI-4538 - Add Process Group information to...

### PR DESCRIPTION
**Pull request by yuri1969**
...Search results

* Separated the search functionality.
* Added a unit test.
* Added the PG info to UI (a mere draft).

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Comment by yuri1969** [comment]
The PG names/IDs display style improvements are welcomed.

Note: The `GET flow/search-results` API was changed.

**Comment by mcgilman** [comment]
@yuri1969 Unfortunately, we consider the REST API to be a public API so we cannot introduce breaking changes in non-major releases.

**Comment by yuri1969** [comment]
@mcgilman OK, I'll redesign the REST API change to a non-breaking one.

**Comment by mcgilman** [comment]
@yuri1969 There appears to be a merge conflict with this branch and the current state of master. I'll be unavailable for a couple days but should have some time to devote to this review later next week.

**Comment by yuri1969** [comment]
@mcgilman The merge conflict should be resolved now.

**Comment by mcgilman** [comment]
@yuri1969 Thanks! Will start reviewing...

**Comment by mcgilman** [comment]
@yuri1969 The introduction of the Parent group makes a lot of sense. However, I thought the idea of the Top level group was a little confusing. Technically, the Top level group is the Root group we just do not support navigating out of it. As an alternative, I wanted to suggest maybe changing that part to return the nearest versioned group (if applicable) that was just released in 1.5.0. This would be helpful in identifying which versioned flow the component exists in. 

Thoughts?

**Comment by yuri1969** [comment]
@mcgilman In my experience, the top level group information was not really as useful as the parent one. So I don't mind the change you proposed.

Anyway, @mattyb149 should be asked since he had created the original request.

**Comment by mattyb149** [comment]
@mcgilman 's suggestion makes sense to me and should prove useful in the search results.  Make it so! :)

**Comment by yuri1969** [comment]
@mcgilman Implementation of the nearest versioned group is done.

**Comment by mcgilman** [comment]
Thanks @yuri1969! This has been merged to master.

**Pull request closed without merging**
