### PR TITLE
NIFI-385 Add Kerberos support in nifi-kite-nar

### PR DESCRIPTION
**Pull request by WilliamNouet**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [Y] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [Y] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [Y] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [Y] Is your initial contribution a single, squashed commit?

### For code changes:
- [Y] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [Y] Have you written or updated unit tests to verify your changes?
- [N] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [N/A] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [N/A] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [N/A] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [N/A] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by trixpan** [comment]
@WilliamNouet this looks like a duplicated PR from the other one introducing Morphlines? If so, mind to close it?

**Comment by pvillard31** [comment]
@trixpan I believe there is indeed an effort to support Kerberos in Kite processors. I believe the two features (Kerberos and Morphlines) have been in both PRs. I know there is a real interest around this Kerberos support. Ideally, it'd be nice to update this PRs to only include Kerberos related changes. Could you do that @WilliamNouet ?

**Comment by trixpan** [comment]
Thanks for the heads up  @pvillard31

**Comment by WilliamNouet** [comment]
@pvillard31 Merci Pierre ! This was my first commit and I messed up since I merged from my master and not my NIFI-385 branch. Should I just close the pull request and reopen a new one to have it set up properly?

**Comment by jtstorck** [comment]
FYI, some issues have been noticed with Hadoop and Kerberos in the NiFi HDFS processors.  There's JIRA that I'm working on to fix a scenario where Kerberos principals end up getting switched between multiple processors.  It's due to the UserGroupInformation class being shared by two instances of processors from the same NAR.  The fix involves not depending on nifi-hadoop-libraries-nar, and including the hadoop-client dependency directly in the nifi-hdfs-processors pom.  

Once the Kite processors support Kerberos, they'll most likely have the same issue, and a similar change will have to be made to the POMs.

For reference, the JIRA is: https://issues.apache.org/jira/browse/NIFI-3520

**Comment by pvillard31** [comment]
Hey @WilliamNouet, sorry for the late answer. I'd try to update this one to keep track of the comments already posted by others. The perfect situation when opening a PR is to only have one commit with only the changes related to the associated JIRA. If you feel more comfortable with opening a new PR, please do so and close this one. Keep in mind the comment from @jtstorck though.

**Comment by WilliamNouet** [comment]
Closing this PR and opening a cleaner one at https://github.com/apache/nifi/pull/1565

**Pull request closed without merging**
