### PR TITLE
[NIFI-13245] address component name overflow in provenance details di…

### PR DESCRIPTION
**Pull request by scottyaslan**
…alog

### CODE REVIEW

**Comment by mcgilman** [comment]
Will review...

**Review by mcgilman — COMMENTED** [review]
Thanks for the PR @scottyaslan! Changes look good. The same issue exists in the Content tab of this same dialog. They are however much less likely to happen given the content.

**Comment by scottyaslan** [comment]
@mcgilman I have addressed your comments. Please have another review.

**Review by mcgilman — APPROVED** [review]
Thanks for the updates @scottyaslan!

**Pull request merged**
