### PR TITLE
NIFI-13557 Corrected regular expression for short months in order to allow for single digit months.

### PR DESCRIPTION
**Pull request by dan-s1**
# Summary

[NIFI-13557](https://issues.apache.org/jira/browse/NIFI-13557)
This fix corrects any 'Date Format' , 'Time Format' and 'Timestamp Format' (used in various record readers) to allow for reading single digit months. Before this fix whether a user specified  `MM` or `M` only double digit months could be read. That logic was incorrect as the underlying code uses  `java.time.format.DateTimeFormatter` and per the [DateTimeFormatter javadoc](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/time/format/DateTimeFormatter.html) specifying single digit month `M` should support both single and double digits.

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [x] Build completed using `mvn clean install -P contrib-check`
  - [x] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by exceptionfactory — APPROVED** [review]
Thanks @dan-s1, looks good! +1 merging

**Comment by dan-s1** [comment]
@exceptionfactory Thank you for merging this. Can this also be include in the 1.x branch? Please let me know if I should submit a separate PR. Thanks!

**Comment by exceptionfactory** [comment]
@dan-s1 I backported this change to the support branch. However, #9096 should not be backported because the change to use `DateTimeFormatter` is only on the main branch for NiFi 2.0.

**Comment by dan-s1** [comment]
@exceptionfactory Thank you for merging this to 1.x! Also thanks for pointing out about `DateTimeFormatter`. I had not realized it was only in 2.x.

**Pull request closed without merging**
