### PR TITLE
NIFI-569 Creating basis for integration-tests in build

### PR DESCRIPTION
**Pull request by apiri**
Introducing the maven-failsafe-plugin to the root pom.xml. Refactoring AWS integration level tests to make use of the IT* prefix and removing @Ignore from these classes.

### CODE REVIEW

**Comment by mcgilman** [comment]
Reviewing...

**Comment by mcgilman** [comment]
The build infrastructure changes look good. I realize the motivation for this ticket was establishing this baseline. However, I wanted to try to run the integration tests to verify they actually ran and everything looked good. The documentation for these integration tests states it requires additional configuration and resources/buckets. Should part of this effort be defining how integration tests relay required setup instructions?

**Comment by apiri** [comment]
Not opposed but not sure how to best accomplish this. A section in the dev or contrib guide talking about how to activate and or what is currently present seem reasonable? Agree that there should be some documentation to highlight the new profile at minimum. Other suggestions?

**Comment by mcgilman** [comment]
Highlighting the existence of the new profile is a good idea and we should do that. However, I was specifically referring to the AWS integration tests that are part of this PR. I wanted to be able to activate the new profile and make sure the integration tests ran and everything looked good. But the integration tests require some additional configuration and resources. However, it does not explain what those are or how to set them up. Do we want to try to document the dependencies a given integration test has so that other developers can run them as well?

**Comment by apiri** [comment]
Sorry went off on a tangent on the previous part. In favor of that but curious as to what the destination should be. Didn't do the integration test classes myself but can comb through and pull out the relevant pieces, just not sure where the documentation of such should live.

**Comment by mcgilman** [comment]
Yep, I realize this PR was just trying to establish the baseline and create the build infrastructure. I can certainly +1 that aspect. I was just wondering if this sort of thing warranted a best practice/convention. If the expectation is that only folks intimately familiar with a particular component will run the integration test than they likely don't need any additional documentation. I'm just trying to figure out what the expectation is.

I'm guessing that the integration tests will likely never be run from NiFi root since it could potentially require a lot external configuration and prep work.

**Comment by apiri** [comment]
Gotcha. There were some good suggestions on the related thread on the mailing list but there are limited classes that fall into this category at this time. Not necessarily sure that this PR will explicitly close the related issue, but could be a first step in the direction of fulfillment.

**Comment by mcgilman** [comment]
+1 Went ahead and merged the proposed changes for the build infrastructure. Specifics for this integration test can be updated as needed.

**Pull request closed without merging**
