### PR TITLE
NIFI-1993 upgraded CGLIB to 3.2.2

### PR DESCRIPTION
**Pull request by olegz**

### CODE REVIEW

**Comment by olegz** [comment]
NOTE to merger: This is 1.0.0 only since the reasons for the upgrade are related to Java 1.8

**Comment by mattyb149** [comment]
What's a good test? Successful build? Or something more?

**Comment by olegz** [comment]
@mattyb149 I got one better ;) Try PR https://github.com/apache/nifi/pull/515 as it stands now and then with this change. That is how it was discovered. I've attached some notes in JIRA. Let me know if you need more details.

**Comment by mattyb149** [comment]
+1 LGTM, tested #515 with and without this commit, verified the test fails without this commit. Merged to master

**Pull request closed without merging**
