### PR TITLE
NIFI-13963 Ensured unknown fields are not included in outputted schema for 1.x.

### PR DESCRIPTION
**Pull request by dan-s1**
# Summary

[NIFI-13963](https://issues.apache.org/jira/browse/NIFI-13963)

This is a back port of  the fix made in #9347 for 2.x.

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [x] Build completed using `mvn clean install -P contrib-check`
  - [x] JDK ~21~ 8

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Review by pvillard31 — COMMENTED** [review]
As said on the JIRA, this can be considered as a breaking change and, as such, I don't think this should be applied on 1.x. I'm no longer a user of the 1.x branch so I won't be a -1 but if this change is merged, I believe this should be made very explicit to users.

**Comment by exceptionfactory** [comment]
It seems worth correcting the behavior, but I question whether this is the right solution on the support branch. As @pvillard31, the default value of `nextRecord()` has remained unchanged, so it seems like we need a different solution for the support branch if this is to be corrected.

I'm not to the point of voting this down, but I'm leaning in that direction.

@dan-s1 or @mosermw, have you evaluated approaches other than this one to correct the behavior for the support branch?

**Comment by dan-s1** [comment]
@exceptionfactory I had an idea to limit the scope of this change to only `JsonTreeReader` and I would like to have your feedback. My idea is to keep @pvillard31 changes in JsonTreeRowRecordReader.java for trimming the schema but change lines 129-133
from 
```
@Override
    protected Record convertJsonNodeToRecord(final JsonNode jsonNode, final RecordSchema schema, final boolean coerceTypes, final boolean dropUnknownFields)
            throws IOException, MalformedRecordException {
        return convertJsonNodeToRecord(jsonNode, schema, coerceTypes, dropUnknownFields, null);
    }
```
to
```
@Override
    protected Record convertJsonNodeToRecord(final JsonNode jsonNode, final RecordSchema schema, final boolean coerceTypes, final boolean dropUnknownFields)
            throws IOException, MalformedRecordException {
        return convertJsonNodeToRecord(jsonNode, schema, coerceTypes, !this.schemaInferred || dropUnknownFields, null);
    }
```
where `schemaInferred` is a boolean calculated in `JsonTreeReader` in method `storePropertyValues` with
       ` this.schemaInferred = INFER_SCHEMA.getValue().equals(context.getProperty(SCHEMA_ACCESS_STRATEGY).getValue());`

and it is passed to `JsonTreeRowRecordReader` by expanding its constructor to take this flag.

This would thereby ensure whenever a schema is specified unknown fields are not kept.
Please let me know your thoughts.

**Comment by dan-s1** [comment]
Hmm this may not work as 3 tests in `TestJsonTreeRowRecordReader` whenever `reader.nextRecord(false, false)` is used are failing.

**Comment by dan-s1** [comment]
@pvillard31 In PR #9347 you had suggested

> If we agree on the above, then it may be easier to juste override nextRecord() in AbstractJsonRowRecordReader and default to nextRecord(true, true).

and both @exceptionfactory and @markap14 agreed to that change. How come instead of that the change was made to

`nifi-commons/nifi-record/src/main/java/org/apache/nifi/serialization/RecordReader.java` ?

```
default Record nextRecord() throws IOException, MalformedRecordException {
        return nextRecord(true, true);
    }
```

**Comment by dan-s1** [comment]
@exceptionfactory I limited the scope of the changes as the original suggestion in #9347 to `AbstractJsonRowRecordReader`

**Comment by exceptionfactory** [comment]
Thanks for evaluating different options @dan-s1, this is helpful.

I think limiting the scope of the `nextRecord()` changes to the `AbstractJsonRowRecordReader` could provide an optimal solution.

I will follow up again soon and look for additional input from @pvillard31 on this approach.

**Comment by dan-s1** [comment]
@exceptionfactory @pvillard31 I am following up on this PR to see if this fix can get into the 1.28.1 release as this is a fix my team needs. Thanks!

**Review by exceptionfactory — APPROVED** [review]
Thanks for making the adjustments @dan-s1, the latest change scoping `nextRecord(true, true)` to the `AbstractJsonRowRecordReader` looks like a good approach. +1 merging to the support 1.x and 1.28 branches.

**Pull request merged**
