### PR TITLE
NIFI-5370 Resolve wildcard certificate issue in secure cluster

### PR DESCRIPTION
**Pull request by alopresto**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [ ] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by alopresto** [comment]
This PR is not ready for review yet. I opened it because some unrelated tests were failing locally and I wanted to see the Travis CI results.

**Comment by alopresto** [comment]
Travis succeeded on #9706.1 (EN) and #9706.3 (JP) but failed on #9706.2 (FR). This means the failing unit tests are not related to this build.

**Comment by alopresto** [comment]
This is now ready for review. Ignore the whitespace only changes on `AbstractNodeProtocolSender`.

**Comment by alopresto** [comment]
This PR is to resolve the user-reported issue in [NIFI-5370](https://issues.apache.org/jira/browse/NIFI-5370) where a secure cluster with nodes using wildcard certificates would not allow UI login. The issue was because the introduced `NiFiHostnameVerifier` did not evaluate wildcard entries properly. This patch fixes the immediate issue. 

**However**, wildcard certificates are not officially supported and are **not recommended** for use in a secure cluster environment. There are numerous disadvantages to using wildcard certificates, they have been actively discouraged in the past, and have worked to this point only out of luck. The Admin Guide will be updated to state this explicitly [NIFI-5399](https://issues.apache.org/jira/browse/NIFI-5399). 

Disadvantages of wildcard certificates for cluster:
* we use certificate identities many times throughout the codebase to identify a node, and if the certificate simply presents a wildcard DN, that doesn’t resolve to anything (see [NIFI-5398](https://issues.apache.org/jira/browse/NIFI-5398))
* you need to provide a custom node identity in your `authorizers.xml` for `*.whatever.com` because all proxy actions only resolve to the cert DN
* no traceability into which node performed an action because they all resolve to the same DN
* if you’re running multiple instances on the same machine using different ports to identify them, and you accidentally put `node1` hostname with `node2` port, it will resolve fine because it’s using the same certificate, but the host header handler will block it because the `node1` hostname is not listed as an acceptable `host` for `node2` instance (correctly)
* if the cert is compromised, all nodes are compromised

Advantages of wildcard certificates for cluster:
* nominally faster to deploy in dynamically-scaled clusters, however the NiFi TLS Toolkit automates the process of generating correctly-signed, uniquely-identified certificates in the proper format. The deployment script or process for adding a node should leverage this tool rather than use a repeated wildcard certificate. Using a wildcard in the SAN is fine as long as a unique value exists in the SAN as well.

**Comment by markap14** [comment]
@alopresto Thanks. The code change makes sense. Was able to verify behavior. I definitely agree with your assessment above for the pros and cons of wildcard certs. +1 merged to master

**Pull request closed without merging**
