### PR TITLE
NIFI-12384 Upgrade Registry to Spring Framework 6

### PR DESCRIPTION
**Pull request by exceptionfactory**
# Summary

[NIFI-12384](https://issues.apache.org/jira/browse/NIFI-12384) Upgrades NiFi Registry from Spring Framework 5 to 6.0.13 along with supporting libraries.

The majority of the changes involve replacing `javax` with `jakarta` in package names to align with major version changes in the Servlet API, JAX RS API, and related programming interfaces.

Related changes include upgrading the NiFi Toolkit CLI to the same JAX RS and Jersey versions as Registry to align with packaging requirements from shared dependencies.

NiFi Registry changes include adjusting the Spring Security configuration to align with Spring Security 6, and removing the test Jetty Server Customizer that is no longer required for integration tests.

These changes are scoped to NiFi Registry using properties in the `nifi-registry` root module, leaving the remaining of the repository on the earlier versions of these libraries.

Upgraded libraries for Registry include the following:

- Upgraded Spring from 5.3.30 to 6.0.13
- Upgraded Spring Boot from 2.7.16 to 3.1.5
- Upgraded Spring Security from 5.8.7 to 6.1.5
- Upgraded Jetty from 10.0.18 to 11.0.18
- Upgraded Servlet API from 3.1.0 to 5.0.0
- Upgraded JAX-RS from 2.1.1 to 3.1.0
- Upgraded Jersey from 2.41 to 3.1.3
- Upgraded JAXB from 2.3.2 to 4.0.4
- Upgraded Java Validation from 2.0.1 to 3.0.2
- Upgraded Flyway from 8.5.13 to 9.22.3
- Upgraded ASM from 9.3 to 9.6 for Java 21

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X] Pull Request based on current revision of the `main` branch
- [X] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [X] Build completed using `mvn clean install -P contrib-check`
  - [X] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

### CODE REVIEW

**Comment by joewitt** [comment]
Full clean build with contrib all tests AND integration tests checks out.

However when attempting to connect nifi with the registry plain unsecured connection.  I attempt to version control a group and receive in the nifi-user.log

`2023-11-17 08:10:24,371 ERROR [NiFi Web Server-55] o.a.nifi.web.api.config.ThrowableMapper An unexpected error has occurred: java.lang.RuntimeException: java.lang.ClassNotFoundException: Provider for jakarta.ws.rs.client.ClientBuilder cann
ot be found. Returning Internal Server Error response.
java.lang.RuntimeException: java.lang.ClassNotFoundException: Provider for jakarta.ws.rs.client.ClientBuilder cannot be found
        at jakarta.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:75)
        at org.apache.nifi.registry.client.impl.JerseyNiFiRegistryClient.<init>(JerseyNiFiRegistryClient.java:100)
        at org.apache.nifi.registry.client.impl.JerseyNiFiRegistryClient$Builder.build(JerseyNiFiRegistryClient.java:275)
        at org.apache.nifi.registry.flow.NifiRegistryFlowRegistryClient.getRegistryClient(NifiRegistryFlowRegistryClient.java:90)`

**Comment by exceptionfactory** [comment]
> Full clean build with contrib all tests AND integration tests checks out.
> 
> However when attempting to connect nifi with the registry plain unsecured connection. I attempt to version control a group and receive in the nifi-user.log

Thanks for catching this issue with the Registry client @joewitt. The problem appears to the the Jersey client version packaged in NiFi versus the one applied to the Registry client library as part of the upgraded dependencies. I will take a closer look and follow up.

**Comment by exceptionfactory** [comment]
Thanks again for catching the Registry Client issue @joewitt. I pushed an update that sets the updated Jersey and JAX-RS library versions in the Flow Registry Client Service NAR, aligning with the versions set in the `nifi-registry` parent module. This resolves the runtime issue by packaging the matching versions of Jersey and JAX-RS in `nifi-flow-registry-client-nar`.

**Review by pvillard31 — APPROVED** [review]

**Comment by pvillard31** [comment]
Full build, running NiFi and NiFi Registry secured, I was able to interact with the NiFi Registry instance to version flows, checkout versions, etc. I'm a +1. @joewitt - do you want to give it another try?

**Comment by joewitt** [comment]
@pvillard31 No worries I'm good with your +1

**Pull request closed without merging**
