### PR TITLE
NIFI-2640 Fixed Windows encrypt-config.bat script

### PR DESCRIPTION
**Pull request by alopresto**
The Apache repo hasn't synced with GitHub yet, so [PR 834](https://github.com/apache/nifi/pull/834) still shows as open, and this PR includes the [`c638191`](https://github.com/apache/nifi/commit/c638191a47ae5767de82b383ecb04496ce18877b) commit which will close it. I'll update this PR after Apache syncs.

### CODE REVIEW

**Comment by JPercivall** [comment]
Hey @alopresto, when building the encrypt toolkit on Windows I get a number of test failures. Since this PR is specifically about encrypt toolkit, could you address them here?
 
[testOutput.txt](https://github.com/apache/nifi/files/434933/testOutput.txt)

**Comment by alopresto** [comment]
@jpercivall it looks like the errors are of two flavors:
* setPosixFilePermissions() apparently does not work on Windows systems. I will add the equivalent file permission modification code to be compatible (but I can't test, as I don't have a Windows system available, so please verify after the next push). 
* your Windows date output format uses an offset time zone (`GMT-0500`) as opposed to the *nix  format (`PST`). I'll adjust the regex to handle this. 

Thanks for finding these.

**Comment by JPercivall** [comment]
@alopresto that fixed some of the issues but not all. Here is the latest:

[testOutput_2.txt](https://github.com/apache/nifi/files/435275/testOutput_2.txt)

**Comment by JPercivall** [comment]
+1

Visually verified code and ran a contrib check build on Windows 8. Observed that the bat script runs as expected on Windows. Thanks @alopresto, I will squash and merge it in.

**Pull request closed without merging**
